### ISSUE TITLE
Cant host this project on Codeanywhere.com / MultiOgar Works There But Why This Project dont?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#10]
![image](https://cloud.githubusercontent.com/assets/20871314/20036624/a8dc6514-a447-11e6-93a0-f4eafad3ceb4.png)
Help!

**Comment by Fantasy-Agario** [comment]
### cd into src  
then do sudo node index.js

**Comment by NameYT** [comment]
@Fantasy-Agario I already did it But I tried sudo node index.js and that's the error that came up

**Comment by NameYT** [comment]
i did cd MultiOgar-Edited/src

**Comment by Fantasy-Agario** [comment]
no just do cd src

**Comment by Fantasy-Agario** [comment]
# Not cd MultiOgar-Edited/src

**Comment by NameYT** [comment]
k

**Comment by NameYT** [comment]
![image](https://cloud.githubusercontent.com/assets/20871314/20036749/e4aee4b4-a44b-11e6-8478-ade30482aaec.png)
Dont work :( @Fantasy-Agario

**Comment by Megabyte918** [comment]
This is not our problem. It's a problem with codeanywhere.

**Comment by NameYT** [comment]
@Megabyte918 Oh okay but can you copy the code that was made so we can get a popsplit always success? Just copy the code i really messed up on the server config so i have to install again :(

**Comment by Fantasy-Agario** [comment]
Well ,just install it again :) @NameYT

**Comment by NameYT** [comment]
@Fantasy-Agario Do you know how to get a popsplit awlays success full no fail srry for bad englsih

**Comment by Fantasy-Agario** [comment]
Yes , have one person/minion or bot (Needs to be roughly half the size Example : Player1 = 3000 mass Player2 = 1500 mass) near a virus , then double split

**Comment by NameYT** [comment]
@Fantasy-Agario By Changing a settings :)

**Comment by Fantasy-Agario** [comment]
I'll play around with them just give me 2 mins :D

**Comment by NameYT** [comment]
@Fantasy-Agario Changing Gameserver.js and PlayerCell.js @Megabyte918 Know that but he wont give me the code :p so i can just paste it

**Comment by Fantasy-Agario** [comment]
Ok , i can't exactly give u perfect popsplits but i can start work on a feature that allows you to get popsplits right more often :) @NameYT

**Comment by NameYT** [comment]
@Fantasy-Agario Okay Thanks where is it then lol xD

**Comment by Fantasy-Agario** [comment]
I said : 

# "i can start work"

**Comment by NameYT** [comment]
@Fantasy-Agario **Okay contact me If its done xD**

**Comment by Fantasy-Agario** [comment]
Ok , it might take a while as I'm currently working on My version of Ogar [()](https://github.com/FantasyArts/Ogar-Remastered)

**Comment by NameYT** [comment]
@Fantasy-Agario The Popsplit will never fail?

**Comment by NameYT** [comment]
@Fantasy-Agario https://github.com/Barbosik/MultiOgar/issues/333 This is what im talking about :p @Megabyte918  Made somjething in the comments

**Comment by Fantasy-Agario** [comment]
Not never as that will cause some bugs in splitting and viruses , but it will definitely increase the chance :D

**Comment by NameYT** [comment]
@Megabyte918 Its not working i tried all your code but sometimes it still fail

**Comment by Fantasy-Agario** [comment]
You might just have to start training ur popsplits m8 XD

**Comment by NameYT** [comment]
@Fantasy-Agario Already started M8

**Comment by Fantasy-Agario** [comment]
You gotta : 
# Eat Sleep n Shit Popsplits - Jinx 2015

**Comment by NameYT** [comment]
http://agar.io/?ip=sambyonweed-samby6667851.codeanyapp.com:3000 @Fantasy-Agario Try Joining

**Comment by Fantasy-Agario** [comment]
I'm in

**Comment by NameYT** [comment]
@Fantasy-Agario Pro lol xD

**Comment by Fantasy-Agario** [comment]
Ikr :D

**Comment by NameYT** [comment]
@Fantasy-Agario SEND ME THE DOWNLOAD LINK IF YOUR DONE on my skype or something : Skype : Gian Sambayan

**Comment by Megabyte918** [comment]
@Fantasy-Agario replace all of the code in your Virus.js to this one: http://pastebin.com/XkfXNmtE
To change the success of popsplits, you need to edit the "mult" variable. The value of mult on lines **54** and **57** is what you need to edit. I'm not sure which values exactly give 100% working popsplits though, that you will need to figure out for yourself. Experiment with those numbers until you have found the best fit for what you want popsplits to be like.

**WARNING:** editing the virus explosion multiplier (mult) drastically effect the way virus explosions look/happen. Increasing it too much can break virus explosions, and decreasing it too much can lead to bugs/glitches with playercells, or in extreme cases, the server can actually crashes on impact with a virus, so you need to be very careful. The current multiplier settings in this project are vanilla which give vanilla success rates, editing it WILL impact that alot, so if your willing to lose vanilla virus explosions and success rates then by all means, continue.

**Comment by NameYT** [comment]
@Megabyte918 I Edited it but where can i find the mult?

**Comment by Megabyte918** [comment]
@NameYT Please read my entire comment before asking a question

> The value of mult on lines 54 and 57 is what you need to edit.

**Comment by Megabyte918** [comment]
@NameYT https://streamable.com/doat 
is that clear enough for you? lol

**Comment by NameYT** [comment]
@Fantasy-Agario The Mult i tried 0 but crashed lol gimmeeeeeeeeeeeeee the number for perfect i tried it

**Comment by Megabyte918** [comment]
@NameYT 

> Increasing it too much can break virus explosions, and decreasing it too much can lead to bugs/glitches with playercells, or in extreme cases, the server can actually crash on impact with a virus, so you need to be very careful

**Comment by mrdabbit** [comment]
@NameYT You should `sudo bash` and then `cd src` and THEN `node index.js`
