### ISSUE TITLE
LMS!

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#104]
this happen when i set gamemode to 4 LMS
![image](https://cloud.githubusercontent.com/assets/17459204/20631085/a3d92016-b356-11e6-88fe-1f92d9639993.png)
![Uploading Failed...]()

**Comment by CalvinDKL** [comment]
Same, i dont think he is done.

**Comment by Fantasy-Agario** [comment]
Its still beta @PrinceDark9243 @CalvinDKL

**Comment by Megabyte918** [comment]
@PrinceDark9243 It looks fine for me, what exactly is wrong there?

**Comment by Gimmo** [comment]
Mass

**Comment by Megabyte918** [comment]
I'm going to close this...
