### ISSUE TITLE
Make Bots More Smarter!!

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#107]
Make them more smarter!

- **[Teaming with Each Other
- Farming Viruses
- Know how to tricksplit
- avoiding being `killed]**`

**Comment by Jhair2015** [comment]
@NameYT  It would kill the memory: /

**Comment by Tyler3D** [comment]
I've seen bots do all of these

**Comment by Fantasy-Agario** [comment]
@NameYT While having bots be smarter is a good thing , but like @Jhair2015 said it would make it more laggy

**Comment by NameYT** [comment]
@Fantasy-Agario Then i just increase the server

**Comment by Fantasy-Agario** [comment]
Do u mean the server RAM ?

**Comment by NameYT** [comment]
@Fantasy-Agario By doing the command thiggy

**Comment by Fantasy-Agario** [comment]
Which command

**Comment by NameYT** [comment]
node --max-old-space-size=6144 index.js (memory is in mb)

**Comment by NameYT** [comment]
do it on the command prompt folder

**Comment by NameYT** [comment]
Also add pellet mode i've been waiting for that Minion Feauture for a long time i think it would be my christmas present :)

**Comment by Fantasy-Agario** [comment]
Yes pellet mode would be a good feature but it would require a compatible client or at least a script

**Comment by NameYT** [comment]
There is a script :) For Controls ERT maybe they can add it :)

**Comment by NameYT** [comment]
Also Pellet Mode Is Helpful so they dont need to type or change the minionMaxStartSize like that

**Comment by Fantasy-Agario** [comment]
True i'll work on that :D

**Comment by NameYT** [comment]
![image](https://cloud.githubusercontent.com/assets/20871314/20646909/9c45da36-b4c0-11e6-94ef-513d17abec1e.png)
Lol look what im doing :3

**Comment by Fantasy-Agario** [comment]
Ill close this as it is duplicated

**Comment by NameYT** [comment]
Sure :)

**Comment by NameYT** [comment]
How bout the Smarter Bots?

**Comment by Fantasy-Agario** [comment]
Hmm , ill see i need to ask Megabyte first tho :)

**Comment by Megabyte918** [comment]
#27
