### ISSUE TITLE
Add </random> Bot Skins That Might Be Usefull and fun

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#11]
Like OgarUL they have </random> skins with bots maybe that's usefull?

**Comment by Fantasy-Agario** [comment]
Ok , i'll try to do that :D

**Comment by AlexandriteErikParacelsus** [comment]
@Fantasy-Agario good luck

**Comment by Megabyte918** [comment]
I can't do it :/
4 hours of trying to implement this, fix after fix, bug after bug, error after error, it never worked. No matter what I tried. Who knew something as simple as having the skins be selected randomly from 1 file with a list of them like botnames.txt, could be so difficult :/
I tried, If you want to continue working on it @Fantasy-Agario, then by all means continue.
@NameYT I'm going to close this for now.
