### ISSUE TITLE
How to make a cmd

### ISSUE THREAD

**Issue by Lukkez** [Megabyte918/MultiOgar-Edited#111]
I wanted to make a command called /id for the chat(using Cigar) to get the ID of the player someone can send the code of the function to get the player ip?

**Comment by Fantasy-Agario** [comment]
hmm , you could do this yourself , becouse i don't think this should be an official feature , unless @Megabyte918 decides otherwise :D

**Comment by Lukkez** [comment]
I do not want this to be official feature, it's because I can't find the code

**Comment by Megabyte918** [comment]
@Lukkez You asking how to add a command to Cigar here?

**Comment by Fantasy-Agario** [comment]
@Megabyte918 Hey , we haven't talked for a while , I can't help with the Multi-Ogar Edited today as I only have my phone , but as I can tomorrow 🙂

I hope things are going good for u buddy , I'll give u more detail later why I was away 🙂

**Comment by Megabyte918** [comment]
@Fantasy-Agario Its alright, thanks and I hope to see you soon :)

**Comment by Fantasy-Agario** [comment]
Hope to see ya soon too :D

**Comment by Lukkez** [comment]
![](http://image.prntscr.com/image/f6d2d18aad7241fa881f87ba81f1c00f.png)

**Comment by Lukkez** [comment]
How?

**Comment by Megabyte918** [comment]
@Lukkez to get a player's id by using the `this.pID` variable in PlayerTracker. Or if you would like the opposite, see the `playerById` function in CommandList
