### ISSUE TITLE
Question on Server structure

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#112]
Where can I found object, containing all user IDs along with their mass/size/coordinates and maybe some optional data?
I want to to play with store/restore this for possible server crash/restart, sharing for scaling and so on . 
Thanks.

**Comment by Fantasy-Agario** [comment]
Hmm , do 
> playerlist 
and u get the ID's

**Comment by Fantasy-Agario** [comment]
For the rest we could introduce a new feature :)

**Comment by Gimmo** [comment]
The game itself should have memoty block, containing this info, without any prosthetic limbs. Am I wrong?

**Comment by ZfsrGhS953** [comment]
Yes, it's called "this.gameServer.clients"

**Comment by Gimmo** [comment]
Thank you. This is exactly what I had in mind.
