### ISSUE TITLE
Question for everyone

### ISSUE THREAD

**Issue by Megabyte918** [Megabyte918/MultiOgar-Edited#114]
Hello everybody! I have a question to ask regarding minion controls. Which does everyone prefer? I'm contemplating getting rid of the Q controls and only leave the ERT controls, but I'm not sure if you guys will still want them or not.

I need everyone to vote on which will stay, ERT or Q. I have created a strawpoll so that you guys can vote.
**Remember, you can only vote once!** So be honest and choose wisely.
Vote here: http://www.strawpoll.me/11756853

# Q controls
Pros:
- Easier to distinguish which control mode you are in
- Easy to use for people who use Q alot
- You don't have to install tampermonkey + the script to use it
- Controls supported on every client

Cons:
- The extra code in PacketHandler for Q decreases performance
- You cannot freeze minions because thats reserved for T
- Difficult to get used to at first

# E, R, and T controls
Pros:
- Very easy to use once you've gotten used to it
- Easy to distinguish which control mode you are in
- You can freeze minions by using T

Cons:
- You have to install tampermonkey aswell as the script to use them
- Some clients do not support E, R, and T keys, so use is limited

**Comment by Jhair2015** [comment]
E - R - T - I VOTE!

**Comment by Gimmo** [comment]
What are we talking about? It's a client feature.!!!  That's why I vote E - R - T 
Performance most of all!

**Comment by AlexandriteErikParacelsus** [comment]
Just leave it as it is

**Comment by Fantasy-Agario** [comment]
i agree with @AlexandriteErikParacelsus  leave it as it is :)

**Comment by Megabyte918** [comment]
I have found a compromise.
