### ISSUE TITLE
help:::....

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#1140]
ik this is a dup but i cant find any tp command in commits can some one send me the code so i chat i cann do /tp id mouse curcor and can i also have spawn /vires id mouse curcor and /board command in chat to XD pls dont kick me on this im t sure if this is issue

**Comment by AlexHGaming** [comment]
Stop duplicating.
You've said the exact issue twice.

**Comment by plazo123** [comment]
@AlexHGaming fantaticbay closed it without paying attetion cause some id**t open about 300 issues so fantastic bay closed all without paying attention and closed mine aswell

**Comment by FantasyIsBae** [comment]
@plazo123 oh sorry 😃

**Comment by plazo123** [comment]
@FantasyIsBae fastest reply everXD

**Comment by FantasyIsBae** [comment]
@plazo123 Ikr xd

**Comment by chewydev** [comment]
So you want to teleport and spawn viruses at the position of the mouse cursor? I'm sure there is a way to find the coordinates on the map relative to the mouse cursor, and teleport there, i'll have to look into it.

**Comment by plazo123** [comment]
@chewydev i have the /tp but i cant do /tp player id mouse i can do /tp curcor

**Comment by Megabyte918** [comment]
@plazo123 I made it a playercommand. Do `/tp [ID] mouse` to teleport the player to your mouse's coordinates and `/tp [ID] [X] [Y]` for regular coordinates.
```js
    tp: function (args) {
        var id = parseInt(args[1]);
        if (isNaN(id)) {
            this.writeLine("Please specify a valid player ID!");
            return;
        }

        var pos = {
            x: parseInt(args[2]),
            y: parseInt(args[3])
        };
        if (args[2] == 'mouse') {
            var pos = {
                x: this.playerTracker.mouse.x,
                y: this.playerTracker.mouse.y
            }
        }
        if (args[2] != 'mouse' && isNaN(args[2]) && isNaN(args[3])) {
            this.writeLine("Invalid coordinates");
            return;
        }

        for (var i = 0; i < this.gameServer.nodesPlayer.length; i++) {
            var check = this.gameServer.nodesPlayer[i];
            if (check.owner.pID == id) {
                if (!check.owner.cells.length) {
                    this.writeLine("That player is either dead or not playing!");
                    return;
                }
                check.position.x = pos.x;
                check.position.y = pos.y;
            }   
        }
        this.writeLine("Teleported " + check.owner._name + " to coordinates")
    },
```

**Comment by Wair1o17** [comment]
Hi @Megabyte918, could you help me solve split double in MultihOgar 1.2.69 [Original]? I'm trying to solve that for several days ...

**Comment by Megabyte918** [comment]
@Wair1o17 Rewrite the collision/move engine
