### ISSUE TITLE
[HELP] this.tickCounter is not a function??

### ISSUE THREAD

**Issue by FlagOfTheObby** [Megabyte918/MultiOgar-Edited#1141]
Hello, I tried to add pushsplits into GameServer.js 
var tick = this.tickCounter();
    if (!maxCell.canEat(minCell) || minCell.getAge(tick) < 14) 
    {
        // maxCell don't want to eat
        return;
    }

and it says this.tickCounter is not a function. My friend, (creator of Germs.io) added pushsplits and he told me that, that code would work and it's not. ???

**Comment by AlexHGaming** [comment]
@FlagOfTheObby Where are you adding this code?

**Comment by AlexHGaming** [comment]
Also you need to define maxCell, and others that need defining.

**Comment by FantasyIsBae** [comment]
@FlagOfTheObby Remove the parentheses (the "()") from  this.tickCounter();

**Comment by AlexHGaming** [comment]
Please define these words and put where the code is lying in. If you do then it would be much appreciated :D

**Comment by FantasyIsBae** [comment]
😄 

```JS
var tick = this.tickCounter;
if (!maxCell.canEat(minCell) || minCell.getAge(tick) < 14)
{
// maxCell don't want to eat
return;
}
```

@FlagOfTheObby

**Comment by FlagOfTheObby** [comment]
Thanks :) @AlexHGaming I'm adding it to GameServer.js at GameServer.prototype.resolveCollision

**Comment by FlagOfTheObby** [comment]
I'm putting it on GameServer.js at GameServer.prototype.resolveCollision (at the end of it).

**Comment by Megabyte918** [comment]
@FlagOfTheObby That code was made for the original MultiOgar. So I doubt the code would work if it was converted and put inside the current GameServer.js. But here you go if you want to try anyway:
```js
if (!check.canEat(cell) || cell.getAge() < 14) {
    // check doesn't want to eat
    return;
}
```
