### ISSUE TITLE
Question:  // update viewbox

### ISSUE THREAD

**Issue by Gamedevolop** [Megabyte918/MultiOgar-Edited#1142]
Hi Everyone, I would like to know, please

What is exactly the job of  // update viewbox? 

is it to calculate the (scale) in combination with getScale function??

Are they both working together to get the right viewport when the player grows up or splits??

Thank you very much in advance,

**Comment by chewydev** [comment]
I think its purpose is to adjust the field of view for the player, or the limit of how much the client can render.

**Comment by Gamedevolop** [comment]
@chewydev Thanks for your response I really appreciated, just to make sure I understood correctly, do you think is the code responsible for expanding the view port, example: every time I split the view port expands and you can see more of the map, like in this video:
[https://www.dropbox.com/s/787isdv7f90fp17/split%20video%20scale.mp4?dl=0](url)

so Imagen that everytime I split I would like to expand the view port three times bigger than the original size that it shows in the video, will  // update viewbox the right place to change the code to do that?

I forgot to say that this video it uses (MultiOgar-Edited server + Cigar as a client)

**Comment by Megabyte918** [comment]
@Gamedevolop You can increase the viewbox size from that function, but i'm not so sure about the "expand 3x bigger everytime you split".

**Comment by Gamedevolop** [comment]
@Megabyte918 
ok cool thanks a lot, I will have to keep trying changing things and values until I find the right place to change that view for the split, I thought it should be done from (PlayerTracker.prototype.getScale = function()), but after I tried many times changing values there is not doing it.
