### ISSUE TITLE
What is?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#1144]
What is 'agitated' ?

**Comment by AlexHGaming** [comment]
Ever tried using google?
And how is this even an issue?

**Comment by cowpits** [comment]
AlexHGaming response is perfect example of agitated. lol

**Comment by chewydev** [comment]
I think you're referring to a client sided variable for cells, stating if they have eaten a pellet, player, or have been eaten. This also takes affect for overlapping other entities. This is used in Cigar.

**Comment by AlexHGaming** [comment]
It makes everything jiggle.

**Comment by Megabyte918** [comment]
`this.isAgitated = false; // If true, then this cell has waves on it's outline`

**Comment by AlexHGaming** [comment]
> If true, then this `cell has waves on it's outline`
