### ISSUE TITLE
pID

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#1147]
what change in PlayerCommand.js  -   this.playerTracker.pID       to show the id of other player

**Comment by AlexHGaming** [comment]
You want it so it shows their ID on their name of the cell?

**Comment by AlexHGaming** [comment]
Please translate it with better grammar, i don't understand :P

**Comment by gyeyoqu** [comment]
Nice english like me XD.

You want a command to get id of others players?, you can write the id of players in the name of chat, or you can get with this name

**Comment by imnotNxhz1** [comment]
yes @gyeyoqu  i  want a command to get id of others players xD    example,  If put the mouse in any player, and write /id get a writeLine with the id of the  player

**Comment by Wair1o17** [comment]
I think that is client sided

**Comment by gyeyoqu** [comment]
@Wair1o17  not client side XD

**Comment by gyeyoqu** [comment]
@imnotNxhz1 You can not do that with canvas, since canvas does not interact with objects, it also requires client and server modifications.

You can use pixijs instead

**Comment by fayizan** [comment]
@gyeyoqu seems he will quit

**Comment by Megabyte918** [comment]
@imnotNxhz1
```js
id: function (args) {
    for (var i = 0; i < this.gameServer.nodesPlayer.length; i++) {
        var check = this.gameServer.nodesPlayer[i];
        var d = this.playerTracker.mouse.clone().sub(check.position);
        if (d.sqDist() <= check.size)
            this.writeLine("The pID of the person you're pointing at is " + check.owner.pID)
    }
},
```

**Comment by AlexHGaming** [comment]
Can't you just put 'playerlist' or 'pl' ? xD
