### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by FantasyIsBae** [Megabyte918/MultiOgar-Edited#1153]
>## __**Announcement**__
Me and @AlexHGaming have created a discord community dedicated to coding!
If you would like to ask any questions related to this project (**Or anything else**) , or questions you deem to be unrelated , we'll be happy to help.

>># Join *Dev Nation*

>[Invite](https://discord.gg/2Ct9TkX) (Never expires)

**Comment by AlexHGaming** [comment]
swag

**Comment by AlexHGaming** [comment]
"anouncement"
"happpy"
# Great fucking spelling

**Comment by FantasyIsBae** [comment]
Sorry grammar nazi 😂

**Comment by AlexHGaming** [comment]
🎉
