### ISSUE TITLE
Cannot connect the server to agar.io

### ISSUE THREAD

**Issue by ElPigianerJone** [Megabyte918/MultiOgar-Edited#1155]
the server is not working now
![image](https://user-images.githubusercontent.com/19348870/28622588-461df6c4-723f-11e7-878c-174e354c89ea.png)

**Comment by AlexHGaming** [comment]
I see you have an extension active. Disable your extension and try again.

**Comment by AlexHGaming** [comment]
I pull requested this issue. Fix is in #1156
