### ISSUE TITLE
New agar.io client update

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#1157]
you guys know what to do with the new client update. 
PacketHandler.js
if (this.handshakeProtocol < 1 || this.handshakeProtocol > 13)
change to 15 
but leaderboard not working.

**Comment by cowpits** [comment]
ok not trying to spam but i was able to get leaderboard to work on my server. 
UpdateLeaderboard.js
line 101:  writer.writeUInt8(0x33); // Packet ID 
change to:  writer.writeUInt8(0x35); // Packet ID

**Comment by cowpits** [comment]
UpdateLeadboard.js
or add this after the closing brace on line 152 }; 
I guess it keeps backwards compatibility. 

// FFA protocol 15
UpdateLeaderboard.prototype.buildFfa13 = function () {
    var writer = new BinaryWriter();
    writer.writeUInt8(0x35);                                 // Packet ID
    for (var i = 0; i < this.leaderboardCount; i++) {
        var item = this.leaderboard[i];
        if (item == null) return null;  // bad leaderboardm just don't send it

        if (item === this.playerTracker) {
        	writer.writeUInt8(0x09);
        	writer.writeUInt16(1);
        } else {
        var name = item._name;
        writer.writeUInt8(0x02);
        if (name != null && name.length)
            writer.writeStringZeroUtf8(name);
        else
            writer.writeUInt8(0);
    }
}
    var thing = this.leaderboard.indexOf(this.playerTracker) + 1;
    var place = (thing <= 10) ? null : thing;

    if (this.playerTracker.cells.length && place != null) {
        writer.writeUInt8(0x09);
        writer.writeUInt16(place);
    }
    return writer.toBuffer();
};

**Comment by AlexHGaming** [comment]
@cowpits Well I PR'ed the protocol bit, not the leaderboard bit tho :-)

**Comment by AlexHGaming** [comment]
Make a PR on this.

**Comment by cowpits** [comment]
PR = pull request? it's ok you can if you want to or if you don't mind.

**Comment by AlexHGaming** [comment]
@cowpits You do it, I don't understand what ur sayin so u do it and it will be extremely helpful :)

> or add this after the closing brace on line 152 };

dat bit confused meh

**Comment by cowpits** [comment]
lol i know you're pulling my leg. 
i'll do the pull request tonight, even though i've never done one before but i'll give it a shot.

**Comment by fayizan** [comment]
lemme do the pr on behalf of @cowpits

**Comment by cowpits** [comment]
correct, i didn't look at the other gamemodes because i don't use them lol

**Comment by proxiemind** [comment]
Hi, PR created, many thanks @cowpits for decoding the packet. I've put proper credit everywhere.

**Comment by NuclearC** [comment]
damn im late.

**Comment by AlexHGaming** [comment]
XD
