### ISSUE TITLE
Spawn minion's

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1161]
Hi!

How to make minions started to spawn only when the player plays? Just minions in normal. do not take nickname of player (serverMinions), but if he's going to play and refresh the minions, they take the nickname of the player. I hope I clearly described the situation, because I use translator:D
My game: http://agarix.xyz/ 
Mode: Bots

**Comment by Megabyte918** [comment]
@TopoR1 In PlayerTracker.js, replace [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L134) line with this:
```js
PlayerTracker.prototype.joinGame = function(name, skin, isMi) {
```
Then replace [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L170) with this one:
```js
if (!this.isMi || isMi)
    this.gameServer.gameMode.onPlayerSpawn(this.gameServer, this);
```

And in MinionPlayer.js, replace [these](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/MinionPlayer.js#L20-L23) lines with this:
```js
if (this.owner.cells.length) {
    this.joinGame(this.owner._name, this.owner._skin, true)
    if (!this.cells.length) this.socket.close();
}
```
That should make sure the player's minions will only spawn if their owner is in-game, and if so, spawn them with their owners name and skin.

**Comment by TopoR1** [comment]
@Megabyte918 thanks you!
