### ISSUE TITLE
Automedica minions userrole:admin and 5 of the Protocol

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1162]
Hi!

How to make Userrole:ADMIN issued 50 minions when logging in to the account? And that is not convenient via the server to add to his minions and would like to see the number of minions were given at the entrance itself. I tried to do, but all the time crash the server:(

And one more question how to forbid connection via 5 protocol?

**Comment by cowpits** [comment]
you want to add minions through chat when login admin? without having to do /minion 50?

**Comment by TopoR1** [comment]
@cowpits yes

**Comment by MastaCoder** [comment]
If protocol 5, return and don't respond to connection.

No support is provided for custom code.

**Comment by Megabyte918** [comment]
@TopoR1 Add this code in the `checkConnection` function of PlayerTracker.js:
```js
if (this.socket.packetHandler.protocol == 5) {
    while (this.cells.length) 
        this.gameServer.removeNode(this.cells[0]);
    this.socket.close(1000, "Protocol not allowed");
}
```

**Comment by TopoR1** [comment]
@Megabyte918 Thank you very much, that helped, thought not answer:)
