### ISSUE TITLE
how to make

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#1163]
how to make collide before 13 ticks

**Comment by AlexHGaming** [comment]
@gyeyoqu CTRL + F is your friend.

**Comment by fayizan** [comment]
I wanna know this too : )

**Comment by ZfsrGhS953** [comment]
@gyeyoqu 
```
mobilePhysics = 1
```

**Comment by AlexHGaming** [comment]
You can use CTRL + F to find the number 13 and to see if it matches with the collisions.
@fayizan @gyeyoqu

**Comment by fayizan** [comment]
@AlexHGaming I m in mobile how do I find the line

**Comment by ItzLevvie** [comment]
@fayizan Tap on the three vertical dots on the upper right of Google Chrome and tap on 'Find in page'

**Comment by MastaCoder** [comment]
No support is provided for custom code.

**Comment by gyeyoqu** [comment]
@AlexHGaming and you can learn better js :p

**Comment by AlexHGaming** [comment]
@gyeyoqu Are you telling me to learn js?
