### ISSUE TITLE
How to change botStartSize

### ISSUE THREAD

**Issue by Sicmda** [Megabyte918/MultiOgar-Edited#1164]
How to change bot start size?
I wanna to change the size of bot.

not minion

**Comment by AlexHGaming** [comment]
Bots use the same spawnmass as the human player.

**Comment by Sicmda** [comment]
@AlexHGaming I mean, I don't want the same size as a player. Is it impossible to change the size of the bot?

**Comment by Megabyte918** [comment]
@Sicmda You can add something like this in GameServer.js under [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L836) line. 
```js
if (player.socket.isConnected == null && !player.isMi) {
    size = startSize; // startsize = start size of bots
}
```

**Comment by Sicmda** [comment]
@Megabyte918 Thanks.
