### ISSUE TITLE
Badwords.txt is literally messed up.

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1167]
Badwords and returned messages need to be partially fixed.
I put `spawnmass` in the chat, and it returned the message "be calm and dont insult others" or something like that. Like how is that bad?

**Comment by pabloalber84** [comment]
Because have "ass" in the chat, the function of detection to bad words need search single word, with spaces, no't in the letters (WIthout special characters).

**Comment by MastaCoder** [comment]
Fixed.
