### ISSUE TITLE
I cant run the server up to 25+ GB [HELP]

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#117]
![image](https://cloud.githubusercontent.com/assets/20871314/20737918/9a72d41c-b6ea-11e6-88b2-9075a9f252e7.png)

**Comment by NameYT** [comment]
@Megabyte918

**Comment by Megabyte918** [comment]
@NameYT you must run the command from inside of /src, not /run

**Comment by NameYT** [comment]
@Megabyte918 
![image](https://cloud.githubusercontent.com/assets/20871314/20738410/e2aa702a-b6ed-11e6-8c7f-32541fcad0da.png) Still an error

**Comment by NameYT** [comment]
@Megabyte918

**Comment by Megabyte918** [comment]
@NameYT Exit out of the terminal, open src, shift + right click, "open command window here", then type the command

**Comment by NameYT** [comment]
I dont understandt you what terminal?

**Comment by NameYT** [comment]
okay nvm i did it

**Comment by NameYT** [comment]
@Megabyte918 
![image](https://cloud.githubusercontent.com/assets/20871314/20739167/72876a40-b6f3-11e6-81b0-da3ba2ece5d7.png)Still error!

**Comment by Megabyte918** [comment]
@NameYT 
1) press the "x" located top right of the command window (the black box with white text in it on the screen)
2) go to the navigation bar (the bar that says MultiOgar-Edited-master > run)
3) click on MultiOgar-Edited-master in the navigation bar (do not click on run)
4) once your in the MultiOgar-Edited-master folder, double click on the folder named "src" directly underneath the "run" folder
5) once your inside the "src" folder, right click an empty space (make sure you dont right click a folder or file)
6) you should then see a dropdown menu, go down on the dropdown menu until you see something that says "open command window here"
7) click on that option, a new command window should open (the black box again)
8) enter that same command that you entered before, and press enter

**Comment by Megabyte918** [comment]
I've already told you, follow my instructions.
