### ISSUE TITLE
Can anyone provide a brief tutorial on how to use the BinaryWriter and BinaryReader?

### ISSUE THREAD

**Issue by kevindhu** [Megabyte918/MultiOgar-Edited#1170]
This, or point me to a resource to learn how to use Barbosik's BinaryWriter implementation. 

I want to be able to use it to send more data in the packets but I have no idea where to begin!

**Comment by kevindhu** [comment]
For example, what is binary protocol 4 vs 5 vs ... 11?


I understand that writing to binary rather than sending plaintext or raw JSON is much more efficient, but how the underlying binary is translated is murky to me.

Also, how would the client know to translate the message back into JSON (or at least make use of it?)

**Comment by chewydev** [comment]
Stop using socket.io EL OH EL.

**Comment by Luka967** [comment]
> This, or point me to a resource to learn how to use Barbosik's BinaryWriter implementation.

> I understand that writing to binary rather than sending plaintext or raw JSON is much more efficient, but how the underlying binary is translated is murky to me.

To even know how to use it, you need to have a solid understanding of how the values get encoded in the first place. Here's a summary of the important.

- What bytes are
- [The integer system](https://en.wikipedia.org/wiki/Integer_%28computer_science%29) (numbers without decimals)
  - Signed and unsigned integers
  - Integer sizes and their minimums & maximums
- [The float system](https://en.wikipedia.org/wiki/Floating-point_arithmetic) (numbers with decimals)
  - Their precision degrades exponentially
  - Their more accurate but expensive to decode variant - [decimals](https://en.wikipedia.org/wiki/Decimal_data_type)
- The string system
  - Number represents a string
  - 1 byte 1 character system - [ASCII](https://en.wikipedia.org/wiki/ASCII)
  - [UTF-8](https://en.wikipedia.org/wiki/UTF-8) and [UTF-16](https://en.wikipedia.org/wiki/UTF-16)

Once you learn that, you should know what [JavaScript bitwise operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators) do.
Briefly, `~~x`, `x >> 0` and `x >>> 0` floors a number, `x & y` is used for [flags](https://en.wikipedia.org/wiki/Bit_field)

> I want to be able to use it to send more data in the packets but I have no idea where to begin!

Look at the source code. You have an example in front of your eyes.

> For example, what is binary protocol 4 vs 5 vs ... 11?

As agar.io kept being updated, the binary protocol structure changed. None of them are compatible with each other so a public server might want to include support for multiple of them, which is what Barbosik did, and we are continuing on, albeit in a very slow pace.

> Also, how would the client know to translate the message back into JSON (or at least make use of it?)

`writer.writeStringZeroUtf8(JSON.stringify(object))` to encode,
`JSON.parse(reader.readStringZeroUtf8(object))` to decode.

Yes, socket.io makes everything easier and more sophisticated, but being sophisticated always ends up slower. Don't use others' tools unless it's a bare bones driver, like a mysql client.

**Comment by chewydev** [comment]
Don't flood my comments :b: UKA

**Comment by Luka967** [comment]
:(

**Comment by chewydev** [comment]
:)

**Comment by kevindhu** [comment]
Yeah socket.io is super easy but I feel if I want to scale it its pretty much impossible.

so by using ws you won't be sending JSON files, ever? I want to definitely transition to binary transmission.

Thanks for posting the links, appreciate them. I was already sort of familiar with bit-shifting, but the protocols just didn't make sense until you pointed them out as exclusive to agar.io.

**Comment by kevindhu** [comment]
Also one more thing, why do you scramble X and Y? I see the documentation says it prevents anti-raga?

**Comment by Luka967** [comment]
*Is an anti-raga mechanism. We just offset the coordinates by an arbitrary number for *all* clients to make clients harder to know where cells actually are.

**Comment by MastaCoder** [comment]
No response in 5 days, closing for now.

**Comment by chewythepig** [comment]
I ended up writing my own Reader and Writer for arraybuffers if anyone cares.
