### ISSUE TITLE
How know?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#1173]
How know clients like cigar, what is the packet 0xFE

if u can see here:

```
 switch (packet) {

 case 0xFE:
                // Server stat
                serverStats = JSON.parse(reader.getStringUTF8());
                latency = Date.now() - lastMessageTime;
                drawServerStat();
                break;

}
```

In MO-E i cant see that packet, but that works fine i think that is packet 254 in 0x notation, but how works this packets? anyone can explain me?

**Comment by pabloalber84** [comment]
0xFE hexadecimal number of 254, from initial packet stats from server-client.
Is a object with the stats from the server, you can see in [https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/packet/ServerStat.js](url)

**Comment by AlexHGaming** [comment]
@pabloalber84 That is a non-existant link.

**Comment by AlexHGaming** [comment]
![image](https://user-images.githubusercontent.com/23644244/28994754-82aeff4e-79cd-11e7-8215-0019333a4df1.png)
returns that

**Comment by pabloalber84** [comment]
@AlexHGaming Fail tag github :P 
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/packet/ServerStat.js

**Comment by MastaCoder** [comment]
No response?
