### ISSUE TITLE
[question] gota explosion

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1174]
How to make explosions from viruses in gota(gota the explosion 1 large cell and 4 same small cell)
Well, or just how to make the explosion to a small cell was of equal mass

please respond with a normal response... and then you don't answer people clear answers and closed questions  I know that this does not apply to the project, but it is the question :) if it is the duplicate that write number of questions where this question is written

**Comment by AlexHGaming** [comment]
Also I am really wanting this, this has been duplicated I think.

**Comment by DeadLord1337** [comment]
the question number with the answer....

**Comment by AlexHGaming** [comment]
#332

**Comment by DeadLord1337** [comment]
ok but how to make the explosion, there were 4 SAME cells. Write what numbers should be inserted in virus.js to 4 SAME cells. I already suffer with these explosions 3 months maybe more (I found good values for explosions in vanilla

**Comment by AlexHGaming** [comment]
idk then. i knew what u meant in the first place, but idk how to do it myself.

**Comment by FantasyIsBae** [comment]
Could you please give an example, thanks :)

**Comment by ZfsrGhS953** [comment]
@FantasyIsBae He already did.

**Comment by AlexHGaming** [comment]
![image](https://user-images.githubusercontent.com/23644244/29034561-8db0401e-7b90-11e7-8d84-042d35194450.png)
![image](https://user-images.githubusercontent.com/23644244/29034588-a8e96f04-7b90-11e7-927a-2042f6d4a989.png)

**Comment by AlexHGaming** [comment]
idk why the 4 cells werent at the same angle, meh mustve messed up for me when i was screenshotting them

**Comment by FantasyIsBae** [comment]
Refer to [this answer](https://github.com/Megabyte918/MultiOgar-Edited/issues/332#issuecomment-270020554), I myself don't know how the physics of gota work, so I cannot really assist you here.
