### ISSUE TITLE
How to make minions...

### ISSUE THREAD

**Issue by giancarlosambayan** [Megabyte918/MultiOgar-Edited#1175]
How do i make minions collect pellet like on this vid : https://www.youtube.com/watch?v=IaB23Cf3Qp0&t=62s

**Comment by AlexHGaming** [comment]
It's on [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L179)

**Comment by giancarlosambayan** [comment]
@AlexHGaming If u look in the video the minions collect pellets much bigger not like the
original pellet mode which collect pellets and left nothing on the map .-.

**Comment by Luka967** [comment]
They did the same as the pellet mode here...

**Comment by giancarlosambayan** [comment]
@Luka967 Watch the video
When the minions collect pellets and minion some minion is not moving and waiting for the pellet to appear! :3 my english suk

i think its Minions collect pellet ticks thingy

**Comment by Luka967** [comment]
>waiting for the pellet to appear

Which is the same that these bots do, isn't it?

**Comment by giancarlosambayan** [comment]
@Luka967 Yes on that vid

**Comment by FantasyIsBae** [comment]
Just saying if you take a look at the amount of bots on that video, you will soon realise that there are around 500 to 600 bots , with around 100 or so mass each, going by that they will obviously be able to collect pellets quicker.

**Comment by MastaCoder** [comment]
I'm pretty sure these bots check their view distance for food as well.
