### ISSUE TITLE
Some new Ideas from the Ogar-Unlimited-Master

### ISSUE THREAD

**Issue by ogarfan69** [Megabyte918/MultiOgar-Edited#1176]
Hey! i have a few thoughts for what you should add in the next update for multiogar-edited.

1.OP feature (gives player various abilities)
2. An option to shrink and enlarge the map from the cmd/server
3.An option to change gamemode from cmd/server
4.split speed setting
5.More things we can do from the cmd/server
Thank you,

**Comment by AlexHGaming** [comment]
A few things:

> 1.OP feature (gives player various abilities)

This is Ogar Unlimited.

>4.split speed setting

It's on [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L163)

**Comment by ogarfan69** [comment]
it isnt on multi ogar! only on ogar unlimited that dosent work anymore!

**Comment by DeadLord1337** [comment]
bad ideas it is not necessary for MiltiOgar-Edited

**Comment by AlexHGaming** [comment]
Agreed with @DeadLord1337.

**Comment by AlexHGaming** [comment]
>it isnt on multi ogar! only on ogar unlimited that dosent work anymore!

Define "it".

**Comment by ogarfan69** [comment]
@AlexHGaming OP

**Comment by ogarfan69** [comment]
nvm, your right. atleast its better than the original ogar

**Comment by pabloalber84** [comment]
All things than you suggest:
If one scripter want this, do it for yourself.
Don't are necessary.

**Comment by MastaCoder** [comment]
1. No.
2. Extra code, can lead to problems.
3. Extra code, can lead to problems.
4. Already in config.
5. Add them yourself, this is a starting base.

**Comment by ogarfan69** [comment]
@MastaCoder How da' hell im gonna add it myself?
