### ISSUE TITLE
leaderboard, player

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1178]
Hi!

How to display your position in the leaderboard as agar.io? For example, if I'm not 10 leaderboard, it shows my current position, for example, 27.

Know what not to write, but maybe you know how to do it.

This has made in agar.lol
![image](https://user-images.githubusercontent.com/19995663/28999722-45c62e70-7a5b-11e7-9afc-83270168bc21.png)
![image](https://user-images.githubusercontent.com/19995663/28999725-61d18b0a-7a5b-11e7-922a-30e2b0c1cd92.png)

**Comment by pabloalber84** [comment]
Client Side

**Comment by TopoR1** [comment]
@pabloalber84 well I ask on the client side to help Cigar

**Comment by MastaCoder** [comment]
This isn't client sided. Has the code been added for the leaderboard changes yet? (Haven't been able to check)

**Comment by EarthAgar** [comment]
no i think its client sided because ive been testing on mine and it dosnt work

**Comment by FantasyIsBae** [comment]
@MastaCoder The code has been added.]
Idk how to get this to work tho.

**Comment by pabloalber84** [comment]
This can be added with custom packet leaderboard type 48, but with the problem to remake leaderboard positions system, adding again in currently gamemode.

**Comment by TopoR1** [comment]
The question is still open, ask someone to give the correct answer. Thank you.

**Comment by Valdex** [comment]
@TopoR1 русские везде!

**Comment by TopoR1** [comment]
I did it, yay!
![image](https://user-images.githubusercontent.com/19995663/30772680-264929f6-a069-11e7-8a3c-d1535e65690d.png)

**Comment by CodeFlush** [comment]
@TopoR1  HOW?
