### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1179]
I have 5 AI bots on my server, typing `pl` in the console returns the following:

![image](https://user-images.githubusercontent.com/23644244/29005617-beb6a370-7ad6-11e7-9d7b-61174cbeda9f.png)

But it is blank.

**Comment by koda** [comment]
cos you're dumb

**Comment by AlexHGaming** [comment]
@koda ??????????/

**Comment by pabloalber84** [comment]
You changed the AI code?

**Comment by AlexHGaming** [comment]
@pabloalber84 nope

**Comment by pabloalber84** [comment]
You changed command playerlist code?

**Comment by MastaCoder** [comment]
Can someone run this on stock and test the same command.

**Comment by FantasyIsBae** [comment]
Ok

**Comment by FantasyIsBae** [comment]
I ran a test to see if there were any errors, everything worked fine.
I'm assuming that you have altered a line or two of code and that's how it broke.
Here are my results for the latest version (**1.6.1**): 
![capture](https://user-images.githubusercontent.com/21162678/29078516-87df57f2-7c52-11e7-8a1b-6287acd0a4b8.PNG)
