### ISSUE TITLE
[ERROR] WebSocket: ENOTFOUND - getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by EarthAgar** [Megabyte918/MultiOgar-Edited#1182]
i need help with the server bind i keep getting this : | [ERROR] WebSocket: ENOTFOUND - getaddrinfo ENOTFOUND 195.267.58.170 and i have already read the other issue and its for server bind not available this one is from what i can tell it says error not found but idk but i need help for this so i can ad it to my client because its more safe then putting a long codeanywhere loging link for a server connection lol but do plz help

**Comment by FantasyIsBae** [comment]
The IP you are trying to bind is probably unavailable.

**Comment by EarthAgar** [comment]
thats not the error message tho and ive done like 8 different ips and none work

**Comment by EarthAgar** [comment]
664.893.126.993 : No
195.267.58.170 : No
993.443.989.997 : No
890.760.892.907 : No
80.60.89.90 : No
878.640.879.950 : No
87.40.87.90 : No

Get the point ?

**Comment by ItzLevvie** [comment]
**_i need help with the server bind - @EarthAgar_**

^ Please leave the serverBind option in gameserver.ini alone.

**_> thats not the error message tho and ive done like 8 different ips and none work - @EarthAgar_**

^ IP addresses cannot be made up, you will have to use the IP provided by CodeAnywhere.

**_> its more safe then putting a long codeanywhere loging link for a server connection - @EarthAgar_**

^ I wouldn't recommend using CodeAnywhere for a production Agar.io server. It's an IDE used for development purposes only.

**Comment by FantasyIsBae** [comment]
@EarthAgar The console won't tell you if the ip can't be binded.
It may be an issue with your network, machine or router.

**Comment by EarthAgar** [comment]
idk how im really new to all this and i have been following a youtuber named cowpits witch gas helped alot so yeah could u maybe tell me how to do this dedicated server or vps ? im fairly noob at this and i know peopl like u guys hate noobs but im a nood lol help would be apreciated thx

**Comment by FantasyIsBae** [comment]
You should buy a VPS from a trusted distributer like [OVH](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiaseaBxcrVAhUrBcAKHZYoBPcQFghEMAA&url=https%3A%2F%2Fwww.ovh.co.uk%2Fvps%2F&usg=AFQjCNG1yB-f_VUZZ1ci5dZYyQL3suJWNg), [Linode](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjzjbmjxcrVAhUkJsAKHdFdBuQQFghGMAA&url=https%3A%2F%2Fwww.linode.com%2F&usg=AFQjCNEMmsaO9jXlh13QTr4xXJLb8jeuxQ) or [Vultr](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwih5Ne0xcrVAhVkJsAKHdviBOcQFgg7MAA&url=https%3A%2F%2Fwww.vultr.com%2F&usg=AFQjCNFWk1yD9m-s1DetXpyJP2IhVpH2XQ) and host it on there.
