### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#1184]
<escript>

hola guapos 7u7

how to do when a player with specific ip, enter in the game this automatic get a user role?

my english is bad :v

</escript>

**Comment by EarthAgar** [comment]
idk but this is a really good idea !!

**Comment by EarthAgar** [comment]
maybe if u change the local ip to their ip and then ?

**Comment by pabloalber84** [comment]
Two functions than you can need:
In playerTracker object:
```
userRole
socket.remoteAddress
```
You will need to add individual roles and ip's.
Or you can use userRoles JSON object:
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/enum/userRoles.json
And simple, when you want to add anyone rol to one ip, just put new line in JSON and in the object from gameServer (https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L152)

**Comment by imnotNxhz1** [comment]
@pabloalber84 i don't understand anything XD

**Comment by pabloalber84** [comment]
@imnotNxhz1 First learn how to script in nodejs/javascript, next see my response.

**Comment by AlexHGaming** [comment]
#Savage

**Comment by AlexHGaming** [comment]
@imnotNxhz1 Try replacing your JoinGame function in PlayerTracker.js to this:

```javascript
PlayerTracker.prototype.joinGame = function(name, skin) {
    if (this.cells.length) return;

    if (skin) this.setSkin(skin);
    if (!name) name = "An unnamed cell";
    var UserRoleEnum = require("./enum/UserRoleEnum");
if (this.PID == "specific ID") 
this.userRole = UserRoleEnum.ADMIN; // < replace admin with whatever role you want
    this.setName(name);
    this.spectate = false;
    this.freeRoam = false;
    this.spectateTarget = null;
    var packetHandler = this.socket.packetHandler;
```

**Comment by AlexHGaming** [comment]
Or do what @pabloalber84, but my method is easier and clearer.

**Comment by AlexHGaming** [comment]
Any more questions, feel free to ask me! (make sure you tag me though lol)

**Comment by pabloalber84** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/commit/7e248f093b6fc8c37dd785c4f15417255d9f1608
https://github.com/Megabyte918/MultiOgar-Edited/commit/16f75ee09d49340809019e7e486c4672d5037bf6
https://github.com/Megabyte918/MultiOgar-Edited/commit/055affe1c7d6cac7ff9cbf294e35851a9e29c349

:)
I dont tested :baby:

**Comment by AlexHGaming** [comment]
@MastaCoder @Megabyte918 @FantasyIsBae
No response.

**Comment by imnotNxhz1** [comment]
thanks :100:  @pabloalber84  @AlexHGaming
