### ISSUE TITLE
How to Display Your Position and Mass on the Leaderboard?

### ISSUE THREAD

**Issue by Mr-BrockLee** [Megabyte918/MultiOgar-Edited#1186]

**Comment by AlexHGaming** [comment]
I **THINK** that is client sided.

**Comment by AlexHGaming** [comment]
Wait nvm it isn't

**Comment by Mr-BrockLee** [comment]
Ive heard ogar or whatever has it but idk

**Comment by pabloalber84** [comment]
If you want server side:
Use custom packet leaderboard 48, and rebuild the leaderboard system.
If you want client side:
Get from any playerlist actual's, the positions and mass, and put in leaderboard update.

**Comment by F0RIS** [comment]
@pabloalber84 client don't have such data about all cells in the game. So without changes on server it cant be done
