### ISSUE TITLE
Cannot connect to server - web_menu_login_elsewhere_header

### ISSUE THREAD

**Issue by XxXN0SplittrXxX** [Megabyte918/MultiOgar-Edited#1187]
In the past I've been able to host servers just fine using multiogar-edited.

I have not played the game for a while and just now I tried to host my own server again, but I get the following error:
 [https://gyazo.com/ffe107a41eac97f7c03ef223a41dd2ad]
**This is in incognito mode*

I've re-forwarded my ports just to be sure; they are open, but nobody can connect to my server. The best I can get it to do is show me on the player list in the console, but all it will do is say ''Connecting''.

Also, it seems like it keeps refreshing the connection, as everytime I refresh the playerlist in the console, my player ID has increased by the amount of times my agario refreshes: [https://gyazo.com/d79dd705e5a47fd837b8447030a2b2c6] (Edited)
__*Note__ that this particular scene happened whilst I was playing agar.io normally, which is why I am logged in in the gif. I decided to use this as a reference, as it is very similar, if not the same sometimes when I try to connect to my server using my public IP address.

I'm not quite sure what caused this to happen, as it used to work just fine when I left it.

If anyone knows how I could fix this, I'd appreciate it!

Edit: I have also downloaded the latest version of MultiOgar-Edited.
*When using my static IPv4 to connect, I'm able to play now. When I use the public IP in the link, it gives the same error above. Not sure what the problem is still.

**Comment by AlexHGaming** [comment]
Try reinstalling the server, does that work? It works fine for me.

**Comment by XxXN0SplittrXxX** [comment]
My bad, I forgot to mention that I've downloaded the latest ZIP package as well of Multi-Ogar. I'll add it in.

**Comment by FantasyIsBae** [comment]
Try using chrome in normal mode.

**Comment by XxXN0SplittrXxX** [comment]
I get the same error in normal mode with the public IP. In fact, when I do it without incog, it gets stuck, connecting with the message ''Logging onto Google+.''

**Comment by AlexHGaming** [comment]
@XxXN0SplittrXxX You need to logout of facebook / google before using your private server.

**Comment by XxXN0SplittrXxX** [comment]
@AlexHGaming Yes, I have made sure of that as well. I'm not logged into agar.io with either of those.

**Comment by AlexHGaming** [comment]
I could not reproduce.

**Comment by cowpits** [comment]
from your comment you can connect using your local IP but not external IP? 
so basically you can connect using agar.io/?ip=127.0.0.1:portnumber correct? but not public IP? that's port forwarding and you said it's forwarded. are you running this on a windows machine? is the firewall on?

**Comment by XxXN0SplittrXxX** [comment]
Yes, that is right. I am running on a Windows 10 and the firewall is on.

**Comment by cowpits** [comment]
did you ever get a notification to allow node.js to go through the windows firewall on Private or Public network? I have a feeling the rule is not set for it.

**Comment by XxXN0SplittrXxX** [comment]
Is this what you mean? https://gyazo.com/52c2998224fee81322cfd12542d1b778 I do not remember getting a notification recently for that

**Comment by AlexHGaming** [comment]
@XxXN0SplittrXxX Try connecting to a different client. Does that work?

**Comment by XxXN0SplittrXxX** [comment]
@AlexHGaming What do you mean, a different client?

**Comment by AlexHGaming** [comment]
@XxXN0SplittrXxX A different website to play your server on.

**Comment by XxXN0SplittrXxX** [comment]
Ah, well, I don't know any websites for that. It used to be astr.io, but now that that doesn't work anymore I haven't found a replacement for it. Do you maybe have a suggestion? I'd love to try it.

**Comment by AlexHGaming** [comment]
@XxXN0SplittrXxX You could try using [my client](http://agarahg.tk) for 443 and 4444 localhost ports only. Get a localhost server, put the port to either keep 443, or have 4444, connect to the client, pick the 443 / 4444 server and try that.

**Comment by cowpits** [comment]
what's the No column in the screenshot you posted? you have Yes but not sure what the No is for.

**Comment by XxXN0SplittrXxX** [comment]
@AlexHGaming Yes, this works for me. I can connect fine locally, but not with using an external IP.
@cowpits the No column is ''Override'', the Yes column is ''Enabled''

**Comment by XxXN0SplittrXxX** [comment]
Quite confused, but suddenly it is working again after I got on my computer today: https://gyazo.com/adc223a2bc1cf3b891fe926e38ec277e

Thanks for the help everyone, I appreciate the support.

**Comment by Georgleeb22** [comment]
I am so grateful to you for explaining it so easily.
Thank you!

**Comment by AlexHGaming** [comment]
No problem bro ;)
