### ISSUE TITLE
Somebody tried do 2x2 game mode?

### ISSUE THREAD

**Issue by F0RIS** [Megabyte918/MultiOgar-Edited#1189]
Share please if yes or suggest better way how to implement it)
Also I wanna do players count changable like 3x3, 4x4, NxN

**Comment by AlexHGaming** [comment]
@F0RIS Do you mean like Team Scrimmage?

**Comment by F0RIS** [comment]
@AlexHGaming yes

**Comment by AlexHGaming** [comment]
Some parts would be client sided, some parts would be server sided.

**Comment by ZfsrGhS953** [comment]
@AlexHGaming I think it's server sided only.

**Comment by F0RIS** [comment]
@AlexHGaming all needed info can be showed in leader board.
Another question - how to host it right? If its 2x2 for example only 4 players can play at one game server. So for 100 players we need 25 game servers? That's kinda strange.. Is it too hard to make several "rooms" at one game server? Split somehow gamefield and etc or it's not good decision and better just create many game servers?

**Comment by AlexHGaming** [comment]
@F0RIS It's really confusing on how to explain it.

**Comment by Soniz-YT** [comment]
Make a server like graver.io ultra split

**Comment by AlexHGaming** [comment]
@Soniz-YT 
`1.` That is off topic to this issue.
`2.` Just lower split velocity and make the recombine time 0.

**Comment by Valdex** [comment]
@F0RIS  на gota.io forum смотри где-то было такое

**Comment by MastaCoder** [comment]
This isn't client sided. Can we stop saying everything is client sided when it really isn't?

**Comment by Valdex** [comment]
Антон DIX написал уже 2v2

**Comment by Agarian** [comment]
2x2 as in 2v2, right?

**Comment by ChamForever** [comment]
@Valdex Russsia xDD

**Comment by Valdex** [comment]
Eeeaaah

**Comment by Valdex** [comment]
I with F0RIS russian
