### ISSUE TITLE
Help! Line Split Not Working!

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#119]
Fix! Only working halftime

**Comment by NameYT** [comment]
@Megabyte918

**Comment by ZfsrGhS953** [comment]
Here's how to fix it:
[This line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/PlayerCell.js#L58) should be:
```javascript
var speed = Math.min(d, speed);
```
The line above should be removed.
[This line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/PlayerCell.js#L49) should be:
```javascript
if (squared === 0) return;
```

**Comment by NameYT** [comment]
@ZfsrGhS953 Do you know how to change splitMass so i can get a better chance of popsplits?

**Comment by PsycoYT** [comment]
@ZfsrGhS953  if i pay you , you can do a client to me
