### ISSUE TITLE
Questions about BinaryWriter Buffer

### ISSUE THREAD

**Issue by kevindhu** [Megabyte918/MultiOgar-Edited#1190]
Looking at this project again to better understand binary writing, just have a few more related questions.

I know what a data buffer is (https://en.wikipedia.org/wiki/Data_buffer), but I want to know how to read the binary data once it has been transmitted to the client. I see that the sendPackets method in playerTracker will send the buffer that results from building a packet:
`if (socket.readyState == this.gameServer.WebSocket.OPEN) {
        var buffer = packet.build(this.protocol);
        if (buffer) socket.send(buffer, { binary: true });
    }`

Starting off easy, what would be the function to unwrap the buffer on the client side? 

Another more concrete example: 
I understand that the binary data for something like UpdatePosition  would be:
--packetId--xPosition--yPosition--globalScale--, 

so what would be a function to unwrap this information on the client side so I can get all the original strings and floats back??

Thanks!

**Comment by pabloalber84** [comment]
The interaction are SERVER-CLIENT, this two, can receive and send data in buffer, and two have READER and WRITTER, for socket buffer packet.

**Comment by Luka967** [comment]
Use `ArrayBuffer` and `DataView` in the unwrapping function, the base classes for byte buffer handling in Javascript. Be careful for mismatching offsets.
