### ISSUE TITLE
lol help me

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1191]
![image](https://user-images.githubusercontent.com/24901742/29365960-4b8ad4e8-82a1-11e7-9066-ecd8ccb36051.png)
How to give root? codeanywhere

**Comment by Valdex** [comment]
@DeadLord1337 write 
sudo node index

**Comment by Valdex** [comment]
@DeadLord1337  for blob? :)

**Comment by Luka967** [comment]
@Valdex he doesn't even have root perms
@DeadLord1337 use a different port

**Comment by Valdex** [comment]
@DeadLord1337 o i remember need port up to 1030

**Comment by Valdex** [comment]
@DeadLord1337 i use port 3000

**Comment by Valdex** [comment]
@Luka967 can help me. need make gota.io physics MultiOgar Edited 1.3.5

**Comment by DeadLord1337** [comment]
@Luka967 thx
