### ISSUE TITLE
Small Issue with ServerStat ***

### ISSUE THREAD

**Issue by Mr-BrockLee** [Megabyte918/MultiOgar-Edited#1192]
ServerStat Issue:  The player count feature also counts also counts minions as player, is there a way to eliminate that? So I can have a accurate PlayerCount

**Comment by pabloalber84** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/commit/b0d8f88365c64a79fcb458580167dec1a2579ef4
;)

**Comment by Mr-BrockLee** [comment]
@pabloalber84 

`Spot On! Thanks m8 🥇 `

**Comment by pabloalber84** [comment]
:v

**Comment by AlexHGaming** [comment]
@Mr-BrockLee @FantasyIsBae Close?
