### ISSUE TITLE
Bots Split-alot

### ISSUE THREAD

**Issue by BotCodz** [Megabyte918/MultiOgar-Edited#1194]
Dear Mega, Im having an issue with MOE. i.e the bots split a lot. ex. if i split x2 all the bots split over me. but they cant even eat me. and if i add like 150 bots on the server they get crazy ans splits so much. hoping for a fix soon

**Comment by AlexHGaming** [comment]
@BotCodz #961, been duplicated many times. I'm going to say what megabyte said. Having smarter AI leads to more lag and this has already been suffering with lag due to all of the chunk of code.

**Comment by AlexHGaming** [comment]
@Megabyte918 @FantasyIsBae @MastaCoder 🤔

**Comment by BotCodz** [comment]
well,according to my logic, if bots split more, it creates more lag (more cells=more lag) i'm not saying you to make the bots smart af but just fix this splitting crap.please
