### ISSUE TITLE
Command /set (id) (Functions)

### ISSUE THREAD

**Issue by ArixProject** [Megabyte918/MultiOgar-Edited#1195]
How?

**Comment by AlexHGaming** [comment]
> /set (id) (Functions)

What do you mean specifically?

**Comment by imnotNxhz1** [comment]
gaver.io? xD

**Comment by ArixProject** [comment]
@imnotNxhz1 np xD

**Comment by ArixProject** [comment]
For example, I want to have a part (a coin as in alis.io)

**Comment by ArixProject** [comment]
Close?

**Comment by AlexHGaming** [comment]
There is simply a close issue button on the left where you comment.
Or if you're asking for it to be closed, yes.
Coins in alis.io is client sided.

**Comment by ArixProject** [comment]
I know where the Close button is
