### ISSUE TITLE
Stuck on "Logging in to Google+..."

### ISSUE THREAD

**Issue by NootSponge** [Megabyte918/MultiOgar-Edited#1198]
Hello, I've been having a small problem on connecting to the server. (I'm using the default [agar.io](http://agar.io)/?ip=localhost:443) When I put that into Chrome it finds the server and is connected (as shown [here](http://i.imgur.com/8UZUTX7.png)) but gets stuck spinning on 

> Logging in to Google+...

I can log into  Google+ when the ip parameter isn't there, but I would like to use my skins and all that. I can also play in incognito mode when not logged in, but as I said before I would like to use my skins.

**Comment by NootSponge** [comment]
UPDATE: Broken for Facebook too.

**Comment by ItzLevvie** [comment]
You need to logout of Google+ & Facebook if you want to play on your server.

For the skins issue, use ```<skin_name>``` however you won't be able to see your own skin but other players will see it. 

There's an extension laying around from the Agar community to use different skins and custom skins (only you can see it) too

**Comment by NootSponge** [comment]
Okay, thanks. Is [this](https://chrome.google.com/webstore/detail/agario-skins/ddmbokmmnnhmdllgjohoigfpfmaiahfh?hl=en) the extension?

**Comment by ItzLevvie** [comment]
@NootSponge That's pretty old.

If you don't want to use an extension then use type ```core.setSkins('%skinName')``` on the F12 console

**Comment by NootSponge** [comment]
Does that let you see your own skin?

**Comment by ItzLevvie** [comment]
@NootSponge yes

**Comment by AlexHGaming** [comment]
@NootSponge Just logout of facebook/google, reconnect to your agar.io server, done.

**Comment by NootSponge** [comment]
@ItzLevvie I still can't see the skin.

**Comment by ItzLevvie** [comment]
@NootSponge You were meant to replace ```skinName``` with a actual skin name (for example -> kraken, evileye or war_wings)

**Comment by NootSponge** [comment]
I might be misunderstanding you.
Replace `%skinName` in `core.setSkins('%skinName')` with an agar.io skin name (I've been trying evileye).
Right?

**Comment by NootSponge** [comment]
Turns out `evileye` isn't a skin. I tried some skins from [this website](http://www.agarioguide.com/skins/) and they worked. Thanks anyway!

**Comment by ItzLevvie** [comment]
Actually ```evileye``` is a skin.

**Comment by ItzLevvie** [comment]
You should see my updated comment above it's ```core.loadSkin(..)``` not ```core.setSkins(...)```

**Comment by NootSponge** [comment]
Ah, okay. Thanks.
