### ISSUE TITLE
omg

### ISSUE THREAD

**Issue by ogar-unmimited** [Megabyte918/MultiOgar-Edited#1199]
the bots ai is so crappy pls fix this soon some times the bot are even afk fix this hell!

**Comment by AlexHGaming** [comment]
People like you make me want to kill myself.

**Comment by gyeyoqu** [comment]
@ogar-unmimited agar is dead, stop playing this XD

**Comment by AlexHGaming** [comment]
@gyeyoqu Why are you on the repo then?

**Comment by ZfsrGhS953** [comment]
@ogar-unmimited The bots are only made for testing features that require more than one player (such as popsplits), not normal gameplay. If you actually want to make some smart bots, start learning [here](http://bfy.tw/Nsy).

**Comment by FantasyIsBae** [comment]
Duplicated so many times...

**Comment by ogar-unmimited** [comment]
lel
