### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#12]
If i give minions for friend, later for me all bots start coming to me! and no bots for friend! fix please!

**Comment by NameYT** [comment]
They are fixing on it :) That's the bug

**Comment by NameYT** [comment]
**# For now 1 Person Can control the bots on a time :)**

**Comment by t11tanYT** [comment]
i know, i dont read this)

**Comment by Fantasy-Agario** [comment]
This has been noted in [Issue #7](https://github.com/Megabyte918/MultiOgar-Edited/issues/7)
