### ISSUE TITLE
i cant split and eject minions!!!!

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#120]

**Comment by lotfis** [comment]
press Q to enter minions controls & press Back Q to enter ur cell controls

**Comment by Megabyte918** [comment]
@t11tanYT Works fine for me, using Q and ERPT. If your using ERPT make sure your using the script, your using the Agar.io client, and it is enabled in config.

**Comment by t11tanYT** [comment]
@Megabyte918  i use script ert and p and in config 0 my minions only collect pullets

**Comment by Megabyte918** [comment]
@t11tanYT make sure you don't have any other macros or anything else using the same controls
