### ISSUE TITLE
how send only 1 message?

### ISSUE THREAD

**Issue by MiraMiPalo** [Megabyte918/MultiOgar-Edited#1200]
example in playerTracker.js
if  (this.xD) (this.gameServer.sendChatMessage(null, this.playerTracker, "Te amo ( ͡° ͜ʖ ͡°)");

what add to send only 1?

**Comment by Wair1o17** [comment]
this.sendChatMessage(null, from, "This is to send message.");

**Comment by MiraMiPalo** [comment]
pero envia como 100 mensajes en menos de 1 segundo xD

**Comment by AlexHGaming** [comment]
???????????

**Comment by AlexHGaming** [comment]
English only.

**Comment by gyeyoqu** [comment]
@MiraMiPalo At Least, do you know anything about programming?

**Comment by ZfsrGhS953** [comment]
@gyeyoqu You better look at yourself before blaming someone else.

**Comment by AlexHGaming** [comment]
@gyeyoqu You are making it worse.

**Comment by AlexHGaming** [comment]
@gyeyoqu You are not helping this conversation one single bit.

**Comment by pabloalber84** [comment]
Haber, como nos entendemos, dime we yo te ayudo :v

**Comment by Wair1o17** [comment]
@pabloalber84 Lo que el quiere es que el mensaje se envié sólo a una persona y no a todas las que están conectadas

**Comment by pabloalber84** [comment]
Que haga una variable objecto para declarar 2 cosas: La ip de quien quiere que le aparesca, y el mensaje, y que haga el script este wey

**Comment by Wair1o17** [comment]
Por que ip y no PlayerTracker :v?

**Comment by MiraMiPalo** [comment]
el mensaje se envia bien :v pero solo quiero que se mande uno xD ya que envia como 100 en menos de un segundo,,  

http://i.imgur.com/HZSTLec.jpg

@gyeyoqu  yo tambien te amo ♥

**Comment by Wair1o17** [comment]
lol

**Comment by ZfsrGhS953** [comment]
@MiraMiPalo You need to set a variable after sending the message and add another condition to the if to avoid sending it multiple times.

**Comment by gyeyoqu** [comment]
@MiraMiPalo 

**Out of any function**
`var count = 0;`

**now**(inside the function that check connected player)
```
if( count == !1 & ip='') this.gameServer.sendChatMessage(null, this.playerTracker, "Te amo ( ͡° ͜ʖ ͡°)";
count += 1;
```

Simple and clean

**Comment by pabloalber84** [comment]
Muéstrame en que lugar lo pusiste, y te puedo ayudar bien, osea, un SS del lugar.

**Comment by FantasyIsBae** [comment]
Has this been resolved?

**Comment by Agarian** [comment]
I wouldn't know.
