### ISSUE TITLE
Question: Do you do any client-side prediction or lag compensation?

### ISSUE THREAD

**Issue by kevindhu** [Megabyte918/MultiOgar-Edited#1201]
What happens if the latency is really high? Shouldn't the client see themselves in the present and see the enemies in the past (100 ms)?

I think this game doesn't account for that, but I am just asking if it is necessary for a game like this.

Even if the client is really laggy, do they see themselves really laggy or are they being fed client-side prediction so at least themselves look all right?

Lastly, to repeat again, is there any delay at all for reading server data? Or is it simply the naive approach of just updating all the info immediately when the server information is received by the client?

**Comment by kevindhu** [comment]
By the way, I got the ideas from reading on http://buildnewgames.com/real-time-multiplayer/

**Comment by gyeyoqu** [comment]
trying with compression on ws creation (gameserverj.s)

**Comment by ZfsrGhS953** [comment]
@gyeyoqu Your message doesn't make any sense. He's talking about lag compensation. Compression has nothing to do with that.

**Comment by Luka967** [comment]
@kevindhu Yes, but the lag is barely game-changing up to being a couple hundred milliseconds. In realtime action games like these the human precision is most important.
The server doesn't compensate for the lag in any way.
And even if the client were to have client-side prediction, it would just degrade the experience of the ones who lag. However they *do* have a *position animation* that's usually 120ms long. It's apparent if the server lags over that 120ms threshold. Try forcing the server to update every second, then get in it on agar.
