### ISSUE TITLE
CollectPallens and virus

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1202]
Can make Supplement for minion ? To CollectPallets they collected food and eating virus!!! Good idea I think so.

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L178

**Comment by DeadLord1337** [comment]
I know lol... just to minion gathering food and eating virus. But now they gather only food

**Comment by SAV-404** [comment]
or maybe collect the smaller players is better...dude then they will be players not minions !

**Comment by FantasyIsBae** [comment]
We don't want minions to have an AI , It will affect preformance

**Comment by DeadLord1337** [comment]
me performance is not important... it's a Supplement not really affect performance. 1.6.1 good and so is optimized. It's a good idea!!!

**Comment by AlexHGaming** [comment]
"minions to have an ai"
um what
