### ISSUE TITLE
Protocol 14

### ISSUE THREAD

**Issue by lefela4** [Megabyte918/MultiOgar-Edited#1204]
Hi. I made agar.io bots and I would like to help you to fix ogar for the protocol 14 if you are interested please reply!

**Comment by lefela4** [comment]
I have the full protocol. That mean everything (including the facebook and the shop paket)

**Comment by fayizan** [comment]
what to do with facebook and shop packet  in multiogar ? : |

**Comment by AlexHGaming** [comment]
@lefela4 If you're fixing ogar report it on their repo.

**Comment by FantasyIsBae** [comment]
No just no, go die somewhere else.
