### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1205]
I suggest that the `serverMinions` can be changed.
Instead of having them spawn in when you just enter a server (aka option value clicked it automatically spawns minions), I suggest making them spawn after the user presses play. This can be a good idea because then if I wanted their names to be (playername + bots), it would work as the user would specify a name before the bots spawn in.
It could be a useful feature :)

**Comment by Wair1o17** [comment]
good idea.

**Comment by gyeyoqu** [comment]
@AlexHGaming worse idea ever

**Comment by AlexHGaming** [comment]
@gyeyoqu Please specify why it's the worst idea ever. You keep attacking other people for no reason, and we don't like it like that. Treat others the way you want to be treated. What if you put an idea up on this repository and I called it the worst idea ever? 
Let me get a few things over with you.

![image](https://user-images.githubusercontent.com/23644244/29753189-c519a508-8b63-11e7-873d-ff6c1c30f812.png)

But at the same time, I look at these comments from you to other people.

![image](https://user-images.githubusercontent.com/23644244/29753197-f2534f10-8b63-11e7-9e34-9cae697c17ef.png)

You need to stop being so salty to other people. Like I mentioned earlier, treat people the way you want to be treated, and stop being so argumentitive over suggestions and help, because this is what the repo is for. If you don't like it, and what happens on it (issues, suggestions etc), then, in my "polite" way, fuck off. You are not helping other people, when they need the help. Stop commenting on issues that doesn't help a single bit please. Thank you.

**Comment by MiraMiPalo** [comment]
this is not the same as this? #1161

**Comment by pabloalber84** [comment]
Do yourself :v, can be created in gamemode file, not is the "big" update.
For me, don't are needed.

**Comment by AlexHGaming** [comment]
@MiraMiPalo, alright, I got that to work. Looks like this is a duplicate.
Closing.

**Comment by AlexHGaming** [comment]
@pabloalber84 I just want to know something, not everyone will have this.
