### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Faris90** [Megabyte918/MultiOgar-Edited#1206]
How could I make the map shaped like a triangle

**Comment by AlexHGaming** [comment]
Here at MultiOgar-Edited, we do width x height
the default is 14142x14142
So that means its a square (/ rectangle).
it is not 3d.
what am i on about ;-;

**Comment by gyeyoqu** [comment]
@AlexHGaming a triangle not mean 3d HAHAHA

**Comment by AlexHGaming** [comment]
@gyeyoqu ;-;
You're not helping the fucking repo a single bit.
Refer to my comment in #1205

**Comment by AlexHGaming** [comment]
You are literally making me triggered. Considering you're not helping. Leave the fucking project, then come back when you can actually help other people instead of chatting shit.

**Comment by AlexHGaming** [comment]
You act like a 7 year old who just started javascript. Your immaturity is not taking this repo anywhere further, instead talking shit about other people who need the help that they need on an issue.
