### ISSUE TITLE
Server sided or client sided?

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1207]
Ok
So when I have 4 people on my server, other people can't play. A.K.A, spamming "connecting"
it doesnt stay there, it says connecting, then it'll look like the server crashed, connecting again, repeat
How to fix this

**Comment by AlexHGaming** [comment]
ok i had the fix
since everyone in my server has the same ip
there was a config (ipperplayer **4**)
i had to increase that.

**Comment by ArixProject** [comment]
what ? xD

**Comment by AlexHGaming** [comment]
idk
