### ISSUE TITLE
using ~~ in distance calculations

### ISSUE THREAD

**Issue by arxii** [Megabyte918/MultiOgar-Edited#1208]
I was browsing through the source code of Barbosiks collision code, to see if i can use anything in a blob game that im currently working on and noticed that in modules/Vec2.js, Barbosik copy pasted a Vec2 Library without realizing that it was using ~~ bitwise to round of floats for distance calculations. Sure, its like twice as fast but this speed factor has no difference since you can do it many times over in a single frame. I use Log and Sin/Cos in my avoidance collision and it literally only takes a few more frames and its not like your physics simulation which is running at like 24fps by default is going to dip past 60 unless there is more than 1500 active nodes anyway. I suggest removing ~~ because you are calculating rounded off xy coordinates which literally creates visible stuttering. I'm posting this here because i know Barbosik probably never checks his repository issues anyway. 

BTW, my agario tag name is 🍄🌴ʏʊʀʏ🌴🍄 if u ever see me lol

**Comment by Luka967** [comment]
[They were added to make linesplits easier](https://github.com/Barbosik/MultiOgar/commit/60722903e100cdf3f732d8349c4818b46fafaeaa), not because why not.

**Comment by arxii** [comment]
no, i mean modules/Vec2.js used to calculate avoidance collision in GameServer.js
`
GameServer.prototype.checkCellCollision = function (cell, check) {
    var p = check.position.clone().sub(cell.position);

    // create collision manifold
    return {
        cell: cell,
        check: check,
        d: p.sqDist(), // distance from cell to check    <-------------------------------------------------------
        p: p // check - cell position
    };
};
`



MultiOgar-Edited/src/modules/Vec2.js ::

`
Vec2.prototype.dist = function() {
    return ~~this.x * ~~this.x + ~~this.y * ~~this.y;
};
`
change to ->
`
Vec2.prototype.dist = function() {
    return this.x * this.x + this.y * this.y;
};
`

**Comment by Luka967** [comment]
oh
LOOOOOOOOOOOOOOOOOOOL

**Comment by ZfsrGhS953** [comment]
@Luka967 Linesplits were impossible without it... before [this commit](https://github.com/Megabyte918/MultiOgar-Edited/commit/b67a9f43604e98940072a87da1de2664fe552e62). You see, before the commit, the cells would slow down after reaching 32 units from the cell, and would eventually come be a tiny distance away from the cell (like 1e-14). After the commit, the behavior is fixed, so the ~~ hack is no longer required. This was fixed before when Petridish Ogar got abandoned and some of its physics code ported to MultiOgar-Edited, but reverted after another refactor. And you can linesplit in [Bacter](https://github.com/ZfsrGhS953/Bacter), which has the same movement physics as the current MultiOgar-Edited, but without ~~.

**Comment by arxii** [comment]
oh sorry,
 i think it was node_modules/Vec2.js, not in src/modules.
