### ISSUE TITLE
Identification / Authorization

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#121]
I can't see any identification mechanics. As I see - anyone can send a command to my Cell by a packet with  my pID (which is a simple number).
If I temporary lost connection , I can only respawn a game with new pID, or I can be identified to continue last game? 
Can I use Token -> serverbound packet:80 for user Authorization and how should I do this?

Please explain.

**Comment by Megabyte918** [comment]
Fixed.
