### ISSUE TITLE
help :/ 

### ISSUE THREAD

**Issue by hossemThecoder** [Megabyte918/MultiOgar-Edited#1210]
PlayerTracker.js 
and my name is this.name = Hossem*http://i.imgur.com/GQbxegB.png*honrs*0
```js
PlayerTracker.prototype.setName = function(name) {
    this.name = name;
	var ss = this.name.split("*");
	if (ss[0] == "Hossem") {
		this.cells[0].setSize("1000");
	}
	
};
```
iget this  error `>TypeError : Cannot read property 'setSize' of undefined`

**Comment by ArixProject** [comment]
Do you want to make a hat?

**Comment by hossemThecoder** [comment]
no i want when  this.name.split("*")[0] = "Hossem" then give me 1000 mass
 but thnx i fix this :33
