### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by giancarlosambayan** [Megabyte918/MultiOgar-Edited#1211]
How can i make the minion's spawn seperately like in the end of the map , middle and random place?
some minions spawns on a top of a minion how? to do dat?

**Comment by hossemThecoder** [comment]
?? What

**Comment by AlexHGaming** [comment]
Why would you like the minions to spawn at the end of the map? Seems useless to me.

**Comment by TopoR1** [comment]
Minions have a random position, they can appear anywhere, but if you to customize their appearance on the same part of the map, this will upset the balance of the server.

**Comment by giancarlosambayan** [comment]
@TopoR1 I know that but sometimes the bots spawn on top of each other lolewl

**Comment by giancarlosambayan** [comment]
@AlexHGaming https://www.youtube.com/watch?v=pNZ6APM5Nds
I mean like this :)

**Comment by FantasyIsBae** [comment]
The minions are spawning in random positions on the map in that video though.

**Comment by giancarlosambayan** [comment]
@FantasyIsBae nvm but thanks :) to everyone who reply :D
