### ISSUE TITLE
how to make command /invite and /leave (for party)

### ISSUE THREAD

**Issue by ChamForever** [Megabyte918/MultiOgar-Edited#1213]
**How?**

**Comment by gyeyoqu** [comment]
@ChamForever programming

**Comment by AlexHGaming** [comment]
@gyeyoqu Can you please stop mentioning the word "programming" ???
And doing such would be client sided. You would have to have a popup box to come up to accept it, in which you have to do that by sending packets.

**Comment by gyeyoqu** [comment]
Nope, he asked how it is done and for this the programming is used, you can not tell him how it is done, there will no longer exist a unique algorithm for this task, it can always be done in different ways

**Comment by ChamForever** [comment]
stop stop stop xD

**Comment by AlexHGaming** [comment]
_there will no longer exist a unique algorithm for this task_
So you're assuming that it can't be done
❓

**Comment by ChamForever** [comment]
Maybe! I think that it is possible to make still through prompt

**Comment by AlexHGaming** [comment]
@ChamForever So how will it pop up on other people's screens?

**Comment by ChamForever** [comment]
yes

**Comment by ChamForever** [comment]
@AlexHGaming server sided ye?

**Comment by AlexHGaming** [comment]
I'd say client sided.

**Comment by ChamForever** [comment]
okay i close issue

**Comment by AlexHGaming** [comment]
close

**Comment by AlexHGaming** [comment]
ok

**Comment by gyeyoqu** [comment]
u not know ANYTHING

**Comment by AlexHGaming** [comment]
@gyeyoqu You "not know" english mate speak it fucking properly so i can understand ya. 
Stop bragging.
Stop moaning.
Stop putting other people down.
Stop being so salty.
Stop being a cunt.
Thank you.

**Comment by FantasyIsBae** [comment]
You would first have to develop your own party system, meanwhile this requires a little bit of optional client side modifications (Displaying players within a party, etc), It will mostly be done on the server.

Joining to a party doesn't have to require you to modify anything client sided, chat commands are enough.
>----
gyeyoqu and Alex can you please take this argument into Direct Messages.
>----

**Comment by AlexHGaming** [comment]
alright @gyeyoqu hit me up with discord lets talk

**Comment by gyeyoqu** [comment]
nope i will not talk with stupids kids :p

**Comment by AlexHGaming** [comment]
@gyeyoqu You act like one. Calling me stupid when I actually try to help people. People actually say thanks to me for how much I put into this repo and trying to help the community. Please show screenshots of people saying thanks to you in the next 24 hours, or else....

**Comment by ChamForever** [comment]
omg xD

**Comment by ChamForever** [comment]
![image](https://user-images.githubusercontent.com/28904275/29916902-e0f54cae-8e48-11e7-9655-21f0811f6b6c.png)

**Comment by ChamForever** [comment]
@FantasyIsBae  
![image](https://user-images.githubusercontent.com/28904275/29919014-481dfed8-8e50-11e7-9f7e-279f9a390ce1.png)

**Comment by TopoR1** [comment]
@ChamForever To implement this idea, you should work on the client side. Server-side changes are required. You can see client code from gota.io if the code has the appearance of obfuscation.

**Comment by ArixProject** [comment]
@TopoR1 
![image](https://user-images.githubusercontent.com/29149118/29943172-2029ba4c-8ea1-11e7-9c05-93874993a95b.png)rlly?

**Comment by ZfsrGhS953** [comment]
@AlexHGaming Alright, looks like I finally figured out what's wrong with gyeyoqu. **He's using GitHub through a uni-directional pager!** He can reply to your messages, but you can't reply back.

**Comment by Mr-BrockLee** [comment]
@ZfsrGhS953 u have skype, or discord?

**Comment by ZfsrGhS953** [comment]
@ChamForever Yes, I have a Discord: ```G.com#6028```
Not the IP-leaking Skype though.

**Comment by AlexHGaming** [comment]
@gyeyoqu 🤔 
its been 24 hours 
oh wait... you had nothin in first place

**Comment by gyeyoqu** [comment]
@ZfsrGhS953 shh,

**Comment by ZfsrGhS953** [comment]
@gyeyoqu What language is that?

**Comment by ZfsrGhS953** [comment]
@AlexHGaming Finally found @gyeyoqu 's discord, it's ```psycoYT#6431```

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 hmm... why thank you.

**Comment by AlexHGaming** [comment]
Lemme check his yt channel

**Comment by ZfsrGhS953** [comment]
@AlexHGaming I finally got @gyeyoqu 's source for easier maths, it was on agariocity.pro :smile: :smile:
[Here](https://github.com/ZfsrGhS953/Easier-Maths) it is on github.

**Comment by ZfsrGhS953** [comment]
@AlexHGaming His channel is deleted, the other Psycos you see are due to lack of creativity.

**Comment by Megabyte918** [comment]
Note to self: Don't mess with @ZfsrGhS953 haha

But seriously, let's try to keep the hostility to a minimum. I don't want people who are new to this repo to see these comments because it leaves a bad image.

**Everyone:** If you don't have anything nice to say or any help to give don't say anything at all. This is the issues section after all. Especially you @gyeyoqu, I've never seen a "programmer" act so rude towards people who ask for help.

@ChamForever @FantasyIsBae is right, this is a server-sided job that could be done through chat commands and the leaderboard, unless you want optional client sided features for the party system like he mentioned earlier. I won't tell you exactly how to do it yourself since it requires a ton of server sided modifications that I don't have the time to do atm, but this should give you an idea of where to start.

**Comment by FantasyIsBae** [comment]
@ZfsrGhS953 I have to say, easier maths is some evolutionary code. 😄

**Comment by ArixProject** [comment]
:D

**Comment by ChamForever** [comment]
:disappointed:

**Comment by mafiakb** [comment]
@ChamForever hi u cant help me with add party please? what is ur skype
