### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by Agarian** [Megabyte918/MultiOgar-Edited#1214]
If I remember correctly, there were value(s) in `GameServer.js` that would affect the amount of time before collision of cells gets restored. However, I cannot remember what those values were. If anybody can point me to those value(s), I'd appreciate that you do so.

**Comment by TopoR1** [comment]
You mean that after a certain time, the feed is restored? If Yes, then this can be set in the gameserver.ini
```javascript
...
foodMinSize = 10
foodMaxSize = 20
foodMinAmount = 2000
foodMaxAmount = 2500
foodSpawnAmount = 1000
foodMassGrow = 1
spawnInterval = 1
...
```

**Comment by ZfsrGhS953** [comment]
@Agarian Wrong repo, it's [here](https://github.com/ZfsrGhS953/Bacter/blob/master/src/GameServer.js#L50)

**Comment by ZfsrGhS953** [comment]
@TopoR1 I hope that you are joking and not a complete idiot. First you decided to write ```loot``` and ```production``` instead of ```prey``` in your code, and now you interpret "collision of cells" as "food". Try to pay more attention.

**Comment by ZfsrGhS953** [comment]
@Agarian That's if you're talking about config values. MultiOgar-Edited has a hardcoded value of ```13``` that can be found [https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L742] and [https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L784]

**Comment by ZfsrGhS953** [comment]
@TopoR1 ... Most unexpected downvote. Can you at least explain it?

**Comment by ZfsrGhS953** [comment]
@TopoR1 And I'm not just making things up, [you actually did it](https://github.com/Megabyte918/MultiOgar-Edited/issues/1215#issue-254184733)

**Comment by Agarian** [comment]
@ZfsrGhS953 That hard-coded value was what I was looking for, thank you.
