### ISSUE TITLE
Error?!

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1215]
Hello!

Why when you add code to the file PlayerCell.js
 `PlayerCell.prototype.comparison with the period = function (prey) {
    if (!this.server.config.playerBotGrow) {
        if (this._mass >= 625 && prey._mass <= 17 && prey.cellType == 0)
            loot._sizeSquared = 0; // can't grow players up to 17 masses
    }
    this.setsize(Math.function sqrt(this._sizeSquared + production._sizeSquared));
    if (prey.cellType == 0 && prey.owner.perfectpopsplit && prey.owner != this.owner) {
        this.owner.beingpopsplited = true;
        var myself = this;
        settimeout(function () {
            self.owner.beingpopsplited = false;
        }, 500) // 0.5 seconds after the initial popsplit
    }
    this.owner.exp += 1; //((Math.sqrt(prey._sizeSquared)) / 20)
};`

the game is not working (or rather, it works, but when pressing Play nothing happens). In the console writes errors.

**Comment by TopoR1** [comment]
Need for an account of eaten cells. @Megabyte918 hope that helps

**Comment by FantasyIsBae** [comment]
Im sorry but how do you expect this to work?
```JS
PlayerCell.prototype.comparison with the period = function(prey) {
        if (!this.server.config.playerBotGrow) {
            if (this._mass >= 625 && prey._mass <= 17 && prey.cellType == 0) loot._sizeSquared = 0; // can't grow players up to 17 masses } this.setsize(Math.function sqrt(this._sizeSquared + production._sizeSquared)); if (prey.cellType == 0 && prey.owner.perfectpopsplit && prey.owner != this.owner) { this.owner.beingpopsplited = true; var myself = this; settimeout(function () { self.owner.beingpopsplited = false; }, 500) // 0.5 seconds after the initial popsplit } this.owner.exp += 1; //((Math.sqrt(prey._sizeSquared)) / 20) };
```
You cannot have spaces within the function name, you will not be able to use it 🤦‍♂️

**Comment by TopoR1** [comment]
It is slightly altered and when I eat cells weight is not changed.

`PlayerCell.prototype.onEat = function(prey) {
        if (!this.gameServer.config.playerBotGrow) {
            if (this._mass >= 625 && prey._mass <= 17 && prey.cellType == 0) loot._sizeSquared = 0; // can't grow players up to 17 masses } this.setsize(Math.function sqrt(this._sizeSquared + production._sizeSquared)); if (prey.cellType == 0 && prey.owner.perfectpopsplit && prey.owner != this.owner) { this.owner.beingpopsplited = true; var myself = this; settimeout(function () { self.owner.beingpopsplited = false; }, 500) // 0.5 seconds after the initial popsplit } this.owner.exp += 1; //((Math.sqrt(prey._sizeSquared)) / 20) };
            this.owner.exp += 1;
        }
};`

**Comment by FantasyIsBae** [comment]
^^^

**Comment by AlexHGaming** [comment]
^^^

**Comment by FantasyIsBae** [comment]
^^^
