### ISSUE TITLE
help if u can

### ISSUE THREAD

**Issue by hossemThecoder** [Megabyte918/MultiOgar-Edited#1216]
how can i disable split in specific gamemode ?!
ps: im try to make new gamemode

**Comment by AlexHGaming** [comment]
@hossemThecoder Change the maxcells to 1?

**Comment by ZfsrGhS953** [comment]
@AlexHGaming Then viruses will have no effect.

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 Hmm... good point.

**Comment by hossemThecoder** [comment]
:/ yes virus  have no effect.

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 Aren't virus max cells and player max cells linked together?

**Comment by ZfsrGhS953** [comment]
@AlexHGaming Yes. Should I make a PR to separate them?

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 That would be recommended.
