### ISSUE TITLE
Virus Design

### ISSUE THREAD

**Issue by yetkinaykan** [Megabyte918/MultiOgar-Edited#1218]
Hi, 
How do I change the design of the virus,food?

**Comment by FantasyIsBae** [comment]
This is client sided.

**Comment by ArixProject** [comment]
@ghost In the client

**Comment by Agarian** [comment]
Deleted user lol

**Comment by Fan7asy** [comment]
@ghost you may change some of the variables for each entity.
These may include `isSpiked`; `isAgitated`.

**Comment by Agarian** [comment]
@Fan7asy that account no longer exists (hence why the profile says "deleted user")

**Comment by Fan7asy** [comment]
Its been a deleted user for 10+ months now @Agarian

**Comment by Fan7asy** [comment]
The account was supposedly deleted when OgarUl shut down.

**Comment by Agarian** [comment]
I'm just saying, it's pointless mentioning it

**Comment by Fan7asy** [comment]
Well the account is the creator of the question/issue so it would only make sense to mention it. Right?
