### ISSUE TITLE
Minion name not showing on leaderboard

### ISSUE THREAD

**Issue by TehRealShot** [Megabyte918/MultiOgar-Edited#1219]
Is there a way to get minion names to show on leaderboard?

**Comment by gyeyoqu** [comment]
Yes, you can

**Comment by TehRealShot** [comment]
How?

**Comment by MiraMiPalo** [comment]
delete player.isMi
https://github.com/Megabyte918/MultiOgar-Edited/blob/acc0fbd76c5e421de7ccfeaa9d2b20242d976684/src/gamemodes/FFA.js#L28

**Comment by TehRealShot** [comment]
@MiraMiPalo They still don't show on leaderboard

**Comment by TehRealShot** [comment]
I also had to delete "this.isMinion" on line 203 in PlayerTracker.js

**Comment by Agarian** [comment]
The purpose of this is to substantially decrease lag, as PlayerTracker will not have the need to "Track" the minions on leaderboards, playerlists, etc.
