### ISSUE TITLE
Server stops connecting

### ISSUE THREAD

**Issue by VexxusArts** [Megabyte918/MultiOgar-Edited#122]
I have a weird issue.

So servers are running fine then suddenly server goes "down"

I checked my linux and saw that server process was still running fine, I could even connect to the screen and send commands etc and there was 0 errors. I checked log file also 0 error. And stats port worked fine. Basically everything working fine but no one can connect to that server and i had to restart to fix it. Even PM2 doesnt report an error..

Any idea what this bug is? Even port was still open..

**Comment by PsycoYT** [comment]
same error

**Comment by systemroot** [comment]
with what command do you start your server when this happen?

**Comment by PsycoYT** [comment]
@systemroot  i star my server without pm2 and i have same error

**Comment by Megabyte918** [comment]
@VexxusArts I cannot help you as it is not a server-sided problem. Check if there is something wrong with the client you are using, your network, check if your ports are set up correctly, try using a different browser, or disable extensions/scripts

**Comment by VexxusArts** [comment]
other people have the same error tho..

**Comment by Megabyte918** [comment]
@VexxusArts If they are all using the same client that you are using to connect to the server with, and they can't connect either, then it is a problem with the client. Either that or you don't have your ports setup correctly.

**Comment by VexxusArts** [comment]
I have tested with multiple clients. Server is running fine then suddnly no one can access.

**Comment by Megabyte918** [comment]
@VexxusArts Then it is either your network or the way you have your ports setup, I cannot help you with this problem because this has nothing to do with MultiOgar.
