### ISSUE TITLE
Error?!

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1220]
Hello!

Why when you add code to the file PlayerCell.js
```javascript
PlayerCell.prototype.onEat = function(prey) {
   this.owner.exp += 1; //((Math.sqrt(prey._sizeSquared)) / 20)
};
```
when I start to play and eat cells, the supply is not increased. Even if I add myself 1000 weight and eat cells, the mass still does not increase. What to do? The error console does not give.

If you don't know the solution to this problem, then please do not intervene because I need a solution which is checked. I'll close the question once I get an answer on this issue. FOR ME CLOSE IS NOT NECESSARY!

**Comment by AlexHGaming** [comment]
Custom code is not provided 🤔

**Comment by AlexHGaming** [comment]
This is old code - I can't see onEat in the current version 🤔

**Comment by ZfsrGhS953** [comment]
@TopoR1 [Duplicate!](https://github.com/Megabyte918/MultiOgar-Edited/issues/1215#issuecomment-326294642)
@MastaCoder @Megabyte918

**Comment by gyeyoqu** [comment]
@TopoR1 
You do not even know what you do.

**Comment by ZfsrGhS953** [comment]
@AlexHGaming He finally upgraded to a **two**-directional pager.

**Comment by Luka967** [comment]
XD

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 XDDD

**Comment by gyeyoqu** [comment]
Regarding the question, you will never increase the mass with that small value, since you lose more mass than you gain

**Comment by FantasyIsBae** [comment]
Help is not provided for custom code.

**Comment by TopoR1** [comment]
@FantasyIsBae The reason why you closed the question? You gave an answer?! This piece of code works Tyler3D, but not Megabyte918 and would like to see the code worked fine, since the project Tyler3D closed forever. And this project is very well optimized and I copied the project Tyler3D on Megabyte918, but ran into the problem described at the beginning of the question.
@Megabyte918, help, please, except you, who do not help:(

**Comment by AlexHGaming** [comment]
@TopoR1 Use tyler's fork then.

**Comment by FantasyIsBae** [comment]
It is custom code.
As @ZfsrGhS953 said already:
>------
@TopoR1 MastaCoder already said this:

> No support is provided for custom code.
>
This is not the MultiOgar-Edited-Unlimited repository.
**And don't create duplicates.**

**Comment by TopoR1** [comment]
@FantasyIsBae Here custom only
``javascript
this.owner.exp +=1;
``
and the rest is taken from the file `cell.js` which is a server and related exactly to this problem. 

Paste the file into the `playerCell.js` a normal function
``javascript
PlayerCell.prototype.onEat = function() { };
``
and you will see that it is not working properly and needs fixing. 

and I'm sure you're not in check, you only have to defend their point of views and not to help people.

Round

**Comment by ZfsrGhS953** [comment]
@TopoR1 If you:
**Are blind:** Visit a doctor.
**Want to get banned:** Just imagine that you already are.
**Are trolling:** Troll a chatbot instead.

**Comment by FantasyIsBae** [comment]
Wise words...

**Comment by FantasyIsBae** [comment]
@TopoR1 There is nothing wrong with the code in cell.js...

**Comment by Luka967** [comment]
@TopoR1 Have you even declared the `exp` variable in PlayerTracker.js beforehand?

**Comment by ZfsrGhS953** [comment]
@Luka967 It is optimized, but it's still very slow because Node.js isn't C# (or assembly, which I will use to make my third server implementation (second if only counting implementations that have been made from scratch))

**Comment by TopoR1** [comment]
@Luka967 Yes, of course

**Comment by Luka967** [comment]
Use `console.log` then and investigate yourself then.
