### ISSUE TITLE
Is it possible to play like Dual agar "Multibox"?

### ISSUE THREAD

**Issue by rahmat15** [Megabyte918/MultiOgar-Edited#1222]
Hi, is it possible to play multibox like in dual agar by using tab key? but it has to be in 1 browser window only. 
If it's possible, please tell me how. :)

**Comment by AlexHGaming** [comment]
Client sided.

**Comment by ZfsrGhS953** [comment]
@AlexHGaming It's not client sided (Switching with the Q key and giving the controlled player a brighter color)

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 Camera focus has to be changed. Otherwise, it's duplicated.
#294

**Comment by AlexHGaming** [comment]
Looks like it isn't client sided :/

**Comment by ZfsrGhS953** [comment]
@AlexHGaming I just played dual agar, and the focus doesn't change when I press Tab.

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 Don't you have to change camera focus to a new cell when hitting tab?

**Comment by ZfsrGhS953** [comment]
@AlexHGaming That would be annoying, and as I said dual agar doesn't change camera focus.

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 hmm... ok

**Comment by AlexHGaming** [comment]
It's duplicated for sure like I mentioned.

**Comment by rahmat15** [comment]
it will be really cool if we can play like dual agar by using ogar :D

**Comment by FantasyIsBae** [comment]
As said by Alex, this is a duplicate.
I would refer to Megabyte's response on issue #294
