### ISSUE TITLE
Join Dev Nation?? Closed?

### ISSUE THREAD

**Issue by Gamedevolop** [Megabyte918/MultiOgar-Edited#1223]
Hey How You doing,

Did you close down the discord Join Dev Nation?? I cannot log in for a long time 

https://github.com/Megabyte918/MultiOgar-Edited/issues/1153

**Comment by FantasyIsBae** [comment]
Dev nation has been shut down.

**Comment by FantasyIsBae** [comment]
NOTE: Multiogar-Edited it not related to Dev-Nation so please do not create issues about it here.

**Comment by Gamedevolop** [comment]
@FantasyIsBae  I see thanks for letting me know, 

what a shame was pretty good I hope you open it again in the future

**Comment by AlexHGaming** [comment]
🤔
