### ISSUE TITLE
Scale Resolution For Mobile  Different than Desktop version

### ISSUE THREAD

**Issue by Gamedevolop** [Megabyte918/MultiOgar-Edited#1224]
Hi, 

When I play with MultiOgar on mobiles the Scale resolution is much much smaller than the Agario Mobile and it lags quite a lot, it looks like Agario have two differents scales ratios settings one for Desktops and one for Mobiles. 
does any one please know the scale Ratio that they use on the Agario Mobile app version? or something close to it? 
I think they do the Mobile scale version differently to save performance, as I notice it lags quite a lot on mobiles using the MultiOgar default scale settings as it meant to be for desktops probably only, it looks like on Agario mobile version they use double the scale so the players, food etc...looks bigger  and you can see less of the Map better for performance 

Thank you in advance

**Comment by MastaCoder** [comment]
Client sided.
