### ISSUE TITLE
Lack of reality in the server

### ISSUE THREAD

**Issue by Hydra4dude** [Megabyte918/MultiOgar-Edited#1226]
Hello, I noticed a lack of reality in the server Multiogar 1.6.1 compared to the game Agar.io, for example, does not give the feeling of being in an original server of Agar.io but without people, only bots. I wanted to ask why and ask for improvement on this.

**Comment by ZfsrGhS953** [comment]
@Hydra4dude If you have a cluster with thousands of GPUs, you can try to code a neural network with CUDA/OpenCL and interface it with MultiOgar-Edited. But this will never be included in the master branch, because most users of MultiOgar-Edited aren't millionaires.

**Comment by Hydra4dude** [comment]
:(

**Comment by FantasyIsBae** [comment]
The code is given to you, it is optimised really well, If you would like to code something along the lines of Elon Musk's AI. Then I Invite you to, but this will impact the performance of the server a lot.
