### ISSUE TITLE
Restarting message

### ISSUE THREAD

**Issue by ArixProject** [Megabyte918/MultiOgar-Edited#1227]
how?
this.gameServer.sendChatMessage(null, this.playerTracker, "The winner is + playerTracker.winner");

**Comment by AlexHGaming** [comment]
How are you defining "winner"?

**Comment by ArixProject** [comment]
oops :D
this.gameServer.sendChatMessage(null, this.playerTracker, "Restart");

**Comment by ArixProject** [comment]
server sided yes?

**Comment by AlexHGaming** [comment]
@ArixProject Yes it is. What is the cause of it restarting?

**Comment by ArixProject** [comment]
To restart, I wrote to chat

**Comment by ArixProject** [comment]
![image](https://user-images.githubusercontent.com/29149118/30227082-090486b2-94e1-11e7-9200-9da40594a28f.png)
xD

**Comment by AlexHGaming** [comment]
If you want it to restart it after a certain event you can do the following in playertracker:
```javascript
this.gameServer.sendChatMessage(null, client, "restarted");
```
after what event you're restarting off.

**Comment by ArixProject** [comment]
Where to insert the code?

**Comment by AlexHGaming** [comment]
After where you put such "restart"

**Comment by ArixProject** [comment]
![image](https://user-images.githubusercontent.com/29149118/30228466-8eeb6b06-94e6-11e7-9f01-5ad4b062a216.png)
wow error :D

**Comment by ArixProject** [comment]
Closed

**Comment by MiraMiPalo** [comment]
you want the name of the winner?  i can do but only if the restart is for mass xD

**Comment by MineMooreALT** [comment]
@ArixProject  Nice you used my website :/ just saying i spent quite a fair bit of time on it and its not nice to not credit nor pay me

**Comment by fayizan** [comment]
@MineMooreALT minemoore.xyz/ agar.js XD

**Comment by Wair1o17** [comment]
@MineMooreALT Hahaha, nice to wear something stolen that you stole from me :b @ArixProject
