### ISSUE TITLE
Seperate Bot's Mass and Human's Mass

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1228]
I don't think this is duplicated, I searched and couldn't find any duplicates but:
How can you make it so bots can spawn in with x mass, while humans can, for example, spawn in with 5000 mass?

**Comment by FantasyIsBae** [comment]
This is similar to minions spawning with a different mass to the players,
So just replace the `addBot` function within BotLoader.js with the following:
```JS
BotLoader.prototype.addBot = function () {
    var BotPlayer = require('./BotPlayer');
    var s = new FakeSocket(this.gameServer);
    s.playerTracker = new BotPlayer(this.gameServer, s);
    s.packetHandler = new PacketHandler(this.gameServer, s);
    s.playerTracker.spawnmass = 100;

    // Add to client list
    this.gameServer.clients.push(s);
    
    // Add to world
    s.packetHandler.setNickname(this.getName());
};
```

Replace the 100 with any other value, or create a config for it.

**Comment by AlexHGaming** [comment]
I will try this.

**Comment by AlexHGaming** [comment]
@FantasyIsBae Not working.

**Comment by AlexHGaming** [comment]
Working, but it's size not mass.
Closing.
