### ISSUE TITLE
Question (again)

### ISSUE THREAD

**Issue by Agarian** [Megabyte918/MultiOgar-Edited#1229]
This seems to have been an issue for a long time: Teams mode.
I want to know if teams mode has or has not been fixed (since @Megabyte918 won't come on Discord).
Either way, it happens immediately after startup. This seems to be the error I get all the time:

`[FATAL] TypeError: Cannot read property 'team' of null
    at Teams.onCellAdd (/home/ubuntu/workspace/src/gamemodes/Teams.js:41:12)
    at GameServer.addNode (/home/ubuntu/workspace/src/GameServer.js:202:274)
    at GameServer.spawnCells (/home/ubuntu/workspace/src/GameServer.js:605:38)
    at GameServer.mainLoop (/home/ubuntu/workspace/src/GameServer.js:450:55)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)`

And if this is not fixed, any suggestions on how to fix this? Cause it has been like this for a while.
**Side Note:** I have found that the teams leaderboard is working in the latest protocol (along with others). **Server version is 1.5.1**

**Comment by AlexHGaming** [comment]
> Side Note: I have found that the teams leaderboard is working in the latest protocol (along with others).

so #482 would need to be closed.

Megabyte always comes on discord lol, we're just doing some behind the scenes that are off-topic to this repo, so he rarely checks this repo and cleans it. **cough gonna get him here when he comes online**

**Comment by Agarian** [comment]
Thing is, the error occurs at the `onCellAdd` function in `Teams.js`
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gamemodes/Teams.js#L85
Remove that line of code, and you will find that the leaderboard works just fine in the latest protocol. BUT, by removing this code, apparently the server has no idea what team you got set on, so your team color seems to constantly change, as the server TRIES to figure out what team you got assigned.

**Comment by Luka967** [comment]
Line references in the error don't match. I can't even find when is the function called.
I won't even look into this. I'm honestly tired of this code; I'll try to get some free time in the next week to rewrite all this. It *will* take some time.

**Comment by retslac** [comment]
Lo and behold, i'm alive!

@Agarian Been a long time.  I haven't been following Ogar for more than a year.  By the look of your error i think you are trying to add the wrong celltypes (cells without an owner) to the team nodes array.  

Maybe try this:
```javascript
if (cell.cellType == 0) {
    this.nodes[cell.owner.team].push(cell);
}
```

**Comment by Agarian** [comment]
Retslac lives! But anyways, I will try that.

**Comment by Agarian** [comment]
@retslac I regret to inform you that this code did not exactly work. While the server did not crash on startup, it does give the following effect I described in the first message: 
http://i.imgur.com/I827Elz.gifv

**Comment by Agarian** [comment]
AlexHGaming gives the thumbs up emoji -.-

**Comment by AlexHGaming** [comment]
lmao

**Comment by AlexHGaming** [comment]
i did that because im here when you commented xD

**Comment by retslac** [comment]
@Agarian Strange behavior.  But i'm not familiar anymore with latest protocols or with your code so i have no idea how to fix this problem.  Maybe @Luka967 will be able to help you?

**Comment by ZfsrGhS953** [comment]
@Agarian ```MultiOgar-Edited 1.5.1``` Are you out of your time? Update to 1.6.1 and try again.

**Comment by Agarian** [comment]
Might I add that the latest version of MultiOgar-Edited has at least twice the amount of bugs that 1.5.1 does @ZfsrGhS953

**Comment by ZfsrGhS953** [comment]
@Agarian Then post all of them here. No one can fix the bugs if only you know about them.

**Comment by Agarian** [comment]
Be careful what you wish for.
Here we go:
- The teams leaderboard doesn't work
- Hunger games has a border bug (which cuts off 3/4ths of the map)
- Whenever you do not have a name, the text `An unnamed cell` will actually appear on your cell.
- Sometimes configurations will refuse to work entirely, as if it doesn't read `gameserver.ini`
- Sometimes the leaderboard doesn't appear on the Rainbow gamemode
And I thought I'd add that I continue to find more as I go.

**Comment by ZfsrGhS953** [comment]
@Agarian 
1. Already reported, but I don't have time to fix it due to me working on another project (and I will get banned if I mention it here). Wait for someone else to fix it.
2. HungerGames changes some config values by itself, which MultiOgar-Edited doesn't like much.
3. That's an intentionally added feature for buggy clients that don't replace empty leaderboard entries with "An unnamed cell". But it has been implemented in a bad way, instead of including it in the leaderboard packets, the fix replaces empty names in the **spawn** packets with "An unnamed cell"
4. Are you running MultiOgar-Edited from a network mounted drive?
5. Attempt to reproduce the bug on multiple clients. If it doesn't happen on all of them, it's client sided.

**Comment by Agarian** [comment]
For 4, it turns out I was not, my mistake.
For 5, I've seen this happen on the only clients I can access, being protocols 5, 6, 7, and 14. It can happen when a new player connects to the server, but doesn't spawn. Minor bug, but an OCD person like me (or those using free-roam spectate for extended periods of time) would find it annoying.

**Comment by AlexHGaming** [comment]
@Agarian idk

**Comment by Agarian** [comment]
Well, I ended up finally finding what caused this crash, the dumbest thing possible:
`this.haveTeams = true;` was missing in Teams.js -_-
