### ISSUE TITLE
Agario Page Not Working!!

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#123]
When i do agar.io/?ip=localhost:443
My page is stoping on agario i cant close the tab....
i have 2 scripts only why

**Comment by NameYT** [comment]
@Megabyte918 
![image](https://cloud.githubusercontent.com/assets/20871314/20789124/514e2232-b7ee-11e6-9750-3e30cf337bdd.png)

**Comment by MineMooreALT** [comment]
only you samby

**Comment by NameYT** [comment]
lol

**Comment by Firekix** [comment]
Yea fr me too its not loading..... Iam using 2 scripts together(custom skins and E R controls).....

**Comment by Gimmo** [comment]
Todays version working fine with diferent clients including agar.io. Check your setup.

**Comment by ZfsrGhS953** [comment]
There may be some conflicts when you use more than one script. They don't happen always, but in your case (custom skins and ERTP controls) a conflict happened. Disable the script that's less necessary for you.

**Comment by Megabyte918** [comment]
@NameYT It's because the URL of the skin that you are using is invalid, make sure it ends with .jpg, .bmp, .png, or .gif

**Comment by Megabyte918** [comment]
Fixed, sorry for the long wait
