### ISSUE TITLE
Fatal Error MultiOgar Help me

### ISSUE THREAD

**Issue by User123456789123** [Megabyte918/MultiOgar-Edited#1230]
[INFO ] MultiOgar 1.2.69 - An open source multi-protocol ogar server
[INFO ] 0 IP ban records loaded.
[WARN ] User account "Local Administrator" disabled
[WARN ] User account "Local Moderator" disabled
[WARN ] User account "Local User" disabled
[INFO ] 0 user records loaded.
[INFO ] 25 bad words loaded
[WARN ] TLS: not supported (SSL certificate not found!)
[INFO ] WebSocket: ws
[ERROR] Stats Server: listen EACCES 0.0.0.0:88
[INFO ] Listening on port 8081
[INFO ] Current game mode is Free For All
>[FATAL] TypeError: Cannot read property 'headers' of undefined
    at GameServer.onClientSocketOpen (/home/cabox/workspace/MultiOgar/src/GameServer.js:273:115)
    at emitTwo (events.js:88:13)
    at WebSocketServer.emit (events.js:173:7)
    at /home/cabox/workspace/MultiOgar/node_modules/ws/lib/WebSocketServer.js:88:16
    at WebSocketServer.completeUpgrade (/home/cabox/workspace/MultiOgar/node_modules/ws/lib/WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (/home/cabox/workspace/MultiOgar/node_modules/ws/lib/WebSocketServer.js:197:10)
    at Server.<anonymous> (/home/cabox/workspace/MultiOgar/node_modules/ws/lib/WebSocketServer.js:87:14)
    at emitThree (events.js:98:13)
    at Server.emit (events.js:176:7)
    at onParserExecuteCommon (_http_server.js:401:14)

**Comment by ZfsrGhS953** [comment]
@User123456789123 You're running the wrong server (MultiOgar). Run MultiOgar-Edited instead.

**Comment by AlexHGaming** [comment]
@User123456789123 ^^^

**Comment by AlexHGaming** [comment]
@Megabyte918 close it you mega faggot

**Comment by ZfsrGhS953** [comment]
@AlexHGaming Do you realise that you mentioned Megabyte918 instead of mentioning User123456789123 again?

**Comment by AlexHGaming** [comment]
@User123456789123 close it
@ZfsrGhS953 lmao

**Comment by User123456789123** [comment]
Help me

**Comment by Wair1o17** [comment]
@User123456789123 that is MultiOgar 1.2.69, this project is MultiOgar-Edited.

**Comment by User123456789123** [comment]
Ok tanks

**Comment by User123456789123** [comment]
How auto restart like wair.io

**Comment by AlexHGaming** [comment]
I managed to make auto restarts made by @cowpits , but I ain't sharing about it yet.

**Comment by AlexHGaming** [comment]
And @User123456789123 please close issue.

**Comment by ZfsrGhS953** [comment]
@AlexHGaming 
```but I ain't sharing about it yet.```
Did Andrews hack your account?

**Comment by ZfsrGhS953** [comment]
@AlexHGaming Keep in mind that this is an open source project.

**Comment by cowpits** [comment]
@AlexHGaming lol teaser. I'm going to do a tutorial on the auto-restart but thanks for the credit. Feel free to do a PR if you like. 

@User123456789123 Don't use MultiOgar 1.2.69 it's old and deprecated. As everyone mentioned use MultiOgar 1.6.1 which has all the fixes and works with agar.io client since Miniclip decides to screw us every 4 months or so.

**Comment by AlexHGaming** [comment]
@cowpits lmao
_copyright @cowpits 2017_

**Comment by cowpits** [comment]
@AlexHGaming lol legal mumbo jumbo xD

**Comment by AlexHGaming** [comment]
@cowpits xD
_waiting 1 week for an issue that needs to be closed_

**Comment by DeadLord1337** [comment]
@AlexHGaming https://www.youtube.com/channel/UCFYFShs-wwEnB4oi3KX3UWQ xDDDDDDDDDDDDDDDDDD looololol

**Comment by AlexHGaming** [comment]
@DeadLord1337 he's my fav youtuber dont take the piss out of him k
