### ISSUE TITLE
Question - Server Commands In Client?

### ISSUE THREAD

**Issue by xN3BULA** [Megabyte918/MultiOgar-Edited#1231]
Is it possible to issue server commands in a client?

**Comment by ZfsrGhS953** [comment]
@xN3BULA Yes, but it's a large security issue unless you use wss. Since wss is laggy in node.js, it was removed by Megabyte918. It's better to stay on SSH, even if the black and white console is not comfortable to use.

**Comment by xN3BULA** [comment]
Hmm okay...  I was planning on adding server commands to my game chat but since its  a security issue I wont proceed with it.

**Comment by Wair1o17** [comment]
Try with cigar, that has it
