### ISSUE TITLE
(Merge time) How is MultiOgar-Edited calculating it 

### ISSUE THREAD

**Issue by Gamedevolop** [Megabyte918/MultiOgar-Edited#1232]
Hey how you doing, 

Not Duplicate I checked

I have been looking for days for how is been calculated the (Merge Time) in MultiOgar-Edited but I'm not sure if I'm blind or I cannot figure it out, I looked everywhere for **(playerRecombineTime)** but I couldn't find it mentioned anywhere both (how you aply the time & how you compare it) to allow the cells to merge.

the Base is **(playerRecombineTime) = 30**  but how does it go up according to the size of the cells?
I looked at all the issues and this [https://github.com/Megabyte918/MultiOgar-Edited/issues/309](url)
is the only one that I see that goes in depth about the subject but is still not very clear how it does it with the Cells.Age

Do you follow the Formula  **"TTR = max(30, rounddown(cell.Size * 0.2));"**  like in this Wiki page mentions [http://agar.gcommer.com/index.php?title=Formulas](url)  or you use a different method of calculating it,

Where can I find the MultiOgar-Edited source code where you calculate how long each cell has to wait before can merge again

Thank you in advance

**Comment by AlexHGaming** [comment]
@gyeyoqu I need your help. Please help this guy as you are so good at coding.

**Comment by gyeyoqu** [comment]
@Gamedevolop 
```
var time = this.config.playerRecombineTime,
base = Math.max(time, cell._size * 0.2) * 25;
```

It will find the max value between the `time` and the `cell size * 0.2`,so the major value will be multiplicated for 25.

`cell._canRemerge = cell.getAge() >= base;` 
After if base is less or equal the player will remerge,

**Comment by Gamedevolop** [comment]
@gyeyoqu That's Great Thank you so much I get a better picture now I see like you dt corrected cool

I still Can't see the link though with this formula and the one we use in MultiOgar, as the part to check for Merging is a bit confusing because it checks for  a Fix number **(13)** I was expecting to see the comparison against the "Base" because it will vary depends on the cell size but (13) doesn't vary that's why I got very confused. unless I'm looking in the wrong place jeje

**Example:**  from Source Code **GameServer.js**
[https://www.dropbox.com/s/kp1ckm69bby5jgt/Collisions.png?dl=0](url)

And the same for the Cell.getAge( ) I can't see where the Age gets affected by the cell.size 
**Example:** Source code found in entity:  **Cell.js**
[https://www.dropbox.com/s/h9dtkd4no3uiywh/cell.Age.png?dl=0](url)



The formula you wrote gyeyoqu I think is the best and easier to understand it would be cool if Multiogar has that set Up will avoid many future confusions :) for learning purposes, but hey MultiOgar is the best Organised and structure Project I see in GitHub with clear variables names and everything commented so it doesn't border me just a suggestion. 

I Guess I have to do more calculations to understand it lol

@gyeyoqu Thanks Man For the help 👍 
@AlexGaming Thanks for the help call 👍 
Thanks guy I really appreciated

**Comment by Gamedevolop** [comment]
@gyeyoqu  You know what I just found the code that you wrote in /src/GameServer.js  Line (651) I'm such an ass :)  I swear I can't remember how many times I went through the whole pages of code and I didn't see this part lol, now I see why you wrote that nice tutorial, I thought it wasn't implemented already in MultiOgar and that you were showing me how to implemented by my self jejeje hoo man I'm losing it already too much Javascript
Everything is clear already, Thanks again for the help
