### ISSUE TITLE
Server version update

### ISSUE THREAD

**Issue by Hydra4dude** [Megabyte918/MultiOgar-Edited#1233]
You editors of MultiOgar, wanted to know if it will have a new update for the server and when it could leave.
 
THANK YOU!

**Comment by AlexHGaming** [comment]
@Hydra4dude How is this really an issue?

**Comment by Fan7asy** [comment]
@Hydra4dude The server is fairly stable at the moment and does not require a version change, from time to time there are changes being made, but nothing worthy of a version change.
