### ISSUE TITLE
Is there a way to list a bot separately in the leaderboard? 

### ISSUE THREAD

**Issue by Mr-BrockLee** [Megabyte918/MultiOgar-Edited#1234]
[LB] Like different colored name ?
[IG]  Or by making the cells grey?

**Comment by ZfsrGhS953** [comment]
@Mr-BrockLee You'll have to use something other than color, because that's client sided.

**Comment by Mr-BrockLee** [comment]
@ZfsrGhS953  How abt making the cells grey?

**Comment by ZfsrGhS953** [comment]
@Mr-BrockLee That will work.

**Comment by Mr-BrockLee** [comment]
If so how?

**Comment by Mr-BrockLee** [comment]
I guess not?
