### ISSUE TITLE
How to..

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#124]
Hello guys, how to change the cell color depending the skin?

**Comment by Jhair2015** [comment]
text on cmd:  color ID "RGB color"  @PsycoYT

**Comment by PsycoYT** [comment]
DEPENDING SKIN

**Comment by Megabyte918** [comment]
@PsycoYT Not possible as the server cannot predict what skin you are going to input and what color will match said skin from the script.
