### ISSUE TITLE
Restart Spaming

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#1245]
When i start my server cmd start spaming
![image](https://user-images.githubusercontent.com/17459204/30784357-8ad3f3fc-a108-11e7-80b0-1487aadf5a50.png)

**Comment by ArixProject** [comment]
lol

**Comment by ArixProject** [comment]
![image](https://user-images.githubusercontent.com/29149118/30785063-01180b88-a169-11e7-9059-75ad876b2d0d.png)

**Comment by ZfsrGhS953** [comment]
@Gigabyte918 @ArixProject Both bugs have been fixed, it will be merged soon.

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 The error @ArixProject is showing there is that he ran index.js in the run folder.

**Comment by AlexHGaming** [comment]
And I thought putting 0 at the config was going to disable it. Turns out not xD

**Comment by ZfsrGhS953** [comment]
@AlexHGaming It's not him who ran index.js from the run folder, it's the batch file.

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 
![image](https://user-images.githubusercontent.com/23644244/30787049-832a2f7a-a178-11e7-8601-85a69aa6097c.png)

**Comment by ZfsrGhS953** [comment]
@AlexHGaming [It's here](https://github.com/AlexHGaming/MultiOgar-Edited/blob/1c64e136ffdb133df19eb8448e98fd6f57612294/run/win-Start.bat#L3)
Supposed to be ```../src/index.js```
