### ISSUE TITLE
auto-restart upon reaching a specific mass

### ISSUE THREAD

**Issue by josefredohd** [Megabyte918/MultiOgar-Edited#1247]
it's possible?

**Comment by Wair1o17** [comment]
it's possible?

Yes

**Comment by josefredohd** [comment]
how

**Comment by MiraMiPalo** [comment]
te diria como! pero me tenias hasta la gaver con tus bots en Gaver.io >:v

**Comment by AlexHGaming** [comment]
This has been duplicated so many times.

**Comment by fayizan** [comment]
make it on your own :)

**Comment by josefredohd** [comment]
@MiraMiPalo xD

**Comment by AlexHGaming** [comment]
english plez

**Comment by MiraMiPalo** [comment]
why the code is a secret? xD

**Comment by josefredohd** [comment]
idk :(

**Comment by plazo123** [comment]
are you kidding me thats probably the easiest thing to do in multiogar

**Comment by Fan7asy** [comment]
Duplicate.

**Comment by Mr-BrockLee** [comment]
@plazo123  Than HOW???
