### ISSUE TITLE
Colored name *like a blue,green,orange*

### ISSUE THREAD

**Issue by ArixProject** [Megabyte918/MultiOgar-Edited#1248]
And so how?

**Comment by Agarian** [comment]
This is not only a duplicate, but this is also a client sided issue.

**Comment by ArixProject** [comment]
okay client sided

**Comment by ArixProject** [comment]
stop
in the server only how?

**Comment by ArixProject** [comment]
or server sided?

**Comment by Fan7asy** [comment]
This is a client sided issue.

**Comment by Agarian** [comment]
Most clients these days are older ones that still have a `main_out.js` file. If you have your own client, look in said file for what gives each cell a name, and look for what defines the color of the name.

**Comment by ArixProject** [comment]
okay

**Comment by Fan7asy** [comment]
Its usually done by a text engine named `UText` or something along those lines.

**Comment by ArixProject** [comment]
@Agarian i have Luka967/Cigar

**Comment by ArixProject** [comment]
and one issue
How to make that by nick was the userrole "admin"
*bad english*

**Comment by ArixProject** [comment]
@Fan7asy

**Comment by Fan7asy** [comment]
@ArixProject I assume the line is [here](https://github.com/Luka967/Cigar/blob/master/www/assets/js/main_out.js#L1494)  if you want to change the color of the text.

**Comment by Fan7asy** [comment]
Please elaborate on your other issue

**Comment by ArixProject** [comment]
@Fan7asy thanks)

**Comment by Fan7asy** [comment]
No problem, do you still require help with your other issue?

**Comment by ArixProject** [comment]
yes of course

**Comment by Fan7asy** [comment]
Do you mean: make the nickname be set automatically by userrole?

**Comment by ArixProject** [comment]
yes

**Comment by Fan7asy** [comment]
One moment.

**Comment by ArixProject** [comment]
kk

**Comment by ArixProject** [comment]
and????

**Comment by Fan7asy** [comment]
One moment, I'm trying to sort out two issues at once.

**Comment by ArixProject** [comment]
okay

**Comment by Fan7asy** [comment]
First you will need to put the `UserRoleEnum` variable into global focus.
In order to do this move [Line 75](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L75) to the top (somewhere about [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L4));

Next replace [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L139) with:
```JS
    if (this.userRole === UserRoleEnum.ADMIN)
    this.setName("A NAME");
    else 
    this.setName(name)
```

**Comment by ArixProject** [comment]
thanks

**Comment by ArixProject** [comment]
and one issue :D (in color name)

**Comment by ArixProject** [comment]
how to make color name on other name?

**Comment by Fan7asy** [comment]
Yes?

**Comment by ArixProject** [comment]
![image](https://user-images.githubusercontent.com/29149118/31048746-969b9568-a62c-11e7-8fd8-aa5ca8695d43.png)
i tried but not working

**Comment by Fan7asy** [comment]
I don't use Cigar, so you are going to have to ask @Luka967

**Comment by ArixProject** [comment]
oh okay((

**Comment by ArixProject** [comment]
wow shit :D
![image](https://user-images.githubusercontent.com/29149118/31048760-140e5742-a62d-11e7-99cb-84859b429a02.png)

**Comment by Fan7asy** [comment]
Did it work then?

**Comment by ArixProject** [comment]
@Fan7asy ummm.. nope
