### ISSUE TITLE
[feature request] Merge CommandList+PlayerCommand

### ISSUE THREAD

**Issue by cyclopentan** [Megabyte918/MultiOgar-Edited#1249]
Make one place to store all commands.
Add command's property privilege level(Console, Admin, Moder, User).

1) require("Command.js")
2) configure Logger or writeLine usage

Advantages:
-WebAdmin don't needed, all commands available from console
-One place to apply changes

Help display don't fits to chat. How to solve:
1) Pages
2) "See console help" stub

Why not?

**Comment by AlexHGaming** [comment]
???

**Comment by ArixProject** [comment]
wtf?

**Comment by ArixProject** [comment]
Do you want to make your Goth?

**Comment by ArixProject** [comment]
do you want as in ogarul?

**Comment by Agarian** [comment]
Why exactly should we merge the two files? CommandList is already large enough.

**Comment by cyclopentan** [comment]
They implement same functionality - commands. For example user "/mass" command is same with console "mass" command. Seems, that PlayerCommand.js is cut version of CommandList.js with some additions: pretty chat print and rights check.

I wish to make all commands availabe to user admin from chat. This is good idea, because extra tab don't needed and no need to edit two files: all commands stored in one place.

Because of file size limitation we can leave all files, but need to remove code duplication

**Comment by AlexHGaming** [comment]
@cyclopentan The reason we have /mass in chat is because we have something called "UserRoles", where people with a certain IP (or leave it blank for any IP) can login as an admin. Not all admins have terminal control, therefore more than 1 person who doesn't host the server can use the command from there.

**Comment by cyclopentan** [comment]
@AlexHGaming And why admin(chat user with admin role) can use only 7 of 25+ commands?
For example this commands is unavailable: pause, change, explode, pop, replace, tp, split, rec, color, speed, freeze.
Minimal solutions is proxy unfound in PlayerCommand to CommandList if user is admin.

It's feature request, not a bug

**Comment by cyclopentan** [comment]
If there is two types of admins: server-admin and game-admin, and game-admin willn't get access to other commands(that i listed in previous message) we can make two admin roles.
For me admin will have access to all commands, and it he can do it from console it is excellent
