### ISSUE TITLE
Segmentation fault, wut

### ISSUE THREAD

**Issue by systemroot** [Megabyte918/MultiOgar-Edited#125]
i got a new dedicated server and i was trying to setup a server. 
so i started, i start to play i add 1K minions for myself after 1 min server is closed with a output **" > Segmentation fault "**

reading somewhere in google about that http://stackoverflow.com/questions/3200526/what-is-a-segmentation-fault-on-linux

anyone know how to fix this?!

**Comment by Megabyte918** [comment]
@systemroot interesting.. is this reoccurring or did it just happen once?

**Comment by systemroot** [comment]
@Megabyte918 it's happening everytime i can you i can't play with it :/

**Comment by Megabyte918** [comment]
Try reverting https://github.com/Megabyte918/MultiOgar-Edited/commit/4e084a315f7d5ebcff768e9ef0a258e5ef8a71b0

**Comment by Tyler3D** [comment]
@Megabyte918 Can you go to Cloud 9?

**Comment by systemroot** [comment]
@Megabyte918  that did the magic https://vid.me/vHm1
thank you :+1:

**Comment by systemroot** [comment]
@Megabyte918  it's happening again any idea what i can do else!?

**Comment by Megabyte918** [comment]
@systemroot I couldn't reproduce this error.. try using something else than your new server and if the problem doesn't happen, then it is a problem with that server. Let me know the results

**Comment by systemroot** [comment]
i rebuild server and i changed os from centos to ubuntu,  idk how but this solved my problem
