### ISSUE TITLE
New Discord Server for MultiOgar-Edited

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1250]
Hiya, yes I do understand this isn't an issue, but this could make things easier for the repo.
Instead of me checking the repo 24/7, and others, I have made a discord server!
I've also been noticing that people keep asking me where Dev Nation has gone, but now this is like a replacement.

Join here: https://discord.gg/FGsB4mJ
Ask questions, have a talk + more. 
_btw you can leave labels like off-topic ones if the collab known as @Fan7asy wants to_

**Comment by AlexHGaming** [comment]
:(

**Comment by Agarian** [comment]
GitHub is always dead when it's a school week

**Comment by AlexHGaming** [comment]
yep

**Comment by wunzer0** [comment]
The link isn't working.

**Comment by ItzLevvie** [comment]
@wunzer0 https://discord.gg/msMVwQC

**Comment by Agarian** [comment]
Why did I get a notification here?
