### ISSUE TITLE
Virus pop split not work

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1253]
1) Please work on division from viruses! they are horrible... I have a feeling that popsplit not working because of this. The developers will review the original division from viruses.
2) End you might ask why Megabyte918 not doing updates? something happened?

**Comment by AlexHGaming** [comment]
@DeadLord1337 

> 1. Please work on division from viruses! they are horrible... I have a feeling that popsplit not working because of this. The developers will review the original division from viruses.

The virues work fine for me, but if you want to change the chances so it works better, tweak the `exp` variable in virus.js.
And also this is in the FAQ of the Wiki

>2. End you might ask why Megabyte918 not doing updates? something happened?

Megabyte is no longer working on this repo, instead something is coming up in some time by him. Let's maybe say he "disbanded" this repo.

**Comment by DeadLord1337** [comment]
@AlexHGaming I want to play the original, but with these values pop split much easier and coincides with the original.

>     // Monotone explosion(s)
>     else if (c._mass > 625) {
>         // virus explosion multipliers
>         var exp = Math.random() * (4.5 - 4.6) + 4;
>         while (threshold / exp > 24) {
>             threshold /= exp;
>             exp = 2;
>             big.push(threshold >> 0);

**Comment by AlexHGaming** [comment]
@DeadLord1337 Close?

**Comment by DeadLord1337** [comment]
@AlexHGaming  Eh... tell me, what makes a string  `c.div = 20` in virus.js  just a detail and I will close

**Comment by AlexHGaming** [comment]
@DeadLord1337 ????
That isn't a string lol

**Comment by DeadLord1337** [comment]
@AlexHGaming in short, what makes `c.div = 20` XDD

**Comment by DeadLord1337** [comment]
can do c.div = 999999999999999999999999999999999999999 what will happen

**Comment by Agarian** [comment]
He's asking what `c.div = 20` is, what it does, and what it would affect if he changed it.

**Comment by fayizan** [comment]
Try and tell us the result @DeadLord1337

**Comment by Agarian** [comment]
I have actually tried this myself, trying values such as 0, 10, 100, etc. but had not found any visible difference in virus splitting.

**Comment by DeadLord1337** [comment]
There may remove this `c.div` -_- if it is not why not to powder brains

**Comment by DeadLord1337** [comment]
@Agarian @AlexHGaming 
Сan remove very old bug where an explosion for example, 136 mass parts are not the same. the Central part is not the same as the rest.
![33](https://user-images.githubusercontent.com/24901742/31190267-4f30cf76-a943-11e7-866e-8672a630b635.PNG)

**Comment by DeadLord1337** [comment]
@AlexHGaming  @Agarian can remove very old bug when in the explosion! parts are not the same. the Central part (it is the smallest) is not the same as the rest
![33](https://user-images.githubusercontent.com/24901742/31191015-7c67cf56-a945-11e7-983f-60b8532325f0.PNG)

**Comment by AlexHGaming** [comment]
@DeadLord1337 I swear that's modified virus.js code.

**Comment by AlexHGaming** [comment]
Well it is, try using the vanilla one.

**Comment by DeadLord1337** [comment]
-_- Vanilla server settings 
![34324](https://user-images.githubusercontent.com/24901742/31229376-254079ea-a9e9-11e7-93c7-ddb7b0a570f5.PNG)

**Comment by AlexHGaming** [comment]
Hmm...

**Comment by DeadLord1337** [comment]
hmm

**Comment by ArixProject** [comment]
hmm

**Comment by Fan7asy** [comment]
hmm
