### ISSUE TITLE
small question

### ISSUE THREAD

**Issue by Niall7459** [Megabyte918/MultiOgar-Edited#1256]
I have a server.

It is a 4 Core 1GHZ CPU with 1GB RAM
and approx 1 MBPS Network UP
2 MBPS Network Down

Will this hold an Multi-Ogar Edited server for maybe around 30 players?
If not what is the reccommened hardware specifications...

Because my high end current server cannot be used at the moment...

**Comment by Niall7459** [comment]
My bad 31 MBPS download

**Comment by ArixProject** [comment]
idk

**Comment by AlexHGaming** [comment]
@Niall7459 it depends on your hoster. If you port forward then 31MBPS could be a happy way to start it.
If you're talking about FPS then that should handle it to - my potato laptop gets average 45 - 60fps off it :P

**Comment by cyclopentan** [comment]
If it's VPS, processor time is shared between virtual servers. That means in fact server can use only part of 1 GHz@4cores, but 10% is still very much. Seems, thats network speed is weak point. You can meausure used connection of one client, and then calculate it. If you do it, please share results

**Comment by cyclopentan** [comment]
I measured data rate on server with 40 bots. My result:

server to one client:
  40 KByte/s=320KBit/s when connected, but not playing
  1 KByte/s=8KBit/s on game
  50 KByte/s=400KBit/s on spectator mode

one client to server:
  0,5 KByte/s=4Kbit/s in game
  0 when not playing

Internet and server providers meausers link in KBit/s
Your server can use about 34Kbit/s from one client to server and 68KBit/s from server to one client

**Comment by cyclopentan** [comment]
If server is self-hosted maybe your router uses feature, that maximize priority of video traffic and real link is not 1 and 2 MBPS

**Comment by Niall7459** [comment]
So there is more upload used than download.

yes it is self hosted

**Comment by cyclopentan** [comment]
Do you have problem with performance or you only have interest? Seems, that 31MBPS link is ok. upload from who? Player or server?

**Comment by Niall7459** [comment]
Upload from server is approx 1 MBPS

Occasionally the game just freezes, this is at my school, so wether its the schools network I dont know. because Theres alot of people play

**Comment by cyclopentan** [comment]
My verdict - ploblem is in 1MBPS link from server to client. Only 4 connected, but playing users can freeze your server(4*320=1280>1024 KBPS).

Suggest to close issue

**Comment by Niall7459** [comment]
OH NO

**Comment by Niall7459** [comment]
Ok but will my CPU be okay???

1 GHZ  x4 Core ARM Cortex - A53

Running  alongside PHP, NGINX, MYSQL

**Comment by Niall7459** [comment]
And memory = 1 GB!

**Comment by cyclopentan** [comment]
@Niall7459 Yes. I don't calculated this, but seems that it is big values

**Comment by Niall7459** [comment]
@cyclopentan Wait to those specs will be fine for about 10 players?

**Comment by Niall7459** [comment]
Will it be slowed down if:


-- Internet ----->    My Server    ---Proxy ----> Other Server (With multiogar)
                                     |
                                     --> Website

Will this slow it down?

**Comment by cyclopentan** [comment]
It's unclear what you asking. What do you mean, when say "Connection between servers"?
Scheme is Client - Client's ISP - Internet - Server's ISP or hoster - Server
Servers can't connect directly to each other.
