### ISSUE TITLE
Consoleplus login

### ISSUE THREAD

**Issue by xN3BULA** [Megabyte918/MultiOgar-Edited#1257]
How do you login? I tried using the same login as the one I use for the ingame login but it dosnt work it just refreshes.

**Comment by ArixProject** [comment]
in vk?

**Comment by AlexHGaming** [comment]
Best Issue Ever.

**Comment by cyclopentan** [comment]
edit ./src/enum/userRoles.json - change password and ip. Or leave blank ip if you don't want to restrict another. Then ./run/console-plus.js

**Comment by cyclopentan** [comment]
@AlexHGaming It isn't obvious, becuse config file is in another place. Firstly i don't understand how to use standard login system, and (!) hardcoded my own :) Then i reading code to understand how it works

**Comment by cyclopentan** [comment]
Added to wiki. Suggest to close
