### ISSUE TITLE
40x traffic waste, when connected but not playing

### ISSUE THREAD

**Issue by cyclopentan** [Megabyte918/MultiOgar-Edited#1258]
When user connected to server, but don't playing server downstream to one client is 320Kbit/s, but in game only 8Kbit/s. Spectator mode uses about 400KBit/s.

This is indirect sign of security issue. Maybe server sends all map, but don't only user region(or best user region in spectator mode).

Also it causes freeze of server with low-wide internet stream, see #1256 issue.
Collect your own data https://gist.github.com/cyclopentan/8764216f69ae5767598efb9aadb16a1f

**Comment by fayizan** [comment]
True spectator mode uses a lot of bandwidth : |

**Comment by cyclopentan** [comment]
There is no principal difference between spectator mode and gaming: user see only visible cells. Server willn't send all cells to client in spectator mode

**Comment by ZfsrGhS953** [comment]
@cyclopentan That code doesn't show the entire bandwidth usage, because it doesn't account for the length of WebSocket, TCP and IP headers. Add 42 (2 bytes WebSocket, 20 bytes TCP and 20 bytes IP) to byteLength to get the correct bandwidth.

**Comment by cyclopentan** [comment]
@ZfsrGhS953 got it, thank you. Updated calc script. Now result is same, not more than 15% difference. You can try it, now script is user-frienly :)

**Comment by fayizan** [comment]
@cyclopentan  make pull request : |

**Comment by Agarian** [comment]
I've seen [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L186) of code in GameServer.js on multiple occasions. Exactly what is it supposed to mean? I may have an idea on what it means, but I'm not sure about it.

**Comment by cyclopentan** [comment]
@Agarian this is config of max package size. Don't change it,  it willn't solve problem, because server sends, what i willn't.
If you decrease this value, client will send more packets, and there will be more service traffic or crash

**Comment by Luka967** [comment]
@cyclopentan The server sends the cells the player can see. Unless [serverMinScale](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L50) gets reached no unnecessary cells get sent.
Zooming out farther from the standard proves this.
![image](https://user-images.githubusercontent.com/15956695/31315844-02214fb8-ac21-11e7-979c-d44ba7f01b47.png)

You can implement your own idle connection filtering by checking if mouse position changes; then you can send the remove all packet and empty update packets, and as soon as the mouse moves you're going to start sending proper updates.

But unless your bandwidth is limited it's of no large use. 164 connections spread out in 12 servers use about 5.9 MB/s upstream on the private server in the picture.

> this is config of max package size. Don't change it, it willn't solve problem, because server sends, what i willn't.
If you decrease this value, client will send more packets, and there will be more service traffic or crash

No. Multiple WebSocket frames get sent which will ultimately get merged as a single TCP fragment. It *will* lead to more upstream data being sent if used badly.

**Comment by cyclopentan** [comment]
@Luka967 Thank you for mistake fix about maxPayload. What client do you use?

**Comment by Luka967** [comment]
A heavily modified version of mine.

**Comment by cyclopentan** [comment]
@Fan7asy Problem doesn't sovled. Why close?

**Comment by Fan7asy** [comment]
Sorry my bad.

**Comment by Fan7asy** [comment]
There 🙂

**Comment by cyclopentan** [comment]
@Fan7asy OK, thank you

**Comment by ZfsrGhS953** [comment]
@Luka967 Merging multiple frames that are 40ms apart makes the ping increase by 40 ms for each frame sent. I think that a good WebSocket library should merge frames that are 5ms apart at most, 40ms looks like a rather terrible compromise of ping for bandwidth.

**Comment by ZfsrGhS953** [comment]
@Luka967 I figured that the message above is rather complicated, so I'll say this: If they actually do get merged into a single frame, why don't the cells move in bursts? :smile:

**Comment by Luka967** [comment]
@ZfsrGhS953 WebSocket frame =/= WebSocket message
A message is a series of frames with the last one having the FIN flag set.
The `maxPayload` just governs the maximum payload size of a frame.
Libraries merge messages (i.e. spectate packet & world update packet) and send them over as a single TCP fragment, so that's why they don't move in bursts.

**Comment by ZfsrGhS953** [comment]
@Luka967 Sorry, I thought that you were talking about frames from different game ticks getting merged. And sorry again for making a mistake about ping, 40ms is the maximum ping increase, average is 20.

**Comment by Luka967** [comment]
No problem xd

**Comment by MastaCoder** [comment]
Any updates?
