### ISSUE TITLE
Error in PlayerTracker.js

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1259]
Please correct this error, it is bad for performance from the player. If a player joined the server or ate it, he sees the whole field, which affects the number of FPS. 

To fix it you need to replace the line in the file [PlayerTracker.js](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js) on this [line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L130) this code
```javascript
    if (!scale) return scale = this._score = .4; // reset
```

This fix is going to be good if players with weak computers, which are difficult to open solitaire:)

**Comment by Agarian** [comment]
Alright, I may just make a Pull Request on this
