### ISSUE TITLE
This error is triggered when CollectPellets minions. How to fix?

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1262]
![image](https://user-images.githubusercontent.com/19995663/31311294-e6c7e624-abb1-11e7-9659-1e9eec89a71f.png)

**Comment by Fan7asy** [comment]
Everything works completely fine in the latest version of MultiOgar-Edited.
I am assuming you are using a modified version, we cannot help you with that.
Its your code, your issue.

**Comment by TopoR1** [comment]
@Fan7asy Changed only the name and that's not changed anything.

**Comment by Fan7asy** [comment]
`You are using a modified version of MultiOgar-Edited`

**Comment by TopoR1** [comment]
@Fan7asy Where are you from? And even more, I fixed this error, just needed to add the condition that cells have length.

**Comment by Fan7asy** [comment]
I'm originally from Poland, but I have lived in England for most of my life.

**Comment by TopoR1** [comment]
@Fan7asy  I am from Russia and I wanted to ask where did you get this, and the interpreter translated differently.

**Comment by Fan7asy** [comment]
Where did I get what?
