### ISSUE TITLE
Skins not coming up

### ISSUE THREAD

**Issue by nityoday** [Megabyte918/MultiOgar-Edited#1263]
I cannot get skins when I use the name < shark > My Name or < cougar >My Name.( without spaces in angular brackets) Also I Didn't understand how to add one . Can someone help me how to do that ?

**Comment by Agarian** [comment]
Premium skins have been patched almost a year ago now. So skins using `<>` will not work anymore. Though, I wish they did.

**Comment by AlexHGaming** [comment]
@Agarian perfect timing lmao

**Comment by Agarian** [comment]
Also, do you happen to know any clients that still use `<>` skins?

**Comment by nityoday** [comment]
Yes I Know one, can I Drop links in here ?

**Comment by nityoday** [comment]
https://www.youtube (dot) com/watch?v=_gdggDbxASo

**Comment by AlexHGaming** [comment]
aka https://www.youtube.com/watch?v=_gdggDbxASo

**Comment by Agarian** [comment]
Dude it's already been established that premium skins got patched on agar.io
I'm looking for OTHER clients that still have premium skins. Note: `<>` skins = premium skins

**Comment by nityoday** [comment]
Okay, thanks a lot, and can I get the older ogar version ( to play with skins ) which is not patched? I Had the ogar unlimited which dosen't works now.

**Comment by Agarian** [comment]
Getting an older version will not help. Miniclip themselves patched the use of premium skins on agar.io

**Comment by nityoday** [comment]
Ohkk. Thanks for helping , Agarian,,
