### ISSUE TITLE
Post your custom clients here

### ISSUE THREAD

**Issue by Agarian** [Megabyte918/MultiOgar-Edited#1264]
If anybody is interested in posting some custom clients, post them here. I'm curious to see them.

Here's my client: [agarian.github.io](https://agarian.github.io/).
Source code can be found [here](https://github.com/Agarian/agarian.github.io).

**Comment by AlexHGaming** [comment]
http://agarahg.tk
_ok shameful advertisement_

**Comment by Agarian** [comment]
It appears that I can't connect to servers with that client.

**Comment by Agarian** [comment]
@AlexHGaming Do you happen to know of any custom skin scripts? Or clients that have premium skins (besides yours)?

**Comment by Wair1o17** [comment]
@Agarian http://josefredohd.byethost7.com

that is my friend client

**Comment by Agarian** [comment]
I thought I'd mention that the custom skins script no longer works.

**Comment by cyclopentan** [comment]
What about github links? What clients exclude CigarProject/Cigar do you know?

**Comment by Agarian** [comment]
Dude honestly, I've been looking to implement premium skins into my own client, and I need one that already has them implemented to work off of.

**Comment by DeadLord1337** [comment]
http://atomical.byethost6.com/?i=1
https://trapkillo.github.io/trapclientv2/out.html#ip=127.0.0.1:443
http://agariox.net/

**Comment by TopoR1** [comment]
http://agarix.xyz/

**Comment by hossemThecoder** [comment]
Http://Agar.tn

**Comment by Fan7asy** [comment]
Here's [mine](https://github.com/Fan7asy/Client)

**Comment by cyclopentan** [comment]
@Fan7asy Wow, great job)

**Comment by Fan7asy** [comment]
Thank you @cyclopentan 🙂

**Comment by ArixProject** [comment]
cmgar.000webhostapp.com (i have a free hosting) :D

**Comment by Niall7459** [comment]
http://www.nagar.eu

gone quite downhill and unmaintained recently though.

**Comment by Niall7459** [comment]
Ah, everyone clients remind me of my game, when it first released on the 13th of October I installed a new Cigar server back in the days when the client and server were combined, Brings back such good memories!

I want to rebuild my game! :(

**Comment by xN3BULA** [comment]
http://asat-agar.online

**Comment by Wair1o17** [comment]
@xN3BULA that is athex.io game haha

**Comment by xN3BULA** [comment]
@Wair1o17 xAz lets me use it

**Comment by Agarian** [comment]
@Fan7asy yours is my favorite so far

**Comment by Luka967** [comment]
https://github.com/Fan7asy/Client/blob/master/js/main.js#L713 @Agarian

**Comment by Agarian** [comment]
Cool, now I can check that off my to-do list lol

**Comment by cowpits** [comment]
http://gkclan.me

**Comment by Fan7asy** [comment]
@Luka967 Aye

**Comment by Fan7asy** [comment]
@Luka967 What Luka said.

**Comment by Agarian** [comment]
Yeah I was about to say somebody should add a label lol

**Comment by Fan7asy** [comment]
lol

**Comment by AmorimGames** [comment]
I need good client with macros for download please can send me, skype : yt.rememberme.br

**Comment by Agarian** [comment]
I may have one

**Comment by Agarian** [comment]
Shit

**Comment by AmorimGames** [comment]
Agarian send me please,skype or discord please or public here

**Comment by Agarian** [comment]
@AmorimGames look at the very first comment in the issue

**Comment by AmorimGames** [comment]
@Agarian i need download to change to my language(portuguese)

**Comment by AmorimGames** [comment]
Forget it,i see you profile and download tnx,can send me free host?

**Comment by Agarian** [comment]
`Can send me free host?`
Not too sure what you mean by that too be honest, but if you mean send you a host that offer's free service, I can't help you on that.

**Comment by AmorimGames** [comment]
how you host you game?

**Comment by Agarian** [comment]
Oh you caught my server, didn't you? Well I use Cloud9, but it isn't free.

**Comment by AmorimGames** [comment]
hm ok tnx

**Comment by MineMooreALT** [comment]
Used to have a really good client that I had optimized alot for laggy computers and its was for my website but lack of traffic and no one playing led to me closing it.

**Comment by AlexHGaming** [comment]
Codeanywhere is a suggestion, but it is terrible in terms of ping. (192ms minimum, 240ms maximum)

**Comment by Agarian** [comment]
I personally use Cloud9, but I don't host my server. As for CodeAnywhere, I haven't heard too many good things about available RAM.

**Comment by hossemThecoder** [comment]
http://ka3boura.tn/

**Comment by ArixProject** [comment]
http://q96208pi.beget.tech/

**Comment by Agarian** [comment]
Anybody have minimap code that I can use? I'm thinking about putting one in my client.

**Comment by cowpits** [comment]
I'm using Cigar client and so far I have not had any success with getting a minimap to work. By that I mean I want a minimap to show all players not just my position. I want one like agarplus or alis.

**Comment by Agarian** [comment]
I at least want one that shows my position.

**Comment by Droppers** [comment]
https://agar.yt/

Used to be quite active, but I do not maintain it anymore. I am just keeping it online.

Thank you Megabyte918 and all contributors for MultiOgar-Edited!

**Comment by cowpits** [comment]
@Agarian see this Cigar client https://github.com/dinhduynhat/Agar-Ogar-Cigar-web-client
has minimap that shows your position. 
I have a few more clients that people have sent me but I don't use them because they're ripped. I hate when people do that so I refuse to use them. I'm willing to give them to you if you want.

**Comment by Agarian** [comment]
@cowpits Not only is that code obfuscated, but the mini map its self is broken.

**Comment by cowpits** [comment]
what about Jara's client? it has a minimap https://github.com/JaraLowell/OgarClient

**Comment by Agarian** [comment]
@Droppers I love your client! Do tell me, how would one implement a mini map such as yours?

**Comment by Niall7459** [comment]
@Droppers would you be kind enough to send me the source code?

**Comment by Niall7459** [comment]
www.nagar.eu/client2/

**Comment by ArixProject** [comment]
https://classidie.xyz/web/

**Comment by ZfsrGhS953** [comment]
@ArixProject Your website isn't working through HTTPS. But don't fall for the paid certificate scam, [set it up for free.](https://letsencrypt.org/getting-started/)

**Comment by bbcnkl** [comment]
http://agar.rs

**Comment by Droppers** [comment]
@Niall7459 there is no way I can do that, I can send you a specific part of the code.

**Comment by SAV-404** [comment]
i have the best client ever..this is it : https://www.facebook.com/SAV.404/videos/1849118388660969/
-just a video cz i don't want to share it yet.

**Comment by mafiakb** [comment]
@SAV-404 i dont see ur video

**Comment by SAV-404** [comment]
@mafiakb log in facebook first.

**Comment by Gatoz** [comment]
Hello , how do I make my client never close, should I have my computer always on?

**Comment by cowpits** [comment]
are you hosting on your computer? windows IIS? then yes keep it running.

**Comment by Niall7459** [comment]
Buy a raspberry pi like £35 I run mine 24/7 With Client and MultiOgar.

It actually handles 20 players easily. at 40 it started to struggle.
I've hd 57 players on there and you only notice that the gameplay is a bit slower.

But Once I've fixed my main server I will probably use that because of its perfomance.

**Comment by RevengePlayz** [comment]
@Niall7459 Check your mail please!

**Comment by RevengePlayz** [comment]
or add me on discord Revenge#5285 Thanks

**Comment by Mistik** [comment]
My custom client coded from scratch
https://senpa.io/web

**Comment by Faris90** [comment]
bruh
