### ISSUE TITLE
Minion random name

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1265]
Maybe add setting to minion they had different names
; [MINIONS]
randomName = 1/0

**Comment by TopoR1** [comment]
It is easy to implement, but few will help.

**Comment by AlexHGaming** [comment]
@DeadLord1337 I do not what you mean. Do you mean random names like the AI bots?

**Comment by ArixProject** [comment]
nice idea

**Comment by DeadLord1337** [comment]
@AlexHGaming yes

**Comment by Fan7asy** [comment]
Replace [line 70](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/BotLoader.js#L70) in `BotLoader.js` with the following:

```JS
   name = this.getName();
```
Now if you add minions without specifying a name, the name will be random.
The names are taken from `BotNames.txt`.

**Comment by DeadLord1337** [comment]
@Fan7asy Oh noice thx
