### ISSUE TITLE
How to know how much the player's minions?

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1266]
I don't know, but maybe it's
```javascript
this.miQ
```
 in PlayerTracker.js?

**Comment by AlexHGaming** [comment]
You can't really tell how many minions the player has.

**Comment by Agarian** [comment]
Yeah, `this.miQ` jusy defines whether a player has control of minions via the Q key.

**Comment by TopoR1** [comment]
I made it! HURRAH!!! Was rotted to suffer as numbers at addition didn't consist of the server, and stuck together)
![image](https://user-images.githubusercontent.com/19995663/31579903-5779d7c8-b149-11e7-82a8-400f1b44f924.png)

**Comment by AlexHGaming** [comment]
@TopoR1 close

**Comment by Agarian** [comment]
@TopoR1 How did you implement premium skins anyway? I would (really) love to know
