### ISSUE TITLE
minions do not appear on leaderboard

### ISSUE THREAD

**Issue by Hydra4dude** [Megabyte918/MultiOgar-Edited#1269]
How do I make the minions appear on the leaderboard?

**Comment by Agarian** [comment]
You would have to remove [this line of code](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L206) from `PlayerTracker.js`

**Comment by Agarian** [comment]
@Hydra4dude you can actually now look in `gameserver.ini` and change the config `minionsOnLeaderboard` to 1, since my recent pull request got merged.
