### ISSUE TITLE
Is the skin command not working or i need to do something else?

### ISSUE THREAD

**Issue by rjay222** [Megabyte918/MultiOgar-Edited#127]
If i do `skin 1 kraken or <kraken>` i get the error `gameServer.getPlayerById is not a function`. If its not working, will it ever be? The skin script is cool but it doesn't give you the borders...

**Comment by Tyler3D** [comment]
@rjay222 IDK why he added back the skin command cause, the clients doesn't let the server choose the skin. Maybe its still work in progress?

**Comment by rjay222** [comment]
**Nvm, i already understood everything. I'm closing this.**

**Comment by rjay222** [comment]
@Megabyte918 btw the skin script doesn't let you see the other cell skin when youre multiboxing.
