### ISSUE TITLE
party mode creation

### ISSUE THREAD

**Issue by Hydra4dude** [Megabyte918/MultiOgar-Edited#1270]
I know this may not seem like a problem, but since the server has almost all modes of agar.io, why does not it have party mode? With that the server would be complete for good.

**Comment by Wair1o17** [comment]
Client sided.

**Comment by Agarian** [comment]
The party game mode is pretty much FFA with out anti-teaming. The only thing party mode would add here is the friends feature.

**Comment by Hydra4dude** [comment]
In the same way it would look really cool, the minions could be friends to look more like the original agar.io

**Comment by giancarlosambayan** [comment]
@Hydra4dude @Agarian @Wair1o17 
![image](https://user-images.githubusercontent.com/30329244/31580619-e80c1056-b187-11e7-8e5d-ae6ffe1be848.png) u mean liek dis boiz

**Comment by Hydra4dude** [comment]
What is the link of your server ??

**Comment by Agarian** [comment]
I have actually noted that when you use `/?ip=` in the agar.io URL, changing to any game mode will just reconnect to the IP put in the URL. That's how he did it.

**Comment by giancarlosambayan** [comment]
@Agarian @Hydra4dude lol how do i apply the yellow rings on the bots |:/

**Comment by DeadLord1337** [comment]
@giancarlosambayan How to make yellow rings lol please tell me

**Comment by giancarlosambayan** [comment]
@DeadLord1337 i messed up the FFA.js them kaboom

**Comment by fayizan** [comment]
He got skin too @Agarian  :|

**Comment by Agarian** [comment]
@giancarlosambayan I'm more interested in how you got a premium skin to work just there.

**Comment by ItzLevvie** [comment]
@Agarian maybe he used https://github.com/Megabyte918/MultiOgar-Edited/issues/1198#issuecomment-323614513?

**Comment by Agarian** [comment]
I'm surprised that still works lol

**Comment by SAV-404** [comment]
try this : https://github.com/SAV-404/agario-free-skins

**Comment by DeadLord1337** [comment]
noice hex

**Comment by giancarlosambayan** [comment]
@ItzLevvie ye its the same command that the extension do but it cannot be seen by other players only u
but it works in raga.pw server :p others can see it

**Comment by Gatoz** [comment]
hola , porfa yo tambien quiero saber como pongo el borde amarillo en mi celula please

**Comment by Fan7asy** [comment]
@Gatoz Stop spamming and English only.
