### ISSUE TITLE
Tournament Mode

### ISSUE THREAD

**Issue by FirstCodeReviewer** [Megabyte918/MultiOgar-Edited#1272]
Can somebody tell me why this commit has been done?
https://github.com/Megabyte918/MultiOgar-Edited/commit/6cc57188b8f619fd22ed1c3e4675a306e595e9d4#diff-0c8da013755c38968640b5eda94bcf99R221
Why does he call `process.exit(3);` in Line 221 & 233?

With this option its only possible to play Tournament once. 
And there is also some Dead Code inside.

I could do a PR fixing this. But I am unsure wether `process.exit(3);` is intended or not.

**Comment by AlexHGaming** [comment]
Very good point.

**Comment by Agarian** [comment]
You could try calling the reset command instead of `process.exit`

**Comment by Agarian** [comment]
I did not like why it was used, but here's a simple fix:

```js
for (; gameServer.nodes.length;) gameServer.removeNode(gameServer.nodes[0]);
for (; gameServer.nodesPlayer.length;) gameServer.removeNode(gameServer.nodesPlayer[0]);
for (; gameServer.nodesEject.length;) gameServer.removeNode(gameServer.nodesEject[0]);
for (; gameServer.nodesFood.length;) gameServer.removeNode(gameServer.nodesFood[0]);
for (; gameServer.nodesVirus.length;) gameServer.removeNode(gameServer.nodesVirus[0]);
return this.gamePhase = 0;
```

Replace both lines of `process.exit` with the above code.
