### ISSUE TITLE
Tournament vs Hunger

### ISSUE THREAD

**Issue by FirstCodeReviewer** [Megabyte918/MultiOgar-Edited#1273]
What are the differences between Tournament and HungerGames?

**Comment by Luka967** [comment]
In Hunger Games, players spawn around a circle with viruses and large pellets in the center.
In Tournament, players spawn in random places and no extra cells are created.
Both finish when only one player remains.

**Comment by ArixProject** [comment]
lol

**Comment by Agarian** [comment]
This is the general layout for the food and virus cells that spawn in the center:
![hungergameslayout](https://user-images.githubusercontent.com/23372586/31579594-67b25fb2-b107-11e7-8a8c-0cbd23a04413.png)
