### ISSUE TITLE
How to change minion control hotkey?

### ISSUE THREAD

**Issue by xN3BULA** [Megabyte918/MultiOgar-Edited#1274]

**Comment by Agarian** [comment]
It depends, do you want to know how to do this on a custom client? Or do you just want to do this on the agar.io client (assuming you have the ERTP script)?

**Comment by xN3BULA** [comment]
@Agarian I meant i want to change the default Q to something else

**Comment by FirstCodeReviewer** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/cd5e362b35699df1c167652e98c8b9ad04fc496c/src/PacketHandler.js#L63

https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L128-L141

https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L364-L375

https://github.com/Megabyte918/MultiOgar-Edited/blob/cd5e362b35699df1c167652e98c8b9ad04fc496c/src/PacketHandler.js#L14

https://github.com/Megabyte918/MultiOgar-Edited/blob/cd5e362b35699df1c167652e98c8b9ad04fc496c/src/PacketHandler.js#L16

https://github.com/Megabyte918/MultiOgar-Edited/blob/cd5e362b35699df1c167652e98c8b9ad04fc496c/src/PacketHandler.js#L249-L252

**Comment by xN3BULA** [comment]
@FirstCodeReviewer Ty
