### ISSUE TITLE
Fixed PartyMode Thinggy w/ Friends + ummm leaderboard yellow thinggy + and umm no arrows yet cuz i fk uped

### ISSUE THREAD

**Issue by giancarlosambayan** [Megabyte918/MultiOgar-Edited#1279]
lol dafuq
![image](https://user-images.githubusercontent.com/30329244/31583092-cfd4d3bc-b1c6-11e7-9887-064e7780471c.png)
someone give me sum knife imma kill my self now

**Comment by ArixProject** [comment]
lol

**Comment by giancarlosambayan** [comment]
![image](https://user-images.githubusercontent.com/30329244/31583166-e23b0598-b1c7-11e7-9e03-d9ebd4e75d4f.png)
All right kell me pls

**Comment by Mr-BrockLee** [comment]
@giancarlosambayan Can this be added to custom client?

**Comment by giancarlosambayan** [comment]
@Fan7asy sorreh bruaw

**Comment by giancarlosambayan** [comment]
@Mr-BrockLee wot u mean?
