### ISSUE TITLE
Client 

### ISSUE THREAD

**Issue by Fantasy-Agario** [Megabyte918/MultiOgar-Edited#128]
# Client 

Does anyone want me to make an official client for this project ?

**Comment by ZfsrGhS953** [comment]
Yes! Will the client have its own protocol?

**Comment by Jhair2015** [comment]
Yeah!

**Comment by Fantasy-Agario** [comment]
@ZfsrGhS953 Once I get the base done I will work on protocols :D

**Comment by CalvinDKL** [comment]
Cool!

**Comment by MastaCoder** [comment]
Why not just make Cigar compatible with it?

**Comment by Fantasy-Agario** [comment]
It is compatible with Cigar but our own client would be more "Expandable"

**Comment by MastaCoder** [comment]
Expandable to what?

**Comment by Fantasy-Agario** [comment]
To adding more features as we go along :)
