### ISSUE TITLE
[Bug] "board" command

### ISSUE THREAD

**Issue by giancarlosambayan** [Megabyte918/MultiOgar-Edited#1282]
Hey i was wondering if u can fix the "Board" command cuz when i do /board random names , etc
it just repeat my name lol

**Comment by Agarian** [comment]
Yes, this is due to the new `buildUserText` function in UpdateLeaderboard.js
It needs to be fixed, or reverted.

**Comment by giancarlosambayan** [comment]
@Agarian ye but it does the Friend System on the leaderboard ( ͡° ͜ʖ ͡°)

**Comment by giancarlosambayan** [comment]
@Agarian also the functions for 'minionsOnLeaderboard' seems doesn't work ._.

**Comment by FirstCodeReviewer** [comment]
I do not know what you mean. For me it is working. There is no PlayerCommand called `/board` so i guess you mean the ConsoleCommand and if you do it still works for me.. Tested on FFA with command `"board random names"`. Everything showed up correctly on the client. First place was random and second place was names.

**Comment by Agarian** [comment]
Have you tried on different clients? I've seen what he's describing in the agar.io client with the new `buildUserText` function.

**Comment by giancarlosambayan** [comment]
@FirstCodeReviewer try to do `board 32 TYT 32 LOL 32 YAY 32 BRUH 32 AGAR` on agar.io cilent
mine just give the Friend System thing with the leaderboard w/ Yellow colors know as friends?

**Comment by giancarlosambayan** [comment]
@Agarian `buildUserText` function where is it lol xd

**Comment by Agarian** [comment]
@giancarlosambayan Except, that yellow friend text is NOT supposed to happen. The text that the `board` command displays is supposed to be white, and ONLY white. And it should not display player's names either. And you can find the `buildUserText` function in `src>modules>UpdateLeaderboard.js`

**Comment by giancarlosambayan** [comment]
@Agarian wait min look at my screenshot lol

**Comment by Agarian** [comment]
I don't think you can send videos here, GIF's maybe. Also where's your screenshot?

**Comment by giancarlosambayan** [comment]
@Agarian i did this in the console
board 32 ??? 32 ??? 32 ??? 32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ???32 ??? 32 ??? 32 ??? 
![image](https://user-images.githubusercontent.com/30329244/31638775-f46d5d60-b307-11e7-82d1-f920111bc547.png)
Then this happens lmao
is this the `buildUserText`
??

**Comment by Agarian** [comment]
THAT is not supposed to happen, I will revert the `buildUserText` function when I can, now isn't a good time.

**Comment by giancarlosambayan** [comment]
@Agarian well that happend so idk lol

**Comment by giancarlosambayan** [comment]
imma close dis for now :D
