### ISSUE TITLE
how can i download version 1.6.0

### ISSUE THREAD

**Issue by josefredohd** [Megabyte918/MultiOgar-Edited#1284]
Title

**Comment by ItzLevvie** [comment]
@josefredohd https://github.com/Megabyte918/MultiOgar-Edited/archive/1.6.0.zip

**Comment by josefredohd** [comment]
Thank you :)

**Comment by josefredohd** [comment]
And the version 1.5.0?

**Comment by Agarian** [comment]
That version hasn't been archived, unfortunately.

**Comment by FirstCodeReviewer** [comment]
@josefredohd There it is: https://github.com/Megabyte918/MultiOgar-Edited/tree/8eec70e43dc9ab9a891a5163a23f01d38abb07e0
