### ISSUE TITLE
How to get the forwarded IP address?

### ISSUE THREAD

**Issue by Niall7459** [Megabyte918/MultiOgar-Edited#1285]
What can I edit in the code to get the reverse proxy forwarded ip?

Because I have my game behind an Nginx reverse proxy..
so the Ip is always showing 192.168.1.108 (IP of my proxy)...
Anyway to change this to the users real IP
Because i have X-Forwarded For headers?

Any help much appreciated...

**Comment by Fan7asy** [comment]
This is unrelated to the server itself.
