### ISSUE TITLE
Auto-restart like alis.io does not work in version 1.6.1

### ISSUE THREAD

**Issue by EzequielCoder** [Megabyte918/MultiOgar-Edited#1286]
I got the auto-restart as alis.io, it works in version 1.4.2 but in version 1.6.1 it does not work help me!:

var tEnd = process.hrtime(tStart);
    this.updateTime = tEnd[0] * 1000 + tEnd[1] / 1000000;
    for (var i = 0; i < this.clients.length; i++) {
        if (!this.isRestarting) {
            var client = this.clients[i].playerTracker;
            if (client && client.cells.length > 0) {
                if (client._score / 100 > this.config.serverRestartSize) this.resetServer();
            }
        }
    }
};

GameServer.prototype.resetServer = function() {
        this.isRestarting = true;
        var newLB = ["Restarting", "In", "1", "Minute"];
        this.gameMode.packetLB = 48;
        this.gameMode.specByLeaderboard = false;
        this.gameMode.updateLB = function(gameServer) {
            gameServer.leaderboard = newLB;
            gameServer.leaderboardType = 48;
        };
        setTimeout(function() {
         process.exit(1);
         var gm = Gamemode.get(this.gameMode.ID);

        // Replace functions
        this.gameMode.packetLB = gm.packetLB;
        this.gameMode.updateLB = gm.updateLB;
        this.isRestarting = false
        }.bind(this), 20000)
};

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/1281
Fantasy's comment.

**Comment by EzequielCoder** [comment]
Why not

**Comment by Luka967** [comment]
Because it's custom. This is not StackOverflow. If you want something to work put effort into it instead of immediately asking everywhere.

**Comment by EzequielCoder** [comment]
Ok thx
