### ISSUE TITLE
 How to automatically put the name you are using to the minions

### ISSUE THREAD

**Issue by josefredohd** [Megabyte918/MultiOgar-Edited#1287]
Title

**Comment by AlexHGaming** [comment]
#303

**Comment by Wair1o17** [comment]
Duplicate.

**Comment by AlexHGaming** [comment]
Or replace [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/MinionPlayer.js#L20-#L24) with the following:

```javascript
if (this.owner.cells.length) {
		if (!this.owner._name) {
		this.joinGame(this.owner._name, this.owner._skin)
		} else {
    this.joinGame(this.owner._name + "'s bot", this.owner._skin, true)
		}
    if (!this.cells.length) this.socket.close();
}```

**Comment by AlexHGaming** [comment]
The code looks a bit nasty, but looks fine to me (this copies the owner's skin, alongside with (user)'s bot as the name)

**Comment by AlexHGaming** [comment]
If you DON'T want it to copy the owner's skin then:
```javascript
if (this.owner.cells.length) {
		if (!this.owner._name) {
		this.joinGame(this.owner._name)
		} else {
    this.joinGame(this.owner._name, true)
		}
    if (!this.cells.length) this.socket.close();
}
```

**Comment by AlexHGaming** [comment]
Yep, it doesn't look like proper js, but it works.

**Comment by josefredohd** [comment]
the minions appear with the name "minions" but then it is changed to my name. How can I make them enter my name directly?

**Comment by Agarian** [comment]
To be honest, I don't think there's a real way to actually do that, unless you make that code change the `defaultMinionName` config directly.

**Comment by josefredohd** [comment]
as in duex.io

**Comment by Agarian** [comment]
@josefredohd Actually, the solution is pretty simple. Open up `src > ai > MinionPlayer.js`, then replace the code on line 50 with `name = s.playerTracker.owner._name;`

**Comment by Agarian** [comment]
And that will do it.

**Comment by josefredohd** [comment]
still not working, the minions appear with the name "An unnamed cell"

**Comment by Agarian** [comment]
Did you remember to remove the code at line 70 before adding what I gave you? And if so, did you remember o leave the name area blank in the `minion` command? Because this worked just fine for me.

**Comment by josefredohd** [comment]
in serverMinions in gameserver.ini

**Comment by AlexHGaming** [comment]
Just do what me or agarian did at the top, that seems to work :D

**Comment by Shair17** [comment]
LOL

**Comment by Agarian** [comment]
Yes, it does, but he doesn't like how you can VERY briefly see the minion's originally intended name before it get's set to the owner's name.

Let's say `defaultMinionName` is "The Name". When you have that code in, it does change the minions' name to their owner's name, however, when minions initially spawn, they will still use "The Name", due to `defaultMinionName`. So you will see that when minions spawn, "The Name" appears very briefly before changing to the minion owner's name.

**Comment by josefredohd** [comment]
Yes

**Comment by josefredohd** [comment]
I do not want to see the "defaultMinionName"

**Comment by josefredohd** [comment]
i only want see the owner's name

**Comment by Agarian** [comment]
@josefredohd I made a mistake with the name code.
Refer to the fixed tutorial below:
Open the file [BotLoader.js](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/BotLoader.js), then replace the code on [Line 70](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/BotLoader.js#L70) with `name = s.playerTracker.owner.getName();`

**Comment by josefredohd** [comment]
[FATAL] TypeError: s.playerTracker.owner.getName is not a function
    at BotLoader.addMinion (C:\Users\Jose Alfredo Hdez\Desktop\Bots 1\src\ai\BotLoader.js:70:38)
    at GameServer.checkMinion (C:\Users\Jose Alfredo Hdez\Desktop\Bots 1\src\GameServer.js:358:23)
    at GameServer.onClientSocketOpen (C:\Users\Jose Alfredo Hdez\Desktop\Bots 1\src\GameServer.js:331:10)
    at emitOne (events.js:96:13)
    at WebSocketServer.emit (events.js:188:7)
    at C:\Users\Jose Alfredo Hdez\Desktop\Bots 1\node_modules\ws\lib\WebSocketServer.js:91:14
    at completeHybiUpgrade2 (C:\Users\Jose Alfredo Hdez\Desktop\Bots 1\node_modules\ws\lib\WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (C:\Users\Jose Alfredo Hdez\Desktop\Bots 1\node_modules\ws\lib\WebSocketServer.js:309:13)
    at WebSocketServer.handleHybiUpgrade (C:\Users\Jose Alfredo Hdez\Desktop\Bots 1\node_modules\ws\lib\WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (C:\Users\Jose Alfredo Hdez\Desktop\Bots 1\node_modules\ws\lib\WebSocketServer.js:173:26)

**Comment by Agarian** [comment]
Forgot `getName()` isn't a function anymore. Shit.

**Comment by josefredohd** [comment]
and as I have to put it

**Comment by MiraMiPalo** [comment]
#1161

**Comment by josefredohd** [comment]
Gracias we

**Comment by MiraMiPalo** [comment]
funciono? xD

**Comment by josefredohd** [comment]
Si xD

**Comment by josefredohd** [comment]
Hey te quiero preguntar algo, conectate en discord

**Comment by josefredohd** [comment]
@MiraMiPalo
