### ISSUE TITLE
minions in differsize 

### ISSUE THREAD

**Issue by giancarlosambayan** [Megabyte918/MultiOgar-Edited#1288]
Hi the `minionsOnLeaderboard` function on gameserver.ini is not working
`minionsOnLeaderboard = 1 (Enable)`
`minionsOnLeaderboard = 0 (Disable)`

So i started my server and its set to `1` but i do not see my minion names on the leaderboard?
[NOW WORKING]

Also Sir @Megabyte918 🤣
I would like to ask you a question?

It is about the minion size?
I want a command like this
`minion [id] [mass] [amount] [name]`
i found the code but it doesn't seem work for the new version
i would like you to update it again thanks

**Comment by Agarian** [comment]
@giancarlosambayan `minionsOnLeaderboard` isn't working because #1283 hasn't been merged.

**Comment by Fan7asy** [comment]
*Excuse me?*

**Comment by Agarian** [comment]
Check that, download the latest version now @giancarlosambayan

**Comment by giancarlosambayan** [comment]
@Agarian Okee thanks but i will wait for @Megabyte918 to answer my question cuz alot of people want it ;)

**Comment by Agarian** [comment]
@giancarlosambayan So pretty much, you want to add a `mass` attribute to the `minion` command?

**Comment by giancarlosambayan** [comment]
@Fan7asy I will close this after i get @Megabyte918  message thanks :D

**Comment by Agarian** [comment]
Alrighty then.

**Comment by giancarlosambayan** [comment]
@Agarian #784 same as that but the codes doesn't work anymore :/

**Comment by Agarian** [comment]
I can get that code working again, if you would like.

**Comment by giancarlosambayan** [comment]
@Agarian sure thing :D

**Comment by Agarian** [comment]
Alright, give me a little bit of time, so I can work my "magic" lol

**Comment by giancarlosambayan** [comment]
@Agarian 

> Ye the magic begins xd

**Comment by Agarian** [comment]
Just don't get triggered if I can't do it :p

**Comment by giancarlosambayan** [comment]
@Agarian Its okay bruh , i can wait for it lul , megabyte can do it if u cant do it lol
do it just do it is the reapting wordz
#ripgrammar
#ripenglish

**Comment by giancarlosambayan** [comment]
@Agarian Also i want you to look at this
https://www.youtube.com/watch?v=K1k_f0Aowc4
If you look closely you can see the minion collect pellets in different way?
Not the same as this version of how the minions collect
do you know how to do it?
it also reduce lag ;)

**Comment by Agarian** [comment]
@giancarlosambayan Do note that minions collect pellets in the same way here as they do there. And plus, note that that guy used EXTERNAL minions. Not only would that lag more, but would also be blocked by the `ANTI-BOT` configs in `gameserver.ini`.

**Comment by giancarlosambayan** [comment]
@Agarian Oh but  you know how to make minions collect pellet like that? i think its called ticks or something?

**Comment by Agarian** [comment]
You do realize that the `P` key makes minions collect pellets, right? The minions here literally collect pellets the same way, and in an even better way (in terms of performance).

**Comment by giancarlosambayan** [comment]
@Agarian Yes i do realize that i mean , how they collect pelletsl like that in the video?
Some bots eat each other
When they got big they stop for like 0.5 seconds then they find pellets?

**Comment by Agarian** [comment]
In MultiOgar, the bots do actually sometimes eat each other when finding pellets (gonna refer to pellets as food from now on). Though when the minions can't find food, they go to the owner's mouse.

**Comment by giancarlosambayan** [comment]
@Agarian oke xd changed the topic for this issue i close this as soon as i get ur message about the command syntax for the bots

**Comment by giancarlosambayan** [comment]
@Agarian so how is it xd

**Comment by giancarlosambayan** [comment]
Closing dis too
