### ISSUE TITLE
Local Issue

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1290]
![image](https://user-images.githubusercontent.com/23644244/31728167-77335abc-b423-11e7-838c-5bb74623e15d.png)

**Comment by AlexHGaming** [comment]
Well I fixed the issue, but I heavily modified my MultiOgar Fork, so someone will have to pr this:
```bat
@echo off
:a
node ../src/index.js
@echo Restarting server
goto :a

```

Change lin-Start.sh to that.

**Comment by AlexHGaming** [comment]
Closing when PR'ed.

**Comment by Agarian** [comment]
@AlexHGaming that code for `win-Start.bat` is no different than the current version. Did you post the right code?

**Comment by FirstCodeReviewer** [comment]
@AlexHGaming Create a new Branch, Pull from Megabyte master do the Change and PR it. Then delete your Branch after PR...
