### ISSUE TITLE
minions in differ size

### ISSUE THREAD

**Issue by giancarlosambayan** [Megabyte918/MultiOgar-Edited#1291]
I know this is duplicate but
#784 `Doesn't work with the new update?`
Any fix @Megabyte918

**Comment by MiraMiPalo** [comment]
`var mass = parseInt(split[3]);`
`if (isNaN(mass)) mass = gameServer.config.minionStartSize;`
`gameServer.config.minionStartSize = Math.sqrt(mass * 100);`

**Comment by giancarlosambayan** [comment]
@MiraMiPalo Sorry but can u post the code seperately?
like what Megabyte did
Its full :/ i dont rlly get u sorry

**Comment by MiraMiPalo** [comment]
minion: function (gameServer, split) {
        var id = parseInt(split[1]);
        var add = parseInt(split[2]);
        var mass = parseInt(split[3]);
        var name = split.slice(4, split.length).join(' ');

		if (isNaN(mass)) mass = gameServer.config.minionStartSize;
		gameServer.config.minionStartSize = Math.sqrt(mass * 100);
        // Error! ID is NaN
        if (isNaN(id)) {
            Logger.warn("Please specify a valid player id!");
            return;
        }

        // Find ID specified and add/remove minions for them
        for (var i in gameServer.clients) {
            var client = gameServer.clients[i].playerTracker;

            if (client.pID == id) {

                // Prevent the user from giving minions, to minions
                if (client.isMi) {
                    Logger.warn("You cannot give minions to a minion!");
                    return;
                };

                // Remove minions
                if (client.minionControl === true && isNaN(add)) {
                    client.minionControl = false;
                    client.miQ = 0;
                    Logger.print("Succesfully removed minions for " + getName(client._name));
                    // Add minions
                } else {
                    client.minionControl = true;
                    // Add minions for client
                    if (isNaN(add)) add = 1;
                    for (var i = 0; i < add; i++) {
                        gameServer.bots.addMinion(client, name);
                    }
                    Logger.print("Added " + add + " minions for " + getName(client._name));
                }
                break;
            }
        }
    },

**Comment by giancarlosambayan** [comment]
@MiraMiPalo i dont rlly get it rip me ._. |

This is what megabyte did

"Replace the minion command in CommandList.js with this one"

"minion: function(gameServer, split) {
        var id = parseInt(split[1]);
        var add = parseInt(split[2]);
        var mass = parseInt(split[3]);
        var name = split.slice(4, split.length).join(' ');
            
        // Error! ID is NaN
        if (isNaN(id)) {
            Logger.warn("Please specify a valid player id!");
            return;
        }  
        
        // Find ID specified and add/remove minions for them
        for (var i in gameServer.clients) {
            var client = gameServer.clients[i].playerTracker;
            
            if (client.pID == id) {
                // Remove minions
                if (client.minionControl === true && isNaN(add)) {
                    client.minionControl = false;
                    client.miQ = 0;
                    Logger.print("Succesfully removed minions for " + getName(client._name));
                // Add minions
                } else {
                    client.minionControl = true;
                    // Add minions for client
                    if (isNaN(add)) add = 1; 
                    for (var i = 0; i < add; i++) {
                        gameServer.bots.addMinion(client, name, mass);
                    }
                    Logger.print("Added " + add + " minions for " + getName(client._name));
                }
                break;
            }
        }
    },"

"Then replace the addMinion function in /ai/BotLoader.js with this one:"

"BotLoader.prototype.addMinion = function(owner, name, mass) {
    var MinionPlayer = require('./MinionPlayer');
    var s = new FakeSocket(this.gameServer);
    s.playerTracker = new MinionPlayer(this.gameServer, s, owner);
    s.packetHandler = new PacketHandler(this.gameServer, s);
    s.playerTracker.owner = owner;

    var size;
    if (isNaN(mass)) {
        size = this.gameServer.config.minionStartSize;
        if (this.gameServer.config.minionMaxStartSize > size)
        size = Math.random() * (this.gameServer.config.minionMaxStartSize - size) + size;
    } else {
        size = Math.sqrt(mass * 100);
    }
    s.playerTracker.spawnmass = size;
    
    // Add to client list
    this.gameServer.clients.push(s);

    // Add to world & set name
    if (typeof name == "undefined" || name == "") {
        name = this.gameServer.config.defaultName;
    }
    s.packetHandler.setNickname(name);
};"

The syntax of the command is "minion [id] [amount] [mass] [name]"

**Comment by MiraMiPalo** [comment]
reaplace  `BotLoader.prototype.addMinion` function to default code, and try

**Comment by Agarian** [comment]
@MiraMiPalo I've noticed a fairly bad flaw with your code: When you make the command change a config value, it affects all that the config affects. So when you change `minionStartSize`, all minions, including other player's minions have the same start size.

**Comment by MiraMiPalo** [comment]
i think i'm missing this
`if (isNaN(mass)) {
					Logger.warn("Please specify a valid mass amount!");
					return;
				}`

**Comment by MiraMiPalo** [comment]
No, it's still bad xD

**Comment by Agarian** [comment]
@MiraMiPalo It's be better to leave that code out, as if somebody doesn't supply a mass, they shouldn't have to. I'm trying to see if I can devise a fix to the bug I explained earlier.

**Comment by MiraMiPalo** [comment]
minion: function (gameServer, split) {
        var id = parseInt(split[1]);
        var add = parseInt(split[2]);
        var mass = parseInt(split[3]);
        var name = split.slice(4, split.length).join(' ');

        // Error! ID is NaN
        if (isNaN(id)) {
            Logger.warn("Please specify a valid player id!");
            return;
        }

        // Find ID specified and add/remove minions for them
        for (var i in gameServer.clients) {
            var client = gameServer.clients[i].playerTracker;

            if (client.pID == id) {

                // Prevent the user from giving minions, to minions
                if (client.isMi) {
                    Logger.warn("You cannot give minions to a minion!");
                    return;
                };

                // Remove minions
                if (client.minionControl === true && isNaN(add)) {
                    client.minionControl = false;
                    client.miQ = 0;
                    Logger.print("Succesfully removed minions for " + getName(client._name));
                    // Add minions
                } else {
                    client.minionControl = true;
					gameServer.config.minionStartSize = Math.sqrt(mass * 100);
					if (isNaN(mass)) gameServer.config.minionStartSize = Math.sqrt(30 * 100);
                    // Add minions for client
                    if (isNaN(add)) add = 1;
                    for (var i = 0; i < add; i++) {
                        gameServer.bots.addMinion(client, name);
                    }
                    Logger.print("Added " + add + " minions for " + getName(client._name));
                }
                break;
            }
        }
    },

**Comment by MiraMiPalo** [comment]
BotLoader.prototype.addMinion = function(owner, name) {
    var MinionPlayer = require('./MinionPlayer');
    var s = new FakeSocket(this.gameServer);
    s.playerTracker = new MinionPlayer(this.gameServer, s, owner);
    s.packetHandler = new PacketHandler(this.gameServer, s);
    s.playerTracker.owner = owner;

    // Spawn minions at special size
    var size = this.gameServer.config.minionStartSize;
    s.playerTracker.spawnmass = size;
    
    // Add to client list
    this.gameServer.clients.push(s);

    // Add to world & set name
    if (typeof name == "undefined" || name == "") {
        name = this.gameServer.config.defaultName;
    }
    s.packetHandler.setNickname(name);
};

**Comment by MiraMiPalo** [comment]
@Fan7asy @Megabyte918 closeeee

**Comment by Agarian** [comment]
Looks better:
```js
minion: function (gameServer, split) {
var id = parseInt(split[1]);
var add = parseInt(split[2]);
var mass = parseInt(split[3]);
var name = split.slice(4, split.length).join(' ');

    // Error! ID is NaN
    if (isNaN(id)) {
        Logger.warn("Please specify a valid player id!");
        return;
    }

    // Find ID specified and add/remove minions for them
    for (var i in gameServer.clients) {
        var client = gameServer.clients[i].playerTracker;

        if (client.pID == id) {

            // Prevent the user from giving minions, to minions
            if (client.isMi) {
                Logger.warn("You cannot give minions to a minion!");
                return;
            };

            // Remove minions
            if (client.minionControl === true && isNaN(add)) {
                client.minionControl = false;
                client.miQ = 0;
                Logger.print("Succesfully removed minions for " + getName(client._name));
                // Add minions
            } else {
                client.minionControl = true;
	    gameServer.config.minionStartSize = Math.sqrt(mass * 100);
	    if (isNaN(mass)) gameServer.config.minionStartSize = Math.sqrt(30 * 100);
                // Add minions for client
                if (isNaN(add)) add = 1;
                for (var i = 0; i < add; i++) {
                    gameServer.bots.addMinion(client, name);
                }
                Logger.print("Added " + add + " minions for " + getName(client._name));
            }
            break;
        }
    }
},
```

**Comment by MiraMiPalo** [comment]
@Agarian no, no looks better :v
