### ISSUE TITLE
minions on the leaderboard

### ISSUE THREAD

**Issue by giancarlosambayan** [Megabyte918/MultiOgar-Edited#1292]
So the minions does show in the leaderboard but when i add bots
the bots seems doesn't to be in the leaderboard?
is there anyway i can make that happen?
ssry bad english

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L189

**Comment by giancarlosambayan** [comment]
@AlexHGaming No i mean , When i add bots like 50 AI Bots the minions doesn't seem to be on the leaderboard

**Comment by Agarian** [comment]
Do you want to hide bot's names from the leader board, hide minions from the leader board, or do you have a problem that needs to be fixed?

**Comment by MiraMiPalo** [comment]
he want to show the minion and bots names on the leaderboard.. 
but when add bots the minions don't show on leaderboard
o eso creo yo :v

**Comment by giancarlosambayan** [comment]
@MiraMiPalo thanks :D  
@Agarian MiraMiPalo fixed it so i m closjn dis

**Comment by Gatoz** [comment]
yo tambien quiero saber como slucionar eso , de que aparescan los bots y los minions en la tabla de clasificacion
