### ISSUE TITLE
Skins broken again

### ISSUE THREAD

**Issue by Niall7459** [Megabyte918/MultiOgar-Edited#1293]
Can this be fixed again?

Thank you

**Comment by Agarian** [comment]
Dude, can't you realize that premium skins have been broken for many months now? If you want to use premium skins on the agar.io client, use [this script.](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/scripts/CustomSkins.js)

**Comment by Niall7459** [comment]
I am really sorry I only upgraded a few days ago...
A notice shoudl be put on the read me.

**Comment by Niall7459** [comment]
Wait I am using CIGAR Client...
It uses <> skins...

**Comment by Niall7459** [comment]
@Agarian Well is there anything that can be done to fix this? Other than using previous versions..

**Comment by Agarian** [comment]
Last I've heard, Cigar does not use `<>` skins.

**Comment by Niall7459** [comment]
Uhh, well my version definatley supports it because Ive been using it for a year now..

**Comment by Niall7459** [comment]
@Agarian I mean If i were to put my name as <doge>cell
This used to work with MultiOgar...

What happened?

**Comment by Agarian** [comment]
Your version has them? Impressive.
Also I'm unsure. What update was it that broke the skins? More specifically, what version did the skins work on?

**Comment by Niall7459** [comment]
Well i wrote it so it would basically just set your nick name to 

<skin name>nick name.

Let me just find what verison i was using

**Comment by Agarian** [comment]
Alright, but I don't have much time until lunch is over.

**Comment by Niall7459** [comment]
Okay you know what I dont actully know it msut have been a while back..

**Comment by Niall7459** [comment]
Because my skins work fine with OgarServ

**Comment by Agarian** [comment]
If it works on other clients, there's no reason (that I'd know of) that it shouldn't be working for your client, unless there's an issue within the client.

**Comment by Niall7459** [comment]
I am downloading the 1.6.0 release

**Comment by Niall7459** [comment]
I will give it a go

**Comment by Niall7459** [comment]
It does not work with 1.6.0

Where can I get a copy of 1.5.0. It is not in the releases tab.

**Comment by Agarian** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/tree/8eec70e43dc9ab9a891a5163a23f01d38abb07e0

**Comment by Niall7459** [comment]
Not working on 1.5 either..
Must be a problem on my client side..

**Comment by Agarian** [comment]
I'd imagine at this point.

**Comment by Niall7459** [comment]
But the thing is it works fine with OgarServ, (a forked copy of MultiOgar-Edited)

**Comment by Niall7459** [comment]
Even if I name myself the skin. EG 'doge' It still doesnt work with multiogar

**Comment by Agarian** [comment]
Oh sorry, I'm still thinking that OgarServ is a client lol, but I'm really not sure at this point.

**Comment by Niall7459** [comment]
https://github.com/JaraLowell/OgarServ
Skins work with this.

Where about is skin processing is it in PackerHandler.js?

**Comment by Agarian** [comment]
The very bottom function of `PacketHandler.js`

**Comment by Niall7459** [comment]
Ah okay the code looks a bit different

**Comment by Agarian** [comment]
Hmm, tell me, how would somebody implement `<>` skins anyway? I've been looking to add them to my client.

**Comment by Niall7459** [comment]
I fixed the skins by modifying some code.

But now I just need to fix the names because they appear as <skinname>Hello instead of just name lol..

**Comment by Agarian** [comment]
I mean what "modifications" would I have to do? Because I don't know where to start.

**Comment by Niall7459** [comment]
My code is very messy and outdated but i will post it:
In cigar.... I  edit to this..
`wHandle.setSkin = function(arg) {
      arg = atob(arg);
      if (arg != "None" || arg != "") {
        //$("#selectedSkin").text(arg);
        $("#skin-img").attr("src", "skins/" + arg + ".png");
        $("#skin-img-panel").attr("src", "skins/" + arg + ".png");
        $("#nick").css("padding-left", $("#selectedSkin").width() + 7.5 + "px");
        sendSkin = arg;
      } else {
        //$("#selectedSkin").text("");
        $("#skin-img").attr("src", "cell.png");
        $("#skin-img-panel").attr("src", "skins/cell.png");
        $("#nick").css("padding-left", 7.5 + "px");
      }
      $("#selector").fadeOut('fast');
      $('.skinList > li').hide();
    };`
`wHandle.setNick = function(arg) {
        hideOverlays();
        userNickName = arg;
        if (sendSkin != null) {
            userNickName = "<" + sendSkin + ">" + userNickName;
        }
        sendNickName();
    };`

Im sorry It was a long time ago i programmed this, I think i added the variable sendSkin somewhere at the top..

**Comment by Niall7459** [comment]
oh dear that wasnt meant to happen.

**Comment by Niall7459** [comment]
basically,

I set the Nickname to "<" + skinName + ">" + nickname
But this only works with OgarServ

I have sortof fixed it in MultiOgar

**Comment by Agarian** [comment]
Do you have the `sendSkin` function?
