### ISSUE TITLE
Problem in minions in the leaderboard

### ISSUE THREAD

**Issue by Hydra4dude** [Megabyte918/MultiOgar-Edited#1294]
when the minions are alone with me, they appear on the leaderboard, but when I put the bots in the room, they disappear, that is, for the minions to appear in the leaderboard and in the viewer mode, it is necessary to put the minions as players as the bots in the room.

THANK YOU!

**Comment by MiraMiPalo** [comment]
in MinionPlayer.js Change to
`this.isMi = false;`
in PacketHandler.js Delete this line
`socket.emit('close');`

**Comment by Agarian** [comment]
@MiraMiPalo That breaks the functionality of the `minionsOnLeaderboard` config.

**Comment by MiraMiPalo** [comment]
in MinionPlayer.js Change to
`this.isMi = false`
and add this
`this.MinionLB = true`

in PacketHandler.js Delete this line
`socket.emit('close');`

in FFA.js change
`player.isMi` for `player.MinionLB`

**Comment by Agarian** [comment]
I'm not sure what `socket.emit('close');` does.
