### ISSUE TITLE
PlayerCommand.js Ban command Thanks:) [Off-Topic]

### ISSUE THREAD

**Issue by Yukatii** [Megabyte918/MultiOgar-Edited#1297]
The title says it boi I need a way to get a ban over with a linecommand (Yes I transferred Commandline.js over to PlayerCommand but no luck ;/ i just getn an error pls help)

**Comment by Fan7asy** [comment]
What was the error produced? @Yukatii

**Comment by MiraMiPalo** [comment]
I just created this and it worked for me

 ban: function(args){
    var Commands = require('./CommandList');
    var id = args[1];
    for (var i in this.gameServer.clients) {
    var client = this.gameServer.clients[i].playerTracker;
    if (client.pID == id) {
    Commands.list.ban(this.gameServer, args);
    this.writeLine("Player " + client._name + " has been banned")
                }
      }
  },

**Comment by Agarian** [comment]
Here's the "pretty printed" version of the above code:
```js
ban: function(args) {
    var Commands = require('./CommandList');
    var id = args[1];
    for (var i in this.gameServer.clients) {
        var client = this.gameServer.clients[i].playerTracker;
        if (client.pID == id) {
            Commands.list.ban(this.gameServer, args);
            this.writeLine("Player " + client._name + " has been banned")
        }
    }
},
```

**Comment by MiraMiPalo** [comment]
tu siempre corrigiendome :v

**Comment by MiraMiPalo** [comment]
![closed](https://user-images.githubusercontent.com/25539632/31856819-48689a74-b691-11e7-9100-9c7cbeea6eaa.jpg)

**Comment by Agarian** [comment]
@Fan7asy @Megabyte918 Close this. I swear, somebody should give me the collaborator role, for the sake of closing issues when needed

**Comment by AmorimGames** [comment]
@Agarian #1299

**Comment by AlexHGaming** [comment]
@Agarian chances of getting it is extremely rare, i beg for it to @Megabyte918 and he keeps pulling the `idk` - yet i talk to him almost everyday
