### ISSUE TITLE
Invecible Command

### ISSUE THREAD

**Issue by AmorimGames** [Megabyte918/MultiOgar-Edited#1299]
title says it all

**Comment by AmorimGames** [comment]
@Agarian #1299

**Comment by Fan7asy** [comment]
Invecible?

**Comment by AmorimGames** [comment]
https://www.youtube.com/watch?v=N_2cv89SlpY

**Comment by Fan7asy** [comment]
Sorry I cannot support you with custom code.

**Comment by MiraMiPalo** [comment]
@Fan7asy  why no?

**Comment by AlexHGaming** [comment]
This is an issue's section.

**Comment by Fan7asy** [comment]
@MiraMiPalo This is the `issues` section, meaning it is for **issues**, from what i can see here, there's no issue.

>If you can't do it, *learn*

**Comment by MiraMiPalo** [comment]
and the section of custom code? xD

**Comment by Fan7asy** [comment]
?

**Comment by ArixProject** [comment]
lol gaver have a multiogar

**Comment by MiraMiPalo** [comment]
https://youtu.be/vJX9aYeJFXc

**Comment by AmorimGames** [comment]
@MiraMiPalo send me please
skype : yt.rememberme.br
discord : ﾑﾶの尺ﾉﾶᴸᵉᵍᵉⁿᵈ#9554

**Comment by ArixProject** [comment]
@MiraMiPalo give me command plzz

**Comment by ArixProject** [comment]
@MiraMiPalo 
give me command plzz

**Comment by ArixProject** [comment]
dame el código por favor
