### ISSUE TITLE
How to spawn in with the minions?

### ISSUE THREAD

**Issue by agariotips** [Megabyte918/MultiOgar-Edited#13]
I mean, when you start the server, you don't have to do minion (id) (amount) for every player. (over 112 ould be horrible), is it possible to make it so when they join the game, minions start spawning for them without me having to manually do it? If so, how?

**Comment by AlexandriteErikParacelsus** [comment]
Yeah it's possible, we need someone to develop it.

**Comment by Megabyte918** [comment]
I will work on this once the "only 1 person can control minions at a time" bug is fixed.

**Comment by Fantasy-Agario** [comment]
@Megabyte918 This could be made like the plugin IpBots by LegitSouja , 
Note down the ip in a config file ,
Server gets that file and gives minions to the ip Everytime that IP (player) connects :)

**Comment by agariotips** [comment]
@Fantasy-Agario Yeah, something like that would be very nice :)

**Comment by Megabyte918** [comment]
@agariotips Finished. I will continue to work on the minions by ip thing tho

**Comment by Megabyte918** [comment]
@agariotips If you want minions by a special IP, you can do something like this in GameServer.js on this line: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L367
<pre>
if (this.config.serverMinions > 0 && ws.remoteAddress == "insert your ip here") {
</pre>
So for example if I wanted minions to only be spawned in with me when I connect using my localhost IP address I would do:
<pre>
if (this.config.serverMinions > 0 && ws.remoteAddress == "127.0.0.1") {
</pre>
