### ISSUE TITLE
Yellow Ring ??!

### ISSUE THREAD

**Issue by ElPigianerJone** [Megabyte918/MultiOgar-Edited#1300]
pls give detail tutorial how to have yellow ring??!

**Comment by AlexHGaming** [comment]
@ElPigianerJone Dupe.

**Comment by ElPigianerJone** [comment]
?

**Comment by Shair17** [comment]
@ElPigianerJone  Client sided.

**Comment by ElPigianerJone** [comment]
i dont know how pls help me
![image](https://user-images.githubusercontent.com/19348870/31863976-19b9a25a-b780-11e7-95bc-afa217fe4d9e.png)

**Comment by AlexHGaming** [comment]
#905 #906

**Comment by ElPigianerJone** [comment]
It's not a detail tutorial :((

**Comment by Fan7asy** [comment]
Those are duplicates not detailed tutorials. @ElPigianerJone

**Comment by giancarlosambayan** [comment]
![image](https://user-images.githubusercontent.com/30329244/31870813-73c8f36a-b7e2-11e7-9a8b-a9b63fecca3c.png)
u mean liek dis lol

**Comment by Agarian** [comment]
@giancarlosambayan You know that you don't have to show off and rub it in people's faces, right? If you had time to post that image, I'm sure you have more than enough time to tell people how to implement it, otherwise, I don't want to hear it.

**Comment by giancarlosambayan** [comment]
@Agarian just tell me how to merge it ._. i'm not showing off ._. i wanna share it but how da faudge i merge
sorry i dont know how to use gituhb bruh

**Comment by giancarlosambayan** [comment]
@Agarian  @Shair17 @ElPigianerJone reffer to my new issue/tutorial #1301
