### ISSUE TITLE
Applying Yellow Rings / Yellow Packets to the Server [Tutorial]

### ISSUE THREAD

**Issue by giancarlosambayan** [Megabyte918/MultiOgar-Edited#1301]
Make your own js file at src>gamemodes
Make it "PartyMode.js"
Open it and paste this

Copy and Paste this : https://pastebin.com/zwi0m2vZ
(I uploaded it in pastebin cuz when i put the code here
it just messed up)

Then save , go to gamerserver.ini
Change the `serverGamemode = 0` to `serverGamemode = 10`
Then run the server and you should see yellow rings in your cell 
~Gian
PS : found dis cuz i was messing up with FFA.js lol
its the same as FFA.js just changed something :p

**Comment by giancarlosambayan** [comment]
@Agarian @MastaCoder @Megabyte918 @Fan7asy Cant merge it so i made an issue lol ,

**Comment by MiraMiPalo** [comment]
or just change serverGamemode to another xD

**Comment by giancarlosambayan** [comment]
@MiraMiPalo xd

**Comment by Agarian** [comment]
What is that changed "something"? I see no change other than the gamemode name, and gamemode id. Also please note that you also need to add the gamemode to `src/gamemodes/index.js`.

**Comment by giancarlosambayan** [comment]
@Agarian idk bout the index.js but it does work anyways

**Comment by ArixProject** [comment]
![image](https://user-images.githubusercontent.com/29149118/31874646-04ec802e-b7d3-11e7-82bb-9060499cd045.png)
Hmm

**Comment by giancarlosambayan** [comment]
@ArixProject it works for me and for megabyte
maybe u did something wrong ._.

**Comment by ArixProject** [comment]
my fail

**Comment by ArixProject** [comment]
![image](https://user-images.githubusercontent.com/29149118/31874711-5be9e7ea-b7d3-11e7-9783-e95fe6e7129b.png)

**Comment by ArixProject** [comment]
![image](https://user-images.githubusercontent.com/29149118/31874722-6a5596e4-b7d3-11e7-9a15-4136bd911ec7.png)
how to add friends ?

**Comment by giancarlosambayan** [comment]
@ArixProject that's gonna be applied in the server soon as soon as i get my hands on that code lol just wit for my update

**Comment by ArixProject** [comment]
okay

**Comment by ThebigbossCE** [comment]
Yeah ! I thanks for this "party mode style" :)

**Comment by Fan7asy** [comment]
This has been out there since v13.

**Comment by giancarlosambayan** [comment]
@Fan7asy What do you mean?

**Comment by giancarlosambayan** [comment]
#916 #905

**Comment by Fan7asy** [comment]
This code has existed since protocol version 13.
It is useless, unless a party mode is actually implemented.

**Comment by Niall7459** [comment]
I’m going to try to write a party mode in MySQL and php just fire up a server and do friend system through the client with PHP and MySQL then match two players that are friends onto there own server..
