### ISSUE TITLE
Bot error

### ISSUE THREAD

**Issue by josefredohd** [Megabyte918/MultiOgar-Edited#1302]
https://gyazo.com/0fb15f5295d0c71c2586e9bc134d1d2b

**Comment by Agarian** [comment]
@josefredohd Hmm, odd. Does this occur with the latest version? And do you have a modified version? You should make sure the `Vec2.js` file still exists in the `modules` folder. If not, you need to add it back.

**Comment by suprix** [comment]
i recommend to delete whole node_modules and install deps again

**Comment by AlexHGaming** [comment]
@josefredohd you do not have the Vec2.js file. Try reinstalling the server to the latest version and try again.

**Comment by josefredohd** [comment]
I work thanks
