### ISSUE TITLE
How to fix the doublesplits in MultiOgar of Barbosik

### ISSUE THREAD

**Issue by josefredohd** [Megabyte918/MultiOgar-Edited#1303]
#644

**Comment by MiraMiPalo** [comment]
![hqdefault](https://user-images.githubusercontent.com/25539632/32146762-4bb6290a-bca2-11e7-866a-695ade659c82.jpg)

**Comment by josefredohd** [comment]
:V

**Comment by josefredohd** [comment]
JoseAlfredo-josef128339.codeanyapp.com:8081   entra a mi server

**Comment by josefredohd** [comment]
http://athex.io/?ip=JoseAlfredo-josef128339.codeanyapp.com:8081

**Comment by Shair17** [comment]
Mira men, MegaByte ha cambiado un chingo de cosas, es algo muy tedioso solucionar eso, pero hay una forma de hacerlo xdd

**Comment by josefredohd** [comment]
Cual es we

**Comment by Shair17** [comment]
Reservado para duex :)

**Comment by josefredohd** [comment]
xD

**Comment by josefredohd** [comment]
entra al server

**Comment by MiraMiPalo** [comment]
soy level 100 en duex :v

**Comment by josefredohd** [comment]
quien

**Comment by Shair17** [comment]
Ufff que rikolino xdd

**Comment by josefredohd** [comment]
yo soy como 13

**Comment by josefredohd** [comment]
lo jugue un rato y subi rapido de nivel xD

**Comment by josefredohd** [comment]
ya tengo el autorestart

**Comment by MiraMiPalo** [comment]
ves que tanto te costo :v

**Comment by josefredohd** [comment]
Una madre

**Comment by MiraMiPalo** [comment]
me lo pasas? xD

**Comment by Shair17** [comment]
@MiraMiPalo Discord?

**Comment by Agarian** [comment]
That was me, the Unnamed Cell XD

**Comment by josefredohd** [comment]
xD

**Comment by MiraMiPalo** [comment]
@Shair17 si lo tengo we xD

**Comment by Shair17** [comment]
@MiraMiPalo Cual es pues :v

**Comment by josefredohd** [comment]
hey miramipalo pasa discord

**Comment by Shair17** [comment]
@josefredohd ALV, me vale verga prro ;v

**Comment by josefredohd** [comment]
Jalateee

**Comment by Shair17** [comment]
ke

**Comment by josefredohd** [comment]
El doublesplit

**Comment by Shair17** [comment]
Nel, me demoro un chingo averiguar como, para ponerme a buscar en las primeras versiones, hay una version de barbosik que esta arreglado el doble, la checkrigidcollision o algo asi

**Comment by josefredohd** [comment]
ok gracias por la pista xD

**Comment by MiraMiPalo** [comment]
pues en que falla el doble? :v

**Comment by josefredohd** [comment]
sale todo chueco

**Comment by MiraMiPalo** [comment]
@Shair17  we como logro la doble T en Ultrasplit? :v

**Comment by Shair17** [comment]
pues mira we, como te ekzplico, primero presionas una ves la t, luego de eso rikuras, lo haces otra vez, y pos ya esta no
ah karnal tutorial mas isi no puede haber ;VV

**Comment by josefredohd** [comment]
Jajaja

**Comment by MiraMiPalo** [comment]
lo intentare ♥ +1 sub

**Comment by Shair17** [comment]
y tu discord?

**Comment by MiraMiPalo** [comment]
miramipalo#8607

**Comment by Shair17** [comment]
Me acuerdo de ti porque eras fan de rubinho todo manko xdd

**Comment by MiraMiPalo** [comment]
si soy un pinshew pro :v no te metas con papi rubinho 7u7

**Comment by Agarian** [comment]
Hola chicos, ¿de qué están hablando? (͡ ° ͜ʖ ͡ °)

**Comment by MiraMiPalo** [comment]
@Agarian de lo mucho que me amas! ♥

**Comment by ArixProject** [comment]
@MiraMiPalo

**Comment by ArixProject** [comment]
@MiraMiPalo #1299

**Comment by AlexHGaming** [comment]
I copyrighted that issue!™

**Comment by josefredohd** [comment]
why

**Comment by mafiakb** [comment]
la invacion de latinos xD

**Comment by AlexHGaming** [comment]
can we speak english please kthnx

**Comment by Agarian** [comment]
lol
