### ISSUE TITLE
How to fix restart?

### ISSUE THREAD

**Issue by ArixProject** [Megabyte918/MultiOgar-Edited#1304]
image
![image](https://user-images.githubusercontent.com/29149118/32326346-87371072-bfe3-11e7-9e3e-63dd2831a787.png)

**Comment by Agarian** [comment]
@Fan7asy I think this one's for you.

**Comment by Fan7asy** [comment]
This code is non-existent.

**Comment by ArixProject** [comment]
@Fan7asy why? i use new version

**Comment by Fan7asy** [comment]
No you're using your own version

**Comment by ArixProject** [comment]
ummm... no

**Comment by Fan7asy** [comment]
As far as im aware `index.js` only has `57` lines of code not `185`

**Comment by Fan7asy** [comment]
Please show me where the line of code you've shown is located within MultiOgar-Edited and I may be able to assist you.
