### ISSUE TITLE
Lol what?

### ISSUE THREAD

**Issue by ArixProject** [Megabyte918/MultiOgar-Edited#1307]
![image](https://user-images.githubusercontent.com/29149118/32394383-fcb189a8-c0ed-11e7-8bef-1e8d7706cfe2.png)
lol

**Comment by AlexHGaming** [comment]
@ArixProject did you do a certain command when this happened? Did this happen when opening the server?

**Comment by Fan7asy** [comment]
Look above the error @AlexHGaming

**Comment by AlexHGaming** [comment]
Ah,

**Comment by AlexHGaming** [comment]
Oh ffs i was gonna explain what my brain was thinking

**Comment by Fan7asy** [comment]
lol

**Comment by AlexHGaming** [comment]
_Must test before committing_

**Comment by ArixProject** [comment]
lol

**Comment by ArixProject** [comment]
Okay, I'll try to fix it solo
And my english is bad :C

**Comment by ArixProject** [comment]
thx

**Comment by Fan7asy** [comment]
np

**Comment by ZfsrGhS953** [comment]
@ArixProject If you want people to notice your issue, use descriptive issue names.

**Comment by ArixProject** [comment]
@ZfsrGhS953 okay
