### ISSUE TITLE
Client Sided or Server Sided?

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1308]
How can I make it so the mass updates to whatever mass the current player is.
For example
My high score is 5405
My current mass: 4544
How can I make `mass: 5405` turn into `mass: 4544` as if it is the same mass as the player?

# great grammar alex well done.

**Comment by Agarian** [comment]
Wwll, this is client sided, but I believe it may be easy for custom clients.

**Comment by AlexHGaming** [comment]
Alright.

**Comment by Agarian** [comment]
In early clients, you can actually press ESC and then the play button, and your high score is updated to your current score. Say my high score was 22500 mass, and my current score is 19000 mass. Pressing ESC then the play button will change my high score from 22500 to 19000.

**Comment by AlexHGaming** [comment]
I know this lol, I just wanna do it as if it updated without pressing ESC.

**Comment by Agarian** [comment]
I know that, but I don't think I'd know how, or bother to try lol

**Comment by FirstCodeReviewer** [comment]
Client of Luka has this Feature built in.
