### ISSUE TITLE
How we can block bots?

### ISSUE THREAD

**Issue by korlight** [Megabyte918/MultiOgar-Edited#1309]
Hi, how we can block bots? Like this video https://www.youtube.com/watch?v=_orOQrsuleo

They can connect directly to the server.

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L82

**Comment by AlexHGaming** [comment]
Put that to 0.

**Comment by ZfsrGhS953** [comment]
@korlight These "bots" are the stupid bots that do nothing more than ruin the server. However, I'm working on a "innovational smart bot technology" (?) that will fix all of these problems and allow both normal players and players with bots to be happy.

**Comment by Agarian** [comment]
Yeah, the bot's AI or "smartness" has gone down hill quite a bit, they can't even shoot viruses at people anymore (though I think that was removed on purpose), not to mention they tend to have an `influence` to smaller cells, even if there's a larger cell that will eat the bot after that bot eats the smaller cells.
