### ISSUE TITLE
Spawnmass to ip

### ISSUE THREAD

**Issue by ArixProject** [Megabyte918/MultiOgar-Edited#1310]
Mass boost :D
Example : Me : i joined the game and my spawnmass the have 4k
Other : I joined the game and my spawnmass the have 1k

**Comment by ArixProject** [comment]
duplicate!!! [closed]

**Comment by ArixProject** [comment]
@Fan7asy 
make issue to duplicate

**Comment by ArixProject** [comment]
for other why duplicate #262

**Comment by EduardoSebastian** [comment]
I not know this project, but i can imagine:

```
var ips = ["192.168.0.1","131.221.49.203"];
ips.forEach( e => { e.mass = 4000;});
```
