### ISSUE TITLE
Virus command on PlayerCommands.js ?

### ISSUE THREAD

**Issue by ArixProject** [Megabyte918/MultiOgar-Edited#1311]
title
and no say to `server sided` :C

**Comment by AlexHGaming** [comment]
Why would it be client sided lol

**Comment by ArixProject** [comment]
ops

**Comment by Agarian** [comment]
You want to spawn viruses with a chat command?

**Comment by MiraMiPalo** [comment]
pop: function (args) {
        var Entity = require("../entity");
        var id = parseInt(args[1]);
        if (isNaN(id)) {
            this.writeLine("Please specify a valid player ID!");
            return;
        }
        for (var i in this.gameServer.clients) {
            if (this.gameServer.clients[i].playerTracker.pID == id) {
                var client = this.gameServer.clients[i].playerTracker;
                if (!client.cells.length) return Logger.warn("That player is either dead or not playing!");
                var virus = new Entity.Virus(this.gameServer, null, client.centerPos, this.gameServer.config.virusMinSize);
                this.gameServer.addNode(virus);
                this.writeLine("Popped " + client._name);
            }
        }
        if (client == null) return void this.writeLine("That player ID is non-existant!");
    },

**Comment by Agarian** [comment]
I forgot about a command that I created in the first place =/

**Comment by ArixProject** [comment]
@MiraMiPalo Thanks <3

**Comment by ArixProject** [comment]
@MiraMiPalo Wtf?
![image](https://user-images.githubusercontent.com/29149118/32415564-ccf11e44-c24c-11e7-924d-68c6887d8cbb.png)

**Comment by ArixProject** [comment]
@EduardoSebastian nice code -_-

**Comment by Fan7asy** [comment]
@EduardoSebastian Nice job 😄

**Comment by EduardoSebastian** [comment]
Ok, I can help you, if you put me in context, I dont want to check all the code to see what each thing means here @ArixProject

**Comment by ArixProject** [comment]
okay

**Comment by Fan7asy** [comment]
I'm sorry, but I have to close this as it categorises as `Custom Code` and as stated before we cannot help with that.

**Comment by EduardoSebastian** [comment]
so i cant help you @ArixProject , laws of this project

**Comment by ArixProject** [comment]
@EduardoSebastian thank

**Comment by MiraMiPalo** [comment]
@ArixProject you sure that put the code in PlayerCommand, and not in commandList? xD

**Comment by Agarian** [comment]
@MiraMiPalo Add the below code into `PlayerCommand.js`:
```js
pop: function (args) {
    var Entity = require("../entity");
    var id = parseInt(args[1]);
    if (isNaN(id)) {
        this.writeLine("Please specify a valid player ID!");
        return;
    }
    for (var i in this.gameServer.clients) {
        if (this.gameServer.clients[i].playerTracker.pID == id) {
            var client = this.gameServer.clients[i].playerTracker;
            if (!client.cells.length) return this.writeLine("That player is either dead or not playing!");
            var virus = new Entity.Virus(this.gameServer, null, client.centerPos, this.gameServer.config.virusMinSize);
            this.gameServer.addNode(virus);
            this.writeLine("Popped " + client._name);
        }
    }
    if (client == null) return void this.writeLine("That player ID is non-existant!");
},
```

**Comment by MiraMiPalo** [comment]
@Agarian wtf! i dont need the code

**Comment by DeadLord1337** [comment]
wot

**Comment by Fan7asy** [comment]
I'm going to lock this, the code has been provided, the help has also been provided.
