### ISSUE TITLE
I need an agar client.

### ISSUE THREAD

**Issue by Arena1245** [Megabyte918/MultiOgar-Edited#1312]
I want a custom agar client that has at least a triple split macro and a double split macro for me to play. I do not like playing on the agar.io site. Please help me.

**Comment by AlexHGaming** [comment]
@Arena1245 Try installing a client (cigar client for example, i recommend [luka's](http://github.com/Luka967/Cigar) client, and modify it and run it off there.

**Comment by Arena1245** [comment]
OK Alex, thank you.

**Comment by Fan7asy** [comment]
I have an Open Source client.
You may download it [here](https://github.com/Fan7asy/Client).
