### ISSUE TITLE
How can I change the graphics of my agar client?

### ISSUE THREAD

**Issue by Arena1245** [Megabyte918/MultiOgar-Edited#1313]
I want for that option that defines the graphics of the game that has' medium, mobile, high and retina

**Comment by Agarian** [comment]
Hold up, `mobile` quality? Also this is a client sided issue, obviously (though semi-easy to implement).

**Comment by Arena1245** [comment]
Yes, teach me how to.

**Comment by AlexHGaming** [comment]
This is a server repo, not a client repo. Client sided.

**Comment by Arena1245** [comment]
?

**Comment by AlexHGaming** [comment]
This has nothing to do with MultiOgar-Edited.

**Comment by Agarian** [comment]
If you want the graphics feature as from the current version of agar.io, I can't help you there. Maybe the graphics options from an older version of agar.io (like v72).

**Comment by Arena1245** [comment]
Can be

**Comment by Fan7asy** [comment]
I know a way, learn JS.

**Comment by Faris90** [comment]
mm
