### ISSUE TITLE
Create FFA game mode with Time

### ISSUE THREAD

**Issue by ChikoxD** [Megabyte918/MultiOgar-Edited#1315]
Hello Megabyte918 you can create a game mode in **FFA** that is with 1 hour restart time like Tournament. The game must show the list of players, the restart time and in the end congratulate the player who won the game.

**Comment by FirstCodeReviewer** [comment]
Thats exactly what my PR was made for. Just use Tournament Mode. There is no need to restart the server. You can set the Tournament Time at 1 hour. Afterwards the winner will be congraduated. Even the time of the Tournament is beeing displayed.. There is no need for Megabyte to create a new gamemode.. 
@Fan7asy Closerequest

**Comment by ChikoxD** [comment]
the difference of **FFA** and Tournament is Tournament starts the game when it reaches the number of players that you put and in **FFA** the time should run like that between any player.

If you have it, can you give it to me?

**Comment by Agarian** [comment]
Tournament is a game mode...
Set the value `serverGamemode` in `gameserver.ini` to 4.

**Comment by AlexHGaming** [comment]
If you ever want megabyte to do anything, he wont. He has disbanded the repo, just like Barbosik.

**Comment by Fan7asy** [comment]
@AlexHGaming That's where you are wrong, Megabyte is very busy, he has school and work in real life.
Just because he has not been active doesn't automatically mean that he disbanded the repo.

**Comment by AlexHGaming** [comment]
He kinda has. He is working on a new fork, I think he said to me in DM's saying he isn't working on the repo anymore.

**Comment by ChikoxD** [comment]
I found this website http://happyfor.win/ as an example of FFA. Some of you can help me know how to get it.

**Comment by Fan7asy** [comment]
Also to clarify, Barbosik left GitHub not the `MultiOgar` repository specifically.

**Comment by FirstCodeReviewer** [comment]
@ChikoxD 
Well yes thats a huge Problem.
Just look at this Line: https://github.com/Megabyte918/MultiOgar-Edited/blob/2f312412b2e7bd296df4c006d0d39ded35e71286/src/gamemodes/Tournament.js#L143
And this one:
https://github.com/Megabyte918/MultiOgar-Edited/blob/2f312412b2e7bd296df4c006d0d39ded35e71286/src/gamemodes/Tournament.js#L138

Finally then do the startGamePreparation onServerInitialization and your done.

**Comment by AlexHGaming** [comment]
Alrighty
