### ISSUE TITLE
Did anyone tried to add anti-teaming penalty on multiogar edited?

### ISSUE THREAD

**Issue by ThebigbossCE** [Megabyte918/MultiOgar-Edited#1316]
Hi all :D 
I just want to know if anyone tried to add the anti-teaming penalty on multiogar edited? Because i know  the Ogar server have an "anti-team" option..

This can be cool, yes, so if you know any server working with this option, please share it :D 

thx.

**Comment by NuclearC** [comment]
Im afraid its gonna be shit like agar's anti teaming

**Comment by Fan7asy** [comment]
It would also affect preformance.

**Comment by ThebigbossCE** [comment]
@NuclearC Yeah :D but i like it because this can be cool
and @Fan7asy yes i know but if one user wants to use/activate it, it's because he wants to do that, true ? I tried to add anti-teaming bu myself but i'm not really expert on it and this doesn't work..

**Comment by AlexHGaming** [comment]
Wasn't this already a feature?

**Comment by Agarian** [comment]
In Ogar, not MultiOgar-Edited.

**Comment by ZfsrGhS953** [comment]
@Fan7asy What about postformance?

**Comment by Fan7asy** [comment]
My spelling isn't the best, leave me alone 😛 @ZfsrGhS953
