### ISSUE TITLE
Cannot Connect

### ISSUE THREAD

**Issue by CodeFlush** [Megabyte918/MultiOgar-Edited#1317]
I cannot connect to any client, when ever i create a server it only works on the agar.io client but not any other client... Why? I tried reinstall MOE and Got a fresh client that works for everyone else but its not working, it only owrks through agarclient
(Using **CodeAnywhere**)

**Comment by Fan7asy** [comment]
I'm not too sure why this is happening, may I know which clients you've used?

**Comment by CodeFlush** [comment]
@Fan7asy 
Yours
Lukas
Cigar

**Comment by Fan7asy** [comment]
Okay, try renewing your Internet Protocol Configurations.
Follow these instructions:
1. Go into `Command Prompt`.
2. Type in `ipconfig /release`.
3. Wait, then type `ipconfig /renew`

**Comment by Fan7asy** [comment]
Run 
```
connect("ws://127.0.0.1:<port>");
```
In the developer console.

**Comment by Fan7asy** [comment]
Now that you've edited your message, make sure that you've read on how to get your application IP, and port on CodeAnywhere.

**Comment by CodeFlush** [comment]
I did get it right, if i didnt y would it work on agar client 🔢

**Comment by CodeFlush** [comment]
(https://i.imgur.com/iEPtt9m.png)
**Again, it works perfectly fine in agar.io/?ip=xxx:port**

**Comment by Agarian** [comment]
Are you by chance using a client that runs off of gitbub.io? What client are you using that isn't working? And did you change the config `serverBind`?

**Comment by CodeFlush** [comment]
Used all the client listed above , no changes were made to client and serer bind , freshly installed

**Comment by CodeFlush** [comment]
To make ^^ Clear 
I used the client stated above , however only one works, agar.io client and I freshly installed MOE and No changes were made client-side. I get a error message in my console box (given ^^^)

**Comment by CodeFlush** [comment]
@Fan7asy Why is this Closed?

**Comment by Fan7asy** [comment]
I closed this because it is not a direct issue with MultiOgar-Edited.

**Comment by AlexHGaming** [comment]
What about #1264 😂

**Comment by Fan7asy** [comment]
@AlexHGaming Its an exception, it was open before i added the new rules.
It is up to the author to close it.

**Comment by cowpits** [comment]
@CodeFlush out of curiosity, are you hosting your client on 000webhost? i think i know your problem if your client link starts with https:// then it will never connect. use http://

**Comment by CodeFlush** [comment]
@cowpits  Thanks i am using 000webhost

**Comment by cowpits** [comment]
yeah I figured it's trying to use SSL in the link. I get that all the  time on my youtube channel. Glad it's worked out for you man.

**Comment by ZfsrGhS953** [comment]
@CodeFlush Then stop using 000webhost. It injects some additional code into the page that can mess up anything. Move it to Github Pages.

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 PHP doesn't operate with github I think.

**Comment by Luka967** [comment]
@CodeFlush This should've already been apparent if you were to check the browser's console. You need to manually adjust whether the websocket connection is secure (`wss` instead of `ws`) on Fantasy's client, whereas mine and Cigar do that automatically. Unless you've set up SSL on your gameserver, you'd never make a connection because having an insecure websocket connection on an HTTPS site is prohibited, and a connection is not possible if you're requesting a secure websocket connection on a SSL 
disabled gameserver. An error message should've been there either way. I haven't tested it myself.
@cowpits There's no malicious code involved.

**Comment by Fan7asy** [comment]
Here's luka with his brainy stuff.

**Comment by Luka967** [comment]
Don't bully me >:(

**Comment by Fan7asy** [comment]
Soreh

**Comment by cowpits** [comment]
@Luka967 I know there's no malicious code lol. I was just pointing out that 000webhost defaults to https:// when the site is published and most people don't catch that. A few months ago I made a tutorial on Cigar using Hostinger but now it's not free so I tell people to use 000webhost. :)

**Comment by Luka967** [comment]
Wrong mention on my end lol

**Comment by cowpits** [comment]
lol check out what I've done with it http://gkclan.me but I want a minimap, one day though. Thank you.

**Comment by Luka967** [comment]
Oh yeah, I'm going to make a minimap on my fork by the end of the week. Gonna be basic though

**Comment by Fan7asy** [comment]
~~Oh yeah, no one cares~~ Your client will be even 🅱️etter 🙂

**Comment by Fan7asy** [comment]
Nice @Luka967
