### ISSUE TITLE
PlayerList command - playerCommands.js

### ISSUE THREAD

**Issue by SparlBlyad** [Megabyte918/MultiOgar-Edited#1318]
# **Please read this notice throughly before creating your issue.**

### Before you create your issue you ***MUST*** follow these rules: 

1. **The issue is in written in English.**
2. **The issue is directly related to the project.**
3. **Your issue is not a duplicate of a previous issue.**
4. **Descriptive information must be provided, so that we can reproduce the error you are experiencing**
5. **Error logs must be provided if any crashing is experienced.**

>**Please note that we will *NOT* provide assistance if the issue is with your own code, your issue WILL be locked if this is the case.**

# **Issue Formatting**

**In order for us to provide you with the best assistance we kindly ask you to present your issues in the best way that you can.**

Please read through [this guide](https://guides.github.com/features/mastering-markdown) to learn how you can apply [Markdown](https://en.wikipedia.org/wiki/Markdown) to your issues.

>---

**IF YOU HAVE READ THESE RULES PLEASE DELETE THIS TEXT**

**Comment by SparlBlyad** [comment]
I need playerlist command in playercommands.js. can anyone give me code?

**Comment by Agarian** [comment]
Lets start with the fact that text displayed by the playerlist command wouldn't even fit in the chat.

**Comment by SparlBlyad** [comment]
oh, ok. I'm closing issue.

**Comment by ChamMGamer7** [comment]
@SparlBlyad lol

**Comment by ChamMGamer7** [comment]
@SparlBlyad i have a command playerlist
