### ISSUE TITLE
Player id

### ISSUE THREAD

**Issue by SparlBlyad** [Megabyte918/MultiOgar-Edited#1319]
# **Please read this notice throughly before creating your issue.**

### Before you create your issue you ***MUST*** follow these rules: 

1. **The issue is in written in English.**
2. **The issue is directly related to the project.**
3. **Your issue is not a duplicate of a previous issue.**
4. **Descriptive information must be provided, so that we can reproduce the error you are experiencing**
5. **Error logs must be provided if any crashing is experienced.**

>**Please note that we will *NOT* provide assistance if the issue is with your own code, your issue WILL be locked if this is the case.**

# **Issue Formatting**

**In order for us to provide you with the best assistance we kindly ask you to present your issues in the best way that you can.**

Please read through [this guide](https://guides.github.com/features/mastering-markdown) to learn how you can apply [Markdown](https://en.wikipedia.org/wiki/Markdown) to your issues.

>---

**IF YOU HAVE READ THESE RULES PLEASE DELETE THIS TEXT**

**Comment by SparlBlyad** [comment]
I want to close with player nicname was his ID. is this possible?

**Comment by AlexHGaming** [comment]
@SparlBlyad Not understanding on what you're trying to address.

**Comment by Fan7asy** [comment]
No idea what you mean.

**Comment by AlexHGaming** [comment]
And @Fan7asy you are now unbanned from the MultiOgar-Edited Discord Server.

**Comment by CodeFlush** [comment]
He means he wants the nick of the user to be their id? nothing else atleast i think so. @Fan7asy
