### ISSUE TITLE
how to that omg

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#132]
WTf in this page yourself see your skins, how as that omg another plz explain me? WTF

http://minemoore.uk.to/agar/

**Comment by Megabyte918** [comment]
@AlexByte918 It is a different client. MiniClip has patched skins on private servers on their client so you won't be able to see your own skin. If you want to see your own skin use the CustomSkins script in the /scripts folder.
Also, don't make issues for simple questions like this, it's not worth it.

**Comment by MineMooreALT** [comment]
.
