### ISSUE TITLE
How to make Mother-cell Shoot Food a lil further?

### ISSUE THREAD

**Issue by CodeFlush** [Megabyte918/MultiOgar-Edited#1322]
Ok the issue with the current mother cell is that, when its fed the food it shoots out is way close to the mother cell, some of them barely make it out. How do i make it so food thats being shot gets a lil further from the mother cell?

**Comment by Agarian** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/MotherCell.js#L62
Change around the numbers there, higher numbers mean farther shot distances.

**Comment by CodeFlush** [comment]
Thanks it sort of QOrk, but is there a way to make it come out faster too?

**Comment by Agarian** [comment]
I'm not too sure about that.

**Comment by Luka967** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gamemodes/Experimental.js#L18
Also increase the maximum food count.

**Comment by CodeFlush** [comment]
Alright Man, @Luka I appreciate the fact that you made a client for everyone to use , Thank You
@Agarian You are a great helper Bud, Thank You!
