### ISSUE TITLE
 Agar.io blocks the client

### ISSUE THREAD

**Issue by Gatoz** [Megabyte918/MultiOgar-Edited#1323]
Hello, today I connect to my client of agar.io http://agar.io/?ip=127.0.0.1:443 and I notice that it is blocked, it is the new update that includes DNA, as it can be solved, hope your help, Thanks

**Comment by cowpits** [comment]
I just posted the fix #1324

**Comment by Gatoz** [comment]
thank you very much

**Comment by Gatoz** [comment]
there is a problem with the use of skins, they all have the same skins

**Comment by Agarian** [comment]
Is this in the custom skins script?

**Comment by AlexHGaming** [comment]
@Agarian Nope.
