### ISSUE TITLE
miniclit agar.io client update

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#1324]
Mniclit (not a type) new update for agar.io client if you can't connect, change this line in PacketHandler.js
I tested it on 1.3.5 I'm sure it's the same for 1.6.1, leaderboard seems fine thus far. 
from 
if (this.handshakeProtocol < 1 || this.handshakeProtocol > 15)
to
if (this.handshakeProtocol < 1 || this.handshakeProtocol > 17)

**Comment by cowpits** [comment]
Line 38 of PacketHanderl.js file ver 1.6.1 to be specfic.

**Comment by ChamMGamer7** [comment]
fucking miniclip xd

**Comment by Gatoz** [comment]
Thanks Cowpits, you are the maximum

**Comment by ChamMGamer7** [comment]
i hate a miniclip agario new update

**Comment by cowpits** [comment]
lol it's miniclit and not a typo

**Comment by Gatoz** [comment]
the update is good, in my opinion it will improve the agar.io, the bad that has blocked the client, a query how can I put skin on my agar.io client

**Comment by ChamMGamer7** [comment]
lol @cowpits 
![image](https://user-images.githubusercontent.com/33523998/32958450-96e47512-cbcf-11e7-8b3b-f1d71e5ddd5f.png)

**Comment by AlexHGaming** [comment]
Going to PR this.

**Comment by DeadLord1337** [comment]
Update!!! not connect :O

**Comment by Gatoz** [comment]
@ChamMGamer7  lol HOW IT OUTED YOU, IT SEES GREAT 

please, better solution to connect as before, since all appear with the same skins

**Comment by DeadLord1337** [comment]
settings no skins = crash server

**Comment by cowpits** [comment]
I didn't notice the skins problem, I only looked at connection, need to dig deeper into the skins. At least if I put a skin name in <sly>name it shows it. before it wouldn't show my skin but could see everyone else's skin.

**Comment by DeadLord1337** [comment]
@cowpits блэт

**Comment by AlexHGaming** [comment]
@DeadLord1337 english only

**Comment by DeadLord1337** [comment]
:В

**Comment by cowpits** [comment]
for me on 161 and 135 the no skin option on agar.io client doesn't crash the server, it only disconnects the client or kills the cell.

**Comment by cowpits** [comment]
this is what I get when I have a skin and select no skin tick box. https://i.imgur.com/zuSOtxU.jpg

**Comment by Agarian** [comment]
Yeah, all skins apparently are all the same now...

**Comment by cowpits** [comment]
i don't know what protocol they're using for the skins. line 120 in PlayerTracker.js  this._skinUtf8protocol11 = writer1.toBuffer();
if you change the protocol number, you won't see skins and doesn't crash the client but i know you want skins.

**Comment by ZfsrGhS953** [comment]
@cowpits The first thing that came to my head while thinking what ```mniclit``` means is **m**ounted **n**etwork **i**nterface **c**ommand **l**ine **i**nterface **t**erminal. Pretty impressive, considering that they can't even make their game run at 60 FPS.

**Comment by cowpits** [comment]
@ZfsrGhS953 that is impressive on your part actually to come with that. but I actually typed it with a t instead of p on purpose. lol. I would've called them mininip if it fits but miniclit was the closest to miniclip, and serves the same purpose. Well, almost... :P

**Comment by ZfsrGhS953** [comment]
@cowpits Look closely at it. There's nothing between m and n (in the description, not the title).

**Comment by cowpits** [comment]
oh boy lol

**Comment by Agarian** [comment]
Somebody should propose a name change for Miniclip 😆 
#MiniClit

**Comment by CodeFlush** [comment]
right
