### ISSUE TITLE
Random ejected mass spawn selection is wrong.

### ISSUE THREAD

**Issue by Tombez** [Megabyte918/MultiOgar-Edited#1325]
Line 890 of GameServer.js: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L890
`var index = (this.nodesEjected.length - 1) * ~~Math.random();`
Variable `index` will always be `0`, because double not `~~` will truncate the random number which is normally a float from `0` inclusive to `1` exclusive, to `0`. Then no matter what `this.nodesEjected.length - 1` is, you multiply it by `0`.

If you want a random index of `this.nodesEjected`, use:
`var index = ~~(this.nodesEjected.length * Math.random());`

If you just wanted `0`, use `0`.

**Comment by Agarian** [comment]
Come to think of it, this may explain why ejected cells seem to sometimes disappear instead of spawning cells.

**Comment by Tombez** [comment]
I don't believe this is the reason, if that is happening. The ejected mass is never explicitly removed, which makes it seem like the server relies on the fact that the newly spawned player will immediately eat it.

This issue only makes it so the oldest ejected mass is always picked to spawn a new player, which isn't really a bad thing at all.

**Comment by Agarian** [comment]
I see now that the removal of the ejected cells only existed in an older version lol
