### ISSUE TITLE
Auto Split

### ISSUE THREAD

**Issue by smatch999** [Megabyte918/MultiOgar-Edited#1329]
Hello,
Have possibility for disable auto-split!?
Example: player get 50.000 mass and stop, NO auto-split.
Thank you!

**Comment by Agarian** [comment]
A very easy way to do this is to set the config `playerMaxSize` to a massive number (like 999999), then set the config `playerDecayCap` to whatever mass (or size value) that you want.

**Comment by smatch999** [comment]
Oh,
I work with this code, is correct?

`GameServer.prototype.autoSplit = function (cell, client) {
    // get size limit based off of rec mode
    if (client.rec) var maxSize = 1e9; // increase limit for rec (1 bil)
    else maxSize = this.config.playerMaxSize;

    // check size limit
    if (client.mergeOverride || cell._size < maxSize) return;
    if (client.cells.length >= this.config.playerMaxCells || this.config.mobilePhysics) {
        // cannot split => just limit
        cell.setSize(maxSize);
    } else {
        // split in random direction
        cell.setSize(maxSize);
    }
};`

**Comment by smatch999** [comment]
My code above works for me.
Thanks!

**Comment by Agarian** [comment]
Well, that works too
