### ISSUE TITLE
Player command /id

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#133]
Hello! so i was making this player id command /id so players can see their id.
Now when i add the command so i can do /id in the chat it works but then i try adding the PlayerID thing it crashes.

https://gyazo.com/a4ecc1429634ce03801d66ba252b38d5

it that right?

sorry if its hard to understand.

**Comment by Megabyte918** [comment]
@CalvinDKL 
<pre>
id: function (args) {
    this.writeLine("ID: " + this.playerTracker.pID);
},
</pre>

**Comment by CalvinDKL** [comment]
Aha!, let me try.

**Comment by CalvinDKL** [comment]
Mega, maybe you can add it to this project?? i mean i got it to work, but maybe other people would want it.

**Comment by Megabyte918** [comment]
Yeah sure
