### ISSUE TITLE
improved plz...

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1330]
Make the splits more smooth and similar to vanilla, that part was more "obedient", that was not part was not shiver a little, I think so that it is necessary to add a maximum of 4-5 lines of code or remove some!! do not say that splits are similar to vanilla(they are like 65%) I know what you fantasy, luka, megabyte can do better!
I can give a slow mo video of a split of vanilla and MO-E, to view the details of how the split
This is the only drawback to MO-E bad split...
Please improve the splits, please...

**Comment by ZfsrGhS953** [comment]
@DeadLord1337 Do you want MultiOgar-Edited to simulate the latest update's lag?

**Comment by DeadLord1337** [comment]
@ZfsrGhS953 more detail do not understand a bit :D if you mean that the update will affect the performance that I somehow without a difference

**Comment by AlexHGaming** [comment]
@DeadLord1337 can you provide a GIF of vanilla splits vs mo-esplits?

**Comment by DeadLord1337** [comment]
@AlexHGaming hm no gif will be difficult easier for me to record video and then slow it down to fill here streamable.com

**Comment by DeadLord1337** [comment]
Vanilla:
https://streamable.com/4sj84
https://streamable.com/650l2
https://streamable.com/cqg26
Mo-E:
https://streamable.com/g3s3y
https://streamable.com/8vmwm
https://streamable.com/yowqn

**Comment by cowpits** [comment]
when members of TYT clan used to post their god like game play (pun) people used to ask me how they do their splits so smoothly. And they were on the agario client. What I found was we all play at highest resolution but they drop their display resolution so they can get these smooth splits. Try it.

**Comment by DeadLord1337** [comment]
@cowpits All also I changed the screen resolution in the config file to 800x480, all the same, changed the screen resolution in Windows, too, all exactly the same. How can the screen resolution actually affect the physics division lol

**Comment by cowpits** [comment]
I see videos with smooth splits on agar.io client and other people post vids on agar.io client but they don't look as smooth. I learned it was because of screen resolution. So laugh if you will, just look at youtube videos and you'll see what I mean.

**Comment by DeadLord1337** [comment]
@cowpits you may be right, but I don't believe, must still improve splits to Mo-E.
compare pop split vanilla (Macro fast double split) and Mo-E
Vanilla: 
https://streamable.com/47g20
https://streamable.com/92tmb
Mo-E:
https://streamable.com/f0ra8
https://streamable.com/q27u8
I meant that in a Mo-E fast pop splits (Macro double split) pieces seem to disappear, it was in all versions of the megabyte and the rest of the developers are not smart enough to fix it and did not pay attention to this, it can be considered a bug. Where the pieces disappear... lol
 Myself already half a year trying to fix this bug, but I'm not well versed in node...

**Comment by Fan7asy** [comment]
You're taking the word "splits" out of context. You're talking about **Popsplits**, **Pushsplits**, etc. Those are just 'tricks'. Splitting, is splitting your cell, and I don't find any issue with that.

**Comment by Fan7asy** [comment]
Nevertheless, I will try 'fixing' the 'splits'.

**Comment by chewythepig** [comment]
@Fan7asy dickhead improve performance lol (otherwise make this thing fit for production servers)

**Comment by Fan7asy** [comment]
**No**

**Comment by Fan7asy** [comment]
@DeadLord1337 [Is this good enough?](https://media.giphy.com/media/xUOxf59Cb2lPHY5F3G/giphy.gif)

**Comment by chewythepig** [comment]
@Fan7asy i usually do the same thing with like a min split size of 100, how did you do it?

**Comment by DeadLord1337** [comment]
@Fan7asy hmm I like it. But can you please do the pop split so that you have 17K and the 10K enemy (I hope that you have changed the code, not splitVelocity xD)
as here https://streamable.com/47g20

**Comment by ZfsrGhS953** [comment]
@DeadLord1337 Have you thought that the special effects on the video can speed it up or slow it down? Next time try to find an unedited video.

**Comment by DeadLord1337** [comment]
@ZfsrGhS953 Now there are very few those who make pop split through macros, all make it slowly. and about the effects in the video, I don't know... they all do lol. this is a video with vanilla speed I slow it down on youtube

**Comment by fayizan** [comment]
@cowpits Trying play at (75-100)fps for smoother gameplay

**Comment by DeadLord1337** [comment]
Luka's the best

**Comment by DeadLord1337** [comment]
@Megabyte918 why duplicate?

**Comment by Megabyte918** [comment]
@DeadLord1337 
#179 
#260 
#263 
#314 
#588 
#664

**Comment by AlexHGaming** [comment]
Savage!

**Comment by DeadLord1337** [comment]
#52
