### ISSUE TITLE
minion

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1331]
Are not interested in this idea? To make the update CommandList.js that was the function of "minionall or abbreviated as "mnall" for example, a player entered in the console "minionall 100 namebots" and all the people and bots had the minions xDD noice idea

**Comment by ChamMGamer7** [comment]
@DeadLord1337 
![image](https://user-images.githubusercontent.com/33523998/33241471-7a61da96-d2ce-11e7-84fe-7a238e3b27de.png)

**Comment by Fan7asy** [comment]
Just change the value of `serverMinions` in the config using the `change` command.
