### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by ElPigianerJone** [Megabyte918/MultiOgar-Edited#1332]
![image](https://user-images.githubusercontent.com/19348870/33241553-9596bd42-d2f9-11e7-8616-07d49923ac2f.png)

**Comment by ItzLevvie** [comment]
Download the latest MultiOgar-Edited, this was fixed in https://github.com/Megabyte918/MultiOgar-Edited/pulls?q=is%3Apr+is%3Aclosed
