### ISSUE TITLE
Virus with a skin

### ISSUE THREAD

**Issue by Mesare** [Megabyte918/MultiOgar-Edited#1333]
How can I make so the virus have a skin? Like in gota.
I know how to change virus' color but idk how to put a skin.
it's server sided so don't just close the issue and say its client sided.

**Comment by Fan7asy** [comment]
Its Client sided.

**Comment by ZfsrGhS953** [comment]
@Fan7asy @Mesare 
```javascript
if (node.isSpiked) cellName = "name";
```
