### ISSUE TITLE
colored name

### ISSUE THREAD

**Issue by suprix** [Megabyte918/MultiOgar-Edited#1334]
How to make so:
if(player._name == 'example')

it will be colored name on the leaderboard (and on cell if possible)

**Comment by mafiakb** [comment]
client side!

**Comment by suprix** [comment]
It might be server side too...I made now colored name but only on cell, not on leaderboard.

**Comment by AlexHGaming** [comment]
@suprix Client sided I am afraid.

**Comment by Pollogy** [comment]
How do u do it on a cell though

**Comment by suprix** [comment]
Just changing some stuff..i don't remember the code rn Im not on pc but it was example
if(player._name == "Suprix") {
this.cellColor[] some shit idk 
};
but it changes to white once you split...
