### ISSUE TITLE
Playerlist command through chat coding help

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#1335]
Can someone take a look and let me know how I can return the human players only and not bots or minions, please?
@Megabyte918 you have helped me before with my silly chat commands can you take a look?
@AlexHGaming I'm tagging you because I miss you bro :)
I understand the chat box is limited but I'm also trying to figure out a way to make it scroll. 
Here's what I get currently: https://i.imgur.com/D82NYTL.png
Here's the code

   pl: function(args) {
        if (this.playerTracker.userRole != UserRoleEnum.ADMIN && this.playerTracker.userRole != UserRoleEnum.MODER) {
            this.writeLine("ERROR: access denied!");
            return;
        }
			var clients = this.gameServer.clients;
        clients.sort(function(a, b) { return a.playerTracker.pID - b.playerTracker.pID; });
        for (var i = 0; i < clients.length; ++i) {
            var client = clients[i].playerTracker;
            var socket = clients[i];
            var ip = client.isMi ? "[MINION]" : "BOT";
            if (socket.isConnected && !client.isMi) {
                ip = socket.remoteAddress;
            }
            var protocol = this.gameServer.clients[i].packetHandler.protocol;
            if (!protocol) {
                protocol = "?";
            }
            var data = "ID: " + client.pID + " - NICK: " + client._name + " - IP: " + ip;
            this.writeLine(data);
        }
    },

**Comment by AlexHGaming** [comment]
@cowpits Miss you too bro! I am not so certainly sure on this, maybe @Fan7asy could help out 😜

**Comment by cowpits** [comment]
no problem @AlexHGaming thank you and nice to hear from you again.

**Comment by Fan7asy** [comment]
Could you be a little bit more specific please?

**Comment by AlexHGaming** [comment]
@Fan7asy basically wants playerlist in chat, but he doesnt want minions and bots to be included into it.

**Comment by cowpits** [comment]
@Fan7asy the code is to do /pl and return players minions and bots though chat. But I only want to get human players not bots or minions. I keep trying but the only way I'm able to get any output is by adding the var ip = client.isMi ? "[MINION]" : "BOT"; without it, I get nothing.

**Comment by cowpits** [comment]
I got it !!!! bam !!! it came to me this morning while I was looking at my brain fart code. This is what I wanted look https://i.imgur.com/GvMmNEA.png
I know the chat can show up to 15 but I can live with that for now.

**Comment by AlexHGaming** [comment]
_close da issue_ @cowpits 👍

**Comment by Matthew-MK** [comment]
what code did you use?
