### ISSUE TITLE
How can I do push splits and double push on the Edited MultiOgar server.

### ISSUE THREAD

**Issue by Arena1245** [Megabyte918/MultiOgar-Edited#1337]
I wanted to play also doing push split on my server.

**Comment by SuperOP535** [comment]
GG issue #1337

**Comment by Fan7asy** [comment]
leet

**Comment by Fan7asy** [comment]
@Arena1245 I cannot help, this is to do with your own code...
But I can recommend a [video](https://www.youtube.com/watch?v=mpy0JQY1XGE) made by AlexHGaming.
