### ISSUE TITLE
Mbps speed for agar.io clients

### ISSUE THREAD

**Issue by Gasvash** [Megabyte918/MultiOgar-Edited#1339]
Hello, I have a cosulta, in the agar.io client, how much speed is needed for 30 or 50 players, in Mbps to render the game but without lag, and I would also like to know, if it is no longer possible to use masks by the update or if it can be configured, thanks.

**Comment by DeadLord1337** [comment]
buy a good VPS with fast speed :/

**Comment by Luka967** [comment]
A 100Mbps upstream & 20Mbps should handle up to 50-60 players with no problem.

**Comment by Gasvash** [comment]
@DeadLord1337  
Thank you I love you :D , tell me only I want for the client in agar.io, does it work or do I have to have a client of my own? , on the other hand, how much would a good VPS cost me for the client and where can I buy it?

**Comment by Gasvash** [comment]
@DeadLord1337 
please, can you help me to create my client with vps, please just tell me how I do it
