### ISSUE TITLE
More functions for minions

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#134]
delay for minions(new setting) MinionsDelay = (time in milliseconds) This setting add delay for follow mouse ( like bots with proxy) 
MinionSpawnDelay =  (time in milliseconds) This setting add delay after spawn minion (delay  
before move to mouse)
MinionMoveToCell = 0 (1 on 0 off)
Please, add it (i want this minions like old days, and this settings 
diversify minions )

**Comment by t11tanYT** [comment]
Please add this settings (i know 50% and more people want
this )

**Comment by Megabyte918** [comment]
@t11tanYT

> delay for minions(new setting) MinionsDelay = (time in milliseconds) This setting add delay for follow mouse ( like bots with proxy)

No point in adding delay, as you can just disconnect the bots or kill them.

> MinionSpawnDelay = (time in milliseconds) This setting add delay after spawn minion (delay
before move to mouse)

Read this: https://github.com/Megabyte918/MultiOgar-Edited/issues/115#issuecomment-263755354, the same thing would apply for MinionSpawnDelay.

> MinionMoveToCell = 0 (1 on 0 off)

Pointless, because you can just freeze the minions by using T

**Comment by AlexandriteErikParacelsus** [comment]
The move to cell feature is pretty useless in my opinion

**Comment by NameYT** [comment]
@Megabyte918 How to make bot smarter how about the calculation? i cant run my server 25+ GB make a video i dont understand you or just screenshot it :)

**Comment by Megabyte918** [comment]
@NameYT They are already smart.

**Comment by t11tanYT** [comment]
@Megabyte918  - i want laggy bots , i not want to freeze all bots, its not reallistic 
delay for minions(new setting) MinionsDelay = (time in milliseconds) This setting add delay for follow mouse ( like bots with proxy)
- No point in adding delay, as you can just disconnect the bots or kill them.
- im want to bots go to you mouse  with delay (example) in config  MinionsDelay = 30 
bots go to you mouse with 30 milliseconds delay (mouse coordinates 0x 0y, 30 milliseconds later 100x 100y and bots go to 0x 0y) and  I will add new command -  MinionsDelayMin = (time in milliseconds to min delay)  MinionsDelayMax = (time in milliseconds to max delay) conclusion: mega reallistic bots like old free bots

**Comment by AlexandriteErikParacelsus** [comment]
Lol wtf, why would you add more lines of code to have laggy bots

**Comment by Fantasy-Agario** [comment]
@AlexandriteErikParacelsus Your profile pic shows my reaction...

**Comment by firelightning13** [comment]
@Fantasy-Agario That's what I do everyday
