### ISSUE TITLE
Improved collectPellet minion

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1340]
As here https://www.youtube.com/watch?v=K1k_f0Aowc4&t there are server files in description
1)So bots are not immediately included in you when you don't see mass, if you do not see mass, then they stop
2)To bots was to "not care/shit" did not pay attention, but just collected mass

**Comment by ZfsrGhS953** [comment]
@DeadLord1337 This has been asked about many times already. @Megabyte918 made minions update every tick instead of every 10 ticks, because according to him it increases performance, even though I'm pretty sure it doesn't. Duplicate.

**Comment by DeadLord1337** [comment]
I haven't found a duplicate question of my question...
the video is very good collect pellet

**Comment by DeadLord1337** [comment]
Is productivity important to you, not the quality of the server? Here I have on the contrary old versions without lags at all, but since 1.6.0 there have been lags (And this is not from the PC ...)
