### ISSUE TITLE
killall help

### ISSUE THREAD

**Issue by vamosperu** [Megabyte918/MultiOgar-Edited#1342]
Help with a new game mode. everything starts well but at the end I get the following error.
| [FATAL] TypeError: Can not read property '**killall**' of undefined
    at Timeout._onTimeout src / gamemodes / SelfFeed.js: 39: 29)
    at ontimeout (timers.js: 471: 11)
    at tryOnTimeout (timers.js: 306: 5)
    at Timer.listOnTimeout (timers.js: 266: 5)
Some help

var FFA = require('./FFA'); // Base gamemode
var Mode = require('./Mode');

function SelfFeed() {
    FFA.apply(this, Array.prototype.slice.call(arguments));
    
    this.ID = 7;
    this.name = "SelfFeed";
    this.specByLeaderboard = true;

    this.restartInterval = 120000; // 2 min
}

module.exports = SelfFeed;
SelfFeed.prototype = new FFA();

// Gamemode Specific Functions

SelfFeed.prototype.onServerInit = function (gameServer) {

    gameServer.config.serverMaxConnections = 30;
    gameServer.config.borderWidth = 35000;
    gameServer.config.borderHeight = 35000;
    gameServer.config.foodMinAmount = 100;
    gameServer.config.foodMaxAmount = 100;
    gameServer.config.virusMinAmount = 0;
    gameServer.config.virusMaxAmount = 0;
    gameServer.config.ejectSize = 85;
    gameServer.config.ejectSizeLoss = 50;
    gameServer.config.ejectCooldown = 0;

    gameServer.config.playerMaxSize = 1500000000;
    gameServer.config.playerStartSize = 300
    gameServer.config.playerMaxCells = 24
    gameServer.config.playerRecombineTime = 0

    
    setInterval(function () {
        gameServer.commands.killall(gameServer, null);      
    }, this.restartInterval);
};

**Comment by AlexHGaming** [comment]
No custom code allowed.
@

**Comment by MiraMiPalo** [comment]
killall need `CommandList`

**Comment by AlexHGaming** [comment]
@vamosperu and i think .commands.killall is undefined

**Comment by AlexHGaming** [comment]
```javascript
var FFA = require('./FFA'); // Base gamemode
var Mode = require('./Mode');

function SelfFeed() {
FFA.apply(this, Array.prototype.slice.call(arguments));

this.ID = 7;
this.name = "SelfFeed";
this.specByLeaderboard = true;

this.restartInterval = 120000; // 2 min
}

module.exports = SelfFeed;
SelfFeed.prototype = new FFA();

// Gamemode Specific Functions

SelfFeed.prototype.onServerInit = function (gameServer) {

gameServer.config.serverMaxConnections = 30;
gameServer.config.borderWidth = 35000;
gameServer.config.borderHeight = 35000;
gameServer.config.foodMinAmount = 100;
gameServer.config.foodMaxAmount = 100;
gameServer.config.virusMinAmount = 0;
gameServer.config.virusMaxAmount = 0;
gameServer.config.ejectSize = 85;
gameServer.config.ejectSizeLoss = 50;
gameServer.config.ejectCooldown = 0;

gameServer.config.playerMaxSize = 1500000000;
gameServer.config.playerStartSize = 300
gameServer.config.playerMaxCells = 24
gameServer.config.playerRecombineTime = 0


setInterval(function () {
    gameServer.commands.killall(gameServer, null);      
}, this.restartInterval);
};
```

**Comment by AlexHGaming** [comment]
This is the code simplified.

**Comment by vamosperu** [comment]
@AlexHGaming @MiraMiPalo Any suggestions to enable it

**Comment by Agarian** [comment]
@vamosperu The following code should work fine:
```js
var FFA = require('./FFA'); // Base gamemode

function SelfFeed() {
    FFA.apply(this, Array.prototype.slice.call(arguments));
    this.ID = 7;
    this.name = "SelfFeed";
    this.specByLeaderboard = true;
    this.restartInterval = 12e4; // 2 min
}

module.exports = SelfFeed;
SelfFeed.prototype = new FFA();

// Gamemode Specific Functions

SelfFeed.prototype.onServerInit = function(gameServer) {
    gameServer.config.serverMaxConnections = 30;
    gameServer.config.borderWidth = 35000;
    gameServer.config.borderHeight = 35000;
    gameServer.config.foodMinAmount = 100;
    gameServer.config.foodMaxAmount = 100;
    gameServer.config.virusMinAmount = 0;
    gameServer.config.virusMaxAmount = 0;
    gameServer.config.ejectSize = 85;
    gameServer.config.ejectSizeLoss = 50;
    gameServer.config.ejectCooldown = 0;
    gameServer.config.playerMaxSize = 15e8;
    gameServer.config.playerStartSize = 300;
    gameServer.config.playerMaxCells = 24;
    gameServer.config.playerRecombineTime = 0;
    setInterval(function() {
        var count = 0;
        for (var i = 0; i < gameServer.clients.length; i++) {
            var playerTracker = gameServer.clients[i].playerTracker;
            while (playerTracker.cells.length > 0) {
                gameServer.removeNode(playerTracker.cells[0]);
                count++;
            }
        }
    }, this.restartInterval);
};
```

**Comment by vamosperu** [comment]
thanks to all.  @Agarian  
thanks for your help it was perfect everything works fine

**Comment by Shair17** [comment]
lol Perú

**Comment by AlexHGaming** [comment]
Close issue?

**Comment by vamosperu** [comment]
@Agarian Sorry to bother you. You can show the time in the leaderboard

**Comment by Agarian** [comment]
I'll see what I can do when I have the time, until then, I can't do much. I'll also hope that Fan7asy doesn't close this issue lmao

**Comment by vamosperu** [comment]
ok, take the time until you can, thanks

**Comment by Agarian** [comment]
Well the winds here knocked my internet out for a good 2 hours, and to be honest, I'm somewhat clueless on where to start here...

**Comment by Fan7asy** [comment]
![278352899300655105](https://user-images.githubusercontent.com/21162678/33795626-fc6f898a-dcdc-11e7-9fab-93a167f6d312.png)
