### ISSUE TITLE
 Experimental Mode Configuration

### ISSUE THREAD

**Issue by Gasvash** [Megabyte918/MultiOgar-Edited#1344]
it's a query,
Can you set the experimental mode of the client agar.io to the style of gota.io?,
 in this way:
 1-the mother cell that generates food.
 2- when I press "W", the mother cell generates more food.
3-and the food on the map, have the same size, but with more mass
Thank you.

**Comment by AlexHGaming** [comment]
Problem with this issue is that we are trying to make it look like vanilla agar.
