### ISSUE TITLE
Client Binding, bug

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#1345]
I use client binding on my servers. I noticed it's not working on this version of 1.6.1 but it works on the previous version of 1.6.1
If enabled I can't connect, but once I rem the line with # I can connect. 
I have this: 
clientBind = "http://www.gkclan.me - http://gkclan.servegame.com -  http://agar.io"

**Comment by cowpits** [comment]
I noticed serverRestart not working either on this update 1.6.1 version. I'm going to revert back to the previous 1.6.1. I'll try to fix what I can for these two bugs. Anyone else seeing these?

**Comment by Unai144** [comment]
It happens the same to me too with the clientBind

**Comment by SuperOP535** [comment]
It happens to me too :(

**Comment by cowpits** [comment]
it is kind of weird but i'm able to get it to work if the link does not have a / at the end of it. 
for example: http://mywebsite.com  
if I have a / in the end it won't bind. so don't do this http://mywebsite.com/ 
give it a try.

**Comment by cowpits** [comment]
and only one site can be bound, on the previous version I had more than 3.
