### ISSUE TITLE
Can't join to server

### ISSUE THREAD

**Issue by JanSzumotalski** [Megabyte918/MultiOgar-Edited#1346]
Hi, there!

I cant join to my server with agar.io/?ip=127.0.0.1:443.
Just client shows 

> connecting to arena

How to fix it?
Im using the 1.6.1 server version.

**Comment by JanSzumotalski** [comment]
Ok fixed

**Comment by emir-memmi** [comment]
how did you solve that ? @JanSzumotalski

**Comment by JanSzumotalski** [comment]
Yes

**Comment by JanSzumotalski** [comment]
Just loged out of google @emir-memmi

**Comment by Agarian** [comment]
k

**Comment by emir-memmi** [comment]
thanks that worked @JanSzumotalski
