### ISSUE TITLE
 query

### ISSUE THREAD

**Issue by Gasvash** [Megabyte918/MultiOgar-Edited#1347]
Hello, I know this is duplicated thousands of times with respect to the bots, but I would like to know if you can configure the bots separately from the players, this way
 1-Botstartsize: Mass that generates the bot, different from the player's
2-botmaxcells: Maximas cells that can have a bot, which would be recommended 2 cells
, sorry for this question, but you could help me, thanks

**Comment by Agarian** [comment]
I've actually added this in my server, ironically. You need to add the following to [line 888 in GameServer.js](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L888):
```js
else if (player.isBot) size = this.config.botStartSize;
```
And also add this to [this.config, at line 48](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L48):
```js
botStartSize: 31.62,
```

And finally, add the following into `config.ini` (it doesn't matter where): `botStartSize = 31.62`
And that's it! Now set `botStartSize` to whatever you want.

**Comment by Pollogy** [comment]
Is There a way to get a separate cell colors for de bots

**Comment by Agarian** [comment]
That I am unsure of.

**Comment by CodeFlush** [comment]
ANy luck? @Agarian

**Comment by Agarian** [comment]
Well, no.

**Comment by Fan7asy** [comment]
My bad
