### ISSUE TITLE
Authorization / Identification  #3

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#135]
Where server is behind a load balancer, it must identify the user each time this user connects.
That's why to use a token packet (https://github.com/forairan/agar.io-protocol/blob/master/protocol.md -> **Packet 80**).

1. Balanser(or ClientServer) will send a random Token to the client. 
2. Balanser send the same Token to the server.
3. For each connection, the client sends the Token to the server.
4. The server compares the token and selects a set of user properties for this Token (or get them from ClientServer)

Plus Some work at client software - cookies, an so on. 

This is a way to store mass and all things which can be sold to users, as Agar.io does. 

Need help with this. Need some hook on MultiOgar, the data storage for this task have too many solutions and may to be or not to be a part of the server . This hook should get Token and allow get/set mass and maybe some other thinds not from client, but from some external software or maybe plugin.

**Comment by Megabyte918** [comment]
What?

**Comment by Gimmo** [comment]
What is wrong? It's just a question. Can you point me where (var or property) server store recieved Token?

**Comment by Fantasy-Agario** [comment]
We cannot do this for legal reasons as it falls under Sec. 103(f) of the DMCA (17 U.S.C. § 1201 (f)
laws 

In other words it accounts as Illegal Reverse Engineering

**Comment by Fantasy-Agario** [comment]
We cannot do this as it accounts for illegal Reverse Engineering
