### ISSUE TITLE
ViewBox minion

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1352]
### How to make minion collected mass over the WHOLE/ALL map, and not in the area I see?

**Comment by AlexHGaming** [comment]
No custom code allowed
@Fan7asy

**Comment by DeadLord1337** [comment]
Please... help

**Comment by AlexHGaming** [comment]
This is an issues section my man, any suggestions post it in the discord :P

**Comment by Agarian** [comment]
You do realize that minions do that already, right @DeadLord1337?

**Comment by DeadLord1337** [comment]
@Agarian They do not do this, they do not collect mass all over the map, but only in my field of vision...

**Comment by Agarian** [comment]
If you're talking about a large amount of minions, then yes, I believe that's to same memory.
