### ISSUE TITLE
Virus-command

### ISSUE THREAD

**Issue by suprix** [Megabyte918/MultiOgar-Edited#1353]
How to make so if virus is eaten, it sends command to server?

Example: if virus is eaten, function send command to the server to change player's name. "name 1 example"

**Comment by Agarian** [comment]
You would likely want to add this to the `Virus.prototype.onEaten` function.

**Comment by suprix** [comment]
Yes, I know but I don't know how to do that :roll_eyes:

**Comment by Agarian** [comment]
Well depends, what command do you want to call when a virus is eaten? I can't really help unless you tell me that at the very least.

**Comment by suprix** [comment]
@Agarian skype/discord?
