### ISSUE TITLE
How to change the time with which cell are pushed out?

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#1356]
1) Change the number 13 in the following line to whatever you please:
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L781
`var r = this.config.mobilePhysics ? 1 : 13;`
2) You need to change both 13's here to the same value you set for the previous line:
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L823
`if (cell.getAge() < 13 || check.getAge() < 13)`
3) So that it would be easier, as every time not to go and change in GameServer.js can be replaced by all 13, on `this.config.pushTime`

**`var r = this.config.mobilePhysics ? 1 : this.config.pushTime;`
`if (cell.getAge() < this.config.pushTime || check.getAge() < this.config.pushTime)`**

And in writing in config `pushTime: 13, `
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L47
 
THANKS [Agarian.](https://github.com/Agarian)

**Comment by ZfsrGhS953** [comment]
@DeadLord1337 This is the issue section, not the wiki...

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 are you confused as well as me

**Comment by AlexHGaming** [comment]
Meanwhile you have me sweating gota and getting fans asking me for my id and pass :(
https://imgur.com/a/03B30
