### ISSUE TITLE
problem in the skins of the new update of agar.io

### ISSUE THREAD

**Issue by Hydra4dude** [Megabyte918/MultiOgar-Edited#1358]
I wanted to ask if you have solved this skin problem yet?

**Comment by AlexHGaming** [comment]
@Fan7asy 👍

**Comment by Hydra4dude** [comment]
so I can put the new skins in the minions, without everyone getting the same skin?

**Comment by Hydra4dude** [comment]
so I can put the new skins in the minions, without everyone getting the same skin?

**Comment by Gasvash** [comment]
I think not yet:, (

**Comment by Agarian** [comment]
Nope.

**Comment by fayizan** [comment]
@Megabyte918  can you please fix

**Comment by Gasvash** [comment]
lol ,I hope you can

**Comment by fayizan** [comment]
fixxxxxxxxxxx plssssssssssss @Megabyte918

**Comment by AlexHGaming** [comment]
Wait, what's the point of this when we have #1327?
So this is a dupe.
@Megabyte918

**Comment by fayizan** [comment]
@ZfsrGhS953 you got any fix ?

**Comment by ZfsrGhS953** [comment]
@fayizan Yes, it's very simple: stop using the Megacyst (aka Miniclip)'s client.

**Comment by Agarian** [comment]
Do what he said lol

**Comment by AlexHGaming** [comment]
do what agarian said
