### ISSUE TITLE
 ask with VPS, help me

### ISSUE THREAD

**Issue by Gasvash** [Megabyte918/MultiOgar-Edited#1359]
help me, please I can not run the server on the VPS, please help me out the time on the VPS:, (
![example](https://user-images.githubusercontent.com/34172427/34082838-04fcccae-e334-11e7-885e-aeacc20abdc4.PNG)

**Comment by Luka967** [comment]
Update your node.js version or replace the mentioned `const` with `var`.

**Comment by Gasvash** [comment]
@Luka967 as? , help me please

**Comment by AlexHGaming** [comment]
Go to binarywriter.js
Go to line 10
Replace const with var

**Comment by AlexHGaming** [comment]
If it brings an error, revert it back to const and update your node version.

**Comment by Gasvash** [comment]
no, how to update node.js?
I got this
![toma 2](https://user-images.githubusercontent.com/34172427/34084191-6fe8d57e-e34a-11e7-9401-4f6fd1cf48ad.PNG)

**Comment by Gasvash** [comment]
or am I running the server badly?

**Comment by AlexHGaming** [comment]
@Gasvash do node -v in your terminal. What does it output?

**Comment by Gasvash** [comment]
@AlexHGaming  v0.10.25

**Comment by Agarian** [comment]
HOLY SHIT THAT'S OUTDATED BOI

**Comment by Agarian** [comment]
First of all, you'll need to clean the NPM cache. Do so by inputting the following:
`sudo npm cache clean -f`
Once that's done, install node helper with the following:
`sudo npm install -g n`
Once node helper is installed, input the following:
`sudo n stable`
That should do.

**Comment by SuperOP535** [comment]
0.10.25 o_o that's so old

**Comment by Gasvash** [comment]
Thank you all
 :D
