### ISSUE TITLE
[Quick Question] is it writing onto disk?

### ISSUE THREAD

**Issue by Niall7459** [Megabyte918/MultiOgar-Edited#1360]
Does the game server do ANY writing to disk whilst it is running, its all stored in ram right?

Thanks

**Comment by Niall7459** [comment]
I'm pretty sure it doesn't actually at all. apart from log files. but  my dad keeps saying "it is writing all the time" cos we were talking bout sd cards and their lifetime.

**Comment by AlexHGaming** [comment]
@luka967, tech support needed!

**Comment by SuperOP535** [comment]
It does write logs but you can make log file verbosity to 0 other than that idk

**Comment by SuperOP535** [comment]
whoops sorry i didnt read, deleting both comments.

**Comment by Luka967** [comment]
Logging and copying over the default server config does write I/O, If your SD card is new, don't worry about it, it'd wear out in more than 5 years; by that time this fandom might come to an end lol

**Comment by Fan7asy** [comment]
@Niall7459 Your dad is cool lol

**Comment by ZfsrGhS953** [comment]
@Niall7459 You can try to run it from a RAMDisk.

**Comment by Niall7459** [comment]
Il give it a go tonight
