### ISSUE TITLE
Nobody here understands...

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1362]
Yes I am the next Makan, but issues lately have been so irrelevant that I have to make this.
This is MultiOgar-Edited, we have issues to only show that what bugs are going on in the server. Then I've been lately seeing issues that aren't even issues, instead they ask for suggestions when this can be easily asked in the [discord server](https://discord.gg/FGsB4mJ), issues are a completely different thing. Yes I'm going to get hate off this, but it needs to be actually understood.

https://github.com/Megabyte918/MultiOgar-Edited/issues/1361 - can be asked in the discord server.
https://github.com/Megabyte918/MultiOgar-Edited/issues/1360 - can be asked in the discord server.
https://github.com/Megabyte918/MultiOgar-Edited/issues/1344 - how can nobody respond back to this? Yet again, discord server.
https://github.com/Megabyte918/MultiOgar-Edited/issues/1264 - lets talk about this one. This issue was made for posting some custom clients. Apparently so this is allowed to stay because it was before the new so called "rules" that @Fan7asy made, however;
1. Can be asked in the discord server.
2. Not even an issue
https://github.com/Megabyte918/MultiOgar-Edited/issues/1249 - a suggestion, can be asked in the discord server.
https://github.com/Megabyte918/MultiOgar-Edited/issues/1189 - can be asked in the discord server.

**I just want to say, I know that not anyone is aware of the discord server we have, I completely understand that people don't have discord or not know what it means, I am trying my best to not put them down for this, I'm just saying that it isn't a valid issue and I have spreaded the discord server multiple times, from now on anyone asking for the discord server, it is this link: https://discord.gg/FGsB4mJ
Any questions / queries, ask it in the text channel, we would like to help you, but this repo is for your own server and reporting issues, suggestions can be in the discord.
Hate me as much as you can for being extremely salty, but I just had to.
Thank you for making me say this comment.**

**Comment by DeadLord1337** [comment]
I'm tired of reading... :O

**Comment by AlexHGaming** [comment]
bahahah

**Comment by Gasvash** [comment]
It is true

**Comment by Fan7asy** [comment]
>complains about issues being off-topic

>cREATES aN oFF tOPIC iSSUE

>Intelegence 100

**Comment by Fan7asy** [comment]
Sorree, I have to close this.

**Comment by AlexHGaming** [comment]
@Fan7asy lmao im sowee

**Comment by Niall7459** [comment]
Oh sorry i didnt know there was discord lol

**Comment by ZfsrGhS953** [comment]
@AlexHGaming That's your middle name? "Sowee"

**Comment by ZfsrGhS953** [comment]
@AlexHGaming Spreaded the discord server multiple times? But have you tried to put it in the readme file?

**Comment by AlexHGaming** [comment]
did i
