### ISSUE TITLE
Im quitting.

### ISSUE THREAD

**Issue by Fan7asy** [Megabyte918/MultiOgar-Edited#1365]
Here's an explanation why. 

![screenshot from 2017-12-19 19-36-44](https://user-images.githubusercontent.com/21162678/34175953-20095846-e4f6-11e7-9d6b-8b41ef99498c.png)

**Comment by AlexHGaming** [comment]
Ok.

**Comment by Megabyte918** [comment]
I understand.

I know that maintaining a project like this may seem like a waste of time, unfulfilling, or like people just don't appreciate the work you do, but I just want you to know we all appreciate the stuff you've done to maintain the repository. You were there when no one else could do it. I wish I had been more active on this repo so you wouldn't have had to deal with everything on your own :/

I probably can't change your mind, but I just want to thank you for everything you have done. 
I'll miss you buddy :(

**Comment by Fan7asy** [comment]
I hope this repository will remain maintained without me. I may just come back once and again and do some minor things, but I am not coming back to agar. Thank you for the opportunity you gave me and sorry that I just threw it away, but i hope you understand why I decided to leave.

I'll miss you too :(

**Comment by CodeFlush** [comment]
@Fan7asy  iCriEverytime

**Comment by SuperOP535** [comment]
i cri evertiem

**Comment by Agarian** [comment]
*Github needs to add the `:cry:` emoji as a reaction*

**Comment by Niall7459** [comment]
Aww this is sad actually

**Comment by Niall7459** [comment]
Wait @SuperOP535 you make pocket mine no plugins nice I used to do that sort of stuff but for the java version called Nukkit

**Comment by Niall7459** [comment]
Mp not no lol
