### ISSUE TITLE
Issue when going in a virus.

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#1368]
When you go into a virus, it causes to have tiny cells.

![pabpax--t_ayhvtqqyxlxw](https://user-images.githubusercontent.com/23425837/34230668-ba479c6c-e5d0-11e7-955a-6e98b151b2d6.png)

**Comment by freaky767** [comment]
I did not edit anything in Virus.js, although I did have to check if I was running the original code, which I was.

**Comment by AlexHGaming** [comment]
@freaky767 Can you provide your MultiOgar-Edited version?

**Comment by Megabyte918** [comment]
@freaky767 I tested this on a newly downloaded version and I could not reproduce it. Could you provide us with more detail as to how this happened so we could find the problem? (version number, configs, how much mass you had, etc)

**Comment by AlexHGaming** [comment]
![image](https://user-images.githubusercontent.com/23644244/34260350-8cc05ddc-e65d-11e7-8a44-e165469bd6ca.png)
@Megabyte918 Reproduced.

**Comment by AlexHGaming** [comment]
@Luka967's commit is doing this, maybe luka can fix?

**Comment by Agarian** [comment]
This wasn't happening before Fan7asy added his physics, then reverted them, so it's likely because of that.

**Comment by Luka967** [comment]
I've just fresh installed MO-E and couldn't get it.
@AlexHGaming Could you share your settings file?

**Comment by AlexHGaming** [comment]
@Luka967 Virus settings?

**Comment by fayizan** [comment]
@Luka967  @AlexHGaming yes please tell me how do I set virus setting same like agario

**Comment by freaky767** [comment]
im probably running an old version. sorry for making this...

**Comment by AlexHGaming** [comment]
I mean I have this issue aswell...
