### ISSUE TITLE
Minions on my server.

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#137]
Some dude made minions on my server, the scramble level is all the way up.
Please secure it more!

**Comment by Megabyte918** [comment]
@CalvinDKL See if it still happens with these settings:
serverIpLimit = 2
serverMinionIgnoreTime = 5
serverMinionThreshold = 5
serverMinionInterval = 500
serverScrambleLevel = 3
playerBotGrow = 0

**Comment by CalvinDKL** [comment]
ok, but isnt scramble level 4 better?

**Comment by MastaCoder** [comment]
Scramble won't just help @CalvinDKL

**Comment by CalvinDKL** [comment]
ohh, alright. let me try.

**Comment by CalvinDKL** [comment]
Doesnt just playerbotgrow do it for ppl that is using bots via the console?

**Comment by MastaCoder** [comment]
@CalvinDKL Try this as well. Edit your main_out.js and the server, add a packet with some sort of formula or something in it so that they can't find it, then obfuscate the code. As well as use some PHP to change the canvas ID everytime the page loads.

This isn't a 100% sure fire method, but it stalls the heck out of them.

**Comment by MastaCoder** [comment]
@CalvinDKL No, it stops even players. :)

**Comment by CalvinDKL** [comment]
Cool, so just a random packet??

**Comment by MastaCoder** [comment]
Yeah. Try to add some stuff behind your code so that they can't join with their normal client. Maybe change some packets, update some things. However, if you do this you'll have to port if everytime MultiOgar gets updated.

**Comment by CalvinDKL** [comment]
ye, thats the downside.

**Comment by MastaCoder** [comment]
Also it's not sure fire. It is very easy to unobfuscate the code, this is the only bad part of .io games. The JS code is available for anyone to view.

**Comment by CalvinDKL** [comment]
I have an older version of multiogar edited, so i dont have the playerbotgrow thing. ill try without it, and if it still doesnt work ill update all my servers :)

**Comment by CalvinDKL** [comment]
MastaCoder, remember i made a issue with the spectate bug?

**Comment by MastaCoder** [comment]
For Cigar?

**Comment by CalvinDKL** [comment]
Yes, i know i need to post it on there but wut eva lol.
Uhmm, the same thing happens in the menu bit.

https://gyazo.com/dab6db289bac2ac8cd5b9216c18bad85

**Comment by CalvinDKL** [comment]
Just thought i would let you know :)

**Comment by CalvinDKL** [comment]
And same with the minimap. Players are begging but the minimap gets scrambled and dont work. So i removed it for now.

**Comment by MastaCoder** [comment]
Yeah I know about that. Still don't know why it's happening exactly. All I know is that it might be because of the scramble updating constantly and the client catching up, but ending up in the same area.

**Comment by CalvinDKL** [comment]
Ye, can i do a pull request thing? I can add a minimap to cigar if u want to.

**Comment by MastaCoder** [comment]
I don't think we need a minimap for Cigar, they break once you scramble anyways 👍 

@Megabyte918 I'm working on an update right now, prepare for the PR quite soon :)

**Comment by CalvinDKL** [comment]
Masta, what update? tell me, NOWOWW! xD

**Comment by CalvinDKL** [comment]
THe bots are completely patched, but so i the borders i added. they are gone.

**Comment by CalvinDKL** [comment]
The scramble level 3 destroys all my good features............................
isnt there a bit of code u can add so the server sees to not patch the map or borders??

**Comment by MastaCoder** [comment]
Oh it wasn't a big update, just some cleaning up @CalvinDKL 😄 

Thats the whole point of scramble, to stop bots from knowing where the borders are and where they are on the map. That's why I said I can't add a minimap or border to the client 👍

**Comment by CalvinDKL** [comment]
ok................ i see.
FUUUU, that sucks a lot. I mean other private servers are too big to care about it xD

**Comment by Megabyte918** [comment]
How did the other settings go @CalvinDKL ?

**Comment by CalvinDKL** [comment]
WOrked, but fucked over skins xD
BUT I PATCHED BOTS!!!
for real.
its a script that takes proxies from 600 different free websites.
and bans em.
And also did a thing where i use
ws.close

**Comment by MastaCoder** [comment]
What if they use paid proxies..?

**Comment by CalvinDKL** [comment]
Paid proxies, then the bots still wont work. They cant connect.
But if they find a way around it with paid proxies then like 1 in 100 uses
em.

**Comment by Gimmo** [comment]
Easy way is to detect header "X-Forwarded-For" and block connection. No proxies- no problems. :)

**Comment by MastaCoder** [comment]
@Gimmo Headers can be changed REALLY easily. 
@CalvinDKL You're method won't work. If they can find proxies that you don't know about than you have a problem.

Just banning IP's won't work. You'll need to actively be banning all their IP's for it to work. Really the only way to ban them is if we can find some sort of method to block bot connections. This is one of the main drawbacks of open source projects. Since everyone can see the code, reverse engineering is the easiest thing to do.
