### ISSUE TITLE
Teleport hack

### ISSUE THREAD

**Issue by TehRealShot** [Megabyte918/MultiOgar-Edited#1370]
There is a hack someone is using on my server and it's allowing them to teleport. I have no idea of how to fix. Script of hack: https://hastebin.com/ilemujumuh.js

**Comment by Luka967** [comment]
The script sets one of the player's mouse coordinates to Infinity - this reproduces it:
```js
window.addEventListener("keydown", function(e) {
    switch (e.keyCode) {
        case 37:
            $("canvas").trigger($.Event("mousemove", {
                clientX: -Infinity,
                clientY: 0
            }));
            break;
        case 38:
            $("canvas").trigger($.Event("mousemove", {
                clientX: 0,
                clientY: -Infinity
            }));
            break;
        case 39:
            $("canvas").trigger($.Event("mousemove", {
                clientX: Infinity,
                clientY: 0
            }));
            break;
        case 40:
            $("canvas").trigger($.Event("mousemove", {
                clientX: 0,
                clientY: Infinity
            }));
            break;
    }
});
```
And because your server is flawed, doing this teleports all nearby cells along with the executor for some reason. I've tested it on a fresh install of MultiOgar-Edited locally and it doesn't work.

**Comment by TehRealShot** [comment]
How can I stop it?

**Comment by Luka967** [comment]
>your server is flawed

We don't spoonfeed people.

**Comment by AlexHGaming** [comment]
@Luka967 It's an issue.

**Comment by ZfsrGhS953** [comment]
@AlexHGaming But he said that it's already fixed.

**Comment by Luka967** [comment]
@AlexHGaming 

>I've tested it on a fresh install of MultiOgar-Edited locally and it doesn't work.

It's not *our* issue.

**Comment by AlexHGaming** [comment]
Ah, my bad.

**Comment by TehRealShot** [comment]
Thanks for the info. I patched in my main_out.js
`mainCanvas.onmousemove = function(event) {
	if (event.clientX == Infinity || event.clientX == -Infinity || event.clientY == Infinity || event.clientY == -Infinity) {
		return alert('STOP HACKING!');
	}
	rawMouseX = event.clientX;
	rawMouseY = event.clientY;
	mouseCoordinateChange()
};`

**Comment by ZfsrGhS953** [comment]
@TehRealShot "main_out.js"
Facepalm...

**Comment by TehRealShot** [comment]
i also patched it in the gameserver.js
