### ISSUE TITLE
if score....

### ISSUE THREAD

**Issue by suprix** [Megabyte918/MultiOgar-Edited#1374]
How can I make so it gives me some message back if player reach specific score? (NOT MASS)

example 

![image](https://user-images.githubusercontent.com/24485754/34396220-4a6140a4-eb68-11e7-9d8e-69c7183c824b.png)
And I want to put it in GameServer.js only

**Comment by suprix** [comment]
ewh idk why it doesn't convert to prettier code lol
![image](https://user-images.githubusercontent.com/24485754/34396216-40eab5a0-eb68-11e7-9dbc-6aa5c73016cd.png)

**Comment by Agarian** [comment]
If not mass, than what?

**Comment by suprix** [comment]
@Agarian What do you mean?

**Comment by AlexHGaming** [comment]
Firstly, ask it in the [Discord Server](https://discord.gg/FGsB4m).
Secondly, try adding the following code after [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L129) in PlayerTracker.js:
```javascript
if (this._score == "replacewithyourscorenumber") console.log("Player has reached number score!")
```

**Comment by suprix** [comment]
Firstly, Im banned lol.
Secondly, okay ill try

**Comment by suprix** [comment]
any possible way to put that code in GameServer.js? @AlexHGaming

**Comment by suprix** [comment]
and it doesn't work tho

**Comment by AlexHGaming** [comment]
@suprix You're banned? Let me check the logs.

**Comment by AlexHGaming** [comment]
Are you chicko?

**Comment by suprix** [comment]
I am Suprix XD

**Comment by suprix** [comment]
I need to get voice channel invite to access the server

**Comment by AlexHGaming** [comment]
You aren't banned.
![image](https://user-images.githubusercontent.com/23644244/34415068-8fc268cc-ebe4-11e7-94db-f6f42e2b9183.png)

**Comment by suprix** [comment]
Can you give me some voice channel invite?

**Comment by suprix** [comment]
Sometimes discord have that glitch where if you were banned you will need voice channel invite

**Comment by AlexHGaming** [comment]
OK ill send invite

**Comment by AlexHGaming** [comment]
https://discord.gg/Gqw3nGy

**Comment by Megabyte918** [comment]
@suprix 
1) The code you are describing will not work unless the players score is EXACTLY at 800.
2) @AlexHGaming 's code should do the trick, it will not make a difference whether or not it is in GameServer.js or not.

**Comment by AlexHGaming** [comment]
@suprix remember, you can change the operator.
```javascript
if (this._score == "replacewithyourscorenumber")
```
could also be
```javascript
if (this._score >= "replacewithyourscorenumber")
```
