### ISSUE TITLE
Parfect Papsplots.

### ISSUE THREAD

**Issue by Fan7asy** [Megabyte918/MultiOgar-Edited#1375]
I creat gam adn he is verry verry gud, mai quuestin is wai is no popsplat parfect 100%.
I c Boobleballz maek profesionel pepsplots and i think wai i cen not do le sam on mai survur.
Wan mur quuestein, whoat is le recoomended amount ofe wham for this surrrveerr?

**Comment by AlexHGaming** [comment]
2 maik you're survur 100percnt popposplot u nud 2 go 2 you're systcum32 fiel aind deleet eet. youre pc woll go boom qwicker een performnce and porfoct poopsplots wil werk.

**Comment by ZfsrGhS953** [comment]
@Fan7asy @AlexHGaming Didn't know you two can speak Dutch...

**Comment by ZfsrGhS953** [comment]
@MastaCoder @Megabyte918 Invalid & Off-topic.

**Comment by chewythepig** [comment]
What an intelligent conversation.

**Comment by AlexHGaming** [comment]
Mega is offline rn

**Comment by AlexHGaming** [comment]
Makan doesn't check the goddamn thing anymore

**Comment by chewythepig** [comment]
@AlexHGaming Makan is too busy buying Luka Discord Nitro

**Comment by ZfsrGhS953** [comment]
@chewythepig Don't worry, I'll let him know about OpenDiscord when I finish it... So that he can enjoy GIF... I mean VP9 emoji and avatars.

**Comment by AlexHGaming** [comment]
Luka has it now

**Comment by AlexHGaming** [comment]
He had gotten nitro yesterday

**Comment by ZfsrGhS953** [comment]
@AlexHGaming Discord has VP9 emoji?

**Comment by AlexHGaming** [comment]
What?

**Comment by AlexHGaming** [comment]
Ok, let's take this over to the discord, this is useless commenting on a repo XD

**Comment by chewythepig** [comment]
@ZfsrGhS953 Is OpenDiscord gonna he your implementation of Discord? If so, I started on one too :P

**Comment by AlexHGaming** [comment]
AHEM, discord server

**Comment by ZfsrGhS953** [comment]
@chewythepig Yes. Don't be surprised if you finish yours earlier, because we'll see which one is **faster** :smile:

**Comment by chewythepig** [comment]
@ZfsrGhS953 Started on it 2 months ago, haven’t worked on it since. Made the mistake of starting on the UI which was and still is utter hell. I’ll be rebooting the project soon after I get some key features released on Popsplit.us. I’ll more than likely write the entire backend **efficiently** before I even start on a client or UI/UX.

**Comment by Fan7asy** [comment]
@AlexHGaming I delet soostem tharty too, pc went kaboom kaboom and mai hom burned-ded downe. I n0w haz 20, 000 unated stats dolar damag to pey oof.

**Comment by Fan7asy** [comment]
Thank you evary boady foar le hlp in this isooe

**Comment by AlexHGaming** [comment]
noot ai prooblem.

**Comment by Agarian** [comment]
wkat da hekz is goni onn heeer?

**Comment by AlexHGaming** [comment]
nuthing

**Comment by Agarian** [comment]
Ow okey th3n.

**Comment by chewythepig** [comment]
Ei giv op on u kidz

**Comment by Fan7asy** [comment]
I agreai

**Comment by Fan7asy** [comment]
404: Brein Cells N0t F0und

**Comment by Agarian** [comment]
ow mah hed hwurts, my bwain celz is dyin

**Comment by AlexHGaming** [comment]
saim

**Comment by MastaCoder** [comment]
***6 days ago***

**Comment by Fan7asy** [comment]
**7 days ago**

**Comment by chewythepig** [comment]
**8 Days Ago**

**Comment by Agarian** [comment]
k

**Comment by AlexHGaming** [comment]
@Agarian Why do you say "k" everywhere lmao

**Comment by AlexHGaming** [comment]
_**9 days ago**_

**Comment by Agarian** [comment]
Because k

**Comment by freaky767** [comment]
k
also twank u mai pc want kaboom boom aftew this help

**Comment by AlexHGaming** [comment]
_**10 days ago**_

**Comment by Luka967** [comment]
***Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa***

**Comment by Agarian** [comment]
~~***11 days ago***~~

**Comment by RasyiidWho** [comment]
send me vegena

**Comment by Gigabyte918** [comment]
*15 days ago*

**Comment by AlexHGaming** [comment]
ok lets maybe stop lmao

**Comment by Fan7asy** [comment]
**16 days ago**

**Comment by Fan7asy** [comment]
**17 days ago**

**Comment by Fan7asy** [comment]
**18 days ago**

**Comment by Fan7asy** [comment]
**19 days ago**

**Comment by Agarian** [comment]
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k

**Comment by MastaCoder** [comment]
hey you no do da spam

**Comment by Agarian** [comment]
k

**Comment by Fan7asy** [comment]
A quEsTIEN

**Comment by Fan7asy** [comment]
Do u kno da wae?

**Comment by Agarian** [comment]
k is da wae

**Comment by chewythepig** [comment]
why are we still doing this

**Comment by AlexHGaming** [comment]
i dont know

**Comment by Agarian** [comment]
This issue is officially:
# DANK.

**Comment by Luka967** [comment]
k
