### ISSUE TITLE
Ultrasplit in MO-E

### ISSUE THREAD

**Issue by Hydra4dude** [Megabyte918/MultiOgar-Edited#1376]
How do I put ultra split in MO-E, since the server does not recognize the minus sign in PlayerRecombineTime? Ex: PlayedRecombineTime: -999

**Comment by Agarian** [comment]
Are you trying to make merging never happen, or instantly happen?

**Comment by AlexHGaming** [comment]
Ok, firstly, discord server.
Secondly, put the recombine time to 0, and lower the split velocity
@Megabyte918 close

**Comment by AlexHGaming** [comment]
Also a dupe

**Comment by AlexHGaming** [comment]
weSmart

**Comment by Megabyte918** [comment]
Duplicate of #792 and #862

**Comment by Agarian** [comment]
k

**Comment by Valdex** [comment]
@Hydra4dude ULTRASPLIT WRITEN ON MULTIOGARBLOB BY F0RIS

**Comment by Valdex** [comment]
@Hydra4dude its rly copy of ultra from bubla and gaver

**Comment by Agarian** [comment]
k

**Comment by AlexHGaming** [comment]
k
