### ISSUE TITLE
Error when eat MotherCell

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#1377]
![capturex](https://user-images.githubusercontent.com/19422415/34614466-2d98bd32-f264-11e7-88a5-57bd28954e86.PNG)

**Comment by AlexHGaming** [comment]
Try removing the parantheses on line 78 in your virus.js file.

**Comment by Agarian** [comment]
I have found the fix, you need to add the following line to line 24 in MotherCell.js:
`MotherCell.prototype.explodeCell = Virus.prototype.explodeCell;`

**Comment by RasyiidWho** [comment]
Thanks @Agarian 🍡
