### ISSUE TITLE
Mother Cell can't produce a food even motherCellMaxMass

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#1380]
I use older version, the mother cell are producing a food, but not happen in new version

**Comment by RasyiidWho** [comment]
Old version (produce a food, didn't cause lag because it's eject about 5 in 10s)
![produce1](https://user-images.githubusercontent.com/19422415/34636490-df248264-f2d4-11e7-9321-eaf0b925c984.PNG)

New version
![produce 2](https://user-images.githubusercontent.com/19422415/34636493-ec563c34-f2d4-11e7-9bb2-189d5faac2c6.PNG)

I try remove line 34-36 in MotherCell.js, yea it's work, but produce too many foods, and when I change this.motherUpdateInterval in Experimental.js to 20, It's produce food more slower, but it's slow to produce a food too when mother eat my cell.

Sorry for my bad english.

**Comment by Agarian** [comment]
I've fixed your previous issue, however I *think* this issue is normal. Have you tried feeding the mother cell?

**Comment by RasyiidWho** [comment]
I mean the mother cell produce a food, just like vanilla agar. Old version have this..

**Comment by Agarian** [comment]
Oh so it doesn't produce food even when its fed?

**Comment by freaky767** [comment]
i think he means that the mothercell doesnt produce food while nobody has fed it anything, which isn't normal compared to agar.io

**Comment by Agarian** [comment]
Well, that's what I initially thought, but he seemed to deny it.

**Comment by RasyiidWho** [comment]
@freaky was true

**Comment by Agarian** [comment]
Well unfortunately, this was a feature that I wanted, but couldn't re-create myself =/

**Comment by RasyiidWho** [comment]
old version have this feature

**Comment by RasyiidWho** [comment]
![capture](https://user-images.githubusercontent.com/19422415/34752688-69c6a6fe-f5e6-11e7-8d00-f3b70ca1939e.PNG)

**Comment by Agarian** [comment]
What version is "old version"?

**Comment by RasyiidWho** [comment]
same 1.6.1, but it's old one, I can give you if you want

**Comment by Agarian** [comment]
I take that back, I know what you mean now, but in that version, the food gets produced too fast (same speed as if the mothercell were fed).

**Comment by RasyiidWho** [comment]
I didn't found that issue.

**Comment by Megabyte918** [comment]
@RasyiidWho It should be fixed now. I've been observing vanilla experimental mode, and I made it so if the mothercell has not been fed (its size is less than or equal to the minimum size) it will spawn food at random intervals of 25-50 ticks. If it HAS been fed, it will spawn food in intervals of 2 ticks.
