### ISSUE TITLE
Missing playercommands

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1382]
I can not find the playercommands file nor command list. If I am not acting retarded like I always am, why is it removed?

**Comment by ZfsrGhS953** [comment]
@AlexHGaming 
[CommandList](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/CommandList.js)
[PlayerCommand](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/PlayerCommand.js)

**Comment by AlexHGaming** [comment]
Wait what lmao, i couldnt find it in the file finder
