### ISSUE TITLE
Anyone can make port this Virus.js? To make popsplit easier

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#1383]
This is older Virus.js, anyone can make a new version?
#807

**Comment by Agarian** [comment]
Dude, all you have to do is paste that code into `Virus.js`. And since the current physics are realistic enough, we're not going to port that code here. Just know that we're going for **vanilla** physics, not physics that allow for pop-splits to be easier.

**Comment by RasyiidWho** [comment]
Can you port that Virus.js? I use in current agar but doesn't work

**Comment by DeadLord1337** [comment]
Virus physics Very good!!! Lord approves)))

**Comment by AlexHGaming** [comment]
The virus physics may be easier to popsplit, but it will be unbalanced.
