### ISSUE TITLE
Run.Bat won't work it deletes every time i extract

### ISSUE THREAD

**Issue by Vizouee** [Megabyte918/MultiOgar-Edited#1386]
I try to extract the file to desktop but run.bat or install dependacies does not work it deletes
Plz help

**Comment by Vizouee** [comment]
Nevermind it did it again

**Comment by AlexHGaming** [comment]
@Vizouee can you paste the code inside of win-run.bat

**Comment by Agarian** [comment]
I have no clue as to how the file deletes itself. Do you even have NodeJS installed @Vizouee?

**Comment by AlexHGaming** [comment]
He probably means when there is an error, the command prompt closes.
@Vizouee please can you provide us your run.bat code?

**Comment by Agarian** [comment]
Again, that happens if you don't have NodeJS installed.

**Comment by AlexHGaming** [comment]
It would say figlet is not defined or someit like that.

**Comment by Fan7asy** [comment]
...No it wouldn't.
If NodeJS isn't installed on the device in question, the command prompt would throw an error.
>figlet isn't even in the question.

**Comment by Fan7asy** [comment]
@Vizouee Can you please open command prompt in the root folder of the project and type as follows:
```
npm install
```
Copy the output once the command has ran. It may be an error with npm itsself.
Also the file shouldn't delete, there's nothing in place that can make it actually do that...

**Comment by Fan7asy** [comment]
Just to be sure, you have extracted the entire `MultiOgar-Edited` folder, not just the batch files?

**Comment by Megabyte918** [comment]
@Vizouee Do you have any antivirus programs by any chance? If so, disable them before you extract the files. It might be whats deleting the file every time you extract it from the zip. If not, just run the commands manually through the command prompt.

**Comment by Vizouee** [comment]
I found out The I disabled my anti virus then it worked thanks megabyte
