### ISSUE TITLE
All the bots have the same skins

### ISSUE THREAD

**Issue by Vizouee** [Megabyte918/MultiOgar-Edited#1387]
I would join in and all the bots have the same skin

**Comment by Agarian** [comment]
This is a known issue with the agar.io client. Not sure what the cause is...

**Comment by Vizouee** [comment]
Oh can't you just make it random between the skins

**Comment by Vizouee** [comment]
Or is it just agar.io

**Comment by AlexHGaming** [comment]
@Vizouee Duplicate.

**Comment by Vizouee** [comment]
Duplicate what?

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/1358
