### ISSUE TITLE
What makes 'ws' different from 'uws'?

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1389]
It is very interesting what 'uws' is for and why it differs from 'ws'...

**Comment by AlexHGaming** [comment]
All I can tell you is that uws = ultra websocket and ws = websocket. I think it transfers more, not too sure.

**Comment by REDGuineaPig** [comment]
Apparently it's more efficient, lightweight and fast.

See here: https://github.com/uNetworking/uWebSockets

**Comment by Luka967** [comment]
[`uWebSockets`](https://github.com/uNetworking/uWebSockets) is a C++ library. It supports multi-threading and has a very small memory footprint. `uWS` is its port for node.js.
`ws` is, apart from the optional C++ addons, a pure node.js library, thus it doesn't support multi-threading and uses more memory.

**Comment by AlexHGaming** [comment]
ok luka will tell you everything lmao
