### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by FantasyIsBae** [Megabyte918/MultiOgar-Edited#139]
# Client 

I have made a basic client It can be found here : [Multi-Ogar Client](http://multiogar-edited.pe.hu/)
Don't be disappointed by the looks as I will be adding more features in the near future :)
(I'm already planning a new client :D)

# Forum

I was wandering if anyone wanted a forum ? :D

**Comment by Jhair2015** [comment]
Nice! :D

**Comment by Jhair2015** [comment]
Hide Grid - Dark Theme *bug*

i select "HideGrid" And automatically set on white background and not on darktheme

**Comment by NameYT** [comment]
@Fantasy-Agario Do you know the code? For BOT SMARTER only for me? i need the calculatuon :)

**Comment by Fantasy-Agario** [comment]
@NameYT Define pls :)

**Comment by NameYT** [comment]
@Fantasy-Agario Why i cant use pellet mode :(

**Comment by NameYT** [comment]
@Fantasy-Agario That make bots smarter!! Tricksplit Teaming Splitrunning like that farming virus

**Comment by Fantasy-Agario** [comment]
@Jhair2015 Thanks for pointing that out :) 

And the client isn't fully finnished yet so its a bit buggy

**Comment by NameYT** [comment]
@Fantasy-Agario Why i cant use pellet mode in Agar.io

**Comment by Fantasy-Agario** [comment]
What about the forums ? anyone want one :)

**Comment by Fantasy-Agario** [comment]
On my client or the Agar.io client ? @NameYT

**Comment by NameYT** [comment]
@Fantasy-Agario Agar.io and i want FORUMS!!!!!!!!!!

**Comment by NameYT** [comment]
![image](https://cloud.githubusercontent.com/assets/20871314/20862840/2bebbe96-b9f1-11e6-9479-bcb5fe3bdeb5.png)
This is my settings

**Comment by NameYT** [comment]
@Fantasy-Agario Help

**Comment by Fantasy-Agario** [comment]
hmm im not familiar with the new settings , I couldn't get this to work either, try downloading the earlier version [REVERT](https://github.com/Megabyte918/MultiOgar-Edited/tree/5cc112fd517734f665d9c66d34feb6a3710bebc4)

If it doesn't work then you might have to ask @Megabyte918 

And imma start work on the forums right away :P

**Comment by NameYT** [comment]
@Fantasy-Agario Yay :) do we have login system like that ?

**Comment by Jhair2015** [comment]
@NameYT 

`minionStartSize` = 32
`minionMaxStartSize` = 32
`disableERTP` = 0
`disableQ` = 0
`serverMinions` = 15
`defaultName` = "Jhair"
`collectPellets` = 1

**Comment by Fantasy-Agario** [comment]
@Jhair2015 Thanks <3

**Comment by Fantasy-Agario** [comment]
For the forums ? @NameYT

**Comment by NameYT** [comment]
@Fantasy-Agario Yes

**Comment by Jhair2015** [comment]
@Fantasy-Agario  

No problem and...

Whats is FORUMS??

**Comment by firelightning13** [comment]
@Fantasy-Agario Is forum necessary?

**Comment by Jhair2015** [comment]
@Fantasy-Agario  @NameYT 

What are forums? Sorry I'm not American, I'm from Latin America! :p

**Comment by NameYT** [comment]
@Fantasy-Agario @Jhair2015 IT DOESN"t WORK PELLET MODE DOESN"t WORK

**Comment by Fantasy-Agario** [comment]
They are like mini social networks 

[EXAMPLE](http://forum.ogarul.io/)

**Comment by firelightning13** [comment]
@Jhair2015 haha it works like this http://www.minecraftforum.net/

**Comment by NameYT** [comment]
I will make an issue that it dont work :()

**Comment by Fantasy-Agario** [comment]
And @firelightning13 

A forum is not necessary but it would separate the support issues from acctual issues with the code + it would be nice to have a community surrounding this project :P

**Comment by NameYT** [comment]
@Fantasy-Agario Why pellet mode doens't work

**Comment by Fantasy-Agario** [comment]
I'm not sure but ill try fixing it :D

**Comment by Jhair2015** [comment]
@NameYT  I do get pallet mode in the last update...

**Comment by Jhair2015** [comment]
@firelightning13  xD :v

**Comment by NameYT** [comment]
@Jhair2015 Well it doens't work now :(

**Comment by AlexandriteErikParacelsus** [comment]
seems like your client doesn't support "P"

**Comment by Fantasy-Agario** [comment]
the client isn't fully finnished yet so its a bit buggy

**Comment by AlexandriteErikParacelsus** [comment]
right

**Comment by Megabyte918** [comment]
I don't really think we need a forum yet

**Comment by Fantasy-Agario** [comment]
Yeh not yet , but just to take it into consideration :)

**Comment by MastaCoder** [comment]
This client looks familiar.. 😢

**Comment by MineMooreALT** [comment]
very

**Comment by AlexandriteErikParacelsus** [comment]
play.ogarul.tk??? TRIGGERED

**Comment by Fantasy-Agario** [comment]
Its open source so yh , plus this is just a basic client for the time being :D

**Comment by AlexandriteErikParacelsus** [comment]
![b n v khong co tieu d](https://cloud.githubusercontent.com/assets/17348976/20863066/d724cf74-b973-11e6-8a62-54191e49a042.png)

**Comment by Fantasy-Agario** [comment]
XD

**Comment by AlexandriteErikParacelsus** [comment]
lmao

**Comment by AlexByte918** [comment]
add the skin feature

**Comment by MastaCoder** [comment]
It's just the fact that Andrew made it is making me want to do what's in the image. 😄

**Comment by AlexandriteErikParacelsus** [comment]
@mastacoder XDDDD

**Comment by AlexByte918** [comment]
if you can configure the skins, like to minemoore.uk.tk?

**Comment by MineMooreALT** [comment]
I use a completely different thing and it only works for my client
