### ISSUE TITLE
Im bad at this so i need help

### ISSUE THREAD

**Issue by MikaelMart** [Megabyte918/MultiOgar-Edited#1391]
Okay so i have my stuff and yea but i use agarian Ogar client or the thing i heard about if its not the right thing to use what do i use and also if its that how to i connect to my own server? i tried 127.0.0.1:433 on the ip thing and Soloserver 433 but it doesn't work ik im bad at this but i just need help with this

**Comment by AlexHGaming** [comment]
@MikaelMart Make sure your port is the port you located in gameserver.ini.

You said 433, it is not default 433, it is 443. Try `127.0.0.1:443` and not `127.0.0.1:433`

**Comment by Agarian** [comment]
Ugh blame that on github, as it only supports `wss://`, meaning you'd have to download the client itself if you want to connect to localhost servers.

**Comment by MikaelMart** [comment]
Okay i don't know what Ogar client i have one thats like a .html file when i open it it opens like a Agarian website with no details or anything when i put the stuff in it and press Connect/Play it just refreshes and it unfills the Nickname and stuff so idk what client and also idk what you mean with wss if you mean like wss on the ws part on the gameserver.ini the console stops working ;/ (ik im a noob)

**Comment by Agarian** [comment]
When I say `wss`, I'm referencing a "Secure WebSocket". Localhosts don't support that, and the github.io link forces it (since it's `https`).

**Comment by MikaelMart** [comment]
oh ok

**Comment by Luka967** [comment]
Open up the console. Screenshot what's there.

**Comment by MikaelMart** [comment]
what console?

**Comment by ItzLevvie** [comment]
Press F12 in your browser when connecting to your server via a custom client.

**Comment by MikaelMart** [comment]
oohh ook
wait

**Comment by Agarian** [comment]
I didn't know it takes 2 hours to screenshot the console lol

**Comment by AlexHGaming** [comment]
lmaooo

**Comment by MastaCoder** [comment]
6 hours*

**Comment by AlexHGaming** [comment]
7 hours*

**Comment by MikaelMart** [comment]
i just dint want to do this rn

**Comment by MikaelMart** [comment]
![image](https://user-images.githubusercontent.com/26523808/35481956-7aee9ac8-0436-11e8-81a8-6f42fbfe1bd6.png)
thats it

**Comment by cowpits** [comment]
is your server running on your computer? 
what port are you using? if your computer no way you can be using 443, i'm positive another app is already bound to that port, so you need to change it 4444 for example. 
test your server using agar.io client, sign out of any agar.io account or use guest mode in chrome. connect using http://agar.io/?ip=127.0.0.1:4444 or whatever port number you set.

**Comment by AlexHGaming** [comment]
That looks so bad without bootstrap lmao

**Comment by Luka967** [comment]
@MikaelMart Your client isn't even functioning because it's not loading jQuery for some reason.

**Comment by Agarian** [comment]
It appears that the ONLY thing he downloaded is `index.html` -_-

**Comment by MikaelMart** [comment]
@Agarian i have the src and some linux stuff and more

**Comment by Agarian** [comment]
OK, what's the issue here? The fact that you can't get the server to run, or that my client isn't working for you? Just a note, you should use the Chrome browser for my client, as it works best.

**Comment by AlexHGaming** [comment]
k
k
k
k
k
k
k
k
k
k

**Comment by MastaCoder** [comment]
Seems to be having client issues, until you figure out how to get jQuery working I'm going to have to close this.

**Comment by Agarian** [comment]
@MastaCoder I have not been able to duplicate that issue with the client. Either he downloaded it incorrectly, modified something, or it's an issue with his PC.

**Comment by Agarian** [comment]
Actually, I was just able to duplicate that bug, but this only occurs if `index.css` is missing.

**Comment by cowpits** [comment]
Either way, 1st he used https://agarian.github.io which will not work for him. And 2nd if he downloaded the client it won't work either because he doesn't know how to host the client. Either way we're assuming he has done or doing what we think he's doing, which is trying to play on his private server using Agarian client. lol. 
I have already given him a solution to try to test his server using agar.io client and that's all he needs to do. Unless the issue here is him trying to use Agarian's client which is fine but he's going about it the wrong way.
