### ISSUE TITLE
How to send extra info to server

### ISSUE THREAD

**Issue by Niall7459** [Megabyte918/MultiOgar-Edited#1394]
How could I get the client to say send over some extra data (such as the UserID) and the server can then recieve it and use that to connect to the database.

I know how to do databasing but not sure how to send over the user Id with websockets..

Any help would be great....

Thanks!

@Megabyte918 
@AlexHGaming
or anyone...

**Comment by AlexHGaming** [comment]
Sorry my dude, I am not into clients, packets & that. Sorry dude :P

**Comment by Niall7459** [comment]
Ok

**Comment by SomeoneCares11** [comment]
same question here. 
please help us, the websocket encrypt data into binary or something, i don't know how to send and receive these binary data

**Comment by ZfsrGhS953** [comment]
@SomeoneCares11 Encryption (when using ```wss```) is done entirely by the browser, you don't need to worry about it.

**Comment by Niall7459** [comment]
@ZfsrGhS953 I still noticed that the websockets are still in a weird format without ssl. Like if you were inspecting websockets using socket.io you can easily seee what’s being sent using this “mqtt” it is not under standable il send a screen shot of my websockets being sent later

**Comment by SomeoneCares11** [comment]
@ZfsrGhS953 in cigar client when it send a chat command it using
```
            var msg = prepareData(2 + 2 * str.length);
            var offset = 0;
            msg.setUint8(offset++, 99);
            msg.setUint8(offset++, 0); // flags (0 for now)
            for (var i = 0; i < str.length; ++i) {
                msg.setUint16(offset, str.charCodeAt(i), true);
                offset += 2;
            }

            wsSend(msg);
```
and when send the nickname
```
            var msg = prepareData(1 + 2 * userNickName.length);
            msg.setUint8(0, 0);
            for (var i = 0; i < userNickName.length; ++i) msg.setUint16(1 + 2 * i, userNickName.charCodeAt(i), true);
            wsSend(msg)
```

i really don't understand the use case of `prepareData` and `setUint8` and `setUint16`, and what are the numbers in these functions means. because i see it has different numbers on every command

**Comment by Niall7459** [comment]
@SomeoneCares11 I know I can’t understand it like that we need someone to explain what everything means

That last bit almost looks like it’s sending each caharacter separately of the nickname or maybe together....

**Comment by ZfsrGhS953** [comment]
@SomeoneCares11 That's string data being converted to binary.

**Comment by AlexHGaming** [comment]
Oh yeah custom code

**Comment by SomeoneCares11** [comment]
@MastaCoder give us 5 minutes from your time and explain what they mean, and i'll make PRs

**Comment by Luka967** [comment]
We don't spoonfeed here. Learn about binary data types yourself.
