### ISSUE TITLE
**Reminder of Discord Server**

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1396]
Remember, we still have our discord server for giveaways + help with your custom code!

Discord link: https://discord.gg/4Nrewjc

**Closing this in 24 hours, unless Mr Makan comes in and closes it and calls it useless**

**Comment by AlexHGaming** [comment]
We are sick and tired of you asking for custom code on this github, so paste them in the discord server to not get your issue locked, and wait for someone to come and help you.

**Comment by MastaCoder** [comment]
AHEM. I'LL SAY IT.

**USELESS**.

**Comment by AlexHGaming** [comment]
NON OF THAT LANGUAGE

**Comment by Agarian** [comment]
Well it appears that @MastaCoder wants people to continue to ask these questions here. Makes me wonder why he's a collaborator...

**Comment by Agarian** [comment]
Well, hell! He complains about it, yet there's been less of those issues, has there not been? That WAS because of the Discord server. I say was because it's... been deleted?! I'm about ready to kill somebody...

**Comment by MastaCoder** [comment]
@Agarian Now before I continue to write anything, first please explain to me how that link was related to anything to do with an issue? I have said this over and over again, the ISSUES section on Github is for suggestions, feedback, and issues about a project. Not a place for people to post links about other Discord links or to ask questions about adding code. If they really wanted to do that they'd join some sort of official community that was setup for it. Also, if it was really an official community, you'd leave a link to it in the README file, not make an issue that'd probably get lost somewhere later on hoping people would see it.

Glad it wasn't the official one either, it was filled with Alex posting useless information in announcements and tagging everyone for it as well as constant drama between everyone in there.

**Comment by AlexHGaming** [comment]
> Alex posting useless information in announcements and tagging everyone for it

Well, it wasn't a massive server with like over 1000 people in it, if that was the case then hence wise there wouldn't be any useless announcements. 

> Funny thing I just noticed a Discord server does actually exist in the README, so if it was already there, what's the point on making a reminder for it? If the people are that incapable of reading the README which shows up front page to join, what has you thinking they'll join through reading the issues?

Good question, hardly anyone even bothers to scroll down the README, instead they come to the issues. My bad, yes I did make an issue about it, which is invalid, but it leads to more people maybe joining the server and not moaning their custom code here.

**Comment by AlexHGaming** [comment]
The Discord server is lower down on the list when you click the repo aswell
