### ISSUE TITLE
I give up on the Discord Server.

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1397]
Yes, I got rid of the discord server. I am sick and fucking tired of being server leader of people who think im too strict. I'm just not capable of handling a server on my own without any moderators to help me, since the server is unpopular. I just can't do as an admin / leader, it just causes chaos in the server and people are  fucking leaving over it. Getting teased, people taking shit to a new level and can't follow rules. I'm done.

**Comment by AlexHGaming** [comment]
Yes, I know Megabyte is the main man behind this, but the server was on its last legs. People leaving and saying it's useless and not necessary anymore. It's very true, not even needed anymore. It had to be done.

**Comment by jimboy3100** [comment]
Send me your discord invitation. I can help you. I am author of Legend Mod

**Comment by Agarian** [comment]
SON OF A BITCH

**Comment by AlexHGaming** [comment]
lawl

**Comment by Niall7459** [comment]
Oh I wondered where it had gone

**Comment by Luka967** [comment]
I've made a replacement
https://discord.gg/27v68Sb

**Comment by AlexHGaming** [comment]
oh hello
