### ISSUE TITLE
ERROR CELL

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1399]
Error, please fix
![image](https://user-images.githubusercontent.com/19995663/35484132-c9e678d2-045c-11e8-96e5-0cad6f0da01d.png)

**Comment by AlexHGaming** [comment]
Please can you provide me your node.js version and MultiOgar-Edited Version?

**Comment by ZfsrGhS953** [comment]
@MastaCoder @Megabyte918 Modified version (I don't recall GameServer.js being 1506 lines long...)

**Comment by TopoR1** [comment]
@AlexHGaming 9.4.0

**Comment by ZfsrGhS953** [comment]
@TopoR1 Just tell me a thing: Do you put these downvotes by yourself? If not, someone might have hacked your account.

**Comment by Luka967** [comment]
It's modified. We can't help you unless you give us something more to work with.
