### ISSUE TITLE
Features for minions

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#14]
please make a minion to use with E AND R like ogarUL , with "q" is sooo hard

**Comment by AlexandriteErikParacelsus** [comment]
agario client doesn't support E and R and we don't have our own client

**Comment by Megabyte918** [comment]
I'll see what I can do about the server sending minions split/eject packets so you can use E&R on separate clients, I'm not very experienced with working with packets or client-sided stuff, but I'll try

**Comment by Megabyte918** [comment]
@RelTakeover It has been implemented.
