### ISSUE TITLE
Pellet Mode Doesn't Work if Q OR P IS CLICKED!!

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#140]
Dont work! @Megabyte918 @Fantasy-Agario 
![image](https://cloud.githubusercontent.com/assets/20871314/20862883/caca538c-b9f2-11e6-8a97-867c88278b9a.png)

**Comment by Jhair2015** [comment]
@NameYT  Fixed

**Comment by NameYT** [comment]
@Jhair2015 Thanks

**Comment by AlexandriteErikParacelsus** [comment]
wtf is this

**Comment by NameYT** [comment]
@Megabyte918 @Jhair2015 Okay it doesn't work

**Comment by Megabyte918** [comment]
@NameYT Refer to #131

**Comment by AlexandriteErikParacelsus** [comment]
You need the ERTP script in the scripts folder, because your ERT script is outdated and you don't need to disableQ

**Comment by Jhair2015** [comment]
@AlexandriteErikParacelsus  So that means that obligatorily each player must have installed the script, but there are some that are very stubborn and ignore to install script besides that some goes wrong and an endless things ...

**Comment by NameYT** [comment]
@Jhair2015 @Megabyte918 DONT WORK DAFUQ

**Comment by Megabyte918** [comment]
Works fine for me.

**Comment by AlexandriteErikParacelsus** [comment]
@Jhait2015 who gives a crap, they can't use pellet mode is their fault, and there are no clients that supports P (I didn't found one yet)

**Comment by NameYT** [comment]
@Megabyte918 i fixed it i cant pellet mode cuz i ran 1000 bots why

**Comment by MastaCoder** [comment]
Why are you running 1000 bots..

**Comment by firelightning13** [comment]
for youtube
