### ISSUE TITLE
How to play with my friends ?

### ISSUE THREAD

**Issue by GhostShot3** [Megabyte918/MultiOgar-Edited#1401]
I want to play with my friend, how do I get him to access my server?

**Comment by AlexHGaming** [comment]
Host it on a VPS or any free IDE like Codeanywhere.

**Comment by GhostShot3** [comment]
How ?

**Comment by AlexHGaming** [comment]
Look at my video here on how to do it: https://www.youtube.com/watch?v=xqzUcB5DjX4&t=77s

**Comment by GhostShot3** [comment]
Ok

**Comment by GhostShot3** [comment]
I'm with problems, i commented in your video I'm the "ghostshot3"

**Comment by GhostShot3** [comment]
You have discord to help me ?
