### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GhostShot3** [Megabyte918/MultiOgar-Edited#1402]
How to convert mass to size and size to mass?

**Comment by Agarian** [comment]
From size to mass, it's (`size` * `size`) / 100.

**Comment by GhostShot3** [comment]
And mass to size ?

**Comment by AlexHGaming** [comment]
I think:
100 * (size / size)

**Comment by GhostShot3** [comment]
Hm, i wil try it

**Comment by GhostShot3** [comment]
Nope

**Comment by GhostShot3** [comment]
Why size instead of mass?

**Comment by Agarian** [comment]
Because that's how agar.io does it. I believe it's less work on the server side to calculate mass to size for agar.io.

**Comment by Agarian** [comment]
The formula for mass to size is: `square root (mass * 100)`.

**Comment by GhostShot3** [comment]
Thanks
