### ISSUE TITLE
How to open console plus in codeanywere ?

### ISSUE THREAD

**Issue by GhostShot3** [Megabyte918/MultiOgar-Edited#1405]
/\

**Comment by AlexHGaming** [comment]
You can't.

**Comment by GhostShot3** [comment]
Ok

**Comment by GhostShot3** [comment]
@AlexHGaming For the server to run 24 hours a day need to buy "always on"?

**Comment by Xyros7** [comment]
@GhostShot3  CodeAnywhere is shit, dont pay for it, buy a vps , you might find it cheaper.

**Comment by GhostShot3** [comment]
@ghost codeanywerer lag ?

**Comment by AlexHGaming** [comment]
@GhostShot3 Codeanywhere only allows you to have 1 always on container, and you have to pay monthly. I am pretty sure you don't need to pay monthly or like that with a VPS. I suggest OVH as a VPS, since it has good reviews :).

**Comment by AlexHGaming** [comment]
You can host servers, yes
