### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by GhostShot3** [Megabyte918/MultiOgar-Edited#1406]
When server auto restart the bots disappear

**Comment by Agarian** [comment]
I'd assume that you mean the `serverBots` config doesn't spawn more bots upon restart.

**Comment by GhostShot3** [comment]
Yes

**Comment by GhostShot3** [comment]
@Agarian How to make aways spawn ?

**Comment by Agarian** [comment]
@GhostShot3 Try adding the following code to the [restart function](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L580):
```js
if (this.config.serverBots) {
    for (var i = 0; i < this.config.serverBots; i++) this.bots.addBot();
    Logger.info("Added " + this.config.serverBots + " player bots");
}
```

**Comment by GhostShot3** [comment]
Ok

**Comment by Agarian** [comment]
Let me know if it doesn't work for you, but I can't guarantee I can help right away (no PC to test on).

**Comment by GhostShot3** [comment]
I will test it

**Comment by GhostShot3** [comment]
http://prntscr.com/ib4f9c

**Comment by Agarian** [comment]
You probably added it wrong

**Comment by GhostShot3** [comment]
Working ,you will add it as commit ?

**Comment by Agarian** [comment]
Will do.
