### ISSUE TITLE
Why lag?

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1407]
There are 70 players on the server, each with 15 minions, the server itself is loaded only by 30%, but the game shows that everything is slow. RAM is always filled to 60-70%. I do not know why all actions are slower if the server is not even half full. I tried to use uws, but nothing has changed. Also on the server are 2000 feeds, 50 spines and 10 bots-players. What to do?

P.S now on the server less players, but in the evening there are a lot of them.
![image](https://user-images.githubusercontent.com/19995663/35777653-bddcc58a-09c2-11e8-9456-68b2c1b33450.png)

**Comment by TopoR1** [comment]
When players are more than 60, it becomes noticeable that the game is slower.

sorry for my English

**Comment by AlexHGaming** [comment]
@Luka967 nerd come here.

**Comment by ZfsrGhS953** [comment]
@TopoR1 Install the latest version from here, and **do not modify anything**.

**Comment by TopoR1** [comment]
@ZfsrGhS953And so is the latest version.

**Comment by ZfsrGhS953** [comment]
@TopoR1 Update your Node.js if it's outdated (the latest version is 9.5.0)

**Comment by TopoR1** [comment]
@ZfsrGhS953 It is installed. Believe me, all the options that you offered, I tried

**Comment by ZfsrGhS953** [comment]
@TopoR1 The only other option I know is to install Linux on the server.

**Comment by TopoR1** [comment]
@ZfsrGhS953 Also slows down, nothing has changed

**Comment by Luka967** [comment]
That's a high amount of minions for just 70 players; try changing the config
Also the CPU is bad, get one with high IPC (architecture doesn't matter a lot, just look for high clocks) and low core count (you don't need all the cores, node.js's code execution is in one thread)

**Comment by TopoR1** [comment]
@Luka967 And why not make multithreading?)

**Comment by Luka967** [comment]
Aside from node.js's limitations on synchronized multi-threading, you can't scale this execution pattern to multiple threads. The only thing here parallelizable is the quadtree's search functions by making it a C++ addon, and I'd bet for not much improvement.

**Comment by TopoR1** [comment]
@Luka967 In vain I certainly bought 4 cores ...
