### ISSUE TITLE
help pleease

### ISSUE THREAD

**Issue by dada211** [Megabyte918/MultiOgar-Edited#1409]
how do I add an ipbots plugin https://github.com/dinhduynhat/OgarUL-Plugin-Library

**Comment by DeadLord1337** [comment]
MoE and UnlimitedOgar different projects (UnlimitedOgar no longer supported none)

**Comment by GhostShot3** [comment]
@DeadLord1337 exactly

**Comment by Fan7asy** [comment]
*UnlimitedOgar*
