### ISSUE TITLE
auto restart

### ISSUE THREAD

**Issue by MineMooreALT** [Megabyte918/MultiOgar-Edited#141]
Hi can you please add auto restart and if possible ip bots. Would make my day!

**Comment by MastaCoder** [comment]
I was actually going to add this: auto restart

**Comment by MineMooreALT** [comment]
what

**Comment by AlexandriteErikParacelsus** [comment]
> I was actually going to add this: auto restart
It means he was actually going to add this: auto restart

**Comment by MineMooreALT** [comment]
ok 👍

**Comment by Jhair2015** [comment]
@MineMooreALT https://github.com/Barbosik/MultiOgar/issues/217#issuecomment-233934233

**Comment by MineMooreALT** [comment]
So its impossible? I wanna make one of those selffeed server's like alis but i need auto restart

**Comment by Fantasy-Agario** [comment]
Its not impossible , but its hard @MineMooreALT

**Comment by MineMooreALT** [comment]
What about a thing that triggers a killall command every 2 minutes

**Comment by Fantasy-Agario** [comment]
Yeh thats not a bad idea , I can make u a version if u like do u have skype or anything?

**Comment by MineMooreALT** [comment]
yeah taj.moore89 thanks

**Comment by Fantasy-Agario** [comment]
I'll do it tommoro as I'm going to sleep in a min or two as its like 01:28 am

**Comment by MineMooreALT** [comment]
Oh ok damn but tomorrow is school and its like 9:29 am for me

**Comment by Fantasy-Agario** [comment]
Ok ill do it now then :D

**Comment by MineMooreALT** [comment]
Thanks

**Comment by Fantasy-Agario** [comment]
Np :P

**Comment by MineMooreALT** [comment]
if you cannot find me on skype just tell me your skype

**Comment by Fantasy-Agario** [comment]
Cant find u 

My skype : FantasyIsBae

**Comment by MineMooreALT** [comment]
requested

**Comment by MastaCoder** [comment]
I'm pretty sure MultiOgar doesn't ever go up to 4GB. The person in the post said that killing 1 process that is using a whole 4GB is a dangerous practice, and yes it is.

![img](https://i.gyazo.com/cd2e0b3e97d6f0598abf6fe0d6ea0f82.png)

With 12~ servers active restarting every 3 hours I barely go over 4GB of RAM usage. (While CPU is pretty high) Don't use the killall command, a better practice is to close the program completely, have it wait 20 seconds for node to clear everything and then restart the server. If you just use killall, the background RAM that might occur on some memory leaks could still be there.

**Comment by Megabyte918** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/146#issuecomment-266349717
