### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by GhostShot3** [Megabyte918/MultiOgar-Edited#1420]
I have an idea of adding a command to update the server files(like ogarunlimited), this would help those who have hosted servers ,they would not have re-dowload the files.

**Comment by Agarian** [comment]
~~Nah, OgarUL ain't good for MultiOgar's health~~

**Comment by GhostShot3** [comment]
@Agarian Lol

**Comment by MastaCoder** [comment]
What he said

**Comment by GhostShot3** [comment]
@MastaCoder ? is just a command

**Comment by MastaCoder** [comment]
> Nah, OgarUL ain't good for MultiOgar's health

**Comment by GhostShot3** [comment]
@MastaCoder is a C-O-M-M-A-N-D

**Comment by Agarian** [comment]
Well we D-O-N-T want OgarUL commands here @GhostShot3.

**Comment by GhostShot3** [comment]
@Agarian OMGGGGG

**Comment by GhostShot3** [comment]
This will not affect the performace

**Comment by AlexHGaming** [comment]
We never said it would.

**Comment by GhostShot3** [comment]
Okay, I'll stop talking here
