### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#1422]
If you have virusEqualPopSize set to 1 and then if you change the playermaxcells more than 16 (for example I had 64) the virus will only split the cells into 16 and not 64.

**Comment by AlexHGaming** [comment]
@Luka967

**Comment by Agarian** [comment]
That's because there's a separate config for how many cells a virus splits you into. It's `virusMaxCells`.

**Comment by Agarian** [comment]
Though I honestly think the `virusMaxCells` config should be removed.

**Comment by freaky767** [comment]
Oh.
