### ISSUE TITLE
Virus custom range & speed

### ISSUE THREAD

**Issue by GhostShot3** [Megabyte918/MultiOgar-Edited#1425]
How to edit virus speed and distance separately ?and is possible to put exact speed ?
The `virusVelocity` config change the 2 tings at same ,i need to change the Velocity and the Range separately

**Comment by DeadLord1337** [comment]
? refine what do you want to do, what do you need it

**Comment by Agarian** [comment]
I don't think you can edit both separately, but I may be wrong.

**Comment by GhostShot3** [comment]
@DeadLord1337 Title
