### ISSUE TITLE
spawn cell

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#1427]
A spawn player takes place in any place, no matter what there is a player. Why not make spawn players in a place where there are no players, and then enrages that constantly spawn the player in the players. In the agarion, there is no such thing and it will spawn precisely to the place where there are no players. I hope this will not be ignored and there will be a normal spawn of players not in the players will be realized.

**Comment by Agarian** [comment]
Wasn't this fixed already? I mean, that's what the `willCollide` function does (or is supposed to). Then again, I last saw it work in 1.5.0.

**Comment by TopoR1** [comment]
@Agarian I do not know, but I use the latest version of MultiOgar and 6 protocol and when I press Play and there are a lot of players on the card, I will either not spawn or spawn in the player or I will normally recover. I would like it to be corrected, it's probably the 6th protocol, because I did not check it at 4 and 5.

**Comment by Agarian** [comment]
I believe you not spawning has to do with the `willCollide` function being unable to find a "safe" place to spawn. Otherwise, I'm not sure. I may make a PR to revert to 1.5.0's `willCollide` function, but not until somebody else can prove that it doesn't work.

**Comment by Agarian** [comment]
Oh and for the record, protocol has nothing to do with it.

**Comment by TopoR1** [comment]
@Agarian Then you need to fix this problem on the server
