### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GhostShot3** [Megabyte918/MultiOgar-Edited#1428]
The bots is machine learning ?

**Comment by Luka967** [comment]
No
And ask questions on discord next time.

**Comment by GhostShot3** [comment]
@Luka967 Ok ,sorry ?

**Comment by Agarian** [comment]
(Close this)

**Comment by AlexHGaming** [comment]
>And ask questions on discord next time.
>Says in the discord rules to not ask questions.

WaitWhat

**Comment by MastaCoder** [comment]
https://i.imgur.com/qNyPHqu.png - Where?

**Comment by Agarian** [comment]
Rule #3: "Don't ask around everybody for custom code or roles"

**Comment by AlexHGaming** [comment]
^^

**Comment by Luka967** [comment]
How does mentioning code or roles imply questions

**Comment by AlexHGaming** [comment]
> Don't ask around everybody for custom code 
`ask`

**Comment by Luka967** [comment]
>>Don't ask **for custom code or roles**

>Don't ask any type of question, not even how this or that works

?????

**Comment by Fan7asy** [comment]
![maxresdefault](https://user-images.githubusercontent.com/21162678/36395816-018c39a4-15b3-11e8-8fb3-422ee058424e.jpg)
I'd agree with Luka

**Comment by AlexHGaming** [comment]
>  imply questions

**Comment by AlexHGaming** [comment]
> questions

**Comment by Agarian** [comment]
k

**Comment by Fan7asy** [comment]
How fucking retarded are you guys
He's asking a question get over it.

**Comment by GhostShot3** [comment]
getting over it ?

**Comment by MastaCoder** [comment]
Asking questions about the project is a question. Asking questions about people helping you adding custom code is not condoned, I don't know how much clearer this needs to be.
