### ISSUE TITLE
Memes

### ISSUE THREAD

**Issue by Fan7asy** [Megabyte918/MultiOgar-Edited#1429]
Submit your memes here

![hyperboi](https://user-images.githubusercontent.com/21162678/36395891-632f9750-15b3-11e8-8e3d-306a3b177f81.png)

**Comment by SuperOP535** [comment]
![zozzz](https://user-images.githubusercontent.com/27556391/36396060-7b8933ca-15bc-11e8-8dc5-f1de558a8f1e.jpg)

**Comment by Fan7asy** [comment]
xDD

**Comment by GhostShot3** [comment]
lol

**Comment by SuperOP535** [comment]
why makan

**Comment by MastaCoder** [comment]
ur memes no issue jaja eks dee

**Comment by Fan7asy** [comment]
Nuuu

**Comment by Agarian** [comment]
~~I will end u if u don't open dis again~~

**Comment by Agarian** [comment]
![received_544403125927719](https://user-images.githubusercontent.com/23372586/36401747-86154a96-15a7-11e8-9a09-254c6d337d24.jpeg)

**Comment by AlexHGaming** [comment]
![image](https://user-images.githubusercontent.com/23644244/36425889-411638d0-1640-11e8-90bf-a9a7ec9d9d06.png)

**Comment by Fan7asy** [comment]
@AlexHGaming How about you fuck yourself you idiotic hypocrite. 
First you tell us to follow the rules, and then what do you do? You go into our guild and fuck it up. 
Go fucking kys. You are one deluded cunt. This time im fucking pissed off.

**Comment by AlexHGaming** [comment]
@Fan7asy Firstly, yes i did tell you to follow the rules, if you didn't then you would have to face consequences (mutes, kicks, bans), then in the same server you started to talk shit behind my back, so what could I have done to get revenge? "Oh ye I'm just gonna let you get away with talking shit behind be back, oohoo im not gonna get noticed"
If you never were talking about me, I would not spam mention the server. I would just left it chill and minded your own business, I don't let things slide.
