### ISSUE TITLE
Anyone plz

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#143]
Anyone please pass me a code to random skins (no with skins), im working a project to random skins from Dlc 1 to Dlc actualli, but im need te code to start working

**Comment by Megabyte918** [comment]
@AlexByte918 
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L263-L278
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L287-L295
