### ISSUE TITLE
Gravitational splits is POSSIBLE

### ISSUE THREAD

**Issue by kekko9994** [Megabyte918/MultiOgar-Edited#1430]
@AlexHGaming @Megabyte918 MegaByte918 the Gravitational splits is possible, watch my smallest video: https://youtu.be/qp9qa7VjUms > this is are all my job. 

PS. U need more Clips write in the chat with comment.

**Comment by DeadLord1337** [comment]
@kekko9994 it is not possible you have 100% changed the code, in pure Mo-E it is almost unreal

**Comment by kekko9994** [comment]
nope, i'm not changed the code

**Comment by kekko9994** [comment]
i'm used gameserver.ini

**Comment by kekko9994** [comment]
u need to watch with you eyes????

**Comment by kekko9994** [comment]
i'm training in my server
for search more bugs on my server

**Comment by DeadLord1337** [comment]
pour your version on some file sharing service I downloaded

**Comment by kekko9994** [comment]
you have hamachi, i'm see you this split

**Comment by Agarian** [comment]
I know how to add this -_-

**Comment by AlexHGaming** [comment]
So do I, I have the code for it, I will make a PR for this.

**Comment by Agarian** [comment]
Add the following code to [line 825 in GameServer.js](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L825):
```js
if (!check.canEat(cell) || cell.getAge() < 1 && check.cellType == 0) return;
```

**Comment by AlexHGaming** [comment]
I'm PR'ing a more simpler way.
Hold on.

**Comment by Agarian** [comment]
## more simpler
Also, how is it more simple?

**Comment by RevengePlayz** [comment]
@AlexHGaming Is there are way i can make locked names for a specific ip address or something

**Comment by kekko9994** [comment]
WRONG!!!!! i'm are an agar modder all for me is not are secret

**Comment by Agarian** [comment]
@kekko9994 Dude the code I specified just makes them much easier to perform...
In no way am I saying this is impossible without the code, just extremely difficult. I've done it only ONCE without my addition (after like 30+ previous tries). So I am implying that it's just very difficult, not impossible. Now, who exactly are you calling a liar here?

**Comment by AlexHGaming** [comment]
@kekko9994 Trying to not be rude, but your grammar is not understandable. And no it is not wrong, since it actually works, and being an agar modder ain't even possible. It's called "good at agario clone (editing)"

**Comment by B0RYS** [comment]
"Gravitational splits" kden we have an aeronautic scientist over here.

**Comment by AlexHGaming** [comment]
@B0RYS Reason it was called that was because back when the pushsplit just came into gota, we didn't have a name for what it would be called, so I just named it gravitational because it like moves weird, I don't know, I just prefer it to be called PushSplits.

**Comment by SuperOP535** [comment]
k

**Comment by Agarian** [comment]
The problem I see with calling this type of pushsplit just a "pushsplit" is that there is already a trick under that same name in agar.io. So by not naming this pushsplit a "gravitational pushsplit", it can cause confusion. Could there be a better name for this trick? Yes. Do I know what that name would be? No, but since people kept adding "gravitational" in-front of the name, people just kind of went with it.

**Comment by Gigabyte918** [comment]
@Agarian i tried these code

if (!check.canEat(cell) || cell.getAge() < 1 && check.cellType == 3) return;

and

if (!check.canEat(cell) || cell.getAge() < 1 && check.cellType == 3) {
return;
}

but the code isnt working i want eject mass to go throw player but this code dosent change anything but if i change check.cellType to 0 it applys eat collision on every cell type please help!

**Comment by Agarian** [comment]
@Gigabyte918 Do you mean you want them to ALWAYS go through players? Or just have a small window to when cells are stacked on each other? To do the second thing, remove ` && check.cellType == 3` completely. For the first thing, keep ` && check.cellType == 3`, and change `cell.getAge() < 1` to a larger number (you may also have to add ` && cell.cellType == 3` but IDK for sure).

**Comment by Gigabyte918** [comment]
I tried this code but nothing changes

if (!check.canEat(cell) || cell.getAge() < 1 && check.cellType == 0) return;

**Comment by AlexHGaming** [comment]
Okay, since you guys are really bothered, do this.

Put the following code on this line [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L825):

   ```javascript
 if (!check.canEat(cell) || cell.getAge() < 2) {
        // check doesn't want to eat
        return;
    }
```

**Comment by AlexHGaming** [comment]
or ```javascript
if (!check.canEat(cell) || cell.getAge() < 1 && check.cellType == 0) return;
``` like agarian said

**Comment by AlexHGaming** [comment]
if ya talking about pushsplits, or "gravitational splits"

**Comment by Gigabyte918** [comment]
i want only eject cell to go throw player not other cell type

Code i used

`if (!check.canEat(cell) || cell.getAge() < 20 && check.cellType == 3) return;`
