### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by ManishaD6** [Megabyte918/MultiOgar-Edited#1436]
I installed multiogar, and when I go to http://agar.io/?ip=127.0.0.1:443, it won't connect me to the server( when I press play, there's a blank screen). I installed everything correctly, and I ran win-Start.

**Comment by Agarian** [comment]
For one, make sure the port in `gameserver.ini` is 443. And if you have Skype open, you will need to change the port to something else.

**Comment by ManishaD6** [comment]
The port is 443 and I don't have Skype

**Comment by AlexHGaming** [comment]
@ManishaD6 Try logging out of your agar.io FB / Gmail account.

**Comment by Agarian** [comment]
^

**Comment by ManishaD6** [comment]
Im not logged in lol

**Comment by ManishaD6** [comment]
and I also unchecked the no skins option

**Comment by AlexHGaming** [comment]
Please can you provide me an image of your console when connecting to a server? Thanks.

**Comment by ItzLevvie** [comment]
Miniclip has done some protocol changes on their side, so for now use a custom client.

**Comment by ManishaD6** [comment]
Can you tell me the custom clients I can use, please?

**Comment by ManishaD6** [comment]
AlexHGaming, the console remains the same as when I opened it

**Comment by ManishaD6** [comment]
![20180310_131300](https://user-images.githubusercontent.com/37234081/37246792-fc253d06-2464-11e8-89d6-a374129cff7b.jpg)

**Comment by ManishaD6** [comment]
sorry it's sideways...

**Comment by AlexHGaming** [comment]
Not your node console, the web console.

**Comment by ManishaD6** [comment]
Sorry, how do I find the web console...

**Comment by AlexHGaming** [comment]
F12 -> Console

**Comment by ManishaD6** [comment]
![20180310_132812_001](https://user-images.githubusercontent.com/37234081/37246923-396426da-2467-11e8-800c-f0f95cb698e5.jpg)

**Comment by Agarian** [comment]
I think agar.io broke private servers again...

**Comment by ManishaD6** [comment]
What clients can I use?

**Comment by Agarian** [comment]
You could try mine: https://agarian-2.github.io/

**Comment by ManishaD6** [comment]
I don't think it works :(

**Comment by Agarian** [comment]
Dude yes it works, I use it all the time!

**Comment by ManishaD6** [comment]
You select Local 443 right?

**Comment by Agarian** [comment]
Yes...

**Comment by ManishaD6** [comment]
I tried and it just says connecting... Thank you though.

**Comment by AlexHGaming** [comment]
Just as long as you have a server running on the port 443, then you connect to an option which has the value of port 443, you should be able to connect without any errors.

**Comment by cowpits** [comment]
Yeah miniclit update agario client. you can use my tutorial test site http://cowpits.ga to play on your server. 
Select LOCAL from the drop down list, it's set to connect to 127.0.0.1:443
If you want to make your own I made a bunch of tutorial on my channel youtube.com/cowpits

**Comment by cowpits** [comment]
I've been moving all weekend and don't have my stuff set up yet to figure out their new protocol might be a while before i get to it.

**Comment by ManishaD6** [comment]
Thank you cowpits, and everyone else for your support!

**Comment by AlexHGaming** [comment]
Client sided.

If you want to add skins on the cigar clients, go to the folder called skins then add the images there.

**Comment by MastaCoder** [comment]
Seems like this problem is solved, let me know if there are any more issues.

**Comment by cowpits** [comment]
@ManishaD6 I added a bunch of agario skins to the gallery.

**Comment by ManishaD6** [comment]
Thank you so much ♥!
