### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by Tetratrix** [Megabyte918/MultiOgar-Edited#1437]
How can I show the id of the player in the client?
I have tried sending packages, but without success, I am using cigar client

**Comment by Agarian** [comment]
There is a /id command for the client's chat...

**Comment by Tetratrix** [comment]
Yes i know, but i want to show it in a text on client

**Comment by MastaCoder** [comment]
If you want it to show on the players name just have it send after the name like Makan#1. If you want it anywhere else it's going to require some client side changes.
