### ISSUE TITLE
Agar.io connecting to arena error . . .

### ISSUE THREAD

**Issue by tris90190** [Megabyte918/MultiOgar-Edited#1438]
Whenever I try to join my private server, all the clients I try wont connect. The agar.io one just says connecting to arena and then disconnects. I am signed out of google / facebook. Why is this happening? How can I fix it?

**Comment by Agarian** [comment]
What Node version are you running? Are you using the latest version of MultiOgar-Edited? What messages do you get in the dev console in other clients? You need to be more specific. And just a note, it appears that agar.io had some client updates, so that client is out of the picture currently.

**Comment by cowpits** [comment]
yeah there's a new agario client update that blocks connections to private servers.

**Comment by tris90190** [comment]
I got it working today. Thanks.

**Comment by Luka967** [comment]
How though? I've just started debugging it. I can't spawn in and the client constantly sends messages with unknown IDs.

**Comment by Agarian** [comment]
@tris90190 Do you mean you got it working on another client? Or did you ACTUALLY get it to work on the agar.io client?
