### ISSUE TITLE
Agario Private Server Still Doesn't Working After March Update 

### ISSUE THREAD

**Issue by Aminovic96** [Megabyte918/MultiOgar-Edited#1439]
Hello,

After the update by Miniclip this month, the private server doesn't working and the Connect message appears, although I start Run, play on Port 443 and to make sure i change the Port code to 4545 and i get the same result!
What should i do ?, is there a simple problem that I might be able to solve it or i wait the update ?
![capture](https://user-images.githubusercontent.com/37406305/37464888-a0dd0eba-2851-11e8-9be0-f56f6885dab6.PNG)

Thanks

**Comment by Agarian** [comment]
Most likely wait for a new server update, as time is needed to figure out what changed, and to fix it accordingly.

**Comment by Aminovic96** [comment]
Thanks

**Comment by Faris90** [comment]
go to reroagr.bitballoon.com/?ip=127.0.0.1:443

**Comment by Aminovic96** [comment]
Hi guys
Mostly the server still doesn't working after this new Update
I tested anything but without any results
i don't know where is the problem 
pls can i solve it ?
![capture](https://user-images.githubusercontent.com/37406305/39664086-e7d2cbec-5075-11e8-8008-b7376b75eeeb.PNG)

**Comment by Luka967** [comment]
https://www.reddit.com/r/Agario/comments/8h1b0t/how_to_connect_to_private_servers_on_agario_after/

**Comment by Agarian** [comment]
@Aminovic96 Close?

**Comment by rassmate** [comment]
Cannot get this to work either.
Don’t know where to put code suggested in reddit link.

**Comment by Luka967** [comment]
In the developer console.

**Comment by Agarian** [comment]
k
