### ISSUE TITLE
New Commnad 

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#144]
@Megabyte918 add update command so we dont have to download it all over again also
if i spawn 1000 bots? i cant do a pellet mode.....
but if i run 500 i can do them pellet mode
how is that posible ?

**Comment by MastaCoder** [comment]
You can just use git, it'll update it for you.

**Comment by Megabyte918** [comment]
@NameYT Refer to #36
And by default visible node calculations for minions are disabled once the server has detected there are greater than 800, this includes calculations for pellets unfortunately.
