### ISSUE TITLE
How can I make my friends play with me in Private server?

### ISSUE THREAD

**Issue by Aminovic96** [Megabyte918/MultiOgar-Edited#1440]
- In particular, Hamachi has been used before but unfortunately the number of friends is limited in 5 and there is slow in playing at this network !
Are there other programs better than Hamachi and give me an unlimited number of friends?

- Private Server Not yet working because of Miniclip updates, I have now played at Client http://cowpits.ga Can my friends play with me on this server?

Thanks

**Comment by AlexHGaming** [comment]
I suggest using a VPS or an IDE.

You can use really bad ones like [Codeanywhere](https://codeanywhere.com), but it has consistent 190ms+ response time. A VPS like OVH would be highly recommended if you are looking for fast servers.

**Comment by cowpits** [comment]
if you're running your server from you home computer, then forward the port from your router. or like Alex said setup a server on codeanywhere but it lags. cowpits.ga will be up for a while so feel free to play on it with your friends if you like.

**Comment by Aminovic96** [comment]
Really, thank you very much <3

**Comment by Aminovic96** [comment]
Really, thank you very much

**Comment by MastaCoder** [comment]
Why was this re-opened?

**Comment by Agarian** [comment]
*insert shrug here*
