### ISSUE TITLE
Protocol 1

### ISSUE THREAD

**Issue by Faris90** [Megabyte918/MultiOgar-Edited#1441]
How can I connect to protocol 1

**Comment by SuperOP535** [comment]
Lol

**Comment by ItzLevvie** [comment]
Protocol 1 doesn't exist

**Comment by AlexHGaming** [comment]
da fk

**Comment by MiraMiPalo** [comment]
![29d5c8404945e4e2490e58cc03bbb1397261dad3_00](https://user-images.githubusercontent.com/25539632/37884023-27ba8bbc-306b-11e8-9fd2-6b7cbedaca7a.jpg)

**Comment by ZfsrGhS953** [comment]
@Faris90 The one that doesn't support viruses and uses float64 for x, y and size? Watch out for your server bandwidth and players saying "WHY CAN'T I EAT GREEN CELLS???" So I don't think there are any good reasons to support it.

**Comment by Faris90** [comment]
It exists in agarserv

**Comment by Faris90** [comment]
:p

**Comment by Faris90** [comment]
You all have no c

**Comment by ZfsrGhS953** [comment]
@Faris90 Agarserv uses protocol 5.

**Comment by Agarian** [comment]
^

**Comment by AlexHGaming** [comment]
^

**Comment by AlexHGaming** [comment]
To be fair I don't understand why you would want to even connect to it. I'd just stick with the normal one to be honest.

**Comment by SuperOP535** [comment]
Wanna hear a joke? agar.bio


didn't get it? it still uses protocol 1 xd

**Comment by ZfsrGhS953** [comment]
@SuperOP535 I checked, it's protocol 4. Didn't understand the joke.

**Comment by SuperOP535** [comment]
No it is 1, I tried to connect to mogar-e with it and it said "protocol 1 assumed as 4" so?

**Comment by AlexHGaming** [comment]
_protocol 1 assumed as 4_

`assumed as 4`

**Comment by SuperOP535** [comment]
yes, it says **1**

**Comment by ZfsrGhS953** [comment]
@SuperOP535 That's a bug with some clients that causes the protocol to show up as 1 even if it's a different one.

**Comment by SuperOP535** [comment]
ok smart guy thanks for proving me wrong 😢

**Comment by Agarian** [comment]
*Close*

**Comment by ZfsrGhS953** [comment]
@Agarian It's already closed.

**Comment by Agarian** [comment]
k

**Comment by AlexHGaming** [comment]
rekt

**Comment by ZfsrGhS953** [comment]
@Agarian Or did you mean to have a collab close it so that it doesn't suddenly go open if Faris90 presses the wrong button by mistake?

**Comment by AlexHGaming** [comment]
I don't know where Makan has been. Probably school since he has a life and I don't. FeelsBadMan

**Comment by Agarian** [comment]
@ZfsrGhS953 lol, no

**Comment by Agarian** [comment]
But answer me this: Do you happen to know what arras.io was? (If you don't) it's a diep.io private server pretty much. Though it has a major flaw, and that is how inefficient it is. You can find the code [here](https://github.com/nepphhh/arrasio). But what I really want to ask is could you find out just why it's inefficient, and how it would be fixed? You'd be helping a decently large discord community.
