### ISSUE TITLE
I can't connect to my own server, why is that?!?! I'm trying  to get the latest version to work?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!

### ISSUE THREAD

**Issue by FlOwwOlf40** [Megabyte918/MultiOgar-Edited#1442]
# **Please read this notice throughly before creating your issue.**

### Before you create your issue you ***MUST*** follow these rules: 

1. **The issue is in written in English.**
2. **The issue is directly related to the project.**
3. **Your issue is not a duplicate of a previous issue.**
4. **Descriptive information must be provided, so that we can reproduce the error you are experiencing**
5. **Error logs must be provided if any crashing is experienced.**

>**Please note that we will *NOT* provide assistance if the issue is with your own code, your issue WILL be locked if this is the case.**

# **Issue Formatting**

**In order for us to provide you with the best assistance we kindly ask you to present your issues in the best way that you can.**

Please read through [this guide](https://guides.github.com/features/mastering-markdown) to learn how you can apply [Markdown](https://en.wikipedia.org/wiki/Markdown) to your issues.

>---

**IF YOU HAVE READ THESE RULES PLEASE DELETE THIS TEXT**

**Comment by Aminovic96** [comment]
I have the same problem bro , because of miniclip update agario it doesn't work , you should waiting until getting the last version

**Comment by AlexHGaming** [comment]
Get the latest version, then connect to a different client other than agar.io.

**Comment by Agarian** [comment]
Try using https://agarian-2.github.io/

**Comment by AlexHGaming** [comment]
^

**Comment by Aminovic96** [comment]
Please Agarian How it does work ?; is there any tutorial to fix it ?

**Comment by SuperOP535** [comment]
Most custom clients does not use the latest protocol (for example that one uses 6 and agar.io currently uses 17 so there is a big difference)

**Comment by cowpits** [comment]
yeah don't try the agar.io client it's not working since the new march 2018 update as everyone has said. 
test your server on agarian client or try mine http://cowpits.ga, if you are running it on 127.0.0.1 then select LOCAL from the list if you are on codeanywhere or another vps, then edit element and add your server link.

**Comment by bbcnkl** [comment]
You can try
http://agar.rs?ip=127.0.0.1:443

**Comment by SuperOP535** [comment]
@bbcnkl your one is in a (for me, atleast) weird language so I don't think anyone would prefer that over an english one

**Comment by josefredohd** [comment]
http://josefredo.byethost3.com/?ip=127.0.0.1:443

edit ip

**Comment by bbcnkl** [comment]
@SuperOP535 You can choose language from dropdown menu xD

**Comment by Gasvash** [comment]
@josefredohd 
I like your client, I like :), by the way where can I get it?, can you please, I currently use the client of Luka, but I want to change: D

**Comment by Gasvash** [comment]
@bbcnkl and @josefredohd  

Hi, sorry but as I do to play with friends with your clients in a private server, I already try with my public ip but I can not

**Comment by CrosWebsite** [comment]
plz help :(

**Comment by Tombez** [comment]
@CrosWebsite what is your issue?
Try updating to the latest stable NodeJS (version 14 or 15)
