### ISSUE TITLE
what is happening

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1445]
@MastaCoder @Megabyte918, the repo has been untouched in ages, I get it, real life stuff, school etc. But what if someone was to spam the repo? Issues aren't being closed like they used to, issues need closing, like this one lol

**Comment by Luka967** [comment]
Why make an unnecessary issue then when you can ask the same question in the discord ser- oh wait, you say the server is pointless, why bother with the repo then?

**Comment by AlexHGaming** [comment]
Tell me what the point of the discord server is then @Luka967

**Comment by AlexHGaming** [comment]
why did i make this an issue anyways, what was i doing lol
