### ISSUE TITLE
Auto Restart Server

### ISSUE THREAD

**Issue by Flamto** [Megabyte918/MultiOgar-Edited#1450]
Hi can you add on server auto restart based score

exp: 80 000 score The server will restart 

like alis.o or gaver.io

**Comment by AlexHGaming** [comment]
#141 #447 #1281 #458 #596 #811 
One of these should work!

**Comment by Flamto** [comment]
but i don't got Full Help

**Comment by josefredohd** [comment]
Go to PlayerTracker.js and replace this:
 PlayerTracker.prototype.getScale = function() {
    this._score = 0; // reset to not cause bugs with leaderboard
    var scale = 0; // reset to not cause bugs with viewbox
    for (var i = 0; i < this.cells.length; i++) {
        scale += this.cells[i]._size;
        this._score += this.cells[i]._mass;
    }
    if (!scale) return scale = this._score = 0.4; // reset scale
    else return this._scale = Math.pow(Math.min(64 / scale, 1), 0.4);
};

For this:
PlayerTracker.prototype.getScale = function() {
    this._score = 0; // reset to not cause bugs with leaderboard
    var scale = 0; // reset to not cause bugs with viewbox
    for (var i = 0; i < this.cells.length; i++) {
        scale += this.cells[i]._size;
        this._score += this.cells[i]._mass;
        var c = [" ", "Restarting", "Winner", "Is", this._name]; 
        var Commands = require('./modules/CommandList'); 
        if (this._score >=30000) var execute = Commands.list['board'](this.gameServer, c);
	if (this._score >=30000) setTimeout(function(){process.exit(1);}, 0.08 * 60 * 1000);
    }
    if (!scale) return scale = this._score = 0.4; // reset scale
    else return this._scale = Math.pow(Math.min(64 / scale, 1), 0.4);
};

Replace 1 if (this._score >=30000), by the mass you want for the server to restart

**Comment by Flamto** [comment]
Thx Very much 

But when server restart consol close in windows

**Comment by MiraMiPalo** [comment]
@josefredohd  dame los creditos >:v xD

**Comment by josefredohd** [comment]
Use pm2 so that the server does not close

**Comment by Shair17** [comment]
JAJAJAJA
