### ISSUE TITLE
Arcadeplex.org bots

### ISSUE THREAD

**Issue by valonymeri** [Megabyte918/MultiOgar-Edited#1453]
Hi can anybody help me.
People keep sending me bots to my server using this arcadeplex.org  how to I stop this kind of bots

**Comment by AlexHGaming** [comment]
This is a client-sided feature iirc. You'd want to implement a ReCAPTCHA if you have permission for the website, otherwise set your client binding to another client that might have anti-bot support.

**Comment by valonymeri** [comment]
Thx for fast replay man
I have permission to the website. Whats the vest thing i should do.  Can you tell me more abot this iirc , ReCAPTCHA and cliend binding to another client with anti bot support please.

**Comment by Luka967** [comment]
Servers can't do much with a generalized client, however you can tighten the modifications an external script can do to the client. I've had an experiment with bots before. Try adding this to the start of the client's script.

```js
var WebSocket = window.WebSocket;
delete window.WebSocket;
```

Please report back, I want to see if this does work.

**Comment by ZfsrGhS953** [comment]
@valonymeri What kind of bots? Smart ones that play like a player - you can fix the problem by tweaking the game config. As for the bad dumb bots that cluster in a single position, for now you can turn on coordinate scrambling. But I'm working on a patch that blocks them without affecting minimaps at all - you can try it once it's finished.

**Comment by valonymeri** [comment]
Bots are called arcadeplex bots, and are added via tampermoneky chrome
extension using a script, which come to the mothercell like selfeed.  they
can break limits of the server by sending thousands of bots. How to stop
this any idea

**Comment by Luka967** [comment]
@ZfsrGhS953 arcadeplex is like any other bot group, a bunch of skids pretending to know something. It's definitely external minions in question
I've managed to find their extension script:
https://pastebin.com/Nmtqc4re

**Comment by Luka967** [comment]
@valonymeri You've made an error in the client's script, try debugging & fixing it. If you can't fix it send over the error message and the relevant code

**Comment by valonymeri** [comment]
How do you know i have made an error in my client script. i mean how to
stop them from sending bots to my client , i see no error in my client, i
am using cigar project as client

**Comment by ZfsrGhS953** [comment]
@NuclearC I think that's your bot script.

**Comment by valonymeri** [comment]
I have the serverMaxConnections to 200 but bots go past that, it does not
stop bots

**Comment by NuclearC** [comment]
nah that aint my script 🤔

**Comment by valonymeri** [comment]
Does any body knows how to stop these bots please ?

**Comment by AlexHGaming** [comment]
Try changing the following line to 1:
https://github.com/AlexHGaming/MultiOgar-Edited/blob/master/src/gameserver.ini#L82

**Comment by valonymeri** [comment]
It does not work because they use proxy, they don't have the same ip

**Comment by AlexHGaming** [comment]
oshit

**Comment by valonymeri** [comment]
Any idea  any one how to stop these bots.it must be a way.

**Comment by Wawy123** [comment]
you can add some weird packet that server would send and it would be encryption key.... you just have to make it hidden somewhere idk...

**Comment by ZfsrGhS953** [comment]
@Wawy123 [This](https://en.wikipedia.org/wiki/Security_through_obscurity#Criticism) I fail to understand why everyone here gives the lowest priority to security...

**Comment by Niall7459** [comment]
A captcha would probably solve this, but then again some people might not like it. Information for installing a captcha here https://www.google.com/recaptcha/intro/v3beta.html

**Comment by MastaCoder** [comment]
Captcha is your best bet.
