### ISSUE TITLE
Allow participation during tournament mode competition

### ISSUE THREAD

**Issue by agaraq** [Megabyte918/MultiOgar-Edited#1455]
Allow participation during tournament mode competition

**Comment by FirstCodeReviewer** [comment]
very simple realized.
https://github.com/Megabyte918/MultiOgar-Edited/blob/dbce2b37ff9014f10ed6deffcf6ebaa5e5e8e1cf/src/gamemodes/Tournament.js#L138

change to: 
if ((this.contenders.length < this.maxContenders)) {
