### ISSUE TITLE
Battle Royale Mode In Private server :O

### ISSUE THREAD

**Issue by iGhozT** [Megabyte918/MultiOgar-Edited#1456]
Anyone know anything about this? :o

**Comment by SuperOP535** [comment]
No, it's not possible. You have to make it yourself

**Comment by AlexHGaming** [comment]
It is possible. The only thing you need to make on the client side is where the zone is etc etc.

**Comment by SuperOP535** [comment]
I meant that it is not possible in the current state.. and I actually said `You have to make it yourself`.......

**Comment by Shair17** [comment]
Yes, it's possible @iGhozT

**Comment by MastaCoder** [comment]
You'll have to make it yourself.

**Comment by Faris90** [comment]
...

**Comment by MastaCoder** [comment]
Don't bump old issue.
