### ISSUE TITLE
Can I use the leaderboard in tournament mode?

### ISSUE THREAD

**Issue by agaraq** [Megabyte918/MultiOgar-Edited#1457]
Can I use the leaderboard in tournament mode?

**Comment by FirstCodeReviewer** [comment]
Play with this:
https://github.com/Megabyte918/MultiOgar-Edited/blob/dbce2b37ff9014f10ed6deffcf6ebaa5e5e8e1cf/src/gameserver.ini#L207

But I am not quite sure. Setting to Zero should do what you want. If not you need to adjust the code in Tournament.js

**Comment by MastaCoder** [comment]
You'll have to change the code to support the leaderboard instead.
