### ISSUE TITLE
Error at the end of the launch

### ISSUE THREAD

**Issue by CrIKxS** [Megabyte918/MultiOgar-Edited#1459]
Hello, I have a problem launching my server everything is going well and when I logged in I had error

`>| [FATAL] RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -599
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32LE (internal/buffer.js:515:3)
    at Buffer.writeUInt32LE (internal/buffer.js:528:10)
    at BinaryWriter.writeUInt32 (C:\io\src\packet\BinaryWriter.js:32:18)
    at UpdateNodes.writeUpdateItems5 (C:\io\src\packet\UpdateNodes.js:151:16)
    at UpdateNodes.build (C:\io\src\packet\UpdateNodes.js:20:34)
    at PacketHandler.sendPacket (C:\io\src\PacketHandler.js:303:29)
    at PlayerTracker.sendUpdate (C:\io\src\PlayerTracker.js:294:19)
    at GameServer.updateClients (C:\io\src\GameServer.js:457:39)
    at GameServer.mainLoop (C:\io\src\GameServer.js:662:10)`

Screen of the error : https://gyazo.com/661d81b057b96671dff4a500cf5e58b4

Thank you for your understanding and your help.

**Comment by ZmanGamer** [comment]
When you logged in did you mean to say play? Also i have a POSSIBLE SOLUTION under this comment.
                                                                                                  ---------- -------------

**Comment by ZmanGamer** [comment]
Delete the whole multiogar file (copy gameserver.ini if you want to keep your settings) and redownload multiogar as a zip and open it and unzip the file to wherever you want (also, install the latest lts build of node.js, then go to src and replace the gameserver file you copied earlier if you modified the defualt settings, then install the dependencies and wait for it to say dependencies installed successfully then press a key to exit that command prompt, then, go to the run folder in the multiogar folder then run it. (THIS IS A POSSIBLE SOLUTION AND I DON'T KNOW IF IT WILL WORK OR NOT. Just a warning.)

**Comment by AlexHGaming** [comment]
It's most likely your node version. Can you open the command prompt for me and put in `npm -v `then pasting it here! Much appreciated.

**Comment by ZmanGamer** [comment]
yup

**Comment by F0RIS** [comment]
![image](https://user-images.githubusercontent.com/10178982/43044362-27113b26-8dad-11e8-82a0-55fd25e8cdc7.png)

**Comment by SuperOP535** [comment]
Try using node 8

**Comment by B0RYS** [comment]
Fixed in cd7a4484dd73bee192e4a05aff1cc5c7fce0eeb2
