### ISSUE TITLE
Auto restart setting.

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#146]
Hello!

So the auto restart feature would be awesome if it were to be made!
Its because now and then my servers get too big.

Thank you!

**Comment by ZfsrGhS953** [comment]
I think I have a better idea to prevent players getting big. Calculate mass that the map can fit, then divide the server total mass by the map mass to get a fraction of map fill. Then, substract that fraction from 1 and divide the decay by it. I'll make a PR if @Megabyte918 decides that this is a good solution.

**Comment by DaAwesomeRazor** [comment]
Auto restart? You mean like restarting the process? or just killing all the players. I made an auto restart that closes the process, and pm2 auto opens it.

**Comment by G047** [comment]
lol razor

**Comment by Gimmo** [comment]
Death on Cell size limit will be more honestly.

**Comment by Tyler3D** [comment]
How about something like this:

`@echo off
cls
:start
node ../src/index.js
@echo.
@echo Restarting server...
@echo.
goto start`

**Comment by Tyler3D** [comment]
When the server crashes it restarts it

**Comment by Tyler3D** [comment]
So, All we need is a function to crash the server

**Comment by Tyler3D** [comment]
Or stop the process

**Comment by ZfsrGhS953** [comment]
Just crashing the server doesn't necessarily mean that the node process will exit. The intended way to do this is:
```javascript
process.exit(1);
```

**Comment by G047** [comment]
add this to the index.js

``setTimeout(function(){process.exit(1);}, 10*60*1000``

**Comment by Tyler3D** [comment]
Ok

**Comment by ZfsrGhS953** [comment]
That will restart the server in 10 minutes, but what if you want to restart it in a different amount of time? Use gameserver.js and read the restart time value from config.

**Comment by Tyler3D** [comment]
I did on my fork

**Comment by Tyler3D** [comment]
Now I test

**Comment by systemroot** [comment]
another way is https://github.com/remy/nodemon#delaying-restarting

**Comment by CalvinDKL** [comment]
@G047 setTimeout(function(){process.exit(1);}, 10*60*1000

That line, that doesnt restart the server.....

**Comment by CalvinDKL** [comment]
What i would like is a setting in the server files.
Which Restarts the server. Then ill add a countdown timer to my client so people can see it restarts.

**Comment by Tyler3D** [comment]
I made a pull request

**Comment by Tyler3D** [comment]
based on config

**Comment by CalvinDKL** [comment]
Thanks Tyler

PS isnt a pull request a thing where u merge or just add a feature?
i dont know lol

**Comment by Tyler3D** [comment]
Well, you make a fork and a pull request is to request the owner to accept your commits on your fork

**Comment by Tyler3D** [comment]
https://help.github.com/articles/about-pull-requests/

**Comment by CalvinDKL** [comment]
ok ok ok ok, and does your commit thingy have a autorestart thing?? xD

**Comment by Tyler3D** [comment]
Yup

**Comment by Tyler3D** [comment]
If you want it, download this

**Comment by CalvinDKL** [comment]
PLS ! Love u if u do, no homo.

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/MultiOgar-Edited

**Comment by Tyler3D** [comment]
XD

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/MultiOgar-Edited

**Comment by CalvinDKL** [comment]
Lol i hopes he accepts, it would be a useful feature!

**Comment by Gimmo** [comment]
It's crap. This shoudn't be done. The root of server problem have to be found.

**Comment by AlexandriteErikParacelsus** [comment]
@Gimmo right

**Comment by Megabyte918** [comment]
I added a playerMaxScore config so that you can have control over how big your server gets, I don't an auto-restart system needs to be implemented since there are node modules such as pm2 that can do it for you.
