### ISSUE TITLE
Unable to connect to a local server ( http://agar.io/?ip=127.0.0.1:443 )

### ISSUE THREAD

**Issue by r8w9a5k** [Megabyte918/MultiOgar-Edited#1461]
Hello.
I successfully started server via nodeJS.
![run](https://user-images.githubusercontent.com/28980824/41812224-6887964e-771f-11e8-9e7d-c97606d93576.png)

But when I try to play using http://agar.io/?ip=127.0.0.1:443 it's disconnecting me.
![fail](https://user-images.githubusercontent.com/28980824/41812233-9b134978-771f-11e8-87a0-26f8f978dad8.png)

What am I doing wrong? I also tried to change port but the problem was same.

**Comment by Agarian** [comment]
https://www.reddit.com/r/Agario/comments/8h1b0t/how_to_connect_to_private_servers_on_agario_after/

**Comment by r8w9a5k** [comment]
@Agarian Thank you but where should I paste these two lines of code?

```
core.disableIntegrityChecks(true);
core.connect("ws://ServerIP:Port");
```

**Comment by Luka967** [comment]
Developer console. F12 to open developer tools, the console should appear first.

**Comment by r8w9a5k** [comment]
@Luka967 Hi, thank you for your help. Now I see this problem ❌
![error](https://user-images.githubusercontent.com/28980824/41822534-8ee81aa2-77f1-11e8-8ab4-7683bc0fcc80.png)

**Comment by EastArctica** [comment]
@r8w9a5k I believe you have to put in your IPV4 Adress into the 127.0.0.1 or just put localhost for testing

**Comment by BradElko** [comment]
I'm having this same problem :(

**Comment by Agarian** [comment]
Got the same issue when I tried connecting to my Cloud9 server, I think agar.io just made the killblow to private servers on their client.

**Comment by FirstCodeReviewer** [comment]
use this basic userscript.
https://github.com/FirstCodeReviewer/Agario-client-with-private-servers
