### ISSUE TITLE
localhost:443 won't load. 

### ISSUE THREAD

**Issue by BradElko** [Megabyte918/MultiOgar-Edited#1462]
I loaded the two port (88 and 443).

88 Works fine 
![image](https://user-images.githubusercontent.com/28650697/42084743-8cd94ace-7b5c-11e8-8d0b-9037647e6e8c.png)

443 Never loads.
![image](https://user-images.githubusercontent.com/28650697/42084914-08dd852c-7b5d-11e8-9022-1bc9417e6769.png)

What am I doing wrong?

**Comment by ItzLevvie** [comment]
Go to Agar.io and press F12 then in the console type

```
core.disableIntegrityChecks(true);
core.connect("ws://localhost:443");
```

**Comment by BradElko** [comment]
When I did it with the special url
![image](https://user-images.githubusercontent.com/28650697/42118385-bbb773d8-7bd0-11e8-9086-94ff949e6318.png)
When I did it in the normal url
![image](https://user-images.githubusercontent.com/28650697/42118447-1ce4c4ee-7bd1-11e8-9487-11f438f0e79a.png)

**Comment by FirstCodeReviewer** [comment]
use this basic userscript.
https://github.com/FirstCodeReviewer/Agario-client-with-private-servers
