### ISSUE TITLE
Start.bat not working???

### ISSUE THREAD

**Issue by IceyYT** [Megabyte918/MultiOgar-Edited#1463]
I just downloaded the file edited the gameserver.ini then installed dependencies then tried opening the start.bat file. After the cmd prompt opened it said node is an incorrect or unknown command and didn't work. I decided to try messing with the file a little bit to see if I could fix it but could not. Please help. ;(

PS I was trying to fix it myself because I did not have an account on here yet.

**Comment by IceyYT** [comment]
Oh yeah and I've tried your guys new code aswell as the old one.

**Comment by Luka967** [comment]
Try downloading & installing the current LTS version of node. If it still won't work, can you screenshot what's appearing in the command prompt?

**Comment by IceyYT** [comment]
[](https://imgur.com/a/zKtkZ0l) thats the screenshot link.

**Comment by Luka967** [comment]
You don't even have node.js installed.
https://nodejs.org/en/

**Comment by Luka967** [comment]
You don't have node.js installed. MultiOgar-Edited uses node.js.
https://nodejs.org/en/

**Comment by IceyYT** [comment]
thank you it works now! I guess I downloaded the wrong thing lol. You guys can close this now.
