### ISSUE TITLE
Private servers not work anymore

### ISSUE THREAD

**Issue by Radu13** [Megabyte918/MultiOgar-Edited#1464]
I can't enter in my personal server, did all the steps.
I also used last metthod from reddit 
core.disableIntegrityChecks(true);
core.connect("ws://127.0.0.1:443");

Console gives me undefined and search a normal server after that

**Comment by FirstCodeReviewer** [comment]
use this basic userscript.
https://github.com/FirstCodeReviewer/Agario-client-with-private-servers

**Comment by Radu13** [comment]
How i put it in script folder but i don't get exactly how get it work

**Comment by FirstCodeReviewer** [comment]
There is a README inside the repository explaining it step by step.
You obviously need Tampermonkey for that.

**Comment by Radu13** [comment]
You can provide me the link?

**Comment by DeadLord1337** [comment]
From agar.io new Protocol 18, change 17 to 18 [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L37)
CLOSE ISSUES

**Comment by B0RYS** [comment]
The server currently only supports protocols up to version 11.
