### ISSUE TITLE
this ain't be client-side

### ISSUE THREAD

**Issue by SAV-404** [Megabyte918/MultiOgar-Edited#1466]
i'm using v72 with the latest version of this server, so, to play with skins i should use these `< >`, to make it work, i've just replaced `skinName = (inner == "r") ? this.getRandomSkin() : inner;` with this `skinName = (inner == "r") ? "%" + this.getRandomSkin() : "%" + inner;`.
the problem is the skin keep appearing even when i delete the skin `ex : <shark>` and i use an other nick name but the issue steel won't be fixed.

**Comment by DeadLord1337** [comment]
#1343
#463

**Comment by SAV-404** [comment]
### **can't speak English?...... alright :**
here is a skin with a nickName :
![eryeryeryeryeryery](https://user-images.githubusercontent.com/26459304/42725067-c50c24d2-8775-11e8-84d4-5ce27a613711.PNG)
_result :_
![rgergergergerg](https://user-images.githubusercontent.com/26459304/42725089-fdc2dd02-8775-11e8-8ff5-b6cb91525032.PNG)
and here i'm deleting the skin and using an other nickName:
![fgdfgdfg](https://user-images.githubusercontent.com/26459304/42725096-19518186-8776-11e8-83ff-07dbb044740d.PNG)
_result :_
![rgsdgsdgsdg](https://user-images.githubusercontent.com/26459304/42725087-f55ac4ea-8775-11e8-943b-467b8c33019e.PNG)

### see what i'm talking abt??

**Comment by SAV-404** [comment]
also don't tell me to use an oldest version of this server!

**Comment by B0RYS** [comment]
Why are you using this server, its essentially been discontinued. Just use [OgarII](https://github.com/Luka967/OgarII).

**Comment by SuperOP535** [comment]
OgarII is also a bit dead but it works fine

**Comment by AlexHGaming** [comment]
Why are we using OgarII? That's been apparently discontinued aswell.

**Comment by MastaCoder** [comment]
Ogar -> OgarPlus -> Ogar Unlimited -> MultiOgar -> MultiOgar Edited -> Ogar II -> OgarX.

Come on man get with the program. 🤣

**Comment by AlexHGaming** [comment]
wait where did ogarx come from

**Comment by AlexHGaming** [comment]
nani

**Comment by MastaCoder** [comment]
I don't know, Luka's currently doing the ninth rewrite: https://github.com/Luka967/OgarX

**Comment by AlexHGaming** [comment]
oh

**Comment by Jahseeh** [comment]
client ?

**Comment by freaky767** [comment]
just use ogarii, simple.

**Comment by SAV-404** [comment]
Well...ogarii doesn't work for me...if anyone can close this issue it must be the owner of this project...fix this issue or get the fuck out of here!

**Comment by SAV-404** [comment]
this is so helpful man, thank you so much, closing this issue was the best think u ever done, this guy deserves a trophy, come on guys, give it up for @B0RYS !!

**Comment by B0RYS** [comment]
Sarcasm works as proved :+1:
