### ISSUE TITLE
SoloTricksplit in private server its possible?

### ISSUE THREAD

**Issue by kekko9994** [Megabyte918/MultiOgar-Edited#1467]
SoloTricksplit in private server its possible????? (like gota.io)

**Comment by kekko9994** [comment]
@Agarian You help me with this trick??

**Comment by FirstCodeReviewer** [comment]
Yes it’s possible and you also know it it‘s possible.
You are mentioning gota.io which is basically also a private server.

**Comment by kekko9994** [comment]
you know how to get solotrick?
@FirstCodeReviewer

**Comment by kekko9994** [comment]
i'm need settings from gameserver.ini (i'm trying to get solotrick but i'm failling)

**Comment by kekko9994** [comment]
resolved, CLOSED ISSUES

**Comment by Y4ssine** [comment]
!ؤص$ؤ«#ؤذق4!5؟صسسؤؤصصص؟قءءءففؤ ربيع ذي قفؤف*"
