### ISSUE TITLE
I already try everything but I still can not access to official agar.io client

### ISSUE THREAD

**Issue by Jahseeh** [Megabyte918/MultiOgar-Edited#1469]
I tried using this script ([script](https://github.com/FirstCodeReviewer/Agario-client-with-private-servers/))
i tried changing protocol 17 to 18 ([protocol](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L37))
i tried everything 😢 
 tried everything but i cant play :(

**Comment by Jahseeh** [comment]
plz help

**Comment by Gasvash** [comment]
@Jahseeh 
change the protocol to 18 
but you have to disable agario extensions to make it work

**Comment by Jahseeh** [comment]
then? how i connect to my server? with agar.io?ip=???

**Comment by B0RYS** [comment]
At the moment the server essentially only supports protocols up to version 11 therefore you are unable to connect.

**Comment by Gasvash** [comment]
@Jahseeh @B0RYS 
if it workss in the  agario cliemt , in agario press F12 and add this  in console
core.disableIntegrityChecks(true);core.connect("ws://yourIP:Port")

**Comment by Jahseeh** [comment]
Mmmm, i make it work well...
![image](https://user-images.githubusercontent.com/22761215/43694060-151258f6-98f7-11e8-8a15-3fc1e356c238.png)
but there are som bugs 🤣

**Comment by freaky767** [comment]
you can use OgarII which supports all protocls from 4 to 17.
https://github.com/Luka967/OgarII

**Comment by B0RYS** [comment]
Sorry my mistake @Jahseeh.
