### ISSUE TITLE
Server attempts to recover lag.

### ISSUE THREAD

**Issue by Tyler3D** [Megabyte918/MultiOgar-Edited#147]
If your server is lagging for a while, and then you stop the lag. Ex. Kick bots. Then your server will be in fast motion.
I left my server running overnight with 2000 bots. Then, for 30 minutes or so, the server is running in fast motion.

**Comment by Megabyte918** [comment]
Weird.. I will see what I can do

**Comment by Megabyte918** [comment]
Fixed.
