### ISSUE TITLE
Eject Lag Increased FPS!

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#1474]
Recently i opened a issue #1468 but i dident explained not much about it but when there is so much eject mass on the map game starts to slow down everything.in the old versions of MO-E its dosent happen.

**Comment by SAV-404** [comment]
client sided, so much rendering causes lag, also, why ppl still using the official agario client??

**Comment by Gigabyte918** [comment]
Dude i use cigar client which has no lag at rendering but server starting to slow down when there is eject cells on server

**Comment by Gigabyte918** [comment]
It happens with every client and it is server sided

**Comment by B0RYS** [comment]
@Gigabyte918 Disable `Accelerated 2D canvas` in `chrome://flags`
