### ISSUE TITLE
How to remove a virus?

### ISSUE THREAD

**Issue by Petabyte918** [Megabyte918/MultiOgar-Edited#1476]
Hello, 
Sorry y English not very well...
How to remove a virus?

how can i do remove virus after enough feed?

 
![screenshot_2](https://user-images.githubusercontent.com/42844791/45039990-9145e180-b06d-11e8-8c42-b2e8e8a49bb2.png)

**Comment by MastaCoder** [comment]
wha

**Comment by AlexHGaming** [comment]
k

**Comment by Petabyte918** [comment]
I ask a question here but i solve my problem myself. I edit here for this sorry
