### ISSUE TITLE
discord server

### ISSUE THREAD

**Issue by PowerHead35** [Megabyte918/MultiOgar-Edited#1484]
I know   : 2. **The issue is directly related to the project.** but idk why i can't join the discord server called "Agario Private Server" i leaved and said "I will come back i've learned javascript completly" and when i want to join it i get an error. Did i get banned?

**Comment by vnx123** [comment]
You're not banned, the invite just expired.

**Comment by Luka967** [comment]
^https://discord.gg/66X2ESb

**Comment by B0RYS** [comment]
Updated the link
