### ISSUE TITLE
Collision of ejected cells

### ISSUE THREAD

**Issue by xiaoyu5263** [Megabyte918/MultiOgar-Edited#1488]
How do I set it to no collision?

**Comment by xiaoyu5263** [comment]
Sputting balls without collision....

**Comment by DeadLord1337** [comment]
@xiaoyu5263 You say "How do I set it to no collision?"...

**Comment by xiaoyu5263** [comment]
> @ xiaoyu5263你说“我怎么设置它没有碰撞？”......
Sorry，No details.
How do I do this?
