### ISSUE TITLE
UltraSplit Issue

### ISSUE THREAD

**Issue by SaturnGamer05** [Megabyte918/MultiOgar-Edited#1489]
I can't add the setBoost of Creating Cells from 780 to 400 (In GameServer.js) Can someone help me to make a code to create the ultrasplit?

**Comment by DeadLord1337** [comment]
@SaturnGamer05 Duplicate...

Write in console:
```
change splitVelocity 400
change playerRecombineTime 0
change playerMaxCells 64
```

**Comment by SaturnGamer05** [comment]
**It doesn't work dude... It had a better way but get deleted....**

**Comment by SaturnGamer05** [comment]
**WATCH THE VIDEOOOOO**

**Comment by DeadLord1337** [comment]
I all the same wrote that in the video he makes, even easier.

**Comment by DeadLord1337** [comment]
If you need the result as in the video, use MultiOgar 1.2.69

**Comment by SaturnGamer05** [comment]
;-; 1.2.69 is ezier? Do u have a fixed bugs 1.2.69 version?

**Comment by FirstCodeReviewer** [comment]
@SaturnGamer05 That Video is using Barbosiks Multi Ogar not this fork.

**Comment by SaturnGamer05** [comment]
Oh isn't it? Wow, I thought that was this fork.

**Comment by SaturnGamer05** [comment]
Do we have some solution to do this in this fork (MultiOgar Edited) too?

**Comment by B0RYS** [comment]
We are not here to teach you how to code.
