### ISSUE TITLE
When will a plugin api be added

### ISSUE THREAD

**Issue by MkGamesdev** [Megabyte918/MultiOgar-Edited#1491]
That would be a very nice feature!

**Comment by Luka967** [comment]
MultiOgar-Edited isn't being maintained a lot and there's been no talk about a plugin API. Shameless plug aside, my server implementation https://github.com/Luka967/OgarII has some API for adding console commands, chat commands and gamemodes for now. I'm not maintaining it a lot either.

**Comment by MkGamesdev** [comment]
Merge ogarii and Moe together :)

That would be the perfect server :+1:
