### ISSUE TITLE
Eject,only overlap without collision.

### ISSUE THREAD

**Issue by xiaoyu5263** [Megabyte918/MultiOgar-Edited#1493]
How to achieve?

**Comment by Faris90** [comment]
change mobilePhysics from 0 to 1 in gameserver.ini

**Comment by xiaoyu5263** [comment]
I just want to modify this, not the physics engine.
![default](https://user-images.githubusercontent.com/40060634/51068477-a3f2a780-1659-11e9-9ed7-c6b3d5baa7ff.PNG)
