### ISSUE TITLE
protocol 20

### ISSUE THREAD

**Issue by Faris90** [Megabyte918/MultiOgar-Edited#1494]
will you put protocol 20?

**Comment by Matthew-MK** [comment]
Use OgarII
https://github.com/Luka967/OgarII

**Comment by ealgase** [comment]
> Use OgarII
> https://github.com/Luka967/OgarII

From the README the dev seems kinda aggressive.

**Comment by Luka967** [comment]
it's for a reason. I'm trying to prevent the clog of """issues""" that MultiOgar-Edited has and so far it's working. I'm still answering most questions in the discord and I accepted two pull requests two weeks ago because I was too lazy to do the same myself lmao

**Comment by ealgase** [comment]
I think if you removed the "Pull requests are not welcome." line it would go over a lot better.  That way, when someone asks for a feature, close the issue and say "Send a PR".

**Comment by Luka967** [comment]
the README will have a better tone soon, don't worry
