### ISSUE TITLE
Can someone help me with a Locked Name system?

### ISSUE THREAD

**Issue by FlushDesert22** [Megabyte918/MultiOgar-Edited#1498]
I've been trying to implement a Locked Name system in my server, but it's not working! Please help!

**Comment by hossemThecoder** [comment]
what do u mean locked name ?

**Comment by AlexHGaming** [comment]
I think you've been living under a rock lol @zettabyte918 
and @FlushDesert22 sorry for the late reply; a locked name system requires need of good php & mysql skills for the client side of things, it will take time to make a good secure account system, therefore this is client sided mostly.

**Comment by zettabyte918** [comment]
@AlexHGaming  ok.
![1](https://user-images.githubusercontent.com/18426424/62328405-5fbedb80-b4b3-11e9-975e-558a75800280.PNG)
![2](https://user-images.githubusercontent.com/18426424/62328408-62213580-b4b3-11e9-8e16-2011645be775.PNG)
![3](https://user-images.githubusercontent.com/18426424/62328411-64838f80-b4b3-11e9-98c5-fc614a6d8dca.PNG)
![4](https://user-images.githubusercontent.com/18426424/62328416-664d5300-b4b3-11e9-8d0c-2b8492bbe493.PNG)
![5](https://user-images.githubusercontent.com/18426424/62328421-68afad00-b4b3-11e9-9643-89941c4d3443.PNG)
