### ISSUE TITLE
does not connect to server

### ISSUE THREAD

**Issue by Wr0ngPass** [Megabyte918/MultiOgar-Edited#1499]
I tried to do it on a remote machine, and in the local network.
![image](https://user-images.githubusercontent.com/48523163/56046750-a04fe900-5d4c-11e9-8aca-dd8592aa61ec.png)
![image](https://user-images.githubusercontent.com/48523163/56046770-ac3bab00-5d4c-11e9-878b-39043e0b0475.png)
![image](https://user-images.githubusercontent.com/48523163/56046782-b2318c00-5d4c-11e9-8209-42453e45d47d.png)
![image](https://user-images.githubusercontent.com/48523163/56046800-bf4e7b00-5d4c-11e9-8538-36c2be95977f.png)

**Comment by Luka967** [comment]
You need to use a client such as [Cigar2](https://cigar2.glitch.me/) and connect through it to be able to play.

**Comment by B0RYS** [comment]
LMAO
