### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by B0RYS** [Megabyte918/MultiOgar-Edited#1501]
# Notes 
## Functionality
The server itself is functional and the game is playable without a problem. However there may be some issues. I will keep updating this as i find them. In the meantime use [release 1.6.0](https://github.com/Megabyte918/MultiOgar-Edited/releases/tag/1.6.0).

## General notes
- Gamemodes are still functional.
- All entities are still functional
- Bots and minions still work.
- Chat and its commands still work with the exception of `/login` (needs re-design).
- Player commands are a mess.

## Current bugs
- Default server minions aren't spawning.
- Bots don't leave the game.

## Plans
- Overall plan is to keep refactoring code until it reaches a, for the most part, decent standard.
- User system needs rewriting.

**Comment by Matthew-MK** [comment]
why?

**Comment by B0RYS** [comment]
Im still in the process of converting this to ES6 JS syntax so some bugs are present. Im currently going through each file and optimizing and removing as many bugs as I can. This will take some time. Sorry.

**Comment by Matthew-MK** [comment]
oh ok

**Comment by SaturnGamer05** [comment]
minions didnt work for me when i set it to another number (serverMinion), the bots didnt appear but the id's has been taken by them

**Comment by B0RYS** [comment]
@SaturnGamer05 Thanks for letting me know. I'll take a look at it once I'm done with the commands.

**Comment by MyNameIsDorathy** [comment]
Currently Version 1.6.1 is working great with the cigar2 client, but 1.6.2(Latest) seems to keep disconnecting and is unusable with cigar2.

**Comment by SaturnGamer05** [comment]
Yea it unusable with cigar2

**Comment by SaturnGamer05** [comment]
I got disconnect continuously from the server...

**Comment by B0RYS** [comment]
Reverted `master` to 1.6.1, issue no longer needed.
