### ISSUE TITLE
how do you use console-plus(ive looked at all the issues)

### ISSUE THREAD

**Issue by JE5143** [Megabyte918/MultiOgar-Edited#1503]
ive been trying to use console-plus on heroku and i can´t figure it out. i know how to run it and stuff

agario server URL(NOT the client): **https://agarioserv2.herokuapp.com**
the client: **https://agarioserv.herokuapp.com/www/index.html**
part of the HTML file(console-plus.html): 

```
<script>
      var Host='agarserv2.herokuapp.com';
      var idx=0;
      buffer =[];
      var el = document.getElementById('input');
      el.focus();
      el.onblur = function () { setTimeout(function () { el.focus(); });};
```
the console-plus.json file:
```
{
  "username":"CENSORED",
  "password":"CENSORED",
  "ip":"agarioserv2.herokuapp.com",
  "port":8080
}
```
the console-plus.html client URL: **http://agarioserv.herokuapp.com/run/console-plus.html**
when it was trying to connect with ws:// it couldnt because it isn't supported so i changed it to wss:// in the html file and it connects and sends the data but the console doesnt recieve anything back and i want to know if i set the host and/or the ip wrong for the console

![image](https://user-images.githubusercontent.com/48130949/56662296-a9f11f00-6671-11e9-8283-36d55e9f38e3.png)

**Comment by B0RYS** [comment]
Im not sure if this is an issue with the server, or heroku. I'll need to investigate when the entire server is rewritten.
