### ISSUE TITLE
ini is not listed as a dependency in package.json

### ISSUE THREAD

**Issue by arnavb** [Megabyte918/MultiOgar-Edited#1504]
When I try to run the server after an `npm i`, I get the error module `ini` isn't found. I looked at `src/modules/CommandList.js` and saw that it does `require("ini");`. I then checked `package.json`, which doesn't list it as a dependency. After running an `npm i ini`, the server starts properly.

`ini` should be listed as a dependency in `package.json`, unless I'm missing something here.

I can send a PR to remedy this if you guys want.

**Comment by B0RYS** [comment]
All done, server doesn't use the ini module anymore. I've made the change in my local version but forgot to push it.

**Comment by arnavb** [comment]
Kewl. Thanks for clarifying.

**Comment by SaturnGamer05** [comment]
it needed me to install the ini, then figlet, ws and other things ;-; and it didnt work for cigar2
