### ISSUE TITLE
Can't connect by Cigar2 Client

### ISSUE THREAD

**Issue by SaturnGamer05** [Megabyte918/MultiOgar-Edited#1506]
The lastest version of 1.6.1 was suit with Cigar2, but seemed the lastest 1.6.2 wasn't. It told me to install ini, then figlet, then ws and other things... After installing all of them, the server's console ran well, but I couldnt get into the server, it kept disconnecting continuously.

**Comment by B0RYS** [comment]
Server is still unstable, all these issues will be fixed when i rewrite it.
