### ISSUE TITLE
console-discord send output?

### ISSUE THREAD

**Issue by JE5143** [Megabyte918/MultiOgar-Edited#1508]
I was messing with console-discord.js and noticed it doesn't output the console logs to discord, I really wanted to do this(I KNOW IT SAYS DON'T POST ISSUES WITH OWN CODE) i couldn't figure it out and This is my last hope that you would help me or add the feature to multiogar

**Comment by B0RYS** [comment]
We are not here to help with your own code. Rule still applies.
