### ISSUE TITLE
Critical Bug?

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#154]
Size and Score changes on every motion. Below is a tail of very long log, which ended when changes stops by time.
Cell ,this time, quietly stay in the corner. When I slightly move Cell(no any eating), log begins a new long round of changes. It's a shit :(

To reproduce - just insert console.log into PlayerTracker.updateMass. Run on MO "from the box" with single client.

pID 4
size: number 32.498946473522345
score: number 1056.1815218888705
pID 4
size: number 32.46643126130577
score: number 1054.0691588450927
pID 4
size: number 32.4339485805753
score: number 1051.9610205274023
pID 4
size: number 32.401498398783154
score: number 1049.8570984863472
pID 4
size: number 32.36908068341414
score: number 1047.7573842893744
pID 4
size: number 32.33669540198559
score: number 1045.6618695207958
pID 4
size: number 32.304342522047314
score: number 1043.5705457817542
pID 4
size: number 32.27202201118161
score: number 1041.4834046901904
pID 4
size: number 32.239733837003214
score: number 1039.40043788081
pID 4
size: number 32.20747796715925
score: number 1037.3216370050486
pID 4
size: number 32.17525436932922
score: number 1035.2469937310389
pID 4
size: number 32.14306301122494
score: number 1033.1764997435769
pID 4
size: number 32.11090386059056
score: number 1031.11014674409
pID 4
size: number 32.078776885202494
score: number 1029.0479264506018
pID 4
size: number 32.046682052869386
score: number 1026.9898305977008
pID 4
size: number 32.014619331432094
score: number 1024.9358509365056
pID 4
size: number 32
score: number 1024  <<< changes stopped at this point

**Comment by Megabyte918** [comment]
Why is this a problem?

**Comment by Gimmo** [comment]
Because it is direct parazitic server load. It's generated by circular references in many places.

**Comment by Megabyte918** [comment]
What do you mean? It's supposed to be generated that way.

**Comment by Gimmo** [comment]
What way? I do nothing, but score is changes ? As I understand, it should change when some events (collisions) happened. As one collision -> one change.

**Comment by Megabyte918** [comment]
That's not how it is in vanilla Agar.io, your supposed to decay whether or not you have moved or not.

**Comment by Gimmo** [comment]
It's not decay by time. It's decay by recursion. When Cell stay quiet, it stops and Cell stay intact until it try to move.

**Comment by Megabyte918** [comment]
I don't get what your trying to say.

**Comment by Gimmo** [comment]
If you want to change mass by time, you will change it by system tick.
You say "supposed to decay whether or not you have moved or not"
When Cell stops in the corner, it stop changes.
You can see exponencial changes of score in the log.  It's typical for recursion. Can you point me the place, where this recursion programmed?

**Comment by Megabyte918** [comment]
Mass IS changed by system time or every "tick" because the updateMassDecay function is called every tick in the server's mainLoop. When a cell stops in a corner, it's not supposed to affect that because that's not how it is in vanilla. It still changes mass or "decays" as long as the cell is alive.
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L659-L662
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L682-L703

**Comment by Gimmo** [comment]
Thank you.
Please look the new log. Last value is a timestamp. As you can see, interval doesn't look like a second, but score changes. This is what I'm talk about.

score: number 1064.0739639526134 1480906513595
pID 1
score: number 1061.9458160247082 1480906514741
pID 1
score: number 1059.8219243926587 1480906514831
pID 1
score: number 1057.7022805438737 1480906514935
pID 1
score: number 1055.5868759827858 1480906515008
pID 1
score: number 1053.4757022308202 1480906516179
pID 1
score: number 1051.3687508263583 1480906516267
pID 1
score: number 1049.2660133247055 1480906516365
pID 1
score: number 1047.167481298056 1480906516447
pID 1
score: number 1045.0731463354596 1480906517619
pID 1
score: number 1042.9830000427887 1480906517726
pID 1
score: number 1040.8970340427031 1480906517833
pID 1
score: number 1038.8152399746175 1480906517888
pID 1
score: number 1036.737609494668 1480906519057
pID 1
score: number 1034.6641342756786 1480906519148
pID 1
score: number 1032.5948060071273 1480906519245
pID 1
score: number 1030.5296163951127 1480906519337
pID 1
score: number 1028.4685571623224 1480906520499
pID 1
score: number 1026.4116200479975 1480906520597
pID 1
score: number 1024.3587968079016 1480906520688
pID 1
score: number 1024 1480906520768   << cell stops

**Comment by Megabyte918** [comment]
Ok then, glad I could help 👍

**Comment by Megabyte918** [comment]
What did you do with the code?

**Comment by Gimmo** [comment]
PlayerTracker.prototype.updateMass = function () {
    var totalSize = 0;
    var totalScore = 0;
    for (var i = 0; i < this.cells.length; i++) {
        var node = this.cells[i];
        totalSize += node._size;
        totalScore += node._sizeSquared;
    }
    if (totalSize == 0) {
        //do not change scale for spectators or not in game players
        this._score = 0;
    } else {
        this._score = totalScore;
        this._scale = Math.pow(Math.min(64 / totalSize, 1), 0.4);
    }
    this.isMassChanged = false;
console.log("pID "+ this.pID);                                                                          // <<<<<<<<
console.log("score: "+typeof( totalScore)+" "+ totalScore+" "+Date.now());  // <<<<<<<<

};
----------------------------------------------------------------------------------------------
No any sign more. Rest of code is "Out the Box".

**Comment by Megabyte918** [comment]
I meant with the code for mass decay

**Comment by Gimmo** [comment]
Read. 

I make each experiment with clear instance of MultiOgar.

**Comment by Megabyte918** [comment]
I've had no problem with lag whatsoever. I can leave it running overnight and it would be fine the next day.

**Comment by Gimmo** [comment]
It's not an answer. Server should work intact looong period under heavy load. People requires autoRestart because server is unstable. The error, which my logs shows, can be the reason of problem. It can't be fixed by simple prosthesis.

**Comment by Gimmo** [comment]
There is an error in 
     if (((this.tickCounter + 3) & (25)) == 0) {
            // **once** per second
            this.updateMassDecay();
    }
Should be 
     if (((this.tickCounter + 3) & (25))) {
            // once per second
            this.updateMassDecay();
    }
This remove execution of  .updateMassDecay from circular call, because circular call has loop length about 100ms,  but recursion still stay in place, and when Cell eat the Food we have old result:

....................... skipped
score: number 1053.5071365954618 1480963565399
pID 2
score: number 1051.4001223222708 1480963565445
pID 2
score: number 1049.2973220776262 1480963565491
pID 2
score: number 1047.1987274334706 1480963565535
pID 2
score: number 1045.1043299786036 1480963565588
pID 2
score: number 1043.0141213186464 1480963565640
pID 2
score: number 1040.9280930760092 1480963565694
pID 2
score: number 1038.846236889857 1480963565715
pID 2
score: number 1036.7685444160775 1480963565806
pID 2
score: number 1034.6950073272453 1480963565896
pID 2
score: number 1032.6256173125907 1480963565995
pID 2
score: number 1030.5603660779655 1480963566074
pID 2
score: number 1028.4992453458094 1480963566121
pID 2
score: number 1026.442246855118 1480963566230
pID 2
score: number 1024.3893623614074 1480963566232
pID 2
score: number 1024 1480963566263

**Comment by Gimmo** [comment]
There is an typo in call 

     if (((this.tickCounter + 3) & 25)==0) {
         // once per second
         this.updateMassDecay();
     }

should be     
     if (((this.tickCounter + 3) **%** 25)==0) {
         // once per second
         this.updateMassDecay();
     }

This remove repetitive execution of  updateMassDecay. Now it happened once per second  as required.

score: number 2553.5598891000936 1480966072055
pID 1
score: number 2548.4527693218934 1480966073178
pID 1
score: number 2543.35586378325 1480966074304
pID 1
score: number 2538.269152055683 1480966075429
pID 1
score: number 2533.192613751572 1480966076561
pID 1
score: number 2528.1262285240687 1480966077679
pID 1
score: number 2523.0699760670204 1480966078802
pID 1
score: number 2518.0238361148868 1480966079928
pID 1
score: number 2512.987788442657 1480966081054
pID 1
score: number 2507.9618128657717 1480966082179
pID 1
score: number 2502.9458892400403 1480966083304
pID 1
score: number 2497.939997461561 1480966084429

**Comment by Gimmo** [comment]
Explanation:
```

for (var i = 0;  i < 100;i++){console.log(i,"->",i & 25)}
 0 "->" 0
 1 "->" 1
 2 "->" 0
 3 "->" 1
 4 "->" 0
 5 "->" 1
 6 "->" 0
 7 "->" 1
 8 "->" 8
 9 "->" 9
 10 "->" 8
 11 "->" 9
 12 "->" 8
 13 "->" 9
 14 "->" 8
 15 "->" 9
 16 "->" 16
 17 "->" 17
 18 "->" 16
 19 "->" 17
 20 "->" 16
 21 "->" 17
 22 "->" 16
 23 "->" 17
 24 "->" 24
 25 "->" 25
 26 "->" 24
 27 "->" 25
 28 "->" 24
 29 "->" 25
 30 "->" 24
 31 "->" 25
 32 "->" 0
 33 "->" 1
 34 "->" 0
 35 "->" 1
 36 "->" 0
 37 "->" 1
 38 "->" 0
 39 "->" 1
 40 "->" 8
 41 "->" 9
 42 "->" 8
 43 "->" 9
 44 "->" 8
 45 "->" 9
 46 "->" 8
 47 "->" 9
 48 "->" 16
 49 "->" 17
 50 "->" 16
 51 "->" 17
 52 "->" 16
 53 "->" 17
 54 "->" 16
 55 "->" 17
 56 "->" 24
 57 "->" 25
 58 "->" 24
 59 "->" 25
 60 "->" 24
 61 "->" 25
 62 "->" 24
 63 "->" 25
 64 "->" 0
 65 "->" 1
 66 "->" 0
 67 "->" 1
 68 "->" 0
 69 "->" 1
 70 "->" 0
 71 "->" 1
 72 "->" 8
 73 "->" 9
 74 "->" 8
 75 "->" 9
 76 "->" 8
 77 "->" 9
 78 "->" 8
 79 "->" 9
 80 "->" 16
 81 "->" 17
 82 "->" 16
 83 "->" 17
 84 "->" 16
 85 "->" 17
 86 "->" 16
 87 "->" 17
 88 "->" 24
 89 "->" 25
 90 "->" 24
 91 "->" 25
 92 "->" 24
 93 "->" 25
 94 "->" 24
 95 "->" 25
 96 "->" 0
 97 "->" 1
 98 "->" 0
 99 "->" 1
```

**Comment by Megabyte918** [comment]
Interesting.. I will revert back to the old way functions were called using tickCounter as an interval immediately. Thanks for letting me know
