### ISSUE TITLE
STUPID BOTS

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#155]
bots always avoid with BIG distanse, and always split(spawn and split to food or player)
FIX IT

**Comment by Tyler3D** [comment]
Or maybe your bad at the game. Their actually pretty smart. They can presplit and reverse tricksplit you.

**Comment by PrinceDark9243** [comment]
NO @t11tanYT is Right the isnt split when they are big.

**Comment by Fantasy-Agario** [comment]
They do split when they're big XD

**Comment by Megabyte918** [comment]
Fixed
