### ISSUE TITLE
i cant eat

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#156]
i cant eat food bigger than me , please fix that.

**Comment by PrinceDark9243** [comment]
yes you cant able to eat food when you are smaller than food lol!

**Comment by CalvinDKL** [comment]
lol, but i believe someone made a issue on this.....

**Comment by Megabyte918** [comment]
@PsycoYT You are not supposed to be able to eat cells bigger than you. Do not make any more issues on the subject.
