### ISSUE TITLE
Cant see skin w/ CustomSkin By Megabyte

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#157]
![image](https://cloud.githubusercontent.com/assets/20871314/20921431/0195e6d6-bbdf-11e6-9177-1b67c49c91a9.png)
Help Not Working!!
I have the script on
![image](https://cloud.githubusercontent.com/assets/20871314/20921438/0beb2e16-bbdf-11e6-9f52-bece911a92c4.png)
@Megabyte918 Fix

**Comment by Megabyte918** [comment]
I can see my skins just fine. Can you post the link here?

**Comment by MastaCoder** [comment]
Maybe also post of the photo of the console for any errors?

**Comment by Megabyte918** [comment]
I'm gong to close this for now...
