### ISSUE TITLE
Console Commands

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#158]
Kick 
not working properly - immediately after kick user reborns with a new ID.
What should be:: something like after client's cell is eaten ;  gameplay on client side stay in place, client's cell disappear, client reborn only after new  command "play" issued.  Kickbot, meanwhile, working a right way.

Mass
cannot set mass less then 9. When I use console for experiments/debugging it is an annoying limitation. It's a console, not a port for wild users. Also client change displayed score when I increase mass by console, and doesn't change - on decrease, while console [ playerlist], displays score in a right way.

**Comment by Megabyte918** [comment]
> not working properly - immediately after kick user reborns with a new ID.

That's what its supposed to be right? It kicks them from the server like it's supposed to. 

> What should be:: something like after client's cell is eaten ; gameplay on client side stay in place, client's cell disappear, client reborn only after new command "play" issued. Kickbot, meanwhile, working a right way.

The same thing could be replicated using the ban and unban commands.

> cannot set mass less then 9.

Fixed.

> client change displayed score when I increase mass by console, and doesn't change - on decrease

I cannot help you with that, as it is a client related issue.

**Comment by Gimmo** [comment]
Kick - reject one time. If cell reborn, no-one will know about kick. Nothing changes. Cell **should not reborn automatically**, but connection must stay alive.
Ban - reject forever.
It's common practice for all games and chats.

**Comment by Megabyte918** [comment]
I will make it so you must reload the page in order to play again.

Mass: Which other clients have you tested it on? That feature was removed a long time ago, you used to be able to press escape and it would reset your score to what you currently had, but now if your mass has decreased, your score will no longer change unless you have surpassed your previous score.

**Comment by Gimmo** [comment]
It's wrong way - connection must stay alive and cell should reborn on "play" button. Exactly as when you are eaten under overlay after press escape. 

About mass - yes, seems I was wrong: it't not a bug, it's feature. Score indicator always shows your maximal mass in current game, where the mass indicator(embedded) shous current value of mass. Sorry...

**Comment by Megabyte918** [comment]
@Gimmo would you like me to make it so they must reload the page in order to play again?

**Comment by MastaCoder** [comment]
@Megabyte918 But that won't really favor the people that do have multiple servers and do follow the way that Miniclip does it.

**Comment by Gimmo** [comment]
I badly need the game can be finished normal way - before reconnection. Your proposal is acceptable for kick, but it will be the same discussion about finishing game: I should ask you about the way to finish the game the way I describe. So, easy way is to find solution for kick the way I wrote before, it will resolve two problems. :)

**Comment by Megabyte918** [comment]
I have added a new command, it should disable the player from spawning until you either redo the command on them, or they reload the page.

**Comment by Gimmo** [comment]
Thanks, I'll check how it works.

**Comment by Gimmo** [comment]
Damn language barrier.
I'm sorry for so much disturbance. Kick working just perfect, if simple removed line
CommandList.js :: 396  `socket.close(1000, "Kicked from server");`
Play in this case not needed and should be removed.
Much appreciate your help!

**Comment by Megabyte918** [comment]
@Gimmo No problem :)
