### ISSUE TITLE
Minions to all

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#16]
make a "gamemode" that gives minions to all like alis.io

**Comment by Jhair2015** [comment]
@RelTakeover  That's where they are @Megabyte918 - @Fantasy-Agario , They work great for making that gameplay! :)

**Comment by Megabyte918** [comment]
@RelTakeover that sounds cool, but I think it would be better having configs for it rather than a whole gamemode. And the only way this would work is if the "only 1 person can have minions" bug is fixed, which it isn't yet, so just be patient and maybe after it's fixed I'll work on it :)

**Comment by Fantasy-Agario** [comment]
@Megabyte918 I could possibly write a gamemode if u like :) 
+ The Files Minion Loader & Minion Socket were missing from the Repo so I added them back
