### ISSUE TITLE
new EPIC gamemode idea

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#163]
TEAMS2
Gamemode, like teams, but if you eated by cell in green team you spawn in green team (and winner is team, which captured all players.
and new settings for this gamemode and original teams
TeamsCount = (count of teams)
i think is good idea

**Comment by ZfsrGhS953** [comment]
I think this gamemode should be called "Green Team"

**Comment by PsycoYT** [comment]
@ZfsrGhS953  pleaseee help me , i need your help please....

**Comment by PrinceDark9243** [comment]
Thats a Good idea but i wish this could be Reality but @Megabyte918 *DONT WANT TO MAKE THIS PROJECT OGAR UL!*

**Comment by XtremePlayzCODE** [comment]
just like diep.io tag mode, right?

**Comment by AlexandriteErikParacelsus** [comment]
No

**Comment by XtremePlayzCODE** [comment]
@AlexandriteErikParacelsus, or should I say bleach drinker from your profile pic, basically what he is describing is tag mode in diep, but only the green can be taggers, or am I just missing something

**Comment by Megabyte918** [comment]
@t11tanYT I could do something like that but I don't think we need an entire gamemode dedicated to it, maybe I'll make it like a config or something.

**Comment by firelightning13** [comment]
@AlexandriteErikParacelsus It looks like it

**Comment by t11tanYT** [comment]
@XtremePlayzCODE  yes

**Comment by AlexandriteErikParacelsus** [comment]
@firelightning13, I know, I just randomly dropped a "no" in the issue. And xtremecode act all triggered

**Comment by Megabyte918** [comment]
As far as I know, there is no way to let the server know which player killed them last after they have spawned again. I also suspect adding such a thing would decrease performance if there are a lot of bots or players constantly spawning after being eaten. Which means you cannot set the player's color after they spawned to the player's color that killed them. Also isn't this how teams mode already is? The more one team eats of the opposite team, the less of them there will be. Which will eventually lead to a team "winning" the gamemode. Also the TeamsCount config will not work for most clients as it would cause bugs with the leaderboard if there is more than 3. I am closing this for now.

**Comment by XtremePlayzCODE** [comment]
@AlexandriteErikParacelsus I'm not triggered, I am stating my opinion. It's 2016 dude, no men get triggered, only furious feminists

**Comment by MastaCoder** [comment]
@XtremePlayzCODE Wrong. I saw Andrew get triggered.

**Comment by XtremePlayzCODE** [comment]
Man Andrew, stop gettin triggered while callin people triggered. I am severely triggered

**Comment by AlexandriteErikParacelsus** [comment]
@XtremePlayzCODE So man do triggered

**Comment by XtremePlayzCODE** [comment]
@AlexandriteErikParacelsus Yes men does triggerness and do has properly grammars.
