### ISSUE TITLE
Change virus color?

### ISSUE THREAD

**Issue by Vvrrick** [Megabyte918/MultiOgar-Edited#165]
Is there code to change virus color? And what do you mean by "soften splits"

**Comment by Fantasy-Agario** [comment]
Change the rgb color here : https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js#L8

**Comment by Megabyte918** [comment]
@Vvrrick soften splits: meaning they aren't as hard as they were, the cells separate more elegantly instead of snappily
