### ISSUE TITLE
Console Commands 2

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#166]
When player is divided into many parts, after issue "kill" or "kick" console commands, player remains in playerlist. Only one element(part) removed from user screen (client)  :(

Player can be removed only after repetitive ( for every part ) command.

**Comment by Megabyte918** [comment]
This does not happen with me. I split 16 and killed myself and it said I was dead or not playing.

**Comment by Gimmo** [comment]
Strange. I change initial size to 300 and split cell by virus. I check it few times, but I'll check one more time the way you do.

**Comment by Gimmo** [comment]
I try one more time, more carefully.
Kill kills all and report number of removed cells. 
But kick removes only half of children . I.e. I need a few iteration to remove it completely.
In any occasion, when cell is fully destroyed it remains in playerlist, but marked as "DEAD OR NOT PLAYING"  

NOTE: in my server I don't drop connection inside kick command.

**Comment by Gimmo** [comment]
Originl kick (by Barbosik) glue together ll childs of plyer's sell .

**Comment by Megabyte918** [comment]
Fixed.
