### ISSUE TITLE
changing cell color depending skin

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#169]
@Megabyte918 

I've read NatsuTheGreat that said that :

> You can make a switch(){} statement, but you have to know the RGB of the color that you want.

SimonOrJ  said that :

> I think you should know where to go from this. It involves the usage of PlayerTracker.setColor().

`PLEASE HELP ME !!`

Is similar to the color of the minions,when it detects a minion it changes the color to gray

**Comment by Megabyte918** [comment]
@RelTakeover The server cannot predict what skin you are going to input and what color will match that skin, so your better off just setting your color manually through command to match the skin that you have.
