### ISSUE TITLE
Some Bug!

### ISSUE THREAD

**Issue by Chancerst** [Megabyte918/MultiOgar-Edited#17]
First of all, Thank you for working to continue this project :D 

![default](https://cloud.githubusercontent.com/assets/19770308/20049032/deab0986-a503-11e6-8c65-8410148c1c9e.PNG)
The latest Version had some bug.

**Comment by PrinceDark9243** [comment]
Dude You are Running Ogar Ul!

**Comment by Fantasy-Agario** [comment]
Its fixed now :)
