### ISSUE TITLE
Question on code

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#170]
Can't find the point, where I can see event that Cell is completely eaten and see its pid. 

Also I need the point (event) where Cell disabled/destroyed by lost connection and see its id and size.

Help please.

**Comment by Megabyte918** [comment]
@Gimmo 
Cell is completely eaten: [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L917)
See it's pID: [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/CommandList.js#L760)
Cell is destroyed by lost connection: [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L245)
See cell's size: listed [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/CommandList.js#L799), by calling [getScore](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L166-L169) fucntion, which also calls [updateMass](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L176-L192) function.

**Comment by Gimmo** [comment]
@Megabyte918 
Thank you very much, but this is not exactly what I need. Bad english, as always.

Completely eaten cell:  I meant cell and all it's children + pID : I meant to get pID as property in point of removing/destroy.  In the line you point I get separate signal for every part of my cell has been eaten.

The same for lost connection - needed pID and total size or total mass in the point of decision.  

Other words - I try to get message on console "connection lost - pID 2 - size 123" and "user eaten - pID 2"
and get them only once.

**Comment by Megabyte918** [comment]
@Gimmo `cell.isRemoved = true;` in resolveCollision means that something has eaten that specific cell, in your case you should use `this.isRemoved` in PlayerTracker because it defines a player and all of their cells, not just one. And if you want to get the messages in console for more than one player you should be doing it around [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/CommandList.js#L776-L784) area in CommandList.

**Comment by Gimmo** [comment]
`this.isRemoved = true;` in PlayerTracker is set only on handle disconnection.  It's ok. 
But where can I get signal for all eaten for this user? Where is the point, after which command to `"exit without disconnection because all user's Cells die"`  is sent to client? 
One message for one event is o.k. , this is exactly what I need.

**Comment by Gimmo** [comment]
I'll try to glue....

**Comment by Megabyte918** [comment]
this.isRemoved is not only used to mark players as disconnected, but it is also used in many places to mark a player as dead or not playing. If using that does not work for you, try adding a check to see if the player has any cells in game or not.

**Comment by Gimmo** [comment]
I make everything I need. Thank you one more time.
In GameServer.checkCellCollision

`if (cell.owner) {.
     if(cell.owner.cells.length===1)
console.log("user pID "+cell.owner.pID+"completely eaten");
}`
