### ISSUE TITLE
You are no working, or you never are working with rush mode? (gamemode)

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#171]
Im have this dude, or this is the same gamemode to lastmn stanting?

**Comment by AlexandriteErikParacelsus** [comment]
Why are you doing this? @AlexByte918

**Comment by Megabyte918** [comment]
@AlexByte918 Yes it is still being worked on, @Tyler3D started working on it when the original issue was made, I also helped with it a bit, but development has been slowed due to both of us being busy with other things.
