### ISSUE TITLE
60 FPS

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#172]
please

**Comment by ZfsrGhS953** [comment]
Node.js is too slow for that. For that, you'll need at least C++, or maybe even Assembly if you want to host a big server.

**Comment by NameYT** [comment]
@ZfsrGhS953 Do you know how to run the server up to 25gb?

**Comment by ZfsrGhS953** [comment]
Does your server reach 1.4GB RAM usage and crash?

**Comment by Gimmo** [comment]
@ZfsrGhS953  Do you mean - the server has memory leaks? Wher from '1.4GB RAM' is coming.

**Comment by ZfsrGhS953** [comment]
@Gimmo It's the default RAM limit in node.js
