### ISSUE TITLE
Issues , please help me.

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#174]
1)How to make the reaction faster to the mouse?Like agar.io
2)What happens if I edit this number:

`var timeStep = 40;`

3)What happens if I edit this number:

 ` if (dt > 120) this.timeStamp = ts - timeStep;`

4)What happens if I edit this var:

` var ts = Date.now();`

5)How to up the fps?

**Comment by Megabyte918** [comment]
Reactions with the mouse are equal to that of Agar.io, and I suggest not editing those settings if you don't know what your doing.
