### ISSUE TITLE
Skin Script

### ISSUE THREAD

**Issue by PheoniXAgario** [Megabyte918/MultiOgar-Edited#175]
Hi Megabyte,

I'm using your skin script, and the skin only shows up when i put in regular (keyboard) characters. When i try putting in something like ᑭᕼΣ𐍈Ɲ𐌆✘⚔⚔一ϺƬ♜ the skin doesn't show. Any fix?

-PheoniX

**Comment by Megabyte918** [comment]
I will look into it.

**Comment by NameYT** [comment]
@Megabyte918 @PheoniXAgario Same Problem...

**Comment by NameYT** [comment]
@Megabyte918 How did raga.pw made there own game mode and work using the skin :3

**Comment by AlexandriteErikParacelsus** [comment]
@NameYT Is it agar client clone or agario client?

**Comment by NameYT** [comment]
@AlexandriteErikParacelsus Agario cilent

**Comment by NameYT** [comment]
@Megabyte918 FIX THIS PLZ

**Comment by PheoniXAgario** [comment]
Guys, @Megabyte918 is looking into it, stop pestering him with redundant messages

**Comment by AlexandriteErikParacelsus** [comment]
@PheoniXAgario are you sure?

**Comment by NameYT** [comment]
@Megabyte918 Fix This problem pls

**Comment by Megabyte918** [comment]
I legit don't know how to fix this :/ 
The extension doesn't seem to modify anything having to do with the name, all it does is get the value of what you put in by using `document.getElementById(\'nick\').value`, so maybe it's just a client sided problem? I'm not sure.

**Comment by Fantasy-Agario** [comment]
Guys i will try making an extension that has ERT controls and lets u use your own skin :)

**Comment by MastaCoder** [comment]
@Megabyte918 Can you link me to the extension they are talking about so I can look at it?

**Comment by Jhair2015** [comment]
@MastaCoder  Hey, is this script : **https://raw.githubusercontent.com/Megabyte918/MultiOgar-Edited/master/src/scripts/CustomSkins.js**

**Comment by AlexByte918** [comment]
Solution. Click right in box of nickname. browse in elements MaxLenght. already as puted in 15, double click and change to 999,

**Comment by MastaCoder** [comment]
@AlexByte918 That's not the problem. Skins don't show up with fancy characters, not length.

**Comment by 5p1Ky** [comment]
Same problem for me, I can't use custom skin using my nick (愛✈⊶ΛτнσM༅⎇ᵇᶺₑ) ... I can only see it when puting a keyboard name :(

**Comment by 5p1Ky** [comment]
Oh I just tested, lettre by letter, to write my name, and I just found out that this caracter: "Λ" isn't supported... All others caracters that are in my name are working perfectly using my skin ^^ I think I have to change this letter in my nickname xD

**Comment by Knift** [comment]
Can you try this: delete random skins, and try to add custom skins like in ogar unlimited master (if you dont know how, go to YT).

**Comment by Knift** [comment]
Because we cant see random skins on ourself.

**Comment by Knift** [comment]
Only on our m8

**Comment by Luka967** [comment]
Server can't send images.

**Comment by Luka967** [comment]
I mean that it needs protocol modifications

**Comment by Knift** [comment]
Oh ok i understand

**Comment by Knift** [comment]
But maybe it can work with any extension

**Comment by Luka967** [comment]
Sure it would with if it supports custom skins.

**Comment by FlareYT** [comment]
@NameYT , raga made their own Client , so they were able to add Skins and their Gamemodes.

Greetings Flare !

**Comment by AlexHGaming** [comment]
@Megabyte918 @FantasyIsBae @AlexandriteErikParacelsus Close? Well it is something client sided

**Comment by SAVAGE2001** [comment]
hey guys i made a script of skins...you can find all the skins and you can add if you want..i just i wanted to share with you guys...i know this is noob but i'll be batter in the futer
[skins.txt](https://github.com/Megabyte918/MultiOgar-Edited/files/847551/skins.txt)

**Comment by Jhair2015** [comment]
@SAVAGE2001 is fine

**Comment by SAVAGE2001** [comment]
@Jhair2015 thank you  😊 😊
