### ISSUE TITLE
Fix This

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#176]
![captura de pantalla 100](https://cloud.githubusercontent.com/assets/18153674/21064976/fccc519a-be2b-11e6-90af-22b2207ff03f.png)
![captura de pantalla 102](https://cloud.githubusercontent.com/assets/18153674/21064978/fcf3fd58-be2b-11e6-92d8-e166c002467c.png)

**Comment by Megabyte918** [comment]
Fixed

**Comment by Jhair2015** [comment]
@Megabyte918  THANKS
