### ISSUE TITLE
HOW TO MAKE A MERGE SERVER?

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#177]

**Comment by Jhair2015** [comment]
Like alis.io

> playerMinSize = 64
playerMaxSize = 1500
playerMinSplitSize = 80
playerStartSize = 250
playerMaxCells = 100
playerSpeed = 1
playerDecayRate = .002
playerRecombineTime = 0
playerMaxNickLength = 15
playerDisconnectTime = 60

**Comment by AlexandriteErikParacelsus** [comment]
@Jhair2015 maxCells is 64 not 100

**Comment by Jhair2015** [comment]
@AlexandriteErikParacelsus  Oh, well I'll give you 100: p
