### ISSUE TITLE
Issue server crash.

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#178]
Hello! so i am getting an issue were my server crashes.

Here is what it says
![error](https://cloud.githubusercontent.com/assets/23283642/21074441/889b253e-bef9-11e6-9a45-5e3cb16253f8.png)

And is there a way i can make it automatically start if the server crashes??

**Comment by MastaCoder** [comment]
If it's Linux, use the restart script:

```bash
#/bin/bash
clear

while true
do
  # Insert your tasks here
  done
```

**Comment by CalvinDKL** [comment]
Masta, sorry i dont really understand the code. So i have no idea on how to use it.
Can you explain please?

**Comment by MastaCoder** [comment]
Put that into a .sh file. Replace the comment in the do - done loop of how your server runs. "node index.js" or whatever. Put the .sh file in the directory of where it's going to run, go back to it and run it by typing in sh name.sh

**Comment by CalvinDKL** [comment]
Wait so i need to run my server through that file??

**Comment by CalvinDKL** [comment]
And i dont need a restart script, i need a script that opens the server if it crashes.

**Comment by CalvinDKL** [comment]
Wait nvm, does it automatically start if the server crashes?? 
xD

**Comment by MastaCoder** [comment]
Yeah

**Comment by Gimmo** [comment]
Looks like noone knows that it's simple error in code.
@Megabyte918  - please add check `typeof split !== undefined` in GameServer:1571

**Comment by CalvinDKL** [comment]
Masta, it still doesnt work :/

and error comes up when i run it with this    sh runnocrash.sh

![66334a76ba90307f5d040c88b65d0466](https://cloud.githubusercontent.com/assets/23283642/21075583/1211d59e-bf16-11e6-9956-aed80ab846a1.png)


and this is code i put in
`#/bin/bash
clear

while true
do
  node index.js
  done`

**Comment by CalvinDKL** [comment]
And i put the .sh file in the src folder by the index.js

**Comment by MastaCoder** [comment]
I don't know why it does that sometimes. Are you sure you put in tabs?

**Comment by CalvinDKL** [comment]
in tabs? on my vps i just put it in the src folder where the index.js is and ran it.

**Comment by MastaCoder** [comment]
No I meant indents in the sh file.

**Comment by Megabyte918** [comment]
@CalvinDKL It looks like you are using an outdated version, this bug was fixed long ago.

**Comment by CalvinDKL** [comment]
Maybe edited the gamserver.js :)
I added minions protection

**Comment by Megabyte918** [comment]
Then it is a problem with the code you've inserted, I cannot help you because I do not know what you modified.

**Comment by fayizan** [comment]
@Megabyte918  How to autorestart server..?

**Comment by Megabyte918** [comment]
@fayizan the same question was asked here: https://github.com/Megabyte918/MultiOgar-Edited/issues/76
