### ISSUE TITLE
Splits

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#179]
Can they make the splits more like agario?

Even in gota.io they are more like agar.io!!(more than multiogar)

Of what they really ought to be concerned, is in the form of divisions, which are the same as agar.io.
Because even if they say they are the same, they really ARE NOT

There is something called "splitrunning realtime", it consists of giving spaces with your team without stopping, this can be done in agar.io, in gota.io, in cigar and ogarUL, but in multiogar you can not, multigame spaces Are faster, very straight and unarmed, please do not close this topic, I want the opinion of the people that play multiogar and agar.io or gota.io

THANKS.

**Comment by Jhair2015** [comment]
@PsycoYT  I do splitrunning well with MultihOgar Edit

**Comment by RelTakeover** [comment]
not same splitrunning that agar.io @Jhair2015

**Comment by AlexandriteErikParacelsus** [comment]
gota splitting is not accurate as multiogar edited

**Comment by Megabyte918** [comment]
It looks vanilla to me, I've compared the splitting to spectate in party mode and I don't think there is any difference.

**Comment by Vvrrick** [comment]
@Megabyte918 I think you should make the splits smoother. The vanilla physics are chunky. Not sure if you understand what I mean, but if you have the desire to, you should make the splits smoother like ogar-unlimited. Not as soft but smooth. Btw is there any way to replace the server split physics with the physics of agarplus? I have a working version of a+ that uses the old protocol that only works for private servers but the code is still obfuscated

**Comment by ZfsrGhS953** [comment]
OgarUL-like splitting:
In [these lines](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L873-L874) change "1" in them to "0.2"

**Comment by Megabyte918** [comment]
This is splitrunning I captured in vanilla spectate in party mode:
https://streamable.com/ozv1

This is splitrunning on MultiOgar-Edited:
https://streamable.com/j39d

**Comment by ZfsrGhS953** [comment]
They look almost the same.

**Comment by Megabyte918** [comment]
That's what I thought.. I don't know what the problem with it is

**Comment by ZfsrGhS953** [comment]
They want splitting to be like Ogar Unlimited

**Comment by ZfsrGhS953** [comment]
This is my attempt at making gota.io-like splitting:
```javascript
    var m1 = ~~c.cell1._mass * (Math.min(Math.min(c.cell1.getAge(this.tickCounter),c.cell2.getAge(this.tickCounter)),1000)/1000 / c.m);
    var m2 = ~~c.cell2._mass * (Math.min(Math.min(c.cell1.getAge(this.tickCounter),c.cell2.getAge(this.tickCounter)),1000)/1000 / c.m);
```
You'll also have to make cells be able to collide before 14 ticks have passed for it to work correctly (I don't think you'll have any problems with that)

**Comment by Megabyte918** [comment]
@ZfsrGhS953 nice!. While your at it, do you know how to do anything about the cell switching when you doublesplit? I have no idea how to get rid of it...

Also, the splitting in Gota.io looks too slow/snappy if you ask me. If it was on the vanilla client then it would be more noticable.

**Comment by ZfsrGhS953** [comment]
Try using the OgarUL splitting code, but with 10 iterations. Because with OgarUL splitting cells move slower when colliding, they shouldn't pass through themselves. And 10 iterations are needed for fast splitting.

**Comment by PsycoYT** [comment]
Although it does look odd, its divisions are really good.

**Comment by PsycoYT** [comment]
you can see my own splitrunning realtime in ''OGARUL''

https://www.youtube.com/watch?v=qcR1F4Au1zo

**Comment by PsycoYT** [comment]
Because you do not make changes in the spaces And make them more similar to gota.io,

OR EVEN IF TO IMPROVE THEM, in vanilla it is easier it makes realtime for its client, since it facilitates it,

But in a normal client, spaces look more upright, more unarmed and faster

I think this is a problem that happens to everyone


Not because I have the same value of division means that it is the same as vanilla, because the code of fact is neither similar

thanks

**Comment by PsycoYT** [comment]
At least you could copy OGARUL, copy does not mean not know or ruin, it means to get good ideas from others, nothing more, that's why people always prefer OGARUL, because it has better physics than multiOgar , 
And I'm telling you that I own agario.city and ogar.pw

**Comment by Vvrrick** [comment]
@Megabyte918 yes but doesn't it have code to change the physics of splitting and overall smoothness?

**Comment by AlexandriteErikParacelsus** [comment]
What was the problem that killed Ogarul? Lag. We can't just put ogarul's code in

**Comment by Megabyte918** [comment]
@PsycoYT I cannot help you with that... If the splitting looks different on different clients then that's just how it is. It is designed to be played primarily on the Agar.io client, so splitrunning looks vanilla. If you want to splitrun as if your using OgarUL, do what @ZfsrGhS953 said to make the splits like that.

@Vvrrick No it does not, it just looks different.

I am closing this.

**Comment by Megabyte918** [comment]
I've taken another look at the splitting from vanilla and I've compared it with MultiOgar-Edited.

The difference wasn't really noticeable until I started experimenting with the collision restore ticks and used an extension so I could see the difference more clearly, then I saw what was wrong. 

Reducing the ticks by 1 in recent updates seemed to do the trick, the splitting looks as if there is no difference with vanilla. The softness, the distance, the snappiness or "chunkiness", the splitrunning, etc. I've also done the same with virus explosions and popsplit success rates.

**Comment by freaky767** [comment]
How to i get collisions when i put in that code?
Because i dont have any collisions

**Comment by Megabyte918** [comment]
What

**Comment by freaky767** [comment]
when i put the gota split code into the gameserver.js
and then split, the cells do not collide.

**Comment by freaky767** [comment]
get it?

**Comment by Megabyte918** [comment]
@freaky767 
> You'll also have to make cells be able to collide before 14 ticks have passed for it to work correctly (I don't think you'll have any problems with that)

**Comment by freaky767** [comment]
how do i do that?

**Comment by freaky767** [comment]
or is it possible to do it?

**Comment by Agarian** [comment]
@ZfsrGhS953
