### ISSUE TITLE
Create skin changer

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#180]
Please add skin changer feature

**Comment by MastaCoder** [comment]
NO. NO OGARUL STOP IT. YOU STOP RIGHT THERE.

**Comment by AlexandriteErikParacelsus** [comment]
![b n v khong co tieu d](https://cloud.githubusercontent.com/assets/17348976/21078467/140feba6-bf25-11e6-9041-ba11ff278ba2.png)
@MastaCoder

**Comment by Megabyte918** [comment]
nah.

**Comment by Jhair2015** [comment]
@PsycoYT  Use this script ;-; :  http://pastebin.com/raw/gcFCQCYx

have skin changuer...
