### ISSUE TITLE
How to Set Login System On MGar.io on MultiOgarEdited!

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#186]
How to set a admin like this
/login SambyYT (WORKS ON COMPUTER IP)

**Comment by NameYT** [comment]
@Megabyte918

**Comment by Megabyte918** [comment]
Use the /login player command.

**Comment by systemroot** [comment]
@Megabyte918 i'll like to add a countdown at the end of leaderboard 
is possible? if yes can you please give some help? not for all, example just teach me how to add a text on leaderboard example "Hello" then i'll work with other part

**Comment by Megabyte918** [comment]
@systemroot try using what the board command uses to change the leaderboard. And you can get a model of what a working countdown looks like from Ogar's tournament gamemode: https://github.com/OgarProject/Ogar/blob/master/src/gamemodes/Tournament.js

**Comment by NameYT** [comment]
@Megabyte918 /login player doesn't work how to add accounts like that per ip?

**Comment by Megabyte918** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/enum/userRoles.json

**Comment by NameYT** [comment]
@Megabyte918 LOGIN FAILED :(

**Comment by NameYT** [comment]
@Megabyte918 NVM I DID IT ANYWAY BUT I CANT DO /minion on the chat :( [please help

**Comment by Megabyte918** [comment]
@NameYT That command does not exist

**Comment by MastaCoder** [comment]
@NameYT Are you from the OgarUL community? If so, please go back to it. Or better, go to OpenAgar and spam some good issues there :)

**Comment by RasyiidWho** [comment]
lol :V

**Comment by Jhair2015** [comment]
@RasyiidWho :V
