### ISSUE TITLE
unlock names per ip

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#187]
i want block names like [admin] - [mod] ,Except for some ip, so that only admins can have them

**Comment by Megabyte918** [comment]
@PsycoYT insert this code into the `setNickname` function in PacketHandler.js:
<pre>
var UserRoleEnum = require("./enum/UserRoleEnum");
if (this.socket.playerTracker.userRole !== UserRoleEnum.ADMIN && this.gameServer.checkBadWord(name))  {
    skin = null;
    name = "Hi there!";
}
</pre>
Then add [admin] to the list of bad words. What the code above does is allow people with the user role of "admin" to bypass the name filter, therefore you are the only one who can use [admin]. If you want the same thing to apply for moderators, change `UserRoleEnum.ADMIN` to `UserRoleEnum.MODER`. 

Or if you want both admins and moders to bypass the filter you can do this:
<pre>
var UserRoleEnum = require("./enum/UserRoleEnum");
if (this.socket.playerTracker.userRole !== UserRoleEnum.ADMIN && 
    this.socket.playerTracker.userRole !== UserRoleEnum.MODER && 
    this.gameServer.checkBadWord(name))  {
    skin = null;
    name = "Hi there!";
}
</pre>
I haven't tested this yet, but theres no reason why it shouldn't work.

**Comment by PsycoYT** [comment]
that code isnt work
