### ISSUE TITLE
ADMIN FEATURES

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#188]
- specific color of admin
- more commands
- To report in chat that an admin has entered
- TAG [ADMIN] IN THE CHAT

more ideas?

**Comment by CalvinDKL** [comment]
I am willing to pay, since the youtubers that play on my server want this i want this too xD
Like royal kept asking me and Risky and bang.

Its only chat colours!

**Comment by PsycoYT** [comment]
YES PLEASE ADD !!

**Comment by MastaCoder** [comment]
2 things.

1. User levels are already implemented into the system. There is no reason to add it. This is supposed to be a base, you can add everything else by learning and working with the code.
2. You'll need work on your client as well for it to really work as well. (Since IP's change)

There is no point in this. Not all people want it, this is more of a base. Everything else, you'll have to add.

**Comment by Megabyte918** [comment]
@MastaCoder is right, people with custom clients should use the base to their advantage to do as they please with chats and such. Adding it into the server itself would not be such a good idea, considering how many different clients people use.

>specific color of admin

you can just set your color using the color command

>more commands

I could probably consider this, anything from CommandList and PlayerCommand does not affect performance so I could add as many commands as I want. But which commands would you like to see?

>To report in chat that an admin has entered

What I said earlier

>TAG [ADMIN] IN THE CHAT

What I said earlier

**Comment by PsycoYT** [comment]
main commands like /mass - /kick - /ban - /playerlist - /minion - /tp - /kill

**Comment by MastaCoder** [comment]
How would mass - kick - etc work if you don't know player ID's? You can't fit a whole playerlist inside a chat of course. We need to find another way. Of course I can add a packet to Cigar to do things like this. (Show more information), but I'll need to get them from @Megabyte918 on how he will add the code to the server first.
