### ISSUE TITLE
Is Multiogar multithreaded?

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#189]
Hello!
i had around 300 players on my server earlier today, the server was using 1gb of ram and i had 5 more available, is that because of nodejs? Because i have noted that multiogar runs much better and is less laggy than ogarul.

Would Open Agar be a solution maybe?

**Comment by Megabyte918** [comment]
@CalvinDKL MultiOgar is not multithreaded. 
Quote from Barbosik: 
>multithreading requires to use thread synchronization objects and features, such as critical sections, semaphores, mutexes, memory bariers, spin locks and other things. Without these things, you cannot utilize multithreading effectively. I'm not sure, but as I know node.js doesn't support it. Also, multithreading makes code very complicated and it's easy to add bugs.

If you want to make it so your server allocates more RAM for one process refer to this issue, it was answered here: https://github.com/Megabyte918/MultiOgar-Edited/issues/167
