### ISSUE TITLE
Make the minions control E and R? Like Ogar UL

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#19]
Is it possible?

**Comment by PrinceDark9243** [comment]
Dude Vanilla Agar.io Does not support E and R key or any other key it only support W,Space and Q!

**CLOSE THIS ISSUE**

**Comment by Fantasy-Agario** [comment]
Like @PrinceDark9243 said,
Vanilla agario client doesn't support the keys E and R , although we could make an extension that allows you to use those keys , it would be hard .

**Comment by Megabyte918** [comment]
@NameYT added

**Comment by NameYT** [comment]
@Megabyte918 @Fantasy-Agario Make me the extension for the Minions that woudl be great i will make vids to promote this best project :)
