### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by kareemman00** [Megabyte918/MultiOgar-Edited#190]
Can I Just Ask U To Make A Multi Names For Minions Please ??

**Comment by AlexandriteErikParacelsus** [comment]
Depends if it gonna effect the performance of the server. We don't want this project to be like OgarUL. Too much lag, the project collapsed on itself.

**Comment by AlexByte918** [comment]
Im want that same

**Comment by kareemman00** [comment]
No Problem I Know UnderStanded

**Comment by kareemman00** [comment]
# Closed

**Comment by Megabyte918** [comment]
You can already have multi-names for minions, just do `minion [id] [amount] [name] `
