### ISSUE TITLE
Big Thanks

### ISSUE THREAD

**Issue by kareemman00** [Megabyte918/MultiOgar-Edited#191]
I Would Say To U A BIG BIG THANKS For Letting Me To Continue Making My Service FuryBots
I Success To Use The Orignal Skins Shop, Skins And Skins Bots Too 
Soon The Exp Point [For Now Not Counted]
# BIG BIG THANKS FOR MegaByte And Fantasy Agario And All Who Helped For This Super Perfect Server 
And Here is Some Pics From My Progress : http://ge.tt/9Bh67rh2

Regards ~FuryBots ;3

**Comment by Jhair2015** [comment]
@kareemman00  lmao, hot to connect miy facebook account to MultiOgar o.O

**Comment by AlexByte918** [comment]
GOOD :D plz continue working in this

**Comment by AlexandriteErikParacelsus** [comment]
Thank you for your support, megabyte would be happy to see this. Keep doing what are you doing and stay awesome

**Comment by AlexByte918** [comment]
LOL. how you see yourseelf the skin? why no miniclip as eliminated skins from private servers?

**Comment by NameYT** [comment]
OMG HOW HELP ME PLEASE?

**Comment by NameYT** [comment]
@kareemman00

**Comment by kareemman00** [comment]
Guys Just An Ex That Make The Game Think Thats Ur Server Is An Official One Then It Lets U To Use The Official Skins Its Easy And Very Sample :smiley:

**Comment by kareemman00** [comment]
And Thanks For Ur Sweet Words :heart:

**Comment by kareemman00** [comment]
Thank U For Ur Sweet Words @AlexandriteErikParacelsus @NameYT @AlexByte918 
@Jhair2015 Its An Sample Thing To Do Just Make The Game Thinks That's My Server Is An Offical One 
Just Sample :smiley:

**Comment by Firekix** [comment]
@kareemman00 Cant Beleive U done this bro!!!!!!!!!!!!!............
So the Client thinks urs private server is Official one!!!!!(Still Cant Beleive)....

**Comment by Fantasy-Agario** [comment]
@kareemman00 If u have time please give me your skype or anything i can contact u through :P

**Comment by PrinceDark9243** [comment]
Hey http://ge.tt/9Bh67rh2 isnt opening!

**Comment by PrinceDark9243** [comment]
@kareemman00 dont leak this server because if get this info the will try to secure the client!

**Comment by kareemman00** [comment]
facebook https://www.facebook.com/elshbshb.da3 

@PrinceDark9243  When It Done

**Comment by Jhair2015** [comment]
@kareemman00 I have sent you request =), Please accept = DE
My account: Jimmy Morales.

**Comment by systemroot** [comment]
lol is this possible? 

btw @kareemman00 accept if u want *dope.boy66*

**Comment by AlexHGaming** [comment]
You didn't make that server because in the second picture, it shows at the bottom a 'kinda' watermark saying: Multi-Ogar Edited Master. Which means you didn't make it all and just changed things around

**Comment by Megabyte918** [comment]
Thank you so much @kareemman00 <3 
made my day!

**Comment by Jhair2015** [comment]
@Megabyte918 Could be Inspect element lol (F12), Although I do not believe it very possible, anyway I hope it's real and I can get it = D


@AlexHGaming  He said it is a MultiOgar server, but official server!

**Comment by AlexByte918** [comment]
@Jhair2015 You are stupid? Really its Multi ogar, See A little down, say Multi-OgarEdited Master (VERSION)
In miniclip official sv no its that.

**Comment by PrinceDark9243** [comment]
LOL

**Comment by PrinceDark9243** [comment]
WHAT THE SAMPLES ARE REMOVED!

**Comment by kareemman00** [comment]
Guys i Did Saied its An Offical One But The Ext but an new game mode the game thinks its an officall one then let u use the officall skins server but when open the ext only when open it

**Comment by kareemman00** [comment]
and its now puplic but the site is down for now when the site is up i will share with u the link for now let me open my pc and i will send u some pics

**Comment by kareemman00** [comment]
guys its real i swear its like raga's one but with some improves the same script for the skins server leak

**Comment by Megabyte918** [comment]
I'm going to close this for now.. @kareemman00 thanks for being so nice :)

**Comment by NameYT** [comment]
@kareemman00 Send me to i sended a request..... Gian Carlo Sambayan Accept it and give me the server download plz Thanks
