### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by kareemman00** [Megabyte918/MultiOgar-Edited#192]
I Opened The Ports 5595,2458 on my vps and i checked it on can u see me and I Sayed Its Opened But When Open The Server I Got This 
=== Started 2016-12-13T10-09-03-937 ===
[INFO ][10:09:03] 0 IP ban records loaded.
[WARN ][10:09:03] User account "Local Administrator" disabled
[WARN ][10:09:03] User account "Local Moderator" disabled
[WARN ][10:09:03] User account "Local User" disabled
[INFO ][10:09:03] 0 user records loaded.
[INFO ][10:09:03] 419 bad words loaded
[INFO ][10:09:03] [1m[32mMultiOgar-Edited 1.4.2[37m - An open source multi-protocol ogar server[0m
[INFO ][10:09:03] WebSocket: ws
[ERROR][10:09:04] Stats Server: listen EACCES 0.0.0.0:2458
[ERROR][10:09:04] WebSocket: EACCES - listen EACCES 50.3.86.152:5595
[ERROR][10:09:04] Please make sure you are running Ogar with root privileges.
[DEBUG][10:09:04] process.exit(1)
=== Shutdown 2016-12-13T10-09-04-091 ===
 # Please Help Please

**Comment by MastaCoder** [comment]
That port can't be used. Are you running it with root privileges on an open port? Quite surprised how someone working on Facebook login to work with this can't figure out that he is under an incorrect port.

**Comment by Megabyte918** [comment]
@kareemman00 make sure you are running with root privaleges, those errors are only caused by permission issues.
