### ISSUE TITLE
how to change splits like ogarul

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#193]
title

**Comment by Jhair2015** [comment]
@PsycoYT  Changue This: 

>     var m1 = ~~c.cell1._mass * (1 / c.m) - 0.01;
>     var m2 = ~~c.cell2._mass * (1 / c.m) - 0.01;

Change to 0.2 or go try it your way!

In this location: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L874-L875

**Comment by Megabyte918** [comment]
Yes, refer to this comment: https://github.com/Megabyte918/MultiOgar-Edited/issues/179#issuecomment-266272129

**Comment by PsycoYT** [comment]
@Megabyte918  incorrect , this it affects the doublesplit...

**Comment by Megabyte918** [comment]
It is supposed to.

**Comment by PsycoYT** [comment]
There must be a way to change them without affecting the doubleplit

**Comment by PsycoYT** [comment]
Or you can, transform the code so that it can be edited with a variable, it would be pretty good

**Comment by PsycoYT** [comment]
re-open this issue ..

**Comment by ZfsrGhS953** [comment]
Changing it without affecting doublesplits will require to add a check to the code that finds 4 cells in a row and speed up splitting speed if it has been found, which will massively reduce performance.

**Comment by PsycoYT** [comment]
@ZfsrGhS953  @Megabyte918  help me -_- ,There must be a way to change them without affecting the doubleplit

**Comment by MastaCoder** [comment]
> which will massively reduce performance.

@PsycoYT this isn't OgarUL.
