### ISSUE TITLE
Reconnection

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#196]
How is reconnection supposed to work?

When I disconnect player (close browser tab or refresh browser) player stay in player list with status "disconnected".
When I open client in a new tab or refresh browser, server generate a new player with new ID.
When I do this 10 times, I get 10 hanged users in waiting timeout, which I cannot reconnect.
[![cons.png](https://s24.postimg.org/60mag1okl/cons.png)](https://postimg.org/image/cr2rphbq9/)
What the sense of it and how can I reconnect ? 

Problem persists in all clients. The only difference is agar.io client - using it I can hang no more then 2 instances, if I repeat disconnections, older users disappear from player list. 

As I think, we have mix of two tasks:
1. "Keep connection" timeout - while player is not active.
2. Reconnection timeout - while we store user data for reconnection, which **doesn't work at all**.

As reconnection doesn't work - player list should be cleaned from dead records immidiately when socket connection is lost.  So-so...

**Comment by Megabyte918** [comment]
@Gimmo What clients have you tested this on? I've tried each client from the list in the README and the [DISCONNECTED] message dissapeared after two instances on all of them.

**Comment by Gimmo** [comment]
Cigar and Alis. 
Server on Deb7  VM.
MultiOgar - last version "from the box".
Check one more time right now. F5->Play button on client ->F5.......skip...... pl on console

**Comment by Megabyte918** [comment]
@Gimmo I also checked with said clients, I could not reproduce it. Also the server clears everything regarding the player once they've disconnected.

**Comment by Gimmo** [comment]
@Megabyte918 
`the server clears everything regarding the player once they've disconnected`
Sorry to say, but no. I found this problem while working on other things ( track client object life to modify code) . Objects stay in memory and erased at the same time when erased from list. My own problem was on multiply erase of object and, as a consequence, multiply callback.   Server really have hanging objects in timeout loops.
I check clean (fresh install) server just to be sure the reason of problem not in my code.

**Comment by Megabyte918** [comment]
@Gimmo Fixed the leaderboard thing, turns out they get removed in vanilla too. Also what do you want me to do about the timeout? That's how its supposed to work, the player's cells stay where they were once they disconnected until the timeout ends, then it is removed.

**Comment by Gimmo** [comment]
@Megabyte918
Re: Timeout: 
It's a security hole. It's easy to make script, which will reconnect fast enough to cause server overhead.

Player object should be destroyed at disconnection. If you like to see disconnected player in Player List - there is nothing wrong to keep this as record in Player List, but player object definitely should be removed from memory.

**Comment by Megabyte918** [comment]
@Gimmo It clears the player by removing all of its cells, and it can only do that by waiting for playerDisconnectTime to pass.

**Comment by Gimmo** [comment]
@Megabyte918  one cell by one tick, right?

**Comment by Megabyte918** [comment]
@Gimmo 
Socket is destroyed on disconnect [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L280-L290). It then removes the player from `this.socketCount`, and then marks them as "disconnected" by using `ws.isConnected = false;`

If the `isConnected` variable is false, playertracker waits for disconnect time to pass [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L234-L254), after it has passes, it removes all of their cells, then marks them as "removed" by using `this.isRemoved = true;`

if `this.isRemoved = true;` from playertracker, the following things happen:
- update is skipped [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L266) and [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L317)
- spectate target is cleared [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L498-L501)
- they are cleared from the list of client's [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L424-L427)

And that's pretty much it.

**Comment by Gimmo** [comment]
Why we can't simply do something like `this.player = null` on disconnection ?  All operations you point are good for game dynamics, but not necessarily for total destroy. Where I'm wrong?

**Comment by Megabyte918** [comment]
@Gimmo Where do you suggest I put that variable? There's no point because `isConnected` and `isRemoved` are basically the same thing. Same thing with `this.socket.remoteAddress == null`

**Comment by Gimmo** [comment]
@Megabyte918  I'll try to think about it.  :)

**Comment by Megabyte918** [comment]
It already does this though

**Comment by Gimmo** [comment]
It does this **after timeout** at  PlayerTracker about line 254. During `if (this.cells.length == 0 || dt >= this.gameServer.config.playerDisconnectTime)` timeout time object hangs in memory.
I place callback here and get it with zeroed size and mass after timeout. From every instance of disconnected player.

**Comment by Megabyte918** [comment]
ok

**Comment by Gimmo** [comment]
Timeout 0 did the trick :)
