### ISSUE TITLE
Server Lag

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#198]
Hello!
So my server is lagging, a lot.
it isnt because i dont have enough ram or anything like that.

The Lag:
https://gyazo.com/404446f5117077730cde43e2884d2a96

Status of the server (at the time when it was lagging):
Connected players: 60/128
Players: 60 - Bots: 0
Server has been running for 462 minutes
Current memory usage: 124.2/148 mb
Current game mode: Free For All
Current update time: 32.229 [ms]  (good)

**Comment by PsycoYT** [comment]
i can help u , give me your server

**Comment by ZfsrGhS953** [comment]
http://agarup.us/

**Comment by Megabyte918** [comment]
@CalvinDKL A few questions:
- How big were the players on your server?
- What are you using to host?
- How much food/viruses/ejected mass was on the map at the time?

**Comment by MastaCoder** [comment]
Current update time: 32.229 [ms] (good)

That is a lot. Answer @Megabyte918 questions 👍

**Comment by JaraLowell** [comment]
Find:

>         // Move moving cells
>         for (var i = 0; i < this.movingNodes.length;) {
>             cell1 = this.movingNodes[i];
>             if (cell1.isRemoved)
>                 continue;
>             this.moveCell(cell1);
>             this.updateNodeQuad(cell1);
>             if (!cell1.isMoving)
>                 this.movingNodes.splice(i, 1);
>             else i++;
>         }

and replace with:

>          // Move moving cells
>          for (var i = 0, len = this.movingNodes.length; i < len; ) {
>              if(this.movingNodes[i]) {
>                  var cell1 = this.movingNodes[i];
>                  if (!cell1.isRemoved) {
>                      this.moveCell(cell1);
>                      this.updateNodeQuad(cell1);
>                      if (!cell1.isMoving)
>                          this.movingNodes.splice(i, 1);
>                  }
>              }
>              i++;
>          }

As that seems be where most lag right now comes from 😠

**Comment by ZfsrGhS953** [comment]
Most lag seems to be coming from this.quadTree.find, when I disable it for minions I can run up to 30k without lag (but minions can't eat anything), and when it's enabled for minions, I can only run 5k without lag.

**Comment by Megabyte918** [comment]
@JaraLowell Nice find, I'm going to commit it if you don't mind :)
@CalvinDKL Could the lag have been caused by #225?

**Comment by JaraLowell** [comment]
Weird enough found a other one that for some .. well unknown for me reason causes tick lag as well. 

Live 733:
var speed = ~~Math.sqrt(cell1.boostDistance * cell1.boostDistance / 100);

Apparently using ~~  there lags the tick a lot,. 
so change it to
var speed = Math.sqrt(cell1.boostDistance * cell1.boostDistance / 100);
and poof,. 

ps... seriously.. start using real memory use display and not some weird "reserved used" lol
var rss = parseInt((process.memoryUsage().rss / 1024 ).toFixed(0));

Hugs,
Jara

**Comment by CalvinDKL** [comment]
The lag could have been because of my domain, atm i am using 4 cores with
10gigs of ram without any lag.
So im almost sure that the domain was the issue.

**Comment by CalvinDKL** [comment]
OR it might have been because i only had 2 cores when i opened this issue.
