### ISSUE TITLE
Update skin and name in-game

### ISSUE THREAD

**Issue by nuclearc** [Megabyte918/MultiOgar-Edited#201]
Title ^^

**Comment by MastaCoder** [comment]
Can't you already do that with the name command?

**Comment by nuclearc** [comment]
no its changing only new cell's name

**Comment by Megabyte918** [comment]
@nuclearc Add the following checks into the joinGame function in PlayerTracker:
<pre>
if (name != name) name = name;
if (skin != skin) skin = skin;
</pre>

**Comment by nuclearc** [comment]
i mean update in-game while playing (like old agar.io skin rotator)

**Comment by MastaCoder** [comment]
@nuclearc If you're wondering why it won't update, it's because skins are cached. The client caches skins on cells. So if you switch in game, it won't show until you split or pop.
