### ISSUE TITLE
 Why do not you combine?

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#203]
Why not merge cigar with MultiOGAR-edited?
More features?
More options?

A specialized client for multi-edited?

A customer specialized in Multiogar-Edited? Specialize cigar in Multiogar for greater optimization, fluidity and gameplay?

why not?

Please do not close the topic, this would be a big step and a big change.

@Megabyte918

**Comment by ZfsrGhS953** [comment]
Oh god... Four issues in half an hour. Was it hard for you to put everything in one issue?

**Comment by Megabyte918** [comment]
Yes please. It would make things a lot more simple. Also it is designed to be used with any client, so I'm not going to have it just stick to one.

**Comment by MastaCoder** [comment]
There isn't much of a reason for doing that either. Both projects are supposed to be a base for starting a private server website, not tools to have it ready to be uploaded. 

Cigar is meant to be at a base, anything extra, should be added by yourself. This is to make sure everything works with anything, not just 1.

**Comment by AlexandriteErikParacelsus** [comment]
o gawd
