### ISSUE TITLE
Why? DECREASE

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#204]
if i decrease that value the splits will bug , and the cells they get weird

>    if (cell.getAge(this.tickCounter) < 14 || check.getAge(this.tickCounter) < 14) {

Instead if I modify the ticks splits in original multiOGAR, that does not happen

**Comment by Megabyte918** [comment]
@PsycoYT Do you know what that is?

**Comment by PsycoYT** [comment]
Ok then .. where do I modify the splits ticks?

**Comment by Megabyte918** [comment]
These physics are much different than the original MultiOgar's. The current settings including the collision restore ticks are made specifically to fit the other physics of the server. In other words, it is not meant to be modified.
