### ISSUE TITLE
not working | MINIOS PER IP

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#205]
> @agariotips If you want minions by a special IP, you can do something like this in GameServer.js on this line: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L361
> 
> if (this.config.serverMinions > 0 && ws.remoteAddress == "insert your ip here") {
> So for example if I wanted minions to only be spawned in with me when I connect using my localhost IP address I would do:
> 
> if (this.config.serverMinions > 0 && ws.remoteAddress == "127.0.0.1") {

this code not working fine for me

**Comment by Megabyte918** [comment]
@PsycoYT 
The code for that has moved here: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L314
It works just fine for me.

**Comment by OmarioYT** [comment]
Doesnt work for me... Nothing happens when i add it inside the gameserver.js and add my ip ;-;
