### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#206]
Because in agar.io there is no lag, even though having all the options activated? , either graphics or anything..

Why not improve the performance of multiplayer? MultiOgar is good, but for example, petridish is 5 times better in performance

What is the maximum performance that can reach Multiogar?

Where can I increase server fps?

Where can I make the server nodes faster?

**Comment by Megabyte918** [comment]
>Because in agar.io there is no lag, even though having all the options activated? , either graphics or anything..
Why not improve the performance of multiplayer? MultiOgar is good, but for example, petridish is 5 times better in performance

Client sided.

> What is the maximum performance that can reach Multiogar?

I don't know, it depends on a lot of things.

> Where can I increase server fps?

You can do something similar to that [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L521).

> Where can I make the server nodes faster?

I don't get it.
