### ISSUE TITLE
connect with ogario and quantity of minions

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#207]
1)how to connect with ogario?
2)with this code `if (this.config.serverMinions > 0 && ws.remoteAddress == "insert your ip here") {`

How do I
Specify the number of minions with that code?

**Comment by MastaCoder** [comment]
these questions..

**Comment by Megabyte918** [comment]
1. Can you provide the link to the script?
2. You can already connect with that code, just insert it into the place where I told you.
3. What do you mean by "fix"

**Comment by PsycoYT** [comment]
How do I
Specify the number of minions with that code?

**Comment by Megabyte918** [comment]
use the serverMinions config

**Comment by NameYT** [comment]
@Megabyte918 I cant do /login ADMIN Is there anyway to do /login samby??

**Comment by Megabyte918** [comment]
@NameYT https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/enum/userRoles.json#L4
