### ISSUE TITLE
@MegaByte @MineMooreALT How is this possible!! 

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#209]
https://www.youtube.com/watch?v=ByTez0bTy2U

**Comment by NameYT** [comment]
@Megabyte918 @MineMooreALT

**Comment by AlexByte918** [comment]
@NameYT What is possible?

**Comment by NameYT** [comment]
@AlexByte918 Look at the Video... He can use Pellet mode over 1000 Bots....

**Comment by AlexByte918** [comment]
@NameYT Omg, you right

**Comment by nuclearc** [comment]
whats strange there? lol

**Comment by NameYT** [comment]
@Megabyte918 How can he use pellet mode in 1000 bots :(

**Comment by Megabyte918** [comment]
@NameYT remove the following line of code from playertracker: 
`if (this.gameServer.clients.length > 800 && this.isMi) return;`

But I must warn you first, it will massively reduce performance with minions, pellet mode on or off. I suggest not touching it.

**Comment by AlexByte918** [comment]
@NameYT A bots (someone) no feed pellets, but why its llittle the mass in the map, so the bots no have a direction where go, so go with you
