### ISSUE TITLE
CLIENTS

### ISSUE THREAD

**Issue by Fantasy-Agario** [Megabyte918/MultiOgar-Edited#21]
# Clients 

I Have put together a list some of clients **Compatible** with **MultiOgar-Edited**
## All urls connect to `:127.0.0.1:443`

* [Astr.io](astr.io/?ip=127.0.0.1:443) | A really smooth client we also use this one for testing
* [Agar.io](agar.io/?ip=127.0.0.1:443) | We do not recommend the OG client as it causes lag with minions
* [OgarUL](http://old.ogarul.io/?ip=127.0.0.1:443) | Ogar-Unlimited client, also has support for new minion controls :) (Pretty smooth and basic) 
* [Alis.io](http://alis.io/?ip=127.0.0.1:443) | Really smooth and lightweight also is good for > 500 minions)
* [Ogar-Remastered](http://ogar-remastered.esy.es/) | My own client that i use for testing [My Version of Ogar](https://github.com/FantasyArts/Ogar-Remastered) mainly smooth and it starts slows down at 1000 minions :)

## I will make a wiki soon and add these to it :D

**Comment by Jhair2015** [comment]
Alis.io is available with console :/ and not found minimap!

**Comment by Fantasy-Agario** [comment]
What do u mean 'with console' :D

**Comment by Jhair2015** [comment]
@Fantasy-Agario  Lol ha ha I did not work to put alis.io/?ip=miip:port

Now if they work, sorry for the inconvenience :)

**Comment by Jhair2015** [comment]
@Fantasy-Agario  One more question, it is possible to host my server without needing my router or codeanywhere, nitrous.io, etc.

I want to make one 24/7 with servegame.com or http://bit.ly/2ePc5UZ

**Comment by Fantasy-Agario** [comment]
u still need to port forward

**Comment by Jhair2015** [comment]
@Fantasy-Agario I try to do it, but my router is not compatible, I have seen many tutorials, etc and nothing! :/

**Comment by Fantasy-Agario** [comment]
yh same here

**Comment by Fantasy-Agario** [comment]
# ALSO

Ip = 127.0.0.1
port = 433
weird part separating them = ':' 
game alis.io
ip + weird part separating them + port = alis.io/?ip=127.0.0.1:443
443

**Comment by Jhair2015** [comment]
Mmm ... I will see my router again and send captures! :) thanks for your attention: D

**Comment by AlexandriteErikParacelsus** [comment]
@Fantasy-Agario I having trouble to connecting to alis.io client

**Comment by Fantasy-Agario** [comment]
Yh , np i'm here to help :)

**Comment by Jhair2015** [comment]
:D

**Comment by Gimmo** [comment]
Ogar-Remastered not working for me with different servers. Shows only grid. WTF?

**Comment by Megabyte918** [comment]
@Fantasy-Agario Do we still need this issue? There's already a clients section in the readme, I could add your client to it if you'd like

**Comment by Fantasy-Agario** [comment]
No we don't need this and if you could add it to the readme that would be great :)

**Comment by Megabyte918** [comment]
@Fantasy-Agario I added it, but I do not know the protocol version because I am unable to connect to it for some reason. Can you tell me the protocol version your client uses so I can add it?

**Comment by Vvrrick** [comment]
Hi I'm new, I was wondering if it's possible to revert back to the old agar physics? Like how mgar.io has. I think it uses multiogar, but I can tell it has the old agar physics because it's a hell of a lot smoother.

**Comment by Megabyte918** [comment]
@Vvrrick it's not *impossible*, but it would require a ton of work. It would require a rewriting of the entire collision engine, aswell as the move engine

**Comment by Vvrrick** [comment]
@Megabyte918 couldn't I take something (not sure what) from an old private server like ogarserv? Or is it more complicated than that?

**Comment by Megabyte918** [comment]
@Vvrrick it is much, much more complicated im afraid

**Comment by Vvrrick** [comment]
@Megabyte918 do you plan to make performance a bit better in future updates?

**Comment by Megabyte918** [comment]
@Vvrrick Of course! when this project first started the performance was 2x slower than the original MultiOgar, but due to my recent optimizations it is now equal. I will not stop until performance has greatly surpassed the original MultiOgar's, and I'm getting pretty close.

**Comment by Vvrrick** [comment]
@Megabyte918 is there a way to edit the split speed? Ex:split same distance as a regular split, but slower or faster?

**Comment by Megabyte918** [comment]
@Vvrrick Yes there is. 
For split speed: Edit the speed variable [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Cell.js#L101)
For split distance: Edit the value of 780 [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L793)
For collision-restoration time: Edit the two values of 15 [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L1049)

**Comment by Vvrrick** [comment]
@Megabyte918 I turned on the server tracker so people could join my server (u-bot.ml). Every person that joins gets 10 42 mass bots, but even though I turn on the server scramble to 3, it doesn't scramble at all. Only the minimap. I've also tried 2. The reason I'm bringing this up is because people use extensions to gain their own minions which really lag and slow down the server. When they leave, the server goes in fast motion, so I have to restart it. I've disabled bots and turned on server scramble, then when I play, the cords are scrambled, then i give myself bots. They work. Could you make it scramble when bots are enabled for everyone?

**Comment by Megabyte918** [comment]
@Vvrrick Try it with these settings:
serverIpLimit = 2
serverMinionIgnoreTime = 5
serverMinionThreshold = 5
serverMinionInterval = 500
serverScrambleLevel = 3
playerBotGrow = 0

**Comment by Vvrrick** [comment]
If by host you mean vps? None, I just have server tracker enabled and start the server

**Comment by Vvrrick** [comment]
@Megabyte918 is there a way to change the player's w accuracy? Like when you w in the private server, it goes more straight towards your cursor if that makes sense. In normal agar, when you eject mass, the w doesn't go exactly where your cursor is, just in that general area. In the private server, the area the mass ejects is closer to the cursor. How would I change that if possible?

**Comment by Megabyte918** [comment]
@Vvrrick try editing somewhere around these lines in GameServer:
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L1144-L1154

**Comment by Vvrrick** [comment]
@Megabyte918 sorry for bothering you again lol, but you know how when you split into more pieces, the transition from seeing a smaller area to seeing a larger area is there? Is there anyway to remove the transition to make it like the old agar transition?

**Comment by Megabyte918** [comment]
@Vvrrick You can change the scale of the viewbox in these places:
github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L178-L182
github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L186-L189
github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L281-L289
Either those or its client-related.
