### ISSUE TITLE
@Megabyte Why is this so better while playing with 1500 bots no lag :(

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#210]
https://github.com/G047/MultiOgar-Minions

NO LAG

@Megabyte918 Please fix it :) we want smooth

**Comment by PsycoYT** [comment]
yes i have lag in multiogar-edited with much bots

**Comment by Gimmo** [comment]
@NameYT  just because there is no food in G047. 
Recent version is a few times faster then original MO by Barbosik.
Please stop posting shit instead of issues.

**Comment by AlexandriteErikParacelsus** [comment]
@Gimmo this guy keeps spamming a shit ton of issues. I triggered a lot when I see this guy issues

**Comment by Megabyte918** [comment]
![capture](https://cloud.githubusercontent.com/assets/17245196/21290843/f900823a-c497-11e6-92fa-fec04a6e9e9a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17245196/21290844/fc638238-c497-11e6-9d09-4c77e97ba3fc.PNG)

**Comment by MastaCoder** [comment]
@Gimmo I bet he's from the OgarUL community. I bet!

**Comment by LegitSoulja** [comment]
@MastaCoder I don't understand what you mean about that.. Is it our fault you even have a github with open issues? No. Handle your problems kiddos.

**Comment by MastaCoder** [comment]
Oh god why are you back 😆
