### ISSUE TITLE
 There is too much rebound in the splits

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#211]
how to reduce the rebound in the splits?

**Comment by Megabyte918** [comment]
I don't know what you mean by "rebound"

**Comment by PsycoYT** [comment]
When the cells collide there is much rebound

**Comment by Megabyte918** [comment]
But does "rebound" mean?

**Comment by Megabyte918** [comment]
@PsycoYT https://github.com/Megabyte918/MultiOgar-Edited/issues/179#issuecomment-267880337
