### ISSUE TITLE
Remote console proposal

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#213]
When server run as a daemon, server console is inaccessible. I offer to make remote web console ~~based on  [https://www.npmjs.com/package/web-terminal ](https://www.npmjs.com/package/web-terminal )~~ 

~~There is a lot of terminals, but this one seems to be simple enough and have appropriate functionality.~~ 

Any thoughts?

**Comment by Megabyte918** [comment]
Sure, go ahead! It sounds like it would be a pretty useful feature :)

However I think there should be some sort of config that allows people to choose if they wan't to use the web terminal or not. Kind of like how the `serverWsModule` config is:
<pre>
# serverWsModule: WebSocket module: 'ws' or 'uws' (install npm package before using uws)
serverWsModule = "ws"
</pre>
That way they can choose, and if they choose the web terminal then they will install the module rather adding it to package.json to be installed by default.

**Comment by NameYT** [comment]
@Megabyte918 Have you fix the bug on SCript?

**Comment by NameYT** [comment]
@Megabyte918 Da Skin?

**Comment by Gimmo** [comment]
For now we have two models:

1. MO stay intact. To catch daemon stdin/stdout we need one more instance of node.js. We run small script as a daemon and spawn MO(through next instance of node) as a child process. Script intercepts io and connect with terminal client via sockets.

2. Hooks with transport layer connection ( sockets on server console io) should be added to MO. This way we don't need one more instance of node. Hooks can be disabled via config.

I check a minimal prototypes of both configurations. User terminal in both cases is the same, ready made.

**Comment by Gimmo** [comment]
Here is quick and dirty test without any security. Only for development.

Get MO from https://github.com/Gimmo/MultiOgar-Edited.
Npm install or just copy "node modules" from old install.

// short way - just copy console-plus.js and run.sh to your server /src

Set address of your server in src/console-plus.js::131.
Run "node console-plus".
Open http://YOURADDRESS:1234 in browser.

Comment please

**Comment by Gimmo** [comment]
Now, in first glance, it's look like working.

Changed MO files - CommandList.js : 
changed column order in playerList , because table was messed up in utf8 terminals by "cool names" ; console.log changed to  Logger.print for consistance.

New files:   
src/console-plus.js
src/console-plus.html

Specific terminal commands:

arrow Up/Dn         -> comands history for current session
arrow Left          -> clean input line
Esc or "logout"     -> terminal logout

default login/pass  ->  "admin" "pass"
address of server   ->  console-plus.html :: 24
port                ->  console-plus.js :: 135

run "node console-plus.js" with your favorite daemonizer, it will start MO. 
Play the game as usually.
To open console go yourserver:1234 in browser.

**Comment by Megabyte918** [comment]
@Gimmo Check the PR

**Comment by JaraLowell** [comment]
Am working on an Remote Control ws client trough web using the userRoles.json as source of granting or not granting access. Actually it sort of finished, just need submit it to OgarServ and then if @Megabyte918 likes it enough he can copy it over to here to 😸

**Comment by Megabyte918** [comment]
@JaraLowell Sounds pretty good, but I think this one is good for now :3
@Gimmo PR merged, closing
