### ISSUE TITLE
How to use Commands in Mgar.io / Ingame After Login

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#215]
How to set up commands? @Megabyte918

**Comment by Megabyte918** [comment]
@NameYT /command in the chat.

**Comment by NameYT** [comment]
@Megabyte918 Only show /skin /kill /help

**Comment by Megabyte918** [comment]
Those are the player commands. You can't enter regular commands from CommandList to the chat.

**Comment by NameYT** [comment]
@Megabyte918 Then how can mgar.io did it? i saw in a video doing /login then /minion

**Comment by Megabyte918** [comment]
They must be using a different server.

**Comment by MastaCoder** [comment]
Maybe they **CHANGED** the code. I don't know dude, the minion command is somewhere deep and hidden in the code.
