### ISSUE TITLE
HELP ME MEGABYTE!

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#216]
https://www.youtube.com/watch?v=iuIB_ZUwynY&feature=youtu.be

HELP ME PLEASE

**Comment by Megabyte918** [comment]
What is that

**Comment by NameYT** [comment]
@Megabyte918 Its a Script From Goat that i can't use if i enter the Ip can u help me?

**Comment by Megabyte918** [comment]
Report the bug to Goat. This has nothing to do with this server or the development of MutliOgar-Edited so I am closing.

**Comment by NameYT** [comment]
@Megabyte918 No Its the Script SOme thing wrong with it
Its like u-bot singa clan etc

**Comment by NameYT** [comment]
@Megabyte918 That extension controls the ERTP :)

**Comment by Megabyte918** [comment]
Its not even MultiOgar-Edited.. it's Goats repo, make an issue there.

**Comment by NameYT** [comment]
@Megabyte918 Okay wait for me :)

**Comment by NameYT** [comment]
@G047

**Comment by NameYT** [comment]
@G047 HELP

**Comment by AlexandriteErikParacelsus** [comment]
wtf
