### ISSUE TITLE
How to do that?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#217]
https://www.youtube.com/watch?v=zyjfiPU5QQo

If u closly watch Classy Double Split and the 4th cell look at it how it grow how how?|?
@Megabyte918

**Comment by AlexandriteErikParacelsus** [comment]
It's cell render. You need a strong computer to have it 2k+. If your computer is weak it will disable when you're 2k

**Comment by Megabyte918** [comment]
@NameYT It is client sided, just zoom out 50% on the vanilla client (by zoom i mean ctrl + minus) and it will look the same, however @AlexandriteErikParacelsus is right you do need a pretty good computer for it.
