### ISSUE TITLE
serverBind doesn't work

### ISSUE THREAD

**Issue by iamtaeuk** [Megabyte918/MultiOgar-Edited#218]
Hello,

The feature "serverBind" doesn't work when I assign an IP in the `gameserver.ini`.
It shows an error `EADDRNOTAVAIL`

Isn't serverBind a whitelist-thingy feature to allow web clients?

For example, if the web server (client) has an IP 45.8.0.1, than if I insert that value in, doesn't the server only make connection to that web server?

Thanks.

**Comment by Megabyte918** [comment]
@iamtaeuk try changing your port, `EADDRNOTAVAIL` basically means, `ERROR, ADDRESS NOT AVAILABLE` so if changing your port doesn't work try changing the address your server is listening to.

**Comment by iamtaeuk** [comment]
@Megabyte918 Tried all kinds of random ports (1501,2744,60001 etc); all of them show the same error `EADDRNOTAVAIL`.

**Comment by Megabyte918** [comment]
@iamtaeuk have you tried using different IP's?

**Comment by iamtaeuk** [comment]
@Megabyte918 Yes, from localhost loopback to a real web server IP.

**Comment by cowpits** [comment]
server bind is for a server that has more than one IP address or a Multihome system connected to two different networks. For instance if you have an Ehternet adapter connected to your work network with IP 10.146.10.26 and your WiFi adapter connected to your Home network with 192.168.1.148 you can specify which adapter or IP the server listens on. Sometimes a system can be on the same network with more than one IP for instance 192.168.1.148 and 192.168.1.126 where you also host a website off it. You can designate 192.168.1.126 for Ogar and 192.168.1.148 works the same as IIS or Apache. At least my understanding of server IP bind. 0.0.0.0 means it listens on all IPs assigned to the system.
