### ISSUE TITLE
Spawn-animation

### ISSUE THREAD

**Issue by MineMooreALT** [Megabyte918/MultiOgar-Edited#220]
Can you add a feature called "Spawn-animation" ? look at how the WoW bots spawn in this video for example https://www.youtube.com/watch?v=lNdQBWGik9g √

**Comment by ZfsrGhS953** [comment]
Some agario clones have it, however because it's client sided, a bug happens when you opened the menu while playing the game and press "Play" - the spawn animation would appear in the middle of the screen, but the cell wouldn't appear because you're already playing.

**Comment by MineMooreALT** [comment]
so you cannot do it?

**Comment by Megabyte918** [comment]
Yep, it is client sided I'm afraid.

**Comment by MineMooreALT** [comment]
@Megabyte918 It kinda looks server sided to me like the server gives it the mass like 5 seconds after it spawns

**Comment by Megabyte918** [comment]
@MineMooreALT chack the `spawnPlayer` function in GameServer.js, try setting the size variable to lower than playerStartSize by default, and then set a timeout on adding playerStartSize to the default size. But something like that would hinder performance.

**Comment by MineMooreALT** [comment]
can you put the lines in github for me so I can understand better thanks

**Comment by Megabyte918** [comment]
@MineMooreALT https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L933-L976

**Comment by MineMooreALT** [comment]
@Megabyte918 I'm too fucking noob can you just do it for me

**Comment by Megabyte918** [comment]
@MineMooreALT 
Change [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L940) line to `size = 32;`
Then under [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L969) line add the following code:
<pre>
var self = this;
setTimeout(function() {
    cell.setSize(self.config.playerStartSize);
}, 2000);
</pre>
Players will spawn with 32 starting size by default, then after 2 seconds their size will be set to the value of playerStartSize.

**Comment by MineMooreALT** [comment]
It fucked up bad lmao can you make a separate code for minions because there spawning with 132 mass then going to 43 mass

**Comment by MineMooreALT** [comment]
nvm i fixed it

**Comment by Jhair2015** [comment]
@MineMooreALT  Plz, give me the code!
