### ISSUE TITLE
use jxcore instead node.js

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#221]
will better

**Comment by ZfsrGhS953** [comment]
Node.js is 2 times faster than JXcore. So it will only make things slower.

**Comment by RelTakeover** [comment]
https://www.youtube.com/watch?v=xE_oH1tJI0w

**Comment by Megabyte918** [comment]
Considering the performance it already has, I think it is fine the way it is.
