### ISSUE TITLE
Skins work for minions but not for myself

### ISSUE THREAD

**Issue by Creepso** [Megabyte918/MultiOgar-Edited#224]
why skins like 

**shark or kraken**

or

 other doesn't work for my cell ? help :-1: :tired_face:

**Comment by Megabyte918** [comment]
@Creepso Miniclip has half-patched skins on private servers, you cannot see your own skin but others can. This is a client related issue, therefor I cannot help you resolve it. However you can use custom skins by using the [custom skins](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/scripts/CustomSkins.js) script.
