### ISSUE TITLE
bandwith bug

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#225]
Hello!

So on my VPS my servers use A LOT of bandwith, like today it has used 300gbs
Why?
Any fix??

Thanks

**Comment by MineMooreALT** [comment]
Sounds like a issue with your vps

**Comment by Megabyte918** [comment]
^^

**Comment by systemroot** [comment]
have you try to monitor and to find usage of multiogar-edited for bandwith? that can be caused by ddos attack too.

**Comment by Gimmo** [comment]
Check your VPS logs. Most of all you are brutforced by chinese bot-port-scaner.

**Comment by CalvinDKL** [comment]
Ill check ;)

**Comment by CalvinDKL** [comment]
The guy that owns the VPS company found out the problem, it was my domain that was eating up all the bw.
