### ISSUE TITLE
E R T P Macros (bots) doesn´t work

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#226]
Tittle

**Comment by Megabyte918** [comment]
@AlexByte918 Can you please provide me with more info, such as what client you were using, how your configs were set up, if you had any other macros/extensions/scripts enabled, etc. I can't really fix something if I don't know whats wrong or what caused it first.

**Comment by AlexByte918** [comment]
@Megabyte918 Sorry im stupid, XD already its working :v
