### ISSUE TITLE
Adding messages on the leaderboard [LMS]

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#229]
Hey it would be cool if you could add messages on the leaderboard, such as : time
Or :  The winner is ........

Maybe this could be done??

Thank you!

**Comment by MastaCoder** [comment]
Why would someone need the time. Why would you need the winner is, it's a leaderboard. You already see who number 1 is.

**Comment by CalvinDKL** [comment]
I need it for rush mode, plus it would be more professional.
And the current one is basically normal agario, but if someone was to wipe the whole server by eating them all.

PS: when i kill everyone and i am the last man standing players cant join back in, even though it said LMS started again afterwards.

**Comment by Tyler3D** [comment]
Im working on Rush Mode but I don't have much free time because of school

**Comment by CalvinDKL** [comment]
Tyler its u!
Tyler my main man.

It would be much appreciated.
Can i add you on skype?
I can maybe help coding on it!

my skype - calvin.leonhardt

**Comment by Megabyte918** [comment]
@CalvinDKL You can see an example of what a working countdown on the leaderboard looks like from Ogar's [tournament gamemode](https://github.com/OgarProject/Ogar/blob/master/src/gamemodes/Tournament.js), or if that does not work for you you can try using what the board command uses to change the leaderboard.

**Comment by Tyler3D** [comment]
@CalvinDKL I don't have skype. But, there's the code.
http://pastebin.com/2Z0tTfzz
