### ISSUE TITLE
rlly awesome

### ISSUE THREAD

**Issue by systemroot** [Megabyte918/MultiOgar-Edited#23]
just i want to say thank you i was trying to add minions a log time ago but idk what i was doing i'm not good with nodejs. so thank you alot <3
*you can close this after u read.*

**Comment by AlexandriteErikParacelsus** [comment]
@Megabyte918 m9 u have a fan over here xddddddddddddddddddddddddddddddddddddddddd

**Comment by Megabyte918** [comment]
@systemroot No problem man :) Its nice to see people like you every once in a while, made my day!
