### ISSUE TITLE
Jittering thing.

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#230]
Is there a way to make the playercells not jitter when split in 16 small pieces?

**Comment by agariotips** [comment]
Those are cell collisions, usually during line splits it happens, but not in 16 pieces(for me at least).

**Comment by freaky767** [comment]
True.

**Comment by freaky767** [comment]
For me its kinda annoying when im trying to have a perfect vanilla server.

**Comment by freaky767** [comment]
I just want a fix for the jittering cells.

**Comment by Megabyte918** [comment]
@freaky767 This bug was mostly fixed [here](https://github.com/Megabyte918/MultiOgar-Edited/commit/3a7fcf56942ed8d577cb63c1c9d4175d4c91991c). When you are in 16 cells you will not notice jittering.

**Comment by freaky767** [comment]
thankies :)
