### ISSUE TITLE
Wtf bots

### ISSUE THREAD

**Issue by duwayy** [Megabyte918/MultiOgar-Edited#232]
Is it possible to replace bots by original Barbosik's bots ?
They were way smarter in split

**Comment by Megabyte918** [comment]
@duwayy Just replace the BotPlayer files.

**Comment by duwayy** [comment]
I already tried it but when adding bots in console it give a fatal error and server then crash

**Comment by Megabyte918** [comment]
Can you provide said error?

**Comment by duwayy** [comment]
Sure:
```
>addbot 25
Added 25 player bots
>[FATAL] TypeError: Object #<Cell> has no method 'getSize'
    at PlayerTracker.BotPlayer.decide (/var/www/html/agario/MultiOgar-Edited-master/src/ai/BotPlayer.js:84:27)
    at PlayerTracker.BotPlayer.sendUpdate (/var/www/html/agario/MultiOgar-Edited-master/src/ai/BotPlayer.js:58:10)
    at GameServer.updateClients (/var/www/html/agario/MultiOgar-Edited-master/src/GameServer.js:436:39)
    at GameServer.mainLoop (/var/www/html/agario/MultiOgar-Edited-master/src/GameServer.js:616:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by Megabyte918** [comment]
@duwayy use this one instead: https://github.com/Megabyte918/MultiOgar-Edited/blob/6bb6eef1d5c32c48e3c99b361e4ef361737d4eb5/src/ai/BotPlayer.js

**Comment by duwayy** [comment]
Thank you ! 
Why don't you put back the old one ? In the newest I think bots split too much :)

**Comment by Tyler3D** [comment]
@duwayy Lol I want to popsplit a bot. Then at the perfect moment. I double split. The bot splits all into me.

**Comment by duwayy** [comment]
@Tyler3D If it's a joke, I'm afraid I forgot to laugh.
Not relating to popsplits, bots when they are <300 mass full splitting for savaging tiny cells does not look very "natural", you know.

**Comment by AlexandriteErikParacelsus** [comment]
@duwayy the original bots are dumb, they rarely split

**Comment by duwayy** [comment]
@AlexandriteErikParacelsus they split.. new ones split too much for anything (in my opinion)

**Comment by AlexandriteErikParacelsus** [comment]
@duwayy "they rarely split"
