### ISSUE TITLE
Message to Tyler

### ISSUE THREAD

**Issue by CalvinDKHD** [Megabyte918/MultiOgar-Edited#236]
Hello tyler, thank you for making rush mode.
But it doesnt quite work..

the game runs until the time finishes
and then this error occurs

https://gyazo.com/57b20e63e8c437628a275119f75e8099

**Comment by Megabyte918** [comment]
That gamemode is far from finished, it is just a base.

**Comment by AlexByte918** [comment]
@Megabyte918 When you release?

**Comment by Megabyte918** [comment]
@AlexByte918 When it is finished lol

**Comment by CalvinDKHD** [comment]
xDD
