### ISSUE TITLE
How to make splits like to mobile?

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#238]
Plz

**Comment by ZfsrGhS953** [comment]
Remove [these lines](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L805-L808), [these lines](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L869-L871), and change "40" in [these lines](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L760-L761) to "size1"
