### ISSUE TITLE
What VPS could i use?

### ISSUE THREAD

**Issue by TrueFX** [Megabyte918/MultiOgar-Edited#239]
I need a vps to host my server but i dont know which to use, ive been told digital ocean but dont know how to set it up :(

**Comment by ZfsrGhS953** [comment]
OVH VPS SSD 1 (it can handle about 300 players without lag)

**Comment by TrueFX** [comment]
@ZfsrGhS953 yes but how do i set it up? :) i dont wana buy it and not know how to do it

**Comment by ZfsrGhS953** [comment]
You need to know how to use Linux and SSH

**Comment by TrueFX** [comment]
i dont know how to.. know any tutorials or anything? i used to have one on c9 lol i could do that easily!

**Comment by Fantasy-Agario** [comment]
For a good server you will need to pay , i recommend Digital Ocean .

**Comment by ZfsrGhS953** [comment]
DigitalOcean is more expensive in general and also has a transfer limit, which is very bad for hosting MultiOgar-Edited servers.
