### ISSUE TITLE
SKINS

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#24]
i cant use skins on ogarUL CLIENT <SKIN> , WHY?

**Comment by Megabyte918** [comment]
@RelTakeover This is a client sided problem, not related to this fork of multiogar. I cannot fix this as I am not the owner of the OgarUL client, if you really want skins go ask about it on the OgarUL forums.

**Comment by AlexandriteErikParacelsus** [comment]
lmao wtf is this cancer
