### ISSUE TITLE
Bots (ai)

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#240]
Currently implemented bot are an idiot.

Did someone try other bots?  What the difference if I use [Qbot](https://github.com/hydr93/Ogar-QBot/tree/master/src/ai) or [GogyBot](https://github.com/gogy27/Ogar-GogyBot/tree/master/gogybot), or may be it's possible to implement mechanisms from popular user bots as [Apostolique](https://github.com/Apostolique/Agar.io-bot) or [heyitsleo](https://github.com/heyitsleo/agar.io-bot) ? Does it have a sense at all?

I hope here are people, who have expirience and thought about what the bot should be to win, not only eat resources.

**Comment by Megabyte918** [comment]
@Gimmo I think the current ones are smart, they can splitrun with each other, they can reverse tricksplit, they can get big on their own, what else do you want? Ive seen them get to the top of the leaderboard easily, I'm trying to keep the bots as smart as possible while also keeping the code to a minimum for performance. The other projects you mentioned may be smart, but there are a few things I'd like to mention:

QBot: too large/complex to implement for performance reasons.
GogyBot: same as QBot, and heavily designed to be used for Ogar, it will not work here. And even if I tried to port it, it would impact performance alot. 
Apostolique: same as QBot
heyitsleo: same as QBot

**Comment by Gimmo** [comment]
@Megabyte918 There is two tasks for the bot (as I'm understand):
1. server testing - for this existent bot good enough
2. game promotion - I'm a very weak player, but I win with current bots all the time. It's not good for game.
I don't talk about the way the bot is made, I talk only about result. Maybe one instance of heavy bot can be better then 100 light ones? May be we should have ability to run 100 lightweight bots + pair of different heavy, which will be able to kill player ? When I try to play on different servers, I always killed fast enough - by bots or by teams. I'd like to have this situation to be on my empty server.

**Comment by Megabyte918** [comment]
I do not want this project to become OgarUL.

**Comment by AlexandriteErikParacelsus** [comment]
Yep, the lag make the project collapsed on it self.

**Comment by Megabyte918** [comment]
Current bots are experimental, they are not fully developed yet. As of now it is just a base. They are mostly for testing purposes, not really meant to be played with. Sure they can get to the top of the leaderboard quicker, reverse tricksplit, or even splitrun with each other now and then, but their not really supposed to be difficult enough to challenge a real player. That's what other players are for. I only use these bots if I feel lonely and have no one to play with haha, otherwise I'm playing with other real players.

**Comment by Tyler3D** [comment]
@Megabyte918 I can see that. About to popsplit bot... Omg the bot 16's into my double split.

**Comment by Tyler3D** [comment]
Or maybe they're trying to ruin my satisfaction Idk.

**Comment by Tyler3D** [comment]
Changing your botPlayer.js to this
http://pastebin.com/YN4b6ptM
Aka Undo Megabyte's Last Commit, makes them smarter.

**Comment by Gimmo** [comment]
@Megabyte918 I understood. But I still need productive a bot or at least a good advise how this can/should be built.

**Comment by Megabyte918** [comment]
@Gimmo Just replace/add the necessary files and port the code from ogar over to multiogar

**Comment by agariotips** [comment]
So i would literally copy and paste it into the ai?

**Comment by Gimmo** [comment]
@Megabyte918 Can you point known to be good/working/productive one? Or I have the only chance - to look at stars at github?

**Comment by Megabyte918** [comment]
@Gimmo I don't really know any besides the ones you mentioned earlier

**Comment by Gimmo** [comment]
@Megabyte918  Ok, thanks. Let this issue hang some time, may be someone respond.

**Comment by Gimmo** [comment]
Nothing... No one interested.

**Comment by Megabyte918** [comment]
@Gimmo It shouldn't be that easy to win against bots now (i'm hoping)

**Comment by Gimmo** [comment]
Sometimes really much more better, but I really think aggression to players should be more then to brothers-bots. ( May be coefficient of distance? )
Sometimes big bot ignore me when I'm close enough because of big amount of bots around.

I still easy catch small bots, but time by time big bots catch me fast and rigidly. If bots will be little more sensitive to player  it will be perfect.

Generally - really much better. Thanks.
