### ISSUE TITLE
Sorry I know this is a duplicate but did we ever get auto restart?

### ISSUE THREAD

**Issue by MineMooreALT** [Megabyte918/MultiOgar-Edited#243]

**Comment by AlexByte918** [comment]
You want this? https://github.com/Megabyte918/MultiOgar-Edited/pull/148

**Comment by AlexandriteErikParacelsus** [comment]
@Megabyte918 According to Megabyte918, we're not gonna add it. He said "there is no need cause you can just use pm2 remember?"-Megabyte918 from skype

**Comment by Megabyte918** [comment]
@MineMooreALT https://github.com/Megabyte918/MultiOgar-Edited/issues/146#issuecomment-266349717
