### ISSUE TITLE
Easy anti-bot system

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#245]
New setting
MaxSameNicks (max same nicks can be used, good setting for anti-bot)
MaxSameNicks = 1 - (if owner of bots start their bots, only 1 bot will can connect to server, and he cant have bots(if autobots is on))

**Comment by ZfsrGhS953** [comment]
This is a bad idea, because the bot owners will name their bots after other players to prevent them from spawning.

**Comment by Megabyte918** [comment]
@ZfsrGhS953 Agreed, also it's easy for botters to use different names for bots.
