### ISSUE TITLE
AI Bots are glitching? Random splits, bugs etc.

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#247]
Hi Megabyte;

The AI bots are completely messed up in the server?
Please play on your project by adding AI bots in the server and you teaming with minions or something like that.
Just keep playing with it, then please correct the errors.

**Comment by AlexandriteErikParacelsus** [comment]
There is nothing wrong with the bots (ai)

**Comment by MastaCoder** [comment]
Go away OgarUL.

**Comment by AlexandriteErikParacelsus** [comment]
Go away OgarUL. [x2]

**Comment by Fantasy-Agario** [comment]
Go away OgarUL. [x3]

**Comment by Fantasy-Agario** [comment]
Closing
