### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#248]
1)how to lock commands from web-command 
2) how to set more login accounts on web-command
3 ) How to configure the maximum mass that can give a player through the web console

**Comment by AlexHGaming** [comment]
I can answer 3)
Find 'PlayerMaxMass' then just change that :)

**Comment by AlexandriteErikParacelsus** [comment]
How are these issues?

**Comment by Megabyte918** [comment]
1) It is just a base, don't give your login to people you don't trust with certain commands.
2) Theres no point when theres already a global login system.
3) Change [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/CommandList.js#L515) value in CommandList to something like this: 
`var amount = Math.max(parseInt(split[2]), maximumValue);`
