### ISSUE TITLE
Skins Glitch

### ISSUE THREAD

**Issue by kareemman00** [Megabyte918/MultiOgar-Edited#249]
I have a problem with my extinson arb-cells.tk cuz the extinson lets u use ur offical skins but when i use for example fly skin and play it shows the fly skin but when some one look to me (from another pc) he saw just my name with no skin please some one tell me how to fix Notic : There is not skins bug with multi ogar offical and sorry for my bad english

**Comment by MastaCoder** [comment]
You have a problem with your own script and you're asking us?

**Comment by Megabyte918** [comment]
This has nothing to do with this project.
