### ISSUE TITLE
Delay for minions

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#251]
@Megabyte918 - you misunderstood me in #134 (No point in adding delay, as you can just disconnect the bots or kill them) 
I want to bots go to you mouse with a delay (example) in config MinionsDelay = 30
bots go to you mouse with 30 milliseconds delay (mouse coordinates 0x 0y, 30 milliseconds later 100x 100y and bots go to 0x 0y) and I will add new command - MinionsDelayMin = (time in milliseconds to min delay) MinionsDelayMax = (time in milliseconds to max delay) conclusion: mega reallistic bots like old free bots
delay for minions(new setting) MinionsDelay = (time in milliseconds) This setting add delay for follow mouse ( like bots with proxy)

**Comment by NameYT** [comment]
@Megabyte918 Yes Add this

**Comment by t11tanYT** [comment]
@NameYT  you want this too?

**Comment by NameYT** [comment]
@t11tanYT Yes

**Comment by NameYT** [comment]
#214

**Comment by MastaCoder** [comment]
But the issue is this setting is so useless. Sounds more like OgarUL to me.

**Comment by Megabyte918** [comment]
@MastaCoder Agreed
@t11tanYT do not make any more issues on the subject, it is not going to be added because it is useless.
