### ISSUE TITLE
server error when i try to connect from web client

### ISSUE THREAD

**Issue by systemroot** [Megabyte918/MultiOgar-Edited#255]
when i start server everything is ok. when i try to connect (tried with astr.io and agario) i get this error.
![](http://image.prntscr.com/image/5d4b20c13d1a45019311b135bbb343af.png)
V. 1.4.7 *(First time running it)*

**Comment by AlexandriteErikParacelsus** [comment]
Not happening for me

**Comment by systemroot** [comment]
idk i tried multiple times to re'download and re'install, if i try an old version this error doesn't happen :confused:

**Comment by Megabyte918** [comment]
@systemroot Fixed, sorry for the wait

**Comment by systemroot** [comment]
it's working, and np and thank you
