### ISSUE TITLE
Auto-deploy bots when player joins

### ISSUE THREAD

**Issue by iamtaeuk** [Megabyte918/MultiOgar-Edited#256]
Hello,

I have been testing MultiOgar-Edited for past few days.
With the minion feature, I am trying to accomplish minions to be constantly made for every players.
Would that be possible?

Maybe a separate 'Minion' gamemode could be made for this.

Thanks :)

**Comment by Megabyte918** [comment]
@iamtaeuk You can achieve this by using the `serverMinions` config
