### ISSUE TITLE
I still dont get Perfect Popslit like / Popsplit with any mass like that? Help 

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#26]
I need some help Paste the code like Gameserver.js like that or something i wanna do a same size and practice my popsplit but it always fail how to fix it?

**Comment by Megabyte918** [comment]
@NameYT please do not make duplicate issues, they will be closed or it could result in a ban. Follow my instructions in #10 and you will be fine, its not that hard all you need to do is change two numbers.
