### ISSUE TITLE
About splits.. NEED A CHANGE. Enhancement

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#260]
It may be that the splits are similar to agar.io, but in truth they are not, apologies if this topic has been repeated, but really the splitss need a great change, we will not be the speed or the code itself. The other day a youtuber that did not know the private servers, entered my server and found the very different splitsto agar.io.

Please concentrate on the physics, the performance is fine, do not add new game modes or web consoles, if the splits are still not accurate or similar to agar.io.

**Comment by Jhair2015** [comment]
Yep, i test now and divisions not like agar.io :/
Fix this.

**Comment by PsycoYT** [comment]
yes! please fix..

**Comment by AlexandriteErikParacelsus** [comment]
Go away OgarUL

**Comment by PsycoYT** [comment]
@AlexandriteErikParacelsus 
Do you know how to read?


Clearly I said agar.io not OGARUL, if you are going to comment that it is something productive.

**Comment by Tyler3D** [comment]
@PsycoYT @RelTakeover What's wrong with them. Please record footage of both and upload them. I rarely play so, I don't see a difference.

**Comment by AlexandriteErikParacelsus** [comment]
@PsycoYT Megabyte918 already said that he is not gonna change the way cells split, so just stop bitching about the splits

**Comment by AlexandriteErikParacelsus** [comment]
closing

**Comment by Megabyte918** [comment]
@RelTakeover @PsycoYT @Jhair2015 The splitting is fine, Ive made sure of it this time by comparing. If it still doesn't look right, try disabling skins or using an extension on vanilla and the private server so that way you can see the splitting more clearly. Or do what @Tyler3D said and record a video of both and compare so that way you can see the difference.
