### ISSUE TITLE
I Can't Access Web Console On IDE

### ISSUE THREAD

**Issue by BrunoOlyver** [Megabyte918/MultiOgar-Edited#261]

**Comment by AlexandriteErikParacelsus** [comment]
Please provide more details

**Comment by BrunoOlyver** [comment]
I try to access the link "127.0.0.1:1234"
but nothing appears, I tried the desktop and it worked, because in the IDE it did not work?

**Comment by Megabyte918** [comment]
@BrunoOlyver Make sure that the web console is running on a port your IDE supports and not 1234 by default.

**Comment by BrunoOlyver** [comment]
I managed to fix this myself but thank you!

**Comment by BrunoOlyver** [comment]
Actually i can access but, none of the commands works

**Comment by Gimmo** [comment]
Console works on OS level. It may be too complicated for your IDE.   Ask for IDE support.

**Comment by BrunoOlyver** [comment]
I already got it, the commands work perfectly I just changed the  WebConsole port
