### ISSUE TITLE
Can you add Start mass by ip ?

### ISSUE THREAD

**Issue by ItsDavehere** [Megabyte918/MultiOgar-Edited#262]
Hey first Merry Christmas can you add Start mass by ip ?

**Comment by AlexHGaming** [comment]
spawnmass [ID] [Mass]
enter that in the console

**Comment by AlexandriteErikParacelsus** [comment]
@AlexHGaming no he's mean by mass by ip is a specific ip joined the game, that ip will have that specific mass that no need to do that spawnmass command.

**Comment by Megabyte918** [comment]
@ItsDavehere You can add spawnmass by ip by adding this code into the end of the `onClientSocketOpen` function in GameServer.js:
<pre>
if (ws.remoteAddress == "insert ip here") {
    ws.playerTracker.spawnmass = val;
}
</pre>
