### ISSUE TITLE
the splits are slow

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#263]
in the latest update the split are slower

it would seem that the spaceticks are slower , not the splitspeed..(the splitspeed is fine)

**Comment by Megabyte918** [comment]
@PsycoYT What is a "spacetick"

**Comment by PsycoYT** [comment]
It can be noticed when splits are given in a row, splits are slower

**Comment by Megabyte918** [comment]
@PsycoYT https://github.com/Megabyte918/MultiOgar-Edited/issues/260#issuecomment-269097342, do not make any more issues regarding the subject.
