### ISSUE TITLE
Mobile Physics

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#264]
More things that mobile physics need
1. The owner of eject mass can eatable after 1.9 sec but other cells can eat it instantly
2.  Cells cannot pass throw in the middle of 2 cell like OO they try it then they got eaten
3. Player does not spawn form ejected mass
4.  Pellets does not grow more than 1

**Comment by MastaCoder** [comment]
> Player does not spawn form ejected mass
> Pellets does not grow more than 1

Can't these be done in the gameserver.ini..?

**Comment by PrinceDark9243** [comment]
yes but what about other things i mansioned

**Comment by Megabyte918** [comment]
@PrinceDark9243 
> The owner of eject mass can eatable after 1.9 sec but other cells can eat it instantly

 Is there any videos or other examples of this that I can use to test with?
> Cells cannot pass throw in the middle of 2 cell like OO they try it then they got eaten

Fixed

**Comment by PrinceDark9243** [comment]
https://www.youtube.com/watch?v=S765h9sVgrI

**Comment by PrinceDark9243** [comment]
I you doesnt find any blabla....
 then watch 0:40 to 0:46

**Comment by Megabyte918** [comment]
@PrinceDark9243 Look's normal to me. The same thing happens with regular physics

**Comment by PrinceDark9243** [comment]
not its not make it you will get it!

**Comment by PrinceDark9243** [comment]
and one thing i forget to mension that disconnected player cannot be poped by virus in mobile (Mobile Physics)

**Comment by PrinceDark9243** [comment]
@Megabyte918 add Enhancement TAG!

**Comment by Megabyte918** [comment]
> not its not make it you will get it!

Can't fix something that isn't broken.

> and one thing i forget to mension that disconnected player cannot be poped by virus in mobile 

Example?

**Comment by AlexandriteErikParacelsus** [comment]
I think the split mobile has like push back or something like  that

**Comment by PrinceDark9243** [comment]
For suppose that one cell disconnected so you want to pop him with virus but you cant its like instant recombine for disconnected player
if you dont understand me watch this https://www.youtube.com/watch?v=XXr-EYgklG8
watch form 3:43

**Comment by Megabyte918** [comment]
@PrinceDark9243 You can achieve this by adding this simple check into the beginning of the `onEat` function in Virus.js: 
<pre>
if (c.owner.isConnected == false) return;
</pre>

**Comment by PrinceDark9243** [comment]
Code isnt working!

**Comment by Megabyte918** [comment]
@PrinceDark9243 Works fine for me, you sure you put it in the right place?
It should go here: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js#L32

**Comment by PrinceDark9243** [comment]
i add correctly at that line but nothing happening is just normal i want player can able to eat eject mass for 1.9 sec but virus and (non-owner of the eject mass) can eat it instantly!

**Comment by Megabyte918** [comment]
@PrinceDark9243 
- Virus explosion thingy: 
https://streamable.com/1vhsz

- Ejected mass thingy: 
I've already told you I cannot fix something that isn't broken. And even if I could I'm not going to add that because something like that would cause lag when someone is continuously ejecting mass. My goal for this project is to atleast get vanilla physics, not mobile physics. I am not going to add every single feature from mobile. Atleast not yet. So I am closing this for now.

**Comment by PrinceDark9243** [comment]
i dont want you to add it i just want to make code and then send it to me plz

**Comment by PrinceDark9243** [comment]
how i can able to add eat collision between eject mass and player cell just tell me this!

**Comment by MastaCoder** [comment]
> i just want you to make code and then send it to me plz

ok
