### ISSUE TITLE
How to add? Command all command in mgario cilent?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#265]
When i login i cant do command
can anyone help me?
@Megabyte918

**Comment by PrinceDark9243** [comment]
DUBLICATE

**Comment by NameYT** [comment]
@PrinceDark9243 How please tell me?

**Comment by NameYT** [comment]
@PrinceDark9243 Please tell me how to add commands

**Comment by PrinceDark9243** [comment]
@NameYT I dont know i think @Megabyte918 said that it is not our Problem or anything else

**Comment by Megabyte918** [comment]
@NameYT https://github.com/Megabyte918/MultiOgar-Edited/issues/215, do not make any more issues regarding the subject.
