### ISSUE TITLE
Auto Restart

### ISSUE THREAD

**Issue by P4rtyguy** [Megabyte918/MultiOgar-Edited#266]
Could anyone help me with auto restarting bcuz i run a game and it has alot of trafiic there 6gem.pw and i made a self feed mode and i need an auto restart thanks.

**Comment by Gimmo** [comment]
Auto restart should be done by OS, this task have nothing to MultiOgar. You may make this by cron or by software you use o run  MultiOgar.

**Comment by MastaCoder** [comment]
Duplicate.

**Comment by PrinceDark9243** [comment]
what Masta mean @MastaCoder

**Comment by MastaCoder** [comment]
@PrinceDark9243 Somebody already asked this before, twice.

**Comment by AlexandriteErikParacelsus** [comment]
closing
