### ISSUE TITLE
Linux settings for MultiOgar-Edited

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#268]
MultiOgar-Edited need some featutes which have to be removed outside, because OS have means to resolve the problems them related.

1. Start - Stop and Restart on server fault/crash - SystemV or Systemd or Upstart - what is set for usage on your OS
2. Restart by time interval - cron
3. IP filtering ( ban etc. ) - iptables,  ipsets

All this tasks don't require any programming, one just should read manual and make proper settings. 

Don't forget about holy cow: not OgarUL!

**Comment by Megabyte918** [comment]
1 & 2) so just basically an auto-restart system?
3) we already have that, don't we?

**Comment by Gimmo** [comment]
1&2) it's more then enough
3) nope. As I see in code, server use internal js programmed mechanics instead of system-wide.      
GameServer.js
```
    if (this.checkIpBan(ws._socket.remoteAddress)) {
        ws.close(1000, "IP banned");
        return;
    }
```
```
GameServer.prototype.checkIpBan = function(ipAddress) {
    if (!this.ipBanList || this.ipBanList.length == 0 || ipAddress == "127.0.0.1") {
        return false;
    }
    if (this.ipBanList.indexOf(ipAddress) >= 0) {
        return true;
    } .......skipped
```
As I can see - it's direct scan of banlist by js

**Comment by Megabyte918** [comment]
@Gimmo Alright I understand now.. sounds good!

**Comment by Gimmo** [comment]
I will write samples for Debian, just because I preferre to use it. 

How to use systemd

Systemd is most modern init system for linux.
If it not set on your system:

from root or sudo

 apt-get install systemd
 apt-get install systemd-sysv
 reboot 
then:
 make a file **game.service**
```
  [Unit]
  Description=Bitcoin daemon serivce
  After=network.target


  [Service]

  Type=simple
  Restart=always
  #RestartSec=30
  WorkingDirectory=/where_your_game_placed 

  StandardInput=null
  StandardOutput=null
  StandardError=syslog

  ExecStart= /usr/local/bin/node /where_your_game_placed/src/index  
  # OR /where_your_game_placed/run/console-plus OR you can make different files with whatever.service names
  # to run game with or without console  

  [Install]
  WantedBy=multi-user.target
  Alias=bitcoin.service
```

**Don't forget to remove (comment) loopbacks in console-plus !!** 

put game.service to  /etc/systemd/system

to run ->    systemctl start game.service 
to check ->  status systemctl status game.service
to restart -> systemctl restart game.service  

Now you have the game, which autorestart on errors or server reboot

**Comment by MastaCoder** [comment]
Great work! @Gimmo

**Comment by Megabyte918** [comment]
Nice

**Comment by AlexandriteErikParacelsus** [comment]
Wow, impressive.

**Comment by Gimmo** [comment]
**cron**

cron is always presents in your system
There is two ways to use it

**easy way**
  find directories 
    `/etc/cron.daily`
   `/etc/cron.hourly`
    `/etc/cron.monthly`
    `/etc/cron.weekly`

make file
 **gamerestart**
  `#!/bin/sh`
  `systemctl restart game.service`

put it to directory of your choise i.e. file should lie in "daily" to be executed every day
`cd /this_directory`
`chmod  gamerestart 755`

that's it. File will be executed according the name of directory

**hard way**
  find file /etc/crontab
    open it with editor

valuable part of file has format 

`*     *     *     *     *  /path/to/file/to/be/executed`
`-     -     -     -     -`
`|     |     |     |     |`
`|     |     |     |     +----- Day of week (0-7)`
`|     |     |     +------- Month (1 - 12)`
`|     |     +--------- Day of month (1 - 31)`
`|     +----------- Hour (0 - 23)`
`+------------- Min (0 - 59)    `
``
Each of the first five fields contains only numbers, however they can be left as '*' characters to signify any value is acceptible
```
# Run the 'something' command every hour on the hour
0   *   *   *   * /sbin/something
```

```
# Run the `nightly` command at ten minutes past midnight every day
10  0   *   *   * /bin/nightly
```

```
# Run the `monday` command every monday at 2 AM
0   2   *   *   1  /usr/local/bin/monday
```
One last tip: If you want to run something very regularly you can use an alternate syntax: Instead of using only single numbers you can use ranges or sets.

A range of numbers indicates that every item in that range will be matched, if you use the following line you'll run a command at 1AM, 2AM, 3AM, and 4AM:

```
# Use a range of hours matching 1, 2, 3 and 4AM
*   1-4   *   *   * /bin/some-hourly
```
A set is similar, consisting of a collection of numbers seperated by commas, each item in the list will be matched. The previous example would look like this using sets:

```
# Use a set of hours matching 1, 2, 3 and 4AM
*   1,2,3,4   *   *   * /bin/some-hourly
```
make file as mentioned before for every command you want to execute in schedule
and add appropriate lines to crontab
now you have scheduled tasks for your server

**Comment by Megabyte918** [comment]
@Gimmo Wow.. I should get Linux haha

**Comment by MastaCoder** [comment]
@Megabyte918 Mac does pretty much the same thing too, it's the only reason why I got a MacBook instead of a Dell XPS. I love the Unix terminal.

**Comment by Gimmo** [comment]
@Megabyte918  I never think someone use Mac as production server. 
BTW @MastaCoder is right - all things of MacOS stolen from linux. Difference is imaginary.

**Comment by MastaCoder** [comment]
@Gimmo Well I wouldn't say much as "stolen". They're both built off of the unix base, so *a lot* of the commands in the terminal are pretty much the same. However, Mac was the first main OS that would use Unix. As well, Mac is the only popular Unix based system that is in fact Unix Certified. Linux is not Unix Certified yet! (I think)

I would never use Linux as a base system where I program with, there are so many programs and features that are simply missing from Linux. However, for server production, I am heads into Linux.

I still use Windows, Windows is much for power users. However, I really enjoy the Terminal (and animations!) of MacOS. So it's a win for win, I got to say though, I miss a lot of the shortcuts of Windows that just made using the OS much faster. However, for programming, MacOS is much better in my opinion. :smile:

**Comment by Gimmo** [comment]
Certified unix - it's just about trademark. MacOs use unix-like core only from version 10, but linux have many years history. Nothing to talk about at all.

I also use win for everyday work. But in this thread we talk about production server IMO.

**Comment by Gimmo** [comment]
How to use ipset

install ipset
  `apt-get install ipset` 

predefine hash
  `ipset --create blacklist iphash --hashsize 4096`

add few IPs to blacklist
  `ipset --add blacklist 41.231.136.121`
  `ipset --add blacklist 37.236.253.170`
  `ipset --add blacklist 37.236.239.42`

add iptables rule to reject them
  `iptables -I INPUT -m set --match-set blacklist src -p TCP --destination-port 443 -j DROP`

that's it

Main commands
  `ipset --add blacklist 41.176.136.101` // add IP to blacklist
  `ipset --del blacklist 41.176.136.101` // remove IP from blacklist
  `ipset --flush blacklist` // clean blacklist


// javascript hook for commands (async) 
```
'use strict';

const
    spawn = require( 'child_process' ).spawn,

    addBl = spawn( 'ipset', [ '--add blacklist', '41.176.136.101' ] );
    
    // async returns

    addBl.stdout.on( 'data', data => {
        console.log( `stdout: ${data}` );
    });

    addBl.stderr.on( 'data', data => {
        console.log( `stderr: ${data}` );  
    });

    addBl.on( 'close', code => {
        console.log( `exited with code ${code}` ); 
    });
```
To use it on OS reload blacklist should be saved/restored. I'll add complete script later.

**Comment by MastaCoder** [comment]
@Gimmo You win, I'm out 😆

**Comment by Gimmo** [comment]
@MastaCoder  We should not be so serious, I think.  It's all toys....:)

**Comment by Gimmo** [comment]
Limit number of HTTP connections for IP

apt-get install connlimit

/sbin/iptables -A INPUT -p tcp --syn --dport $port -m connlimit --connlimit-above N -j REJECT --reject-with tcp-reset  
# save the changes see iptables-save man page

**Comment by plazo21** [comment]
dose thsi auto restart or when a error  comes then
