### ISSUE TITLE
Global server-wide chat

### ISSUE THREAD

**Issue by iamtaeuk** [Megabyte918/MultiOgar-Edited#269]
Hello,

Is there a way to send server-wide messages (chats) ?
When a new player joins, that message could be sent when they join the  server.
If the message was sent after the user started playing, it could send the message as if it was a normal chat.
It can have the flag `0x80` (SERVER message).

Thanks :))

**Comment by MastaCoder** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L522-L529

From: Server, forgot what the variable was. (I think it's null?)
To: null (All players)

And the message. Add this when a player joins in game.

**Comment by Megabyte918** [comment]
@iamtaeuk you can achieve this by editing the `serverWelcome1` and `serverWelcome2` configs.

**Comment by iamtaeuk** [comment]
@Megabyte918 Yes, but is it possible to change that message when the server is on? It would be more like an notice type of message. If the player was playing before the message change happened, than the SERVER will just send a server-wide chat to all players. If the message change happend after the player joined, it would be like the `serverWelcome` features.

**Comment by Megabyte918** [comment]
@iamtaeuk You can just change the config through the terminal though right? Like this:
`change serverWelcome1 [message]`

**Comment by iamtaeuk** [comment]
But would using `change serverWelcome1` work if the player is already playing? Wouldn't it only send that message to new players? 

btw using `change serverWelcome1 [message]` gives me `WARN: Invalid value NaN`.
Maybe that message was coded into integer?

**Comment by Megabyte918** [comment]
@iamtaeuk Oh you meant while they are already playing?? In that case just do what @MastaCoder said, and the value of from is playertracker.

**Comment by iamtaeuk** [comment]
If the player joined AFTER I sent the message, it would be like a `serverWelcome` type of message, but I needed the ability to send it both WHILE they were playing. More of a real-time notification type.

**Comment by MastaCoder** [comment]
Just use that function where ever you want. Set some sort of timeout or something to run at a delayed time after a player has joined..
