### ISSUE TITLE
Adding Commands. (No issue's)

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#270]
### Personnaly find this Edited multiogar really cool! I love it, U added minions and that u could do <r> to randomise the skins on agar.io private server, bots eating pellets, god dam best idea i saw!! + all scripts to control bots makes it even easier for poeple to control them.
Possible to add those following commands?
-Modify split speed 
-Add a virusFeedAmount ( lets say u put it to 4, takes 4 shoots till the virus throws.)
-Modify the way we eat virus (cells dont go as far)
-Modify split speed recombine so we can do tricksplit better
=====================================================================
Keep it up!  Best private server i saw. Maybe u could add it to old.ogarul.io so my server could show up on there 'fetch server'. Not even sure if thats possible, cuz if it would be could be great, more poeple could join the server. (maybe make ur own site?)
Still alot of lag and only a total of 100 connections (30 bots, 5 minions to each user and 5-15 users)
This is only my testing server: http://agar.io/?ip=184.75.143.92:442

**Comment by AlexandriteErikParacelsus** [comment]
Oh gawd

**Comment by Megabyte918** [comment]
@raphyjb Thank you for your kind words :)
I have some things to say about your suggestions:
> -Modify split speed

There is no definite "split speed". it is either modify the [split velocity](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L767) of playercells in boosted mode or modify the [speed](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L725) of move decay for any cell (including ejected mass/viruses). Besides, adding a whole command just to change a player's splits peed is kind of useless anyways, I can't think of any reason why one might need such a command.
 > Add a virusFeedAmount

You can already do that, except the config for it is `virusMaxSize`
> Modify the way we eat virus (cells dont go as far)

Also depends on the playercell's split velocity or "boost distance", decreasing the initial value will decrease the distance the cells travel.
> Modify split speed recombine so we can do tricksplit better

I don't get what you mean by "split speed recombine". If you mean the amount of ticks before cells restore collision, it can be found [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L806), (13 is the number you should change for regular physics version)
> Maybe u could add it to old.ogarul.io so my server could show up on there 'fetch server'

It is designed to only show OgarUL servers, not MultiOgar ones. Can't help you with that
> Still alot of lag and only a total of 100 connections (30 bots, 5 minions to each user and 5-15 users)

Care to elaborate more on the state your server was in at the time? Like how big the players were, how long the server's been running for, if you modified any configurations, etc

**Comment by raphyjb** [comment]
Server bin running for 24 hours, total mass in server 50k (its always around 50k, cuz biggest one in server is 35k) Modified alot of configurations lol. U want a paste bin of it?
Also ticks before cells restore collision is what i was talking about, but wat u gave me was for mobile, i tryed mobile, really funny btw! I liked it, but some poeple pissed at me cuz they couldnt popsplit xD
Anyway you could control my console from web address?

**Comment by Megabyte918** [comment]
@raphyjb Well I mean if you have your food set to spawn with 2x the regular amount + 225 starting mass + 64 max cells + low decay rate + minion start size 48 + pellet mode, then of course performance won't be the best haha

**Comment by raphyjb** [comment]
Adding Pellet mod changes something in server lag?

**Comment by AlexandriteErikParacelsus** [comment]
Yeah, the minions will have the minds of their own so of course it will lag

**Comment by raphyjb** [comment]
Best Private server i saw so far! Love the way u split! Just amazing, u can split run, have fun.. without to much lag... maybe make a website ? So u can add chat and the skins of agario... I want all new skins in agar in my ps, thats why i love your server so much, the <r> skins on bots are just awsome.
Make same as this http://astr.io/ add agar.io skins. so when i use <r> we see the skins on there.

**Comment by raphyjb** [comment]
Players: 10 - Bots: 60
Server has been running for 4651 minutes
Current memory usage: 19/50 mb (this goes to 20-35/50mb)
Current game mode: Free For All
Current update time: 9.035 [ms]  (perfectly smooth) (goes from 8-12ms)

**Comment by Megabyte918** [comment]
@raphyjb Pellet mode does affect performance especially if many people are using it at the same time, but also don't forget all of the other configurations you have set, they also contribute to performance.

**Comment by raphyjb** [comment]
Could you make a site?

**Comment by Megabyte918** [comment]
@raphyjb @FantasyIsBae Is working on a client for this project, be patient :)
