### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#271]
Experiment:

When my server runs 100 bots it consumed about 10% CPU ( measured with HTOP ).
When I add connection with ONE player with Chrome, CPU usage increased upto 100% (float 45-100%)
To decrease CPU usage back to initial value player should be hardly disconnected (client tab closed in browser).
Tested with agario/cigar/alisio. Problem persist from oldest (1.2.69) version.
As for me - it shows a big problem in ws operation on server.

Any thouts?  

Update: this depends of browser I use. With Firefox and IE 11 have only 20-25% on the same condition. 
Incognito window Chrome have 25-45%.

It may depends of extensions and so on, but anyway, server should not depends of browser type imo.

**Comment by Megabyte918** [comment]
@Gimmo A few things:
- Can you send me your gameserver.ini? It would help alot
- What are you hosting your server with? And what are the specifications in which you are running your server off of?

**Comment by Gimmo** [comment]
1. initial - out of box
2/3. VM deb7-64 1 core Xeon 2.66 2GB

**Comment by Gimmo** [comment]
@Megabyte918  It was Google Chrome with its own tasks. It was eating **all** my resources. 100% load on all cores. 
When I kill all its windows and open only IE problems disappear.
I'll check on a real web and report later.
