### ISSUE TITLE
External Minions Get Local Minions

### ISSUE THREAD

**Issue by agariotips** [Megabyte918/MultiOgar-Edited#275]
For some reason, any id marked as a "minion" still gets minions from the server, which is an extreme nuisance and the only way to fix it is by banning each minion individually, which is hard. My scramble level is set to three, it takes them to the edges of the map, and they're gray, but they still get server minions. Any way to fix this?

**Comment by Megabyte918** [comment]
@agariotips What version are you using? Also try changing [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L325) line in GameServer.js to this:
<pre>
if (this.config.serverMinions > 0 && !ws.playerTracker.isMinion) {
</pre>

**Comment by agariotips** [comment]
Latest

**Comment by Megabyte918** [comment]
@agariotips Did changing that line of code do anything?

**Comment by mrzack506** [comment]
I'm not sure yet. It might've fixed it, but I have to test it myself.

**Comment by Megabyte918** [comment]
Closing this for now.
