### ISSUE TITLE
New Console UI 

### ISSUE THREAD

**Issue by FantasyIsBae** [Megabyte918/MultiOgar-Edited#276]
Does anyone want a better Console User Interface ?

**Comment by NiesamoWhite** [comment]
yes me!

**Comment by NameYT** [comment]
Yes Me also :)

**Comment by FantasyIsBae** [comment]
Ok , well i will write a new one as soon as i finnish rewriting the README :)

**Comment by PrinceDark9243** [comment]
YOOOOEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS!

**Comment by AlexHGaming** [comment]
Well?

**Comment by AlexHGaming** [comment]
@FantasyIsBae

**Comment by FantasyIsBae** [comment]
Well shit , didn't get to do it XD 

Ive got a weird habit sorry .

**Comment by FantasyIsBae** [comment]
Il'll do it later on :)

**Comment by systemroot** [comment]
@FantasyIsBae take a look at lolcat meybe you can use it somewhere that do a rainbow color on terminal  https://github.com/busyloop/lolcat will be nice if you change some colors :+1: 

i have think to edit mg-edited terminal interface but well i'm not a nodejs guy :v:
