### ISSUE TITLE
Minion!

### ISSUE THREAD

**Issue by NiesamoWhite** [Megabyte918/MultiOgar-Edited#277]
Hello.
when i want to give some minions for a bot player, the bots don't spawn.
Just, Can you make sure the bots can have minions?

**Comment by FantasyIsBae** [comment]
We already discussed this issue and the answer is no , sorry 

> Fantasy

**Comment by raphyjb** [comment]
lol why would u want that LOL this dude is lonely!

**Comment by FantasyIsBae** [comment]
@raphyjb Don't say that , i know this is not the best suggestion , but no need to freak out about it

**Comment by Jhair2015** [comment]
@raphyjb  lol, your maked a livestream on YT playing with minions on official agario server Haha, Chither... NICE... - U remember me?
