### ISSUE TITLE
How to use COnsole-Plus html?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#278]

**Comment by Megabyte918** [comment]
@NameYT Run it with your browser

**Comment by NameYT** [comment]
@Megabyte918 I already run it 🥉

**Comment by NameYT** [comment]
@Megabyte918 NExt how to connect to the server???? and do commands and stuff

**Comment by Megabyte918** [comment]
@NameYT Take a look at the README in /run.

**Comment by NameYT** [comment]
@Megabyte918 Cant Understand please help :) Steps 1 by 1

**Comment by Megabyte918** [comment]
@NameYT https://github.com/Megabyte918/MultiOgar-Edited/blob/master/run/README.md

**Comment by NameYT** [comment]
@Megabyte918 HELP!!
![untitled](https://cloud.githubusercontent.com/assets/20871314/21489403/41cd6dea-cc25-11e6-8ca3-501a54818304.png)

**Comment by Megabyte918** [comment]
@Gimmo ?

**Comment by Gimmo** [comment]
@NameYT  I can't reproduce this error. 
Do you make any changes in code?
Please describe in details what you do.
