### ISSUE TITLE
How to Combine Skin Script and ERTP Controls on Tampermonkey Script? / Also How to add ERTP on Mgario cilent 

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#279]
The title Says it

so i have to open 1 script this is possible i know
but i just dont know the codes

**Comment by NameYT** [comment]
@Megabyte918

**Comment by NameYT** [comment]
@AlexandriteErikParacelsus

**Comment by NameYT** [comment]
@FantasyIsBae

**Comment by Megabyte918** [comment]
Paste the contents of both scripts into one file and save it. Do not make any more pointless issues.
