### ISSUE TITLE
I CANT USE SKINS

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#28]
I CANT USE SKINS BECAUSE YOUR MULTIOGAR IS NOT COMPATIBLE

ZfsrGhS953 SAID ME :+1: 

Ogar Unlimited client uses protocol 4, which doesn't support custom skins of MultiOgar-Edited. They are only supported for protocols 5 and 6. This is off-topic (please post in https://github.com/AJS-development/OgarUL-Client/issues and https://github.com/Megabyte918/MultiOgar-Edited/issues ), so I'll close this issue.

**Comment by Megabyte918** [comment]
@RelTakeover 

> Ogar Unlimited client uses protocol 4, which doesn't support custom skins of MultiOgar-Edited.

Same goes for regular MultiOgar, I cannot change the protocol or make it support skins as I am not the owner of the client. Again, this is not a problem with the server it's the client you are using, so I can't help you. Please take this over to the OgarUL forums and ask the owners if you really want skins.

**Comment by Megabyte918** [comment]
Also, do not make duplicate issues. They will be closed or It could even result In a ban. This is your 7th issue on this project, half of which are already duplicates. I really don't want to have to start banning people, but if you keep it up I will. If you have any issues regarding the previous issues you made, post your question on those issues, don't just make a new one every time.
