### ISSUE TITLE
Adding bots on Teams gamemode causes Fatal

### ISSUE THREAD

**Issue by Tyler3D** [Megabyte918/MultiOgar-Edited#282]
![capture](https://cloud.githubusercontent.com/assets/19315276/21493690/cf25b77e-cbda-11e6-9201-b013d669890e.PNG)

**Comment by Tyler3D** [comment]
Spawning too

**Comment by Tyler3D** [comment]
I guess this gamemode is broken :/.

**Comment by Megabyte918** [comment]
@Tyler3D Fixed.

**Comment by Tyler3D** [comment]
@Megabyte918 that was fast

**Comment by Tyler3D** [comment]
@Megabyte918 cells can move viruses plus eject mass

**Comment by Tyler3D** [comment]
aka viruses don't work

**Comment by Tyler3D** [comment]
if you split on a virus it does tho wtf

**Comment by Megabyte918** [comment]
@Tyler3D fixed again lol

**Comment by PrinceDark9243** [comment]
more thing that in Teams mode if you ate virus you will not get mass!

**Comment by PrinceDark9243** [comment]
until you are sixteen pieces

**Comment by freaky767** [comment]
In teams mode, you don't grow off viruses..

**Comment by Tyler3D** [comment]
![capture](https://cloud.githubusercontent.com/assets/19315276/21508685/117b5356-cc51-11e6-9086-bcc22cebb50d.PNG)

**Comment by Tyler3D** [comment]
same with LMS

**Comment by Megabyte918** [comment]
@Tyler3D Fixed
