### ISSUE TITLE
Add Cell Render

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#283]

**Comment by Megabyte918** [comment]
?

**Comment by NameYT** [comment]
Cell Render = Even if u are at What Ever Mass
Like Classy :)

@Megabyte918 w0w ur always active :3 <3

**Comment by Megabyte918** [comment]
#217 Client sided issue, this has nothing to do with the server.
> @NameYT It is client sided, just zoom out 50% on the vanilla client (by zoom i mean ctrl + minus) and it will look the same, however @AlexandriteErikParacelsus is right you do need a pretty good computer for it.
