### ISSUE TITLE
Client not working?

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#284]
The Alis.io client isn't working. When I change the port (443) to my regular port (444) it won't let me connect?
I'm not an OgarUL I am an Edited-Master but I can't connect to the official alis.io client.
Server works for the other clients though.
How to fix?

**Comment by PrinceDark9243** [comment]
i think you need to clear cookies of your browser

**Comment by FantasyIsBae** [comment]
@AlexHGaming ^^^^^^^

**Comment by AlexHGaming** [comment]
Why was this closed tho? It's not that.

**Comment by FantasyIsBae** [comment]
This is an issue with alis.io NOT MultiOgar-Edited , that's why its closed .

**Comment by fayizan** [comment]
![screenshot_151](https://cloud.githubusercontent.com/assets/19163419/22402449/338493e6-e61d-11e6-9bdf-07a7d6334fb5.png)

@Megabyte918 I tried to connect with alis.io and got this error, any solution..?

**Comment by Agarian** [comment]
Wait, you can actually use alis.io to connect?

**Comment by Agarian** [comment]
I tried and got the same error actually @fayizan

**Comment by ItzLevvie** [comment]
@fayizan Alis.io has a custom protocol

**Comment by pabloalber84** [comment]
No, alis.io send a extras in playertracker, to send the nameserver, port, etc.

**Comment by Luka967** [comment]
alis.io uses a different protocol.

**Comment by ItzLevvie** [comment]
@pabloalber84 Yeah, I know. I realised that way long ago.

After re-creating the server in Feb with the main_out I got from alis.io and dual-agar I was finally able to connect to both of the clients
