### ISSUE TITLE
Experimental mothercells & CPU charge

### ISSUE THREAD

**Issue by duwayy** [Megabyte918/MultiOgar-Edited#285]
Hello,
I turned game mode to experimental to give it a test
I fed a mothercell to ~8000 and then server started become incredibly slow
I checked CPU usage, and it was using 99% of CPU, instead of the 5-15 % it usually consume
CPU usage still remain at 99% after eating the big mothercell, and I had no other choice to exit and launch again multiogar 

Is it related to spawning food calculation ? Is there a way to avoid that ?

**Comment by Megabyte918** [comment]
Well it depends on how much food has been ejected, if the cell was ~8k mass then it was probably ejecting a ton of food. What are your food configurations set to? Normally the mothercell would stop ejecting food if foodMaxAmount has been reached, but if you increase that value then it will continually eject food until it shrinks back down to normal size and theres nothing left but the 8k mass worth of food left. (aka about 8000 foods)

**Comment by PrinceDark9243** [comment]
@Megabyte918 how to make mothercell spawn 2x mass instead of same mass like 1k mother spawns 2k food

**Comment by Megabyte918** [comment]
@PrinceDark9243 See here: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gamemodes/Experimental.js#L19

**Comment by Megabyte918** [comment]
It's been a week, I'm going to close this for now.
