### ISSUE TITLE
Question : How to Connect To Cellcraft.io?? to my Private Server

### ISSUE THREAD

**Issue by JadenTomori** [Megabyte918/MultiOgar-Edited#287]
The Title Say's it
Im a newbie :)

@Megabyte918 
@AlexandriteErikParacelsus 
@FantasyIsBae 
![image](https://cloud.githubusercontent.com/assets/24810162/21522854/17647fe2-cd44-11e6-81ee-06321ae47682.png)

**Comment by AlexHGaming** [comment]
I think 
cellcraft.io/?ip=localhost:443
Or change the 443 to your gameserver.ini port.

**Comment by JadenTomori** [comment]
@AlexHGaming Thanks, but that doesn't work either :) and i'm a girl gamer nice to meet you :)

**Comment by RasyiidWho** [comment]
Why you want connect your server in cellcraft client? try other client, bfc-project.com/freebots/?ip=localhost:443

Sorry for bad english.

**Comment by JadenTomori** [comment]
@RasyiidWho Because CellCraft Cilent Is Awesome :) And Also My friend says that its called "Socket Close or Open"

**Comment by Megabyte918** [comment]
I don't think you can. Also this is a client sided issue and has nothing do do with the server so I am closing.

**Comment by FantasyIsBae** [comment]
@JadenTomori @RasyiidWho @Megabyte918  

This is both client-sided and server-sided

1. Multiogar cannot send any 'hello' packet to the cellcraft client .
2. There's a BIG compatability issue with the physics .
3. The client cannot recieve any server packets apart from the ones listed on a URL list (Cellcraft way of saying FUCK YOU)
4. Socket errors everywhere XD

**Comment by FantasyIsBae** [comment]
I can have a go at making a server for cellcraft but i doubt it will work XD

**Comment by Jhair2015** [comment]
@FantasyIsBae  Nice Example Haha :))

**Comment by FantasyIsBae** [comment]
@Jhair2015 Thanks XD

**Comment by Jhair2015** [comment]
@FantasyIsBae Hahaha lmaooo..

**Comment by JadenTomori** [comment]
@FantasyIsBae Make me xD

**Comment by AlexandriteErikParacelsus** [comment]
aaaaaaa

**Comment by JadenTomori** [comment]
@FantasyIsBae Make meh da Cellcraft serv
xD

**Comment by ItzLevvie** [comment]
^ Only the protocol needs updating

**Comment by FantasyIsBae** [comment]
@ItzLevvie ^

**Comment by ItzLevvie** [comment]
^

**Comment by Megabyte918** [comment]
^

**Comment by FantasyIsBae** [comment]
^

**Comment by Jhair2015** [comment]
^ lol
