### ISSUE TITLE
Same IP

### ISSUE THREAD

**Issue by BrunoOlyver** [Megabyte918/MultiOgar-Edited#288]
![pngngpnpg](https://cloud.githubusercontent.com/assets/17687906/21523910/3e7625e0-ccf9-11e6-81db-126e9e295dea.png)

**Comment by Megabyte918** [comment]
@BrunoOlyver What are you using to host?

**Comment by BrunoOlyver** [comment]
IDE codeanywhere

**Comment by MastaCoder** [comment]
Please don't tell me you're using that for a production server.

**Comment by ZfsrGhS953** [comment]
I think codeanywhere isn't supposed to be used as a VPS, that's why it has some things like this.

**Comment by Megabyte918** [comment]
@ZfsrGhS953 Yes^^ 
@BrunoOlyver Closing.
