### ISSUE TITLE
cell switching order

### ISSUE THREAD

**Issue by Ralphwaldopicklechips** [Megabyte918/MultiOgar-Edited#289]
How to get rid of cells switching when doublesplit? it really annoying :(

**Comment by AlexHGaming** [comment]
I don't have this issue?

**Comment by Tyler3D** [comment]
@Ralphwaldopicklechips But, that's what real agar.io looks like.

**Comment by Tyler3D** [comment]
Try double splitting slower

**Comment by Jhair2015** [comment]
@Tyler3D  Ubication?

**Comment by Tyler3D** [comment]
@AlexHGaming When you double split fast, the two end pieces switch.

**Comment by Tyler3D** [comment]
@Jhair2015 Huh?

**Comment by Ralphwaldopicklechips** [comment]
@Tyler3D in agario it doesnt happern alot but here is happens every time

**Comment by Megabyte918** [comment]
@AlexHGaming An example of what he means is this: https://streamable.com/krkm6 (ignore the sounds of my keyboard lol)
@Ralphwaldopicklechips is right, its not supposed to happen as often as it does. In agario most of the time they do not switch order, no matter what speed you split at. 
I don't know Ralph, this is a problem I've been trying to solve for weeks. You can reduce the rate of it happening by reducing the split velocity, but that's pretty much it. I am pretty noob so this will probably take me a while to find the cause/fix, but for now I am going to leave this open with an issue label.

**Comment by raphyjb** [comment]
yah but in real agar its like that if ur to close, but if u put ur minion abit furthur u will it

**Comment by AlexHGaming** [comment]
Raphy do you remember Weevilated who gave you the old OgarUL server files
and helped you how to get fans to play on the server?

**Comment by raphyjb** [comment]
1st, who is Weevilated, 2nd i got the old ogarUL server files. Now wats up?

**Comment by AlexHGaming** [comment]
Remember him? He was your first person to give you the files. Maybe Hypzter
then?

**Comment by AlexHGaming** [comment]
The 'HOW TO MAKE AN AGARIO PRIVATE SERVER' video with voice?

**Comment by AlexHGaming** [comment]
I'm Hypzter.

**Comment by raphyjb** [comment]
lol
kk

**Comment by AlexHGaming** [comment]
So when I play on your server at least give me some mass boosts (spawnmass)
because I was your first :)

**Comment by raphyjb** [comment]
lol wats ur ip

**Comment by raphyjb** [comment]
can u give mass with ip anyways?

**Comment by AlexHGaming** [comment]
Ask @Megabyte918

**Comment by Megabyte918** [comment]
@raphyjb See: #13 or #205

**Comment by AlexHGaming** [comment]
#13 I know how to do that.
same to #205
We mean SPAWNING in MASS not minions
How do you do that?

**Comment by Megabyte918** [comment]
Oh you meant spawning mass! I must have read it too quickly. Someone has already asked your question here: #262

**Comment by AlexHGaming** [comment]
@raphyjb
Thanks Megabyte

**Comment by freaky767** [comment]
rewriting the splitting code may be an option.

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by Megabyte918** [comment]
@Ralphwaldopicklechips Recent updates should have reduced the rate of them switching.

**Comment by AlexHGaming** [comment]
@Megabyte918 Where about are the lines of the code for me to play around with the values?

**Comment by Megabyte918** [comment]
There are no values for cell switching.

**Comment by AlexHGaming** [comment]
#523 is where I MIGHT of found a solution

**Comment by AlexHGaming** [comment]
@Megabyte918 Can you maybe rewrite the rigid collison and add some values to the extrusion force? 
@Luka967 please can you make a commit with definements on how you fixed your doublesplitting? Because I'm sick and tired of doing a double split tricksplit with a very massive part as a 3rd 😂😂
I'm not stressing, just a bit of so called 'advice'

**Comment by Luka967** [comment]
lol, I didn't even commit the so called fixes

**Comment by AlexHGaming** [comment]
This'll be the longest bug on this repo 😆

**Comment by Tyler3D** [comment]
30... now 31 comments

**Comment by Luka967** [comment]
kden

**Comment by Megabyte918** [comment]
Fixed

**Comment by AlexHGaming** [comment]
@Megabyte918 yay, now this isn't gonna be the longest bug on the repo now :D
