### ISSUE TITLE
Help Me!! for map food

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#29]
Can you tell me what is the correct setting for the food on the map! :)

The default setting gives me some lag in codeanywhere and is not the most similar to Vanilla : /

**Comment by Megabyte918** [comment]
@Jhair2015 try changing the `foodSpawnAmount` config to 1000, looked pretty vanilla to me. But the more food that spawns the more lag there will be.

**Comment by Jhair2015** [comment]
mmm... ok THX!:)
