### ISSUE TITLE
You can't grow from pellets

### ISSUE THREAD

**Issue by Tyler3D** [Megabyte918/MultiOgar-Edited#290]
In agar.io you can still grow from pellets after ~600 mass. Only 10 mass cells don't increase your size.
https://www.youtube.com/watch?v=Tts9NHL8D8I

**Comment by AlexHGaming** [comment]
I swear there's a feature of this somewhere in the advanced section of the server.
(There WAS one in OgarUL and there still is but I don't seem to find it in the Multi-Ogar Edited Master.)

**Comment by Tyler3D** [comment]
There is a config. But, it allows you to grow from everything after 600 mass

**Comment by Megabyte918** [comment]
@Tyler3D Fixed.
