### ISSUE TITLE
How to Start LMS gamemode?

### ISSUE THREAD

**Issue by JadenTomori** [Megabyte918/MultiOgar-Edited#291]
Hi , I need help for LMS Gamemode. It seems it doesn't start when i did on the gamerserver.ini `serverGamemode = 4` How can i start the Last Man Standing If i joined the server
Sorry for Bad English :)
![image](https://cloud.githubusercontent.com/assets/24810162/21532769/5455bf70-cd8e-11e6-8219-19329537104e.png)
@Megabyte918

**Comment by AlexHGaming** [comment]
This happens to me too.
@Megabyte918

**Comment by AlexandriteErikParacelsus** [comment]
o rly?

**Comment by JadenTomori** [comment]
@AlexandriteErikParacelsus How can i start it? <3

**Comment by Megabyte918** [comment]
@JadenTomori Does it work after the latest update?

**Comment by JadenTomori** [comment]
@Megabyte918 Totally Not, my plan is "When i join the server and Add Player Then i can start LMS now"
You sir should make a command like `lms start` thing

**Comment by JadenTomori** [comment]
@Megabyte918 Also Sir I found out that MineMoore Edited MultiOgar can run 1000 bots and do pellet mode with them, also no lag at all :)

Link : https://www.youtube.com/watch?v=Wu9FkvxwLvg

**Comment by Tyler3D** [comment]
@JadenTomori He changed the code

**Comment by Megabyte918** [comment]
@JadenTomori See this comment: https://github.com/Megabyte918/MultiOgar-Edited/issues/162#issuecomment-265631332

**Comment by JadenTomori** [comment]
@Megabyte918 Maybe you can do what Mine Moore Did to the server? It alot better no lag at 1000 bots :)
^_^

**Comment by Megabyte918** [comment]
@JadenTomori I don't know what he did or edited haha, but you can ask him yourself. Closing this for now.
@MineMooreALT

**Comment by JadenTomori** [comment]
@Megabyte918 Ok sure :) Thanks for being nice

**Comment by AlexandriteErikParacelsus** [comment]
@JadenTomori Welcome to MultiOgar-Edited the most nicest place on GitHub

**Comment by JadenTomori** [comment]
@AlexandriteErikParacelsus Thanks <3
