### ISSUE TITLE
Help Wanted : How to add ERTP Controls to my Cilent?

### ISSUE THREAD

**Issue by JadenTomori** [Megabyte918/MultiOgar-Edited#292]
Also i dunno how to host a cilent
i just want a copy of Zgar.ml
@Megabyte918 @FantasyIsBae

**Comment by AlexandriteErikParacelsus** [comment]
Why do we discussing client here

**Comment by Megabyte918** [comment]
@JadenTomori  just add it using the <script> tags, or just import it from the file somewhere else.

**Comment by JadenTomori** [comment]
@Megabyte918 Srry, But i really dont understand you..... But can you screenshot it?

**Comment by Megabyte918** [comment]
@JadenTomori Heres an example:
<pre>
<script>
"insert code from ERTPcontrol.js here"
</script>
</pre>
or you can use:
<pre>
<script src="ERTPcontrol.js"></script>
</pre>
To import the script from an external source.

**Comment by JadenTomori** [comment]
@Megabyte918 umm. Where i will place it?

**Comment by AlexandriteErikParacelsus** [comment]
@JadenTomori I talked to him through c9.io and Mega said he has no ideas

**Comment by JadenTomori** [comment]
@AlexandriteErikParacelsus I found it :)
Just enable "See Hidden Files"
Shall i upload it here?
It will make the server non-lag even running at 1000 Bots
"if u run 100 bots u get lag" "why?" "Settings : foodMaxAmount:17000 and FoodMinAmount 17000"
Shall i @Megabyte918

**Comment by JadenTomori** [comment]
@AlexandriteErikParacelsus BTW Who is this Mega? You're Talking about?

**Comment by Megabyte918** [comment]
what

**Comment by MastaCoder** [comment]
@JadenTomori If you're using the older version of Cigar, check one of the latest commits related on how adding the ERTP controls. They were adding to Cigar in a commit a bit back.

**Comment by AlexandriteErikParacelsus** [comment]
@JadenTomori the only mega that is in this issue

**Comment by JadenTomori** [comment]
@AlexandriteErikParacelsus Oh it was just a short name "Mega" "MegaByte918" srry ahaha @Megabyte918
