### ISSUE TITLE
How to make Gamemode like dual-agar?

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#294]
In dual-agar, I can control 2 cell if I press the Q (not a minion). It's possible in MultiOgar-Edited?

Here the link, http://dual-agar.online/

Sorry for bad english.

**Comment by Tyler3D** [comment]
@RasyiidWho If you know javascript. Just read the gamemode files and create your own.

**Comment by Tyler3D** [comment]
Pretty much any gamemode you can think of is possible in MultiOgar

**Comment by AlexandriteErikParacelsus** [comment]
I think megabyte won't gonna add this gamemode

**Comment by Megabyte918** [comment]
@RasyiidWho What @Tyler3D said, I don't think im going to add this gamemode myself just yet (although its a pretty cool idea) I have alot of other things to work on I don't really have the time, but for a gamemode like that you are going to have to make it so it spawns 2 cells at once, the player can control both, and the player's viewbox switches between cells when they press Q (code can be done in PacketHandler)
