### ISSUE TITLE
[QUESTION] How to give minion's to Bots?

### ISSUE THREAD

**Issue by JadenTomori** [Megabyte918/MultiOgar-Edited#295]
How? Please Answer. I close this issue if its done :)
@Megabyte918

**Comment by t11tanYT** [comment]
For a temporary fix you can remove the !this.owner.socket.isConnected || from this line here:
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/MinionPlayer.js#L23
but it breaks minions disconnecting when the owner leaves, I will have to figure out a way to separate bots and minions further but for right now just do that.

**Comment by JadenTomori** [comment]
@t11tanYT Thanks, for the help... but. i Already Tried that...... "Error" Now it doesn't let me or anyget give bots :3

**Comment by t11tanYT** [comment]
@JadenTomori Check your id in playerlist and give bots again

**Comment by JadenTomori** [comment]
@t11tanYT Tried it, Just disappear

**Comment by JadenTomori** [comment]
@Megabyte918 I just wait for megabyte i closin this now :)

**Comment by Megabyte918** [comment]
@JadenTomori Yep, just do what @t11tanYT said. If you did it correctly it should not throw an error.

**Comment by JadenTomori** [comment]
@Megabyte918 Shall i delete it? And Leave the space? Then Save? I tried it. `minion 1 1000 trolols`
Minions disapper

**Comment by Megabyte918** [comment]
@JadenTomori 
Remove `!this.owner.socket.isConnected || `
 from `if (!this.owner.socket.isConnected || !this.owner.minionControl)`

All that is left should be:
`if (!this.owner.minionControl)`

**Comment by JadenTomori** [comment]
@Megabyte918 Oh That's why i delete the whole part ^^
