### ISSUE TITLE
Found a way to Connect to Cellcraft But There is a problem

### ISSUE THREAD

**Issue by JadenTomori** [Megabyte918/MultiOgar-Edited#297]
`setserver("localhost:444")`

By Doing this to the Console

And you get this error

![image](https://cloud.githubusercontent.com/assets/24810162/21542720/d09d3a7e-cdfa-11e6-8ca5-4cb66afa71db.png)

**Comment by JadenTomori** [comment]
You can connect on every cilent with this

**Comment by JadenTomori** [comment]
@Megabyte918 @AlexandriteErikParacelsus @FantasyIsBae Maybe you know this?
If this is a Cilent Sided or Server Sided Thing i Close it up :3

**Comment by AlexHGaming** [comment]
Probs because Multi-Ogar doesn't support the cellcraft client

**Comment by JadenTomori** [comment]
@AlexHGaming Nope It supports, :) But doesn't let connection

**Comment by ZfsrGhS953** [comment]
This is not the original MultiOgar-Edited. Original version should appear in chat as "MultiOgar-Edited 1.4.8"

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Yup Its not :) Its mine Moore Edited Version It can handle 1000 Bots FAST SERVER!1 :)

**Comment by JadenTomori** [comment]
@ZfsrGhS953 I downloaded this from MineMoore YouTube Video, It can activate pellet mode while in 1000 BOTS

"100 BOTS = LAG" "1000 BOTS = NO LAG"
MAX FOOD "17000" MAX MIN FOOD "SAME"

**Comment by ZfsrGhS953** [comment]
Yes, it has the original collect pellets feature made by me that can be activated by Q at any minion amount and doesn't lag a lot. https://github.com/Megabyte918/MultiOgar-Edited/commit/d86e285461e4290a75fbcc87c3e58e6f5d953097

**Comment by ZfsrGhS953** [comment]
Anyways, updating MultiOgar-Edited won't do anything as the CellCraft protocol isn't supported in any version.

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Is there any Server to make it private? so i can play?

**Comment by ZfsrGhS953** [comment]
The list of clients is in README.md - look for "Ogar clients"

**Comment by JadenTomori** [comment]
@ZfsrGhS953 No i mean only Compatible with Cellcraft.io also there is an error tho.... socket close
do you know how to bypass it? What do cellcraft use protocol srry for bad english<3

**Comment by ZfsrGhS953** [comment]
Why do you want to use the cellcraft.io client?

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Becausei wanna test it P4rty guy know it but wont tell me, he said he will ddos me :(

**Comment by ZfsrGhS953** [comment]
Test what?

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Test if Cellcraft Supports MultiOgar

**Comment by JadenTomori** [comment]
@ZfsrGhS953 I wanna make Bot Video with it like Polar bots :)

**Comment by ZfsrGhS953** [comment]
It doesn't. If it did, the screen wouldn't be filled with a single color.

**Comment by JadenTomori** [comment]
@ZfsrGhS953 U and Partyguy close friend?

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Partyguy Used Cellcraft.io to connect to mgar.io omfg how

**Comment by JadenTomori** [comment]
I think something is blocking the communtiction wait let me send u the error i get

**Comment by JadenTomori** [comment]
![image](https://cloud.githubusercontent.com/assets/24810162/21545094/bb8ceee4-ce0f-11e6-8d87-b6744fbf89a0.png)
![image](https://cloud.githubusercontent.com/assets/24810162/21545101/c955e3d2-ce0f-11e6-805d-b24005443c08.png)

**Comment by JadenTomori** [comment]
@ZfsrGhS953

**Comment by ZfsrGhS953** [comment]
This error occurs when the client and server protocols are different.

**Comment by JadenTomori** [comment]
@ZfsrGhS953 
![image](https://cloud.githubusercontent.com/assets/24810162/21545131/fc1bd128-ce0f-11e6-83d6-8697f8c29523.png)lol wtf is dis

**Comment by JadenTomori** [comment]
@ZfsrGhS953 What do Cellcraft Protocol use ?

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Do you know how to make ERT Work on mgar.io? Also how can i add All Command? After doing /login nothin happnes

**Comment by ZfsrGhS953** [comment]
It uses a custom protocol that is sent to the server as 5

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Is there any cilent that is similar to Cellcraft.io that i can use to connect?

**Comment by ZfsrGhS953** [comment]
Cellcraft.io uses a modified version of this client: http://ogar.mivabe.nl/

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Okay thanks :)

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Do you know how to make ERT Work on mgar.io? Also how can i add All Command? After doing /login nothin happnes

**Comment by ZfsrGhS953** [comment]
What do you mean by "All Command"? The console commands?

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Ye

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Like Mgar.io

**Comment by ZfsrGhS953** [comment]
I don't have the source code of Mgario's servers, so it's not possible to directly copy them.

**Comment by JadenTomori** [comment]
@ZfsrGhS953 Ask Razor?

**Comment by ZfsrGhS953** [comment]
Mgar.io sends packets through WebSocket in a different way, so the userscript's way of intercepting WebSocket messages won't work on it, and so, when you press E,R,T or P, the keys are going to stay pressed from the userscript's view forever, because it doesn't detect packets sent to the server.

**Comment by JadenTomori** [comment]
only q works 4 pellet mode lol

**Comment by JadenTomori** [comment]
but thanks :)

**Comment by MineMooreALT** [comment]
There is nothing different in the protocol in my version so there should be no differnce
