### ISSUE TITLE
I can´t merge

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#298]
I can´t merge configuring this, PLZ help me! (#238)

**Comment by Jhair2015** [comment]
-_-  @AlexByte918 There is a configuration in gameserver.ini for mobile physics, USELA!

**Comment by AlexByte918** [comment]
@Jhair2015 Ohhhh, can you plz pass me the issue?

**Comment by AlexByte918** [comment]
@Jhair2015 Hablass español? :V

**Comment by Megabyte918** [comment]
@AlexByte918 gameserver.ini: `mobilePhysics` config.

**Comment by Jhair2015** [comment]
@AlexByte918  Sí xD
