### ISSUE TITLE
Add minions? :)

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#3]

**Comment by AlexandriteErikParacelsus** [comment]
He has minions, but few people can access (included me). He doesn't want to add here because Andrews said that "do not steal my code and stuff" so he keeps it private

**Comment by Jhair2015** [comment]
:D great

**Comment by AlexandriteErikParacelsus** [comment]
He already made the minions, he still fixing some bugs so be patient.

**Comment by Megabyte918** [comment]
@Jhair2015 they will be finished, just be patient. You can keep up with the bug fixes [here](https://github.com/Megabyte918/MultiOgar-Edited/projects/1).

It's coming together quite nicely so far, all thats left is those bugs and then I can upload the code to here for everyone to use. 

This is what is looks like so far with 600 minions: https://streamable.com/eooe

Sorry if the quality is a little bad, my computer isn't powerful enough to record in 1080p :)

**Comment by Jhair2015** [comment]
Ok no problem :)
