### ISSUE TITLE
How to connect to my server on Ogario! :)

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#30]
Hey Megabyte!

I want to know how to connect to my server with this extension! :)

http://cdn.ogario.ovh/v3/ogario.v3.user.js

Is the Ogario V3, every time I enter with my server, the link is modified, I tried to put in the console of agar.io connect (ws ....) and also core.connect (ws // ...)

**Comment by systemroot** [comment]
delete this 
```
// Check location
if (location.host == "agar.io" && location.pathname == "/") {
    location.href = "http://agar.io/ogario" + location.hash;
    return;
}
```
then connect as normal http://agar.io/?ip=IP:PORT

**Comment by Jhair2015** [comment]
@systemroot  Thanks
