### ISSUE TITLE
How to change the explotion of virus [Question :C)

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#301]
Last, No its possible change the explotion?

**Comment by AlexandriteErikParacelsus** [comment]
no

**Comment by Megabyte918** [comment]
@AlexByte918 Please view other issues before making duplicates.

**Comment by AlexandriteErikParacelsus** [comment]
You will get ban from this project if you don't stop. NameYT already got banned
