### ISSUE TITLE
Request Some Friends To Help 

### ISSUE THREAD

**Issue by kareemman00** [Megabyte918/MultiOgar-Edited#305]
I Request @Megabyte918 @FantasyIsBae @MineMooreALT To Send Me Help On www.facebook.com/4rm.a2z

**Comment by AlexandriteErikParacelsus** [comment]
wat

**Comment by JadenTomori** [comment]
hahaha

**Comment by Megabyte918** [comment]
This has nothing to do with thye project, Im pretty sure

**Comment by Jhair2015** [comment]
@Megabyte918  If it has to do, I think he wants you to help him with the ext for official server's, a copy of raga or something.
