### ISSUE TITLE
merge time

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#309]
Is it possible to make merge time more percist? cuz when i put it to 0, well its to fast for poeple to actually do a popsplit. Right now u eat virus and not even 0.05 sec ur all together... I want it to take more time but when ido on console 0.00000000000000000005 doesnt change anything it only takes whole numbers
*time in ticks it takes for a cell to recombine, on ogarul it had that but not on this one

**Comment by AlexandriteErikParacelsus** [comment]
0.00000000000000000005 is smaller than 0.05....... So you want it to be merge faster or slower? what

**Comment by AlexHGaming** [comment]
The higher the value, the more longer it takes to recombine.
0 is the lowest you can get (which is basically instant merge)
Raphy I don't know what you mean by 'fast enough to make a popsplit' 
You mean when people can't hit a popsplit because people are splitting away?
Explain for me.

**Comment by raphyjb** [comment]
no the time u try to popsplit someone they merge back if there like 20k...

**Comment by raphyjb** [comment]
http://agar.io/?ip=184.75.143.92:442
try it ull see wat i mean

**Comment by Tyler3D** [comment]
@raphyjb XD can you give me minions?

**Comment by Tyler3D** [comment]
im bored

**Comment by raphyjb** [comment]
i give 1 minion because server is laggy, playing and tell me if u lag!

**Comment by Tyler3D** [comment]
it's really laggy :/

**Comment by raphyjb** [comment]
exactly ill take out all bots for now cuz this server is bad

**Comment by Tyler3D** [comment]
Im blue

**Comment by raphyjb** [comment]
i cant really do anything, give mass all i can do.. without making server ultra laggy

**Comment by raphyjb** [comment]
https://discord.gg/kxZa62z
join my discord

**Comment by Tyler3D** [comment]
im second xD

**Comment by Tyler3D** [comment]
reck by jumbo

**Comment by raphyjb** [comment]
@AlexandriteErikParacelsus Even if i write down 0.9999999999999 still takes alot more time then 0, all i want it that the merge takes just a little bit longer so u that the cells dont have time to pop on virus and merge instantly

**Comment by Tyler3D** [comment]
oh so, your screwwing with the merge time xD

**Comment by raphyjb** [comment]
ya need help on that

**Comment by Tyler3D** [comment]
@raphyjb Write Blue is king on the leaderboard xD

**Comment by Tyler3D** [comment]
I recked everybody already

**Comment by raphyjb** [comment]
lol pretty laggy tho

**Comment by Megabyte918** [comment]
@raphyjb I can do tricks just fine at 20k without recombining

**Comment by raphyjb** [comment]
@Megabyte918 Yea but u cannot throw a virus and double split like in alis.io
all i wanna do it like there instant pretty much

**Comment by Megabyte918** [comment]
@raphyjb Looks fine to me: https://streamable.com/jdumd

**Comment by Jhair2015** [comment]
@raphyjb 
1. - I think he knows what he is talking about, he wants instant as well. Well here it is.

     - https://github.com/G047/Multi-Ogar-Anti-Bot - 

      This does not have solved popsplits which is very similar to Instant Alis.io

2. - If you do not want that, you want something like MegaSplit or instant union as the speed of light XD
Go to this Issue.

https://github.com/Barbosik/MultiOgar/issues/162

**Comment by raphyjb** [comment]
alright the problem is that urs is different my playerMaxCells = 400 and playerMinSize = 60

**Comment by raphyjb** [comment]
@Jhair2015 why u say i think he knows what he is talking about, no worry, i know that he knows what his doing or else i would be here.

**Comment by Jhair2015** [comment]
@raphyjb  What? I did not understand anything about what he wrote to me last night

I do not speak English fluently and I need a translator to understand :p

**Comment by raphyjb** [comment]
oh ok. Its ok

**Comment by Megabyte918** [comment]
@raphyjb Still works fine for me with your configurations, did you edit anything regarding the physics?

**Comment by raphyjb** [comment]
Nop, play on my private server ill be playing, ill show u @Megabyte918

**Comment by Megabyte918** [comment]
Can you just send me your gameserver.ini? Then I can take a look and see what's wrong with it

**Comment by raphyjb** [comment]
@Megabyte918 http://pastebin.com/Y8TDTvvx

**Comment by Megabyte918** [comment]
@raphyjb I just tested it out and I can still do what I did in the video I posted earlier.

**Comment by Megabyte918** [comment]
@raphyjb Did you mean that the player BEING popsplitted recombines too quickly afterward? If so just reduce the recombine time, otherwise thats not really a problem that can be fixed

**Comment by JadenTomori** [comment]
@Megabyte918 
I think he mean the "Agarly Hero Mode" Recombine :)

**Comment by AlexandriteErikParacelsus** [comment]
@JadenTomori No, he wants to merge instantly but not merge so fast like it needs to have 1 second cool down or something like that

**Comment by raphyjb** [comment]
exactly wat i want @AlexandriteErikParacelsus but even if i change time on the recombine time always take alot more time, if i put 0, takes me 0 sec remerge, if i put in 0.1 well takes me like 20 secounds...

**Comment by raphyjb** [comment]
@JadenTomori Hero mode, i know how to do that aint that complicated lol i dont want that..

**Comment by raphyjb** [comment]
@Megabyte918 thats exactly wat i meant.

**Comment by Megabyte918** [comment]
@raphyjb 
<pre>
# playerRecombineTime: Base time in seconds before a cell is allowed to recombine
playerRecombineTime = 30
</pre>
It is the base amount of time, then that time goes up as cell size increases or changes by cell age, works the same as in vanilla servers.

Anything below that will do the same thing, it will increase as cell size increases or reset/change by cell age.
So its either base = 30 for the base recombine time, or base <= 0 for instant merge.

**Comment by raphyjb** [comment]
do u think its possible to make it so that cell doesnt have age?

**Comment by Megabyte918** [comment]
@raphyjb Doing so would cause many collision issues, the age of the cell is used to calculate many things, such as:
- [When you are not allowed to recombine](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L649)
- [When cells ignore collision after you split (collision restore ticks for splitting)](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L771)
- [Whether or not you can eat your own cells during recombine](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L819)

**Comment by raphyjb** [comment]
alright thanks for help, also happy new years m8
