### ISSUE TITLE
PLS. HELP WITH MAH SLITHER SERVER XD

### ISSUE THREAD

**Issue by Steve7914** [Megabyte918/MultiOgar-Edited#310]
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server
https://github.com/RowanHarley/Slither-Server

**Comment by Steve7914** [comment]
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 
@Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918

**Comment by JadenTomori** [comment]
@Steve7914 Stop Making Spams!! Also these are not part of the Project so Close it!

**Comment by JadenTomori** [comment]
@AlexandriteErikParacelsus @FantasyIsBae Please Close This Issue.. Its Useless

**Comment by AlexHGaming** [comment]
@Megabyte918 @AlexandriteErikParacelsus @FantasyIsBae  CLOSE THIS!
NOTHING TO DO WITH MULTI-OGAR EDITED

**Comment by AlexHGaming** [comment]
Close #310

**Comment by FantasyIsBae** [comment]
@Steve7914 Go fuck yourself

**Comment by AlexHGaming** [comment]
@FantasyIsBae lol "welcome to Multi-ogar edited master, the nicest place on Github" lmfao

**Comment by FantasyIsBae** [comment]
I know i know , no need to thank me XD

**Comment by FantasyIsBae** [comment]
But, being serious we do need to keep some form of moderation around here @AlexHGaming

**Comment by AlexHGaming** [comment]
haha

**Comment by AlexHGaming** [comment]
Meh you have to show trust

**Comment by AlexHGaming** [comment]
And be known as 'not being a faggot who removes everything' lol

**Comment by JadenTomori** [comment]
@FantasyIsBae I trust :)

**Comment by AlexHGaming** [comment]
same to me, but I don't ask

**Comment by FantasyIsBae** [comment]
Well first you need to ask @Megabyte918 ,
Also we've only just got to speak to you recently 
So , i know i'll sound bad in this , but we don't trust you fully yet @JadenTomori

**Comment by JadenTomori** [comment]
@FantasyIsBae Oh okay :) I just wait :) I only want a permission to close Invalid and Nothin to do with the Project :) To add tags like that

**Comment by AlexHGaming** [comment]
I'm the one trying to help with the issues.
I don't code but I can help the 'low-medium difficulty' issues, such as problems with minions and all that.
Then I'm just there begging on my hands and knees waiting for a collabrator to remove a very useless issue lmfao

**Comment by JadenTomori** [comment]
@AlexHGaming Yah me 2

**Comment by FantasyIsBae** [comment]
Sounds good @JadenTomori 
And @AlexHGaming if u are not online then he can help :D

**Comment by JadenTomori** [comment]
@FantasyIsBae She*

**Comment by JadenTomori** [comment]
@FantasyIsBae Also Where is the Forum you are talkin about?

**Comment by AlexHGaming** [comment]
@FantasyIsBae Also what about the console UI? xD

**Comment by FantasyIsBae** [comment]
@JadenTomori Oops sorry

I'm planning to start work on that today @AlexHGaming

**Comment by FantasyIsBae** [comment]
The forums , is what im planning to do sometime next year as @Megabyte918 thinks its too early

**Comment by FantasyIsBae** [comment]
@JadenTomori Are you a developer by any chance

**Comment by JadenTomori** [comment]
@FantasyIsBae Totally not :) But i develope agario clone bots.. :) Also all i know is HTML/LOGIN SYSTEM THINGs

**Comment by AlexHGaming** [comment]
'clone bots' -_-

**Comment by FantasyIsBae** [comment]
@AlexHGaming Nothing wrong with that XD , i do it myself

**Comment by AlexHGaming** [comment]
tbh I don't even though what clone bots are. Are they like the old agar bots?

**Comment by FantasyIsBae** [comment]
Yes , similar depends on how you make them

**Comment by AlexHGaming** [comment]
ohhh ok

**Comment by JadenTomori** [comment]
@AlexHGaming @FantasyIsBae Its just Ogar Feeder :) It doesn't lag the Server . It lag the one who is using it :)

**Comment by FantasyIsBae** [comment]
@JadenTomori Well , i don't use ogar feeder , i have my own personal bots , as i don't like Ogar Feeder

**Comment by AlexHGaming** [comment]
I just use the default ones set in the multi-ogar files.

**Comment by FantasyIsBae** [comment]
Yep thats a lot different , as thats provided internally not externally to/from the server

**Comment by JadenTomori** [comment]
@FantasyIsBae Guys There is a new Agar Right? "Dual Agar" Do any of u know how to connect to my private server?

**Comment by AlexHGaming** [comment]
Dual Agar isn't new. You can't connect to it with a private server.... can
you?

**Comment by JadenTomori** [comment]
@AlexHGaming Cant lol Problem? "TOO MANY SOCKET ERROR" ^^

**Comment by AlexHGaming** [comment]
?

**Comment by JadenTomori** [comment]
@FantasyIsBae You dont know sockets do you? They are the one that disable to join private server :3 like cellcraft.io

**Comment by FantasyIsBae** [comment]
I do know a fair bit about sockets yes :)

**Comment by JadenTomori** [comment]
@FantasyIsBae Hahaha I wish there was a chat for MutliOgar-Edited so we won't chat or spam any issues :3

**Comment by Jhair2015** [comment]
@FantasyIsBae  Can I be a moderator? XD lmao
I know some things about this and I can help some to solve some things, and eliminate dupicados or that have nothing to do with the project.

**Comment by AlexHGaming** [comment]
1. You need to ask @Megabyte918
2. You can't just ask for moderator, you have to be trusted manually
depending on what you do.

**Comment by Jhair2015** [comment]
@AlexHGaming  OK.
