### ISSUE TITLE
How to increase Bots Smartness etc,..

### ISSUE THREAD

**Issue by fayizan** [Megabyte918/MultiOgar-Edited#311]
Hi Megabyte, I love and enjoyed your version of both Multiogar and Ogarul.
Here is the problem that I faced in your multiogar version 
`Noob Bots`
`Rainbow Mode doesnt show up leaderboard`
`Consoleplus not working for me :(`

**Comment by AlexHGaming** [comment]
Eh.
 - You can change the bot's smartness yourself but if you don't know how to code then, I don't know. Depends what you mean by the bot's smartness.
-  What do you mean by rainbow mode on the leaderboard? Do you mean the coloured text on the leaderboard?

**Comment by JadenTomori** [comment]
@fayizan Yes You can make Bots Very Smarter @Megabyte918 will code it but it will increase the lag because of the calculation of the moves of the bots

**Comment by AlexHGaming** [comment]
@fayizan 
@jadentomori is right.

**Comment by AlexHGaming** [comment]
I'm actually a bad coder, but what is the console plus? I see it in the files but I'm not sure on what it is...

**Comment by AlexHGaming** [comment]
If you want to edit a bit of the bots.
`Go to src`
`Go to ai`
`Open Botplayer`
Edit there.

**Comment by FantasyIsBae** [comment]
@AlexHGaming Console Plus is a web console

**Comment by AlexHGaming** [comment]
What's a web console though?

**Comment by JadenTomori** [comment]
@AlexHGaming It was made by @Ginmo :) It allows you to make your console go into a web made by HTML Codes :)

**Comment by AlexHGaming** [comment]
ohhh
kk

**Comment by JadenTomori** [comment]
@AlexHGaming Anyone can use it to connect to the console directly :) U can edit it here :) ip 🥉

**Comment by JadenTomori** [comment]
@AlexHGaming What he mean in Rainbow mode like "Agarly.com" TOP 1 - TOP 3 With Colors

**Comment by AlexHGaming** [comment]
oh yeah
Can't you change it in the leaderboard settings? @fayizan

**Comment by JadenTomori** [comment]
@AlexHGaming I think he mean random colors.. and i think u cant change color on leaderboard

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by Tyler3D** [comment]
The leaderboard is client related. Only the Vanilla client has this problem.

**Comment by Megabyte918** [comment]
@fayizan 
> Noob Bots

Well what else do you want them to do?

> Rainbow Mode doesnt show up leaderboard

Yes, @Tyler3D and I suspect that to be a client related issue with the Agar.io client. It used to work but they must have changed something so it no longer does, IDK. It is also the "inexplicable bug" that's keeping us from finishing Rush Mode.

> Consoleplus not working for me :(  

Works fine for me.

**Comment by JadenTomori** [comment]
@Megabyte918 Hi Sir :) I wish to become a mod of this Project so i can close down issues that have nothin to do with the project :) I wanna help more people :)

**Comment by Tyler3D** [comment]
@Megabyte918 How about self feeding bots. Shouldn't be to much added lag.

**Comment by Tyler3D** [comment]
if the bot has > 2 cells then, w to the piece that someone is about to overlap

**Comment by Megabyte918** [comment]
@Tyler3D for that you would need to add the following code:
- Detect which one of the bot's cells is the biggest to self feed
- Detect when a player is on top of the bot's biggest cell
- Calculate the size of the player on top of their cell, if they are worth self feeding on or not
- Add the "bots ejecting mass" code, along with cooldown and all that
- Calculate the feed distance between the bot's smaller cells and the bot's biggest cell

**Comment by fayizan** [comment]
Thanks for replying megabyte, The bots actually splits 16 and run away, what I do before was pop, trick and 90 the bot.
console plus is opening but none of the commands work it just remains black and blanck btw I use digitalocean vps
![screenshot_106](https://cloud.githubusercontent.com/assets/19163419/21576190/696d9738-cf4c-11e6-8944-3334f5a00bfe.png)

**Comment by Megabyte918** [comment]
@fayizan What version are you on? This bug was fixed 2 days ago, see this commit: https://github.com/Megabyte918/MultiOgar-Edited/commit/ca2525954d14ed15fc89d8a9b87e4d70ba64bbfa

Also I do not know why that happens.. I'm not sure how console-plus works. @Gimmo do you know why this is happening? I just re-downloaded console-plus and it seems to be happening to me, too

**Comment by fayizan** [comment]
ohh thanks @Megabyte918 , I updated to new version just now, the bots seems better now

**Comment by Gimmo** [comment]
@fayizan  If something don't work as extected, first you should do -  describe exactly what you do to run sever and console. Second: on any problems there is error messages in window you run server in and in browser console. 

Most of all the problem is in addressing - you should set real address or name of your server in console-plus.html line 24 "host"

**Comment by Gimmo** [comment]
@Megabyte918 It's strange for me to tell you : just look what you do different to previous try. Console works, it's not changed. It should work from half-kick.

**Comment by fayizan** [comment]
`Most of all - your problem is in addressing - you should set real address or name of your server in console-plus.html line 24 "host"`
You are so right,My problem is fixed,thank you so much @Gimmo and @Megabyte918

**Comment by fayizan** [comment]
should I close this issue..?

**Comment by NiesamoWhite** [comment]
no pls i don't know how to install the new update

**Comment by AlexHGaming** [comment]
what update?

**Comment by NiesamoWhite** [comment]
if you scroll up megabyte918 talks about the new update

**Comment by fayizan** [comment]
![screenshot_124](https://cloud.githubusercontent.com/assets/19163419/21577596/af449bfa-cf86-11e6-818a-9185b618233e.png)

while running with console.js,I m getting an error should I have to use only web console..?

**Comment by Gimmo** [comment]
Yes. Console-plus is made to be used while you need run server as daemon and unable to access native console. The usage of native console possible only due to loopbacks, which made only for debugging. So you can send commands from native console when you use console-plus, but cannot use arrows and so on. It's not an error - it's feature.  More: if you use demonized server, you have to comment loopbacks in console-plus.js ( see comments in code) either you'll get a real error which will blocking console-plus .
