### ISSUE TITLE
Standalone Configurations

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#312]
It seems to me a good idea that some configurations were independent like for example playerMassDecay you could choose it only for one player and for the others another value

 I mean (example):

```
if ( ip == "anyIp" ) {

this.playerMassdecayrate: 0.001

}

else {


this.playermassdecayrate: 0.03 

}

```

IS POSSIBLE ¿?

**Comment by Tyler3D** [comment]
@PsycoYT Lag...lag...lag

**Comment by Tyler3D** [comment]
that's basically what you have to do to have independent configs. But, laggy, laggy, lag says otherwise.

**Comment by Megabyte918** [comment]
Why would you wan't a specific decay rate for one player? Seems pretty useless if you ask me haha.

**Comment by Megabyte918** [comment]
But if you would like to do such a thing you can insert this code after [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L659) line in GameServer.js:
`if (client._socket.remoteAddress == "insert ip here") rate *= val;`
