### ISSUE TITLE
My server is turn Very Lagged! :/

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#313]
Tittle.

**Comment by raphyjb** [comment]
so? What about it

**Comment by Megabyte918** [comment]
@Jhair2015 Can you provide more information?

**Comment by Jhair2015** [comment]
@Megabyte918 That in the last version, the spaces are very slow: / - In addition there is excessive lag, before used host c9io, but after his fall decided to use codeanywhere.

**Comment by Megabyte918** [comment]
@Jhair2015 The spaces are supposed to be slow, that's how it is in vanilla. If you compare these splits to vanilla, I can guarantee you will not notice a difference. Also by "provide more information" I meant things like:
- How many players were on your server?
- What was the current CPU/memory usage?
- What were your configurations set to?

Can you send me your gameserver.ini? It would help.
I do not have any trouble with lags.

**Comment by Jhair2015** [comment]
@Megabyte918 

There were no more than 20 people

CPU AND MEMORY: the default codeanywhere xD - use that because cloud9 broke :(

Mmm .. I have tried in an old version and had no lag at all and this is my gameserver.ini,

Here my gameserver.ini

http://pastebin.com/raw/fpFUKkAg

I think that you added more graphics to the game, I mean nicer spaces, Classy style, I do not know if you saw one of his videos but its spaces are very nice * - *
Watch it here: https://www.youtube.com/watch?v=q0ykiLzurXo
Sorry for the spam.
If I have noticed the difference of spaces lol. In the last update.

**Comment by AlexHGaming** [comment]
Get a faster PC?

**Comment by PsycoYT** [comment]
same problem but splits are very very worst

**Comment by Megabyte918** [comment]
@Jhair2015 
<pre>
foodMinAmount = 2500 << 2x the normal amount
foodMaxAmount = 3000 << 1.5x the normal amount
foodSpawnAmount = 150 << see below
spawnInterval = 5 << You are spawning 150 (foodSpawnAmount) food cells every 5 ticks, there is 60 ticks in 1 second (i think), 5/60 = 12, 150 (foodSpawnAmount) * 12 = 1800, you are spawning 1800 food cells per second.
</pre>
 I checked through the code that spawns food cells and it seems that foodMaxAmount is never applied. Which means you are continuously spawning 1800 food cells per second, which is probably why your server is lagging. Plus 20 players and 625 spawnmass per player are eating alot of food will cause alot to spawn every second.

I re-compare the splitting later.

**Comment by Jhair2015** [comment]
@Megabyte918  I have used this configuration always in many versions.

@AlexHGaming  and my pc is not so fast but it holds xD, in this last update I had this problem, well a few minutes ago it was updated but I understand.

**Comment by Megabyte918** [comment]
@Jhair2015 Is it still lagging on the latest version?

**Comment by Jhair2015** [comment]
@Megabyte918  Nuhh https://github.com/Megabyte918/MultiOgar-Edited/tree/b9ce28cc73c820589d765e73492937a3d4932f07

in this Version i not have lag.

**Comment by Jhair2015** [comment]
@raphyjb Hey, pallets is the cause of lag, menore this or get a VPS to host.

**Comment by Megabyte918** [comment]
@Jhair2015 Try changing [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L564) line in GameServer.js to this: 
`if (cell1.isRemoved || cell1 == null || client == null)`

If that doesn't work then it is what you are using to host. I've never had any performance issues on any versions. Also c9 or codeanywhere are not places to host, it is for development or testing. So that could also be the reason why you experience lag.

**Comment by Jhair2015** [comment]
@Megabyte918 
Okay, I'll prove it later ^^, and another question, c: it's possible to do this kind of graphics as in this video, I'm hypnotized seeing these spaces XDXD

https://www.youtube.com/watch?v=q0ykiLzurXo&t=243s

**Comment by Megabyte918** [comment]
@Jhair2015 ctrl + minus

**Comment by Jhair2015** [comment]
What?

@Megabyte918

**Comment by Jhair2015** [comment]
@Megabyte918 Ahhh okokok xD

http://stackoverflow.com/questions/16637261/what-does-ctrl-plus-minus-do-in-modern-browsers

XD

**Comment by Megabyte918** [comment]
@Jhair2015 @PsycoYT About splitting: https://streamable.com/gfjus
I cannot notice a difference (using the latest version)

**Comment by Jhair2015** [comment]
@Megabyte918  I do note a difference, multihogar takes a little more to divide than in vanilla
But it is very different to see MultihOgar or Vanilla with OGarrio, there if there is much difference.

**Comment by Megabyte918** [comment]
@Jhair2015 Ogario does not affect splitting. However splitting looks in vanilla compared to with an extension on is the same.. Also please compare through actual spectate rather than youtube videos.

**Comment by Jhair2015** [comment]
@Megabyte918 Nice, Ok ok ok No problem

**Comment by AlexHGaming** [comment]
How to play on the private server with the ogario extension anyways?

**Comment by Jhair2015** [comment]
@AlexHGaming  Install Ogario to tampermonkey and play!
