### ISSUE TITLE
How my friend can join in my server?

### ISSUE THREAD

**Issue by NiesamoWhite** [Megabyte918/MultiOgar-Edited#315]
Me and my friends want to go into my server but my friends can not come. Can someone help us please?

**Comment by NiesamoWhite** [comment]
i have already test with hamashi and my friends can't go in the server :/

**Comment by AlexHGaming** [comment]
They have to connect to your network

**Comment by NiesamoWhite** [comment]
yes but this in don't work too

**Comment by JadenTomori** [comment]
@NiesamoWhite Use Codeanywhere :)

**Comment by AlexHGaming** [comment]
I JUST DID A NEW TRICK
[image: Inline images 1]

**Comment by Jhair2015** [comment]
@JadenTomori  CodeAnywhere premium or free?

**Comment by NiesamoWhite** [comment]
I can't access to the terminal because it's charging.....

**Comment by NiesamoWhite** [comment]
oh thx code any where is working!!

**Comment by AlexandriteErikParacelsus** [comment]
Or you can just portfoward your server

**Comment by Tyler3D** [comment]
@NiesamoWhite Try port forwarding. CodeAnywhere and Cloud 9 give you terrible specs. If you use your real computer you'll get a huge performance boost.

**Comment by Jhair2015** [comment]
![captura de pantalla 117](https://cloud.githubusercontent.com/assets/18153674/21579053/b15389ec-cf68-11e6-94bd-86eb1c801b31.png)
@Tyler3D Pls, help me to host my MultiOgar Server! D:
but I do not know where to start D:

**Comment by Tyler3D** [comment]
@Jhair2015 Host it yourself. Do you know how to portforward?

**Comment by Jhair2015** [comment]
@Tyler3D If I know how to enter my router but not let me host it, as I understand it is a firewall in my router, so I bought DigitalOcean Premium, and I do not know what to do xD D:

**Comment by Tyler3D** [comment]
http://www.noip.com/support/knowledgebase/general-port-forwarding-guide/

**Comment by Tyler3D** [comment]
you host it just by running the server on your computer

**Comment by Tyler3D** [comment]
https://www.ipchicken.com/

**Comment by Tyler3D** [comment]
then people join from that ip

**Comment by Jhair2015** [comment]
@Tyler3D Then it's no use to me DigitalOcean, fuck money to the trash>: c
