### ISSUE TITLE
Splitspeed.

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#316]
I want the splitspeed feature to be added. It isn't an issue, but it's the way to get the attention. I want my split speeds to be different.
I will close this issue when I get an answer from @Megabyte918 
Thanks.

**Comment by FantasyIsBae** [comment]
Is it ok if u get an answer from me xd @AlexHGaming

**Comment by AlexHGaming** [comment]
@FantasyIsBae Just as long as it is added xD

**Comment by FantasyIsBae** [comment]
I can't say it will be added as @Megabyte918 already rejected my pull request .

**Comment by FantasyIsBae** [comment]
U can change it [Here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L749) tho

**Comment by AlexHGaming** [comment]
@fantasyisbae Ok thanks

**Comment by Jhair2015** [comment]
LooooooooooL

**Comment by AlexHGaming** [comment]
I can't find the file?
@Fantasyisbae

**Comment by AlexHGaming** [comment]
nvm found it
