### ISSUE TITLE
the rebound

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#32]
the rebound when i spacing is too excessive

**Comment by Megabyte918** [comment]
I don't know what your talking about, it looks the same as vanilla to me. But if you would like to change the splitspeed you can do so [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L1236)

**Comment by Megabyte918** [comment]
@RelTakeover @PrinceDark9243 nevermind, I took another look at it and compared and it actually WAS a bit fast. I reverted my changes of the normalizedDistance and playerSpeed, the splitting should be fine now. Thank you for pointing it out =D
