### ISSUE TITLE
HappyNewYear!

### ISSUE THREAD

**Issue by FantasyIsBae** [Megabyte918/MultiOgar-Edited#323]
I hope that everyone is enjoying their last moments of 2016 , I wish you all the best and a happy new year ! :)

**Comment by Jhair2015** [comment]
Happy New Year!!!!

**Comment by FantasyIsBae** [comment]
You too m8 :)

**Comment by Jhair2015** [comment]
:v

**Comment by Megabyte918** [comment]
Happy new year mates

**Comment by systemroot** [comment]
Happy new year all

**Comment by Jhair2015** [comment]
yeahhh!

**Comment by AlexandriteErikParacelsus** [comment]
Happy new year guys!

**Comment by Gimmo** [comment]
All the best and Happy New Year!

**Comment by AlexHGaming** [comment]
In Potatoland (where I live) , it is 2018 next year! What about you guys? 1942?

**Comment by FantasyIsBae** [comment]
ffs 😆

**Comment by mafiakb** [comment]
I am Peruvian :3 2016 :P

**Comment by FantasyIsBae** [comment]
Feel sad for u @mafiakb 😆

**Comment by Jhair2015** [comment]
@mafiakb  Enserio eres Peruano? :D Yo también lo Soy =)

**Comment by AlexHGaming** [comment]
I'M IN A NEW YEAR BITCHES! HAHA UK.
Why did I just act like a physcopath

**Comment by mafiakb** [comment]
@Jhair2015 jajajaj yeah a esperar el año compa ;)

**Comment by Jhair2015** [comment]
@mafiakb  Me puedes dar tu skype? =D Quisiera conversar algo contigo.

**Comment by mafiakb** [comment]
@Jhair2015 madksito ahi estoy.

**Comment by JadenTomori** [comment]
@Megabyte918 Happy New Year And To ALL BOIIZ

**Comment by Jhair2015** [comment]
@mafiakb NICE

**Comment by AlexandriteErikParacelsus** [comment]
It's 2017 for me 12 mins ago :D

**Comment by fayizan** [comment]
Happy New Year Everyone..!!!

**Comment by raphyjb** [comment]
happy new years!

**Comment by NiesamoWhite** [comment]
Happy new year!
- (This message has been sent from France ;))

**Comment by MineMooreALT** [comment]
lmao that was 2 days ago. (From Australia, Perth)

**Comment by Gimmo** [comment]
Traveler from future? At last....

**Comment by raphyjb** [comment]
Happy new year from canada!

**Comment by Jhair2015** [comment]
lol lol lol lol lol haa

**Comment by Agarian** [comment]
Happy new year from Michigan and Florida :P

**Comment by Megabyte918** [comment]
Not new years any more lol
