### ISSUE TITLE
How to make a skin changer?

### ISSUE THREAD

**Issue by AlexGallegos908** [Megabyte918/MultiOgar-Edited#326]
For example, <sc>

 <sc>skins= spy,zombie,birdie,

In there you can put your own skins.
Im make this to start working with animated skins of mobile.
Why?
The skin animated need 2 images. For example like this.
http://i.imgur.com/iLQXcWi.png

http://i.imgur.com/p8IllZp.png

**Comment by Tyler3D** [comment]
idk learn javascript

**Comment by Megabyte918** [comment]
@AlexGallegos908 You can find many scripts for skin changers elsewhere on the internet, please don't make issues that don't have to do with this project :)

**Comment by Jhair2015** [comment]
lol
