### ISSUE TITLE
How about a custom isPellet flag?

### ISSUE THREAD

**Issue by Luka967** [Megabyte918/MultiOgar-Edited#328]
I've recently started making an overhauled client for Cigar, and my current bottleneck is drawing pellets.
My test server has a lot of them (10000 in vanilla boundaries) so I end up with around 400 cells to draw on the screen if I'm big enough. And that's giving me 20 FPS.
I've developed a way for testing for pellets with update counting; if the cell wasn't updated for 200ms via packet 16, it'll assume it's a pellet and use a cache image to draw it.
This works in most cases until the window goes out of focus. Then it gets all buggy.

So I'm asking for a new flag 64 (0x40) to be added. I've tested adding it and all other clients ignore it.
This will remove dozens of lines of code for me and make my life easier for some time xD

That'll be 6 lines of code; to add this
```js
if (node.cellType == 1)
    flags |= 0x40;      // isPellet
```
after lines 90, 167 and 250 in `UpdateNodes.js`.

P.S. if you want you can check out the client [here](https://github.com/Luka967/Cigar), it's not finished for now.

**Comment by ZfsrGhS953** [comment]
isPellet flag is not needed, it's already possible to distinguish pellets from other non-ejected and non-virus cells by determining if the cell constantly updates or not.

**Comment by Luka967** [comment]
... Aaaand I've just found
