### ISSUE TITLE
About playerSpeed

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#329]
is really playerspeed = 1 , the real vanillsa speed? please not close the issue.

**Comment by AlexHGaming** [comment]
Probably. @Megabyte918 estimated the playerspeed so it might be a bit off.
It also says in the description of the project 'slower cell, player won't notice difference' or something like that.

**Comment by Jhair2015** [comment]
test 1.2

**Comment by Megabyte918** [comment]
@PsycoYT Looks vanilla to me, try comparing through spectate vs the server
