### ISSUE TITLE
About splits

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#330]
How can I make the splits more like gota.io? please help

**Comment by AlexHGaming** [comment]
Unless you can change the splits yourself through gameserver.js
What do you mean by splits more like gota?
Is it the speed or the camera angle?

**Comment by PsycoYT** [comment]
the way of splits in the game gota.io

**Comment by AlexHGaming** [comment]
Yeah but what do you mean by that?

**Comment by PsycoYT** [comment]
That game has divisions very similar to agar.io

**Comment by Jhair2015** [comment]
@PsycoYT  NOT is Similar

and go to this issue to get gota split's:

https://github.com/Megabyte918/MultiOgar-Edited/issues/179#issuecomment-266272129
