### ISSUE TITLE
How to change the camera adjustments of splitting?

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#331]
Hi all,
How do I change the camera to this: https://www.youtube.com/watch?v=ynDQwtX3Twk
Because my camera on my server doesn't move like what it shows in the video ^^
If I get an answer on how to do this, this issue will be closed.
Thanks.

**Comment by AlexHGaming** [comment]
I mean by when splitting, not the cell itself, when it splits if you get what I mean.

**Comment by Jhair2015** [comment]
@AlexHGaming  
I think those are spaces somewhat similar to OgarUnlimited.

Go here, and change it to a value until you get the desired one. :)

https://github.com/Megabyte918/MultiOgar-Edited/issues/193

**Comment by AlexHGaming** [comment]
Thanks, this will do.
Closing.
