### ISSUE TITLE
I hope not to bother with this, help! : D

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#333]
I do not want to be annoying, but does anyone know how to get the URL of this Host? : D I close this topic as soon as I know = D
![sin titulo](https://cloud.githubusercontent.com/assets/18153674/21596233/73e799be-d106-11e6-8d35-5b04c92a1442.png)

CodeNvy

**Comment by AlexHGaming** [comment]
@MastarCoder

**Comment by Jhair2015** [comment]
@MastarCoder plz :)
