### ISSUE TITLE
Set the max amount of mass for MotherCell

### ISSUE THREAD

**Issue by iamtaeuk** [Megabyte918/MultiOgar-Edited#334]
Hello, is there a way to set the max amount of mass for the Mother Cell?
The mother cell got too big and spawned all of the pellets around itself, making the whole map empty except for the area with the mother cell.

**Comment by Jhair2015** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gamemodes/Experimental.js#L18

changue valor.

**Comment by iamtaeuk** [comment]
@Jhair2015 Not the actual amount of the mother cell itself, but the max mass the mother cell could have

**Comment by Jhair2015** [comment]
@iamtaeuk  Sure

**Comment by ZfsrGhS953** [comment]
Add this line [here](https://github.com/Megabyte918/Mul tiOgar-Edited/blob/master/src/entity/MotherCell.js#L25):
```javascript
if (this._mass > #) return false;
```
Replace # with the max spawner mass you want to have.

**Comment by Agarian** [comment]
If you want, you could also make this a configuration for gameserver.ini
Lets say that config is `mothercellMaxMass`:
Replace `#` with `this.gameServer.config.mothercellMaxMass`

> if (this._mass > this.gameServer.config.mothercellMaxMass) return false;

Then add `mothercellMaxMass: 0` under `this.config {` in GameServer.js line 53
Finally, add `mothercellMaxMass = #`, # being what ever mass you want.

**Comment by Megabyte918** [comment]
I might actually make this a config, cause bots can sometimes accidentally make mothercells huge on experimental.
