### ISSUE TITLE
[Request] Anti- Ogar Feeder Bot

### ISSUE THREAD

**Issue by SomeoneCares11** [Megabyte918/MultiOgar-Edited#335]
Hi,

Our servers gets full because of the bots addons
which allow the user add bots follow him, 

e.g.:
https://www.youtube.com/channel/UCuFWWb480V5lhDS2P8Mu2Xw/videos

script code: 
http://pastebin.com/J2VLRPNN

maxclient per ip not working with this script, its spamming the connections

**Comment by Gimmo** [comment]
I think it's very important question, but the problem have simple solution - limit stream bandwith for given IP.

**Comment by Megabyte918** [comment]
@SomeoneCares11 Try these configurations:
serverIpLimit = 2
serverMinionIgnoreTime = 5
serverMinionThreshold = 5
serverMinionInterval = 500
serverScrambleLevel = 3
playerBotGrow = 0

**Comment by Jhair2015** [comment]
@Megabyte918 Yes they work : D,  however, sometimes it often makes the player a gray or white color ...

**Comment by Megabyte918** [comment]
@Jhair2015 Really? grey/white color was removed a while ago (for suicide bots)

**Comment by SomeoneCares11** [comment]
@Megabyte918  They use proxies and fake header, so the configurations will not help,

Here all information about it : 
https://github.com/davidmann4/ogar-feeder-bot

**Comment by Megabyte918** [comment]
@SomeoneCares11 Have you tried them? It might not help with `serverIpLimit = 2`, but the other configs should also help.

**Comment by SomeoneCares11** [comment]
Yes, i did, but they play with the bots like real playersI change some of the socket which fixed it temporarily.But the spam connections from these bots still cause lag,

**Comment by ItzLevvie** [comment]
Not sure if this will work but try putting this code on the onClientSocketOpen function.

```js
// Anti-bot
if (!ws.upgradeReq.headers['user-agent']) {
   ws.playerTracker.isMinion = true;
}
```

**Comment by josefredohd** [comment]
Abre tu server xD

**Comment by NuclearC** [comment]
@Megabyte918 can you make anti-raga system like vanilla servers have?

**Comment by ZfsrGhS953** [comment]
If he decides to deobfuscate agario.core.js for hours to add the vanilla anti-bot system into MultiOgar-Edited, the botters will only need to look at his code to fix bots.

**Comment by NuclearC** [comment]
-_- why df anti-bot system should be in agario.core.js?

**Comment by FantasyIsBae** [comment]
@NuclearC It can't be done on the server .

**Comment by Megabyte918** [comment]
This should be fixed now.

**Comment by valonymeri** [comment]
Hi I think they found another way of inserting bots, they also can send thousands of bots . Bots are called arcadeplex bots, and are added via tampermoneky chrome extension using a script, which come to the mothercell like selfeed.
can somebody please help
