### ISSUE TITLE
Bug? 2 virus at same location.

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#337]
Here the screenshot, i use my client (not official agar client),

![capture](https://cloud.githubusercontent.com/assets/19422415/21607610/e998ab9c-d1e9-11e6-8c1f-c941b17036b6.PNG)

I found this in the latest update.

**Comment by RasyiidWho** [comment]
![capture](https://cloud.githubusercontent.com/assets/19422415/21607755/dccc5516-d1ea-11e6-9a8b-aa8009a7df94.PNG)

This happens on all virus.

**Comment by AlexHGaming** [comment]
This might be because your client is a bit buggy

**Comment by RasyiidWho** [comment]
In agario client too..

**Comment by PheoniXAgario** [comment]
Yes

**Comment by ZfsrGhS953** [comment]
First thing that comes to my head is...  that the willCollide check is inverted.

**Comment by Jhair2015** [comment]
@ZfsrGhS953  @RasyiidWho  @AlexHGaming @PheoniXAgario 
https://github.com/Megabyte918/MultiOgar-Edited/commit/05ee9d6a21e31fc871bf3e7d0e8b308c1f7c94ab

this bug are created in this update

**Comment by RasyiidWho** [comment]
@Jhair2015 ikr.

**Comment by cedrsgaming** [comment]
Yep, same issue here (with agar client and my custom client)

**Comment by Agarian** [comment]
@AlexHGaming Same profile picture lol
The virus bug is either a client issue, or a bug with the latest version.

**Comment by Megabyte918** [comment]
Fixed; sorry for the wait
