### ISSUE TITLE
Skins not working 1.4.8

### ISSUE THREAD

**Issue by PheoniXAgario** [Megabyte918/MultiOgar-Edited#338]
Command: minion 1 100 <r>PheoniX

<r> used to work on 1.3.5, but not now. My no skins was not checked.

Any fix?

**Comment by Jhair2015** [comment]
wtf, skins not are visible to you or minions/bots?

**Comment by PsycoYT** [comment]
the skins are working.

**Comment by Agarian** [comment]
Skins do work, but since miniclip made patches, YOU can't see your skin, but everybody else on the server can. But that's only happening to premium skins

**Comment by Megabyte918** [comment]
yes ^^ 
also please check other issues to see if it has been asked before
