### ISSUE TITLE
Bot feed is way too fast

### ISSUE THREAD

**Issue by PheoniXAgario** [Megabyte918/MultiOgar-Edited#339]
I adjusted the player eject cooldown thingy and i got it pretty close to vanilla, but the bot feed is still way too fast. Any way to adjust?

**Comment by Jhair2015** [comment]
@PheoniXAgario  Bot or Minion?

**Comment by RasyiidWho** [comment]
If you Player : Don't use any Extensions.
If a Bot : Bot can't feed, right?

**Comment by Agarian** [comment]
You can use decimals for the cool-down as well

**Comment by Megabyte918** [comment]
Yep ^^
