### ISSUE TITLE
how to..

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#34]
how to decrease the virus explosion distance?

**Comment by Megabyte918** [comment]
@RelTakeover either lower the splitspeed located [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L1236),
or increase/decrease the playerSpeed/normalizedDistance ratio:
playerSpeed: [manual](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Cell.js#L87) or [config](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L123) 
normalizedDistance: located [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/PlayerCell.js#L75), (64)
