### ISSUE TITLE
Feed come back if i feed and forward in same direction

### ISSUE THREAD

**Issue by cedrsgaming** [Megabyte918/MultiOgar-Edited#340]
When i press W for feed, the feed is ejected but i eat them directly and the feed was not ejected correctly.

Client: agar.io/?ip=

Here an example of that problem and the virus probem too.
https://youtu.be/7br3Ro6LrwM

**Comment by Jhair2015** [comment]
@cedrsgaming  Have you tried it in the latest version? If so, that's because the last version has an error

Try it out:

https://github.com/Megabyte918/MultiOgar-Edited/tree/5a660ff256f9a1489d5136dad4da358517b26839

**Comment by RasyiidWho** [comment]
Eject bug happen at all agar implementation, I hope Megabyte can fix it :D

**Comment by cedrsgaming** [comment]
Yep, tryed with the last version directly from github like 20 min before i publish my vid.

**Comment by Agarian** [comment]
I don't have that problem :|

**Comment by markstoep** [comment]
We have the same problem at the last version.

**Comment by patrick0888** [comment]
Me too

**Comment by Agarian** [comment]
Well, use the latest

**Comment by Megabyte918** [comment]
I will look into it.

**Comment by Megabyte918** [comment]
Looking for the problem

**Comment by Megabyte918** [comment]
Fixed.

**Comment by RasyiidWho** [comment]
Nice btw 💃
