### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AlexGallegos908** [Megabyte918/MultiOgar-Edited#341]
ERTP Controls BUG
Virus BUG
Explotion of virus BUG
And more config are bug! >:c

**Comment by Jhair2015** [comment]
ERTP BUG?

**Comment by AlexGallegos908** [comment]
@Jhair2015 Si we

**Comment by Jhair2015** [comment]
@AlexGallegos908  "we"? lol idk

**Comment by Agarian** [comment]
The ERTP is a script to control minions on http://agar.io

**Comment by AlexGallegos908** [comment]
@Jhair2015 Hablas español we, pasa skype

**Comment by Jhair2015** [comment]
@AlexGallegos908  Cono lo supo :v? Jajaja, bueno Sí. SKP: live:jimmy:jhair17

**Comment by Megabyte918** [comment]
@AlexGallegos908 Can you explain what kind of bugs you are experiencing? I can't really fix something if I don't know the problem

**Comment by AlexGallegos908** [comment]
@Megabyte918 Men im stupid, CLOSE THIS PLZ :D

**Comment by PrinceDark9243** [comment]
#CLOSE #THIS #ISSUE

**Comment by AlexHGaming** [comment]
The ERTP only works if it supports a client, vanilla does NOT support.
There isn't any virus bug? What do you mean by a 'virus bug?'
If the config is a bug, change it yourself.
If you want to close this, just press 'close' or 'close and comment'
