### ISSUE TITLE
How to use UserRoles?

### ISSUE THREAD

**Issue by ToporBigBots** [Megabyte918/MultiOgar-Edited#344]
How to use UserRoles? Where to enter password?

UserRoles: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/enum/userRoles.json

**Comment by Megabyte918** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/commit/13096a950e903110199a4330a784c5d97b0ae67f#commitcomment-20354243
