### ISSUE TITLE
Auto Update!

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#345]
MultiOgar-Edited has got so many updates so i cant update it and changing gameserver.ini everytime @Megabyte918 We Want Auto Updater buy command /update!

*******************************************VOTE FOR AUTO UPDATE*******************************************

**Comment by AlexHGaming** [comment]
What you can do is whatever line is in whatever file, you can copy and paste the edits on that line(s)
Also it's nearly impossible to do so as it's not possible to go through everyone's gameserver.ini
On OgarUL this was a thing, but your entire gameserver.ini will get refreshed (as in it looks like what it was when you got MultiOgar-Edited. Soo... yeah

**Comment by AlexHGaming** [comment]
Just copy and paste the changes he's made.

**Comment by PrinceDark9243** [comment]
This Took Loot of Time but too lazy to do lol!

**Comment by Jhair2015** [comment]
OGARUL :// ...

**Comment by AlexHGaming** [comment]
I used to have OgarUL but it's shit now as you can actually play on a vanilla client and do smaller sized popsplits and shit.

**Comment by Megabyte918** [comment]
@PrinceDark9243 Please refer to #36

**Comment by PrinceDark9243** [comment]
OK @Megabyte918
