### ISSUE TITLE
Eject Mass

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#347]
Eject mass some times cannot feed front of your cell when splited in 16

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by PrinceDark9243** [comment]
like that #340 but little version of the bug some time your cell eject mass but near cell doesnt get when you are splited into 16 or 8 and 5

**Comment by Megabyte918** [comment]
@PrinceDark9243 Eject is not supposed to be able to pass the distance of split, it's how it is in vanilla.

**Comment by PrinceDark9243** [comment]
no i mean when you set your cooldown to 0 some cells eject mass but other cells cannot able to eat!

**Comment by Megabyte918** [comment]
@PrinceDark9243 Works fine for me.

**Comment by PrinceDark9243** [comment]
@Megabyte918 i mean in mobile physics in no cooldown

**Comment by Megabyte918** [comment]
@PrinceDark9243 Still works fine for me, I can't fix something that isn't broken
