### ISSUE TITLE
how to put sub'domain for gametrackers.

### ISSUE THREAD

**Issue by systemroot** [Megabyte918/MultiOgar-Edited#35]
how do they get my server ip?!
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L1767

here i can see port, name etc. but what about ip. what if i want to put a subdomain !? can this happen?!

**Comment by systemroot** [comment]
i'm closing this here i'll try to ask Barbosik

**Comment by Megabyte918** [comment]
What do you mean by subdomain? If you want to add a tracker, try adding the domain and all the other info you need for your tracker, under all the other tracker's info
For example: 
<pre>
// custom tracker
trackerRequest({
        host: 'tracker.link',
        port: trackerport,
        path: '/trackerpath',
        method: 'POST'
}, 'application/x-www-form-urlencoded', data);
</pre>
If you don't have a port or path just add the info manually with a variable like [this one](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L1784)

**Comment by systemroot** [comment]
no,

as you can see on gametrackers they have their ip's in public, 
so just i want to replace my ip:port with domain:port
i have try to put domain name into serverBind, but isn't starting! even if i put vps ip won't start is needed to let as it is 0.0.0.0

**Comment by Megabyte918** [comment]
@systemroot try using a DNS to hide your ip instead

**Comment by systemroot** [comment]
@Megabyte918 do u know how to make this big virus to split food out faster then normal default?
http://image.prntscr.com/image/e5ae07f51e1a46f8962713b618e03eb9.png

**Comment by Megabyte918** [comment]
@systemroot Reduce this value in Experimental.js (sorry for late response)
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gamemodes/Experimental.js#L19

**Comment by systemroot** [comment]
thank you
