### ISSUE TITLE
Skins!

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#352]
Some Skins names are incorrect in randomSkins.txt

**Comment by Megabyte918** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/commit/06d96c2272b7183f12d4b3a1c11e6cacb224e0c3
https://github.com/Megabyte918/MultiOgar-Edited/commit/557ca1378441782b314982624aa0b314bd7d9541
comments

**Comment by ItzLevvie** [comment]
This is fixed on https://github.com/Megabyte918/MultiOgar-Edited/commit/2dfd735b72abcb98b3046e3112b9b236b398b613
