### ISSUE TITLE
Too much food spawn from MotheCell.

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#355]
![capture](https://cloud.githubusercontent.com/assets/19422415/21682538/b2c472aa-d387-11e6-8634-ea1fc96fbdb0.PNG)

can you reduce the amount of spawn food MotherCell?
I'm sorry there is too much issues created by me :(

**Comment by AlexHGaming** [comment]
Did it spawn out like that?

**Comment by Megabyte918** [comment]
@RasyiidWho This bug is caused by commit: https://github.com/Megabyte918/MultiOgar-Edited/commit/2b27872568a79502952d4e2f9ad0a3f6c2924729
I have just checked, and vanilla mothercells do not eject food unless they are fed by something. 
Reverting the changes now.

**Comment by Agarian** [comment]
They do though, VERY slowly, but they do

**Comment by AlexHGaming** [comment]
@Megabyte918 Vanilla mothercells do slowly give out food but ejecting mass into it makes more food come out and they come out much more faster.

**Comment by Megabyte918** [comment]
@Agarian I've realized this through spectate, I've looked more into it and it seems that in last man standing no food ejects at all (you can see through various youtube videos), however normal with players is fine

**Comment by Agarian** [comment]
It may vary with player amount .-.

**Comment by Agarian** [comment]
@Megabyte918 Discord?

**Comment by Megabyte918** [comment]
kk I'll be there
