### ISSUE TITLE
Border Bouncy Physics

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#356]
How to make entities does not bounce from border bcz @Megabyte918 is changing server code so i cant able to make changes
I am sorry for making lot of issues

This is a part of Mobile Physics (if you have time just add this to GamerServer.js)

**Comment by ZfsrGhS953** [comment]
Do you mean that you want to make a config option for bounce and make a pull request for it, but by the time you finished coding it, there's a new commit and merging isn't possible due to conflicts?

**Comment by ZfsrGhS953** [comment]
Replace [this code](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L671-L675) with this:
```javascript
if (!this.config.mobilePhysics) {
    var r = cell1._size / 2;
    if (cell1.position.x < this.border.minx + r || cell1.position.x > this.border.maxx - r)
        cell1.boostDirection.x =- cell1.boostDirection.x;
	if (cell1.position.y < this.border.miny + r || cell1.position.y > this.border.maxy - r) 
	    cell1.boostDirection.y =- cell1.boostDirection.y;
}
```

**Comment by Megabyte918** [comment]
👍

**Comment by PrinceDark9243** [comment]
ok!

**Comment by PrinceDark9243** [comment]
@ZfsrGhS953 Code isnt working!

**Comment by PrinceDark9243** [comment]
Opsss my mistake the code works thanks @ZfsrGhS953
