### ISSUE TITLE
High update time in stats

### ISSUE THREAD

**Issue by OmarioYT** [Megabyte918/MultiOgar-Edited#357]
Hey,

My server is laggy sometimes with 40 people. I got 2 of them on 1 VPS
Specs from VPS:
4GB RAM
100 SSD
Intel Xeon CPU E5-2670 0 @ 2.60GHz
Ethernet 1GB

My MS is instable and is going from 7 to 15 to 25 to 8 to 13 to 35, its only when there are like 15 people... Imagine 40 people or maybe 50... I am a streamer and i stream for big channels. Today i had like 60 people playing and my MS was like 60 (Extremely high lag) now its on 12-25 with 15 people.. How can i fix this?

**Comment by AlexHGaming** [comment]
What size were the people? If they were somewhere more then 11000 then this could cause lag.

**Comment by Megabyte918** [comment]
@OmarioYT A few questions:
- How big were the players on your server?
- What are you using to host?
- What version are you using?
- Could you send me your gameserver.ini?
- Have you tried it with stats disabled?

**Comment by Andrews54757** [comment]
@OmarioYT This is because quadtree's find methods are very slow

**Comment by Andrews54757** [comment]
@OmarioYT http://zufallsgenerator.github.io/2014/01/26/visually-comparing-algorithms/

**Comment by Andrews54757** [comment]
@OmarioYT As you can see, as the amount of objects get bigger, more "checks" are needed because some overlap lines

**Comment by RasyiidWho** [comment]
wow ogarul creator -/\-

**Comment by OmarioYT** [comment]
@AlexHGaming @Megabyte918 They were above 5K, if the server was above 35K i did killall everytime.
I am using a 2 VPS', 1 VPS 1GB RAM same specs, hosting the site. VPS 2 Specs above hosting gameservers. I  use the newest version, i downloaded it yesterday. 
Gameserver.ini: http://pastebin.com/huhBDg0w
I tried to use stats, but tried to disable them too.

**Comment by Megabyte918** [comment]
@Andrews54757 Interesting, I will experiment with this
@OmarioYT Well I mean.. If you have 40+ players, each with 1000+ spawnmass, and 32 cells for each, then it is bound to lag

**Comment by MineMooreALT** [comment]
are you using host1plus

**Comment by OmarioYT** [comment]
@Megabyte918 Alis.io doesnt lag... & i tried to make spawnmass 500.
@MineMooreALT No, i use Yor-Game.nl

**Comment by Megabyte918** [comment]
@OmarioYT I'm pretty sure Alis.io would have servers that can handle that sort of stuff, especially if they are using the original multiogar and not this one with the amount of players they have.

**Comment by ZfsrGhS953** [comment]
Update to the latest node.js version, it's 2 times faster than 4.x versions and latest JXcore version. Also, high update time should be less of a problem after the new update is merged.

**Comment by Andrews54757** [comment]
I noticed something. https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/packet/BinaryWriter.js is not very optimised

**Comment by Megabyte918** [comment]
Closing this for now, no response in 2 1/2 weeks.
