### ISSUE TITLE
How to aument the speed of the cells of experimental?

### ISSUE THREAD

**Issue by AlexGallegos908** [Megabyte918/MultiOgar-Edited#358]

**Comment by AlexHGaming** [comment]
???
Well...
change the gamemode to Experimental and find the playerspeed and change that? o_o?
@Megabyte918

**Comment by Megabyte918** [comment]
@AlexGallegos908 Which cells are we talking about?

**Comment by ZfsrGhS953** [comment]
I think he's talking about the speed of food ejection from spawners, which can be changed [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/MotherCell.js#L13)

**Comment by Agarian** [comment]
You're mistaken, that's how many mothercells spawn per interval: `mothercellSpawnInterval`

**Comment by AlexGallegos908** [comment]
@Megabyte918 The cells red of expertimental aument speed :v

**Comment by Megabyte918** [comment]
@AlexGallegos908 Ok , do what @ZfsrGhS953 said and you'll be fine :)
