### ISSUE TITLE
anti spam chat

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#359]
title

**Comment by ZfsrGhS953** [comment]
Change [25 * 2](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L186) to whatever value is best for your server chat.

**Comment by PsycoYT** [comment]
decrease for slower messages?

**Comment by Luka967** [comment]
"Slower" messages? What do you mean?

**Comment by PsycoYT** [comment]
If I want to make the interval of messages slower? , Should I increase or decrease the value? Which of the two values ​​should I change?

**Comment by Luka967** [comment]
`25 * 2` is 50 if you didn't know.
If you want to ignore messages sent (for example) 250 milliseconds, change `25 * 2` to `250`

**Comment by Luka967** [comment]
@Megabyte918 Close?
