### ISSUE TITLE
Update Command

### ISSUE THREAD

**Issue by Firekix** [Megabyte918/MultiOgar-Edited#36]
Hey can you guys add a update command to MultiOgar(like in OgarUl).... It would be more better tat way..

(*Popsplits* are working good........ Appreciate ur work....)

**Comment by AlexandriteErikParacelsus** [comment]
@Megabyte918

**Comment by Megabyte918** [comment]
@Firekix https://github.com/Barbosik/MultiOgar/issues/86

**Comment by Firekix** [comment]
Ok Thats fine.... Thanks For your attention
