### ISSUE TITLE
IP Bots & IP SetSpawn

### ISSUE THREAD

**Issue by OmarioYT** [Megabyte918/MultiOgar-Edited#361]
Hey,
I am in Madness Clan atm and members are asking of they can start with higher mass and some bots.

How can i add IP Bots and IP SetSpawn?

**Comment by Jhair2015** [comment]
Duplicate.

**Comment by Megabyte918** [comment]
@OmarioYT 
#262
#205 
#13
Code where minion by ip is now here: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L322
