### ISSUE TITLE
BAN COMMAND NOT WORKING

### ISSUE THREAD

**Issue by 5p1Ky** [Megabyte918/MultiOgar-Edited#362]
I am using MultiOgar-Edited since few days and use it with my friend, but I found a bug.
When I enter the command "ban [IP/ID]" it doesn't ban the player, it just disconnect him then he just have to reload the page to be able to respawn on the server.

Can you please take a look at this issue, it's annoying to be unable to choose which player we want to be on our server...

**Comment by Megabyte918** [comment]
@5p1Ky What are you using to host your server? Banning works just fine for me.

**Comment by Jhair2015** [comment]
@5p1Ky Do you use Codeanywhere to host your server?

**Comment by 5p1Ky** [comment]
I'm using cloud 9 to host it ... Why is it important for the ban option ?

**Comment by iamtaeuk** [comment]
@5p1Ky Cloud9 is **NOT** a server provider, it is for development environment & testing.

**Comment by Gimmo** [comment]
Rackspace give free server to developers for one year. Them write it's irrevocable credit. I used this about 8 month , then them starting require payments for extra traffic and I say bye. Them have idiotic big prices for everything. At least 10 times more then Hetzner.

**Comment by Luka967** [comment]
All players connecting to a cloud9 server go through a proxy.

@Megabyte918 Close

**Comment by 5p1Ky** [comment]
Oh okay thanks ! Just one more thing: will I have the same problem on codenvy.io ?

**Comment by Luka967** [comment]
Never used it.
@Megabyte918 Close

**Comment by iamtaeuk** [comment]
@5p1Ky btw Cloud9 is **NOT** a FREE VPS provider, it is an online _IDE_!
