### ISSUE TITLE
How to change speed disconnection split/cells?

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#366]
How to change speed Double split?
(playerDisconnectTime << Without change/does nothing)
![-1](https://cloud.githubusercontent.com/assets/24901742/21740533/5c2155a2-d4cd-11e6-8826-4d7e350aafa2.jpg)

**Comment by AlexHGaming** [comment]
Do you want to know how to change the speed of a split itself?

**Comment by AlexHGaming** [comment]
Oh and how do you get those skins? Where did you get it from? An extension? I'd love to see my own skin.

**Comment by DeadLord1337** [comment]
@AlexHGaming Yes, how to change the speed of a split itself?

**Comment by AlexHGaming** [comment]
Go to gameserver.js
Find: var newCell = new Entity.PlayerCell(this, client, pos, size2);
    newCell.setBoost(780, angle);
(Line 766)
Then where 780 is, the more slower the split you want, the less value you
change to 780
So below 780 is a slower split speed (recommended: change to 380)

**Comment by DeadLord1337** [comment]
@AlexHGaming thanks a lot <3, and is possible still how to change speed takes off the cells at double split?

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by Jhair2015** [comment]
@DeadLord1337  Skins, how to get? lol @AlexHGaming

**Comment by Megabyte918** [comment]
@DeadLord1337 Find these values in GameServer.js:
<pre>
var m1 = ~~c.cell1._mass / m;
var m2 = ~~c.cell2._mass / m;
</pre>
Multiply them by any number lower than 1 to reduce the snappiness.

**Comment by DeadLord1337** [comment]
@Megabyte918 thx ^_^

**Comment by Wair1o17** [comment]
@Megabyte918 And how is that in MultihOgar 1.2.69?

**Comment by parksisen** [comment]
I need this on the latest version

**Comment by parksisen** [comment]
@m-byte918
