### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#367]
The configuration of playerStartSize is at 130, but in the game it appears with 130 but then it reduces by 10 automatically

```
playerMinSize = 31.6227766017
playerMaxSize = 1500
playerMinSplitSize = 60
playerMinEjectSize = 56.56854249
playerStartSize = 131
playerMaxCells = 16
playerSpeed = 1
playerDecayRate = 0.007
playerDecayCap = 0
playerRecombineTime = 15
playerMaxNickLength = 15
playerDisconnectTime = 20
```

**Comment by ZfsrGhS953** [comment]
```javascript
playerDecayRate = 0.007
```
The decay has been inverted in a recent update, so it should be:
```javascript
playerDecayRate = 0.993
```

**Comment by PsycoYT** [comment]
wtf , how to use the new playercayrate?

**Comment by ZfsrGhS953** [comment]
Substract the old playerDecayRate from 1.

**Comment by PsycoYT** [comment]
? i cant understand

**Comment by PsycoYT** [comment]
shit update

**Comment by Luka967** [comment]
In Ogar or MultiOgar it's `0.007`.
In MultiOgar-Edited it's `1 - 0.007` which is `0.993`.
