### ISSUE TITLE
How to eat

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#368]
How to eat `THE FOOD` THAT IS BIGGER THAN ME ? like ogarul

**Comment by AlexHGaming** [comment]
This is not possible.

**Comment by Luka967** [comment]
[Find this line.](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L822)
```js
if (check._size < cell._size * 1.15) return;
```
Replace it with this:
```js
if (check._size < cell._size * 1.15 && check.cellType != 1) return;
```

**Comment by PsycoYT** [comment]
that code not work @Luka967
