### ISSUE TITLE
i have a issue

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#37]
i have this ( i want set playerDecayRate according the players online ) could you add this ? or help me..

if (humans > 10) {
			playerDecayRate: .0035;
		
	}			
	
else if (humans > 20) {
	
	playerDecayRate: .0055;
	
}
else {
	
	playerDecayRate .0075;
},

is correct or what :(

**Comment by Megabyte918** [comment]
@RelTakeover replace your `updateMassDecay` function in GameServer.js with this one: 
<pre>
GameServer.prototype.updateMassDecay = function () {
    if (!this.config.playerDecayRate) {
        return;
    }
    
    // decayrate increases by 0.0001 per player joined
    var rate = this.config.playerDecayRate;
    for (var i = 0; i < this.socketCount; i++) {
        rate += 0.0001;
    }
    
    var decay = 1 - rate * this.gameMode.decayMod;
    // Loop through all player cells
    for (var i = 0; i < this.clients.length; i++) {
        var playerTracker = this.clients[i].playerTracker;
        for (var j = 0; j < playerTracker.cells.length; j++) {
            var cell = playerTracker.cells[j];
            var size = cell._size;
            if (size <= this.config.playerMinSize)
                continue;
            size = Math.sqrt(size * size * decay);
            size = Math.max(size, this.config.playerMinSize);
            if (size != cell._size) {
                cell.setSize(size);
            }
        }
    }
};
</pre>

**Comment by RelTakeover** [comment]
ok i will try , thanks
