### ISSUE TITLE
Bug with my popsplits.

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#370]
I changed my popsplit physics around a bit so it's much more easier to hit them.
But I have faced ONE major issue.
How do you remove the big cell coming first when hitting a popsplit?
Like when I doublesplit into the enemy, 4th part goes in, then when the 3rd part approaches, the biggest size of all of the cells pop out of me.
How to fix? I want it so the biggest mass piece comes out of the back of the player's cell, making it to eat the smaller parts first and then eat the big part.

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by Megabyte918** [comment]
@AlexHGaming Change the virus explosion multipliers to when that doesn't happen.

**Comment by AlexHGaming** [comment]
@Megabyte918 How do I do this?
I mean that the bigger part is coming first, I'm fine eating the smaller big parts it's just the massive big part. I want the largest mass sized cell to be at the back of the cell,

**Comment by Megabyte918** [comment]
Well for that you would need to detect which cell is the biggest one popping out, and at the same time reverse the angle so it doesn't hit you. Keep in mind this will all be happening in under a second when the player pops. I would suggest just reducing one of the multipliers to be sure no ones that are too big popout. Because something like what I just described earlier would reduce performance

**Comment by AlexHGaming** [comment]
How do I reverse the value? 
Sorry I'm just curious about my popsplits and trying to make mine vanilla as possible.
It's definitely vanilla for me, apart from that big part...

**Comment by AlexHGaming** [comment]
This is what it says in virus.js.
`var v = c.isMoving ? 4 : 1.0;
           var exp = (Math.random() * (v - 3.33)) + 3.33;
            while (threshold / exp > 24) {
                threshold /= exp;
                exp = 2;
                big.push(threshold >> 0);`

**Comment by Megabyte918** [comment]
@AlexHGaming You could negate the "angle" variable
example:
<pre>
for (var k = 0; k < big.length; k++) {
    var angle = 2 * Math.PI * Math.random(); // random directions
    this.gameServer.splitPlayerCell(c.owner, c, -angle, big[k]); // "angle" is normal, "-angle" is opposite
}
</pre>

**Comment by AlexHGaming** [comment]
Is the lower the number the more futher back? So if I make it 0 it should spawn at the back?

**Comment by Megabyte918** [comment]
@AlexHGaming no

**Comment by AlexHGaming** [comment]
So what then? I need to fix this.
