### ISSUE TITLE
Regarding external minion detection.

### ISSUE THREAD

**Issue by Luka967** [Megabyte918/MultiOgar-Edited#371]
I've come to an idea to record the headers for connections on external minions.
Don't ask where I found them xD

Here's me and the first bot connecting.
```
player header
{
  host: '178.149.89.150:701',
  connection: 'Upgrade',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  upgrade: 'websocket',
  origin: 'http://juniormgar.esy.es',
  'sec-websocket-version': '13',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36',
  dnt: '1',
  'accept-encoding': 'gzip, deflate, sdch',
  'accept-language': 'sr-RS,sr;q=0.8,en-US;q=0.6,en;q=0.4,hr;q=0.2,ru;q=0.2',
  'sec-websocket-key': '7IZqimqcrH235J2wbI2+EA==',
  'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits'
}
minion header
{
  host: '178.149.89.150:701',
  connection: 'Upgrade',
  upgrade: 'websocket',
  origin: 'http://agar.io',
  'sec-websocket-version': '13',
  'user-agent': 'ogar-feeder-bot',
  'sec-websocket-key': 'MTMtMTQ4MzgwMTU2ODc5MA==',
  'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits'
}
```
As you might see, a minion header has a lot less info than a player header. Most notably, `user-agent`. On minion's header it's `'ogar-feeder-bot'`, while on player's header it's a standard agent version.

Since a lot of current minion versions use a modified version of ogar-feeder-bot, this poses for a large detection risk.

A regular minion user won't even notice that there's a config for changing the agent nor will know how to see the agent for his browser.

Perhaps we should use this in our power until they find out for this?

**Comment by Gimmo** [comment]
It should be resolved on OS layer, not a server. Look what this guy do : [https://github.com/systemroot/ogars-bots-blocker](ogars-bots-blocker)

**Comment by Megabyte918** [comment]
@Luka967 In ogar feeder bot there is a configuration for the user agent, I dont think blocking bots based on the user agent they have is such a good idea cause they can always just change it to look like its from a regular person

**Comment by Luka967** [comment]
@Megabyte918 True for the config, but many users won't even change it. What Gimmo gave us is a validator using reverse proxying (in this case the validator is nginx). It's basically overriding every connection attempt and it must go through what nginx was told to do. A diagram for the connection which should looks like this:
```
connection -> connection attempt to server -> nginx (validator) -> server
```
We can add two configs, one for checking for the missing headers you listed, and the second one for checking the user-agent. I'll try a quick implementation to see if it works.

**Comment by Luka967** [comment]
It's working on every agar and agar clone I go to and blocks off every minion that connects.

However I've noticed that even though minions are checked, nothing further is done to protect the server against them.

[PlayerTracker.js, line 295](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L295)
```js
if (!this.isMinion || !this.isMi) {
```
It'll always evaluate as `true` and would update the view nodes.
For example, if it's a server minion; `false || true = false`
An AND (`&&`) operator is needed.

Also, why not just block receiving all packets if it's a minion?

**Comment by Gimmo** [comment]
Bot makers read this, and them not so stupid. It's very easy to add all this headers. Also all operations with them on node.js are at least 10 times slower then on nginx , that's why it's used.  Using nginx we change only settings independent of our software structure, them can be changed easily, and don't touch main work.

**Comment by Megabyte918** [comment]
Should be fixed now.
