### ISSUE TITLE
where i can change split distance?

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#373]
i mean to DISTANCE , NOT TO SPEED OF SPLIT.

**Comment by Luka967** [comment]
You can't

**Comment by ZfsrGhS953** [comment]
Change [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L668) to:
```javascript
cell1.boostDistance -= speed / #;
```
Replace # with your speed multiplier. For example,
```javascript
cell1.boostDistance -= speed / 1.5;
```
would make ejected and split cells move 1.5 times further.
