### ISSUE TITLE
Ummm?

### ISSUE THREAD

**Issue by mrzack506** [Megabyte918/MultiOgar-Edited#374]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L119
what?
That decayrate is absurd!

**Comment by Megabyte918** [comment]
Have you tried it? It's the same as it was before

**Comment by mrzack506** [comment]
Oh no it's not. Not at all.

**Comment by mrzack506** [comment]
I'll get a streamable link in a sec

**Comment by mrzack506** [comment]
https://streamable.com/s337e

**Comment by mrzack506** [comment]
https://streamable.com/tpx2b

**Comment by Megabyte918** [comment]
@mrzack506 Have you edited the `playerDecayCap` config by any chance? If so update your GameServer.js, playerDecayCap config was fixed

**Comment by mrzack506** [comment]
Ok, and no, I have not.

**Comment by AlexandriteErikParacelsus** [comment]
It's not happening to me

**Comment by AlexHGaming** [comment]
same? My decay is just like vanilla

**Comment by RasyiidWho** [comment]
Not happen to me, try redownload.
