### ISSUE TITLE
new FUNNY gamemode idea

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#375]
New gamemode - zombie 
This gamemode like Braains.io game, need another physic
if cell small, cell move slow, if cell big, this cell faster than  small cell
New config:
cellGetFast =0.03 (if player speed 1.00 in 10 mass, in 110 mass cell get speed 1.03, and 1.06 in 210 mass)
If this Gamemode starts, and 3 players joined game, 1 random cell freeze for 15 seconds, after 15 seconds starts game. Zombie target: 
infect all survivors, Survivor target: survive 120 seconds. For bots need code for this gamemode, if bot zombie, he collect pullets, and if see survivor, he 
must infect him. If bot survivor, he collect pullets, and if he see zombie,he must 
escape from him.
If zombie infect survivor, zombie get 50% of survivor mass.
If Zombies win, game restart, and all die, and spawn with mass,which he have in 
previous round (Or all tp to random pos).
New settings:
ZombieDecayRate  = .002
SurvivorDecayRate = .000
RoundDuration = 120
SurvivorStartSpeed = 0.5
ZombieStartSpeed = 0.6
MinSurvivors = 3
Zombie color must Be green
Survivor color must be red
And new object - bush - like virus, but Survivor and zombie cant feed him, Survivors will be hide in him,and players cant explodes from him.
BushMass = 200
BushCount= 25
leaderboard in this game:
1.
2.
3
4
5
6
7
8
9
10
11 BiggestZombie - (Name) with mass (mass)
Rules in this gamemode:
You cant split
No viruses
No limit
I think its good idea, its possible to create, and it will be very funny.

**Comment by t11tanYT** [comment]
Sorry for my english im russian xD

**Comment by AlexandriteErikParacelsus** [comment]
Nice suggestion, but I think this will impact a lot in performence

**Comment by t11tanYT** [comment]
@AlexandriteErikParacelsus  Why? its like old zombie gamemode, but with 
additions.

**Comment by AlexandriteErikParacelsus** [comment]
@t11tanYT Because of the amount of lines of code

**Comment by Megabyte918** [comment]
@t11tanYT 
> This gamemode like Braains.io game, need another physic

What kind of physic?

> if cell small, cell move slow, if cell big, this cell faster than small cell
New config:
cellGetFast =0.03 (if player speed 1.00 in 10 mass, in 110 mass cell get speed 1.03, and 1.06 in 210 mass)

This will ruin game balance.

> If this Gamemode starts, and 3 players joined game, 1 random cell freeze for 15 seconds, after 15 seconds 

Why?

>  For bots need code for this gamemode, if bot zombie, he collect pullets, and if see survivor, he
must infect him. If bot survivor, he collect pullets, and if he see zombie,he must
escape from him.

Sounds like performance issues to me.

> If Zombies win, game restart, and all die, and spawn with mass,which he have in
previous round (Or all tp to random pos).

Cashing the amount of mass players have before they die and giving it to them after they respawn would cause performance issues.

> And new object - bush - like virus, but Survivor and zombie cant feed him, Survivors will be hide in him,and players cant explodes from him.

You can do the same with viruses (hiding inside).

> Rules in this gamemode:
You cant split
No viruses
No limit

That sounds like it would be boring.

**Comment by t11tanYT** [comment]
- What kind of physic?
if cell small, cell move slow, if cell big, this cell faster than small cell

If zombie infect survivor, zombie get 50% of survivor mass.

- This will ruin game balance.
This balance need for this gamemode, in this gamemode survivor cant eat samaller survivor,like teams gamemode. if big survivor speed is not fast, for zombies infect this player is easy.

- Why? Sounds pointless to me.
Ok, if game starts, after 15 seconds 1 random survivor survivor
It is becoming zombie.

-Sounds like performance issues to me.
Ok, In this gamemode bot will play as original bot, but he will not avoiding bigger cells, he will avoiding ALL zombies.

-Cashing the amount of mass players have before they die and giving it to them after they respawn would cause performance issues.
Ok,if Zombies win, game restart, and all zombies It is becoming survivor and if Survivors stay alive in 120 seconds ,game restarts, and all zombies It is becoming survivor, and starts  new round.  

-You can do the same with viruses (hiding inside).
Ok

-That sounds like it would be boring.
Its original rules, all players can 
tune this settings.

**Comment by Megabyte918** [comment]
Cell speed:

One of the basic rules of Agar.io is that bigger cells move slower than smaller cells. If I were to make it the opposite, It wouldn't be fun for new players because the big cells would always be dominating the map and you wouldn't be able to see them coming due to your limited range of view as a small cell. It completely messes up the balance.

**Comment by t11tanYT** [comment]
@Megabyte918 Play braains.io, in this game same rules as my gamemode, and many players play this game, in this gamemode anyone CANT eat smaller cells, and if this server have big cells, if they survivor,
they cant eat smaller survivor, and if  zombie touch small survivor, only 50% of survivor mass will be added to zombie, and zombie can collect pullets for mass, in 1 round 300-500 mass,
Ok, new settings for balance:
ZombieGetMass = (how much % of survivor mass will be added to zombie.)
RoundDuration = (how much seconds for survivors needed to survive)
PlayerMaxMass = (old config for balance in this gamemode)
MaxMassToZombie = (if in this config 5000, player with 5001 mass can not be  zombie in start
ZombieGetMassNew =  (how much % of new player mass will be added to zombie.)
this settings will added max balance for this gamemode and max fun for new players
Zombie cant eat smaller zombie,  and all zombies can collect pullets for mass, in 1 round 300-500 mass,
cellGetFast =0.03 (if player speed 1.00 in 10 mass, in 110 mass cell get speed 1.03, and 1.06 in 210 mass)
Set this setting to 0.01 for max balance

**Comment by t11tanYT** [comment]
@Megabyte918  you add it?

**Comment by LegitSoulja** [comment]
@t11tanYT The skills are rare for the repo. I could however create this, but not for multi-ogar. 

There will be tons of gamemodes built into so called `OpenAgar`. In the future, you will get paid for running our servers by the hour, in which at the end of every month you'll get paid. This is so that server owners will be able to keep up with their server. Basically, we will provide you money to continue hosting servers. Even shops coming soon. Stay tuned.

And @Megabyte918 how's it going? I've heard that the protocol has been changed. Have you sortof fixed it?

**Comment by Andrews54757** [comment]
@LegitSoulja Plz. We havent even specified what we are going to do.

**Comment by Megabyte918** [comment]
@t11tanYT It is not in my list of priorities at the moment, there are more important things that need to be taken care of regarding the new Agar.io protocol, once they are taken care of I will start adding new features and gamemodes and all of that other fun stuff. Also I am very busy with real life issues, partially the reason why I've been absent for quite some time. I will leave the "enhancement" label on this for now.

@LegitSoulja I've been trying to learn how the protocol works, but not making much progress due to my lack of time. Also please do not advertise on this repository

**Comment by LegitSoulja** [comment]
@Megabyte918 However, I didn't say so "advertise". I made a remark. Do you not know exactly what advertising mean?

Someone directed me here about the gamemode, and I stated what I had to say straight forward. However, *If I was advertising then delete my post. Anyways bye bye.

**Comment by LegitSoulja** [comment]
@Andrews54757 It's good, however "we" didn't specify but I've talked to someone about the situation if it was possible. Hopefully he'll be working with "us". Both of us are actually working with webgl, making Ogar better. However, after that I'll pass everything into your hands and let you do whatever. Maybe both of you can take things further than I've expected, but I wouldn't be around as much. I don't fit in with none of this. I just had ideas, that can pull through.

**Comment by Megabyte918** [comment]
@t11tanYT I'm not sure I like the idea of this gamemode. I mean I COULD add it if I really wanted to, it sounds pretty easy to, but whats the point if people won't play it? I removed all broken gamemodes along with the ones that nobody played (which includes zombie gamemodes) because they were just taking up unnecessary space. I don't want to add any of those game modes or useless game modes back

**Comment by MastaCoder** [comment]
@Megabyte918 Welp most of the basics can be added through the normal hooks of gamemodes, however some of the other things he requests might need to be added to the server itself, and will cause lag.

It should be possible to add the basic idea, basically the old zombie mode but different.

- Have everyone go find a spot to hide.
- One person will become infected, making them grey.
- They go around and try to find people to tag them.

The longer you stay alive, the higher your score will get and the more you stay as a zombie the less your score will get. The score can be put beside the name, so that mass doesn't affect players size.

I'm going to try to add this once I'm finished with everything if you can't find the time to do it :) Just need to learn the new hooks of MultiOgar since I haven't looked into them at all yet,

**Comment by Luka967** [comment]
Something like the old zombie mode and hide-n-seek? On it xD

**Comment by MastaCoder** [comment]
@Luka967 EXACTLY. I got to say it's a complete rip off of the braains.io idea haha

**Comment by Luka967** [comment]
@MastaCoder Well the brains gamemode was created before braains.io so technically it's still under Devin Ryan's Apache license xD

**Comment by MastaCoder** [comment]
Pfft, let's sue them @Luka967

**Comment by Luka967** [comment]
xD
nah, just the code is licensed xD

**Comment by Agarian** [comment]
xddd

**Comment by Wawy123** [comment]
RUSH GAMEMODE MAYBE XD

but its real agar just with red viruses ;/

**Comment by LegitSoulja** [comment]
@MastaCoder Kid, you have no ability, nor power within your hands to do such a thing as of sueing someone over a game. You're ridiculous. 

Please remove me from this issue, im tired of these alerts.

**Comment by Luka967** [comment]
@LegitSoulja Remember that you've added yourself.
You can also unsubscribe from notifications of this thread.
![image](https://cloud.githubusercontent.com/assets/15956695/22807511/b3b0e2fa-ef27-11e6-82fd-fe3f09b8c22a.png)

**Comment by LegitSoulja** [comment]
@Luka967 yea, you're right. But I keep forgetting that exists.

**Comment by MastaCoder** [comment]
@Megabyte918 can you get rid of @LegitSoulja and Andrew, possibly ban them? They constantly keep causing issues.

1. Advertising.
2. Always going off topic.

Prepare for another reply from Legit rambling on about how he thinks he's better than everyone else. :trollface:

**Comment by MastaCoder** [comment]
Also Megabyte don't delete this message. It's dank memes.

[[https://i.gyazo.com/67bd50d446eebe8ffef520453a6401a6.png]]

Just a few months ago.
[[https://i.gyazo.com/5beff5d0b52e9f4bd4937d0088b32ce5.png]]

**Comment by Andrews54757** [comment]
Everyone, just stop. No more hostility

**Comment by Andrews54757** [comment]
Someone tagged me here

**Comment by MastaCoder** [comment]
WHY ARENT MY DANK MEMES WORKING

**Comment by Andrews54757** [comment]
@MastaCoder @LegitSoulja Both of you, stop it. @Megabyte918 Please delete all comments. I feel pity for you for having to deal with this every day.

**Comment by MastaCoder** [comment]
There is no reason to delete them. They never went off topic. If you want something gone stop posting here. Also, when you post, post in one message please instead of 4 to make Megabytes deleting process faster.

**Comment by Andrews54757** [comment]
I am sure @Megabyte918 is F*ing angry about how the community is acting. If you dont have anything to say that is nice, then dont say it. I have now moved on from Ogar, and un-watched everything, but you people are still bringing me in to stuff, and I am not happy at all, I am angry.

**Comment by MastaCoder** [comment]
@Andrews54757 Love you ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by MastaCoder** [comment]
ANDREW CAN YOU MARRY ME?

**Comment by MastaCoder** [comment]
YOU'RE SMART, HANDSOME AND BRAVE!

**Comment by MastaCoder** [comment]
@Andrews54757 Click the watch button, hit ignoring. Thanks!

**Comment by Luka967** [comment]
You two have become dank memes since you've shut down OgarUL.
There's also a block button, you know right?

**Comment by Andrews54757** [comment]
@Luka967 I have moved on from gaming. I cannot maintain OgarUL anymore. It is just too big.

**Comment by MastaCoder** [comment]
@Andrews54757 Thanks! Don't come back please. Make sure to hit watch -> ignoring.

**Comment by FantasyIsBae** [comment]
Do we need this?

**Comment by Agarian** [comment]
Probably not, also I can't help but want the original Zombie game mode back. Also I don't remember, what exactly was the difference between the Zombie and Zombie Team gamemodes? I need a refresher on that.

**Comment by Fan7asy** [comment]
I'll try to bring the Zombie gamemode back, also I have no idea what the difference was.

**Comment by Fan7asy** [comment]
I'm going to close this.

**Comment by Agarian** [comment]
I think the only difference was the "HERO" and "BRAIN" cells that would give you power-ups. I remember the "HERO" cell gave you Zombie immunity, and instant merge. Eating the "BRAIN"cell would give you a speed boost, but would also turn you into a Zombie. At least, that's what I remember.

**Comment by Fan7asy** [comment]
Oh okay, I'll do that soon :)
