### ISSUE TITLE
Virus move speed in Experimental?

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#377]

**Comment by ZfsrGhS953** [comment]
It's [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gamemodes/Experimental.js#L55). The vanilla value is 100, but additional boosts [don't cancel out previous ones](https://github.com/ZfsrGhS953/Petridish-Ogar/blob/master/Ogar/src/entity/Cell.js#L153). If you set it to 100 in MultiOgar-Edited, the pushing is going to be too slow.

**Comment by RasyiidWho** [comment]
where i can put 100 value?

**Comment by ZfsrGhS953** [comment]
Replace "16 * 20" with it.
