### ISSUE TITLE
Is there a way to play with minion ?

### ISSUE THREAD

**Issue by Nic0x** [Megabyte918/MultiOgar-Edited#378]
Hello,
Is there a way to play with minions with e and r key (e for split, r for feed) using agar.io client ?
Thx

**Comment by ZfsrGhS953** [comment]
Use this userscript: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/scripts/ERTPcontrol.js

**Comment by Nic0x** [comment]
Thanks you so much man !

**Comment by AlexHGaming** [comment]
But remember to change in the gameserver.ini:
`DisableQ = 1`
`DisableERTP = 0`
