### ISSUE TITLE
can u make it [Suggestion]

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#379]
Recently i found a cool trick which blow your mind it called push split https://www.youtube.com/watch?v=PB0s5wrXSRs

psss dont close this issue it is an suggestion i think many peoples will like this suggestion

**Comment by Megabyte918** [comment]
@PrinceDark9243 You can already do those

**Comment by PrinceDark9243** [comment]
Really

**Comment by Megabyte918** [comment]
Yes, I've done plenty

**Comment by PrinceDark9243** [comment]
i tried but isnt work!

**Comment by PrinceDark9243** [comment]
should i need to update the server?

**Comment by PrinceDark9243** [comment]
@Megabyte918 ?
