### ISSUE TITLE
Hey @Megabyte918 !

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#38]
Hey @Megabyte918 !

Hahaha this is somewhat inconvenient for you! eur-lex.europa.eu eur-lex.europa.eu

But I would say a configuration with playerspeed or something, I remember he said it to me recently, but I can not find the notepad in which I save it :(

Please! :)

THANK YOU FOR BEING SO HAPPY TO US <3

**Comment by Megabyte918** [comment]
@Jhair2015 There already is a config for playerspeed, see [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L123).

**Comment by Jhair2015** [comment]
@Megabyte918 I mean that to make double fracture perfect or more or less good, I remember that you wrote me playerspeed: 1.2, something like that, sorry for the inconvenience! :(

**Comment by Megabyte918** [comment]
@Jhair2015 It doesn't have to be a solid "1" or "2" it could be anything in between like 1.1, 1.2, 1.3, etc. You can have any speed that you want it doesn't ***have*** to be a whole number. And what do you mean by "double fracture?" Also, don't be sorry. I like answering people's questions =D
