### ISSUE TITLE
How to change the size of border of cells?

### ISSUE THREAD

**Issue by AlexGallegos908** [Megabyte918/MultiOgar-Edited#380]
You see in this picture the border of the cells:
http://i.imgur.com/nJXdzQD.png

And here the border of actually:
http://i.imgur.com/8KV446i.png

actually are small the border, Im want to make big

**Comment by Megabyte918** [comment]
@AlexGallegos908 Client sided

**Comment by Jhair2015** [comment]
@AlexGallegos908 @Megabyte918  I think that depends on the resolution you have, the screen of Sirius is something big, while yours may be small or something.

**Comment by AlexGallegos908** [comment]
@Jhair2015 That depends on an update that they put in agar.io
