### ISSUE TITLE
Off the server after some time

### ISSUE THREAD

**Issue by Tyskacz** [Megabyte918/MultiOgar-Edited#383]
I have a problem with the trip on your own server after a few minutes,.

The server itself turns on but after a while he goes out and PuTTy crashes mistake of turning off the server. He knows something someone how to fix it?

`
[INFO ] 0 IP ban records loaded.
[WARN ] User account "Local Administrator" disabled
[WARN ] User account "Local Moderator" disabled
[WARN ] User account "Local User" disabled
[INFO ] 0 user records loaded.
[INFO ] 419 bad words loaded
[INFO ] MultiOgar-Edited 1.4.8 - An open source multi-protocol ogar server
[INFO ] WebSocket: ws
[INFO ] Started stats server on port 88
[INFO ] Listening on port 443
[INFO ] Current game mode is Free For All
`

**Comment by Tyskacz** [comment]
refresh

**Comment by Megabyte918** [comment]
This does not happen with me, then again I don't use PuTTy so I don't know what the problem could be.

**Comment by raphyjb** [comment]
@Tyskacz check you ur not getting ddos, i was using putty too and well everyday 1 of my 3 servers were offline for an unknowed reason.. I was getting ddos everytime my vps got online, so i ended my vps because of a ddos problem. and the only thing it says when it closes it something due to space, or speed not to sure.

**Comment by Andrews54757** [comment]
@raphyjb Reason why you dont show your ip, hence why Legit and I created the no-ip system for ogarul and openagar. I suggest you not to show your ip. In the meantime, you can reset your ip by releasing it. Search up on google "dhcp release". 



A wise saying:
> NEVER EVER SHOW YOUR F*ing IP!!!

**Comment by raphyjb** [comment]
@Andrew54757 kk will reset ip, but how can i share my server to poeple without them knowing my ip? cuz im using the agar.io/?ip= as my client...

**Comment by Tyler3D** [comment]
But, can't do DDOS the hostname you give

**Comment by Tyler3D** [comment]
@raphyjb You really can't hide your IP. Only thing you can do is either hope or get a powerful server that won't get knocked down easily by DDOS attacks

**Comment by Andrews54757** [comment]
@Tyler3D You are wrong, they cant ddos the hostname.

**Comment by Tyler3D** [comment]
Really? I thought you can find the ip from the hostname

**Comment by Andrews54757** [comment]
I am using a custom system

**Comment by Andrews54757** [comment]
Created by Legit and me

**Comment by Andrews54757** [comment]
You cannot ddos servers listed here http://forum.ogarul.io/pages/servers/

**Comment by Tyler3D** [comment]
Then that would mean you have no ip right?

**Comment by Andrews54757** [comment]
No, you have a ip, except we are the ones who have it, not the person who is playing.

**Comment by Andrews54757** [comment]
See, to join a server, you might do http://old.ogarul.io/?uid=XaFKCH2ewj

**Comment by Tyler3D** [comment]
That link you gave me doesn't come up with a IP. But, the old.ogarul.io link does

**Comment by Andrews54757** [comment]
ARGH

**Comment by Tyler3D** [comment]
So, you can DDOS old.ogarul.io and bring it down

**Comment by Andrews54757** [comment]
No, cloudfare

**Comment by Tyler3D** [comment]
ohhh

**Comment by Tyler3D** [comment]
I thought that was your network port forwarded

**Comment by Tyler3D** [comment]
nvm then 👍

**Comment by Andrews54757** [comment]
And the link I gave your for openagar is a example. I just opened my server up so you can see what it does. Link: http://opnagar.us/server/AndrewsOpenAgar

**Comment by Tyler3D** [comment]
You and Legit made a great IP spoofing system

**Comment by Andrews54757** [comment]
We just had too many ddos complaints

**Comment by Tyler3D** [comment]
ok lol

**Comment by raphyjb** [comment]
Is it possible to make a agar.io/?ip private server and that hinds the ip?!

**Comment by Tyler3D** [comment]
Sorta. Try making a tk domain a thttp://www.dot.tk/en/index.html?lang=en
Or you can make a no-ip account. http://www.noip.com/
Personially I like noip better cause it auto-updates you domain to you dynamic IP if you have one.
But, this only stop DDOS attacks from people that don't know how to get a IP from a hostname. or you can ask Andrew if he will help you.

**Comment by Tyler3D** [comment]
@raphyjb But remember it is ridiculously easy to get a ip from a no-ip hostname.
Step 1: Click the start button and type cmd
Step 2: click on cmd
Step 3: type ping "Insert hostname"
Step 4: DDOS that Ip xD

**Comment by systemroot** [comment]
>See, to join a server, you might do http://old.ogarul.io/?uid=XaFKCH2ewj.

@Andrews54757 so you think a ip can't be found because you did this uid way?
legit soulja disappoint me, i was waiting something more encrypted.

**Comment by Andrews54757** [comment]
@systemroot Of course no system is perfect. Actually, we can make it perfect, but the problem is that it requires for us to use more of our resources.

**Comment by Andrews54757** [comment]
I was thinking of having a server that is basically a "switch". So this is how it would work

1. Client requests switch server
2. Contacts switch server and give keys to verify. (public private key encryption) 
3. Then the game is playable


How?

1. Client plays via switch
2. Switch fowards ws messages to the actual server
3. Switch fowards outbound ws messsages to the client

DDOS?

1. Doesnt have the right keys.
2. Wont foward messages to server


However, the problem is, is that it would mean that our switch server would have to be very powerful, as it needs to be powerful enough to stop ddosing.

**Comment by Andrews54757** [comment]
That way, the client never actually directly connects to the server. It connects through the switch.

**Comment by Tyler3D** [comment]
yea that would be a problem cause if the switch server stops working nobody can play

**Comment by Tyler3D** [comment]
and high latency

**Comment by Tyler3D** [comment]
but otherwise it seems like an amazing DDOS protection system

**Comment by Andrews54757** [comment]
Then again. Most ddosers are noobs or idiots. So a complex system might not be needed

**Comment by Tyler3D** [comment]
lol true

**Comment by MastaCoder** [comment]
@Andrews54757 you're wasting your time. It took me literally 4 seconds to find the IP of the server.

73.198.77.45:444 is the IP and port of http://old.ogarul.io/?uid=stzazkEGbq. You're pretty much doing random encryptions and added useless security for no reason.

I agree with @systemroot. This method is just disappointing.

**Comment by MastaCoder** [comment]
p90ir;objc /il5bk65 ;oyibv uj;uij7

**Comment by Andrews54757** [comment]
@MastaCoder I already stated that it is very easy. It is to discorage noobs.

**Comment by MastaCoder** [comment]
@Andrews54757 I knew how to do this before I even learned Javascript, I think it's a waste of time. There really is almost no way of hiding an IP. Unless if you can send it through another server and have that data get transmitted back. Something like a proxy/DDoS protection.

Client -> hidden server -> target

Then this would really push away people that don't really know how to go deeper with connections. So they won't be able to find this. However, this method costs money and would need a really damn powerful server if it's going to be expanded.

**Comment by Andrews54757** [comment]
@MastaCoder Already stated above ^^

**Comment by Andrews54757** [comment]
Did you just wake up?

**Comment by Andrews54757** [comment]
Quoting myself like 10 messages ago:

>  I was thinking of having a server that is basically a "switch". So this is how it would work
> 
> 1. Client requests switch server
> 2. Contacts switch server and give keys to verify. (public private key encryption) 
> 3. Then the game is playable


How?

1. Client plays via switch
2. Switch fowards ws messages to the actual server
3. Switch fowards outbound ws messsages to the client

DDOS?

1. Doesnt have the right keys.
2. Wont foward messages to server


However, the problem is, is that it would mean that our switch server would have to be very powerful, as it needs to be powerful enough to stop ddosing.

**Comment by Andrews54757** [comment]
@MastaCoder Also, maybe you can supply me with the powerful servers I need. If you want a better method, then we need to have more resources, theres no other way.

**Comment by MastaCoder** [comment]
@Andrews54757 It's pretty useless to do this much other way. The method we're thinking of won't work and would cost more.

Instead just run the games on servers that are DDoS protected certified, this'll save money from paying off the other servers.

**Comment by Andrews54757** [comment]
> Instead just run the games on servers that are DDoS protected certified

No server is ddos certified

**Comment by Andrews54757** [comment]
Also, the method I am thinking would work, but it would be costly

**Comment by raphyjb** [comment]
but why is it dangereus to send your ip?? Do wat u want seriously i wanna see some damage done :P 206.167.188.2 
Try me!

**Comment by MastaCoder** [comment]
@Andrews54757 Not DDoS certified, protected. Most free-booters are less than 20Gbps which many many many cheap hosts offer 25Gbps protections for free. You can even get bigger ones that could offer more, it would be a cheaper alternative. I don't see why wasting time on this is useful anymore, there are bigger things to take care of. Such as bots.

**Comment by raphyjb** [comment]
@MastaCoder Can u attack me? lol! I just wanna know what u can do. Guess u cant do much... :/

**Comment by Andrews54757** [comment]
@MastaCoder Cloudfare supports websockets

**Comment by AlexHGaming** [comment]
Try using codeanywhere?

**Comment by MastaCoder** [comment]
@AlexHGaming no. You people are the reason why good things don't last.

**Comment by MastaCoder** [comment]
@Andrews54757 Well it won't be long before someone does.

**Comment by Andrews54757** [comment]
@MastaCoder Then I would scramble again

**Comment by MastaCoder** [comment]
@Andrews54757 That's not a really good practice of doing things like this. The people that have it would also have to update their packets as well everytime you do. Doing this all the time is just going to have people give up on it all together.

**Comment by Andrews54757** [comment]
@MastaCoder I have it automatically update packets. Do you not know me?

**Comment by MastaCoder** [comment]
@Andrews54757 Nobody really wants to use just the OgarUL client is what I'm trying to say. You locking down things is just way too much. You might as well just make OpenAgar closed source.

**Comment by MastaCoder** [comment]
@Andrews54757 I have nothing wrong with the project you make or how you do it. It's just how you execute it. (Also, I don't like you since you accused me of botting with no god damn research) You're making OpenAgar into a full blown closed source project where you control everything. You might as well offer the hosting as well so that it makes it impossible to figure out the backend by the way you're going. The project is good, however, the way you're locking it down makes it difficult for people like me to actually really "self-host" it (if you know what I mean).

**Comment by Andrews54757** [comment]
@MastaCoder I want to make it fully open source. But I will tell you something, if I dont, then people will misuse it. Take a look at the difference between OpenAgar and Ogar, Openagar is not plagued with bots, nor is it plagued with idiotic issues (which involve the issue creator being a noob). However, Ogar has a larger community, and is easier to host. You might then say "How would people misuse it?" Well, OpenAgar is planned for many things, many including more usage of our resources to make it better. Think of global chat, rankings, and more. If I dont make it semi-private, then everything is gonna blow. People would start to misuse the chat (spam, profanity, more), People would hack rankings and other things would also happen such as the misuse of skins (OgarUL porn). @MastaCoder Theres no other way

**Comment by Andrews54757** [comment]
@MastaCoder Think of a way in which it is possible to prevent people from misuse, while it being fully open sourced

**Comment by Andrews54757** [comment]
Also, take a look at the issues section of this project. Theres already over 350! And they look a lot like OgarUL issues!

**Comment by raphyjb** [comment]
@Andrews54757 Porn skins are already on, by doing example [goo.gl/] well u opened everyone to have skins like that, one of the big reasons i stop making my server, there was a good 10% using those skins and each time i put them in banned names, they would create a new link. DDOS also a huge problem for me even if u greated ur uid= on site still very easy to get ip.. :/

**Comment by Andrews54757** [comment]
@raphyjb Exactly, I am trying to make OpenAgar different from all the other ogars

**Comment by Andrews54757** [comment]
@raphyjb I wanted to have good features, such as the custom skin system, however, people are misusing it and using porn. This will never happen for OpenAgar

**Comment by Andrews54757** [comment]
@raphyjb DDOS is something I cannot prevent. Use cloudfare

**Comment by raphyjb** [comment]
@Andrews54757 Alright, and in the client ( i mean the website ) could you please add more features like show all players mass, minimap, chat, and pls dont ban poeple users with tampermonkey (scripts) that was a dumb idea @LegitSoulja did and alot quit in the past the last month. To bad could tell him, site was going in a decrease with the number of poeple playing.

**Comment by LegitSoulja** [comment]
@systemroot When I re-made the statistics system you rushed me, hated DDOS attacks, wanted more privacy etc. I did limited amount of work to spoof connection data, however JavaScript is what lacking due to using Dev tools. However, I can make it better, but I kindof gave up on Ogarul all together. I only make things that's noob proof. Did it work? 70%

@raphyjb my system is 100% legit, with reports. People got banned for a reason. The script detection system is mainly to stop bots. You can say it ruined other people expiernece but tell me when was the last time you seen bots flooding a server making it not fun. Scripts are noobish anyways. And I don't allow it.

However, that doesn't mean bans are permanent. If you're banned, submit a ticket. Then I'll look over your case number to actually see if you're using bots. My system has not yet failed. I've been tracking stats for almost 5 weeks. Is it my problem people using scripts? No. Is it my fault people can't have nice things? No. Eventually the site will be shut down, including the project. 

I got things to do, other than sitting around github, and playing video games.

**Comment by Andrews54757** [comment]
@LegitSoulja The ddos protection system only discorages noobs. I can get past in 3 sec with devtools. And I think there would be no need for the script detection thing for OpenAgar. No one found out how it works exactly yet

**Comment by LegitSoulja** [comment]
@Andrews54757 well of course. Duh. Script detection was created due to bots. That'll never happen with OpenAgar.

**Comment by LegitSoulja** [comment]
If that's what you people want is for the script detection to be removed then fine!!!! Enjoy the bots flooding servers. I tried to give a favor, but get accused over for doing a good thing. But whatever.

**Comment by LegitSoulja** [comment]
Polarsbots welcome back.

**Comment by LegitSoulja** [comment]
@Andrews54757 How about we just terminate OgarUl as of right now?

**Comment by LegitSoulja** [comment]
Banned table has been dropped, script detection has been obliterated, and alot of other client functionalities has been removed aswell. 

You're welcome!!

**Comment by LegitSoulja** [comment]
Lol, Deleting my comments wont help kiddos. Anyways' let me get off this repo before I commit a homicide playing with these kids (calming myself down).

**Comment by ZfsrGhS953** [comment]
@LegitSoulja What? We already bypassed your protection, so that was completely unnecessary, because it will bring even more bots into OgarUL.

**Comment by LegitSoulja** [comment]
@ZfsrGhS953 Kid I don't want to hear that BS. Bypassed my ass.

**Comment by LegitSoulja** [comment]
Have some of my roasted salty nuts.

**Comment by Megabyte918** [comment]
@Tyskacz If your problem keeps occurring, please make another issue regarding the subject. Sorry but I have to lock this for now.
