### ISSUE TITLE
Is possible?

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#384]
1) minion spawn alongside to its owner
2) the owner of minion can set that nick
3) the minion have same name of the owner
4) if the player have skin the minion will have the same skin
5) minionSpeed
6) Minion splitSpeed

**Comment by PrinceDark9243** [comment]
1. minion spawn alongside to its owner
This can be possible but useless
-------------------------------------------
2. the owner of minion can set that nick
This can be possible but useless
-------------------------------------------
3. the minion have same name of the owner
This can be possible but useless
-------------------------------------------
4. if the player have skin the minion will have the same skin
This is little but tough in view of my point but useless
-------------------------------------------
5.minionSpeed
      and
6.Minion splitSpeed

can be possible BUT USELESS

**Comment by PsycoYT** [comment]
retard..

**Comment by AlexHGaming** [comment]
I can answer a bit:
2. To set a nick on the minion(s), do the following:
`minion [ID] [Amount] [NAME]`
3. Do previous step.
4. Set skins by doing 2 of these possibilities:
`1. In the CMD, do this;`
`minion [ID] [Amount] [<SKINNAME>] [Name]`
OR:
`2. Go to gameserver.ini.`
`Find the minion section (near the bottom of the file)`
`Where it says` `minionName`, `Put in:`
`<skinname> Example`
So for example if I did this:
`<kraken> AlexHGamingBots`
It would come out as all bots using the kraken skin with their names set as AlexHGamingBots.
OR if you followed the CMD step; Example;
`minion 1 65 <jotun>AHGBots`
All minions will come out with the Jotun skin with the name 'AHGBots'
If you have any questions, just tag me with your issue in the comments of issue and I will try to solve it!

**Comment by AlexHGaming** [comment]
Oh yeah and your solution to Q5 & Q6, do the following (this changes the split speed overall);
1. Go to the gameserver.js file.
2. Press CTRL+F and find: ` newCell.setBoost`
3. The number after that should say '780'
4. The more lower you set that number, the more slower the splits are.
Happy to help.

**Comment by AlexHGaming** [comment]
I know you want this just setup through the files to default, but don't know if it is possible.

**Comment by Megabyte918** [comment]
^^
@PsycoYT Please be nice to others.

**Comment by Agarian** [comment]
^^

**Comment by RelTakeover** [comment]
@Megabyte918 help me ?
