### ISSUE TITLE
Really?

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#386]
@Megabyte918 you said that this push split will work but i tried many time dosent work if you are right just make a video then show me please dont close this as a DUPLICATE!

WATCH CAREFULLY WHAT HAPPENS IN VIDEO
https://www.youtube.com/watch?v=PB0s5wrXSRs&t=65s

**Comment by Megabyte918** [comment]
@PrinceDark9243 It works, trust me. I've done many of them. And I don't have time to make a video.
Please do not make anymore duplicate/invalid issues.
