### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#389]
version 1.5.0 reconnect every second with Cygar. I temporarily rollback to 1.4.8 (07-01).

**Comment by Luka967** [comment]
Paste a part of the log when you try connecting to the server. It might give us an idea why does the socket close.

**Comment by Gimmo** [comment]
Problem was by my hands. Close.

**Comment by systemroot** [comment]
same problem is with me too.
when i connect without a name i keep reconnecting every min or sec. 
when i join with a name that doesn't happen!
