### ISSUE TITLE
Bug report with minions

### ISSUE THREAD

**Issue by Agarian** [Megabyte918/MultiOgar-Edited#39]
- When attempting to give other's minions, the "other" gains mouse control of ALL minions.
- Others can control someone else's minions With E, R, T.

**Comment by Megabyte918** [comment]
@Agarian I am aware of the first one, it has been noted in [#7](https://github.com/Megabyte918/MultiOgar-Edited/issues/7) and [in projects](https://github.com/Megabyte918/MultiOgar-Edited/projects/1). And I'll look into the second one, thanks for letting me know =D

**Comment by Agarian** [comment]
Ok thanks lol

**Comment by Agarian** [comment]
I'm also on Discord

**Comment by AlexandriteErikParacelsus** [comment]
Legend said agarian was never gone

**Comment by Agarian** [comment]
Legend says the original Ogar-Unlimited may soon be reborn...

**Comment by Fantasy-Agario** [comment]
That legend is correct :D 

I tested it already :)

**Comment by Agarian** [comment]
Wow and it isn't even finished xD

**Comment by Fantasy-Agario** [comment]
XD
