### ISSUE TITLE
SPLIT

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#390]
How can I make the divisions more similar to OGARUL, in the current version? This is not duplicate since the previous problem was for a much older version

**Comment by Jhair2015** [comment]
@RelTakeover  Then use old version to have OGARul spaces, in this version, they have changed the location from where it should be changed, I already tried it.


@Megabyte918

**Comment by Megabyte918** [comment]
@RelTakeover Find these values in GameServer.js:
<pre>
var m1 = ~~c.cell1._mass / m;
var m2 = ~~c.cell2._mass / m;
</pre>
Multiply them by any number lower than 1 to reduce the snappiness.
