### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#392]
`GameServer.prototype.mainLoop`  uses `cell1`. If it ever defined, it's used out of scope. How to correct this?
The same with `size1` in `GameServer.prototype.splitPlayerCell`.

**Comment by AlexHGaming** [comment]
@Megabyte918 @FantasyIsBae

**Comment by Gimmo** [comment]
I used jsHint to check GameSever.js . I think it should be refactored, because it's full of syntax problems. So I close this issue, because problem have global character and haven't fast solution.
