### ISSUE TITLE
How to make no team mode? (Solo)

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#394]
cells only eat 98% of the enemy cells. How?

Sorry for bad english..

**Comment by Agarian** [comment]
Apologies, but can you please reword this? Thank you

**Comment by Megabyte918** [comment]
@RasyiidWho Edit [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Cell.js#L62) line in Cell.js, remember it uses size not mass.

**Comment by Agarian** [comment]
What did me mean?

**Comment by Megabyte918** [comment]
I think he wanted to make it so when you eat a player, you only gain 98% of their mass.

**Comment by RasyiidWho** [comment]
can you explain more widely? im noob in js

**Comment by RasyiidWho** [comment]
ogarul have this feature

**Comment by RasyiidWho** [comment]
Can you make it in MultiOgar-Edited config?

https://github.com/AJS-development/Ogar-unlimited/blob/master/src/settings/config.ini#L77-L81

**Comment by Megabyte918** [comment]
<pre>
this.setSize(Math.sqrt(this._sizeSquared + prey._sizeSquared));
</pre>
Sets the size of the cell to the square root of it's own squared size plus the prey's squared size

And no for performance reasons, onEat is called every single time an entity is consumed (this includes food, ejected mass, etc) so having the server get the config value from gameserver.ini every time would not be good.

**Comment by RasyiidWho** [comment]
can you make cell.js for me

**Comment by Agarian** [comment]
Yeah OgarUL does have a `massAbsorbedPercent` config i believe

**Comment by AlexandriteErikParacelsus** [comment]
yes they do

**Comment by RasyiidWho** [comment]
._.
