### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#395]
when ejectCooldown is 1 you cant throw virus fast.
The points pierce the virus

**Comment by Jhair2015** [comment]
@RelTakeover You can use decimal numbers.

**Comment by RelTakeover** [comment]
And what does that have to do with my problem?

**Comment by PrinceDark9243** [comment]
use 0.5 or 0.9 or anything else!

**Comment by Megabyte918** [comment]
@RelTakeover It works fine for me, the cooldown does not affect the way viruses eat ejected mass or how viruses split. Make sure you are using the latest GameServer.js

**Comment by ZfsrGhS953** [comment]
Increase virusMaxAmount to 1e999.

**Comment by RelTakeover** [comment]
yes @Megabyte918  Ejected mass goes through viruses when the max amount is reached, and that happens very quickly when having ejectCooldown and virusMaxSize set to 1 and using the eject macro.
