### ISSUE TITLE
Dynamic arrays vs allocated

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#398]
MO is full of dynamic arrays , where length of array depends on number of added/removed elements, unlike  of allocated (fixed length). Due to this, memory consumption is very small, but who need this?
To spend 80MB with cheap 1 gb server and to be limited by CPU productivity....
Operations on allocated arrays at least 10 times faster then dynamic, because of much less CPU load. 
May be allocated arrays should be used at least in collision engine?
Any thoughts?

**Comment by Megabyte918** [comment]
@Gimmo The only arrays the collision/move engine uses is the client array and movingNodes array, you can't really predict how many are going to be in either of them so using allocated arrays would cause bugs or just wouldn't work

**Comment by Andrews54757** [comment]
@Megabyte918 I suggest you use a Map (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) along with some polyfils (https://github.com/ThreeLetters/MapPoly/blob/master/index.js)

**Comment by Andrews54757** [comment]
It makes inserting/deleting nodes much faster.

**Comment by Andrews54757** [comment]
In that case, in order to delete: 


Without map
```
var index = someArray.indexOf(node)
if (index != -1) someArray.splice(index,1)
```


With map
```
someMap.delete(index)
```

**Comment by Gimmo** [comment]
@Megabyte918  Do you remember errors with lengths in loops? It was because of high dynamics (splice inside loop) . If we use `=null` instead of `splice` , it will be big difference.
Not all arrays need to be allocated, but which has maximal dynamics.
It's easy to predict(set) **maximum available size** for most critical arrays.

**Comment by Andrews54757** [comment]
@Gimmo Map is the best

**Comment by Gimmo** [comment]
@Andrews54757 Just because of shorter notation? Problem of `arrays` is on amount of hidden memory allocations when array size is modified. Why do you think `map` don't make this?

**Comment by Andrews54757** [comment]
@Gimmo Do you know how slow .indexOf of is?

**Comment by Andrews54757** [comment]
it literally goes through every item in the array to see if one matches

**Comment by Andrews54757** [comment]
@Gimmo Performance also shouldn't be a problem as well, the map object is native. Do you also know how slow .splice is?

**Comment by Gimmo** [comment]
@Andrews54757  jsPerf know ewerything. Problem is not a method! Problem is array dinamic memory allocation!!!

**Comment by Andrews54757** [comment]
http://stackoverflow.com/questions/30744355/why-is-array-splice-so-slow

**Comment by Andrews54757** [comment]
http://stackoverflow.com/questions/6682951/why-is-looping-through-an-array-so-much-faster-than-javascripts-native-indexof

**Comment by Andrews54757** [comment]
@Gimmo A map doesnt need to use .indexOf or .splice.

**Comment by Gimmo** [comment]
@Andrews54757  **Problem is not a method! Problem is array dinamic memory allocation!!!**

You don't read me? WTF difference? We talk about array !!!! 
As **method** map is shit just because have 10 times lower productivity  then native loop.

**Comment by Andrews54757** [comment]
@Gimmo You dont understand how it works dont you?

**Comment by Andrews54757** [comment]
@Gimmo Do you know how dynamic arrays work?

**Comment by Andrews54757** [comment]
@Gimmo The reason why a dynamic array is considered to be slow, is because it needs to "clone" itself whenever changing the amount of allocated memory. However, the change in the amount of memory only happens when the array is filled more than it's current limit. Then, it doubles the amount of allocation. But in order to do that, it has to loop through every object in the array in order to copy it to the new one. But this is not a problem, because the probability it does this, decreases rapidly as it happens

**Comment by Andrews54757** [comment]
@Gimmo Map is also a native class

**Comment by Gimmo** [comment]
@Andrews54757 
Ewerything you wrote have no sence, Just make the tests and you will understand.

**Comment by Gimmo** [comment]
@Andrews54757  Do you know what is jsPerf at all?

**Comment by Andrews54757** [comment]
@Gimmo I know what jsperf is. And I will tell you something: Those tests are not reliable

**Comment by Andrews54757** [comment]
@Gimmo Do you speak spanish? Hablas espanol?

**Comment by Gimmo** [comment]
@Andrews54757  no Spanish

You can build your own test with easy. If you will run it in Chrome - it will be close enough to node.js.
Tests should be alternative to be free of real productivity of your browser.

**Comment by Andrews54757** [comment]
@Gimmo Basically no difference:

<img width="1042" alt="screen shot 2017-01-12 at 8 42 42 pm" src="https://cloud.githubusercontent.com/assets/13282284/21915400/b5aff7fc-d907-11e6-98cc-f8aeb9c18923.png">

**Comment by Andrews54757** [comment]
@Gimmo Comparing with map:

<img width="1021" alt="screen shot 2017-01-12 at 8 44 33 pm" src="https://cloud.githubusercontent.com/assets/13282284/21915460/f6cc5870-d907-11e6-883a-ae7cd9a4d16a.png">

**Comment by Andrews54757** [comment]
map is faster

**Comment by Andrews54757** [comment]
Let that sink in...

**Comment by Andrews54757** [comment]
@Gimmo Also, for deleting items:

<img width="973" alt="screen shot 2017-01-12 at 8 49 55 pm" src="https://cloud.githubusercontent.com/assets/13282284/21915578/bbb03828-d908-11e6-9c02-c31c89faf7f4.png">

**Comment by Andrews54757** [comment]
Map is twice as fast

**Comment by Andrews54757** [comment]
@Gimmo For getting items:

<img width="973" alt="screen shot 2017-01-12 at 8 49 55 pm" src="https://cloud.githubusercontent.com/assets/13282284/21915627/2d354376-d909-11e6-9253-c755822cdd46.png">

**Comment by Andrews54757** [comment]
@Gimmo For getting items:

<img width="965" alt="screen shot 2017-01-12 at 8 53 22 pm" src="https://cloud.githubusercontent.com/assets/13282284/21915635/39e20c94-d909-11e6-9d3c-b7c63e7c3c43.png">

**Comment by Gimmo** [comment]
@Andrews54757 Faster then what? Problem is array dinamic memory allocation!!! We should not compare map! We should compare **set of dynamic arrays** with **set of allocated arrays**.
**Allocated array** - array of fixed length
**Dynamic array** - array changing length while adding/removing elements.

do not mix acidic with a long

**Comment by Andrews54757** [comment]
@Gimmo There is no problem.

<img width="1021" alt="screen shot 2017-01-12 at 8 44 33 pm" src="https://cloud.githubusercontent.com/assets/13282284/21915460/f6cc5870-d907-11e6-883a-ae7cd9a4d16a.png">

**Comment by Andrews54757** [comment]
@Gimmo Like I said, you do not know how dynamic arrays work. So I am tired of arguing with you

**Comment by Andrews54757** [comment]
And a dynamic array doesnt change allocation size when a object is removed. It is only changed when it exceeds the amount allocated

**Comment by Andrews54757** [comment]
@Gimmo And jsperf proves you wrong. You said that jsperf knows everything

**Comment by Andrews54757** [comment]
@Gimmo In the graph above, you can see that the allocated array doesnt differ from the normal dynamic array by much.

**Comment by Gimmo** [comment]
@Andrews54757 
Feel free to stay with your opinion, because you absolutely dont understand the problem.

![untitled-22](https://cloud.githubusercontent.com/assets/4733405/21916079/a9c7ea46-d946-11e6-968c-a45d7a3399f7.png)

**Comment by MastaCoder** [comment]
lol rip

**Comment by Megabyte918** [comment]
Why can't we have nice things ;-;
