### ISSUE TITLE
FIx this!!

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#4]
Please solve doubles on MultihOgar
Double Splits are fired incorrectly :(

**Comment by AlexandriteErikParacelsus** [comment]
It appeared there is nothing wrong with double split

**Comment by Jhair2015** [comment]
Ok :)

**Comment by Megabyte918** [comment]
@Jhair2015 what did you mean?

**Comment by Jhair2015** [comment]
@Megabyte918 That the double spaces do not come out correctly, sometimes it comes out very strange, goes out very crooked, if you do not understand Digimelo to make an explanatory video :)

**Comment by Jhair2015** [comment]
@Megabyte918 Okay, thanks for taking the time to answer my questions, but is there no way to edit that?

**Comment by Megabyte918** [comment]
You can by lowering the splitting speed, changing the normalizedDistance/playerSpeed racio, or editing some stuff in the collision engine a bit, but as for editing the doublesplits while keeping the current settings, theres no way. The doublesplits come with the splitting physics and extrusion force of the cells and it cant be reversed as everything falls into place with vanilla in the current settings.

**Comment by PrinceDark9243** [comment]
@Megabyte918 Can i Test the Minions?

**Comment by AlexandriteErikParacelsus** [comment]
@PrinceDark9243 maybe, because all the codes are in a c9 workspace, you just need his permissions (I have mine xd)
