### ISSUE TITLE
Is there a way to make this possible?

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#40]
@Megabyte918 I love this extension extensively, I've tried with "ScrambleLevel" all the options and yet I can not see my partner using the same extension on the minimap! :(

Please tell me one way to make this possible! : D

**Comment by RelTakeover** [comment]
scrambleLevel fight against coordinates

**Comment by PrinceDark9243** [comment]
Try to set scrambleLevel to 0

**Comment by Jhair2015** [comment]
@RelTakeover  @PrinceDark9243 I have already tested on all Scramble Levels, however it did not work for me :(
Any other way to make that possible?

**Comment by Megabyte918** [comment]
@Jhair2015 It might be a problem with the extension itself, other clients/extensions with minimaps work for me on the server. However I've seen some in which their maps just don't work period on vanilla OR multiogar which means whoever made it didn't do it right. Test the minimap on vanilla first, make sure you have the same tags and all that and your doing it right, if you guys can see each other on vanilla then it's a problem with the server but if not its the maker of the extension's fault.

**Comment by Jhair2015** [comment]
@Megabyte918  Hahaha no problem, I already know how to connect with my friend through my server in Ogario V3

:) Likewise thank you for responding! : D

How did I do it ?: Well, I enter normal to the server with the extension running, then I create a party, that party I pass to my friend, that enters first to the server and then to the party and we put in specific tag and well It was how I functioned! :)

**Comment by Megabyte918** [comment]
@Jhair2015 Great! Glad you found a solution

**Comment by Jhair2015** [comment]
:D
