### ISSUE TITLE
Is possible?

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#400]
is possible use a iframe from agar.io to my website and use jquery to edit the index.html ?

We can create rockets, but do not use jquery to edit an iframe ?

**Comment by MastaCoder** [comment]
No, that'd be cross-origin editing which is something you simply can't do.

**Comment by RelTakeover** [comment]
@MastaCoder 
And could I add a chat? with jquery or something like that ?

What things can I do? Apart from an iframe

**Comment by RelTakeover** [comment]
or is possible execute the iframe with a ogar.io extension included?

**Comment by MastaCoder** [comment]
yes, yes, nothhing, no.

**Comment by Megabyte918** [comment]
@RelTakeover Please do not make issues unless it relates to this project, thanks
