### ISSUE TITLE
Here some new features, I hope to appreciate my idea! : D

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#401]
1 - When one has bots, and is in viewer mode, I can not press "Q" to move freely around different parts of the map. ¿Would it be possible to fix this bug or implement another key for FREE SPECTATE?

2- Add minion follow cell. I mean the minion just follow the cell and not the mouse.

Thank you for your time.

**Comment by Megabyte918** [comment]
@Jhair2015 
> 1 - When one has bots, and is in viewer mode, I can not press "Q" to move freely around different parts of the map. ¿Would it be possible to fix this bug or implement another key for FREE SPECTATE?

If this was "fixed" you would not be able to control your minions in spectate mode.

> 2- Add minion follow cell. I mean the minion just follow the cell and not the mouse.

What's the point?

**Comment by Jhair2015** [comment]
Ok, I will close this.
