### ISSUE TITLE
How To Change Server Name in Chat | SOLUTION

### ISSUE THREAD

**Issue by W4rky** [Megabyte918/MultiOgar-Edited#402]
<li><b>Hello , today I will show you how to change the welcome message of the chat.
</b></li>
<br>
http://imgur.com/lWV4FEO
<br>
<br>
<li><b>Go to src , open PacketHandler.js</b></li>
<br>
<li><b>This is default config</b></li>
http://imgur.com/e8A0Eoa
<br>

<li><b>Now change default config and change with this</b></li>
http://imgur.com/aDmPd0K
<br>
<li><b>This is code</b></li>
<br>

> this.gameServer.config.serverName
<br>
<li><b>Once this is done, go to gameserver.ini</b></li>
<br>
http://imgur.com/OQMuiK5
<br>
<li><b>Now , change , in serverName MultiOgar #1 and put your server name</b></li>
<br>
<li><center><b>Result</b></center></li>
http://imgur.com/WM2pZUs

**Comment by RelTakeover** [comment]
Delayed closes this.

**Comment by Megabyte918** [comment]
This is not needed, but thanks anyway :)
