### ISSUE TITLE
@MegaByte918, I need help.

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#405]
@Megabyte918 
I am looking into a solution on making my server great.
You made a comment on the MultiOgar page ages ago: https://github.com/Barbosik/MultiOgar/issues/333
When you made 4 solutions on how to make it better, well first off, you forked this off the original MultiOgar. On the 3rd solution (change number from 2, to 2.5), I can't find this line in my gameserver.js: ` var splitMass = curMass / 2;` how do you change the value from 2, to 2.5? Because I can't find this?
I tested all of this on the original MultiOgar, and the popsplits are amazing for me
But I want to have the same physics on the MultiOgar-Edited.
Hope you can help! I want to know, and if it works, I'll be extremely happy.

**Comment by AlexandriteErikParacelsus** [comment]
Jesus the caps

**Comment by AlexHGaming** [comment]
@AlexandriteErikParacelsus lol

@Megabyte918

**Comment by Megabyte918** [comment]
@AlexHGaming You cannot do that here, as this fork of MultiOgar uses a different formula for virus explosions than the Original does. In other words, that code does not exist anymore. Original `splitMass` function was replaced with `onEaten` in Virus.js, and the `splitMass` variables are now replaced with the virus explosion multipliers.

**Comment by AlexHGaming** [comment]
@Megabyte918 So is there no possible way to change it?

**Comment by Megabyte918** [comment]
@AlexHGaming You can either revert to MultiOgar's virus explosions, or you can tweak the two virus explosion multipliers I've mentioned in previous issues.

**Comment by AlexHGaming** [comment]
And also
when I copy and paste the `splitMass = curmass / 2; ` bit in on the right line, does this: /usr/bin/nodejs                                                                                                                                            
                                                                                                                                                           
/home/cabox/workspace/multiogar/src/GameServer.js:1356                                                                                                     
});                                                                                                                                                        
 ^                                                                                                                                                         
SyntaxError: Unexpected token )                                                                                                                            
    at Module._compile (module.js:439:25)                                                                                                                  
    at Object.Module._extensions..js (module.js:474:10)                                                                                                    
    at Module.load (module.js:356:32)                                                                                                                      
    at Function.Module._load (module.js:312:12)                                                                                                            
    at Module.require (module.js:364:17)                                                                                                                   
    at require (module.js:380:17)                                                                                                                          
    at Object.<anonymous> (/home/cabox/workspace/multiogar/src/index.js:4:18)                                                                              
    at Module._compile (module.js:456:26)                                                                                                                  
    at Object.Module._extensions..js (module.js:474:10)                                                                                                    
    at Module.load (module.js:356:32)                                                                                                                      
                                                                                                                                                           
 How to fix?

**Comment by Megabyte918** [comment]
@AlexHGaming Check your syntax

**Comment by AlexHGaming** [comment]
@Megabyte918 Right
I understand about the curmass not being in the code.
Please can you make some adjustments to my virus.js to make smaller sized popsplits have increased chance along with the smaller parts coming out at the start and more mass towards the end of the enemy's cell? (if you understand) : 
`var Cell = require('./Cell');

function Virus() {
    Cell.apply(this, Array.prototype.slice.call(arguments));
    this.cellType = 2;
    this.isSpiked = true;
    this.isMotherCell = false; // Not to confuse bots
    this.setColor({ r: 0x33, g: 0xff, b: 0x33 });
}

module.exports = Virus;
Virus.prototype = new Cell();

// Main Functions

Virus.prototype.canEat = function (cell) {
    // cannot eat if virusMaxAmount is reached
    if (this.gameServer.nodesVirus.length < this.gameServer.config.virusMaxAmount) {
        return cell.cellType == 3; // virus can eat ejected mass only
    }
};

Virus.prototype.onEat = function (prey) {
    // Called to eat prey cell
    this.setSize(Math.sqrt(this._sizeSquared + prey._sizeSquared));
    
    if (this._size >= this.gameServer.config.virusMaxSize) {
        this.setSize(this.gameServer.config.virusMinSize); // Reset mass
        this.gameServer.shootVirus(this, prey.boostDirection.angle);
    }
};

Virus.prototype.onEaten = function (c) {
    if (c.owner == null) return;

    var minSize = this.gameServer.config.playerMinSize,
    min = (minSize == 32) ? 30 : minSize, // minimun size of small splits
    cellsLeft = this.gameServer.config.playerMaxCells - c.owner.cells.length,
    numSplits = cellsLeft < (c._mass / 16) ? cellsLeft : (c._mass / 16),
    splitMass = (c._mass / numSplits) < min ? (c._mass / numSplits) : min;
    
    // Diverse explosion(s)
    var big = [];
    if (!numSplits) return; // can't split anymore
    if (numSplits == 1) big = [c._mass/2];
    else if (numSplits == 2) big = [c._mass/4,c._mass/4];
    else if (numSplits == 3) big = [c._mass/4,c._mass/4,c._mass/7];
    else if (numSplits == 4) big = [c._mass/5,c._mass/7,c._mass/8,c._mass/10];
    else {
        // ckeck size of exploding
        var threshold = c._mass - numSplits * splitMass; 
        // Monotone explosion(s)
        if (threshold > 466) {
            // virus explosion multipliers
            var v = c.isMoving ? 4 : 4.5;
            var exp = (Math.random() * (v - 3.33)) + 3.33;
            while (threshold / exp > 24) {
                threshold /= exp;
                exp = 2;
                big.push(threshold >> 0);
            }
        }
    }
    numSplits -= big.length;
    // big splits
    for (var k = 0; k < big.length; k++) {
        var angle = 2 * Math.PI * Math.random(); // random directions
        this.gameServer.splitPlayerCell(c.owner, c, angle, big[k]);
    }
    // small splits
    for (var k = 0; k < numSplits; k++) {
        angle = 2 * Math.PI * Math.random(); // random directions
        this.gameServer.splitPlayerCell(c.owner, c, angle, min);
    }
};

Virus.prototype.onAdd = function (gameServer) {
    gameServer.nodesVirus.push(this);
};

Virus.prototype.onRemove = function (gameServer) {
    var index = gameServer.nodesVirus.indexOf(this);
    if (index != -1) 
        gameServer.nodesVirus.splice(index, 1);
};
`

**Comment by AlexHGaming** [comment]
idc about lag, I just want server like this
Do this when you want to, I'm not pushing you to do it now lol

**Comment by AlexHGaming** [comment]
@Megabyte918 Why do you keep closing my issues?
I just want a partial fix in my code.

**Comment by Megabyte918** [comment]
![capture](https://cloud.githubusercontent.com/assets/17245196/21964799/1c397cf8-db21-11e6-9052-ccf05d46eb71.PNG)

**Comment by AlexHGaming** [comment]
But those are old updates and the virus.js code isn't the same as before.

**Comment by AlexHGaming** [comment]
Oh, I've fixed the problem in #332 
Thanks for a bit of help @Megabyte918
