### ISSUE TITLE
You can make bots more intelligent? Very boring to play :с

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#407]
You can make bots more intelligent? Just, well, judge for yourself from the enemy 10k I'm near Sneem into 16 cells(N). What would you do? :) Еat of course...

P.s: You can write questions in their native language? "Russian"

**Comment by AlexHGaming** [comment]
This is a duplicate.
Please check previous issues.

**Comment by AlexandriteErikParacelsus** [comment]
Just no
