### ISSUE TITLE
Merging bug

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#408]
Hi all
I'm actually not making a popsplit bug this time xD
Basicallly I want to say something that needs to be fixed but I don't know how to fix it,
Everytime I am in multiple pieces, I merge my self. After merging time is finished, and I am in 1 cell, I go to another virus so I could test something. For some reason, when I hit the virus, it merges me AGAIN instead of typing in `merge 1` how do I fix?
This really stresses me out when I hit the virus after getting force merged and merges me again.
@Megabyte918 @FantasyIsBae

**Comment by Megabyte918** [comment]
@AlexHGaming It's no bug; that's how its supposed to be. You stay merged in 1 piece until you press space again.

But if you would like to change it you can remove [these lines](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L423-L426) in PlayerTracker, then add the following code after [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L810) line in GameServer:

<pre>
if (cell.owner && cell.owner.cells.length <= 2) {
    cell.owner.mergeOverride = false;
}
</pre>

**Comment by AlexHGaming** [comment]
But I want to change it so I don't have to split once
The reason why I am asking for this is because I am estimating my popsplit physics and I keep changing the code.
But when I explode on the virus again it does the 'bug'
How can I change this so this doesn't happen?

**Comment by Megabyte918** [comment]
It does change it so you don't have to split once.

**Comment by AlexHGaming** [comment]
Thanks.
Closing
