### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by MineMooreALT** [Megabyte918/MultiOgar-Edited#409]
I NEED A WAY TO BAN SOMEONE IF THERE NAME COMES UP MORE THAN 5 TIMES example 5 bots spawn in with the name "somegaywebsite.tk" all the bots get auto banned
or instead of names getting replaced with hi there make it ban them please URGENT

**Comment by MastaCoder** [comment]
what, that doesn't even make sense. The person can just change the names lmao.

**Comment by MineMooreALT** [comment]
That's why I closed it because I realised it was dumb
