### ISSUE TITLE
Teams Gamemode gives mass

### ISSUE THREAD

**Issue by Niall7459** [Megabyte918/MultiOgar-Edited#410]
In Teams gamemode 1 After i reach certain mass (like eating 5 food or so) It starts growing me massivly until I fill the whole map!!!

Not happen on FFA.

**Comment by Agarian** [comment]
Yes, this is a decayMod bug, i'll PR a fix.

**Comment by Megabyte918** [comment]
Fixed in recent commits, thanks @Agarian
