### ISSUE TITLE
FPS (Speed)

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#415]
Is there a way to change FPS (Making Game little slower everything?)

**Comment by RelTakeover** [comment]
Decrease this val 👍  for slower speed

` var timeStep = 40;`

**Comment by Agarian** [comment]
`Gameserver.js` line 516 :arrow_up:

**Comment by Agarian** [comment]
@Megabyte918 close

**Comment by PrinceDark9243** [comment]
Thanks!
