### ISSUE TITLE
Protocol v11 released

### ISSUE THREAD

**Issue by NuclearC** [Megabyte918/MultiOgar-Edited#416]
title ^^

**Comment by Agarian** [comment]
@Megabyte918 We have an issue, new protocol (like he said), and MultiOgar-Edited isn't compatible

**Comment by ItzLevvie** [comment]
^^ https://github.com/Megabyte918/MultiOgar-Edited/pull/417

**Comment by Agarian** [comment]
Yep, it's fixed in that Pull. Awaiting the Megabyte

**Comment by ARBCells** [comment]
It seems that Raga solved the problem with leaderboard.

**Comment by PrinceDark9243** [comment]
@ARBCells What is Raga? and what is the link to that server?

**Comment by ARBCells** [comment]
@PrinceDark9243 Lol. Raga.pw

**Comment by PrinceDark9243** [comment]
Yes i know the raga.pw bots what are taking about the raga's server or other comment simple words and if you are talking about raga server tell me the link sorry for BLA XD
