### ISSUE TITLE
Server don't work now?

### ISSUE THREAD

**Issue by NiesamoWhite** [Megabyte918/MultiOgar-Edited#418]
Cadeanywere don't work and the normal sever don't work. I'm alone?

**Comment by Jhair2015** [comment]
@Megabyte918 Yes to me also does not let me enter my server, and I do not use the latest version: / use is https://github.com/Megabyte918/MultiOgar-Edited/commit/02887a8cf16d3b2fd25297bf40d10f06561736b9 And my host is DigitalOcean

**Comment by Agarian** [comment]
@NiesamoWhite @Jhair2015 Use the update from #417 
Leaderboards are still broken tho =\

**Comment by cowpits** [comment]
Not a muliogar issue from what i can tell. Looks like miniclip has updated the protocol for their client and thus no one can connect using agar.io. All other clients work like c0nsume.me/private4.php?ip work. I'm seeing errors in the console about unsupported protocol when people try to connect with agar.io client.

**Comment by ItzLevvie** [comment]
Check https://github.com/Megabyte918/MultiOgar-Edited/pull/417

**Comment by Jhair2015** [comment]
#FuckMiniclip

**Comment by cowpits** [comment]
@ItzLevvie I don't use custom skins script or tampermonkey or any extensions. My servers are practically dead now. I see people are trying to connect but failing. Anyway, all other clients work fine. I guess miniclip decided to block private servers again.

**Comment by Agarian** [comment]
USE the update in #417 -_-

**Comment by ItzLevvie** [comment]
^^^^^^^^^^^^^^^^^

**Comment by Agarian** [comment]
Or at least apply it...

**Comment by Agarian** [comment]
Miniclip isn't gonna block private servers that easily

**Comment by NiesamoWhite** [comment]
What is this #417 @Agarian ?

**Comment by ItzLevvie** [comment]
Apply patch from https://github.com/Megabyte918/MultiOgar-Edited/pull/417 to make your server work with the latest Agar.io update

**Comment by ZfsrGhS953** [comment]
This is an issue with Moneyclip, it has nothing to do with MultiOgar-Edited.

**Comment by AlexHGaming** [comment]
FINALLY MONEYCLIP DID LIKE A MOBLILE VERSION
NOW MY SERVER IS FUCKED!
THANKS MONYEYCLIP!!!

**Comment by cowpits** [comment]
I applied the patch but still can't connect unfortunately. This sucks. I tried it with 1.5.0 and 1.3.5 just sits there connecting.

**Comment by AlexHGaming** [comment]
I can press 'play' but nothing happens ;-;

**Comment by Agarian** [comment]
That may be a script, or you didn't  use #417

**Comment by AlexHGaming** [comment]
works now

**Comment by Agarian** [comment]
What about the leaderboard?

**Comment by NiesamoWhite** [comment]
idk

**Comment by cowpits** [comment]
ok i'm working now but like everyone else leaderboard is crapped out. lol

**Comment by Agarian** [comment]
Yep.

**Comment by Agarian** [comment]
Anybody have an idea on what to do? Cause i tried looking into the LeaderBoard bug and found nothing that stands out

**Comment by cowpits** [comment]
well the new update for the client shows your position on the leaderboard now. For instance when I joined an FFA server it showed me as 63. This is frustrating and my skype is hammered with people complaining. lol.

**Comment by Andrews54757** [comment]
Just inspect the packets

**Comment by AlexHGaming** [comment]
@Andrews54757 Make a commit then.
You can do us all a favour

**Comment by cowpits** [comment]
does anyone notice "null" at the bottom of the screen?

**Comment by Agarian** [comment]
Yes, that's a "daily quest" bug lol

**Comment by Agarian** [comment]
@Megabyte918 Got time for discord?

**Comment by Andrews54757** [comment]
@AlexHGaming Why should I, I am busy running my own project (Not just OpenAgar). I want to see how this goes, I want to see who here has knowledge of working buffers.

**Comment by Jhair2015** [comment]
@Andrews54757 Please, you are our only hope :(

**Comment by NuclearC** [comment]
ok seems like they changed leaderboard packet a bit.
<Buffer 31 0a 00 00 00 00 4a 61 6e 6f 50 4c 00 42 4c 41 43 4b 20 4a 41 43 4b 00 46 72 65 64 00 5a 2e 41 00 4d 2e 20 4b 45 4d 41 4c 00 f0 9f 8c 93 2b f0 9f 8c ... >
it goes Uint8 Uint32 and Uint8 (is me flag)

**Comment by NuclearC** [comment]
but i still cant click 'play' button when disabling integrity checks

**Comment by NuclearC** [comment]
and fucking mass of food is visible when spectating lmao

**Comment by ItzLevvie** [comment]
'but i still cant click 'play' button when disabling integrity checks' - @NuclearC 

Have you added the patch from https://github.com/ItzLevvie/MultiOgar-Edited/commit/77d2633abd919f820f589985ff372fbb874619bd

**Comment by cowpits** [comment]
clear your browser cache, I was having the same problem after I patched and play button wouldn't activate.

**Comment by cowpits** [comment]
and make sure you're logout from agar.io, clearing the cache will log you out but just in case.

**Comment by NuclearC** [comment]
ok thanks it works now, but any idea how to fix leaderboard?

**Comment by cowpits** [comment]
nope, i was hoping someone might be able to decipher the packets or release a patch.

**Comment by ZfsrGhS953** [comment]
XOR is a simple operation, it isn't really a cipher. More like "decode the packets"

**Comment by AlexandriteErikParacelsus** [comment]
no
