### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#419]
When I did the steps in #416, I can see
MultiOgar-Edited 1.5.0
but when I press play, doesn't work. Any solutions?
codeanywhere is what I host with.

**Comment by NiesamoWhite** [comment]
Just use normal characters like this -> abcdefg....... in your nickname

**Comment by AlexHGaming** [comment]
I have keyboard characters in my name
it's set out as AlexHGaming

**Comment by AlexHGaming** [comment]
working now
