### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#42]
How i can Stop Cell Switching when you double split like (1)(2)(4)(3)
i want (1)(2)(3)(4)

**Comment by PrinceDark9243** [comment]
I hope @Megabyte918 Can Understand it :D

**Comment by Megabyte918** [comment]
@PrinceDark9243 I will check it out

**Comment by Megabyte918** [comment]
@PrinceDark9243 I don't know how to fix this exactly, but I have been able to reduce the rate of it happening a couple times. 

You can by reducing the splitspeed [here] (https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L1225)

Or by reducing the playerSpeed to [normalized distance] (https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/PlayerCell.js#L67) (the first 32) ratio

**Comment by Megabyte918** [comment]
@PrinceDark9243 I took another look at the splitting/collision engine, I found where it was coming from. https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L854
![capture](https://cloud.githubusercontent.com/assets/17245196/20293577/94b19c10-aac5-11e6-9db6-440e53597b11.PNG)
If you wan't to get rid of the order switching, you have to get rid of the two lines under this comment:
<pre>
// cell1: switches order (-+-- or --+-)
manifold.cell1.position.x -= px * impulse1;
manifold.cell1.position.y -= py * impulse1;
</pre>
If you want to get rid of the order NOT switching, get rid of these two lines under the other comment:
<pre>
// cell2: doesn't switch order (---+)
manifold.cell2.position.x += px * impulse2;
manifold.cell2.position.y += py * impulse2;
</pre>
But be warned, cells not switching order results in less snappy and less fast doublesplits,

**Comment by PrinceDark9243** [comment]
it works but i cant able to split in straight line like normal

**Comment by Megabyte918** [comment]
@PrinceDark9243 
> But be warned, cells not switching order could result in less snappy and less fast doublesplits, along with slightly more snappy splitting.
I am aware of this, I will work on the collision engine so that way you can keep the same splitting along with the same rate of cells switching order.

**Comment by Megabyte918** [comment]
@PrinceDark9243 Oh crap! I forgot I closed this without even explaining why >.<
The last few updates to GameServer.js should have made it so cells switch order the same rate as vanilla, I tested it by doing multiple double-tricksplits and 4/5 times the cells did not switch order (they ended like this: ---+). Alot better than it was before.
