### ISSUE TITLE
Dont work agar client! Why?

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#420]
Why not connect the client Agario?
Do not write that another client, you can use...

**Comment by AlexHGaming** [comment]
because of the new update

**Comment by ZfsrGhS953** [comment]
This is both invalid and a duplicate of #418 , it's an issue with Moneyclip.

**Comment by DeadLord1337** [comment]
soon you correct this mistake likely?

**Comment by ItzLevvie** [comment]
Download the latest MultiOgar-Edited.... it should work now.

**Comment by Agarian** [comment]
@Megabyte918 close please lol
