### ISSUE TITLE
I need this please

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#421]
I can send the control of minions E, R, T and P
For agary colnes as astr.io - Pls I need it ...

**Comment by MastaCoder** [comment]
> I can send the control of minions E, R, T and P

what

**Comment by Jhair2015** [comment]
ERTPcontrol ----

But for several customers, I remember if I had sent one that supported several clients, but I lost it: /

**Comment by Agarian** [comment]
@MastaCoder He means this script: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/scripts/ERTPcontrol.js
But compatible with more clients than just agar.io.
And, no, doing `// @match` doesn't make it work for other clients apparently

**Comment by Jhair2015** [comment]
@Agarian  Lol had planned to do that, but maybe it would not work xD

**Comment by Agarian** [comment]
I mean, it would bind to the website, just not be compatible (Pressing those keys would do nothing)

**Comment by AlexHGaming** [comment]
What you have to do:
1. Go to the gameserver.ini
2. Find `disableQ` and `disableERTP` and turn them values from '1' to '0' (standard should have 1 value 0 and another 1'
3.Install the script, refresh agar.io and you should be fine.

**Comment by Jhair2015** [comment]
I need this for astr.io not agar.io

**Comment by AlexHGaming** [comment]
This is client sided, not MultiOgar sided.
@Megabyte918 close close close

**Comment by Jhair2015** [comment]
@AlexHGaming  Ok ok ok ok ok ok ok ok xD lol
