### ISSUE TITLE
How to play on others client?

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#423]
How to play on others client? For example : as a play on **dual-agar.online**

**Comment by AlexHGaming** [comment]
there are only a few clients available.
You can do this. Replace `agar.io/?ip=[IP]:[PORT]`
replace the agar.io with the client name.
For example
`nbk.io/?ip=[IP]:[PORT]`
Just replace the `agar.io` bit with the client name, if it says connecting... then the client doesn't support the private server.

**Comment by AlexHGaming** [comment]
@Megabyte918 Close.

**Comment by DeadLord1337** [comment]
dual-agar.online/?ip=[IP]:[PORT] - dont work...

**Comment by DeadLord1337** [comment]
oh sorry i blind :D

**Comment by AlexHGaming** [comment]
xD

**Comment by AlexHGaming** [comment]
And also this is client sided so please close it because I helped you and it's all solved.
