### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#425]
As some peoples know that Quest is the part of Agar.io Mobile but it came to PC so my suggestion is that to add Quest if a player complete a quest he will get reward like mass,speed,uneatable or anything

**Comment by AlexHGaming** [comment]
With the vanilla client this is not possible
We can't go into the game files and change it so we have quests in our private servers.
Because MegaByte doesn't control the vanilla agar so this can't be added.

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by PrinceDark9243** [comment]
ok i understand you but it can be done on server not on client and this is a suggestion

**Comment by Megabyte918** [comment]
This is a client-related issue.

**Comment by Jhair2015** [comment]
Gigabyte lol copyright from MegaByte XDD
