### ISSUE TITLE
New flag

### ISSUE THREAD

**Issue by NuclearC** [Megabyte918/MultiOgar-Edited#426]
I just discovered a new flags (0x80) that official servers are sending. That flag exists on every food cell record.

**Comment by NuclearC** [comment]
Also it adds some unknown byte before color that is always 0x01

**Comment by PrinceDark9243** [comment]
so what is does? does it make multiOgar run as Official Server?

**Comment by NuclearC** [comment]
no lol its just a cell flag

**Comment by Agarian** [comment]
This may have to do with the red text not showing on a leaderboard

**Comment by Tyler3D** [comment]
@Agarian It is
The missing flag is in packet 0x30. It is identical to the it's me flag used in previous leaderboard. But, in protocol 11 the flag is sent separately.

**Comment by Tyler3D** [comment]
I tried implementing the packet but failed :/

**Comment by Tyler3D** [comment]
The red text and your current position is determined by packet 0x30

**Comment by NuclearC** [comment]
no leaderboard position is related to packet 0x30, this is just a flag in cell update record packet

**Comment by Luka967** [comment]
I'll experiment with thia today

**Comment by Luka967** [comment]
this*. I'm on my phone xD

**Comment by Agarian** [comment]
lol

**Comment by Megabyte918** [comment]
@NuclearC @Luka967 Where does one learn how the protocol and packets and all that stuff works? I've been trying to figure it out but not making much progress, I don't know what to do xd
I figured I'd ask you guys, you seem to know how they work

Also I'm closing this since the flag was added

**Comment by Luka967** [comment]
Protocol learning takes a LOT of time. People had to reverse-enginner the packets. It is (was) all about sniffing (detecting and displaying) ws packets then opening an echo server and displaying the nodes. Sometimes it "worked" depending on

**Comment by NuclearC** [comment]
actually im learning with my own Client xD

**Comment by Luka967** [comment]
Is it the C++ one you posted on Reddit? xD

**Comment by NuclearC** [comment]
yeah
