### ISSUE TITLE
Leaderboard fix for protocol v11

### ISSUE THREAD

**Issue by NuclearC** [Megabyte918/MultiOgar-Edited#427]
Leaderboard packet looks like the same, only without 'isme' flag. So its just a list of string.
New packet with id '48' looks like.
Uint8 opcode
Uint16 my position

Right now i dont know how it changes if you are in top 10.

EDIT: packet 0x30 (aka 48) is sent right after every leaderboard packet. It contains the position of player in leaderboard and its sent when player is joined to game (not sent when dead or spectating).

**Comment by cowpits** [comment]
that works great! thank you

**Comment by Jhair2015** [comment]
Thanks You man! :D

**Comment by ZfsrGhS953** [comment]
A separate 59-byte packet just for your position in the leaderboard? Moneyclip does a pretty good job at optimizing the lag of their servers. Compare it with (this)[https://github.com/ZfsrGhS953/Petridish-Ogar/blob/master/Ogar/src/packet/UpdateNodes.js], I had this protocol (before the project turned into OgarU;) which sent all the data in a single packet, avoiding the 56-byte WebSocket headers.

**Comment by NuclearC** [comment]
why 59-byte? its only 3 bytes.......

**Comment by ZfsrGhS953** [comment]
The WebSocket header is 56 bytes long.

**Comment by NuclearC** [comment]
shit websocket header is just 3 bytes long and packet too, so it will be 6 byte tcp packet at all

**Comment by ZfsrGhS953** [comment]
It will be a 6 byte TCP/IP packet (not TCP). Both TCP and IP headers are 20 bytes long, which means that it'll be 20+20+6 (46 bytes)

**Comment by NuclearC** [comment]
and? you think its too much?

**Comment by MastaCoder** [comment]
@NuclearC it is. If you own servers you'd know all bandwidth is crucial and it costs money to get more. (Quite expensive as well if you go over)

Those 50byte can slowly add up. Right now my MultiOgar server is using about 11TB of bandwidth per month, that's a crap ton showing how I only get around 200 - 400 players on average.
