### ISSUE TITLE
hello you can help me?

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#429]
Hello I would like to do 2 things that although they do not have much to do with this, everyone would like to know

I want to put colorful clans! , I mean if you put zt in the name, the leaderboard will change the color of your name to another color

i have this code

```
 // Text-based
            var o, me = false, w, start;
            ctx.font = "20px Ubuntu";
            for ( ; i < l; i++) {
                o = leaderboard[i];
                if (leaderboardType === 0x31) {
                    me = o.me;
                    o = o.name;
                }

 ctx.fillStyle = me ? "#FFAAAA" : "#FFFFFF";
```

and How to place the current position without being top 10.

**Comment by AlexHGaming** [comment]
Leaderboards are currently being fixed
try pasting this in when the code is being fixed

**Comment by MastaCoder** [comment]
Isn't the leaderboard color client sided?

**Comment by Gigabyte918** [comment]
i think Agar.io dosent support color name!

**Comment by Megabyte918** [comment]
This is client sided, i'm pretty sure.
