### ISSUE TITLE
Minion pellet mode

### ISSUE THREAD

**Issue by XtremePlayzCODE** [Megabyte918/MultiOgar-Edited#43]
Could you add a minion pellet mode maybe by pressing Q two times really fast, like seeing how many times Q was pressed in a short amount of time, (e.g. 2 sec) and turning the minions into bots that only collect pellets temporarily until turned off

**Comment by NameYT** [comment]
DUPLICATE of #8

**Comment by XtremePlayzCODE** [comment]
"If many people request that I add the minions collecting pellets feature, I may add it." - Megabyte918. That's why I have a dupe.

**Comment by NameYT** [comment]
@XtremePlayzCODE just message it on #8

**Comment by XtremePlayzCODE** [comment]
Why don't you

**Comment by XtremePlayzCODE** [comment]
#8 done

**Comment by NameYT** [comment]
@XtremePlayzCODE Already Messaged it :p lets wait for @Megabyte918 to reply my options are when you click "p" as a collect pellet mode like extensions that would be awesome

**Comment by XtremePlayzCODE** [comment]
Say same

**Comment by XtremePlayzCODE** [comment]
#WeWantPelletMode

**Comment by NameYT** [comment]
@XtremePlayzCODE When you click "P" Minions will automatically collect pellets :)
http://agar.io/?ip=sambyonweed-samby6667851.codeanyapp.com:3000
Join my server if you want

**Comment by XtremePlayzCODE** [comment]
Wait wait, they do?

**Comment by XtremePlayzCODE** [comment]
Give me minions, i am XPC

**Comment by XtremePlayzCODE** [comment]
startmass 43 plz

**Comment by NameYT** [comment]
k

**Comment by XtremePlayzCODE** [comment]
YAS

**Comment by NameYT** [comment]
Wait i should make a Sponsor video xD

**Comment by XtremePlayzCODE** [comment]
TOO MUCH LAG

**Comment by XtremePlayzCODE** [comment]
andddddd its offline

**Comment by Fantasy-Agario** [comment]
RIP

**Comment by Jhair2015** [comment]
is stupid add the feature

**Comment by NameYT** [comment]
ADDDDDDDDDDDDDDDDDDDDD

**Comment by XtremePlayzCODE** [comment]
What?
