### ISSUE TITLE
Help with the servers http

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#431]
I get the admin and pass thingy for the http console stuff, and well im on black screen and when i write stuff down doesnt show me anything, and when i press upper button says unidentifed

**Comment by raphyjb** [comment]
[WARN ] User account "Local Administrator" disabled                                                                                                                                                     
[WARN ] User account "Local Moderator" disabled                                                                                                                                                         
[WARN ] User account "Local User" disabled 
how to turn them on? Not even sure if that has anything to do with it ;p

**Comment by raphyjb** [comment]
http://multiogar-edited-raphyjbeaudoin1658139.codeanyapp.com:1234/

**Comment by cowpits** [comment]
to get rid of these WARN messages go into /src/enum/ folder and edit userRoles.json put a password for each role. I haven't figured out how to pass console commands through the client though. I think you could use a module and rcon to pass chat commands through a client that supports chat like c0nsume or ogar.mivabe

**Comment by YazanYT** [comment]
hey
