### ISSUE TITLE
Hunger games

### ISSUE THREAD

**Issue by DaAwesomeRazor** [Megabyte918/MultiOgar-Edited#432]
Is hunger games fixed if it isnt fix it plox so I can use it

**Comment by Tyler3D** [comment]
@DaAwesomeRazor Hunger games no longer exists lol

**Comment by DaAwesomeRazor** [comment]
@Tyler3D Its ok i fixed it

**Comment by DaAwesomeRazor** [comment]
@Tyler3D All you gotta do is change the ticks, and spawn points and some collision stuff and it works

**Comment by Tyler3D** [comment]
@DaAwesomeRazor Ik but Mega deleted it a long time ago

**Comment by Tyler3D** [comment]
Nice job on fixing it tho!

**Comment by Gigabyte918** [comment]
so can you send  me tha server file

**Comment by Megabyte918** [comment]
@DaAwesomeRazor Pull request?

**Comment by Gigabyte918** [comment]
hi @Megabyte918 ^^

**Comment by Jhair2015** [comment]
@Megabyte918  @Gigabyte918  are clon lmao xD

**Comment by Gigabyte918** [comment]
no We are Twin bro XD

**Comment by Gigabyte918** [comment]
my old name is PrinceDark9243 now Gigabyte918 lmao

**Comment by Gigabyte918** [comment]
but i am little different profile lmao
