### ISSUE TITLE
Does not work anymore with agar.io client ?

### ISSUE THREAD

**Issue by Nic0x** [Megabyte918/MultiOgar-Edited#433]
I can't play anymore with agar.io client. You too ?

**Comment by ItzLevvie** [comment]
Use the latest version of MultiOgar-edited, this has been fixed.

**Comment by cowpits** [comment]
to play on agar.io client on private servers you need to logout of the account you use. 
min 4:17 of my video https://www.youtube.com/watch?v=m0nruKe1ILM&t=1s

**Comment by Nic0x** [comment]
Thanks, it works with 1.3.5 version by changing PacketHandler.js
But, does it changes the physic ? I have the impression that it does

**Comment by cowpits** [comment]
I'm using the fix on 1.3.5 I haven't noticed anything about physics although I'm not a good player. The only thing I'm still struggling with is the player name not highlighted on leaderboard. I'm not sure if it is addressed or still being worked on.

**Comment by cowpits** [comment]
BTW, I've done ChatMessage.js and LeadboardUpdate.js fixes

**Comment by Nic0x** [comment]
I haven't played for a long time with Multi Ogar, so maybe i'm wrong
What is ChatMessage.js and LeadboardUpdate.js fixes plz ?

**Comment by cowpits** [comment]
the ChatMessage.js I have no idea for sure but I've been following and applying. LeaderboardUpdate.js if you have a server and did the PacketHandler.js and didn't do the leaderboard fix you'll notice the leaderboard filled with An Unnamed Cell. I have it captured in my video. The update fixes that but the player name is plain and not highlighted in light red color.

**Comment by Nic0x** [comment]
Okay thanks
Is there a tutorial to do these modifications ?

**Comment by cowpits** [comment]
they were merged into the latest build but they work on 1.3.5 version as well.

**Comment by Nic0x** [comment]
Okay, thanks a lot for your help

**Comment by cowpits** [comment]
In case I wasn't clear, simply replace both ChatMessage.js and UpdateLeaderboard.js if you don't want to get the latest 1.5.0 build and you use 1.3.5. The two files are here, you'll see the commit of days ago. https://github.com/Megabyte918/MultiOgar-Edited/tree/master/src/packet 
Just replace what you currently have in /src/packet/
