### ISSUE TITLE
Someone who can help me with my website!

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#434]
I need help on this, I have a client, but every time I enter it closes, any idea how to solve it?

http://i.imgur.com/2D71tzr.png

**Comment by Jhair2015** [comment]
Pls.

**Comment by MineMooreALT** [comment]
ill help

**Comment by Jhair2015** [comment]
@MineMooreALT Nah already leave it, solve it, by protocol v11
Was predetermined at 11, my client did not do that, then I changed it to 9 and everything went well, it hurts that I did not like my client :p
