### ISSUE TITLE
try edit

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#435]
when i try edit in .js archive it says "VARIABLE NOT DEFINED" but is defined but above , how to do ?

**Comment by DaAwesomeRazor** [comment]
??

**Comment by AlexHGaming** [comment]
?? [x2]

**Comment by AlexHGaming** [comment]
Which .js file are you talking about?

**Comment by gyeyoqu** [comment]
When I try to edit some contenido 
Javascript content tells me that variable is not defined, that's because the variable is defined in a separate place to what I'm editing and javascript receives orders from top to bottom, should I have to rename the variable or what do I do?

**Comment by AlexHGaming** [comment]
'contenido'?
I'm English.

**Comment by FantasyIsBae** [comment]
Right , this might be an issue with your editor .

**Comment by ZfsrGhS953** [comment]
@gyeyoqu Do you even know JS?

**Comment by ZfsrGhS953** [comment]
What variable are you trying to edit?

**Comment by Andrews54757** [comment]
This project is becomeing like OgarUL. 387 issues already. And a lot of them look like OgarUL issues.

**Comment by RelTakeover** [comment]
Try to edit something related to "x" variable,If that variable is too far from what I'm editing, it tells me that the variable is not defined, 
Should I define the variable again??

**Comment by gyeyoqu** [comment]
Try to edit something related to "x" variable,If that variable is too far from what I'm editing, it tells me that the variable is not defined,
Should I define the variable again??

**Comment by mrzack506** [comment]
@Andrews54757 Is that a joke? 2017 Quote of the year: "This project[**MultiOgar**-Edited] is becomeing like OgarUL", I'm still laughing as I am typing this.

**Comment by Gigabyte918** [comment]
haha
