### ISSUE TITLE
Mouse problem

### ISSUE THREAD

**Issue by naslit1** [Megabyte918/MultiOgar-Edited#436]
When i press play, my cell shrinks to the size of 1 mass although it is 44 mass, and starts moving to a random location. The same thing happened with minions.

**Comment by AlexHGaming** [comment]
> my cell shrinks to the size of 1 mass although it is 44 mass, 
Change the playerDecayRate to 0.002

> starts moving to a random location
This is because being 0-1 mass, it does that. Make sure, like I mentioned earlier, change the decay rate to 0.002.

**Comment by Megabyte918** [comment]
@naslit1 this was fixed a while ago, please use the latest version
