### ISSUE TITLE
is it possible ?

### ISSUE THREAD

**Issue by matrixreal** [Megabyte918/MultiOgar-Edited#438]
Hi,
is it possible to get this fork run server _ client like the old cigar ?
thank you

**Comment by Niall7459** [comment]
Do you still have the IOS edition of cigar??

**Comment by matrixreal** [comment]
yes i'm just updating it due to copyright issues that's all

**Comment by Niall7459** [comment]
Could I please have the source code if it is open source?? I would appreciate it much

**Comment by matrixreal** [comment]
sorry at this time it's not possible add me in skype matrix.real

**Comment by Megabyte918** [comment]
Yes, you can use this server with Cigar.

**Comment by matrixreal** [comment]
@Megabyte918 
i mean is it possible to run it server + client like old cigar ?
because as i can see there is no client side here

**Comment by Megabyte918** [comment]
@matrixreal You have to run the server, then connect to it through a client. As you said before, there is no client side here. So I cannot help you with client-sided issues.
