### ISSUE TITLE
What's the most players this could potentially support?

### ISSUE THREAD

**Issue by deniskrop** [Megabyte918/MultiOgar-Edited#439]
I understand Node.js is not multithreaded, so it's good for a prototype, but if someone were to scale it, how many players could this game potentially be optimized to support?

**Comment by MineMooreALT** [comment]
it would be best for 500 a server at MOST because players around 100+ needs a bigger map and soon the map will just get to big and your server will suck ass.

**Comment by Megabyte918** [comment]
I am not sure, I've never tried making MultiOgar multi-threaded haha. Nor do I have a'lot of people that join my server at once to test the performance. This fork of multiogar can run about 5000 minions (with default starting mass) with no lag, same with about 1000-2000 playerbots, so I'd say that this fork could run about 300+ players with default starting mass with no lag (that is before they start to get big). Which I think is enough, considering about 500+ players fills almost the entire map.

**Comment by Luka967** [comment]
If MultiOgar becomes multi-threaded (and is possible via child processes) you can probably get up to 1000 of them.
Assuming the forked process assembles packets sent from server and replies with digested client packets.
