### ISSUE TITLE
Kick bots

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#441]
when i added 40 bots and i have 30 minions then i run command `kickbot 10` then it removes some of my minions and bots too? it should need to kick only bots not minions?

**Comment by AlexHGaming** [comment]
I really want this too.
I want a command 'kickminion [amount]' so we can kick the amount of bots and the amount of minions.
This needs to be added! @Megabyte918

**Comment by freaky767** [comment]
nice name

**Comment by Gigabyte918** [comment]
haha

**Comment by Gigabyte918** [comment]
someone needs to be Kilobyte918 lmao XD

**Comment by ItzLevvie** [comment]
Hi mr. @Kilobyte918

**Comment by Kilobyte918** [comment]
how did you get my email?

**Comment by Kilobyte918** [comment]
OH SORRY I FORGOT THAT LMAO!

**Comment by Kilobyte918** [comment]
3 Version of @Megabyte918 LMAO!

**Comment by TeraByte918** [comment]
Hello From V4 :zap:

**Comment by freaky767** [comment]
Megabyte918 Gigabyte918 Kilobyte918 and Terabyte918 What is happening lol??

**Comment by Megabyte918** [comment]
haha these names look familiar
also @Gigabyte918 this has been fixed in recent updates to the "Update" branch, along with bots not being able to have minions, closing

**Comment by Kilobyte918** [comment]
We are Hard Disk Family!

**Comment by Kilobyte918** [comment]
@TeraByte918  Change your name to `Terabyte918` not TeraByte918

**Comment by Terabyte918** [comment]
@Kilobyte918 done

**Comment by Agarian** [comment]
.-.

**Comment by MastaCoder** [comment]
lmao

**Comment by Petabyte918** [comment]
im here lol :)
