### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#442]
i need permission from @Megabyte918 that can i edit the server thing to change and mke my changes by downloading and changing the server on my pc or i dont? not on internet but on localhost changing some thing like virus explosion and other popsplit?

**Comment by Gigabyte918** [comment]
I hope you will understand #RIP @PrinceDark9243

**Comment by Megabyte918** [comment]
I think the physics are good where they are @Gigabyte918, and I have some future updates that will improve them even better
