### ISSUE TITLE
Experimental virus crash server

### ISSUE THREAD

**Issue by markstoep** [Megabyte918/MultiOgar-Edited#443]
When you "shoot" the green virus into the red virus the server crashes.

This is the error: 

[FATAL] TypeError: Cannot read property 'cells' of null
    at Cell.Virus.onEaten (/src/entity/Virus.js:35:64)

See link for GIF:
https://gyazo.com/9f51255841a2e958e065c21c4f528da1

**Comment by Megabyte918** [comment]
Fixed, will merge changes later
