### ISSUE TITLE
new multiogar client

### ISSUE THREAD

**Issue by lotfis** [Megabyte918/MultiOgar-Edited#445]
Does anyone knows this client (http://agar.vuanamlun.net/)? And if ther is any english version of it?
It works whit MultiOgar but its buggy
If there is a better version pls share :)

**Comment by Luka967** [comment]
That's a server hosted in Vietnam. I guess MultiOgar 1.2.69 is backend. Why would you need a english version?
You have [c0nsume.me](c0nsume.me/tracker.php), [ogar.mivabe.nl](http://ogar.mivabe.nl/master) (also protocol 6 version [here](http://ogar.mivabe.nl/prot6/) and tons of other ones.

**Comment by lotfis** [comment]
@Luka967 I know!! but I dont like mivabe graphic style and consume dont support zoom_out neither ERT keys.
That one is realy interessting, and another reason I liked it cause it looks like this one (http://agarioplay.org/) which am realy fan!

**Comment by Megabyte918** [comment]
This is a client related issue, it does not relate to this project.

**Comment by lotfis** [comment]
@Megabyte918 FUCK YOU
