### ISSUE TITLE
Auto Restart With Reach Mass

### ISSUE THREAD

**Issue by kareemman00** [Megabyte918/MultiOgar-Edited#447]
Play Can U Tell Me How Make A Restart System like www.ftwin.io it restarts when some one in the server reach 80k mass but frist it change the board to [Auto Restart In 1 Min] Then It restart @Megabyte918

**Comment by Megabyte918** [comment]
@kareemman00 Something like what you are describing was already implemented [here](https://github.com/Megabyte918/MultiOgar-Edited/commit/cc11ac4c54b3d118732a93f6be02d823bcb2bb48), [here](https://github.com/Megabyte918/MultiOgar-Edited/commit/ad6d227b70843ff47dfe58e90203b4a5f6c8aa99), and [here](https://github.com/Megabyte918/MultiOgar-Edited/commit/391a9cb8a032fa7126cab58b4ef0d8b0a9066178), but was later removed. It doesn't restart the server, but kills the player. You can add back the code if you want, but I've already stated many times that an auto-restart system is not necessary

**Comment by kareemman00** [comment]
But What About The Board Change ?? @Megabyte918
