### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by ShRules** [Megabyte918/MultiOgar-Edited#448]
This server works, but there's some lag though. When i point to the right with my mouse it takes about a second to go right for the cell (I live in europe). It's just like when you are in an asian agario server, while you live in europe.

**Comment by Luka967** [comment]
It's surely something to do with the packet handler.

**Comment by ShRules** [comment]
What's the problem exactly?

**Comment by Luka967** [comment]
I have no idea.
Try moving [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L260) to run before everything else in the `process` function, it *might* do something

**Comment by AlexHGaming** [comment]
If you have wrote loads of new codes, this could make lag.
1. How big was everyone and what max cells were they?
2. What do you use to host the server?
3. Check internet download mbps?

**Comment by Luka967** [comment]
Even default servers give lag. Any server.

**Comment by ShRules** [comment]
1. I was alone on the server. It's not the bots, because even without bots it lags, the bots spawn with 132 mass. I myself start with 180 mass.
2.  Maybe this could be the problem, i use codeanywhere.com, that site itself is also laggy as hell.
3. Internet Mbps is fine just as Upload speed & ms.

**Comment by Tyler3D** [comment]
@ShRules Codeanywhere isn't a very good host

**Comment by Tyler3D** [comment]
Try using the server on your pc.

**Comment by Andrews54757** [comment]
@ShRules Get a better server. But multiogar-edited is also not very optimized. And @Luka967 is right that the packets are not very optimal.  The sizes of the packets should be precalculated, currently, it uses a dynamic buffer (https://github.com/Barbosik/MultiOgar/blob/master/src/packet/BinaryWriter.js). My system pre calculates the size and so is over twice as efficient. (https://github.com/AJS-development/OpenAgar/blob/master/source/modules/FastBuffers.js)

**Comment by Megabyte918** [comment]
@ShRules Use something other than codeanywhere to host. For me the server works just fine when hosting from my pc, I never experience any delay

**Comment by ShRules** [comment]
@Megabyte918 worked! But how can i use skins? I can only see other players their skins. When i use <cannonball> (for example) it doesn't work.

**Comment by Megabyte918** [comment]
@ShRules Miniclip has patched skins on private servers through their client months ago.

**Comment by Agarian** [comment]
Unfortunately
