### ISSUE TITLE
Extension for Minion to Control it" E " R " P (SPLIT , FEED < COLLECT PELLETMODE )

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#45]
That would be awesome if this project have a Script :)

**Comment by Tyler3D** [comment]
This is pointless because MultiOgar has support for other clients. And They can use E, R, P.

**Comment by NameYT** [comment]
But They can make an extension that can be linked with MultiOgar Minion :0

**Comment by Jhair2015** [comment]
No

**Comment by NameYT** [comment]
@Jhair2015 Yes They can @Fantasy-Agario Is making one :p

**Comment by Jhair2015** [comment]
@NameYT  Hahaha have to wait :v

**Comment by AlexandriteErikParacelsus** [comment]
@NameYT Lol no, when does he told you he gonna make one?
