### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by Niall7459** [Megabyte918/MultiOgar-Edited#452]
how does one add a minimap?

**Comment by Jhair2015** [comment]
@Niall7459 It is not possible to add minimap to agrarian client (vanilla), however you can do it on your own client.

**Comment by Niall7459** [comment]
I know i have my own client, do you have like the minimap.js or something.

**Comment by Niall7459** [comment]
![screen shot 2017-01-26 at 19 10 18](https://cloud.githubusercontent.com/assets/9781846/22346228/40f8b2b0-e3fb-11e6-851f-b9cb76feddad.png)

**Comment by Jhair2015** [comment]
![image](https://cloud.githubusercontent.com/assets/18153674/22346334/b664aeb6-e3d1-11e6-9eca-18b02c858f96.png)


like this?

**Comment by Niall7459** [comment]
yes please

**Comment by Niall7459** [comment]
I would love it loads if you could help me!

**Comment by Jhair2015** [comment]
Ok, but it has a defect, the client is hgk

You can try it here:

http://ultrafun.ga/

**Comment by Niall7459** [comment]
My current one always says Y = 0 and The map size is always incorrect

**Comment by Jhair2015** [comment]
Scramble level?

**Comment by Niall7459** [comment]
On your servers, only I show on the minimap.

**Comment by Niall7459** [comment]
Cannot see anyone else.

**Comment by Jhair2015** [comment]
That same I say, the minimap is of the extension HKG, it did not serve the minimap or the skins, I also look for solution for this, or should use another client ...

**Comment by AlexHGaming** [comment]
Pleasw close
This is to do with the client, not the project itself.

**Comment by Luka967** [comment]
It does kind of. Jara made a server-side packet which is a list of player cells in the server. http://ogar.mivabe.nl/prot6/

**Comment by Megabyte918** [comment]
@Niall7459 MultiOgar already has minimap support, you just need to add it to your client/extension/script, which is not sided with server

**Comment by Agarian** [comment]
It has minimap support? Then why is there a scramble level that scrambles minimaps? Contradictory if you ask me =\
