### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#453]

**Comment by Luka967** [comment]
What did you enter in the console?

**Comment by Tyler3D** [comment]
@RelTakeover This is a good mass command for playercommand.js

**Comment by Tyler3D** [comment]
`    mass: function (args) {
        if (this.playerTracker.userRole != UserRoleEnum.ADMIN && this.playerTracker != UserRoleEnum.MODER) {
            this.writeLine("ERROR: access denied!");
            return;
        }
        var mass = (args || "").trim();
        if (mass.length < 1) {
            this.writeLine("ERROR: missing mass argument!");
            return;
        }
        var size = Math.sqrt(mass * 100);
        for (var i in this.playerTracker.cells) {
        this.playerTracker.cells[i].setSize(size);
        }
        this.writeLine("Set mass of " + this.playerTracker._name + " to " + (size * size / 100).toFixed(3));

    },`

**Comment by Tyler3D** [comment]
http://pastebin.com/0Mjfw8Tk

**Comment by Tyler3D** [comment]
Try inserting that
