### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by naslit1** [Megabyte918/MultiOgar-Edited#456]
Is there a way to zoom out like ogario? I've tried many extensions but those doesnt seem to work.

**Comment by RelTakeover** [comment]
client sided.

**Comment by Luka967** [comment]
^
@Megabyte918 Close

**Comment by Jhair2015** [comment]
Use this video, is the OGARio for private servers, also teaches you how to see your friend on the minimap!


--- > https://www.youtube.com/watch?v=L82EMoQtLH0 <---

**Comment by Tyler3D** [comment]
Actually this is server side

**Comment by Tyler3D** [comment]
The server does not send the whole thus, the client cannot view the whole map. But doing this would cause extreme lag

**Comment by Tyler3D** [comment]
@Luka967 ohhhhhhhh ok
