### ISSUE TITLE
Please help me with callbacks

### ISSUE THREAD

**Issue by Niall7459** [Megabyte918/MultiOgar-Edited#457]
```
PlayerTracker.prototype.joinGame = function (name, skin) {

var AccountName = "Guest"
    this.gameServer.SQLconnection.query('SELECT * from tbl_users WHERE userID=' + name, function(err, rows) {
      if (!err) {
    	console.log("User " + rows[0].userName + " Joined the game (" + rows[0].coins + " Coins!)");
      }else{
        console.log('Error while performing Query.');
        accountName = rows[0].userName
      }
    });
    
    console.log(AccountName)<----- undefined




Please could anyone help me?

**Comment by Luka967** [comment]
```js
accountName = rows[0].userName
```
JS doesn't ignore cases.

```js
...
if (!err) {
    console.log(...);
} else {
    console.log('Error while performing Query.');
    accountName = rows[0].userName
}

...
```
You've put name assigning into the else clause, so it'll assign `undefined` every time the SQL query gets an error. So `accountName ` will always evaluate as either `undefined` or `"Guest"`.

**Comment by Niall7459** [comment]
Oh. Do you still have any idea here is my code in the IDE:

![screen shot 2017-01-27 at 12 17 29](https://cloud.githubusercontent.com/assets/9781846/22370703/a321d50e-e48a-11e6-8a32-741b98b72057.png)

**Comment by Niall7459** [comment]
Sorry i have written it wrong...

**Comment by Luka967** [comment]
Just change the query callback:
```js
this.gameServer.SQLconnection.query('SELECT * from tbl_users WHERE userID=' + name, function(err, rows) {
    if (!err) {
        accountName = rows[0].userName;
        console.log(...);
    } else {
        console.log('Error while performing query');
    }
});
```

**Comment by Niall7459** [comment]
and that will work?

**Comment by Luka967** [comment]
Should work, try it out

**Comment by Niall7459** [comment]
Ok

**Comment by Niall7459** [comment]
![screen shot 2017-01-27 at 12 22 38](https://cloud.githubusercontent.com/assets/9781846/22370819/55c2bd04-e48b-11e6-97d2-67b7b6022554.png)
It does not set it.
I can confirm that I have the userID right.

**Comment by Niall7459** [comment]
How does one use the callback function? Everything i looked up looked so confusing..

By the way, connection.query() is Async...

**Comment by Luka967** [comment]
Use the PlayerTracker then, 
```js
function PlayerTracker(...) {
    ...
    this.accountName = "Guest";
    ...
}

...

this.gameServer.SQLconnection.query('SELECT * from tbl_users WHERE userID=' + name, function(err, rows) {
    if (!err) {
        this.accountName = rows[0].userName;
        console.log(this.accountName + " has joined");
    } else {
        console.log("Error while performing query");
    }
});
```
if still doesn't work, turn into debug mode. Log everything - query string, query results and the error if any.

**Comment by Niall7459** [comment]
Tried before, did not work. becuase it sets "accountName" inside of query() not the PlayerTracker.
I might have found solution on the internets..

**Comment by Niall7459** [comment]
`connection.query('SELECT * FROM `books` WHERE `author` = "David"', function (error, results, fields) {
  // error will be an Error if one occurred during the query
  // results will contain the results of the query
  // fields will contain information about the returned results fields (if any)
});`

How can i get the "results" variable outside of this then?

**Comment by Niall7459** [comment]
![screen shot 2017-01-27 at 12 43 24](https://cloud.githubusercontent.com/assets/9781846/22371281/35622ee8-e48e-11e6-953f-d1c3ba59a4d5.png)
This one is clearer

**Comment by Megabyte918** [comment]
@Niall7459 Try making it global in PlayerTracker like Luka said, but define the `this` keyword using another variable outside of the function, because as far as I know you can't use the `this` keyword inside of any non-prototype functions. Example:

```js
function PlayerTracker(...) {
    ...
    this.accountName = "Guest";
    ...
}

...

PlayerTracker.prototype.something = function() {
    // Make sure the "self" variable and your query() function are already inside a prototype, or else "self" will return undefined!
    ...
    var self = this;
    this.gameServer.SQLconnection.query('SELECT * from tbl_users WHERE userID=' + name, function(err, rows) {
        if (!err) {
            self.accountName = rows[0].userName;
            console.log(self.accountName + " has joined");
        } else {
            console.log("Error while performing query");
        }
    });
    ...
}
```
Also this has nothing to do with the development of this project, so I am closing.

**Comment by Luka967** [comment]
damnit I've forgot for `this` binding xD

**Comment by MastaCoder** [comment]
You can't request the accountName outside of the query. The rest of the code will continue while the query is running, since MySQL connections take time. So you're technically requesting an undefined variable while the game is connecting.

**Comment by Niall7459** [comment]
And using the My SQL Query synchronically would be a bad idea.
I guess it would freeze the game a bit.

Could I use self.setName(AccountName) Inside of the query block. Although the player has to split or you dont really get the name change.

Is there anyway I can properly change the name of a cell?

**Comment by Niall7459** [comment]
I will give Megabytes suggestion ago

**Comment by Niall7459** [comment]
@Megabyte918 Thanks alot! It works!

However it would be nice to actually change the users name, not like wait for the player to split to see their account name: etc:
![screen shot 2017-01-28 at 08 40 24](https://cloud.githubusercontent.com/assets/9781846/22395405/92453996-e535-11e6-995c-c51391d8f335.png)

**Comment by Niall7459** [comment]
IT WORKS IT WORKS I GOT IT WORKING TAHNKS SO MUCH!!!!


I GOT SPEED AND MASS MULTIPLIERS CONNECTING TO THE DATABASE!!!!!

**Comment by FantasyIsBae** [comment]
@Niall7459 Maybe make the server auto set the name (Suggestion) :)

**Comment by Luka967** [comment]
*Client. Client queries for name and sets it.

**Comment by FantasyIsBae** [comment]
Sorry I misunderstood , my fault 😄

**Comment by FantasyIsBae** [comment]
And congrats on getting the system to work :)

**Comment by Niall7459** [comment]
What happens is:

On client side:
If user logged in: setNick($_user_identification);

On server:
If $user_identification is in the database: set there user name.

**Comment by MastaCoder** [comment]
I hope you're not sending client information non-encrypted through ws :)
