### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by CalvinDKHD** [Megabyte918/MultiOgar-Edited#459]
Hello!
So i have a suggestion, when you add minions to someone then you should be able to add a timer.
Like so - `minion <id> <amount>/<how long>`
and if you dont set it, then the bots are on for an infinite amount of time.

**Comment by AlexHGaming** [comment]
good idea

**Comment by Megabyte918** [comment]
Sounds pretty pointless to me, you can just be the timer yourself lol
Also why would you want to give a player minions but ONLY for a limited amount of time? That doesn't seem fun :/

**Comment by AlexandriteErikParacelsus** [comment]
^^

**Comment by NiesamoWhite** [comment]
I want this idea too please @Magabyte918

**Comment by naslit1** [comment]
@Megabyte918 Can there be an option to remove minions instead of bots? The command kickbot removes both bots and minions .

**Comment by raphyjb** [comment]
He wants that so he can sell bots for a number of time, I dont think they support that tho.

**Comment by Megabyte918** [comment]
@CalvinDKHD You can just set a timeout for a players minion control.

**Comment by Agarian** [comment]
Doesn't `kickall` kicks players too? IDK about it cause i never actually used it, but just curious.

**Comment by AlexandriteErikParacelsus** [comment]
@Megabyte918 Instead of doing `killall` use `minion [id of the ppl that want to removes minions]`

**Comment by AlexandriteErikParacelsus** [comment]
simple as 123

**Comment by AlexandriteErikParacelsus** [comment]
@Megabyte918 Do you want me to close this issue?

**Comment by Megabyte918** [comment]
@CalvinDKHD You can add a time limit parameter for the minion command by adding the following code:

Add the following variable into PlayerTracker.js:
```js
function PlayerTracker(gameServer, socket) {
    ...
    this.minionTime = null;
    ...
}
```

Add the following variables into the top of the minion command in CommandList:
```js
...
var time = parseInt(split[4]);
...
```

Then under `client.minionControl = true;`, add this:

```js
client.minionTime = time;
```

Then finally add this code into the `checkConnection` function in MinionPlayer.js:
```js
...
// remove minions after time limit (if any)
if (this.owner.minionTime != null) {
    var self = this;
    setTimeout(function() {
        self.owner.minionControl = false;
    }, this.owner.minionTime)
}
...
```
