### ISSUE TITLE
how to ?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#461]
What should I put in ip, to give rank "user" to all players?

**Comment by Tyler3D** [comment]
@gyeyoqu That doesn't really matter cause the user rank doesn't do anything special only admin and mod have special properties

**Comment by Tyler3D** [comment]
But if you insisit
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L84
Change "GUEST" to "USER"

**Comment by Megabyte918** [comment]
@gyeyoqu https://github.com/Megabyte918/MultiOgar-Edited/issues/48 should answer your question
