### ISSUE TITLE
Where can i run this for free?

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#462]
I saw some places where i could run a server, but where can i run it 24/7 without closing it when i close its tab?
Ive bin using Codeanywhere.com but closes server after abit...
Any other site i can try?

**Comment by Megabyte918** [comment]
It's best to port forward and just use your computer.

**Comment by FantasyIsBae** [comment]
@raphyjb ^^^

Tbh i use CodeAnywhere cos i have no idea how to port forward 😆

**Comment by AlexHGaming** [comment]
@FantasyIsBae Same :d

**Comment by Luka967** [comment]
Well I use my computer
*hackerman*

**Comment by Megabyte918** [comment]
*starts server*
**Hacker voice** *I'm in!*

**Comment by Luka967** [comment]
xD

**Comment by FantasyIsBae** [comment]
😄

**Comment by Agarian** [comment]
lool

**Comment by raphyjb** [comment]
XD dont do like i did .-.
Cmon gimmi some web sites @Megabyte918 u dont want ur users to get hacked dont u?
lol
