### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#463]
I want to allow a certain ip to only use a selected skin

Do not say that it is client-sided, because what corresponds to ip is completely backend.

**Comment by FantasyIsBae** [comment]
Its client sided ![Place Meme Here](https://avatars0.githubusercontent.com/u/21162678?v=3&u=96b54784f1182fe1205503fe90367fb77881fd8f&s=400)

**Comment by FantasyIsBae** [comment]
**place meme here**

**Comment by gyeyoqu** [comment]
place your ban here

**Comment by Terabyte918** [comment]
**meme.jpg**

**Comment by Agarian** [comment]
k

**Comment by Luka967** [comment]
![wetweryzseriogh](https://cloud.githubusercontent.com/assets/15956695/22400554/72b393c4-e5b8-11e6-852a-335e5d058480.JPG)

**Comment by Luka967** [comment]
![shyerthsjsdj](https://cloud.githubusercontent.com/assets/15956695/22400555/7c4e12ec-e5b8-11e6-9b9d-ce5662727b1b.JPG)

**Comment by Luka967** [comment]
Before
After

**Comment by FantasyIsBae** [comment]
Wow , much magik 🐕 <== Doge

**Comment by gyeyoqu** [comment]
Humility is left over.

**Comment by Megabyte918** [comment]
@gyeyoqu (In PacketHandler under `setNickname` function) You can add a check for bad words within the brackets of skin names, like this:
```js
if (this.gameServer.checkBadWord(inner)) { 
    // Checks to see if there is a bad word in between skin name brackets (<badword>)
    skin = null;
    name = "Hi there!";
}
```

Add the skin you don't want people to use into /src/badwords.txt. Make sure you add it as just the word itself and not in between brackets.

Then you can add a check for the player's ip, like this:
```js
// If the players ip is not the ip you entered below, check their skin name for bad words.
if (this.socket.playerTracker.remoteAddress != "insert ip here") { // keep quotes around ip
    if (this.gameServer.checkBadWord(inner)) { 
        skin = null;
        name = "Hi there!";
    }
}
```

**Comment by Agarian** [comment]
^^

**Comment by gyeyoqu** [comment]
@megabyte 
And how can I do with more than one ip? And each ip with different skin?

**Comment by gyeyoqu** [comment]
@Megabyte918

**Comment by MastaCoder** [comment]
@gyeyoqu very very easy way of adding it would just be:

```javascript
if (this.socket.playerTracker.remoteAddress != "insert ip here") { // keep quotes around ip
    if (this.gameServer.checkBadWord(inner)) { 
        skin = null;
        name = "Hi there!";
    }
} else if (this.socket.playerTracker.remoteAddress != "insert ip here") { // keep quotes around ip
    if (this.gameServer.checkBadWord(inner)) { 
        skin = null;
        name = "Hi there!";
    }
```

And keep going and going. You can also use || for or so that you can do 2 ip's on 1 line.

**Comment by gyeyoqu** [comment]
@MastaCoder  and each skin for each ip?

**Comment by Luka967** [comment]
```js
if (this.socket.playerTracker.remoteAddress != "insert ip here") { // keep quotes around ip
    if (this.gameServer.checkBadWord(inner)) { 
        skin = null;
        name = "Hi there!";
    }
} else if (this.socket.playerTracker.remoteAddress != "ip 1") { // keep quotes around ip
    skin = "skin 1"
else if (this.socket.playerTracker.remoteAddress != "ip 2") { // keep quotes around ip
    skin = "skin 2"
...
```

**Comment by gyeyoqu** [comment]
@Luka967  i should put {} ? i use your client.

**Comment by Luka967** [comment]
not required
