### ISSUE TITLE
emoticon

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#468]
I would like to be able to put any emoticon in the game and in the chat, and that comes out with its color

**Comment by Megabyte918** [comment]
This is partially client sided isn't it?

**Comment by Agarian** [comment]
Yes

**Comment by Jhair2015** [comment]
U hace Windows 10 or fonts updated?

**Comment by MastaCoder** [comment]
Can't you just use the basic alt emoticons? (☺)

**Comment by Luka967** [comment]
Alt emoticons are ready out of the box and are easy to process through.
