### ISSUE TITLE
Where is Length defined?

### ISSUE THREAD

**Issue by CalvinDKHD** [Megabyte918/MultiOgar-Edited#469]
Hello!
So i am having this error
https://gyazo.com/f152ff48c6458d0bb9fc5d1ea633d1eb

Which happens because length is not defined anywhere

**Comment by Agarian** [comment]
?

**Comment by CalvinDKHD** [comment]
There, just edited it.

**Comment by Agarian** [comment]
ChatCommands never actually worked =\

**Comment by CalvinDKHD** [comment]
well shit....

**Comment by CalvinDKHD** [comment]
Can i go back versions in multiogar, because i need version 1.4.2's playercommands

**Comment by ItzLevvie** [comment]
@CalvinDKHD https://github.com/Megabyte918/MultiOgar-Edited/blob/fd94027fddeb1dfa1362529b921c68685128ee8f/src/modules/PlayerCommand.js

**Comment by Luka967** [comment]
You could've just added the first 7 characters of the commit, no need for links

**Comment by ItzLevvie** [comment]
![image](https://cloud.githubusercontent.com/assets/11600822/22434089/93cbccd8-e712-11e6-8c5e-8fa0d8f9618e.png)

Lol?

**Comment by CalvinDKHD** [comment]
my issue basically is, when you type /login it crashes the server.
And that is because length is not defined.

**Comment by Luka967** [comment]
@ItzLevvie wat xD

**Comment by CalvinDKHD** [comment]
@Luka967 GHost edited his post, Levvie didnt do it.

**Comment by Megabyte918** [comment]
Fixed, just a typo
