### ISSUE TITLE
How to change cell collision delay ?

### ISSUE THREAD

**Issue by GhostShot3** [Megabyte918/MultiOgar-Edited#473]
title

**Comment by Megabyte918** [comment]
@GhostShot3 You can find and change the values [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L751), the "1" is the speed of collision restoration for mobile physics, and "13" is for default physics.

It is also recommended you change the values [In this location as well](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L800) to correspond with the same value of normal collision restoration as to not cause accidental remerge when player cells are in boosted mode.
