### ISSUE TITLE
Happen after update..

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#474]
![gif](https://cloud.githubusercontent.com/assets/19422415/22509326/33cff2aa-e8c0-11e6-8676-4a2bcb5b4a21.gif)

**Comment by NuclearC** [comment]
probs cuz of your client

**Comment by Luka967** [comment]
Is a possibility.
@RasyiidWho Check the server log.

**Comment by RasyiidWho** [comment]
Lol XD

> [NONE ][20:51:57] CONNECTED    127.0.0.1:62431, origin: "http://127.0.0.1"
[NONE ][20:51:57] DISCONNECTED 127.0.0.1:62431, code: 1000, reason: "isMinion", name: " "
[NONE ][20:51:57] CONNECTED    127.0.0.1:62432, origin: "http://127.0.0.1"
[NONE ][20:51:58] DISCONNECTED 127.0.0.1:62432, code: 1000, reason: "isMinion", name: " "
[NONE ][20:51:58] CONNECTED    127.0.0.1:62433, origin: "http://127.0.0.1"
[NONE ][20:51:58] DISCONNECTED 127.0.0.1:62433, code: 1000, reason: "isMinion", name: " "
[NONE ][20:51:59] CONNECTED    127.0.0.1:62434, origin: "http://127.0.0.1"
[NONE ][20:51:59] DISCONNECTED 127.0.0.1:62434, code: 1000, reason: "isMinion", name: " "
[NONE ][20:51:59] CONNECTED    127.0.0.1:62435, origin: "http://127.0.0.1"
[NONE ][20:51:59] DISCONNECTED 127.0.0.1:62435, code: 1000, reason: "isMinion", name: " "
[NONE ][20:52:00] CONNECTED    127.0.0.1:62436, origin: "http://127.0.0.1"
[NONE ][20:52:00] DISCONNECTED 127.0.0.1:62436, code: 1000, reason: "isMinion", name: " "
[NONE ][20:52:00] CONNECTED    127.0.0.1:62437, origin: "http://127.0.0.1"
[NONE ][20:52:00] DISCONNECTED 127.0.0.1:62437, code: 1000, reason: "isMinion", name: " "
[NONE ][20:52:01] CONNECTED    127.0.0.1:62438, origin: "http://127.0.0.1"
[NONE ][20:52:01] DISCONNECTED 127.0.0.1:62438, code: 1000, reason: "isMinion", name: " "

**Comment by Luka967** [comment]
xD

**Comment by RasyiidWho** [comment]
Minion.. -.-

**Comment by MastaCoder** [comment]
Disable minion check maybe?

**Comment by RasyiidWho** [comment]
Work after delete [this ](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L927-L931) line.

**Comment by Luka967** [comment]
Why was that even added in the first place?

**Comment by RasyiidWho** [comment]
I just delete minion check, and work for now XD

**Comment by MastaCoder** [comment]
@Luka967 Isn't it for the minion protection system?

**Comment by RasyiidWho** [comment]
I just play it local, XD

**Comment by Luka967** [comment]
It kicks players that are found to be minions, never saw that piece of code.
