### ISSUE TITLE
Longest spectator

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#475]
Can you help me perform a longer player viewer mode like dual agar?

That the viewer was as if he had 2 distant cells

The server believed, that I have 2 distant cells

how to?

**Comment by Luka967** [comment]
dual-agar servers literally have two clients as one. Making a dual-agar-like server requires a lot of PlayerTracker.js editing.

**Comment by Megabyte918** [comment]
@gyeyoqu You can increase the viewbase of players in gameserver.ini if that's what your looking for.
