### ISSUE TITLE
Recombining instantly after setting higher value.

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#476]
In the gameserver.js, when I edit something, it bugs.
var r = (this.config.mobilePhysics) ? 1 : `13;`
When setting the `13` to a higher value, it recombines after the delay. Happens the most when linesplitting.

**Comment by Luka967** [comment]
[This](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L800) line needs to be changed too.

**Comment by AlexHGaming** [comment]
Oh thanks thanks
