### ISSUE TITLE
Help me plz :)

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#477]
> Which means that these numbers/Commands?

[Virus.js](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js)
        var exp = Math.random() * (**_4.5_** - **_3.33_**) + _**3.33**;_ 
        while (threshold / exp > **_24_**) {
            threshold /= exp;
            exp = **_2_**;
            big.push(threshold >> **_0_**);

How to make on the basis of these teams, the division of the virus in gota.io?

> Correction, discarding the standard food of 13, and the loss of 18:
```
ejectSize = 37
ejectSizeLoss = 43
```

> And one last wish where can find all the settings splits:

For example like this to write:
FROM- ....
...
...
Before....

**Comment by Agarian** [comment]
For the config, you can use `massToSize(#)`
So for `ejectSize`, replace 37 with `massToSize(13)`
And for `ejectSizeLoss`, replace 43 with `massToSize(18)`

**Comment by DeadLord1337** [comment]
@Agarian @Megabyte918  I wrote that... -_- just change this value in [gameserver.ini](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L126-L127)

**Comment by Agarian** [comment]
Wait are you using the `updates` branch? Cause i've noticed a bug where the server doesn't pull config from `gameserver.ini`

**Comment by DeadLord1337** [comment]
@Agarian Yes, change this value in the next update :)

**Comment by AlexHGaming** [comment]
Please refer to #370

**Comment by AlexHGaming** [comment]
And if you want to see what all of that means, look at the bottom of #332

**Comment by Megabyte918** [comment]
^^

**Comment by DeadLord1337** [comment]
@AlexHGaming New code...... -__-  + there is the old code as a new differently ... with the new code there all sort out

**Comment by DeadLord1337** [comment]
in the new code it's different... and you give me the old ...

**Comment by Megabyte918** [comment]
The values you need to edit are still there, just changed slightly
