### ISSUE TITLE
Gota.io linesplits on a wall

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#478]
Normally in gota, when splitting on the wall, instead of bouncing back at you, it stays on the wall and brings the cell up. (What I am trying to say is when splitting 16 on a wall, it will do a vertical linesplit) How can I implement this feature into MultiOgar as I would love this feature!
@Megabyte918

**Comment by Agarian** [comment]
This, like gravitational pushsplits is a bug

**Comment by Megabyte918** [comment]
@AlexHGaming @Agarian You can get rid of cells bouncing off of the border by removing these lines:
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L651-L656

**Comment by AlexHGaming** [comment]
This didn't work, and it generated a lot of lag.

**Comment by Megabyte918** [comment]
@AlexHGaming That is the only code for bouncing off of the border, if you have removed that code and nothing else it should not bounce anymore and not touch performance. Just tested it myself and it worked.

**Comment by AlexHGaming** [comment]
It didn't bounce, but I wanted a linesplit going up.
If you have no idea what I mean, go to a gota server, split on a wall 16 times.
@Megabyte918

**Comment by Megabyte918** [comment]
@AlexHGaming It is an issue with rigid body collision resolution. If you max split against a wall each of your cells will extrude off of each other in random directions.

**Comment by AlexHGaming** [comment]
@Megabyte918 Do you know how to fix this?

**Comment by Megabyte918** [comment]
@AlexHGaming You can kindof get the same border behavior as on Gota.io by replacing the `checkBorder` function in your Cell.js with this one:
```js
Cell.prototype.checkBorder = function (b) {
    var r = this._size / 2;
    if (this.position.x < b.minx + r || this.position.x > b.maxx - r) {
        this.boostDirection.x = this.position.x;
        this.position.x = Math.max(this.position.x, b.minx + r);
        this.position.x = Math.min(this.position.x, b.maxx - r);
    }
    if (this.position.y < b.miny + r || this.position.y > b.maxy - r) {
        this.boostDirection.y = this.position.y;
        this.position.y = Math.max(this.position.y, b.miny + r);
        this.position.y = Math.min(this.position.y, b.maxy - r);
    }
};
```
Make sure you already have the border-bouncing code removed in GameServer.
