### ISSUE TITLE
what i should use?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#479]
i think quadtree is better because 
Quadtree handles objects of different size faster than spatial hash

**Comment by Agarian** [comment]
Spatial hash is better at handling a large number of objects than Quadtree

**Comment by Megabyte918** [comment]
@Agarian That is if it is implemented in the correct way, @gyeyoqu I suggest you stick with the QuadTree for now, because no spatial hashing exists for this project xd

**Comment by Luka967** [comment]
He's probably asking for my fork since I have a spatial hash there xd
