### ISSUE TITLE
Question about Player connected messages and User Roles

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#48]
1st thank you for the update and the edits, really good stuff. 
Can the Player connected message be turned off? I ask because my servers get really busy, I reach max constantly and no lag, incredible. It's hard to issue command from console when the Player connected messages keep coming in. 
Also, are user roles working? if so, would passing the command from chat like using /rcon work?

**Comment by AlexandriteErikParacelsus** [comment]
@megabyte918

**Comment by Fantasy-Agario** [comment]
@cowpits I'll make an option in gameserver.ini :)

**Comment by Megabyte918** [comment]
@cowpits yes it can be turned off, just remove this line in GameServer.js: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L252
and I have no idea how user roles work, ive never used them myself nor know do i know how to use it :/

**Comment by NameYT** [comment]
@Megabyte918 Updated fix:1.) Add this small fix into GameServer.js (thx @NatsuTheGreat) from this commit here: 6b23cea2.) Change the size multiplier located here, change the "1.15" to "1.10"3.) Edit the splitMass variable for virus explosions here, change the "2" to "2.5".4.) Change the first value of the normalized distance, change "32" here, to "64"5.) Change the playerSpeed value in config.ini to "0.5" (so it balances out the speed with the normalized distance)And there you have it! Works with any speed, same size any mass, double, triple, quadruple, double same size, triple same size, quadruple same size, long distance, extremely long distance, long distance same size, you name it, all with vanilla success rate . Also fixes cells flying through other cells, and the rate of which the cells switch order when doublesplitting to vanilla aswell.Here's some of the ones I did:popsplit1popsplit2popsplit3Let me know if it works for you! tthis is what im talking about :0 the popsplit u said always success

**Comment by AlexandriteErikParacelsus** [comment]
^ sorry what??

**Comment by Megabyte918** [comment]
@NameYT you dont need to do that anymore.. this isnt original multiogar, all you need to do is said in #10

**Comment by NatsuTheGreat** [comment]
@NameYT No probs.

**Comment by NameYT** [comment]
@Megabyte918 I still dont get popsplit always fail lol

**Comment by cowpits** [comment]
@Megabyte918 thank you for the fix. Much better now.

**Comment by cowpits** [comment]
@Fantasy-Agario a gameserver.ini option would also be great for the next release if you wish. Thanks.

**Comment by cowpits** [comment]
@Megabyte918, forgot no worries about userRoles, it's not a big deal most people use the agar.io client anyway I wouldnt be able to pass console commands from there, but the c0nsume client is awesome and if it's possible then it'll be a great feature.

**Comment by Megabyte918** [comment]
@cowpits Ive tested it out, you have to input IP in userroles.json as any user you want to be, then if there is a chat on the client your using you can do /command to run commands. if the client has a login/logout system you can use /login or /logout or stuff like that.
