### ISSUE TITLE
Full memory usage

### ISSUE THREAD

**Issue by JoeryDroppers** [Megabyte918/MultiOgar-Edited#480]
Hello,

I was trying the source from the updates branch, and got full memory usage.

![yes](http://i.imgur.com/EPZcTyH.png)

Or is this a known issue?

Happens when I eat someone at 10k mass.

**Comment by Luka967** [comment]
Did the process get terminated for memory allocation failure?

**Comment by JoeryDroppers** [comment]
Seems like the update branch does not work anymore for older node.js versions.

The master branch works just fine at node 4.6.0.

**Comment by Luka967** [comment]
Hmm, how old that node version was?

**Comment by ItzLevvie** [comment]
```master``` and ```Update``` branch works fine for me on Node 4, 5, 6, 7 and 8-NIGHTLY

**Comment by Megabyte918** [comment]
Same here ^^

**Comment by JoeryDroppers** [comment]
@Megabyte918

It works just fine after installing `ws` again, ignore this issue.

**Comment by Luka967** [comment]
Maybe because they stopped using `options` module?
