### ISSUE TITLE
How To Invite friends to my private server

### ISSUE THREAD

**Issue by MRNOOB54** [Megabyte918/MultiOgar-Edited#481]
how do i invite people to my server on agar.io(not Alis.io,astr.io,ect

**Comment by MastaCoder** [comment]
Just send them a link with agar.io/?ip=yourip

**Comment by MRNOOB54** [comment]
From OgarTracker?

**Comment by MastaCoder** [comment]
You can use the link from OgarTracker, sure. But Agar.io would work as well.

If you need to port forward, google some port forwarding guides for your router.

**Comment by MRNOOB54** [comment]
The problem is that every time i load on ogar tracker it just gives me an error i.e "Connection timed out"

**Comment by Luka967** [comment]
OgarTracker is dead.
c0nsume.me doesn't want to display higher versions of MultiOgar.
The only tracker left working is ogar.mivabe.nl/master.
