### ISSUE TITLE
Hilarious "bug" feeding :D

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#483]
How to feed himself so that all the food is gone in 1 ball? without changing commands **ejectSize** , **ejectSizeLoss** and **playerMaxCells** (without increasing the value of these command)
[**Example 1**](https://www.youtube.com/watch?v=eleZ2zPvk2E&t=15s)
[**Example 2**](https://www.youtube.com/watch?v=diK1YdOxXy8&t=285s)

**Comment by ZfsrGhS953** [comment]
That's self-feeding, it's not a bug. Example 1 has 500 cells, which is why the cell gets fed so fast.

**Comment by Megabyte918** [comment]
Yes, you need to center your mouse on the piece you would like to feed while splitting and ejecting at the same time so something like that could happen, but it might not work correctly due to cells switching order on multi split
