### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#484]
how to change the camera to make it in gota.io 
Well, as I understand ... it is necessary to change the camera speed, gota.io it sharper / fast

**Comment by MastaCoder** [comment]
That would be mostly client sided.

**Comment by Jhair2015** [comment]
Vainilla client or own client.

**Comment by Megabyte918** [comment]
Yes it is client sided I'm afraid, however you can achieve this if you can find an extension or script that allows for extra zoom, then tweak the viewbases for a player in gameserver.ini to fit your needs.
