### ISSUE TITLE
 *Nothing to do with the MO-E* I get disconnected from real Agar.io server after a while

### ISSUE THREAD

**Issue by ARBCells** [Megabyte918/MultiOgar-Edited#485]
As the title says... Idk the cause. Very annoying to be disconnected in the middle of a game or when I become massive..

**Comment by Luka967** [comment]
Welcome to Moneyshit's Agar.io.

**Comment by MastaCoder** [comment]
Why are you posting it in the MultiOgar-Edited repo if you know it has nothing to do with it lol.

**Comment by Megabyte918** [comment]
This is a client related issue.
