### ISSUE TITLE
error codeanywhere

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#488]
please can help me with this error  thanks! :+1: 

https://s24.postimg.org/im1scdegj/qweqweqweqwe.png

**Comment by JoeryDroppers** [comment]
Upgrade your node.js version or use an older version of the `ws` module.

**Comment by imnotNxhz1** [comment]
how do it?

**Comment by imnotNxhz1** [comment]
i think have this version of node v0.10.25      but idk how to update  from codeanywhere

**Comment by MastaCoder** [comment]
Don't use Codeanywhere to host a gameserver, it's too slow and it's not allowed (pretty sure).

**Comment by imnotNxhz1** [comment]
It's my only option,, i can´t open ports to play with friends

**Comment by imnotNxhz1** [comment]
i fix this  with a old carpet of node modules

**Comment by AlexHGaming** [comment]
Re-do your server and when opening a container at the start, pick the 14.04 version.
Then do:
`sudo apt-get install nodejs-legacy npm`

**Comment by AlexandriteErikParacelsus** [comment]
closing
