### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#489]
Make it dual-agar.online when you have 1 bot, but thats you so if one of you die, ur the other bot.. thats really cool!
Also could u make a website that could look like dual?
Ty for answering :P

**Comment by Gigabyte918** [comment]
I think it isnt possible in view of my Point but wait for @Megabyte918 Respond.

**Comment by AlexHGaming** [comment]
Raphy, for this to be possible you have to mess about with the camera angle on new lines you need to make. Just give yourself 1 minion.
To make him spawn next to you, I swear someone already make an issue about it

**Comment by Luka967** [comment]
Multiboxing with a bot? Totally possible. It'd be better to use a gamemode for it.

**Comment by Megabyte918** [comment]
Sounds good to me

**Comment by Gigabyte918** [comment]
i think it is not possible but @Megabyte918  Agreed/

**Comment by Megabyte918** [comment]
Rethinking this, I don't think it is possible. 
I don't think it is possible to "transfer ownership" to one client or another. (atleast server sided anyway)
And especially because minions do not have visible node calculations, coordinates, or scores.

**Comment by Tyler3D** [comment]
@Megabyte918 How about tp and then kill/kick the second client.

**Comment by AlexHGaming** [comment]
You can try and triggering a new command:
`minion``DA` `[ID] [skinname] [name]'
When using this command it forces out 1 minion, changing camera angle of each cell and using E to split whatever cell is NOT being controlled.

**Comment by Megabyte918** [comment]
@Tyler3D Then you would lose all of your mass lol
And if I were to set the size after tp and kill, it would not be balanced. 
Example: Your minion pops on a virus and one of it's pieces kills you, your minion then gets killed and you spawn on top of where it once was at the same size, you then end up in one piece again when you should still be popped into many pieces like your minion was before it was killed

@AlexHGaming Remeber: minions do not have visible node calculations, which means they have no camera.

**Comment by MastaCoder** [comment]
Damn nice new profile photo haha @Megabyte918

**Comment by Megabyte918** [comment]
Thanx xD

**Comment by AlexandriteErikParacelsus** [comment]
Ooooo my man is getting sexy

**Comment by Luka967** [comment]
meh

**Comment by AlexandriteErikParacelsus** [comment]
no

**Comment by Luka967** [comment]
yis

**Comment by Agarian** [comment]
k

**Comment by Luka967** [comment]
h

**Comment by Luka967** [comment]
kh... khaledon?

**Comment by raphyjb** [comment]
Im not sure Dual did it, But if it could be possible to spawn 1 bot at a time by pressing a button and that bot you can control by pressing example TAB like they did.. And also you can spectate where u want to spawn, and spawn at the area spectating.. Also something interesting! Maybe try do exact copy of them? haha

**Comment by Megabyte918** [comment]
@raphyjb You can achieve this by adding said key to PacketHandler, and the ERTP control script (or whatever you use), then when that key is pressed add 1 minion. And for spawning: You can achieve this by storing the center position of the clients viewbox, then when they press a certain key it stores that position for regular spawn.
Closing this because the original post is not possible.
