### ISSUE TITLE
What is love?

### ISSUE THREAD

**Issue by AlexandriteErikParacelsus** [Megabyte918/MultiOgar-Edited#49]
@NameYT stop making dunplicated issues about pellet mode and extension for bots, I'm tired of it. Baby don't hurt me don't hurt me no more.

**Comment by XtremePlayzCODE** [comment]
Well you already did the "Baby don't hurt me" so I have nothing to do now. Stupid brain that dosen't know the rest of the lyrics!

**Comment by AlexandriteErikParacelsus** [comment]
@Xtreme why df should I write the whole physics out lmao

**Comment by AlexandriteErikParacelsus** [comment]
Go back to your fucking minecraft game you goat fucker

**Comment by AlexandriteErikParacelsus** [comment]
I don't even fucking say anything you, I could block you from this prject if I need to you 12 years old

**Comment by AlexandriteErikParacelsus** [comment]
Fucking dirty wanker, jerking of in the corner when watching minecraft porn

**Comment by Fantasy-Agario** [comment]
@AlexandriteErikParacelsus Stop

**Comment by XtremePlayzCODE** [comment]
What did I do?

**Comment by XtremePlayzCODE** [comment]
All I said was that you already put "baby don't hurt me" and that I did not know the rest of the lyrics.

**Comment by Jhair2015** [comment]
LOL

**Comment by AlexandriteErikParacelsus** [comment]
Sorry his grammar wasn't clear, I didn't quite understand him. @Fantasy-Agario

**Comment by Fantasy-Agario** [comment]
Yeah its alright , just don't get triggered XD

**Comment by Fantasy-Agario** [comment]
@AlexandriteErikParacelsus

**Comment by XtremePlayzCODE** [comment]
XD Yes sometimes my grammar clear isn't.

**Comment by Fantasy-Agario** [comment]
Like now ? XD @XtremePlayzCODE LOL

**Comment by XtremePlayzCODE** [comment]
That was 100% intentional. Seriously.

P.S. I really wanna play a private server, wanna team or r u busy

**Comment by Fantasy-Agario** [comment]
Yeah ok, i'm busy atm , but I'll play :)

P.S This is what Im working on : https://github.com/FantasyArts/ConsoleChat

**Comment by XtremePlayzCODE** [comment]
Ok

**Comment by XtremePlayzCODE** [comment]
Come say when you have some time back here, I'll work on my own project

**Comment by Fantasy-Agario** [comment]
I have time now , 

if u like i can help , what's your project anyways ?

**Comment by XtremePlayzCODE** [comment]
Xenirus.Runtime, a copy of the C# runtime

**Comment by XtremePlayzCODE** [comment]
but don't worry, it's easy

**Comment by XtremePlayzCODE** [comment]
I can teach you how to do what I am doing

**Comment by Fantasy-Agario** [comment]
Yeah ok , why not :)

Do u have discord or skype ?

**Comment by XtremePlayzCODE** [comment]
disscord

**Comment by XtremePlayzCODE** [comment]
but no mic

**Comment by Fantasy-Agario** [comment]
yh same here :)

**Comment by XtremePlayzCODE** [comment]
lol

**Comment by XtremePlayzCODE** [comment]
invite me to a chat

**Comment by Fantasy-Agario** [comment]
kk just w8 a sec :p

**Comment by Fantasy-Agario** [comment]
I messaged u :)

**Comment by XtremePlayzCODE** [comment]
??

**Comment by XtremePlayzCODE** [comment]
on what?

**Comment by Fantasy-Agario** [comment]
discord :)

**Comment by XtremePlayzCODE** [comment]
o

**Comment by Fantasy-Agario** [comment]
XD

**Comment by XtremePlayzCODE** [comment]
im on disstrackcord
