### ISSUE TITLE
What does this mean in virus.js?

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#491]
`big.push(threshold >> 0);`
What does that line mean?

**Comment by AlexHGaming** [comment]
I know it's something to do with the pushing but what does the 0 represent?

**Comment by Luka967** [comment]
`>> 0` truncates the number.

**Comment by AlexHGaming** [comment]
truncates the number of what?

**Comment by ItzLevvie** [comment]
for exploding cells

**Comment by ItzLevvie** [comment]
of threshold (https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js#L36)

**Comment by AlexHGaming** [comment]
What's threshold?

**Comment by ItzLevvie** [comment]
https://github.com/ItzLevvie/MultiOgar-Edited/blob/master/src/entity/Virus.js#L38
