### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by leboloss18k** [Megabyte918/MultiOgar-Edited#492]
HELLO ALL 

I PLAY WITH MY FRIEND IN MY PRIVATE SERVER AND I HAVE THIS FATAL ERROR WHY

https://gyazo.com/93d1f28d034f09d88dcfdbfca27fa161

**Comment by Luka967** [comment]
Use an older version of `ws` module.

**Comment by leboloss18k** [comment]
How i cant update please i dont know im a noob

**Comment by leboloss18k** [comment]
how i can use older version of ws module please

**Comment by AlexandriteErikParacelsus** [comment]
Search it up

**Comment by leboloss18k** [comment]
i dont understand

**Comment by ItzLevvie** [comment]
1) Delete your ```node_modules``` folder

2) In your packages.json file, you've to change ```"ws": "latest"``` to ```"ws": "1.1.0"```

3) Then go to the ```run``` folder and double click on the ```win-Install_Dep.bat``` file to download the required modules to run MultiOgar-Edited.

4) and finally click on the ```win-Start.bat``` to start your server up

**Comment by JaraLowell** [comment]
if (ws._socket.destroy != null && typeof ws._socket.destroy == 'function')

Reading ws._socket while it already destroyed and deleted; Might add an catch there if you use this.

**Comment by Luka967** [comment]
It's a problem with the new `ws` version; the `onClose` event should fire before the socket object is fully destroyed.

**Comment by JaraLowell** [comment]
From OgarServ Wiki:

As of like V8 version 3.17.13.0 the option to set max new space bin removed. So when you start the server with the --max-new-space-size=xxxx option the server wont start trowing an error.

We do suggest that you use node v0.10.25 ~ v0.10.43 (V8 version 3.14.5.9) as these versions use the lowest memory with OgarServ.

To change your node version:
sudo npm cache clean -f --force
sudo npm install -g n
sudo n 0.10.43

After this, make sure to install the node modules again by first removing the node_modules folder and dooing an npm install
