### ISSUE TITLE
Error :/

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#493]
![image](https://cloud.githubusercontent.com/assets/18153674/22620915/ce1d9ca6-eae4-11e6-9d03-c7f739554eeb.png)

How to fix?

**Comment by ItzLevvie** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by ItzLevvie** [comment]
@Jhair2015 https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by Jhair2015** [comment]
@ItzLevvie  Thank You, i close it.
