### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#496]
When I type in `pl m`, it comes up with this;
![image](https://cloud.githubusercontent.com/assets/23644244/22626052/5b47b2c6-eb9c-11e6-9e52-189f80ca89cf.png)
Do I need to replace `toString` with something else?

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by Tyler3D** [comment]
:D I can fix that hold up imma make a pull

**Comment by Tyler3D** [comment]
This is related to #469

**Comment by ZfsrGhS953** [comment]
Why do such errors happen so often? They crash the server, and because they occur very often, server owners will start going back to MultiOgar soon.

**Comment by Tyler3D** [comment]
@ZfsrGhS953 I'm pretty sure these errors were in multiogar too.

**Comment by ZfsrGhS953** [comment]
MultiOgar doesn't have as much errors as MultiOgar-Edited.

**Comment by Luka967** [comment]
Barbosik was careful with errors. Both `PlayerCommand.js` and `CommandList.js` need to be rewritten.

**Comment by Megabyte918** [comment]
I have fixed errors in the Updates branch.
