### ISSUE TITLE
how to change the color of food?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#498]
only food , no cells.

**Comment by Tyler3D** [comment]
@gyeyoqu 
Change this line: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L870
to this

cell.setColor({[insert color here});
If I wanted a blue I would do: cell.setColor({ r: 0, g: 153, b: 255});
If I want a virus green I would do: cell.setColor({ r: 0x33, g: 0xff, b: 0x33 });
Use this site to find different colors: http://www.w3schools.com/colors/colors_picker.asp

**Comment by gyeyoqu** [comment]
thanks
