### ISSUE TITLE
node Console-plus.js error on startup

### ISSUE THREAD

**Issue by CalvinDKHD** [Megabyte918/MultiOgar-Edited#501]
Hey guys! so i was just trying to run the console
and this happened

https://gyazo.com/9ac76faf67de06078b2cca8c6d451b0a

does anyone have any ideas?
thanks

**Comment by Luka967** [comment]
Use version 1.1.0 of `ws`.

**Comment by CalvinDKHD** [comment]
Can you please run me through it?

**Comment by ItzLevvie** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by ItzLevvie** [comment]
@CalvinDKHD https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by CalvinDKHD** [comment]
When i do that errors just occur.

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData vector2-node
20 silly mapToRegistry name vector2-node
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'vector2-node',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'vector2-node',
23 silly mapToRegistry   name: 'vector2-node',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/vector2-node
25 silly fetchNamedPackageData ws
26 silly mapToRegistry name ws
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'ws',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   escapedName: 'ws',
29 silly mapToRegistry   name: 'ws',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri https://registry.npmjs.org/ws
31 verbose request uri https://registry.npmjs.org/vector2-node
32 verbose request no auth needed
33 info attempt registry request try #1 at 10:01:52 PM
34 verbose request id 7d1f5d5d55f04a82
35 verbose etag W/"52899007-b7c"
36 verbose lastModified Mon, 18 Nov 2013 03:56:55 GMT
37 http request GET https://registry.npmjs.org/vector2-node
38 verbose request uri https://registry.npmjs.org/ws
39 verbose request no auth needed
40 info attempt registry request try #1 at 10:01:52 PM
41 verbose etag W/"5894be03-174eb"
42 verbose lastModified Fri, 03 Feb 2017 17:29:39 GMT
43 http request GET https://registry.npmjs.org/ws
44 http 304 https://registry.npmjs.org/vector2-node
45 verbose headers { date: 'Sun, 05 Feb 2017 21:01:51 GMT',
45 verbose headers   via: '1.1 varnish',
45 verbose headers   'cache-control': 'max-age=300',
45 verbose headers   etag: 'W/"52899007-b7c"',
45 verbose headers   age: '88',
45 verbose headers   connection: 'keep-alive',
45 verbose headers   'x-served-by': 'cache-bma7026-BMA',
45 verbose headers   'x-cache': 'HIT',
45 verbose headers   'x-cache-hits': '1',
45 verbose headers   'x-timer': 'S1486328511.241725,VS0,VE0',
45 verbose headers   vary: 'Accept-Encoding' }
46 silly get cb [ 304,
46 silly get   { date: 'Sun, 05 Feb 2017 21:01:51 GMT',
46 silly get     via: '1.1 varnish',
46 silly get     'cache-control': 'max-age=300',
46 silly get     etag: 'W/"52899007-b7c"',
46 silly get     age: '88',
46 silly get     connection: 'keep-alive',
46 silly get     'x-served-by': 'cache-bma7026-BMA',
46 silly get     'x-cache': 'HIT',
46 silly get     'x-cache-hits': '1',
46 silly get     'x-timer': 'S1486328511.241725,VS0,VE0',
46 silly get     vary: 'Accept-Encoding' } ]
47 verbose etag https://registry.npmjs.org/vector2-node from cache
48 verbose get saving vector2-node to C:\Users\Calvin\AppData\Roaming\npm-cache\registry.npmjs.org\vector2-node\.cache.json
49 verbose correctMkdir C:\Users\Calvin\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
50 http 304 https://registry.npmjs.org/ws
51 verbose headers { date: 'Sun, 05 Feb 2017 21:01:51 GMT',
51 verbose headers   via: '1.1 varnish',
51 verbose headers   'cache-control': 'max-age=300',
51 verbose headers   etag: 'W/"5894be03-174eb"',
51 verbose headers   age: '22',
51 verbose headers   connection: 'keep-alive',
51 verbose headers   'x-served-by': 'cache-bma7027-BMA',
51 verbose headers   'x-cache': 'HIT',
51 verbose headers   'x-cache-hits': '1',
51 verbose headers   'x-timer': 'S1486328511.241756,VS0,VE0',
51 verbose headers   vary: 'Accept-Encoding' }
52 silly get cb [ 304,
52 silly get   { date: 'Sun, 05 Feb 2017 21:01:51 GMT',
52 silly get     via: '1.1 varnish',
52 silly get     'cache-control': 'max-age=300',
52 silly get     etag: 'W/"5894be03-174eb"',
52 silly get     age: '22',
52 silly get     connection: 'keep-alive',
52 silly get     'x-served-by': 'cache-bma7027-BMA',
52 silly get     'x-cache': 'HIT',
52 silly get     'x-cache-hits': '1',
52 silly get     'x-timer': 'S1486328511.241756,VS0,VE0',
52 silly get     vary: 'Accept-Encoding' } ]
53 verbose etag https://registry.npmjs.org/ws from cache
54 verbose get saving ws to C:\Users\Calvin\AppData\Roaming\npm-cache\registry.npmjs.org\ws\.cache.json
55 verbose correctMkdir C:\Users\Calvin\AppData\Roaming\npm-cache correctMkdir already in flight; waiting
56 silly fetchNamedPackageData No valid target from cache, forcing network
57 verbose request uri https://registry.npmjs.org/vector2-node
58 verbose request no auth needed
59 info attempt registry request try #1 at 10:01:53 PM
60 http request GET https://registry.npmjs.org/vector2-node
61 silly resolveWithNewModule ws@2.0.2 checking installable status
62 silly cache add args [ 'ws@latest', null ]
63 verbose cache add spec ws@latest
64 silly cache add parsed spec Result {
64 silly cache add   raw: 'ws@latest',
64 silly cache add   scope: null,
64 silly cache add   escapedName: 'ws',
64 silly cache add   name: 'ws',
64 silly cache add   rawSpec: 'latest',
64 silly cache add   spec: 'latest',
64 silly cache add   type: 'tag' }
65 silly addNamed ws@latest
66 verbose addNamed "latest" is being treated as a dist-tag for ws
67 info addNameTag [ 'ws', 'latest' ]
68 silly mapToRegistry name ws
69 silly mapToRegistry using default registry
70 silly mapToRegistry registry https://registry.npmjs.org/
71 silly mapToRegistry data Result {
71 silly mapToRegistry   raw: 'ws',
71 silly mapToRegistry   scope: null,
71 silly mapToRegistry   escapedName: 'ws',
71 silly mapToRegistry   name: 'ws',
71 silly mapToRegistry   rawSpec: '',
71 silly mapToRegistry   spec: 'latest',
71 silly mapToRegistry   type: 'tag' }
72 silly mapToRegistry uri https://registry.npmjs.org/ws
73 verbose addNameTag registry:https://registry.npmjs.org/ws not in flight; fetching
74 verbose get https://registry.npmjs.org/ws not expired, no request
75 silly addNameTag next cb for ws with tag latest
76 silly addNamed ws@2.0.2
77 verbose addNamed "2.0.2" is a plain semver version for ws
78 silly cache afterAdd ws@2.0.2
79 verbose afterAdd C:\Users\Calvin\AppData\Roaming\npm-cache\ws\2.0.2\package\package.json not in flight; writing
80 verbose correctMkdir C:\Users\Calvin\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
81 verbose afterAdd C:\Users\Calvin\AppData\Roaming\npm-cache\ws\2.0.2\package\package.json written
82 http 200 https://registry.npmjs.org/vector2-node
83 verbose headers { server: 'nginx/1.10.1',
83 verbose headers   'content-type': 'application/json',
83 verbose headers   'last-modified': 'Mon, 18 Nov 2013 03:56:55 GMT',
83 verbose headers   etag: 'W/"52899007-b7c"',
83 verbose headers   'content-encoding': 'gzip',
83 verbose headers   'cache-control': 'max-age=300',
83 verbose headers   'content-length': '723',
83 verbose headers   'accept-ranges': 'bytes',
83 verbose headers   date: 'Sun, 05 Feb 2017 21:01:51 GMT',
83 verbose headers   via: '1.1 varnish',
83 verbose headers   age: '88',
83 verbose headers   connection: 'keep-alive',
83 verbose headers   'x-served-by': 'cache-bma7026-BMA',
83 verbose headers   'x-cache': 'HIT',
83 verbose headers   'x-cache-hits': '2',
83 verbose headers   'x-timer': 'S1486328511.277933,VS0,VE0',
83 verbose headers   vary: 'Accept-Encoding' }
84 silly get cb [ 200,
84 silly get   { server: 'nginx/1.10.1',
84 silly get     'content-type': 'application/json',
84 silly get     'last-modified': 'Mon, 18 Nov 2013 03:56:55 GMT',
84 silly get     etag: 'W/"52899007-b7c"',
84 silly get     'content-encoding': 'gzip',
84 silly get     'cache-control': 'max-age=300',
84 silly get     'content-length': '723',
84 silly get     'accept-ranges': 'bytes',
84 silly get     date: 'Sun, 05 Feb 2017 21:01:51 GMT',
84 silly get     via: '1.1 varnish',
84 silly get     age: '88',
84 silly get     connection: 'keep-alive',
84 silly get     'x-served-by': 'cache-bma7026-BMA',
84 silly get     'x-cache': 'HIT',
84 silly get     'x-cache-hits': '2',
84 silly get     'x-timer': 'S1486328511.277933,VS0,VE0',
84 silly get     vary: 'Accept-Encoding' } ]
85 verbose get saving vector2-node to C:\Users\Calvin\AppData\Roaming\npm-cache\registry.npmjs.org\vector2-node\.cache.json
86 verbose correctMkdir C:\Users\Calvin\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
87 silly fetchPackageMetaData Error: No compatible version found: vector2-node@1.1.0
87 silly fetchPackageMetaData Valid install targets:
87 silly fetchPackageMetaData 0.0.3, 0.0.2
87 silly fetchPackageMetaData
87 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:178:16)
87 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
87 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:20:8
87 silly fetchPackageMetaData     at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:174:7)
87 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:241:18
87 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:111:15)
87 silly fetchPackageMetaData  error for vector2-node@1.1.0 { Error: No compatible version found: vector2-node@1.1.0
87 silly fetchPackageMetaData Valid install targets:
87 silly fetchPackageMetaData 0.0.3, 0.0.2
87 silly fetchPackageMetaData
87 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:178:16)
87 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
87 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:20:8
87 silly fetchPackageMetaData     at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:174:7)
87 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:241:18
87 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:111:15) code: 'ETARGET' }
88 silly rollbackFailedOptional Starting
89 silly rollbackFailedOptional Finishing
90 silly runTopLevelLifecycles Finishing
91 silly install printInstalled
92 verbose stack Error: No compatible version found: vector2-node@1.1.0
92 verbose stack Valid install targets:
92 verbose stack 0.0.3, 0.0.2
92 verbose stack
92 verbose stack     at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:178:16)
92 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
92 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:20:8
92 verbose stack     at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:174:7)
92 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:241:18
92 verbose stack     at FSReqWrap.oncomplete (fs.js:111:15)
93 verbose cwd C:\Users\Calvin\Desktop\MultiOgar-Main\run
94 error Windows_NT 10.0.14393
95 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
96 error node v7.2.0
97 error npm  v3.10.9
98 error code ETARGET
99 error notarget No compatible version found: vector2-node@1.1.0
99 error notarget Valid install targets:
99 error notarget 0.0.3, 0.0.2
100 error notarget This is most likely not a problem with npm itself.
100 error notarget In most cases you or one of your dependencies are requesting
100 error notarget a package version that doesn't exist.
100 error notarget
100 error notarget It was specified as a dependency of 'MultiOgar-Edited'
101 verbose exit [ 1, true ]
`

**Comment by CalvinDKHD** [comment]
ok nvm i fixed it, but now nothing happens when i use the console!

https://gyazo.com/787086e8adabbe834927f1717bbab864

i cant use commands

**Comment by CalvinDKHD** [comment]
Got it!
