### ISSUE TITLE
How to make explotion like to gota.io?

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#502]
Plz :D

**Comment by Jhair2015** [comment]
Changue valors on virus.js

idk xD

**Comment by AlexByte918** [comment]
puto

**Comment by MastaCoder** [comment]
WeLl UU c whchu do heer is just udpate th maan explosionb in virusjs and then  edit antoehr line with x = 2.42134 and bam u got coool expl0sion!1!!1

**Comment by Luka967** [comment]
xDDDDDDDDDD

**Comment by Jhair2015** [comment]
ALV all :v

**Comment by AlexandriteErikParacelsus** [comment]
U cannot lotion urself in agar
