### ISSUE TITLE
any way to add custom skins script  on my agario webclient ??

### ISSUE THREAD

**Issue by wayfarer2** [Megabyte918/MultiOgar-Edited#504]
Hi there i have a webclient wich im using multiogar to run the server but i want to add the Custom-skins to my webclient .
im hoping that players can use any skin they want when they join but i dont know how
please help me .... Thanks and sry for my bad english

**Comment by CalvinDKL** [comment]
Yes, you can look at the CigarProject which is open source and already has it implemented :)

**Comment by AlexHGaming** [comment]
Please only report issues on the project, not clients.

**Comment by wayfarer2** [comment]
Sry For that man

**Comment by Jhair2015** [comment]
Close it
