### ISSUE TITLE
How to change the console plus port?

### ISSUE THREAD

**Issue by CalvinDKHD** [Megabyte918/MultiOgar-Edited#507]
Hello, i so i tried changing the port by changing it in the .html and js file, and it doesnt work.
Its still 1234

**Comment by ItzLevvie** [comment]
@CalvinDKHD https://github.com/Megabyte918/MultiOgar-Edited/blob/master/run/console-plus.js#L177

**Comment by ItzLevvie** [comment]
@CalvinDKHD 

1.  https://github.com/Megabyte918/MultiOgar-Edited/blob/master/run/console-plus.js#L139
2. https://github.com/Megabyte918/MultiOgar-Edited/blob/master/run/console-plus.js#L177

**Comment by CalvinDKHD** [comment]
Sorry, i overlooked that :)
Thank tou Levvie!
