### ISSUE TITLE
Sometimes the server just closes, randomly.

### ISSUE THREAD

**Issue by CalvinDKHD** [Megabyte918/MultiOgar-Edited#508]
Anyone else having this problem?
https://gyazo.com/260aa6bf86d54098aa02345db9d89542
When this happens it just tries to connect to the server.
here is the console, no errors.
https://gyazo.com/e114aba20bfab5bc9e941c54108365ab

**Comment by AlexHGaming** [comment]
The client might be having a bit of a bug.
1. Try entering the ip in the address bar.
2. If it's your client, you need to fix the connection if the address bar isn't working.
I'm not having any bugs as I use Codeanywhereupmyarse and there aren't any errors with clients or servers.

Does your server sometimes work? @CalvinDKHD

**Comment by CalvinDKHD** [comment]
the server works on old versions of multiogar

**Comment by Jhair2015** [comment]
@CalvinDKHD Changue Protocol 11 to 9.

**Comment by CalvinDKHD** [comment]
Can you run me through on how to do that?

**Comment by Jhair2015** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L38

Changue the number 11 to 9.

**Comment by ItzLevvie** [comment]
@Jhair2015 

Don't think that will help.

**Comment by Luka967** [comment]
@Jhair2015 That won't do anything.
@CalvinDKHD Check the server log.

**Comment by Tyler3D** [comment]
Maybe it has to do with this? https://github.com/Megabyte918/MultiOgar-Edited/issues/474

**Comment by Luka967** [comment]
Possible, let's just wait for Calvin to respond.

**Comment by Jhair2015** [comment]
lol sorry :p

**Comment by Luka967** [comment]
no problem xD

**Comment by CalvinDKHD** [comment]
Alright, ill let it run over night. If the same problem occurs in the morning, ill tell ya guys.

**Comment by Luka967** [comment]
It won't do anything. It'll just block agar.io connections to the server.

**Comment by gyeyoqu** [comment]
clien problem

**Comment by RasyiidWho** [comment]
Delete minion check at https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js

**Comment by Luka967** [comment]
wat

**Comment by CalvinDKHD** [comment]
@Luka967 So i left it open overnight, and it didnt crash :)

**Comment by Luka967** [comment]
The server obviously won't crash. You're having is a connection problem. Can you actually play on the server?

**Comment by Jhair2015** [comment]
@CalvinDKHD Use older versión of MultiOgar!

**Comment by CalvinDKHD** [comment]
yeah, i can play on the server. But after some time it just closes.

**Comment by Megabyte918** [comment]
@CalvinDKHD Are you using this branch or the Updates branch? This should have been fixed on the updates branch.

**Comment by AlexHGaming** [comment]
Close? @Megabyte918
