### ISSUE TITLE
Unfinished

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#509]
![image](https://cloud.githubusercontent.com/assets/23644244/22667662/bbaf90a6-ecb5-11e6-80f0-717de7ebf18b.png)
Does not show position when adding the new fix to the `pl m` command.

**Comment by Megabyte918** [comment]
@AlexHGaming PlayerTracker by default does not keep track of the score and position of minions.

**Comment by AlexHGaming** [comment]
k
