### ISSUE TITLE
FORBID WORDS

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#511]
How can I do so that each rank can use certain forbidden names, even though they all have the same forbidden names in common

**Comment by Megabyte918** [comment]
@gyeyoqu This question is similar to https://github.com/Megabyte918/MultiOgar-Edited/issues/187, the code from there should also add what you are asking.

**Comment by gyeyoqu** [comment]
not help me.

**Comment by Megabyte918** [comment]
That code allows admins/mods to use specific words or tags that normal players cannot, that's what you wanted, right?
