### ISSUE TITLE
PREFIX

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#512]
If I created a userLevel with level 5, what is its prefix? If the prefix of SERVER IS 0x80?

**Comment by Agarian** [comment]
0x80 is a flag for the agar client to know what food cells are...

**Comment by Luka967** [comment]
He's talking about chat packets.

**Comment by gyeyoqu** [comment]
yes , how?

**Comment by Agarian** [comment]
Oh.

**Comment by Tyler3D** [comment]
This is client-related sorta. You can "fix" it by using this http://pastebin.com/MKEgM9mk for your ChatMessage.js. And please don't make the same issue on two different repos. Especially since this fork is about a less laggy experience. And mine is about bs features. You will experience a performance decrease with this method tho. @gyeyoqu

**Comment by gyeyoqu** [comment]
@Tyler3D  not work :(

**Comment by Tyler3D** [comment]
@gyeyoqu Then you added the roles wrong

**Comment by Tyler3D** [comment]
It works for me

**Comment by gyeyoqu** [comment]
Object.defineProperty(exports, name, {
        value: value,
        enumerable: true,
        writable: false,
        configurable: false
    });
}

define("GUEST", 0);
define("USER", 1);
define("PRO", 3);
define("LEYEND", 4);
define("DIOS", 5);
define("MODER", 6);
define("ADMIN", 7);

**Comment by gyeyoqu** [comment]
{ 
        "ip":"-", 
        "password":"pass",
        "role":"LEYEND",
        "name":"DIOS" 
    },

**Comment by Tyler3D** [comment]
@gyeyoqu wtf That should work

**Comment by gyeyoqu** [comment]
not working :(

**Comment by Megabyte918** [comment]
@gyeyoqu I have no idea about chat packets let alone finding them, In the meantime just change the admin one to LEYEND and you'll be fine.

**Comment by gyeyoqu** [comment]
i want to add roles , not to replace

**Comment by Megabyte918** [comment]
@gyeyoqu Find the chat packets of the client you are using then add the role along with the packet.
