### ISSUE TITLE
longest

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#513]
how to use longest view without be spectator

**Comment by AlexHGaming** [comment]
???

**Comment by AlexHGaming** [comment]
Do you mean having a larger camera view?

**Comment by Agarian** [comment]
Same what do you mean?

**Comment by AlexHGaming** [comment]
I need to change my profile pic, don't I lmao

**Comment by Agarian** [comment]
Yeah xd

**Comment by AlexHGaming** [comment]
Changing

**Comment by Agarian** [comment]
Cool

**Comment by AlexHGaming** [comment]
Keeping it like this. Now you won't need to keep bragging about us 2 having very similiar profile pictures :P

**Comment by Megabyte918** [comment]
@gyeyoqu Change the `serverMinScale` config. You will need a different client or an extension that allows for extra zoom or else changing it wont matter.
