### ISSUE TITLE
updateMoveEngine using a lot of CPU

### ISSUE THREAD

**Issue by deniskrop** [Megabyte918/MultiOgar-Edited#516]
I am profiling the code to make it faster, and have found that updateMoveEngine is the culprit. Does anyone know what could be slowing it down the most? I'm trying to refactor the code to get more information about what is slow from the profiler.

**Comment by ZfsrGhS953** [comment]
Quadtree.

**Comment by gyeyoqu** [comment]
@ZfsrGhS953  spatial hash is better?

**Comment by ZfsrGhS953** [comment]
Yes, but there are even better collision detection algorithms. You'll see them once I finish making my own server software.

**Comment by Megabyte918** [comment]
The `updateMoveEngine` function was removed and its contents were placed inside of `mainLoop` at the very start of this repository a few months ago. Please make sure you are running the latest version
