### ISSUE TITLE
pay for make game

### ISSUE THREAD

**Issue by Osher12** [Megabyte918/MultiOgar-Edited#517]
sup @Megabyte918 i dont really find someone to make game so i want open here,
if someone here know coding and make game like alis.io/ugar.pw and all this shit game
please contact me skype:pzaze11 (i pay alot of money)

**Comment by SomeoneCares11** [comment]
You can't create game like alis.io or ugar.pw unless you're developer.
If you have a lot of money as you said, make company like (MiniClip) and hire Developers, designers :P

**Comment by Osher12** [comment]
i am developer i need someone to work with me together, i can make alot of money believe me i am in this bussiness alot, i know how many developer take every x hour so thats why i search people i need fix some bugs that i dont know how to fix him

(sry for bad english)

**Comment by SomeoneCares11** [comment]
i was like you and i lost my money with the developers, i lost about 2000$ 
Trust me you need to learn who you do your own stuff. 
Day after day i did what i paid for, for free and its better and easier than what i thought.

Its just an advice, I apologize for the intrusion.

**Comment by kareemman00** [comment]
@Osher12 Ican Help U So :smile:

**Comment by gyeyoqu** [comment]
@kareemman00  if you make me a minimap like alis.io i pay you 20$

**Comment by Osher12** [comment]
@gyeyoqu contact me skype : pzaze11

**Comment by gyeyoqu** [comment]
@Osher12  i cant find you

**Comment by gyeyoqu** [comment]
i using web skype

**Comment by Osher12** [comment]
@gyeyoqu what your skype

**Comment by gyeyoqu** [comment]
Agar Sebastian

**Comment by gyeyoqu** [comment]
in description says : facebook:mayboixgamer

**Comment by Jhair2015** [comment]
@Osher12 I have alis.io free code, the current update! :P

**Comment by Jhair2015** [comment]
@Agarian Yes, i have main.js & sub.js free :p xDdd

**Comment by Agarian** [comment]
Oh you're talking about the client

**Comment by Osher12** [comment]
@Jhar2015 send msg on skype : pzaze11

**Comment by Osher12** [comment]
@Jhair2015

**Comment by MastaCoder** [comment]
@Jhair2015 you did realize taking code is illegal lmao

**Comment by Megabyte918** [comment]
And especially distributing it to other people xd

**Comment by gyeyoqu** [comment]
http://ogar.pw/v2 =) alis.io code

**Comment by Osher12** [comment]
@gyeyoqu send msg on skype pzaze11

**Comment by Jhair2015** [comment]
@Osher12  Send me the request, skype does not show me to you in the directory D:
 my skype: live:jimmy_jhair17

**Comment by gyeyoqu** [comment]
@Osher12  same problem , you not appear

**Comment by Osher12** [comment]
@Jhair2015 Accept
@gyeyoqu idk why not, but try search with email : pzaze1@walla.com (name Osher)

**Comment by Jhair2015** [comment]
![image](https://cloud.githubusercontent.com/assets/18153674/22837035/e7f62df8-ef8c-11e6-9b59-6bd23a196ae6.png)
Those are the results skype throws at me. I have sent a request to the second, and you say that you have already sent it to me, but I have nothing ...

**Comment by Osher12** [comment]
@Jhair2015 what is your discord?
@gyeyoqu what is your discord?

**Comment by Jhair2015** [comment]
@Osher12 https://discordapp.com/channels/280777597338648576

**Comment by Osher12** [comment]
@Jhair2015 not working just send me the code of the server

**Comment by Jhair2015** [comment]
https://discord.gg/4vHw8

**Comment by Osher12** [comment]
@Jhair2015 expired

**Comment by Jhair2015** [comment]
and now? https://discord.gg/rerUJgr
