### ISSUE TITLE
server reconnect

### ISSUE THREAD

**Issue by Osher12** [Megabyte918/MultiOgar-Edited#518]
so my vps working 24/7 and after x hour the server just reconnect why is happen?
look : www.blobsonline.com

**Comment by Jhair2015** [comment]
Probar una versión anterior a está

**Comment by Megabyte918** [comment]
@Osher12 This was fixed in the updates branch, I'm pretty sure.

**Comment by Jhair2015** [comment]
@Megabyte918  Has been fixed, but has some bugs, such as; Spectate, connection, does not allow connection to my client with the branch of updates, but an update 25 days ago if allowed.

**Comment by Megabyte918** [comment]
@Jhair2015 Can you go into detail about those bugs?

**Comment by Jhair2015** [comment]
@Megabyte918 on this ---> https://github.com/Megabyte918/MultiOgar-Edited/tree/Updates

i have spectate bug, minion missing all mass, and more

bad english sorry

**Comment by Megabyte918** [comment]
@Jhair2015 Please see this comment: https://github.com/Megabyte918/MultiOgar-Edited/pull/446#issuecomment-277546760
Same thing applies for score, position, etc.

**Comment by Jhair2015** [comment]
@Megabyte918 Ok, thanks you for this support
