### ISSUE TITLE
if depending success login

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#519]
How can I make an if, if the player is logged in correctly?

something like:

if (player.Login === 'sucess') {  (ONLY EXAMPLE)

//
}

**Comment by Megabyte918** [comment]
@gyeyoqu Just add a check to see if the player's user role is USER, MODER, or ADMIN, because by default every player is marked as "guest". You can't login as a guest. PlayerCommand.js should give you an idea on how it works.
