### ISSUE TITLE
where i can change that

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#52]
where i can change the reach of a virus

**Comment by ZfsrGhS953** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L1312
Change 780 to whatever you like

**Comment by RelTakeover** [comment]
i mean the reach 
To blow up a player 
not the reach of explotion..

**Comment by ZfsrGhS953** [comment]
The line I highlighted is the distance of a virus shot, not the distance of explosion.

**Comment by Megabyte918** [comment]
@RelTakeover Viruses, ejected cells, and players all use the same eat distance. But if you would like to change that you can do something like this under the `resolveCollision` function in GameServer.js:
<pre>
var eatDistance;
// Eat distance for viruses
if (minCell.cellType == 2 || maxCell.cellType == 2) { 
    eatDistance = maxCell._size - minCell._size / 3;    << change the "3" to any number you like
// Eat distance for anything else BUT viruses
} else {
    eatDistance = maxCell._size - minCell._size / 3;
}
</pre>

**Comment by RelTakeover** [comment]
i want change only virus reach

**Comment by Megabyte918** [comment]
That is the reach.

**Comment by RelTakeover** [comment]
with this configuration the reach is soo high

**Comment by RelTakeover** [comment]
please answer me @Megabyte918

**Comment by Megabyte918** [comment]
@RelTakeover What do you have the number set to? If it's too high just lower it

**Comment by RelTakeover** [comment]
this code not working

   
    var eatDistance;
// Eat distance for viruses
if (minCell.cellType == 2 || maxCell.cellType == 2) { 
    eatDistance = maxCell._size - minCell._size / 0.000000000000000000000001;    
// Eat distance for anything else BUT viruses
} else {
    eatDistance = maxCell._size - minCell._size / 0.000000000000000000000001;
}


with value of 0.000000000000000000000001; is higher than the original code with value of '3' , why?

**Comment by ZfsrGhS953** [comment]
Increase it instead of decreasing it.

**Comment by RelTakeover** [comment]
sure? i will try

**Comment by RelTakeover** [comment]
Still the same, it seems that even if the value changes, nothing changes

**Comment by ZfsrGhS953** [comment]
Increase it to a very big value, like 100

**Comment by RelTakeover** [comment]
sure? i will try

**Comment by RelTakeover** [comment]
dont working..

**Comment by Megabyte918** [comment]
@RelTakeover works fine for me, what are you trying to get at? make the eat distance larger? smaller?

**Comment by RelTakeover** [comment]
larger

**Comment by RelTakeover** [comment]
With this, you will not have to get too close to the virus for popsplit

**Comment by RelTakeover** [comment]
with value of 3000000 same distance , the code didnt work :(

**Comment by RelTakeover** [comment]
you are sure that the code is correct?

**Comment by Megabyte918** [comment]
@RelTakeover It does increase the eat distance, but if you would like to increase it more you can do:
<pre>
// check distance
var eatDistance = maxCell._size - minCell._size / 3;
    
// custom eat distance
if (minCell.cellType == 2 || maxCell.cellType == 2) {
    // eat distance for viruses
    var distanceMult = Math.pow(eatDistance, 3);
} else {
    // eat distance for anything BUT viruses
    distanceMult = Math.pow(eatDistance, 2);
}
if (manifold.squared >= distanceMult) {
     // too far => can't eat
    return;
}
</pre>

**Comment by ZfsrGhS953** [comment]
Just change [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L922) to:
```javascript
if (manifold.squared >= eatDistance * eatDistance && minCell.cellType != 2) {
````

**Comment by RelTakeover** [comment]
thanks @Megabyte918
