### ISSUE TITLE
Autosplit on the direction of mouse

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#522]
How can I change it so when I autosplit, instead of splitting a random direction, how can I make it autosplit as if I've done a normal split where my mouse is? I know this isn't normal in vanilla, but I'd like this option
Thanks.

**Comment by Luka967** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L692
Change it to `Math.atan2(cell.position.x - client.mouse.x, cell.position.y - client.mouse.y)`

**Comment by AlexHGaming** [comment]
Thanks man

**Comment by Agarian** [comment]
lol wow

**Comment by Luka967** [comment]
what?
quick question quick answer

**Comment by Agarian** [comment]
@Luka967 When that's added cells go opposite the mouse.
``Math.atan2(cell.position.x - client.mouse.x, cell.position.y - client.mouse.y)``
Should be:
``Math.atan2(client.mouse.x - cell.position.x, client.mouse.y - cell.position.y)``

**Comment by Luka967** [comment]
Rip my brain

**Comment by Agarian** [comment]
lol

**Comment by AlexHGaming** [comment]
oh shit, woops. Thanks @Agarian 
Hope it doesn't fuck up

**Comment by AlexHGaming** [comment]
server crashes :/

**Comment by Luka967** [comment]
What error causes crashes?

**Comment by Agarian** [comment]
First, which branch did you use?
Second, did you include the `var angle` part?
