### ISSUE TITLE
I MIGHT have a solution to the cell switching at the end of 4 parts

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#523]
This might not work in the code but worth having a try.

Try making it so when the 4th part is in the front of all of the cells, add a `boost` definement then add the boost on a seperate line in the splitting area of code. (sorry if this is confusing)
Make this `boost` take effect on the 4th part so when all 4 parts are laying out, this 4th part will get a boost to the front of the order. This could also stabilise popsplits.
The boost is meant to mean where the delay of splitting, when it flinches back then goes back forward again, try and make it so the 4th part gets this BOOST by a small value to lower chances of cell switch
I don't know if the 3rd part will need flinching back, but maybe you could get an idea of what I am saying, and try getting some tips off this.
And no I am NOT downloading off any repos, as I already have my own adjustments to my server.
And no again I can't do this myself, I'm a noob at code myself, but.. you know practice makes perfect lmfao.
Sorry if I confused you with what I said lol.
I'm just so addicted to my own server, thanks to you @Megabyte918 7

Best regards
-Alex

**Comment by AlexHGaming** [comment]
Or maybe try to rewrite the splitting code again

**Comment by Megabyte918** [comment]
> Try making it so when the 4th part is in the front of all of the cells, add a boost definement then add the boost on a seperate line in the splitting area of code. (sorry if this is confusing)

The "4th" part is not decided until after extrusion force is applied, which means there is no way to tell until the doublesplit is over.

> Make this boost take effect on the 4th part so when all 4 parts are laying out, this 4th part will get a boost to the front of the order. This could also stabilise popsplits.

What i said above^^. Also cell switching order on doublesplit does not affect popsplits.

> The boost is meant to mean where the delay of splitting, when it flinches back then goes back forward again, try and make it so the 4th part gets this BOOST by a small value to lower chances of cell switch
I don't know if the 3rd part will need flinching back, but maybe you could get an idea of what I am saying, and try getting some tips off this.

What I said on the first one^^. Same thing applies for 3rd part.

> Or maybe try to rewrite the splitting code again

Well that's helpful lol, thats like saying if popsplit doesnt work then "rewrite popsplits"

**Comment by raphyjb** [comment]
^^ last thing made me laugh

**Comment by AlexHGaming** [comment]
Well I don't know then. I'm just a noob at code and learning. I thought popsplits were affected, my mistake. I was meaning long distance popsplits, normal popsplits are fine. And I was thought you could of maybe rewrote the splitting code because it could work out the next time? I dunno if I'm in an awkward position.

**Comment by Megabyte918** [comment]
Popsplit's are not affected, long distance or short. And the splitting is not the problem, it is an issue with the collision engine. But don't beat yourself up about it, I was the exact same way when I first joined github and started interacting with the community :)

**Comment by Agarian** [comment]
Weren't we all?

**Comment by Luka967** [comment]
Yes we were mate, yes we were

**Comment by AlexHGaming** [comment]
Thanks for positivity @Megabyte918 at least you aren't like them type of people who might not give a f**k about the community *cough* Andrews *cough* that made no sense *cough*
