### ISSUE TITLE
Send your Gameserver.ini

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#524]
I wanna play something different, Send in some different Gameserver.ini if you have some :)
I wanna try em all!

**Comment by MastaCoder** [comment]
Nice issue!

**Comment by Jhair2015** [comment]
lol

**Comment by raphyjb** [comment]
Ok, Issue is this page is getting boring, i wanna have get entertained cuz pewdeipei isnt entertaning me no mo ;( i cri evrytim

**Comment by Luka967** [comment]
YouTube's unsubscribe bugs should entertain you a little xD

**Comment by Megabyte918** [comment]
@raphyjb Please ask this question somewhere else rather than make an issue about it, it is off topic.
Also if PewDiePie isn't entertaining you anymore watch other YouTubers lol

**Comment by raphyjb** [comment]
RIP PUDIPI ;( #PewdiepieFightYoutube
