### ISSUE TITLE
freeroam

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#525]
i cant freeroam spectator

**Comment by Agarian** [comment]
? Press Q

**Comment by Megabyte918** [comment]
^^ I can freeroam just fine. Make sure you don't have minions because they also use the Q key. Either that or disable any extensions/scripts that are also using the Q key.

**Comment by gyeyoqu** [comment]
I am using minions, but I have disabled the Q for minions

**Comment by Agarian** [comment]
Oh, even is Q for minions is disabled, that bug still happens with minions.

**Comment by Megabyte918** [comment]
I will investigate

**Comment by gyeyoqu** [comment]
thanks @Megabyte918

**Comment by Megabyte918** [comment]
Fixed in the updates branch.
