### ISSUE TITLE
How To Auto Restart?

### ISSUE THREAD

**Issue by TheBeast2000** [Megabyte918/MultiOgar-Edited#527]
Help me please

**Comment by AlexHGaming** [comment]
What type of auto-restart do you mean? Do you mean auto-restarting after someone reaches a certain amount of mass or auto-restarting after a certain time limit?

**Comment by MastaCoder** [comment]
Duplicate.

**Comment by TheBeast2000** [comment]
After someone reaches a certain amount of mass

**Comment by Luka967** [comment]
Duplicate of #447

**Comment by TheBeast2000** [comment]
If I put the maximum mass in 5000, and someone reaches that mass, will all players all players die?

**Comment by Luka967** [comment]
No

**Comment by TheBeast2000** [comment]
And how do I make all players die?

**Comment by FantasyIsBae** [comment]
type in killall in the console .

**Comment by Luka967** [comment]
xD

**Comment by Jhair2015** [comment]
buhh xD
