### ISSUE TITLE
About Double splits ..

### ISSUE THREAD

**Issue by MartincoderMlg** [Megabyte918/MultiOgar-Edited#528]
Can Double splits have an other number of splitVelocity Cuz seems having splitVelocity set to lower than 200 make double splits work pretty well close to agar.io

**Comment by Megabyte918** [comment]
Doublesplits cannot have a different split velocity. This is because all splitting uses the same move engine and rigid collision resolution.

**Comment by MartincoderMlg** [comment]
Rip
