### ISSUE TITLE
Enhancement created, need suggestions

### ISSUE THREAD

**Issue by Agarian** [Megabyte918/MultiOgar-Edited#529]
I have successfully created a way for minions to follow a player's/owner's cells. I have made triggers for this in two ways: A key (for the ERTP script), and through a command. However i need suggestions:
- What key should trigger minions to follow the cell?
- What should the command be named, and it's shortcut?

 I just want to make triggers that people will be comfortable with. Now, i'm still THINKING of adding it.

**Comment by Agarian** [comment]
I forgot why I made this issue.

**Comment by Fan7asy** [comment]
lol
