### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#530]
update to UCS NAMES AND CHAT MESSAGES

**Comment by AlexHGaming** [comment]
umm.... what?

**Comment by Luka967** [comment]
He wants strings to be in Unicode again.

**Comment by MastaCoder** [comment]
yes but that doesn't match the current protocol standard.

**Comment by Megabyte918** [comment]
Pretty sure there already is UCS names and chat messages.

**Comment by Luka967** [comment]
He's using my protocol 6 Cigar but he wants the Unicode strings back.
*this guy is weird*

**Comment by gyeyoqu** [comment]
@Luka967 help me please i love you  , jaralowell already added emoticons to his protocol 6
