### ISSUE TITLE
Minion Key Controls

### ISSUE THREAD

**Issue by KrulYuno** [Megabyte918/MultiOgar-Edited#532]
So, here I have no idea about how to control the minions in others keys. The only way to control the minions are to Press Q then you can use W and Space to make them feed or split. But I want it in separate keys. Like, W and Space is for your cell and E and R is for your minions.
How can I do it?
I tried disableERTP = 0 but it didn't work.

**Comment by AlexHGaming** [comment]
What you need to do, is have `disableQ` to 0, and have `disableERTP` to 0.
Install Tampermonkey
Then go to your folder of MultiOgar-Edited, look for the `scripts` folder, then find `AgarMacros.js`
Double click it to go into the folder.
Copy and paste all of the code.
Make a new script in tampermonkey, and paste the entire code into the new script
Refresh Agar.
You're welcome.

**Comment by KrulYuno** [comment]
So, it will only work in http://agar.io/* and http://old.ogarul.io/*?
I tried it on http://astr.io, no luck.

**Comment by AlexHGaming** [comment]
it only works on agar.io
And old.ogarul.io has default, it's already supported E,R,T,P controls, the macro's are built-in, so no need.
And I accidently gave you wrong file. Make a new script and paste in the `ERTPControls` <- I forgot what it's called.
Then did as I did above.
You might as well keep the `AgarMacros.js` script active as it gives you macro feed.

**Comment by KrulYuno** [comment]
ERTPcontrol.js?
I also added // @match        http://astr.io/* to the script. It still doesn't work. Well, atleast old.ogarul.io worked.

**Comment by ZfsrGhS953** [comment]
Astr.iо doesn't use ```Int8Array```s to send data through WebSocket.

**Comment by KrulYuno** [comment]
Ohh.. Thanks. :)

**Comment by ZfsrGhS953** [comment]
I made the ERTPcontrol.js userscript and know how it works.

**Comment by Jhair2015** [comment]
Could I make the script compatible for this client? @ZfsrGhS953
