### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#533]
![image](https://cloud.githubusercontent.com/assets/23644244/22852619/935bd986-f037-11e6-8be6-1108c6f2d8c4.png)

**Comment by AlexHGaming** [comment]
And when retrying to deleting the server and installing it again:
![image](https://cloud.githubusercontent.com/assets/23644244/22852775/a4cee20e-f03b-11e6-985f-d89ff6c1c0c7.png)

**Comment by Luka967** [comment]
You've reinstalled the Updates branch, right?

**Comment by AlexHGaming** [comment]
uhhh..... how do you do that? xD

**Comment by AlexHGaming** [comment]
I downloaded your fork but I want to do comparisions and have fun, but this server shut on me after applying the so called 'fixes' from MegaByte in the pull request section xD

**Comment by AlexHGaming** [comment]
@Luka967 ^^

**Comment by AlexHGaming** [comment]
How do you reinstall updates branch?

**Comment by AlexHGaming** [comment]
In the node_modules/ws/index.js bit, that's the problem, according to the error, how to fix?

**Comment by ZfsrGhS953** [comment]
~~Replace all instances of "const" with "var" and give it another try.~~ Install the latest version of node.js.

**Comment by AlexHGaming** [comment]
Problem was by my side.
Thank you
Closing
