### ISSUE TITLE
Option for show scores

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#536]
Add option for show scores in the leaderboard like dual agar

**Comment by Agarian** [comment]
I think you'd need a custom client for this, then again, this may be done in a similar fashion to diep.io

**Comment by Luka967** [comment]
^

**Comment by Tyler3D** [comment]
Naw, @Luka967's Rush Mode is this sorta.

**Comment by Tyler3D** [comment]
But, this may require a seperate gamemode idk

**Comment by Tyler3D** [comment]
@Luka967 Can I borrow your leaderboard userText and normal functions from your fork.

**Comment by Luka967** [comment]
Sure, no need for credit

**Comment by MastaCoder** [comment]
No need for a custom client. It'd just need server updates, but I don't see why someone would need this since it'd go off the leaderboard.

**Comment by Megabyte918** [comment]
^^
Especially if your name is at the max nick length. It will cause bugs on the vanilla client, so I am not adding this.

**Comment by Tyler3D** [comment]
@gyeyoqu Change your updateLeaderboard.js file to this http://pastebin.com/iTVmDrFC
Add leaderboardmass config to gameServer.js file and gameserver config file
Works on Vanilla but like @Megabyte918 This will cause bugs if you have a long name
