### ISSUE TITLE
AFK Detection !

### ISSUE THREAD

**Issue by SomeoneCares11** [Megabyte918/MultiOgar-Edited#537]
Hi,

i'm afk for 2 days and i'm still connected to the ws:// connection for multiogar server, WTF 😊
How can i detect AFKs :)

Thank you!

**Comment by MastaCoder** [comment]
Pretty sure on an actual server your player would have died by the time you came back. Now for socket connections, pretty sure multiogar closes the connection after a while of being inactive. (I think)

**Comment by Luka967** [comment]
It does

**Comment by Agarian** [comment]
This is a config named `serverTimeout`
