### ISSUE TITLE
How to reload files from .js instead of .ini

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#538]
How can I make it so when I make some changes for example: Virus.js, how can I reload the virus.js file while the server's running without it closing or is it not a feature?

**Comment by Luka967** [comment]
It's not a feature, it's practically very hard and can lead to crashes with existing cells if cell variables' data changes (unless you reset the nodes immediately after applying the new functions).

**Comment by AlexHGaming** [comment]
oh ok.. thanks though! @Luka967
