### ISSUE TITLE
bug in web console ?

### ISSUE THREAD

**Issue by AGarRiBiA** [Megabyte918/MultiOgar-Edited#539]
any people can join to web console it's easy
just change the server IP in console-plus.html
like this

      var Host='serverip:1234';                
and it's will connected to the server console without password # # @

**Comment by Megabyte918** [comment]
You sure you set it up correctly? People may be able to join the web console, but they cannot login. Me and everyone else has to enter a username and pass on my console.

**Comment by AGarRiBiA** [comment]
i think you don't understand me , open this page
http://agarribia.com/console-plus.html

without password :!

**Comment by AGarRiBiA** [comment]
the same console but with password -
http://agarribia.com:1000
admin
test123

**Comment by TheBeast2000** [comment]
How do you do that?

**Comment by Megabyte918** [comment]
@AGarRiBiA Just set it up the same way you did the second one lol, then you will have a password

**Comment by FlareYT** [comment]
@AGarRiBiA , it seems like that you putted the 'console-plus.html' into your Webserver .
You only have to setup console-plus.js ( Replace 127.0.0.1 with your ip) and run it via Command Prompt or NodeJS -> 'node console-plus.js' .
Then you can easily go on your site : http://yoururl.com:1234 <- Port !

Greetings Flare !

**Comment by AGarRiBiA** [comment]
i know that but if people know my console port and have the html file he can access my console if he change the Ip and port in html file to my console port - ip

**Comment by Gimmo** [comment]
Fixed

**Comment by Agarian** [comment]
@Megabyte918

**Comment by AGarRiBiA** [comment]
thanks
