### ISSUE TITLE
IDEA

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#54]
new gamemode:bots (
automatically 
give bots for all
new configs:
autogivebotscount = number of bots to give
autogivebotsname = name of bots
botsautogivebots = 0 (disable and enable to bots give bots)
autogivebotminmass = 32
autogivebotmaxmass = 32 
good idea:D

**Comment by ZfsrGhS953** [comment]
Already added in Petridish Ogar. It would be cool to have the feature here as well !

**Comment by Megabyte918** [comment]
I will work on it, but I am busy with other things atm so it might take some time

**Comment by Megabyte918** [comment]
Finished.
