### ISSUE TITLE
Virus Spawn

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#540]
some times virus spawns inside a player in Update Branch

**Comment by SomeoneCares11** [comment]
+1

**Comment by Luka967** [comment]
If the server is too crowded the safe spawning system fails in most cases.

**Comment by Agarian** [comment]
Never happens to me (then again i don't use the updates branch)

**Comment by ARBCells** [comment]
@Gigabyte918 +1

**Comment by Megabyte918** [comment]
I am aware of this, been trying to fix it.

**Comment by legit** [comment]
Was just about to submit the same issue. +1

**Comment by Megabyte918** [comment]
Fixed in the updates branch.
