### ISSUE TITLE
Bad Leaderboard

### ISSUE THREAD

**Issue by NiesamoWhite** [Megabyte918/MultiOgar-Edited#541]
# Can not solve the problem of the leaderboard?

**Comment by AlexHGaming** [comment]
Look at the latest commits.

**Comment by NiesamoWhite** [comment]
I can't saw my name on the leaderboard

**Comment by Luka967** [comment]
He isn't done updating it yet.

**Comment by NiesamoWhite** [comment]
shit......

**Comment by AlexHGaming** [comment]
Luka on your fork it shows the leaderboard is fixed for me.

**Comment by Luka967** [comment]
That's because I fixed it, Megabyte didn't lol

**Comment by Jhair2015** [comment]
@Luka967 Could you give me a link to your upgrade branch? I've seen your fork, but I do not run the leaderboard in orange

**Comment by Agarian** [comment]
Megabyte did fix it, it just breaks some gamemodes, and Mega's tryna fix em

**Comment by Tyler3D** [comment]
@Jhair2015 The update branch was already merged with master. Just download it

**Comment by Jhair2015** [comment]
@Agarian @Tyler3D Thanks

**Comment by NiesamoWhite** [comment]
@Tyler3D you have fixed the leaderboard?

**Comment by ItzLevvie** [comment]
@NiesamoWhite Use @Luka967's fork

**Comment by NiesamoWhite** [comment]
Can you give me the link?

**Comment by NiesamoWhite** [comment]
I don't understand :/

**Comment by ItzLevvie** [comment]
@NiesamoWhite https://github.com/Luka967/MultiOgar-Edited

**Comment by NiesamoWhite** [comment]
@ItzLevvie THANK YOU!

**Comment by Megabyte918** [comment]
I'm working on it, but very busy ATM

**Comment by ARBCells** [comment]
What do I need to copy from Luka967's fork just to get the red color of the leaderboard?

**Comment by AlexHGaming** [comment]
Luka has different definements on his fork, so probably try to mess around with changing it.
The `LeaderboardPosition` and `updateLeaderboard` is what you have to mess with.
And I don't know again if different definements are in the 2 files soooo.... yeah.

**Comment by Megabyte918** [comment]
Fixed in the updates branch
