### ISSUE TITLE
 How to put password to my console plus?

### ISSUE THREAD

**Issue by TheBeast2000** [Megabyte918/MultiOgar-Edited#543]
Help me

**Comment by TheBeast2000** [comment]
Heeeeelp

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by Jhair2015** [comment]
read Readme.md lol xD

**Comment by TheBeast2000** [comment]
But still the same without password

**Comment by Megabyte918** [comment]
Please see this readme: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/run/README.md
