### ISSUE TITLE
Minions names

### ISSUE THREAD

**Issue by MartincoderMlg** [Megabyte918/MultiOgar-Edited#544]
How to make Minions have the same name as the player or user

**Comment by AlexHGaming** [comment]
just type
`minion [ID] [amount] [name]

**Comment by MartincoderMlg** [comment]
By default they get unamed or the name u give them , basicallyI want them to have user name as default
serverMinions = 10
collectPellets = 1
defaultName = "!username"

**Comment by ARBCells** [comment]
@MartincoderMlg Yup, that would be amazing.

@Megabyte918 Please check this out

**Comment by Luka967** [comment]
Find this line in CommandList.js:
```js
gameServer.bots.addMinion(client, name);
```
Replace it with this:
```js
gameServer.bots.addMinion(client, name || client._name);
```

**Comment by MartincoderMlg** [comment]
ty ❤️

**Comment by MartincoderMlg** [comment]
@Luka967  still one problem the minions spawn before players so they aren't able to get name player name

**Comment by Luka967** [comment]
Spawn before adding minions for yourself

**Comment by MartincoderMlg** [comment]
@Luka967  I meant for auto adding minions from here serverMinions = 10
xD

**Comment by Luka967** [comment]
oh
hmm
too lazy to find how to change that

**Comment by MartincoderMlg** [comment]
me too now just have to make minions  auto spawn after players can u give me a tip I'm new to js but not that bad
