### ISSUE TITLE
Custom skins

### ISSUE THREAD

**Issue by NiesamoWhite** [Megabyte918/MultiOgar-Edited#545]
# **Can you make it possible to give custom skins to the bots?**

**Comment by Luka967** [comment]
Set their name to <skin>name.

**Comment by NiesamoWhite** [comment]
How?

**Comment by NiesamoWhite** [comment]
@Luka967 Not the real skins, others skins!

**Comment by Luka967** [comment]
Custom skins clientsided

**Comment by ARBCells** [comment]
@NiesamoWhite Nope, its not possible. But you can use `<r>BotsName` for random skins.

**Comment by AlexandriteErikParacelsus** [comment]
Client-sided, closing

**Comment by AlexHGaming** [comment]
Alexandrite doesn't give a fuck 😂😂😂😂

**Comment by Luka967** [comment]
@AlexHGaming 
> Custom skins are clientsided

Neither do I

**Comment by NiesamoWhite** [comment]
where is clientsided? @Luka967

**Comment by Luka967** [comment]
Server doesn't store and send skin images, it's the client that gives cells skins.

**Comment by Agarian** [comment]
^^
