### ISSUE TITLE
Split Problem

### ISSUE THREAD

**Issue by SomeoneCares11** [Megabyte918/MultiOgar-Edited#546]
Hi,

I dont know if you are aware about this problem,

sometimes when you split on top the cells split on down 
or to where your mouse was !

ty

**Comment by AlexHGaming** [comment]
I'm actually getting this issue as well.
It happens rarely for me but when it happens it's a pain in the arse.

**Comment by AlexandriteErikParacelsus** [comment]
Gif?

**Comment by Megabyte918** [comment]
Could not reproduce. If you could provide a short video or gif that shows the bug, it would help alot :)

**Comment by FlareYT** [comment]
We could help you , if there would be a Screenshot / Gif :) !

Greetings Flare

**Comment by AlexHGaming** [comment]
I can't send one as my laptop lags after recording like after 10 secs. And it happens RARELY, so it would be impossible to catch

**Comment by SomeoneCares11** [comment]
Ok i have asked my visitors to capture one, its seems you don't know about it :)
it was good in the original MultiOgar

**Comment by Luka967** [comment]
I've seen this problem in MultiOgar too.

**Comment by Megabyte918** [comment]
@SomeoneCares11 What branch were you using when you encountered this bug?

**Comment by JoeryDroppers** [comment]
I also have this issue, I am using the update branch.

**Comment by Megabyte918** [comment]
@SomeoneCares11 Could you elaborate a bit more on the bug? 
> sometimes when you split on top the cells split on down

Do you by chance mean when your cells reflect off of the border?

> or to where your mouse was !

That's supposed to happen lol

**Comment by AlexHGaming** [comment]
> Do you by chance mean when your cells reflect off of the border?
No, at times when you move your mouse after around 100ms of pressing the space bar, it will move to the direction of the mouse when it is supposed to stick on the previous issue.
I can't explain it in much detail, as it only happens to me rarely.

**Comment by Megabyte918** [comment]
@AlexHGaming Try playing around with the latest version of the updates branch for a bit, see if it still happens

**Comment by SomeoneCares11** [comment]
Its fixed when i used last version of node. its server lag issue.
