### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#547]
hi
i recently installed the new version of multiogar-edited and i installed the node module and then i ran it, but when i connect, it just says "TypeError: Cannot read property 'destroy' of null"

any fix?

**Comment by ItzLevvie** [comment]
@freaky767 https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by freaky767** [comment]
thanks
