### ISSUE TITLE
ADD GOTA.IO SPLITS

### ISSUE THREAD

**Issue by Steve7914** [Megabyte918/MultiOgar-Edited#549]
pls

**Comment by AlexHGaming** [comment]
Duplicate of #330 and kinda #300 
Please review other issues before making one.

**Comment by Tyler3D** [comment]
Yay, that saves me hours of playing gota.io in order to implement it into my fork. xD

**Comment by Jhair2015** [comment]
@Tyler3D xDDD

**Comment by Luka967** [comment]
@Megabyte918 Close

**Comment by MartincoderMlg** [comment]
make this splitVelocity = 100 here u got gota.io lol

**Comment by Luka967** [comment]
XD

**Comment by Jhair2015** [comment]
@MartincoderMlg wow xDD
