### ISSUE TITLE
Bots cannot have minions

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#55]
Fix

**Comment by Megabyte918** [comment]
Why would you want bots to have minions? They cant control them lol

**Comment by t11tanYT** [comment]
i want this, for more reaistic

**Comment by rjay222** [comment]
@Megabyte918 he wants to feel like hes playing on a server with bots, just like when you join a party server and theres a bot user. It's indeed more realistic imo.

**Comment by Fantasy-Agario** [comment]
Well , we need the , "only one person can control minions" fixed , before we start anything else :)

**Comment by AlexandriteErikParacelsus** [comment]
@Fantasy-Agario lmao, already fixed a long time ago

**Comment by Megabyte918** [comment]
@t11tanYT For a temporary fix you can remove the `!this.owner.socket.isConnected || ` from this line here:
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/MinionPlayer.js#L23
but it breaks minions disconnecting when the owner leaves, I will have to figure out a way to separate bots and minions further but for right now just do that.

**Comment by Jhair2015** [comment]
add spawn with bots please! :D

**Comment by AlexandriteErikParacelsus** [comment]
@Jhair2015 what did I tell you? And what did you promise to me

**Comment by Megabyte918** [comment]
Most people don't give minions to bots, so if they want to they can just remove that part of the code. There is no easy solution to this problem or at least that I can find so I will close this for now.
