### ISSUE TITLE
Add ogarUL plugin System

### ISSUE THREAD

**Issue by Steve7914** [Megabyte918/MultiOgar-Edited#551]
So people can add features and have no lag for people that don't want them

**Comment by AlexHGaming** [comment]
We can't add OgarUL plugins as we are a different repo that has our own options in the scripts and that would be very bad for andrews as it's just copying and that's lame.

**Comment by Luka967** [comment]
> that would be very bad for andrews

Like we care lol

@Steve7914 that would create a shitload of errors that need to be resolved.

**Comment by Tyler3D** [comment]
xDDDDD

**Comment by Jhair2015** [comment]
@Steve7914 As MegaBye said, first is the performance.

**Comment by AlexHGaming** [comment]
_'MegaBye'_
And yeah the performance is very important, not fun playing a laggy server.

**Comment by Jhair2015** [comment]
@AlexHGaming lol xDD, fucking keyboard, keyboard from IPhone xD
