### ISSUE TITLE
Suggestion : More settings for Minions 

### ISSUE THREAD

**Issue by FlareYT** [Megabyte918/MultiOgar-Edited#552]
So...

I saw that http://mgar.io got Gamemodes like 'Speedy Bots' and wanted to ask , if it would be possible to get it added @Megabyte918 !
I will try my best and keep you Guys updated ! :)

Greetings Flare !

**Comment by Luka967** [comment]
Do you know for a file called `gameserver.ini`?

**Comment by FlareYT** [comment]
@Luka967 , I meant that there should be some Extra Options like adding the Minions another option like "minionSpeed = 1" !

Greetings Flare :) !

**Comment by ZfsrGhS953** [comment]
@FlareYT @Megabyte918 doesn't want to add options like that because they reduce performance.

**Comment by FlareYT** [comment]
@ZfsrGhS953 , I will wait till @Megabyte918 answers !
Otherwise thanks :)

Greetings ! :)

**Comment by ZfsrGhS953** [comment]
@FlareYT He already said that before: https://github.com/Megabyte918/MultiOgar-Edited/pull/376#issuecomment-271470247

**Comment by Megabyte918** [comment]
Yes it is possible, but for performance reasons it will not be implemented. I want to have the highest performance possible with minions :)

**Comment by ZfsrGhS953** [comment]
@Megabyte918 Why you didn't merge my pull request, then?

**Comment by FlareYT** [comment]
@Megabyte918 , alright ! :)
