### ISSUE TITLE
HUGE GLITCH IN COMMAND PROMPT FATAL ERROR -205

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#555]
Sikeeee, You though there was a bug actually there isnt, just want to know where your at with the client u said u were ganna make..

**Comment by Luka967** [comment]
What a clickbait

**Comment by MartincoderMlg** [comment]
^ ikr

**Comment by raphyjb** [comment]
but it worked right?

**Comment by AlexHGaming** [comment]
you can just get a higher chance of getting banned. MEGABYTE NEVER GIVES A SHIT lmfao

**Comment by Tyler3D** [comment]
xDDD ikr

**Comment by MastaCoder** [comment]
lmao what the hell is this..

**Comment by ItzLevvie** [comment]
No idea..

**Comment by MastaCoder** [comment]
1. You didn't pay for MultiOgar-edited, so stop constantly yelling at him to make promises so you guys can simply use it on your own websites, not even leave jack sh*t of credit towards him at all.

2. This section is for ISSUES. Not some clickbait stuff, either you're asking to have this closed and get closer to a ban, or you just have no idea what you're doing.

Where's the respect? @Megabyte918 is putting in so much time to make something OPEN SOURCE so all of you can use it, I myself go to school and own my own websites. It's really hard to program with school on the side. (Well at least for me lmao) Also, he's doing this for free. Also, I'm pretty sure he never made a promise about making a client.. If you want a client, then just use Cigar. It's compatible with MultiOgar and gives you the basic functionalities of a client. If you want more, add them yourself. It's the point of learning to program for the EXPERIEEEEEEEEEEEEEENCE.

### Also thanks for reminding me, I should add a contributions page to my website ;)

**Comment by Luka967** [comment]
@MastaCoder kek include me xD

**Comment by Agarian** [comment]
;OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by TheBeast2000** [comment]
Bitch

**Comment by TheBeast2000** [comment]
@Megabyte918 is a bitch

**Comment by Agarian** [comment]
XD screenshotting this

**Comment by Tyler3D** [comment]
xDDDDDD

**Comment by Tyler3D** [comment]
@Megabyte918 Used Ban.. It's super effective

**Comment by TheBeast2000** [comment]
I do not care is the truth

**Comment by MastaCoder** [comment]
LOL

**Comment by TheBeast2000** [comment]
@MastaCoder 
You are a bitch

**Comment by TheBeast2000** [comment]
Fucking Bitch

**Comment by Tyler3D** [comment]
@TheBeast2000 Fun-Fact: F*** Has over 30 different Definitions. Could you clarify?

**Comment by TheBeast2000** [comment]
I do not speak English, bitch

**Comment by TheBeast2000** [comment]
Bitch Bitch Bitch BitchBitch BitchBitch BitchBitch BitchBitch BitchBitch BitchBitch BitchBitch BitchBitch BitchBitch Bitch

**Comment by Jhair2015** [comment]
Hahaha

**Comment by Megabyte918** [comment]
@raphyjb Please do not make any more invalid issues, this easily could have been asked somewhere else, no need to make an issue about it. Please refer to #128

**Comment by raphyjb** [comment]
alright sry hehe but never answered meh ;*

**Comment by Megabyte918** [comment]
> Please refer to #128
