### ISSUE TITLE
Custom Skins & VPS

### ISSUE THREAD

**Issue by adib696** [Megabyte918/MultiOgar-Edited#557]
=======================1=============================
how can i merge custom skins extension with this & macros Like Ftwin.io
and i tried to use the extension in tampermonkey and edited it but i still can't see the skin!!
=======================2=============================
& Is there any free good vps,
i already use: c9.io & codeanywhere.com ! i can buy premium in c9.io but it's not good as codeanywhere

**Comment by AlexHGaming** [comment]
Maybe you didn't see the skin because:
1. You have 'no skins' on.
2. You may of entered a wrong an invaild URL link.
And macros are fast on this anyways, so I don't see the issue.

**Comment by Luka967** [comment]
1. Use Cigar. It supports ERTP controls as well as a custom skin library. Has a 1700 line long main_out.js but you'll get the hang of it in a few weeks.

2. c9.io and codeanywhere aren't VPSes, they're programming IDEs. Also you have this thing that you're using right now, it's called the internet and is a very good source of information, you should use it to answer your own question.

**Comment by AlexHGaming** [comment]
>  it's called the internet and is a very good source of information, you should use it to answer your own question.

lmfao

> Use Cigar. It supports ERTP controls as well as a custom skin library. Has a 1700 line long main_out.js but you'll get the hang of it in a few weeks.

Or you can use vanilla agar as you can install @Megabyte918 's skin script in the `scripts` folder in the MultiOgar files.
I don't know if this'll work, but try and edit Megabyte's tampermonkey script, and make another URL reader and add ftwin.io in the scripts.
