### ISSUE TITLE
Extremely invalid, but please can I know the skin off this?

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#558]
Sorry for making an issue that has nothing to do with this, even add an 'invalid' label to this but:
What is the skin that Crystal used in the screenshot?
![image](https://cloud.githubusercontent.com/assets/23644244/23039996/974022ec-f487-11e6-83da-31ab2d203458.png)
Can I please know please! And again, sorry for invalidness.

**Comment by Luka967** [comment]
*megabyte locks issue for collaborators only*

**Comment by AlexHGaming** [comment]
Haha lmfao @Luka967

**Comment by Luka967** [comment]
@megabyte
XD

**Comment by ItzLevvie** [comment]
Find out yourself at https://github.com/ItzLevvie/Agario-skins/releases/download/474/premiumSkins.zip

**Comment by Tyler3D** [comment]
Multi-Ogar needs a forum or at least a redit page

**Comment by Tyler3D** [comment]
Nice

**Comment by ARBCells** [comment]
Lol. All Agar.io premium-skins can be found here: http://agario-skins.org/premium-skins

**Comment by AlexHGaming** [comment]
Lol all I wanted to know was the skin name.
And it's Dr.Cosmo's.
Thanks @ARBCells
