### ISSUE TITLE
Viewbox

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#559]
Whenever I'm in multiple pieces, the camera angle doesn't fit to size. Is this a duplicate?
![image](https://cloud.githubusercontent.com/assets/23644244/23046684/ea1349a2-f4a2-11e6-938f-f8d9b0659ac3.png)

**Comment by Agarian** [comment]
I've seen this, however, i'd have to be MUCH bigger to see this effect.

**Comment by Luka967** [comment]
View scale is smaller than the minimum one set in config.

**Comment by AlexHGaming** [comment]
How to fix? @Luka967 
Your're like my god lmfao

**Comment by AlexHGaming** [comment]
I retry on a different client 
This is another result
![image](https://cloud.githubusercontent.com/assets/23644244/23056369/0773e05c-f4e3-11e6-9bf0-4b2a1ba64ba0.png)

**Comment by AlexHGaming** [comment]
Is it a problem with the client?
What viewbase, X and Y, should I set?

**Comment by Luka967** [comment]
It's a server-side limitation in case first on the leaderboard has a massive field of view, to prevent too much upload usage. Change [this config](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L48) to less than 0.1 or 0.

**Comment by Jhair2015** [comment]
Lol @AlexHGaming  I see you like AgarPlus Style, you will love this client (my client xD) http://ultrafun.ga/

**Comment by Megabyte918** [comment]
@AlexHGaming Should be fixed in the updates branch
