### ISSUE TITLE
TrickSplit

### ISSUE THREAD

**Issue by SomeoneCares11** [Megabyte918/MultiOgar-Edited#560]
Hi, what is best split settings to get these awesome tricks becouse its not working, when we do split trick the enemy eat the cells on spliting!

https://www.youtube.com/watch?v=E9pcV5DULGs

**Comment by Megabyte918** [comment]
The current settings are the best settings. The amount of time it takes collision for cells to restore after splitting is the same as it is on vanilla servers.
