### ISSUE TITLE
Errors on disconnect!

### ISSUE THREAD

**Issue by smky** [Megabyte918/MultiOgar-Edited#561]
Basically, the client I use (Cigar) and the Agario vanilla client interfere whith the server when the client disconnects. This FATAL error is throw when a client disconnects (ex: closes browser):

![image](https://cloud.githubusercontent.com/assets/13950666/23078233/ce06e98a-f515-11e6-8900-b849f521020e.png)

As you can see, the server crashed when the client disconnects (destroy()). I have also installed the node modules with npm install, so that shouldn't be an issue.

Server Specs (Just in case):
OS: Ubuntu 16.04
Node Version: 6.5.9
Ram: 1 GB

**Comment by Jhair2015** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/commit/2e0341784f662b11550e396ff2445d28f0ea06f9


chengue package.son
