### ISSUE TITLE
Where's Diverse blow up in ur version 

### ISSUE THREAD

**Issue by MartincoderMlg** [Megabyte918/MultiOgar-Edited#562]
http://i.imgur.com/211pYFj.png

**Comment by Tyler3D** [comment]
@MartincoderMlg https://github.com/Megabyte918/MultiOgar-Edited/issues/332

**Comment by Tyler3D** [comment]
I think that's what you want?

**Comment by AlexHGaming** [comment]
the code was re-made so there is no such thing is 'curmass'
