### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#565]
how i can make all entity does not bounce from border and how i get this arrow on the screen by using a scrip or other extension like
![maxresdefault](https://cloud.githubusercontent.com/assets/17459204/23093951/c42ea360-f611-11e6-9b27-96352268c3c2.jpg)

**Comment by Luka967** [comment]
> how i can make all entity does not bounce from border

Remove [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L651-L656)

**Comment by Gigabyte918** [comment]
yes but i want to change this on Update Branch

**Comment by Luka967** [comment]
shit i was blind
Remove [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/Updates/src/entity/Cell.js#L80) and [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/Updates/src/entity/Cell.js#L85) line
