### ISSUE TITLE
ItzLevvie Help Please, you da best

### ISSUE THREAD

**Issue by adib696** [Megabyte918/MultiOgar-Edited#567]
hypex-yt.tk select FFA and play, why it keeps doing that ?

**Comment by Luka967** [comment]
Which branch are you using?

**Comment by ItzLevvie** [comment]
1. Make sure you've complete access to the 443 port, if not then change your ```serverPort = 443``` to something like ````serverPort = 581``` (you can change the port to what ever you like, but you need to make sure that you've access to that specific port)

2. Disable firewall to allow incoming and outgoing connections

3. If you're website is going to be playable from around the world then you need to change ```CONNECTION_URL = "127.0.0.1:443"``` to ```CONNECTION_URL = "putYourPublicIPhere:yourServerPort"```

**Comment by adib696** [comment]
@ItzLevvie the port is 5001 it works in agario but i can only spectate 
and it works on astr and i can PLAY
but it doesn't work here : im using CIGAR CLIENT
and Multi ogar edited by @Luka967

**Comment by ItzLevvie** [comment]
@adib696 Try using Megabyte918's Update branch and report back if it works or not

**Comment by adib696** [comment]
WORKING :D thanks @ItzLevvie 
But why it lags(freeze) sometimes
go try !
