### ISSUE TITLE
How to change mass of this 

### ISSUE THREAD

**Issue by Crypton918** [Megabyte918/MultiOgar-Edited#568]
Im want to change the mass of this mini cells of the explotion of virus.

Here a image to you stand more..
http://i.imgur.com/HftciMj.png

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js#L34

**Comment by Tyler3D** [comment]
@Crypton918 https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js#L64
Change minSize to what ever size

**Comment by Tyler3D** [comment]
xD both are right and achieve the same purpose

**Comment by Luka967** [comment]
Alex's method is safer.

**Comment by Crypton918** [comment]
Thanks, PLZ CLOSE
