### ISSUE TITLE
How To?

### ISSUE THREAD

**Issue by adib696** [Megabyte918/MultiOgar-Edited#569]
How To merge Agarplus or Ogario Theme with my site ?
AgarCrew.tk
Like: Disable Auto zoom
        Custom Food Color
        Custom Map Color
You get it!

**Comment by Tyler3D** [comment]
Client
Client
Client
https://github.com/Megabyte918/MultiOgar-Edited/issues/498
Client
Seriously, why do you have a website if you don't know how to change it.

**Comment by Megabyte918** [comment]
@adib696 Please do not make issues not related to this project
