### ISSUE TITLE
Food bigger

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#57]
megabyte where i can change to i can eat food more bigger than myself

**Comment by Megabyte918** [comment]
@RelTakeover I don't know about food bigger than yourself, but I can make it so you can eat the food if you are the same size as it. Add this into your `resolveCollision` function in GameServer.js:
<pre>
// Size check
if (maxCell.cellType == 1 || minCell.cellType == 1) {
    var sizeMult = 1;
} else {
    sizeMult = 1.15;
}
if (maxCell._size <= minCell._size * sizeMult) {
    // too large => can't eat
     return;
}
</pre>

**Comment by RelTakeover** [comment]
i mean if the food equal to 100 points , and the player start with 10 of mass , i need eat this food bigger , like ogarUL

**Comment by ZfsrGhS953** [comment]
https://github.com/ZfsrGhS953/Petridish-Ogar/blob/master/Ogar/src/GameServer.js#L1063 Look around this line, you probably want the cellType==1 stuff which checks if it's a food cell.

**Comment by RelTakeover** [comment]
@Megabyte918  @ZfsrGhS953  please help me , what i should edit yo change this ?

**Comment by RelTakeover** [comment]
@AlexandriteErikParacelsus  why you close the issue ?
