### ISSUE TITLE
Close tab/disconnect any player = Crash server

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#570]
**Video:** Sorry lag ;D
https://streamable.com/x2mbr

**Comment by ItzLevvie** [comment]
@DeadLord1337 #492 (comment)

**Comment by ItzLevvie** [comment]
@DeadLord1337 https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by DeadLord1337** [comment]
thx
