### ISSUE TITLE
Server keep crashing...

### ISSUE THREAD

**Issue by suprix** [Megabyte918/MultiOgar-Edited#572]
So when i run my server on Linux Centos VPS, after few minutes it just crash...
When someone try to login on agar.io while is in server, in console server crash again... please help meh...

![image](https://cloud.githubusercontent.com/assets/24485754/23102508/f6544f22-f6aa-11e6-9df7-826bc1ec4ef7.png)
you can see here i turned on server and nothing showed up but server work perfectly till moment it crash (turn off)

**Comment by Luka967** [comment]
Does the log say anything?

**Comment by MastaCoder** [comment]
^ if you're running under a screen, add a pause at the end to catch the error.

**Comment by suprix** [comment]
@Luka967 no, that's wierd thing... when i run server on my main pc (not on VPS) it got red error. You can see it down below.
@MastaCoder What do you mean?

Error on Windows:
![image](https://cloud.githubusercontent.com/assets/24485754/23104937/7a0673aa-f6d7-11e6-9a6c-9967300fd2b8.png)

**Comment by MastaCoder** [comment]
You're using the latest version of ws, check your package.json. There were already reports on this.

**Comment by suprix** [comment]
@MastaCoder how can i fix it?
I downloaded files yesterday.

**Comment by ItzLevvie** [comment]
@suprix https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by suprix** [comment]
Thanks, ill try now.

**Comment by suprix** [comment]
Thank you all soo much! :+1: You guys help me a lot! :)

**Comment by suprix** [comment]
![image](https://cloud.githubusercontent.com/assets/24485754/23105549/66fdb566-f6e1-11e6-80f3-81a1e6fbd05d.png)
Hey guys.... Now i have tryed on VPS (Linux Centos) and it still wont load :(
Even when it load sometimes it won't load log :/

**Comment by FantasyIsBae** [comment]
At the top of index.js put : "use strict";
                        Exactly this^^^^^^^^^

**Comment by FantasyIsBae** [comment]
And don't use const without strict mode.

**Comment by FantasyIsBae** [comment]
Ok just redownload the files , it seems to be an error with ws or your vps server

**Comment by suprix** [comment]
![image](https://cloud.githubusercontent.com/assets/24485754/23105919/940cb520-f6e6-11e6-9a50-a0f9ed3ee3a3.png)
I've got this crash again :(

**Comment by Luka967** [comment]
Make sure you downloaded the Updates branch.

**Comment by ItzLevvie** [comment]
@suprix https://github.com/JaraLowell/OgarServ/issues/172#issuecomment-279242778

**Comment by suprix** [comment]
Okay @ItzLevvie I have done that but still I don't get log of MultiOgar when i run the server (sudo node index.js)

**Comment by Megabyte918** [comment]
Pretty sure that's an issue with your VPS

**Comment by MastaCoder** [comment]
@suprix I'm pretty sure the > in front of the name means you're not running it from ssh? If you're trying to open the file through node.js with sudo, try it without sudo. So node index.js. (because sudo from what I remember doesn't work in node.js)

**Comment by suprix** [comment]
@Megabyte918 yeah, well i tryed on Windows too but it crash with some red shits as you can see above in pictures... @MastaCoder I can run only with Sudo node index.js, overwise ill get this: 
![image](https://cloud.githubusercontent.com/assets/24485754/23140964/b98e9a74-f7b4-11e6-959e-2d64338036e2.png)

Please, i need help ASAP guys! :|

**Comment by Luka967** [comment]
Get a newer version of node

**Comment by suprix** [comment]
i've updated everything

**Comment by Luka967** [comment]
Try reinstalling ws v1.1.0, not the latest one.

**Comment by suprix** [comment]
hm, i dont really know how to do that on Linux VPS... I am using Putty

**Comment by MastaCoder** [comment]
Do node -v. @suprix

**Comment by suprix** [comment]
ight, ill try in sec

**Comment by suprix** [comment]
![image](https://cloud.githubusercontent.com/assets/24485754/23141789/cbc7ff42-f7b8-11e6-8dbb-55061445e3e0.png)
@MastaCoder

**Comment by Luka967** [comment]
Weird.
Do node --version.

**Comment by suprix** [comment]
![image](https://cloud.githubusercontent.com/assets/24485754/23141817/e5dc3a56-f7b8-11e6-8983-8afc89e68f55.png)
I've tryed now even edited MultiOgar from DRGoat and when i join agar.io with server and port it just pause the server.. PS this pic i took from Windows

**Comment by MastaCoder** [comment]
> Do node --version.

**Comment by suprix** [comment]
![image](https://cloud.githubusercontent.com/assets/24485754/23141879/35b52092-f7b9-11e6-807c-c48087667b4f.png)
@Luka967

**Comment by MastaCoder** [comment]
You have an incorrect installation of node.js or your VPS is just playing games with you. Try nodejs --version, if it's not that. We have no idea lol

**Comment by MastaCoder** [comment]
Or you can also try --v

**Comment by suprix** [comment]
Again, just dots lol

**Comment by suprix** [comment]
well, ill wait for @Megabyte918 :(

**Comment by Megabyte918** [comment]
@suprix Try using it with node version `7.1.0`, and ws module version `1.1.0`. That works for me. But then again, I'm on windows so I don't know how well it will work for you

**Comment by ItzLevvie** [comment]
@suprix Try doing https://github.com/JaraLowell/OgarServ/issues/172#issuecomment-279242778

**Comment by ItzLevvie** [comment]
@suprix https://github.com/JaraLowell/OgarServ/issues/172#issuecomment-279242778

**Comment by MastaCoder** [comment]
@ItzLevvie he's on a bad install of node where version doesn't work. 

@suprix just update it, if all fails then it's a problem with your VPS.

**Comment by systemroot** [comment]
can you first show some infos like **lsb_release -a** or **cat /etc/issue**
and **cat /proc/cpuinfo | grep model**
?!

a stupid question, why do you put a . (dot) at the end of "node --version" ?! or i'm blind :confounded:

**Comment by Luka967** [comment]
>a stupid question, why do you put a . (dot) at the end of "node --version" ?! or i'm blind 😖

Both Makan and I were blind, that's what it broke the flag lol

**Comment by MastaCoder** [comment]
WAAAIT HE'S RIGHT

**Comment by Megabyte918** [comment]
@systemroot is that you in the middle of your profile picture lol

**Comment by systemroot** [comment]
@Megabyte918 yea me like a boss xP

**Comment by MastaCoder** [comment]
Got the issue. Read this: http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode to solve the issue for this.

@Megabyte918 You can close this now, unrelated to the server. As for errors like this, we should really make a FAQ in the wiki so errors like the ws one and this one can be put there instead of always getting dupes of them.
