### ISSUE TITLE
Why here you can see your skin?

### ISSUE THREAD

**Issue by Crypton918** [Megabyte918/MultiOgar-Edited#573]
Why here you can see your own skin, and agar.io no. Why?

http://154.16.127.140/agar/#ip=154.16.127.140:777

Why on thath page you can see skin and agar no whyy plz explain meee

**Comment by Jhair2015** [comment]
Agar Protocol

**Comment by Luka967** [comment]
Agar.io won't display any skins on private servers.

**Comment by Crypton918** [comment]
@Jhair2015 So?

**Comment by adib696** [comment]
view-source:http://154.16.127.140/agar/#ip=154.16.127.140:777
da fuq Lol

**Comment by adib696** [comment]
No External files

**Comment by Crypton918** [comment]
@adib696 whut?

**Comment by adib696** [comment]
is that ur site ?

**Comment by Jhair2015** [comment]
@adib696 view-source:http://154.16.127.140/agar/#ip=154.16.127.140:777 **** xD

**Comment by adib696** [comment]
lol

**Comment by ItzLevvie** [comment]
That's @MineMoore's website

**Comment by Crypton918** [comment]
@ItzLevvie yep, but im asking how, in minemoore site you can see your own skins and agar.io no.

**Comment by ItzLevvie** [comment]
Because the client is based on Agar.io v72

**Comment by adib696** [comment]
@ItzLevvie can anyone add auto restart in "custom_time" to multiogar edited ?

**Comment by adib696** [comment]
bcz after 20mins the server stops
but it still work in the cmd !!

**Comment by Crypton918** [comment]
@ItzLevvie How to make work agar Expose?
