### ISSUE TITLE
Implement a new feature. (Cell outline changement.)

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#575]
Normally on vanilla, growing a massive amount of mass in 1 piece 'mediumly speed' grows the outline from`the cell's old size to it's actual size. in medium speed
I have a comparison on what I mean.
https://streamable.com/336zn
Please, I really want this feature.
@Megabyte918
@Andrews54757

**Comment by JoeryDroppers** [comment]
It's client-side?

**Comment by AlexHGaming** [comment]
No it's not, as this can be added to the cell.js file, so it's server sided actually.

**Comment by Andrews54757** [comment]
@AlexHGaming Dont tag me (Dont do @andrews54757). I am not doing Ogar anymore.

**Comment by Jhair2015** [comment]
@AlexHGaming  In fact if possible without implementing anything, "minor zoom" in the browser may be the solution (usually happens because the pc is too sh * t) xD The same as mine is D:

**Comment by Luka967** [comment]
@AlexHGaming That's a client feature. Protocol 5 Cigar does this too when the cell isn't in smooth render mode.

**Comment by MartincoderMlg** [comment]
client-side here's the piece of code that does it 
            function Rc(a) {
                if (null == a || 0 == a.length) return null;
                if ("%" == a[0]) {
                    if (!c.MC || !c.MC.getSkinInfo) return null;
                    a = c.MC.getSkinInfo("skin_" + a.slice(1));
                    if (null == a) return null;
                    for (a = (+a.color).toString(16); 9 > a.length;) a = "0" + a;
                    return  "#"+ a
                }
                return null
            }

**Comment by ItzLevvie** [comment]
@MartincoderMlg That's for skins

**Comment by ItzLevvie** [comment]
@MartincoderMlg That code will only work on v72 client

**Comment by AlexHGaming** [comment]
:[

**Comment by MartincoderMlg** [comment]
@AlexHGaming  stop wasting ur time making issues if you want to learn to code it's never too late ...

**Comment by AlexHGaming** [comment]
@MartincoderMlg Well making issues can get the person learning. Also learning from pull requests can get you learning.

**Comment by MastaCoder** [comment]
Or actually making it yourself.

**Comment by AlexHGaming** [comment]
@MastaCoder True, I really do need to learn Javascript lol

**Comment by Megabyte918** [comment]
@MastaCoder That's how I learned lol, trial and error over and over again

**Comment by MastaCoder** [comment]
@Megabyte918 same 😄  I usually just look at other people's code and try to learn from it. Then I play around with console until something happens. Not a good strategy, but hey, it's fun!

**Comment by Luka967** [comment]
kekness = 6900
bugs = 0

**Comment by Jhair2015** [comment]
@MastaCoder same lol xD

**Comment by Jhair2015** [comment]
@MastaCoder But, only on clients xDD

**Comment by AlexHGaming** [comment]
@MastaCoder Omg same, I know what var is now 😂, well I kinda knew it for a long time. What language are clients written in? Is it css or something like that?

**Comment by Tyler3D** [comment]
@AlexHGaming Html + CSS + Javascript and maybe PHP

**Comment by MastaCoder** [comment]
No PHP unless if you're working with server side things as well. (Getting files, MySQL, etc)

**Comment by RasyiidWho** [comment]
change smoothrender to .3
