### ISSUE TITLE
Eject mobile - agar

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#577]
How to move the eject mobile physic in normal agar?
**Normal agar eject**
![default](https://cloud.githubusercontent.com/assets/24901742/23160229/bc0ba08a-f836-11e6-83b6-45367919b18e.PNG)
**Mobile agar eject**
![2](https://cloud.githubusercontent.com/assets/24901742/23160276/e263ee0e-f836-11e6-9e00-a220982a14f8.PNG)

If you please you can add this feature :)
```
[EJECTED MASS]
; ejectPhysics: 1 - mobile agar eject, 0 - Normal agar eject
ejectPhysics = 1/0
```

**Comment by Megabyte918** [comment]
If you want ejected cells to collide for mobile physics, remove the `&& !self.config.mobilePhysics` from [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/Updates/src/GameServer.js#L574) line in GameServer.js

**Comment by DeadLord1337** [comment]
No, I want to extract the cells collide mobile physics were normal physics agar ._.

**Comment by Megabyte918** [comment]
@DeadLord1337 You can stop ejected cells from colliding on normal agar by commenting out the function call on [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/Updates/src/GameServer.js#L575) line.

**Comment by DeadLord1337** [comment]
Ohh... xD thx. But please add this feature to other users to make it easier <3
