### ISSUE TITLE
Cannot find module index.js

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#578]
https://gyazo.com/7fe8d0a9c1d40681a20d9eaef438c6c3

This is the error that happens
Anyone here that knows a fix?
index.js is in src by the way.

**Comment by Tucsky** [comment]
then do 
`sudo node src/index.js`

**Comment by CalvinDKL** [comment]
dont worry, i fixed it. by Reinstalling everything.
