### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#579]
Leaderboard look weird can you please fix it and make it like vanilla

**Comment by Tucsky** [comment]
The look is probably client related

**Comment by AlexHGaming** [comment]
I'm getting this issue too.

**Comment by Megabyte918** [comment]
The leaderboard has been fixed along with the highlight added on the updates branch.

**Comment by Gigabyte918** [comment]
Really i dident see any light red color on leaderboard and what about position on bottom the leaderborad?

**Comment by Megabyte918** [comment]
@Gigabyte918 use the latest version

**Comment by Gigabyte918** [comment]
ok it worked thanks!
