### ISSUE TITLE
Please New Update!! xD

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#58]
Update!!! :v 

New Custom Gamemode similar alis.io:  spawn a player with minions!!

Fix POPSPLIT!! : Vanilla is updated and popsplit is very easy 

pop is satisfactory with similar mass or less mass

**Comment by RelTakeover** [comment]
yes

**Comment by AlexandriteErikParacelsus** [comment]
Popsplit is normal and stop making duplicate issues, we 're tired of it.

**Comment by Jhair2015** [comment]
Ok :(

**Comment by Megabyte918** [comment]
@Jhair2015 I am working on the minions spawning thing, and popsplits are already like that. They are easy and they do work with similar and less mass (although less mass is very rare)

**Comment by Jhair2015** [comment]
Ok lol, Sorry for the inconvenience
