### ISSUE TITLE
EjectedMass won't push virus 100% of the time

### ISSUE THREAD

**Issue by Tucsky** [Megabyte918/MultiOgar-Edited#581]
![2017-02-22 12 34 17](https://cloud.githubusercontent.com/assets/5738336/23209883/6db6f6da-f8fb-11e6-845a-ee0fd01786b0.gif)

I just added this piece of code to FFA.js

```
Entity.Virus.prototype.onEat = function (prey) {
    var angle = Math.atan2(prey.boostDirection.x, prey.boostDirection.y);
    this.setBoost(16 * 20, angle);
};
```

**Comment by Megabyte918** [comment]
Instead of overriding the function in FFA.js, undo those changes and modify the `onEat` function directly in Virus.js

**Comment by Tucsky** [comment]
Make sense, moved the code to virus.js.
It did not change anything at all tho. This bug seems to only happen when I W from too far but the ejectedcell obviously touch the virus, some just move around, I even increased the velocity. Maybe its a normal behavior but I had been used to something else on the server I play on (that don't run MultiOgar). 
![2017-02-23 10 59 21](https://cloud.githubusercontent.com/assets/5738336/23254445/66d13ff2-f9b8-11e6-977f-d4e4dfc2ab96.gif)

**Comment by AlexHGaming** [comment]
Remove the code from virus.js to whatever it was before.

**Comment by Tucsky** [comment]
Welp no if I do that W wont push the virus at all, which is like the opposite of what I want to do (aka virus from experimental gm)

**Comment by Megabyte918** [comment]
@Tucsky I am working on this

**Comment by Tucsky** [comment]
I switched to mobilePhysics and now is works better, but sometime when the ejected cell go through the side of the virus it don't pass the ["check eating distance" condition](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L774) and therefore go through it without be ate by the virus... (and with mobilePhysics enabled the cell just end up sliding around the virus like on the gif I posted before)

Maybe it all comes from the fact that I heavily edited my server so I'll have to try again on a fresh server to be sure
