### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#583]
![capture](https://cloud.githubusercontent.com/assets/19422415/23232302/525ffdfa-f97d-11e6-95b1-0f06251b6918.PNG)

**Comment by AlexHGaming** [comment]
I had this exact same issue before. (before update)
Download the latest version now as a massive pull request has been merged to fix every problem.

**Comment by Megabyte918** [comment]
Fixed
