### ISSUE TITLE
Dont work minion collectPellets.

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#584]

**Comment by AlexHGaming** [comment]
In gameserver.ini, make sure `CollectPellets` is set to **1** then use the script and try again by pressing 'p'

**Comment by DeadLord1337** [comment]
i know... dont work...

**Comment by AlexHGaming** [comment]
Well I am thinking this is client sided as this is a script only on real agar, not with the project sooo...

**Comment by DeadLord1337** [comment]
Real agar client... dont work wtf damn

**Comment by DeadLord1337** [comment]
I can record the video if you do not believe me)

**Comment by Megabyte918** [comment]
Fixed, the bug was caused by minions getting their visible node calculations removed.

**Comment by DeadLord1337** [comment]
CollectPallets no longer will not be?
