### ISSUE TITLE
MINIONS not appear in the LB

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#586]
title

**Comment by Luka967** [comment]
Score, visible cells & center position is not being tracked on minions to save performance.

**Comment by AlexHGaming** [comment]
@Luka967 But this project is meant to make vanilla. I think the goal is more quality, not performance, idk.

**Comment by Luka967** [comment]
We can't make the perfect vanilla, even a tiny mismatch can be resolved with code but there are too many. Also indexing visible cells for 100 minions is too much for older computers.

**Comment by Jhair2015** [comment]
@Luka967 hahahaha xdddd

**Comment by gyeyoqu** [comment]
How to return to the update with minions on the leaderboard?=

**Comment by Megabyte918** [comment]
@gyeyoqu Get rid of [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L205) line in PlayerTracker.js,
and in FFA.js, remove the `|| player.isMi` from [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gamemodes/FFA.js#L28) line.
But I must warn you, your performance will suffer greatly.
