### ISSUE TITLE
Any comments ?

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#587]
1.2.69

Connected players: 300/128
Players: 0 - Bots: 300
Server has been running for 1 minutes
Current memory usage: 28.1/50 mb
Current game mode: Free For All
Current update time: 5.809 [ms]  (perfectly smooth)

1.5.0 08-jan-17

Connected players: 300/500
Players: 0 - Bots: 300
Server has been running for 1 minutes
Current memory usage: 17.9/37 mb
Current game mode: Free For All
Current update time: 5.788 [ms]  (perfectly smooth)

megabyte - updates  ( hangs time by time, restart needed)

Connected players: 300/500
Players: 0 - Bots: 300
Server has been running for 0 minutes
Current memory usage: 11.4/31 mb
Current game mode: Free For All
Current update time: 14.734 [ms]  (perfectly smooth)

luka patch-1

Connected players: 300/500
Players: 0 - Bots: 300
Server has been running for 6 minutes
Current memory usage: 19/50 mb
Current game mode: Free For All
Current update time: 11.136 [ms]  (perfectly smooth)

***************One small player****************

1.2.69

Connected players: 301/128
Players: 1 - Bots: 300
Server has been running for 3 minutes
Current memory usage: 12.2/26 mb
Current game mode: Free For All
Current update time: 17.964 [ms]  (perfectly smooth)

1.5.0 08-01

Connected players: 301/500
Players: 1 - Bots: 300
Server has been running for 2 minutes
Current memory usage: 20.7/41 mb
Current game mode: Free For All
Current update time: 7.900 [ms]  (perfectly smooth)

megabyte - updates

Connected players: 301/500
Players: 1 - Bots: 300
Server has been running for 7 minutes
Current memory usage: 15.5/50 mb
Current game mode: Free For All
Current update time: 31.136 [ms]  (good)

luka patch-1

Connected players: 301/500
Players: 1 - Bots: 300
Server has been running for 4 minutes
Current memory usage: 11.5/24 mb
Current game mode: Free For All
Current update time: 36.857 [ms]  (tiny lag)

VM box/Deb 7 1 core 2GB  under win7 Xeon 2*2.66 8GB 

@Megabyte918

**Comment by Luka967** [comment]
lol rip my fork

**Comment by Gimmo** [comment]
@Luka967  In a real condition update time of your fork jumps from 10 upto 150ms. I think it depends of GC  .  I.e. problem located in structure of software. Also I use your bot from master fork with 1.5.0 08-01 .

**Comment by Luka967** [comment]
I've spotted GC spiking update times once in a few minutes. uws has some problem managing memory as I get 0.2 MB memory increases on a server developed entirely with that module, however GC keeps collecting it.

**Comment by AlexHGaming** [comment]
And then there's just me not knowing what that is

**Comment by Luka967** [comment]
GC is Garbage collection, a system that asks for and releases (allocates and deallocates) RAM memory for use for the application.

**Comment by Megabyte918** [comment]
@Gimmo It is an issue with the AI of the playerbots. 

In version 1.2.69, the bots do not split until a player has joined and split themselves (see [this](https://github.com/Barbosik/MultiOgar/issues/144) issue I posted), same goes for Luka's repository, but to a lesser degree. This means there are no collision/move engine calculations to be had yet, visible node/viewbox updating, etc. 

In the current version (1.6.0) bots do split on their own, without having the need for a player to join and split themselves. Which means the server has a lot more collision/move engine/viewbox/visible node updating to do, which unfortunately leads to slower update times. It is unavoidable.

Also have you edited your gameserver.ini at all before adding the bots? Were you joined to the game? I reverted my BotPlayer.js to 1.2.69 of MultiOgar's, and I got about 2.6ms on average. I then reverted those changes to version 1.6.0 of BotPlayer.js and I got around 3ms of update time.

**Comment by Gimmo** [comment]
Bot from luka-master. Bot from 1.2.69 not working - gives errors.
No any changes in config. Part 2 ->  I joined the game.


1.5.0 08-01 

Connected players: 300/500
Players: 0 - Bots: 300
Server has been running for 1 minutes
Current memory usage: 27/53 mb
Current game mode: Free For All
Current update time: 3.076 [ms]  (perfectly smooth)

megabyte - updates  

Connected players: 300/500 (bots not moves in client - just stay in place)
Players: 0 - Bots: 300
Server has been running for 0 minutes
Current memory usage: 16.6/46 mb
Current game mode: Free For All
Current update time: 23.485 [ms]  (good)


luka patch-1

Connected players: 300/500 (bots not moves in client - just stay in place)
Players: 0 - Bots: 300
Server has been running for 0 minutes
Current memory usage: 25.1/46 mb
Current game mode: Free For All
Current update time: 15.908 [ms]  (perfectly smooth)

*********plus one player - me (via agar.io)

1.5.0 08-01 

Connected players: 301/500
Players: 1 - Bots: 300
Server has been running for 2 minutes
Current memory usage: 23.3/57 mb
Current game mode: Free For All
Current update time: 9.287 [ms]  (perfectly smooth)

megabyte - updates (bots not moves in client - just stay in place)

Connected players: 301/500
Players: 1 - Bots: 300
Server has been running for 2 minutes
Current memory usage: 17.6/48 mb
Current game mode: Free For All
Current update time: 25.897 [ms]  (good)


luka patch-1 (bots not moves in client - just stay in place)

Connected players: 301/500
Players: 1 - Bots: 300
Server has been running for 1 minutes
Current memory usage: 27.5/47 mb
Current game mode: Free For All
Current update time: 24.182 [ms]  (good)

Absolute numbers can be different because of environment, strait comparison should be done.

**Comment by Megabyte918** [comment]
> Bot from luka-master. Bot from 1.2.69 not working - gives errors.

You have to edit a few things to make them compatible, the bot's mouse object should be set with the new vector,  `getSize()` should be replaced with `_size`, and on Luka's version `quadTree.any` should be replaced with `!quadTree.intersects`, as any() no longer exists in the QuadTree

Also try using version 1.6.0 rather than the updates branch, if the updates branch or 1.6.0 has THAT kind of performance with 300 bots, there is something seriously wrong with your version lol. either that or it is your internet, it can also affect update time

**Comment by Gimmo** [comment]
This numbers has meaning/sense only if you compare with another version in the same conditions/environment.

I try 1.6.0 - it's working almost the same as "updates" ( better without player / worth with player).

**Comment by Gimmo** [comment]
@Megabyte918 

1.6.0 

Connected players: 501/500
Players: 1 - Bots: 500
Server has been running for 4 minutes
Current memory usage: 17.4/52 mb
Current game mode: Free For All
**Current update time: 25.258 [ms]  (good)**

Connected players: 500/500
Players: 0 - Bots: 500
Server has been running for 2 minutes
Current memory usage: 18.3/37 mb
Current game mode: Free For All
Current update time: 9.645 [ms]  (perfectly smooth)

1.5.0 08-01

Connected players: 501/500
Players: 1 - Bots: 500
Server has been running for 1 minutes
Current memory usage: 29.7/54 mb
Current game mode: Free For All
**Current update time: 12.188 [ms]  (perfectly smooth)**

Connected players: 500/500
Players: 0 - Bots: 500
Server has been running for 0 minutes
Current memory usage: 26.6/54 mb
Current game mode: Free For All
Current update time: 7.019 [ms]  (perfectly smooth)

Different environment. You can see - collision engine works for  500 bots, but addinng 1 player gives twice more load for 1.6.0 .  Why?

I can make setup, which will show less then your 8ms, but I talk about relative, not absolue values.

**Comment by Luka967** [comment]
And here I am sitting with 0.4 ms load for every small player. Specially designed server, written from scratch.

**Comment by Gimmo** [comment]
@Luka967 
COOL!  But I just want to understand development goals and results ( measurements ). I'm sure, you, on your server, not even see any difference...

**Comment by MastaCoder** [comment]
@Gimmo YOU BET IT'S COOL. GO PLAY IT ON APRIL 2ND AT ABS0RB.ME FAM.

**Comment by Megabyte918** [comment]
I will compare performances across versions and put the results here soon

**Comment by Megabyte918** [comment]
Okay, I have finished recording the different performances for each version. These are the conditions in which I measured the performance with:

- Measurements for each version were taken after **1 minute** of the server running with 300 bots and no players connected to the server. 
- It was taken again after **3 minutes** have passed and one player had joined. 
- I have also added an "average score" section to each status command to show the difference between each version of playerbot's AI and the amount of calculations going on at the time regarding the size of the bots
- Each gameserver.ini was fresh out of the box for each version, only thing edited was `playerStartSize` which I changed to 32.

## Version 1.2.69 (Original):

**No players, 300 bots:**

Connected players: 300/128
Players: 0 - Bots: 300
Average score: 36.25
Server has been running for 1 minutes
Current memory usage: 24.9/48 mb
Current game mode: Free For All
Current update time: 4.340 [ms]  (perfectly smooth)

**1 player, 300 bots:**

Connected players: 301/128
Players: 1 - Bots: 300
Average score: 74.30
Server has been running for 3 minutes
Current memory usage: 16.1/50 mb
Current game mode: Free For All
Current update time: 7.906 [ms]  (perfectly smooth)

## Version 1.5.0 (08-01-17):

**No players, 300 bots:**

Connected players: 300/500
Players: 0 - Bots: 300
Average score: 35.02
Server has been running for 1 minutes
Current memory usage: 25/47 mb
Current game mode: Free For All
Current update time: 5.262 [ms]  (perfectly smooth)

**1 player, 300 bots:**

Connected players: 301/500
Players: 1 - Bots: 300
Average score: 101.55
Server has been running for 3 minutes
Current memory usage: 25.4/49 mb
Current game mode: Free For All
Current update time: 10.677 [ms]  (perfectly smooth)

## Version 1.6.1 (Luka's fork):

**No players, 300 bots:**

Connected players: 300/500
Players: 0 - Bots: 300
Average score: 123.10
Server has been running for 1 minutes
Current memory usage: 14.2/51 mb
Current game mode: Free For All
Current server load: 27.30%  (10.821 / 40 ms)

**1 player, 300 bots:**

Connected players: 301/500
Players: 1 - Bots: 300
Average score: 344.74
Server has been running for 3 minutes
Current memory usage: 27.2/53 mb
Current game mode: Free For All
Current server load: 33.01%  (13.203 / 40 ms)

## Version 1.6.0 (Current version):

**No players, 300 bots:**

Connected players: 300/500
Players: 0 - Bots: 300
Average score: 33.29
Server has been running for 1 minutes
Current memory usage: 28.7/48 mb
Current game mode: Free For All
Current update time: 7.901 [ms]  (perfectly smooth)

**1 player, 300 bots:**

Connected players: 301/500
Players: 1 - Bots: 300
Average score: 89.16
Server has been running for 3 minutes
Current memory usage: 18/52 mb
Current game mode: Free For All
Current update time: 10.210 [ms]  (perfectly smooth)

I have noticed, that on the current version there is a lag spike that happens after around the one minute mark. 3.5ms jumps up to greater than 7ms and does not change-- I will investigate this later.

**P.S: If you would like to add the "average score" section to your status command, here it is: http://pastebin.com/RTW8rsj4**

**Comment by Luka967** [comment]
rip my fork again xd

**Comment by Luka967** [comment]
Compared to my new server:
10 seconds after starting up
```
>bk
Full update time:   4.366606 ms
Server update time: 1.769204 ms
World update time:
  1: 1.765988 (300 players)
Socket update time: 2.597402 ms
- Connection checking:    0.013 ms
- View updating:          1.372 ms
- Packet send/Bot update: 1.211 ms
Clients:            0 real (0 pending 0 ignored 0 accepted), 300 bots
Memory usage:       13.760/46.980 MB
Download usage:     0.000 kbps
Upload usage:       0.000 kbps
>bk 1
World update time: 2.06144 ms
World update times:
- Spawning & JSON reload: 0.040 ms
- Moving updating & find: 0.000 ms (0)
- Player updating & find: 1.899 ms (307)
- Processed checks:       362 all, 0 bounce, 55 eat
- Rigid processing:       0.001 ms (Infinity µs avg)
- Eat processing:         0.119 ms (2.163 µs avg)
- Leaderboard updating:   0.177 ms
World nodes: 1543 (1543 actual), 84 branches
```

Player joins
```
>bk
Full update time:   17.563153 ms
Server update time: 6.171754 ms
World update time:
  1: 6.166493 (301 players)
Socket update time: 11.389938 ms
- Connection checking:    0.131 ms
- View updating:          7.610 ms
- Packet send/Bot update: 3.644 ms
Clients:            1 real (0 pending 0 ignored 1 accepted), 300 bots
Memory usage:       16.530/52.980 MB
Download usage:     13.192 kbps
Upload usage:       76.280 kbps
>bk 1
World update time: 3.532269 ms
World update times:
- Spawning & JSON reload: 0.030 ms
- Moving updating & find: 0.000 ms (0)
- Player updating & find: 3.098 ms (557)
- Processed checks:       891 all, 164 bounce, 168 eat
- Rigid processing:       0.174 ms (1.062 µs avg)
- Eat processing:         0.227 ms (1.352 µs avg)
- Leaderboard updating:   0.177 ms
World nodes: 1786 (1786 actual), 84 branches
```
1st place bot had 4500 score

3 minutes later
```
>bk
Full update time:   13.103908 ms
Server update time: 5.419535 ms
World update time:
  1: 5.414859 (301 players)
Socket update time: 7.684081 ms
- Connection checking:    0.108 ms
- View updating:          5.620 ms
- Packet send/Bot update: 1.952 ms
Clients:            1 real (0 pending 0 ignored 1 accepted), 300 bots
Memory usage:       20.108/56.980 MB
Download usage:     13.200 kbps
Upload usage:       161.197 kbps
>bk 1
World update time: 5.222568 ms
World update times:
- Spawning & JSON reload: 0.036 ms
- Moving updating & find: 0.000 ms (0)
- Player updating & find: 4.434 ms (610)
- Processed checks:       1079 all, 214 bounce, 229 eat
- Rigid processing:       0.406 ms (1.895 µs avg)
- Eat processing:         0.342 ms (1.492 µs avg)
- Leaderboard updating:   0.269 ms
World nodes: 1841 (1841 actual), 80 branches
```
1st place bot had 29000 score

**Comment by MastaCoder** [comment]
@Megabyte918 is there anything to sacrifice from CPU to RAM? 50MB of ram is very very little judging about how much work the CPU ends up doing most of the time, and that's all on 1 core. (Since Node.js stuff)

ClosedAgar managed to put a lot of the work into the RAM, such as sqrt calculations. (@Luka967 told me we can't really use what they use since small amounts of mass require decimal calculations.) We should try to focus on making M-ED much more efficient in it's RAM usage. Most cheap VPSes come with 512mb of RAM and 1 vCPU core. ;-;

**Comment by Luka967** [comment]
26 minutes later (not playing)
```
>bk
Full update time:   8.228517 ms
Server update time: 3.117584 ms
World update time:
  1: 3.115247 (301 players)
Socket update time: 5.110057 ms
- Connection checking:    0.065 ms
- View updating:          2.728 ms
- Packet send/Bot update: 2.315 ms
Clients:            1 real (0 pending 0 ignored 1 accepted), 300 bots
Memory usage:       21.772/55.980 MB
Download usage:     13.219 kbps
Upload usage:       3171.665 kbps
>bk 1
World update time: 3.178954 ms
World update times:
- Spawning & JSON reload: 0.158 ms
- Moving updating & find: 0.000 ms (0)
- Player updating & find: 2.143 ms (553)
- Processed checks:       2274 all, 448 bounce, 1266 eat
- Rigid processing:       0.290 ms (0.648 µs avg)
- Eat processing:         0.586 ms (0.463 µs avg)
- Leaderboard updating:   0.183 ms
World nodes: 1727 (1727 actual), 80 branches
```

**Comment by Megabyte918** [comment]
@Luka967 Heyy, that's pretty good 👍 
@MastaCoder Using RAM for sqrt calculations sounds like it would be the best option for now, unless there is something that takes up more usage than the move/collision engine that we don't know about

**Comment by MastaCoder** [comment]
@Megabyte918 At lower mass, aren't the sqrt's with decimals?

**Comment by Megabyte918** [comment]
@MastaCoder It doesn't have to be, some values can be floored so that there are no remaining decimals without consequences.

**Comment by Gimmo** [comment]
https://jsperf.com/sin-cos-vs-sqrt/3

**Comment by MastaCoder** [comment]
@Megabyte918 Whatever that works 👍  Good luck!

**Comment by Gimmo** [comment]
Now I have almost the same results for latest 1.6.0 and 1.5.0, difference mostly in experiment errors limits. 
Closed.... 
Thanx for your help.
