### ISSUE TITLE
 These are the real splits of agar.io

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#588]
I have been watching and I have noticed that between agar.io and gota.io, they have things in common like:

- the cells blink when giving 16 spaces fast
- in both come the same tricks

See the video in the minute 6:03 when the player give the 16 splits

https://www.youtube.com/watch?v=DF3LH3AQZtk

**Comment by Megabyte918** [comment]
This also happens in the current version. You just need a fast enough macro for it

**Comment by AlexHGaming** [comment]
@Megabyte918 Is this client sided?

**Comment by Luka967** [comment]
Yes

**Comment by AlexHGaming** [comment]
@Luka967 Well, it's both kinda

**Comment by Luka967** [comment]
Yes

**Comment by Luka967** [comment]
xD
