### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#589]
Hey! so there is another server like multiogar that someone went of and made, i cant remember what its called.
Ogar something, not ogar unlimited.

Anyone know?
thanks

**Comment by AlexHGaming** [comment]
Ogar project?

**Comment by CalvinDKL** [comment]
No, another one.

**Comment by CalvinDKL** [comment]
IT has a bunch of extra features, uhh. I cant remember!

**Comment by Tyler3D** [comment]
OpenAgar? My version?

**Comment by Tyler3D** [comment]
@CalvinDKL

**Comment by MastaCoder** [comment]
OgarPlus?

**Comment by Jhair2015** [comment]
OgarServ?

**Comment by CalvinDKL** [comment]
YES! Open agar!

**Comment by Luka967** [comment]
lol

**Comment by MastaCoder** [comment]
@CalvinDKL ew

**Comment by AlexHGaming** [comment]
ewww ffs
