### ISSUE TITLE
Why do we change colors while clicking Q REmove it and E AND R T ALREADY ADDED its annoying 

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#59]
fix

**Comment by firelightning13** [comment]
why not?

**Comment by systemroot** [comment]
No. How can we know which are we control if color don't change.

**Comment by ZfsrGhS953** [comment]
Not everyone installs the userscript to control bots.

**Comment by Megabyte918** [comment]
@NameYT #7 

> Q controls function differently: Due to recent protocol changes and updates in Agar.io, adding letters to your name with the Q key no longer works. We had to settle with color change instead. (see "How to use?")

**Comment by NameYT** [comment]
@Megabyte918 I USE THE SCRIPT E R T BUT STILL :( MAKE MY COLORS ded

**Comment by Megabyte918** [comment]
@NameYT if you don't want the cell to change color, go to PacketHandler.js and remove lines 155-158 and 163-165.
