### ISSUE TITLE
Fix?

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#591]
![image](https://cloud.githubusercontent.com/assets/18153674/23326500/2d69ebb4-facc-11e6-84fd-fcc9d599ff89.png)

**Comment by Tyler3D** [comment]
Just add
`var figlet = require('figlet');`
To the top of your index.js

**Comment by Tyler3D** [comment]
@Jhair2015

**Comment by Megabyte918** [comment]
@Tyler3D Fixed this in a recent PR, thank you :)

**Comment by Jhair2015** [comment]
@Tyler3D Thanks, I was out of line xD, sorry for the delay in responding, and also Thanks again @Megabyte918

**Comment by Tyler3D** [comment]
@Megabyte918 Your Welcome :)
@Jhair2015 lol

**Comment by FantasyIsBae** [comment]
Shit sorry , 
forgot about that lol

**Comment by Jhair2015** [comment]
@FantasyIsBae No problem lol
