### ISSUE TITLE
Making Serverwelcome messages HTML

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#594]
hey! So the title says it, maybe it would be cool if that was possible, like:

` serverWelcome2: 'Follow AgarUp.us on <a href="example.com">Twitter!</a>'`
i know its possible, but does anyone know how to do it?

**Comment by Luka967** [comment]
Possible only on client-side.

**Comment by CalvinDKL** [comment]
ahh ok, because i tried like this `var Twitter = '<a href="http://agarup.us/">Twitter!</a>'`
`serverWelcome2: 'Follow AgarUp.us on ' + Twitter`

**Comment by CalvinDKL** [comment]
But how would i put a <a> tag around something that isnt even in the client code?

**Comment by AlexHGaming** [comment]
isn't MultiOgar-Edited Javascript?
And this is client ided as writing messages on a client doesn't relate to the project.

**Comment by Megabyte918** [comment]
@CalvinDKL Something like that you would not modify in gameserver.ini, try doing that in PacketHandler.js where `serverWelcome2` is actually used

**Comment by MastaCoder** [comment]
@CalvinDKL It's called in a canvas, if tags like that were allowed, someone could just send <h1>HELLO</h1> and it'd break everything :) 

From what I remember, Agar.io when it was released allowed HTML characters in the canvas for the leaderboard, so people screwed with it. After that it was fixed.
