### ISSUE TITLE
Out of Topic, I need someone's help please!

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#595]
- I know this is off topic, I will close it if there is no answer or if MegaByte asks me to do it, I will do it instantly.

Does anyone know how to get a minimap server, like the alis?

For example, NBK.IO has its own ip which is something like * 149.xxx.xxx.xxx: XXXXX *

And there's something like that: minimap.xxxx: xxxx

I would like to know if anyone knows some fork or knows about it, please that I could send the link, I would appreciate it a lot :)

**Comment by Tyler3D** [comment]
@Jhair2015 Alis.io has a minimap on their client and has no scamble

**Comment by Jhair2015** [comment]
@Tyler3D If I know, I would like to know if someone has knowledge of some fork which allows to put their own * ip * of chat / minimap, I do not know if they understand me xd

**Comment by Tyler3D** [comment]
You mean have the chat and minimap on a different server then the main game one?

**Comment by Jhair2015** [comment]
@Tyler3D No

me refiero a esta parte en el codigo que hay en alis y nbk, y en micliente, quiero tener uno propio

Ejemplo:

> function Connection() {
    var msg;
    var self = this;
    self.setCurrentServer = function() {//self.connect = function() {
        socket = io("Here IP", {  //socket = io("xample", { // IP del chat/minimapa
            transports: ["websocket"]
        });
        socket.on("updateCoords", function(walkers) {
            minimap.updateNode(walkers);
        });
        socket.on("receiveMessage", function(data) {
            chatRoom.receiveMessage(data.sender, data.msg);
        });
    };

**Comment by Tyler3D** [comment]
xD I can barely read spanish. I only got Example from that

**Comment by Jhair2015** [comment]
Lol, I forgot to activate the translator hahaha xDD

**Comment by Tyler3D** [comment]
lol

**Comment by Jhair2015** [comment]
ready, i edited xd

**Comment by Tyler3D** [comment]
idk what nbk.io and alis.io have seperate IP's for minimap/chat and the game Server

**Comment by Tyler3D** [comment]
Also, you cannot select what IP you want to server to be hosted on. The best you can do is get to hostname

**Comment by Jhair2015** [comment]
I know xD, but I wonder if there will be a post in github or something that allows us to have our own server lol

That's why I opened this, well I proceed with the close of this

**Comment by Tyler3D** [comment]
ok

**Comment by Jhair2015** [comment]
Ok lol
