### ISSUE TITLE
Auto Restart ?

### ISSUE THREAD

**Issue by adib696** [Megabyte918/MultiOgar-Edited#596]

**Comment by Luka967** [comment]
Search for the duplicate issues before you ask a question.
@Megabyte918 close

**Comment by AlexHGaming** [comment]
I wish I could've closed it

**Comment by AlexHGaming** [comment]
Duplicates of #596 #527 #447 #458 #266 #141 #146 and #243
Please search before making an issue. Please read the rules of issues [here](https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template)

**Comment by Luka967** [comment]
holy shit thats a lot of duplicates

**Comment by AlexandriteErikParacelsus** [comment]
123.................... closed

buh bye

**Comment by MastaCoder** [comment]
ooo sassy

**Comment by AlexandriteErikParacelsus** [comment]
am i roight??

**Comment by MastaCoder** [comment]
:trollface:

**Comment by Luka967** [comment]
:1st_place_medal: goes to @AlexandriteErikParacelsus for excellent moderation
