### ISSUE TITLE
How to get this without doing it myself xD?

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#597]
![image](https://cloud.githubusercontent.com/assets/18153674/23333701/113bc452-fb5e-11e6-87b8-dc6ae55f096b.png)

HOW?

**Comment by ItzLevvie** [comment]
It's figlet

**Comment by Jhair2015** [comment]
@ItzLevvie  Thanks, 

i close it

**Comment by AlexHGaming** [comment]
Wow I was just writing a long fuckin paragraph how to change it lmao
jk
@ItzLevvie

**Comment by Jhair2015** [comment]
@AlexHGaming None of that, I want to add that message to my client xD
