### ISSUE TITLE
Thanks MegaByte!! :) for minions :D

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#6]

**Comment by Fantasy-Agario** [comment]
Yh it took  a while for us (mainly Megabyte) to make it :D

**Comment by Jhair2015** [comment]
Yes :)))) is there any way to donate something? : D

**Comment by Fantasy-Agario** [comment]
Ask @Megabyte918 he should kno

**Comment by Megabyte918** [comment]
@Jhair2015 No problem man :), and I don't want anyone to donate to me, I added these minions just because it seemed like it'd be a fun project to do, and it was =D

**Comment by Jhair2015** [comment]
Thaks :)
