### ISSUE TITLE
Popsplit Doesn't work!

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#60]
Fix

**Comment by Jhair2015** [comment]
@NameYT  That if they work, even I have popsplit popup with 22 000 mass, MegaByte is already tired of these Dupicados, He is the one who decides if there is any failure in popsplit and will be corrected ....

**Comment by Megabyte918** [comment]
@NameYT can you explain? they work perfectly for me

**Comment by NameYT** [comment]
@Megabyte918 How to get popsplit with anymass? example : POPSPLITTING 15k mass (opponent) me 12k

**Comment by Megabyte918** [comment]
@NameYT just do it regularly, it DOES work just not as often as normal popsplits (mass to half of mass).

**Comment by NameYT** [comment]
@Megabyte918 I remember u sent something in the popsplit on the multiogar original

**Comment by NameYT** [comment]
Updated fix:

1.) Add this small fix into GameServer.js (thx @NatsuTheGreat) from this commit here: 6b23cea

2.) Change the size multiplier located here, change the "1.15" to "1.10"

3.) Edit the splitMass variable for virus explosions here, change the "2" to "2.5".

4.) Change the first value of the normalized distance, change "32" here, to "64"

5.) Change the playerSpeed value in config.ini to "0.5" (so it balances out the speed with the normalized distance)

And there you have it! Works with any speed, same size any mass, double, triple, quadruple, double same size, triple same size, quadruple same size, long distance, extremely long distance, long distance same size, you name it, all with vanilla success rate :). Also fixes cells flying through other cells, and the rate of which the cells switch order when doublesplitting to vanilla aswell.

Here's some of the ones I did:
popsplit1
popsplit2
popsplit3

**Comment by NameYT** [comment]
@Megabyte918 Look at

**Comment by NameYT** [comment]
@Megabyte918 look at dat

**Comment by Megabyte918** [comment]
@NameYT you do not need to do that anymore the fixes are outdated and are not nessecary.

**Comment by NameYT** [comment]
@Megabyte918 im doing it on the oruiginal mutliu ogar

**Comment by Megabyte918** [comment]
@NameYT Well it should work then. I've told you how to get 100% working popsplits many times, but you failed to follow my instructions. You've made 5 issues about popsplits, i'm tired of it. Any other issues regarding popsplits I will close, any comments about it I will not respond to. You should know by now. If its that difficult for you, get someone else to do it. I've spoonfed you as much as I can, even to the point where I spent 10 minutes of my time making a video explaining how to do it, just for you to still not follow the directions and make more issues/comments . I'm not doing it any more. If you need any more proof that popsplits work, check these out. 

https://streamable.com/6152
https://streamable.com/8exi
https://streamable.com/xt4q
https://streamable.com/at7h
https://streamable.com/xrak
https://streamable.com/szg0
https://streamable.com/8iln
https://streamable.com/9htx
https://streamable.com/1dzl
https://streamable.com/ewq3
https://streamable.com/q8x0
https://streamable.com/6tn0
