### ISSUE TITLE
how to setup servers on ubunto ?

### ISSUE THREAD

**Issue by Y4ssine** [Megabyte918/MultiOgar-Edited#601]
i have many srvers on a digital ocean account how do i setup nodejs and stuff cus i'm not familiar with linux :)

**Comment by AlexHGaming** [comment]
On linux you can do
`sudo apt-get install nodejs-legacy npm` to install.
Install git by doing `sudo apt-get install git`
Get packages by doing `sudo apt-get update`
If you're making a server do `git clone git://github.com/Megabyte918/MultiOgar-Edited.git`
Are those the answers to your questions?

**Comment by Y4ssine** [comment]
thanks @AlexHGaming  i alreasdy did it just by searching into youtube 
i rent 3 ubuntu servers rn :D

**Comment by AlexHGaming** [comment]
no problem dude

**Comment by Y4ssine** [comment]
@AlexHGaming  i have a prob with my site ! 
minimap + chat + skins not working ?

**Comment by AlexHGaming** [comment]
Did you reinstall the server?

**Comment by Y4ssine** [comment]
how i don't understand?

**Comment by Y4ssine** [comment]
i just copied codes from another site

**Comment by AlexHGaming** [comment]
What are you using to host your server?

**Comment by Y4ssine** [comment]
hmmm digitalocean

**Comment by Y4ssine** [comment]
the server is working well
but minimap chat and stuff arn't

**Comment by Y4ssine** [comment]
@AlexHGaming  can you walk me through please?

**Comment by AlexHGaming** [comment]
Can't help you there, I can use Codeanywhere, but not digital ocean, ask @MastaCoder
on this repo we don't support client sided features we are just about fixing the server that makes it run with the physics.
On vanilla agar there's no minimap or chat, skins were removed out of private servers a year ago.
If you really want skins then go on the cell.sh client.

**Comment by Y4ssine** [comment]
ok thank you but what if i want to install an older version of multiogar edited?

**Comment by AlexHGaming** [comment]
Not sure

**Comment by MastaCoder** [comment]
Installation is written on the front page. Install the version of Node.js depending on your version of Ubuntu, you'd need to Google this part.

Then follow the instructions listed in the README.md.
