### ISSUE TITLE
How to make a larger map?

### ISSUE THREAD

**Issue by AgarXTRA** [Megabyte918/MultiOgar-Edited#602]
The current map is too small so I wonder how to make the map larger? Because I have very many players in my server so it becomes easy crowded...

**Comment by ItzLevvie** [comment]
You can change it here: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L86-L87

**Comment by AgarXTRA** [comment]
What is the calculation if I want a 50% larger map? ^^

**Comment by AlexHGaming** [comment]
basically half 14142 (7071) then add it on.
14142 + 7071 = 21213.

**Comment by Luka967** [comment]
^^

**Comment by AlexHGaming** [comment]
sup

**Comment by Luka967** [comment]
the ceiling

**Comment by AlexHGaming** [comment]
var ceiling = Sup
var literal = Luka
ceiling literal
Did I say it right?

**Comment by AgarXTRA** [comment]
What map size ''party'' server using?

**Comment by AlexHGaming** [comment]
14142x14142

**Comment by AgarXTRA** [comment]
Really It feels bigger size

**Comment by AgarXTRA** [comment]
@ItzLevvie Add this new skins to ''randomskins'': [palm_tree
samba
mountain
trickster
bird_mask
golden_mask
icon
soloist
diva
metal_face
performer
songsmith](url)

**Comment by AgarXTRA** [comment]
@ItzLevvie Update ''randomskins''

`palm_tree
samba
mountain
trickster
bird_mask
golden_mask
icon
soloist
diva
metal_face
performer
songsmith`

**Comment by ItzLevvie** [comment]
Added on https://github.com/Megabyte918/MultiOgar-Edited/pull/605/commits/7ea9d01a077b06fcad02810617ee081bb1a64351 @AgarXTRA
