### ISSUE TITLE
how do i install an older version of multiogaredited ?

### ISSUE THREAD

**Issue by Y4ssine** [Megabyte918/MultiOgar-Edited#604]
hmm i think version 1.3 or somethink like that was much better how do i download it back ?

**Comment by Tucsky** [comment]
git reset 936c8004811ec32fa23a3068f62b262f65a90fe0

**Comment by Y4ssine** [comment]
i don't get it :c

**Comment by Y4ssine** [comment]
what shall i do

**Comment by ItzLevvie** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/archive/936c8004811ec32fa23a3068f62b262f65a90fe0.zip

**Comment by AgarXTRA** [comment]
Lol. @Y4ssine I can not in any way see that older versions would be better than 1.6.0..

**Comment by Luka967** [comment]
@AgarXTRA The only good one is 1.5.0

**Comment by Y4ssine** [comment]
no the split suck at 1.6 seriously 
but 
@ItzLevvie i'm using ubuntu
how can i do the 
git clone git://github.com/Megabyte918/MultiOgar-Edited.git ?
and just install v 1.3 ?

**Comment by ItzLevvie** [comment]
```
wget https://github.com/Megabyte918/MultiOgar-Edited/archive/936c8004811ec32fa23a3068f62b262f65a90fe0.zip
tar -xzf 936c8004811ec32fa23a3068f62b262f65a90fe0.zip && rm -rf 936c8004811ec32fa23a3068f62b262f65a90fe0.zip
```

**Comment by Y4ssine** [comment]
![image](https://cloud.githubusercontent.com/assets/25416932/23340346/ffaea146-fc4d-11e6-8dd2-4aa2ad5255dd.png)

can i give u my server to set it up for me :face_with_head_bandage:

**Comment by ItzLevvie** [comment]
https://github.com/JaraLowell/OgarServ/issues/172#issuecomment-279242778

**Comment by ItzLevvie** [comment]
@Y4ssine https://github.com/JaraLowell/OgarServ/issues/172#issuecomment-279242778
