### ISSUE TITLE
Bug in Leaderboard

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#606]
when i set the maxlb in config this happens when show my position
![image](https://cloud.githubusercontent.com/assets/17459204/23340431/00cde2a8-fc58-11e6-8013-210f8e879714.png)

**Comment by AlexHGaming** [comment]
client sided

**Comment by Gigabyte918** [comment]
i dont think so

**Comment by Megabyte918** [comment]
It is server sided, I will work on this

**Comment by Gigabyte918** [comment]
ok :)

**Comment by Luka967** [comment]
confused yet again

**Comment by Megabyte918** [comment]
@Luka967 Me too
@Gigabyte918 I'm thinking this might be client related, the server should automatically adjust and display the position of the player regardless if they are on the leaderboard or not or how long the leaderboard is. From what I've seen, there is nothing wrong with anything regarding the leaderboard code in FFA.js, UpdateLeaderboard, LeaderboardPosition, etc. They should all be displaying the position regardless. Maybe the agario client only supports the position for a leaderboard with 10 elements?

**Comment by Gigabyte918** [comment]
are you sure? if yes then ill close this issue!

**Comment by Megabyte918** [comment]
Yes I am pretty sure it is client sided, if it weren't for the limitation then it would work with different leaderboard lengths
