### ISSUE TITLE
buy game like alis.io

### ISSUE THREAD

**Issue by Osher12** [Megabyte918/MultiOgar-Edited#607]
hello i search buy alis.io game
20usd not more. is only decrypt the script

**Comment by Jhair2015** [comment]
@Osher12 I have a similar game to Open Source, do you want it?

**Comment by MastaCoder** [comment]
> 20usd not more. is only decrypt the script

1. That's illegal.
2. You can do this easily with some sort of beautifier and a little bit of cleaning up.
3. That's illegal.
4. Why don't you just work and make it yourself instead of taking other peoples hard work.
5. That's illegal.

**Comment by AlexHGaming** [comment]
How to make an alis.io game:
1. Learn coding.
2. Learn coding.
3. Make your game.

**Comment by Jhair2015** [comment]
xd hahaha

**Comment by Osher12** [comment]
@Jhair2015 i send you msg on discord join !

**Comment by Y4ssine** [comment]
@Jhair2015  can you pleasegive me that game which is similar to alis.io :D ?

**Comment by Jhair2015** [comment]
@Y4ssine Not free sorry, @Osher12 I already spoke to you in discord right now

**Comment by AlexHGaming** [comment]
k

**Comment by Y4ssine** [comment]
i'll pay 5 usd that's what i can afford ;_;

**Comment by Y4ssine** [comment]
jhair can i have ur discord ?

**Comment by Jhair2015** [comment]
@Y4ssine Ok

**Comment by MastaCoder** [comment]
@Megabyte918 close.

**Comment by Luka967** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Jhair2015** [comment]
yes, close!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Osher12** [comment]
@Jhair2015 send msg on discord

**Comment by Y4ssine** [comment]
@Jhair2015  what's your discord !

**Comment by Jhair2015** [comment]
@Y4ssine https://discord.gg/rMYsJjF @Osher12
