### ISSUE TITLE
Design like agarup.us , alis.io

### ISSUE THREAD

**Issue by Osher12** [Megabyte918/MultiOgar-Edited#608]
hello so i search design like alis.io agarup.us i dont want copy from people so if somone have is good for me :)

**Comment by MastaCoder** [comment]
STOP.
POSTING.
DUPLICATES.
OF.
THE.
SAME.
ISSUE.
(THIS.
IS
CLIENT.
RELATED.)

**Comment by Megabyte918** [comment]
@Osher12 If you post any more duplicate issues about this topic, you will be temp banned. This is client related therefore we cannot help you. End of story.
