### ISSUE TITLE
How to make a connection directly?

### ISSUE THREAD

**Issue by Crypton918** [Megabyte918/MultiOgar-Edited#609]
Anyone want to you see your own skin. but Config-web.miniclip are blocked them.
so. im want to ask if megabyte o other people can make a connection directly.
For example. why when in your console of agar.io put some like to this
MC.showLevelUp (100,99,100)
u get skin of veteran. that no are a connection directly of agar.io?
Can you please explain me how that work of connection. plz

**Comment by Jhair2015** [comment]
Client...

**Comment by Crypton918** [comment]
@Jhair2015 Kyc peruano :v:v:v:v:v:v:v

**Comment by Megabyte918** [comment]
@Jhair2015 Is right, and even if there was a way (which I doubt there is, miniclip blocked them for a reason) It would have been done a long time ago.

**Comment by Jhair2015** [comment]
@Megabyte918 exact

**Comment by Crypton918** [comment]
@Jhair2015  Klo por tu culpa cerraron :V

**Comment by Jhair2015** [comment]
@Crypton918 :'v
