### ISSUE TITLE
Hidden skins aren't working

### ISSUE THREAD

**Issue by Unai144** [Megabyte918/MultiOgar-Edited#610]
Hi,
I'm trying to put skins like this: **< kraken >name** [with no spaces] to hide the skin name and with MultiOgar Edited doesn't work (the skin doesn't appear) and it works with the MultiOgar original version. 
Happens the same in different clients (tried on Cigar client, ogarul,...)
Can't understand why.
Thanks

**Comment by Gigabyte918** [comment]
dude Miniclip has patched the skins you cant able to see skin but other peoples can see without <kraken> on your name Now Close?

**Comment by Unai144** [comment]
@Gigabyte918 Yes, other people can see the skins: http://prntscr.com/edzv7a with < 8ch > in this case, but only it appears in one cell I can't understand why I cannot see my own skin, that can be fixed?
Thanks

**Comment by AlexHGaming** [comment]
client sided.
And to get official skins such as doge and wojak whatever, just type them in on their own, it's just skins from the shop that don't work,
Please close as this is client sided, and has nothing to do with the project.

**Comment by AgarXTRA** [comment]
I use same extension as ''Raga.pw'' for my server and skins works very good. U can see ur own skin and other can see yours without any problems :) I talking ofc about the original Agar.io client

**Comment by Gigabyte918** [comment]
@AgarXTRA Can you send that extension so i can play with skins

**Comment by AgarXTRA** [comment]
@Gigabyte918 Sure. If you give me your e-mail

**Comment by Jhair2015** [comment]
@Gigabyte918 http://www.agarxtra.pw/

**Comment by Megabyte918** [comment]
@Unai144 Please search if your issue has already been posted before making an issue. There have been many duplicates of this issue.
