### ISSUE TITLE
LMS bug

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#611]
Whenever starting LMS with AI bots, when killing them all, then close the LMS, they don't respawn back. Fix?

**Comment by Megabyte918** [comment]
Use the addbot command to add the bots back.

**Comment by AlexHGaming** [comment]
@Megabyte918 But can you make the feature so we don't have to do that? It'd be a good idea

**Comment by Megabyte918** [comment]
@AlexHGaming It is an issue with the BotPlayer.js file you are using, in the current version the bug you are describing does not happen, and the bots do indeed respawn. 
You can either revert the `checkConnection` function in your BotPlayer to the current one, 
Or, you can just do `ab [amount]` in the console real quick lol, surely that's not too much of a hassle?

**Comment by AlexHGaming** [comment]
@Megabyte918 Oh ok, lol, I'm running on 1.5.0 atm because I had fixed the doublesplit cell switch, as it used the (c) function
In the current version now, it's (m) and it uses cell and check, not cell.1 position yadda yadda yadda
Thanks for answering lol
