### ISSUE TITLE
Found Cool Thing!

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#612]
When you hit play then you hit escape then remove the nick and type new nick you will get new nick but leaderboard doesnt change the name on it!

**Comment by AlexHGaming** [comment]
Vanilla behaves the same. You can't change your name while you're alive in the first place.

**Comment by Luka967** [comment]
Client-sided feature

**Comment by Megabyte918** [comment]
^^
