### ISSUE TITLE
Auth packets

### ISSUE THREAD

**Issue by AdaptCharm** [Megabyte918/MultiOgar-Edited#614]
Does anyone have the auth packets for protocol version 5?

**Comment by Tyler3D** [comment]
@AdaptCharm Check out https://github.com/issy123/agario-protocol/blob/master/protocol-v2.1.5.md
I'm pretty sure the auth packets would be the same, because miniclip whet crazy about changes in protocol 6.

**Comment by Luka967** [comment]
FE 05 00 00 00
FF 01 00 00 00
