### ISSUE TITLE
Update for Ogarclient

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#615]
@Megabyte918  YOU CAN MAKE THIS UPDATE TO SUPPORT UNICODE?

https://github.com/JaraLowell/OgarServ/commit/61e716272c8c5303bdda622483bdbd62d88aba0b

**Comment by AlexHGaming** [comment]
No. We don't support clients.

**Comment by Tyler3D** [comment]
Ummm ask @JaraLowell Not @Megabyte918

**Comment by MastaCoder** [comment]
@Tyler3D he means make M-ED support Unicode.

Short Answer: No.
Long Answer: No we support official client.

**Comment by Luka967** [comment]
@MastaCoder He's using my protocol 6 client and wants to replace strings unicode -.-'

**Comment by JaraLowell** [comment]
Do not ask @JaraLowell >.< go ask @Tyler3D 

And actually agar.io supports Unicode names :3 (Emoji)

**Comment by gyeyoqu** [comment]
jaralowell rekt all ass

**Comment by MastaCoder** [comment]
what? lmao

**Comment by Megabyte918** [comment]
@gyeyoqu Duplicate of #530, and if you want unicode add the code from @JaraLowell's updates.
