### ISSUE TITLE
Adblock 

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#616]
@Megabyte918  if the player have adblock , this name will be "Dont use ADBLOCK"

**Comment by AlexHGaming** [comment]
This is the dumbest thing I've ever seen.
1. This is client sided.
2. What's the point? If he's not getting paid for an open-source project, what actually is the point of automatically renaming?
3. Even if he wanted to do this, he couldn't, as MultiOgar-Edited doesn't detect things other than badwords but can't detect if someone's using adblock.

**Comment by ZfsrGhS953** [comment]
4. The name "Dont use ADBLOCK" is 16 characters long, which is more than the default 15 character limit.

**Comment by Luka967** [comment]
lol rip

**Comment by Jhair2015** [comment]
hahahaha
