### ISSUE TITLE
Question about virus reaction

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#617]
How do you edit the reaction when a cell hits the entity virus? Like when you hit it, it'll explode you 2 seconds after been hit. Or even longer?
I want to know how to do this, might be a retarded thing to ask, but I want to know, thanks.

**Comment by Tyler3D** [comment]
@AlexHGaming Add a "setTimeout" before the main splitting action

**Comment by Tyler3D** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js#L37
Add:
setTimeout(function(){}, 2000); // 2000 is 2 seconds you have multiply the number of seconds by 1000.

**Comment by AlexHGaming** [comment]
ta

**Comment by Gigabyte918** [comment]
close?

**Comment by AlexHGaming** [comment]
I added it as a function, but how to actually add it?

**Comment by Megabyte918** [comment]
What do you mean?

**Comment by Jhair2015** [comment]
@Megabyte918 I think it means to make a pull request and upload that lol

**Comment by AlexHGaming** [comment]
No, like, ugh, DM's @Megabyte918
