### ISSUE TITLE
Leader of the server show position

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#619]
The player with the most mass will be recognized on the map and will indicate the position of him, as in diepio or space.

**Comment by Jhair2015** [comment]
Client

**Comment by Luka967** [comment]
Yet again client

**Comment by MastaCoder** [comment]
I choose you @AlexandriteErikParacelsus!

Use close issue!

**Comment by Megabyte918** [comment]
@gyeyoqu When you make an issue, I want you to please consider whether it is a duplicate or a client sided issue first. Almost every one of your 22 issues you've made has been either a duplicate, client sided, or an issue that could have easily been resolved if you would have searched around for it in other issues. Please, I **REALLY** don't want to have to start temporarily banning people for things like this, just please do your research before making an issue and I won't have to do it :/
