### ISSUE TITLE
When are you gonna add Pellet Mode? /QUESTION/

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#62]
When?

**Comment by Tyler3D** [comment]
Duplicate of #8 #43 #45 And a bunch more

> Alright, since people are requesting it I guess I could start working on it, but I'm very busy right now. Still have a lot of features and bugs to fix so it might not be for a while until its implemented.

**Comment by Tyler3D** [comment]
@NameYT
