### ISSUE TITLE
special people ?

### ISSUE THREAD

**Issue by Y4ssine** [Megabyte918/MultiOgar-Edited#620]
#What if i want to add a verfication badge or something near certian ppl ?
![capture](https://cloud.githubusercontent.com/assets/25416932/23452483/4f022dc2-fe19-11e6-9849-dfcc13428069.PNG)
something that is like this i know it sounds retarded but i just want to know

**Comment by Luka967** [comment]
Client-sideeeeeeeeeeeeeeed

**Comment by AlexHGaming** [comment]
Client sideddddddddddddddd
@AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus

**Comment by Jhair2015** [comment]
I invoke you @AlexandriteErikParacelsus  xD

**Comment by Luka967** [comment]
```c#
User user = World.GetUser("AlexandriteErikParacelsus");
user.Invoke((Action)delegate() {
    user.closeIssue("620");
};
```

**Comment by Jhair2015** [comment]
XDDDD

**Comment by Megabyte918** [comment]
@Y4ssine Refer to #187, you can do something like that, and instead of changing the skin to null and name to "Hi there!", you can do something like this: `name += 'insert text'`. This means any player with the specified user role will have that text after their names. Anything other than this method is most likely client sided.

**Comment by Y4ssine** [comment]
@Megabyte918  good but what if i just want to add an image ! 
i'm not good with JS can u walk me through that ?

**Comment by Megabyte918** [comment]
@Y4ssine Images would be client sided
