### ISSUE TITLE
Where can I find developers for a Agar.io-related project? (Not an issue)

### ISSUE THREAD

**Issue by AgarXTRA** [Megabyte918/MultiOgar-Edited#621]
First... sorry for posting this here, but I really dont know anywhere else to ask this question.

I have a very good idea that is Agar.io-related and I need developers who can make the project a reality. Where can I find talented guys who do this in exchange of money? My budget for this project is $3000-3500 +/- $500.

Maybe you're the one I'm looking for? Or perhaps you know someone else?

Anyway, please contact me on Skype / e-mail if you can bring something.

Please dont close this post (at least for a few days)

Skype: josef.shaat / e-mail josefshaat@gmail.com

**Comment by AlexHGaming** [comment]
First, we only talk about issues with the project
Second, follow the first rule
Third, follow the second rule

**Comment by Gigabyte918** [comment]
Not Project Related

**Comment by AlexHGaming** [comment]
^^

**Comment by Luka967** [comment]
Fourth, read @AlexHGaming's comment
Fifth, https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template#before-an-issue-is-made-submitted-make-sure

**Comment by AlexHGaming** [comment]
That's a long ass link

**Comment by Luka967** [comment]
no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface: no shit :trollface:

**Comment by MastaCoder** [comment]
> Please dont close this post (at least for a few days)

**Comment by Luka967** [comment]
:trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface:trollface::trollface:

**Comment by Luka967** [comment]
lol rip

**Comment by Jhair2015** [comment]
@RasyiidWho ":trollface:" :trollface:

**Comment by Jhair2015** [comment]
lol is :troll-face:   Delete "-"

**Comment by Luka967** [comment]
`:trollface:`

**Comment by ItzLevvie** [comment]
:trollface:

**Comment by ItzLevvie** [comment]
:taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco: :taco:

**Comment by Gigabyte918** [comment]
https://assets-cdn.github.com/images/icons/emoji/trollface.png

**Comment by Gigabyte918** [comment]
![image](https://assets-cdn.github.com/images/icons/emoji/trollface.png)

**Comment by Gigabyte918** [comment]
:trollface: HAHA

**Comment by Gigabyte918** [comment]
:trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface::trollface:

**Comment by AgarXTRA** [comment]
Incredibly how low level it has been on Github nowadays

**Comment by Luka967** [comment]
Partly because you're asking on the wrong place, partly because we love the trollface (i.e. we're immature)

**Comment by MastaCoder** [comment]
Partly because this is M-ED. The **issues** section of a project isn't a place to ask for devs. 

is·sue
ˈiSHo͞o/Submit
noun
1.
an important topic or problem for debate or discussion.
"the issue of global warming"
synonyms:	matter, matter in question, question, point, point at issue, affair, case, subject, topic; More
2.
the action of supplying or distributing an item for use, sale, or official purposes.
"the issue of promissory notes by the bank"
synonyms:	issuing, publication, publishing, printing; More
verb
1.
supply or distribute (something).
"licenses were issued indiscriminately to any company"
synonyms:	supply, provide, furnish, arm, equip, fit out, rig out; More
2.
come, go, or flow out from.
"exotic smells issued from a nearby building"
synonyms:	emanate, emerge, exude, flow (out/forth), pour (out/forth); be emitted
"the smell of onion issued from the kitchen"

**Comment by duwayy** [comment]
Instead of send trollfaces maybe someone could tell him where to ask what he wants uh? I personnaly have no idea where

**Comment by Luka967** [comment]
Problem is there's no such place.

**Comment by Luka967** [comment]
You know for the Internet right?

**Comment by AGarRiBiA** [comment]
i can help u :)
i already have a game site
http://kodclan.net :)

**Comment by RasyiidWho** [comment]
thanks :trollface:

**Comment by Luka967** [comment]
:trollface:
