### ISSUE TITLE
Invisible Bug!

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#622]
sometimes the entities just disappear and appear from no where sorry i cant able to give any evidance

**Comment by AlexHGaming** [comment]
which entities are you talking about? All of them?

**Comment by Gigabyte918** [comment]
yes all of them speically minions and bots #MyBadEnglishHAHAHAHAHAHAHAHAHA

**Comment by Luka967** [comment]
wat

**Comment by Gigabyte918** [comment]
how i can record my screen so i can show you that bug

**Comment by Megabyte918** [comment]
Could not reproduce.

**Comment by Gigabyte918** [comment]
what?

**Comment by MastaCoder** [comment]
he can't reproduce the bug you're talking about.
