### ISSUE TITLE
who is admin?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#624]
How could I make the server tell the client who is admin and who is not?

**Comment by AlexHGaming** [comment]
client sided

**Comment by gyeyoqu** [comment]
THE SERVER THELL TO THE CLIENT

**Comment by Luka967** [comment]
But the client needs to know what to do for that type of message.

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/issues/47
This issue started because of a duplicate from another repo that is duplicate from someone else xD

**Comment by MastaCoder** [comment]
The server already has flags for admins. You just need to make them do something on the client, lol.

**Comment by AGarRiBiA** [comment]
@MastaCoder How ? .-.
i want to make [ADMIN] behind admins name ;P

**Comment by Luka967** [comment]
...

**Comment by Megabyte918** [comment]
@gyeyoqu What @MastaCoder said
@AGarRiBiA See my last comment on #620
