### ISSUE TITLE
Skins not working in 1.6.0 using custom client (old version work)

### ISSUE THREAD

**Issue by RasyiidWho** [Megabyte918/MultiOgar-Edited#625]
1. (Not client problem)
![1](https://cloud.githubusercontent.com/assets/19422415/23544560/11b70812-002a-11e7-90e0-c89a467ad778.PNG)

2. Not work (latest 1.6.0)
![2](https://cloud.githubusercontent.com/assets/19422415/23544864/556ca3a4-002b-11e7-9531-af373078c4cb.PNG)

3. Work (old 1.5.0)
![3](https://cloud.githubusercontent.com/assets/19422415/23544881/6181bdfa-002b-11e7-92d8-92d94569fdbc.PNG)

**Comment by AlexHGaming** [comment]
Client sided I'm afraid
@AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus @AlexandriteErikParacelsus

**Comment by CalvinDKL** [comment]
Client sided? How, nothing has been changed client sided. I have the same problem.

**Comment by Megabyte918** [comment]
Skins work in every client I've tried, regardless of the version. I've said this many times before, nothing in this version has anything edited regarding skins other than a custom skins script (which has nothing to do with the server), and randomskins. Please check if there is an issue with your custom client regarding skins, and that everything is in working order.

**Comment by Y4ssine** [comment]
with 1.6.0   skins don't work even with agar.io domain

**Comment by Megabyte918** [comment]
@Y4ssine Skins have been patched in the vanilla client on all versions. They are only visible to other players.

**Comment by gyeyoqu** [comment]
Quiet skins work, they do not know

**Comment by smky** [comment]
This is probably client side...
If you are having problems with random bot skins, this is server side and you need to change something in PacketHandler.js.

Use this for your PacketHandler.js: http://pastebin.com/NQJbLP83

**Comment by CiMFULL** [comment]
Cigar have this problem too (with version 1.6.0)..
without <>
![2](https://cloud.githubusercontent.com/assets/26116340/23584504/538c6fe4-0196-11e7-9ebb-7d617d033a22.PNG)
![1](https://cloud.githubusercontent.com/assets/26116340/23584506/6410925a-0196-11e7-9be7-0793201d6f42.PNG)
with <>
![3](https://cloud.githubusercontent.com/assets/26116340/23584507/68038da4-0196-11e7-9a4b-d9d41691d2c3.PNG)
![4](https://cloud.githubusercontent.com/assets/26116340/23584511/6c7df45a-0196-11e7-9df3-b2f68269b6b2.PNG)

**Comment by MastaCoder** [comment]
So it has to be a MultiOgar-Edited issue. If the normal version works and the packet version doesn't, somethings been changed.

@Megabyte918 did you update anything in the skin system for p5? It was working fine before 1.6.0. (According to above)

**Comment by Tyler3D** [comment]
@MastaCoder Your right. /skin works. I'm going to try to fix this

**Comment by cowpits** [comment]
Wait, doge is an easter egg skin you can't wrap it in tags and add a name
on agar.io client any easter egg skin will be visible, premium skins are not visible to the player but other players can see it. 
I use the cigar client and skins in tags <skin> don't work i upload my own skin. perhaps i'm missing the point here.

**Comment by cowpits** [comment]
oh i see... i can put any of the skins that i have uploaded in tags <> or braces { } and they are visible as long as I have the skin in my skins folder in Cigar Client.

**Comment by MastaCoder** [comment]
@cowpits We don't use that easter egg on Cigar. All skins work with or without <>.

**Comment by cowpits** [comment]
@MastaCoder i'm confused, i'm using the Cigar Client and have to upload my skins to see them. What am i doing wrong?

**Comment by FlareYT** [comment]
You guys could try to use this [PacketHandler.js](http://pastebin.com/5KG6xL72) , works for me ( http://ogario.gq ) :) !

Greetings Flare.

**Comment by Jhair2015** [comment]
@FlareYT Could you tell me which VPS you use to host your servers please?

**Comment by FlareYT** [comment]
@Jhair2015 , im using a Windows VPS.

**Comment by CalvinDKL** [comment]
Has this been fixed yet??

**Comment by Megabyte918** [comment]
Fixed in recent updates

**Comment by Agarian** [comment]
@RasyiidWho What client is that?
