### ISSUE TITLE
This is a gamemode or other version of ogar?

### ISSUE THREAD

**Issue by CiMFULL** [Megabyte918/MultiOgar-Edited#626]
http://cellcraft.io/ http://galx.io/
This 2 site have same version (or gamemode) or ogar.
The server are really fun, a stalking virus, we will spawn as a virus spawn several times (about 6), labirin, 2nd map, and so mucchh other..

**Comment by CiMFULL** [comment]
https://github.com/pulviscriptor/agario-client/issues/203

**Comment by smky** [comment]
They custom coded both the clients and the server gamemodes. I think either both games are created by the same person, or by two friends.

**Comment by Luka967** [comment]
^^

**Comment by FantasyIsBae** [comment]
Elaborating on from what @smky said ,

Both have custom server and client protocols .
The servers are likely written in C++ .
And both are most likely owned by the same person/people , because for example when Cellcraft is down for maintenance you will be redirected to Galx.io

**Comment by smky** [comment]
One more thing to add,

Both have about the same physics, except galx, when you hit a virus, splits the cells evenly instead of around a primary cell.

**Comment by suprix** [comment]
Actually Fantasy, its python :D
