### ISSUE TITLE
How to change eating size?

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#629]
Normally in vanilla, you have to be 33% bigger than a cell to eat it, how to change this config?

**Comment by Tyler3D** [comment]
@AlexHGaming https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L777
Change 1.11 to 1.33 to get 33%

**Comment by AlexHGaming** [comment]
@Megabyte918 You do realise that vanilla uses 33% not 11% lol

**Comment by Luka967** [comment]
@AlexHGaming Since size is square rooted everything must be square rooted for the equation to stay in balance.
The actual multiplier should be a square root of 1.3 (1.14017543).
If you were to compare mass then you use 1.3.

**Comment by AlexHGaming** [comment]
@Megabyte918 change

**Comment by Megabyte918** [comment]
Fixed, @Luka967 Thanks for pointing it out

**Comment by Megabyte918** [comment]
@Luka967 Wait hold on a sec.. the mass requirement to eat a cell on Agar.io is 1.25, so wouldn't the size requirement be 1.11803398875?

**Comment by AlexHGaming** [comment]
@Megabyte918 no it is 1.33% not 1.25%

**Comment by Luka967** [comment]
@Megabyte918 Eating a virus needs in vanilla requires at least 132 mass.
sqrt(132 * 100) = 114.891252930761
sqrt(100 * 100) = 100
114.891252930761 / 100 = 1.1489125 which is 8% error compared to sqrt(1.3).

**Comment by Megabyte918** [comment]
Ah ok, I get it now. I remembered reading about it in the agario wiki or the agario complete physics guide on Reddit (or something like that) so I assumed it was true. Thanks for explaining

**Comment by AlexHGaming** [comment]
since i brought the attention, you're welcome.

**Comment by Luka967** [comment]
lmao
