### ISSUE TITLE
[Question] How was the WS socket issue on IE fixed?

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#630]
Hey! So i would just like to get some insight on this, just so i can understand how it was fixed.
Thanks!

**Comment by Megabyte918** [comment]
It was fixed by downgrading the version of the ws module in package.json. The current version of said module causes a crash when a player disconnects.

**Comment by CalvinDKL** [comment]
Downgrading do 1.1.0?

**Comment by ItzLevvie** [comment]
@CalvinDKL Yes
