### ISSUE TITLE
How do I set someones role to admin ? (By ip or id)

### ISSUE THREAD

**Issue by Y4ssine** [Megabyte918/MultiOgar-Edited#632]
the title says all

**Comment by Tyler3D** [comment]
https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/issues/48 - for IP
add this command to commandList.js - http://pastebin.com/Bf1Y4FCL -- for new command
userrole [id] [role]
@Y4ssine

**Comment by Y4ssine** [comment]
THANKS @Tyler3D YOU ARE THE BEST I LOVE YOU XD ♥
