### ISSUE TITLE
Suggestion ! 

### ISSUE THREAD

**Issue by Y4ssine** [Megabyte918/MultiOgar-Edited#633]
What if we made a discord channel to exchange information easier ? 
since here if you posted an issue you will probably get a feedback in 1-5 hours but in discord u can get it in at least 1-20 mins with easier contact :D 
or if u guyss already have a discord channel pass it in the comment ;o

**Comment by Tyler3D** [comment]
Or a forum

**Comment by Y4ssine** [comment]
@Tyler3D  what do u think of this website O.o
Agarian,tk 
it's a social media a mix between (fb+twitter) 
?

**Comment by Tyler3D** [comment]
@Y4ssine Nice

**Comment by Luka967** [comment]
Discord is a messaging service.
I'd use Reddit.

**Comment by Y4ssine** [comment]
discord is fast tho reddit style is annoying a bit

**Comment by Y4ssine** [comment]
reddit is just like github

**Comment by Y4ssine** [comment]
@Luka967  check agarian.tk 
login using 
Yassine as user
123123123 as pass 
:) and check the admin panel :D

**Comment by Luka967** [comment]
Reddit is built for back and forth convos related to aa topic. Reddit is fast too. Discord is still just a messaging service.

**Comment by Luka967** [comment]
a*

**Comment by Y4ssine** [comment]
ok
les make that reddit :D

**Comment by Megabyte918** [comment]
There is no need for a sub reddit, it will just end up the same as this.

**Comment by MastaCoder** [comment]
^ + 1000

**Comment by Luka967** [comment]
well yeah

**Comment by Megabyte918** [comment]
@Y4ssine Sorry if support seems a little slow, I have other things besides github that I do that take up alot of time and so do the other collaborators for this project. I'm thinking about adding some more collaborators but I'm not sure on it yet
