### ISSUE TITLE
Force remerge cells?

### ISSUE THREAD

**Issue by deniskrop** [Megabyte918/MultiOgar-Edited#635]
I want to make it so the player cells automatically remerge after some time, without the player having to put his mouse in the center to make them remerge. Can anyone advise how this could be done?

**Comment by Y4ssine** [comment]
i dont get you ! but i think you can use the command "rec ID" for to set the recombinetime to 0 for some players or 
you can do "merge ID" to remege any player cells without having to wait 30 seconds
or if you want the server to be instant server 
you can go to gameserver.ini  and search for playerRecombineTime and set it to 0

**Comment by Y4ssine** [comment]
did i answer !

**Comment by deniskrop** [comment]
@Y4ssine "merge ID" to remege is good but it is too fast, but I want to have the player cells move towards each other and merge instead of it being done instantly with "merge ID" to remerge

**Comment by Y4ssine** [comment]
i really don't understand what r u saying :D

**Comment by Y4ssine** [comment]
do u want to set that only to your cell or for all players  ?

**Comment by Tyler3D** [comment]
That's basically impossible because your cells follow your mouse

**Comment by Y4ssine** [comment]
@Tyler3D  need ur help ! do you have discord

**Comment by Tyler3D** [comment]
What do you need?

**Comment by deniskrop** [comment]
Basically, 30 seconds after splitting I want the players cells cells to all move towards the center, and automatically remerge into the single main cell instead of the player having to put his mouse in the center to remerge them

**Comment by Gigabyte918** [comment]
like Nebulous? Dont know what is Nebulous? [Here(https://www.youtube.com/watch?v=_B69rImCac4)]

**Comment by Gigabyte918** [comment]
where cell automaticlly Recombine no need to push cell on center!

**Comment by Megabyte918** [comment]
@deniskrop Such a thing is not possible. Since the cells already follow the mouse, you cant have them follow another set position (the center) while also having them follow the mouse.

**Comment by deniskrop** [comment]
@Megabyte918  Yes like nebulous, how do they do it? Is there any way I can make it like nebulous with this project?
