### ISSUE TITLE
Bug or Easter Egg

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#639]
when i added the bots with name `Titin` they all come with name `Hi there` is that a bug or Easter Egg @Megabyte918

**Comment by Gigabyte918** [comment]
and i used this nick on me C₁₆₉₇₁₉H₂₇₀₄₆₄N₄₅₆₈₈O₅₂₂₃₇S₉₁₁ this is Titin's Formula Try it!

**Comment by ZfsrGhS953** [comment]
No, you triggered the bad word filter. There is an easter egg, but it's somewhere else.

**Comment by Megabyte918** [comment]
@Gigabyte918 Remove the name from badwords.txt and you will be able to use it.
