### ISSUE TITLE
How to make an extension? like u-bot.ml?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#64]
When i do it it always goes to real agar lol

**Comment by Tyler3D** [comment]
You have to code it

**Comment by Megabyte918** [comment]
@NameYT 
1.) learn javascript
2.) code it

**Comment by NameYT** [comment]
@Megabyte918 Make one for this project :) That have bots count like that

**Comment by Megabyte918** [comment]
There is no need for an extension add on to this project.
