### ISSUE TITLE
auto ban outside bots???

### ISSUE THREAD

**Issue by TrAnZiT21** [Megabyte918/MultiOgar-Edited#640]
i have seen other games with an anti bot that when someone tries spawning bots it will automatically ban the proxies used to spawn the bots, can anyone tell me how i could do that on my server???

**Comment by MastaCoder** [comment]
Get a list of every single proxy in the world and ban them, no it's not possible. You'd need to add some sort of extreme minion checking system, in which I don't think is possible without beating the crap out of performance.

**Comment by AlexandriteErikParacelsus** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
