### ISSUE TITLE
Food appearance

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#642]
Such as changing the appearance of food, make it look smaller, even if the size of the dough is big,
If the food is 100 points, it will look like it's 50

OGARIO V3 , have this option

**Comment by ZfsrGhS953** [comment]
@gyeyoqu Change (this line)[https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Cell.js#L60] to this:
```javascript
this.setSize(Math.sqrt(this._sizeSquared + (prey.cellType === 1 ? prey._sizeSquared * 2 : prey._sizeSquared));
```
This will make food give 2 times more mass than normal, which is what you wanted (50 mass pellets give 100 mass)

**Comment by gyeyoqu** [comment]
mm , not work for me

**Comment by AlexHGaming** [comment]
@AlexandriteErikParacelsus reopen it or i will hak ur roblox account

**Comment by MastaCoder** [comment]
KEEP IT CLOSED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Megabyte918** [comment]
@gyeyoqu Try storing the prey's size in a variable then adding it, like this:
```js
var size = prey.cellType === 1 ? prey._sizeSquared * 2 : prey._sizeSquared
this.setSize(Math.sqrt(this._sizeSquared + size));
```

**Comment by gyeyoqu** [comment]
@Megabyte918  you can explain more ? please

**Comment by ZfsrGhS953** [comment]
@gyeyoqu I edited the code, there was a missing bracket.

**Comment by gyeyoqu** [comment]
Keep giving the same value as  points

**Comment by gyeyoqu** [comment]
I keep giving the same points, does not multiply
