### ISSUE TITLE
Question about playerCommads.js

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#645]
In the below a Moder/Admin can run /login password
/minion 1000 
for example to give himself 1000 minions. Or /minion and he gets only 1. 
Is there a way to limit to 20? 
} else {
player.minionControl = true;
                // Add minions for self
                if (isNaN(parseInt(add))) add = 1;
                for (var i = 0; i < add; i++) {
                    this.gameServer.bots.addMinion(player);

**Comment by Y4ssine** [comment]
interrested !

**Comment by AlexHGaming** [comment]
cowpits im ur biggest fan on YT
not really

**Comment by cowpits** [comment]
@AlexHGaming lol that's awesome!
not really :P

**Comment by Tyler3D** [comment]
@cowpits @Y4ssine http://pastebin.com/dYz1LdaR

if (add > 20) add = 20
Change 20 to whatever you want. And This appears twice

**Comment by cowpits** [comment]
@Tyler3D thank you, this works but i was able to keep running the command and it kept adding 20.
/minion 100 it would add only 20 which is good but I don't want them to be able to keep running. 
I want 20 to be the cap if it's possible unless they die and refresh the page.

**Comment by Tyler3D** [comment]
@cowpits http://pastebin.com/tD8Phc5L

**Comment by cowpits** [comment]
yeah i saw that link earlier and added in PlayerCommands.js. Is that the correct file?

 } else {
                player.minionControl = true;
                // Add minions for self
                if (isNaN(parseInt(add))) add = 0;
                  if (add > 20) add = 20

 // Add minions
                    } else {
                        client.minionControl = true;
                        // Add minions for client
                        if (isNaN(add)) add = 0;
                          if (add > 20) add = 20

**Comment by Tyler3D** [comment]
@cowpits No use the last one

**Comment by cowpits** [comment]
cool that is sweet! i got it but i changed this 
} else {
                player.minionControl = true;
                // Add minions for self\
                if (player.userRole == UserRoleEnum.USER)

UserRoleEnum.MODER to UserRoleEnum.USER

I don't want to give Moderator password for users, i'll give them the User password. And this works great, everytime I ran the command it removed the minions and added only 20. Thank you so much. 

I know this could be a stretch but is there a way to have the minions get the player name?

**Comment by Megabyte918** [comment]
@cowpits call the `addMinion` function with these paremeters:
```js
for (var i = 0; i < add; i++) {
    gameServer.bots.addMinion(client, client._name);
}
```

**Comment by cowpits** [comment]
@Megabyte918 you are awesome, thank you. 
i added it but kept crashing, so I figured why not try this: 
self.gameServer.bots.addMinion(player, player._name); 

bam that worked, that's all I needed is a little nugget. Man I can't express how much I appreciate this. 

The only thing that doesn't work and it didn't work before all this was Moder or Admin command for /minion playerID minionAmount doesn't do anything. 

Here's what I have: 

 /** For you **/
        if (isNaN(id)) {
            this.writeLine("Warn: missing ID arguments. This will give you minions.");
            // Remove minions
            if (player.minionControl == true && add == "remove") {
                player.minionControl = false;
                player.miQ = 0;
                this.writeLine("Succesfully removed minions for " + player._name);
            // Add minions
            } else {
                player.minionControl = true;
                // Add minions for self\
                if (player.userRole == UserRoleEnum.USER) {
                    // Remove minions first
                    player.minionControl = false;
                    player.miQ = 0;
                    // Then Add some
                    var self = this;
                    setTimeout(function() {player.minionControl = true;
                    if (isNaN(parseInt(add))) add = 0;
                    if (add > 25) add = 25
                        for (var i = 0; i < add; i++) {
                            self.gameServer.bots.addMinion(player, player._name);
                        }
                        self.writeLine("Added " + add + " minions for " + player._name);
                }, 1000);
                }
             else {
            if (isNaN(parseInt(add))) add = 1;
                for (var i = 0; i < add; i++) {
                    this.gameServer.bots.addMinion(player, player._name);
                }
                this.writeLine("Added " + add + " minions for " + player._name);
            }
        }
 
        } else {              
               /** For others **/
            for (var i in this.gameServer.clients) {
                var client = this.gameServer.clients[i].playerTracker;
                if (client.pID == id) {
                    // Remove minions
                    if (client.minionControl == true) {
                        client.minionControl = false;
                        client.miQ = 0;
                        this.writeLine("Succesfully removed minions for " + client._name);
                        var text = this.playerTracker._name + " removed all off your minions.";
                        this.gameServer.sendChatMessage(null, client, text);
                    // Add minions
                    } else {
                        client.minionControl = true;
                        // Add minions for client
                        if (isNaN(add)) add = 0;
                          if (add > 50) add = 50
                        for (var i = 0; i < add; i++) {
                            this.gameServer.bots.addMinion(client, client._name);
                        }
                        this.writeLine("Added " + add + " minions for " + client._name);
                        var text = this.playerTracker._name + " gave you " + add + " minions.";
                        this.gameServer.sendChatMessage(null, client, text);
                    }
                }
            }
        }
    },
