### ISSUE TITLE
Displacement.length is not a function

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#646]
![image](https://cloud.githubusercontent.com/assets/23644244/23645636/109a16a8-0305-11e7-9768-ee4e5628f11c.png)

**Comment by AlexHGaming** [comment]
This is when I use the addbot command.

**Comment by Megabyte918** [comment]
@AlexHGaming Use the latest version of BotPlayer.js.

**Comment by Jhair2015** [comment]
lol

**Comment by Luka967** [comment]
wat
