### ISSUE TITLE
Consuming All My Internet Speed 

### ISSUE THREAD

**Issue by fayizan** [Megabyte918/MultiOgar-Edited#648]
@Megabyte918 Just look at this, it consuming all my bandwidth 
![screenshot_514](https://cloud.githubusercontent.com/assets/19163419/23664893/e8c4d12c-037c-11e7-850e-e465698bc026.png)

This is my friend Screenshot \/

![17200015_1026183154192398_610249674_o](https://cloud.githubusercontent.com/assets/19163419/23664951/1dc3a952-037d-11e7-9b35-0f8e7102ce18.jpg)

**Comment by ZfsrGhS953** [comment]
301 kilobytes per second is definitely too much for 51 non-food cells. Maybe Moneyclip broke something again causing the server to send updates for all food cells...
@Megabyte918 This is off-topic.

**Comment by Megabyte918** [comment]
@ZfsrGhS953 Are you sure this is client sided? Maybe this could be an issue with the server. But then again, I couldn't manage to reproduce the same amount of bandwidth consumption with the same amount of food cells/bots/viruses
@fayizan Does the same bandwidth consumption happen on other versions of MultiOgar or by using other clients/extensions?

**Comment by fayizan** [comment]
nope I tried with your multiogar version only

**Comment by Luka967** [comment]
@fayizan Are you sure you're actually connected to your server?

**Comment by fayizan** [comment]
yes @Luka967 I hosted my server in digitalocean vps and played with 3 friends, all of them reported high data usage while playing in my PS so I shut it down and I use [kitty mod](https://kittymod.github.io/)(ogario edited) extension to play but I dont think it causing heavy data usage bcoz I use kitty mod since barbosik multiogar created...

**Comment by Megabyte918** [comment]
> nope I tried with your latest multiogar version only

So it does not happen on other versions?

**Comment by ZfsrGhS953** [comment]
@Megabyte918 As it turns out, all the visible nodes including food are pushed to ```addNodes``` on every tick. :(

**Comment by fayizan** [comment]
@Megabyte918 I dont have this problem in your previous versions and I tested again with your latest version all bandwidth consumption happens when I add minions and remove them completely too

**Comment by Megabyte918** [comment]
@ZfsrGhS953 That's a good thing right?
@fayizan How many minions are you adding? What's the starting size? Minions should not affect bandwidth much as they are basically the same thing as playerbots, that and the fact that your not adding like a million of them lol

**Comment by ZfsrGhS953** [comment]
@Megabyte918 Of course it isn't, nodes that are already visible and only need a position+size update should be pushed to ```updNodes``` instead.

**Comment by ZfsrGhS953** [comment]
@Megabyte918 What is happening here is that the server is sending names for all player cells on every tick and sending updates for over a hundred food cells that don't move at all.

**Comment by Megabyte918** [comment]
Oh yeah true, I thought that it was a good thing to send them so often to avoid any possible bugs with the client but I guess that's clearly not the case for any non-moving nodes, I will work on this later when I have the time

**Comment by Megabyte918** [comment]
@fayizan The extension you are using is the problem. I've prevented my server from sending updates to the client for non-moving nodes (food, viruses, etc) and compared bandwidth consumption. Surprisingly enough, it did not affect it all that much, even with 1000 foods on the map, judging by the meter on my taskbar.
I have however, tested my internet speed with the extension that you were using in the time of the screenshot you posted above, and my bandwidth usage nearly tripled.

**Comment by fayizan** [comment]
ohhh so you will fix it on next update ? since I use that extension with agario but it consume only <30kB/

**Comment by fayizan** [comment]
I tried with no extension but it still use max upto 200kB/s 
![screenshot_8](https://cloud.githubusercontent.com/assets/19163419/24134315/873a1c20-0e29-11e7-99e7-37870e596e39.png)

**Comment by fayizan** [comment]
> @fayizan How many minions are you adding? What's the starting size? Minions should not affect bandwidth much as they are basically the same thing as playerbots, that and the fact that your not adding like a million of them lol
I added like 200minions :| 50minions for each since my vps is 16gb droplet

**Comment by deniskrop** [comment]
Fix here: https://github.com/Megabyte918/MultiOgar-Edited/issues/758#issuecomment-294340267

**Comment by fayizan** [comment]
is this fixed..?

**Comment by fayizan** [comment]
@Megabyte918 is this fixed...?

**Comment by Megabyte918** [comment]
@fayizan There is nothing to be fixed, see my previous comment

**Comment by dfiverr** [comment]
@fayizan If you want to fix it, this is how: https://github.com/Megabyte918/MultiOgar-Edited/issues/758#issuecomment-294340267

**Comment by fayizan** [comment]
Thank you @Megabyte918 and @dfiverr
