### ISSUE TITLE
ugh, another error

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#650]
![image](https://cloud.githubusercontent.com/assets/23644244/23681986/57a400d4-0389-11e7-89a4-417496b40c45.png)

**Comment by AlexHGaming** [comment]
I had to reinstall the server and delete this one, but just incase it happens to me again, how do you do it?

**Comment by ItzLevvie** [comment]
@AlexHGaming https://github.com/JaraLowell/OgarServ/issues/172#issuecomment-279242778

**Comment by MastaCoder** [comment]
we're there already like 12 posts on this issue? Someone needs to add this to the wiki, ugh.

**Comment by Megabyte918** [comment]
@MastaCoder done
