### ISSUE TITLE
I need kind of help...

### ISSUE THREAD

**Issue by suprix** [Megabyte918/MultiOgar-Edited#655]
Hey,
I want to ask you 2 things...
1) So I've seen in game called "mgar.io" when i were mod there that have new thing in command.
**/minion [ID] [AmoutOfBots] [BotMass] <r>...**
So basiclly I want to add code for BotMass but i don't really know how...
Could someone give me that code? Owner of the game don't want to give to anyone :|

2) How can I add autorestart for server?

**Comment by AlexHGaming** [comment]
I can fuckin answer question 2 for you: Choose your liking 👍 
#596 #141 #146 #266 #447 #458 #267 #146 #148 #76

**Comment by suprix** [comment]
Alright, i've asked my friend and he's about to help me...
I just need 1st thing more :| :1234:

**Comment by AlexandriteErikParacelsus** [comment]
Closed

**Comment by Megabyte918** [comment]
@suprix There is already a command like this for minions in PlayerCommand.js

**Comment by suprix** [comment]
I can't find it for some reason.. Could you give me line?
And check the 2nd thing please. @Megabyte918
