### ISSUE TITLE
Please adjust! I pay...

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#656]
1) Virus
> (Very bad physics division from viruses!
> Original destroy virus:
> 15k size
> ![5454](https://cloud.githubusercontent.com/assets/24901742/23812260/cf4413a0-05ea-11e7-9ae2-f3817baa78ad.PNG)
> ![default](https://cloud.githubusercontent.com/assets/24901742/23811014/326caa6a-05e5-11e7-903e-0128982a3f27.PNG)
> MultiO-Edited (Last version):
> ![default](https://cloud.githubusercontent.com/assets/24901742/23811491/4f1e1818-05e7-11e7-8994-e53b1ec3aa98.PNG)
> Same size - 4.3k
> Very ridiculous division from viruses :/
>
>Here I personally in agario do pop split for 100%! turning out absolutely always, and here when on a     private the server that! everything is very bad... By Plz make the most similar division from viruses, it very strongly influences process of a game... it seems so to me.)
2) Eject Bug

> You can correct "animation" of eject mass, she somehow it is too far from edge of ball, it is necessary slightly closer ;)
> Original:
> ![5555](https://cloud.githubusercontent.com/assets/24901742/23812322/226c2c0c-05eb-11e7-86be-1ff514e9438e.PNG)
> MultiO-Edited (Last version):
> ![23](https://cloud.githubusercontent.com/assets/24901742/23812384/61ecb450-05eb-11e7-9c01-88f793d418ec.PNG)
>

**Comment by Luka967** [comment]
1. I have a good algorithm for virus mass exploding but it's private.
2. It's supposed to be like this.

**Comment by DeadLord1337** [comment]
Really... "It's supposed to be like this"  and why in agario not so...? Takes off for agario eject mass exactly from the edge of a ball, and on a privata the server from air...

**Comment by AlexHGaming** [comment]
hey, i'm pretty much a popsplitter my self.
If you want to increase the size of the cells, go to virus.js, find the exp bit, then change the '2' to a lower value. So if it was 1.6, it'd be nearly vanilla.

**Comment by DeadLord1337** [comment]
no no no... in agario at most from division of a virus 2-3 parts, and here 8... it isn't realistic. to me would be on the original as much as possible

**Comment by AlexandriteErikParacelsus** [comment]
Just stop with these issues

**Comment by MastaCoder** [comment]
^ Dad

**Comment by Luka967** [comment]
^ daddy

**Comment by DeadLord1337** [comment]
and you haven't answered me... adequate answer... that for developers such don't care for us.

**Comment by DeadLord1337** [comment]
and this the problem with viruses was in 1.5.0... well really think about settings of division from viruses

**Comment by Luka967** [comment]
@DeadLord1337
> Please adjust! I pay...

Very misleading title. We're open-source and are doing this in our free time. We could have slapped you with a .exe and people would be happy about it. But we haven't - we've made this as a base that can be modified, still 10 year olds keep asking on how to change this and that.

**Comment by Megabyte918** [comment]
@DeadLord1337 If you pay close enough attention to the divisions between vanilla and this version, they will look the same

**Comment by DeadLord1337** [comment]
ok fnx :\

**Comment by DeadLord1337** [comment]
@Luka967 May you give me a good algorithm for division from viruses?... plz :ссссс
