### ISSUE TITLE
A script that shows the players id?

### ISSUE THREAD

**Issue by CalvinDKL** [Megabyte918/MultiOgar-Edited#659]
Hey! So i dunno if its possible, but does someone know how to make a script that displays a users player id?
Thanks

**Comment by Luka967** [comment]
This requires protocol modifications. You're better off by just appending player ID at player's name.

**Comment by FantasyIsBae** [comment]
It is possible but @Luka967 is right

**Comment by CalvinDKL** [comment]
I understand but i need the actual id so players can be given bots

**Comment by Luka967** [comment]
Use regex to get the ID off of the player's name.
`/[\s\S]*/#([0-9]+)/` should work if you prefix the ID with #.
