### ISSUE TITLE
Minion Control (HELP YOU)

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#66]
Actually to controll the minions you need Press Q, 
You can change this with this steps.

1)Open in MultiOgar-Edited-master/src ERT control,
2)copy all and paste in tampermonkey (tampermonkey.net)
3)configure like this in the line 6 (// @match        *.agar.io/*, Change *.agar.io/ to agar.io/YourIp:Port)
4)Already works split bot with E and feed with R

**Comment by Megabyte918** [comment]
@AlexByte918 I don't think we need an issue for this because most people already know how to use it if their able to setup their own server, so I'm going to close this. But thanks for your help anyway :)
