### ISSUE TITLE
Client-sided but want to know

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#660]
How to change the max nick length name from 15 to higher?
Dunno if it's dupe, don't care if gets locked to collaborators, I just want to know how to change.

**Comment by Tyler3D** [comment]
@AlexHGaming Lol it's a config https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L159

**Comment by Jhair2015** [comment]
I think it refers to the client, that is done with F12 xd

**Comment by Luka967** [comment]
Vanilla clients should limit text length to 15. Servrr just double checks.

**Comment by Luka967** [comment]
dat typo

**Comment by AlexHGaming** [comment]
kk im retarded

**Comment by MastaCoder** [comment]
`<input maxlength="15" />`

**Comment by MineMooreALT** [comment]
right click on name box and choose inspect element change the maxlength to "9999" should be g

**Comment by MastaCoder** [comment]
@MineMooreALT or remove it lmao
