### ISSUE TITLE
how remove the grid?

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#661]

**Comment by Jhair2015** [comment]
Client sided

**Comment by imnotNxhz1** [comment]
I still do not understand xD

**Comment by Jhair2015** [comment]
that is not possible

**Comment by FantasyIsBae** [comment]
> I still do not understand xD
@imnotNxhz1 
What he means is that the grid cannot be removed using the server , it can only be done using the client .
