### ISSUE TITLE
help

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#663]
now to get  free 24/7 agar.io server?

**Comment by ItzLevvie** [comment]
Buy a VPS

**Comment by Luka967** [comment]
^

**Comment by Jhair2015** [comment]
I already have VPS, but like for 24/7 with putty or some other software?

**Comment by Luka967** [comment]
Just run a script that starts the server in a loop

**Comment by Jhair2015** [comment]
What is the name xd?

**Comment by ZfsrGhS953** [comment]
@Jhair2015 [forever](https://github.com/foreverjs/forever)

**Comment by MastaCoder** [comment]
@ZfsrGhS953 Just use screens, they're better ;)

**Comment by Y4ssine** [comment]
@Jhair2015  i know how to run a server 24/7 on ubunto :) pm me in discord  Yassine#1657

**Comment by MastaCoder** [comment]
ubonto :trollface:

**Comment by Jhair2015** [comment]
@MastaCoder hahahah xDDD :trollface: :

**Comment by ZfsrGhS953** [comment]
@MastaCoder Umm, he said "ubunto", not "ubonto".

**Comment by Luka967** [comment]
oboöunthü

**Comment by ItzLevvie** [comment]
ubunt(u)o triggered

**Comment by Tyler3D** [comment]
I have unbunchu and inx mint and windows 9.2 on my wmwares. Running windows 11

**Comment by FantasyIsBae** [comment]
I have Linou Operationg Sistem 40 MegaByte (Get it ?) memory and quad core CPU

**Comment by Jhair2015** [comment]
:trollface:

**Comment by MastaCoder** [comment]
@ZfsrGhS953 shhh, idk what you're talking about.

**Comment by FantasyIsBae** [comment]
:trollface:

**Comment by ItzLevvie** [comment]
Wirus

**Comment by ZfsrGhS953** [comment]
@MastaCoder What? I didn't post anything.

**Comment by ZfsrGhS953** [comment]
@FantasyIsBae That's not funny, you got permabanned from my repositories.

**Comment by FantasyIsBae** [comment]
>@FantasyIsBae That's not funny, you got permabanned from my repositories.

@ZfsrGhS953 Its funny that you can't take a joke .

**Comment by FantasyIsBae** [comment]
lol

**Comment by ZfsrGhS953** [comment]
@FantasyIsBae That's not the reason why I banned you, it's because you edited my message without permission. Was it hard for you to quote my message and edit it instead of editing the message itself?

**Comment by FantasyIsBae** [comment]
Matters how injured his friend is

**Comment by Luka967** [comment]
And how strong is the relationship of the two friends, and it's neutral here

**Comment by FantasyIsBae** [comment]
@Luka967 Good point

**Comment by Luka967** [comment]
@FantasyIsBae

> 40 MegaByte memory

Is Megabyte your bae now lol

**Comment by FantasyIsBae** [comment]
He's a good friend that's for sure :) 

#MegabyteIsBae

**Comment by FantasyIsBae** [comment]
@Luka967 Do u wanna join [TinyDev](https://github.com/TinyDev)

**Comment by Luka967** [comment]
Nah

**Comment by FantasyIsBae** [comment]
@Luka967 Np :)
