### ISSUE TITLE
MultiOgar Vanilla

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#664]
How can I make my multiogar exactly like vanilla the splits the speed the movement and the pellets can anyone please telll me thank you :)

**Comment by Luka967** [comment]
They're pretty similar already.

**Comment by Jhair2015** [comment]
yes, is similar to 95%

**Comment by AlexHGaming** [comment]
That's what we are trying to do, also trying to maintain performance as possible

**Comment by FantasyIsBae** [comment]
@Jhair2015 And @AlexHGaming are right

**Comment by Megabyte918** [comment]
@FantasyIsBae is right

**Comment by Luka967** [comment]
@Megabyte918 is right

**Comment by koda** [comment]
I just wanted to ask what I can make the split velocity at and e.t.c

**Comment by FantasyIsBae** [comment]
@Luka967 is right

**Comment by MastaCoder** [comment]
@FantasyIsBae is right

**Comment by FantasyIsBae** [comment]
@MastaCoder is right

**Comment by Jhair2015** [comment]
@MastaCoder @FantasyIsBae  @Luka967 is right

**Comment by AlexHGaming** [comment]
@Jhair2015 is right

**Comment by Y4ssine** [comment]
freaking punch of trollers .-.

2017-03-17 23:10 GMT+04:00 AlexHGaming <notifications@github.com>:
