### ISSUE TITLE
Skin with <>

### ISSUE THREAD

**Issue by vincent95330** [Megabyte918/MultiOgar-Edited#665]
Why i can't add skin with <skin> ? Its don't work :/ I have to name myself as the skin ... Help me please

**Comment by vincent95330** [comment]
This script not working ? 
PacketHandler.prototype.setNickname = function (text) {
    var name = "";
    var skin = null;
    if (text != null && text.length > 0) {
        var skinName = null;
        var userName = text;
        var n = -1;
        if (text[0] == '<' && (n = text.indexOf('>', 1)) >= 1) {
            if (n > 1)
                skinName = "%" + text.slice(1, n);
            else
                skinName = "";
            userName = text.slice(n + 1);
        }
        //else if (text[0] == "|" && (n = text.indexOf('|', 1)) >= 0) {
        //    skinName = ":http://i.imgur.com/" + text.slice(1, n) + ".png";
        //    userName = text.slice(n + 1);
        //}
        if (skinName && !this.gameServer.checkSkinName(skinName)) {
            skinName = null;
            userName = text;
        }
        skin = skinName;
        name = userName;
    }
    if (name.length > this.gameServer.config.playerMaxNickLength) {
        name = name.substring(0, this.gameServer.config.playerMaxNickLength);
    }
    if (this.gameServer.checkBadWord(name)) {
        skin = null;
        name = "Hi there!";
    }
    this.socket.playerTracker.joinGame(name, skin);
};

**Comment by Jhair2015** [comment]
lol VinceBots

**Comment by AlexHGaming** [comment]
You do realise that this is a project to do with the server not with skins and scripts!!!

**Comment by FantasyIsBae** [comment]
@AlexHGaming Is right
