### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#668]
i cant find the error , any1 can help me

![cc3d8edc-0439-11e7-9fd1-ec68abbf90b3](https://cloud.githubusercontent.com/assets/25285427/23996837/b6159d58-0a2d-11e7-86de-2b26bb9003f9.png)

**Comment by Megabyte918** [comment]
Can you describe how you produced this error?

**Comment by Tyler3D** [comment]
@gyeyoqu That crash is from the account command from my repo which was fixed a while ago

**Comment by gyeyoqu** [comment]
@Tyler3D in what commit?
