### ISSUE TITLE
last version is laggy!

### ISSUE THREAD

**Issue by SomeoneCares11** [Megabyte918/MultiOgar-Edited#669]
Hi,

i was using an old version from MultiOgar-Edited ( 3 month ago ),
i decied to upgrade today, 

i see the meaning of lag !

**Comment by SomeoneCares11** [comment]
The lag on 1.6.0, 

Could someone explain the updated files to fix
`	Fix cells switching order on doublesplit`

i want to get just this from the new version.

**Comment by MastaCoder** [comment]
You can't just use an older version and pull changes from newer versions, theres a lot of dependent code on that code.

**Comment by AlexHGaming** [comment]
To fix the cell switch revertation
Go to playercell.js
Find `unshift` and replace it with `push`

**Comment by Luka967** [comment]
dat issue number tho

**Comment by AlexHGaming** [comment]
i know right it is mlg 420 blaz it

**Comment by AlexHGaming** [comment]
where my boy @AlexandriteErikParacelsus at doe

**Comment by SomeoneCares11** [comment]
@AlexHGaming i didn't find it!
this my PlayerCell file!
`var Cell = require('./Cell');

function PlayerCell() {
    Cell.apply(this, Array.prototype.slice.call(arguments));
    
    this.cellType = 0;
    this._speed = null;
    this._canRemerge = false;
}

module.exports = PlayerCell;
PlayerCell.prototype = new Cell();

// Main Functions

PlayerCell.prototype.canEat = function (cell) {
    return true; // player cell can eat anyone
};

PlayerCell.prototype.getSpeed = function (dist) {
    var speed = 2.1106 / Math.pow(this._size, 0.449);
    var normalizedDist = Math.min(dist, 32) / 32;
    // tickStep = 40ms
    this._speed = speed * 40 * this.gameServer.config.playerSpeed;
    return this._speed * normalizedDist;
};

PlayerCell.prototype.onAdd = function (gameServer) {
    // Gamemode actions
    gameServer.gameMode.onCellAdd(this);
};

PlayerCell.prototype.onRemove = function (gameServer) {
    // Remove from player cell list
    var index = this.owner.cells.indexOf(this);
    if (index != -1) {
        this.owner.cells.splice(index, 1);
    }
    // Gamemode actions
    gameServer.gameMode.onCellRemove(this);
};
`

**Comment by Megabyte918** [comment]
@SomeoneCares11 Replace your PlayerCell.js with the newest one.
