### ISSUE TITLE
Requesting coding help

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#670]
Can someone take a look at this please, I'm stuck. If you recall I wanted to allow users to /login and order themselves minions and the minions pick up their skin and name. Issue here https://github.com/Megabyte918/MultiOgar-Edited/issues/645
Well this works great and thank you for the help on it. But I found a bug or security issue, I noticed that a user can /login and order minions for other users up to 50. Basically same as Mod or Admin. With the current code, Admin is also limited to 50. So I figured why not try to create different specifications based on Roles. But I'm stuck and the server crashes once I connect. 

test working file here: http://tutorialscow.esy.es/
/login guest
/login moder
/login admin

As Guest you can give other players up to 50 minions, just like Admin and Mod

Working file
[PlayerCommand.txt](https://github.com/Megabyte918/MultiOgar-Edited/files/847948/PlayerCommand.txt)

Non working roles file
[PlayerCommand_Roles.txt](https://github.com/Megabyte918/MultiOgar-Edited/files/847950/PlayerCommand_Roles.txt)

**Comment by vincent95330** [comment]
Hey cowpits , can you add me on skype : vincentcoc , I have to speck with you .. :)

**Comment by cowpits** [comment]
ok is this you?  ๖νιиƈє༻,

**Comment by Megabyte918** [comment]
@cowpits Add an if statement that prevents users without the required permissions to give minions to others.

**Comment by cowpits** [comment]
@Megabyte918 yeah I think I got it. Thanks for the tip but I could only get either Moder or Admin to work but not both. If I get both working when Moder does /minion remove #ID for a player, it loops and keeps giving Moder minions, although it removes the minions for the other player, lol. 
I'll figure it out eventually. Thanks again.
