### ISSUE TITLE
I got a big problem! HELP

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#671]
![trollface](https://cloud.githubusercontent.com/assets/18507527/24024705/e3020b7c-0a8b-11e7-8cb7-19d0f5ae0529.jpg)

**Comment by raphyjb** [comment]
Just hoping to make someone laugh ;P i promis!

**Comment by MastaCoder** [comment]
...

**Comment by AlexHGaming** [comment]
:trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: v

**Comment by ZfsrGhS953** [comment]
@Megabyte918 Invalid.

**Comment by Jhair2015** [comment]
:venezuela:

**Comment by Jhair2015** [comment]
:V

**Comment by Gigabyte918** [comment]
CLOSE!

**Comment by Megabyte918** [comment]
@raphyjb Please do not make invalid issues like these
