### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by vincent95330** [Megabyte918/MultiOgar-Edited#673]
How to login with chat ?? 
I have config userroles 
[
    { 
        "ip":"127.0.0.1", 
        "password":"test",
        "role":"ADMIN",
        "name":"Local Administrator" 
    },
    { 
        "ip":"127.0.0.1", 
        "password":"test3",
        "role":"MODER",
        "name":"Local Moderator" 
    },
    { 
        "ip":"127.0.0.1", 
        "password":"test2",
        "role":"USER",
        "name":"Local User" 
    }
]

But i can't login in game ... :/

**Comment by gyeyoqu** [comment]
You must change the default ip for your ip in http://vermiip.es

and then in the chat write: /login ''password''

**Comment by gyeyoqu** [comment]
@vincent95330

**Comment by Megabyte918** [comment]
@vincent95330 Please search up your question to see if it is reproduced first, this has been asked many times before.
