### ISSUE TITLE
The new binary reader

### ISSUE THREAD

**Issue by AdaptCharm** [Megabyte918/MultiOgar-Edited#674]
I am trying to implement a functional login system coded in Javascript. It consists of three functions:

`register()` - Username / password registration, stored into a MySQL database
`login()` - Checks the submitted credentials and authenticates the user account
`logout()` -  Log out the authenticated user account

These functions and their event handlers is already implemented client-side.

When it comes to the back-end packets and server-side code, I have already done that as well. 
_However_, whenever I'm trying to call the `readUInt8()` function from the `./packet/BinaryReader`, the server crashes with this error message: `TypeError: reader.readUInt8 is not a function`.

So my questions is what happened to this function? Why is it not included in the binary reader anymore? Did it get replaced with another function? What is the correct function I should call?
https://github.com/Barbosik/MultiOgar/blob/master/src/packet/BinaryReader.js

Any feed-back appreciated.

**Comment by Megabyte918** [comment]
@AdaptCharm The function was removed because it was not needed anymore (it was no longer being used in the server)
If you would like to add the function back however, just copy/paste it from the original file, it shouldn't cause any conflicts.

**Comment by Kasilon** [comment]
@AdaptCharm can you share the login system with register login et logout ?
