### ISSUE TITLE
anyone here actually got a life?

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#678]
![4527065](https://cloud.githubusercontent.com/assets/18507527/24070033/3fc30a14-0b8b-11e7-8f22-529b43a4ab7f.jpg)

**Comment by FantasyIsBae** [comment]
Funny-ish , but invalid .

**Comment by Luka967** [comment]
I don't and am happy

**Comment by raphyjb** [comment]
same :P
