### ISSUE TITLE
How to Make Tampermonkey Which Send The Code to the agario console thing

### ISSUE THREAD

**Issue by SambyAgarYT** [Megabyte918/MultiOgar-Edited#679]
There is a problem in pellet mode :( When i activate it some bots collect but it follows me :) Please send help
I also fix the skin script issue
but i need to know the tampermonkey code to make it work!
@Megabyte918  TY

**Comment by ZfsrGhS953** [comment]
@SambyAgarYT Megabyte changed the pellet mode so that the bots that don't have any pellets in proximity will follow your mouse. You can revert to the old behavior by changing "8e4" in [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/MinionPlayer.js#L53) to "1e999"

**Comment by MastaCoder** [comment]
That's gonna take a beat in performance though ^^

**Comment by ZfsrGhS953** [comment]
@MastaCoder Why? It doesn't change the quadtree find range, only the minimum squared distance required for a bot to lock on a pellet.

**Comment by SambyAgarYT** [comment]
@ZfsrGhS953 Lemme try :D

**Comment by SambyAgarYT** [comment]
@ZfsrGhS953 @Megabyte918 
![image](https://cloud.githubusercontent.com/assets/26500691/24076982/a1062704-0c79-11e7-9031-8e5ee5b8f24e.png)Working skin w/out a the skin script :p help me

**Comment by Tyler3D** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/7#issuecomment-259932803
Two "Samby"s wtf

**Comment by SambyAgarYT** [comment]
@Tyler3D wut? oh that? that's not my official account lol :p i just made my official acc yesterday :p btw i fixed the skin lol but anyone know the code for tampermonkey for sending the commands thru console?\

**Comment by Tyler3D** [comment]
@SambyAgarYT If you mean chat commands you have to use another client. The only chat scripts I know of, aren't server-sided.

**Comment by SambyAgarYT** [comment]
@Tyler3D I mean in tampermonkey making a blank text box then put kraken there and the code will be sent to the agario page console thingy

**Comment by SambyAgarYT** [comment]
@Megabyte918 can you help me bro? Is there anyway to contact you in private?

**Comment by Megabyte918** [comment]
It would be best to just to do it through client modifications .

**Comment by SambyAgarYT** [comment]
@Megabyte918 Ikr :dagger:
