### ISSUE TITLE
Rush Mode

### ISSUE THREAD

**Issue by NoiseControllers** [Megabyte918/MultiOgar-Edited#68]
it's possible.

thanks :)

**Comment by Megabyte918** [comment]
@NoiseControllers What's rush mode?

**Comment by firelightning13** [comment]
https://www.youtube.com/watch?v=kOrKHaAXYMY

**Comment by Megabyte918** [comment]
So its basically just FFA with red viruses and a 5min time limit?

**Comment by firelightning13** [comment]
I guess that's pretty much. There's nothing really special about it

**Comment by PrinceDark9243** [comment]
no one thing more you can split virus with 3 eject mass

**Comment by firelightning13** [comment]
really? i haven't test it yet. my cheap phone still couldn't handle this kind of graphic. well, you could just modify it manually in gameserver.ini, or add the gamemode yourself. but that's up to @Megabyte918

**Comment by PrinceDark9243** [comment]
and more thing when virus split mass of virus turn to 75

**Comment by Megabyte918** [comment]
@PrinceDark9243 If rush mode was to be added, I am unable to add those specific physics for the mode as it would cause lag, even when the mode is off.

**Comment by Megabyte918** [comment]
@NoiseControllers It is being worked on

**Comment by Megabyte918** [comment]
Would you like it to have mobile physics as well or just keep the current ones?

**Comment by MastaCoder** [comment]
Not mobile physics please 😭

**Comment by PrinceDark9243** [comment]
OH COOL!

**Comment by PrinceDark9243** [comment]
Mobile Physics have no auto SPlit!

**Comment by Megabyte918** [comment]
Development halted due to inexplicable bug**

**Comment by PrinceDark9243** [comment]
@Megabyte918 When you are going start development the Rush Mode!

**Comment by PrinceDark9243** [comment]
@Megabyte918 !

**Comment by Megabyte918** [comment]
@PrinceDark9243 
> Development for this gamemode has been halted due to an inexplicable bug**

**Comment by MastaCoder** [comment]
lol

**Comment by PrinceDark9243** [comment]
so Fix the BUG

**Comment by MastaCoder** [comment]
Dude, he's doing it on his free time. This is an open source project. He's not getting paid for it. Don't see why he even has to do it for you, he can just closed this all together and not do it at all.

At least have some respect for people offer these software for absolutely no cost..

**Comment by PrinceDark9243** [comment]
i am sorry you are @MastaCoder  Sorry @Megabyte918

**Comment by Tyler3D** [comment]
@Gigabyte918 @NoiseControllers I sorta made Rush Mode. 
http://pastebin.com/JNxJNFXS - Make a file called Rush.js in your gamemode folder
http://pastebin.com/qVy4WSNM - Replace index.js with this.
Change your server gamemode to 4

**Comment by Tyler3D** [comment]
The "inexplicable bug" is that the agario client doesn't work. But I figured since I'm not going to work on it anymore I would release it. I recommend you use the Cigar client or astr.io for Rush Mode.

**Comment by Tyler3D** [comment]
Also the ending doesn't mention the winner it just uses a normal FFA leaderboard.

**Comment by Tyler3D** [comment]
@Megabyte918 Close?

**Comment by Luka967** [comment]
This is for sure due to packet 0x30 being now for FFA position.
But hey, we can still trick agar. Use the FFA packet and just add a string containing time left before everything.
I'll try this too.

**Comment by Agarian** [comment]
For some reason, i just has the idea for a config:
Display only the top 10 people
Or display top 10 and your position, like agar.io

**Comment by Tyler3D** [comment]
@Luka967 No, because the leaderboard didn't work even on protocol 9 for the original client. Which is weird considering that the board command works on the vanilla client.Protocol 11 I haven't tested on but. I would imagine it would be the same result. I will try your method. But, I don't have much free time.

**Comment by Tyler3D** [comment]
@Agarian I don't think that is possible for the original client because that client gets your position from 0x30. And removing that will remove the red text.

**Comment by Tyler3D** [comment]
But Ill see what I can do

**Comment by Luka967** [comment]
I've completely forgot for this.
Lemme start doing it xD

**Comment by Tyler3D** [comment]
lol

**Comment by Luka967** [comment]
I made some progress. Currently struggling with packets like you :/

**Comment by Luka967** [comment]
Fixed it~

**Comment by Tyler3D** [comment]
dammmmmm xD

**Comment by Agarian** [comment]
lol i've added too many features to my server(performance hasn't changed :D), so i can't get the latest version, and i can't seem to get @Luka967 leaderboard fix to work either DX

**Comment by Luka967** [comment]
@Agarian It all works for me.

Alright. I made Rush Mode!

I just want to set all players on free-roam when the game finishes. This'll take a few minutes

xD

**Comment by Agarian** [comment]
lol

**Comment by Luka967** [comment]
![lol](https://cloud.githubusercontent.com/assets/15956695/22407925/37709d12-e670-11e6-878d-aa9b462b0b01.JPG)

**Comment by Agarian** [comment]
lol wut

**Comment by Agarian** [comment]
Gimme rush mode when u finish lol

**Comment by Luka967** [comment]
I'll put it [on my fork](https://github.com/Luka967/MultiOgar-Edited) after I finish because it needs a good amount of code refactoring to make it possible

**Comment by Agarian** [comment]
Ok 👍

**Comment by Tyler3D** [comment]
xD my code is crap @Luka967  @Agarian

**Comment by Luka967** [comment]
Minutes turned into hours as I too encountered a bug with free-roam. Can't trace to anything.

**Comment by Luka967** [comment]
@Megabyte918 Did you get this problem too maybe?

**Comment by Luka967** [comment]
Oh I get it now... I assigned to spectate the largest player and copy all its visible nodes but I'm the largest player so nodes aren't updated
Took me 30 minutes to discover this xD

**Comment by Luka967** [comment]
Fixed it finally god damnit

Posting it on github soon

**Comment by Agarian** [comment]
.-.

**Comment by Agarian** [comment]
You're in a WAY different timezone that me lol

**Comment by Luka967** [comment]
lol yes
And when I was just about to start committing parents forced me for bed
;-;

**Comment by Luka967** [comment]
"forced me for bed"
lol

**Comment by Agarian** [comment]
XD

**Comment by AlexandriteErikParacelsus** [comment]
Shut up and let me fill you with my pleasure

**Comment by Agarian** [comment]
.-.

**Comment by Luka967** [comment]
![ayy](https://cloud.githubusercontent.com/assets/15956695/22418615/0546e0c0-e6da-11e6-873e-4a6f4790c99b.JPG)
![lmao boi](https://cloud.githubusercontent.com/assets/15956695/22418616/05475b5e-e6da-11e6-976b-3fbae152d764.JPG)

**Comment by Luka967** [comment]
Would you like highlighted text with every protocol? xD

**Comment by Luka967** [comment]
I pushed the changes to my fork.

**Comment by Agarian** [comment]
Whoa, that's possible?

**Comment by Luka967** [comment]
Yup

**Comment by Agarian** [comment]
lol then maybe...

**Comment by Luka967** [comment]
Finished doing it xD

**Comment by Agarian** [comment]
WOW k

**Comment by NoiseControllers** [comment]
How to get mass of the user?

**Comment by ZfsrGhS953** [comment]
@NoiseControllers 
```javascript
return this._mass;
```
PlayerTracker isn't a cell, you need to use _score instead:
```javascript
return this._score;
```

**Comment by NoiseControllers** [comment]
@ZfsrGhS953 yes, but the problem is what alone sum _score.

Is for do a mode of game kind Survival mode, Where yes mass is same 0 you die with a limit of time.

**Comment by Fan7asy** [comment]
@Luka967 Has added this on [his fork](https://github.com/Luka967/MultiOgar-Edited), so I will close this issue.
