### ISSUE TITLE
UserRoles

### ISSUE THREAD

**Issue by Mr-BrockLee** [Megabyte918/MultiOgar-Edited#680]
How Do  I turn it on? How do I login and How do i give it to a friend?

**Comment by Tyler3D** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/673

**Comment by Tyler3D** [comment]
http://lmgtfy.com/?iie=1&q=How+to+search+a+Github+repo+for+issues
XD

**Comment by MastaCoder** [comment]
i love lmgtfy

**Comment by Mr-BrockLee** [comment]
Still login failed, so pretend my password is "henrisen3" i do  /login henrisen3? @MastaCoder @Tyler3D

**Comment by Megabyte918** [comment]
@Mr-BrockLee Yes. Also people have asked this many, many times before.
