### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by smky** [Megabyte918/MultiOgar-Edited#681]
How would I be able to use HttpsServer?

**Comment by MastaCoder** [comment]
was removed because it had a memory leak.

**Comment by smky** [comment]
Well then i'm screwed... I recently added a voice chat feature with the pubhub api on my custom client (popsplit.us), and since its powered by webrtc, I need a secure ssl/tls connection. I have a valid certificate, so thats not the issue. My current solution is to have the voice chat application hosted on a seperate domain (chat.popsplit.us) which is secured with https. My aim is to implement voice chat directly into the client, and not have then on seperate domains. This is impossible if I cannot use ssl with MultiOgar...

Any ideas/solutions?

**Comment by Luka967** [comment]
Barbosik's MultiOgar supports SSL.

**Comment by smky** [comment]
How would I be able to implement it manually into Megabyte's MultiOgar fork. I can deal with the memory leak.

**Comment by Megabyte918** [comment]
@smky Search for the commits in which SSL support was removed, and then add the code that was removed back. It should have been removed shortly after this repo was created

**Comment by smky** [comment]
Thanks! One more question... do you plan on fixing this said memory leak from using SSL in the future, or is it not very important @Megabyte918?

**Comment by Megabyte918** [comment]
There are greater priorities at the moment.

**Comment by smky** [comment]
Good point...
