### ISSUE TITLE
RE: UserRoles #680

### ISSUE THREAD

**Issue by Mr-BrockLee** [Megabyte918/MultiOgar-Edited#683]
Still login failed, so pretend my password is "henrisen3" i do /login henrisen3? @MastaCoder @Tyler3D

**Comment by AlexHGaming** [comment]
yeah same keeps happening to me.

**Comment by MastaCoder** [comment]
I don't use userRoles, I find it kinda useless if you don't have a members system installed. (My IP changes once every week, and it'd be a pain to go through and change it each time.)

**Comment by TrAnZiT21** [comment]
Ypu can take out the ip and leave it blank so if your ip did change u wouldnt have to change the settings, unless u want to make it so if anyone ever got the password they wouldnt be able to sign in.
