### ISSUE TITLE
Splits is so bad ?

### ISSUE THREAD

**Issue by AGarRiBiA** [Megabyte918/MultiOgar-Edited#686]
why the splits is so bad ? ...
http://k-d.io -> EXP+ (1)
gameserver.ini : http://kodclan.net/gameserver.ini
yt video : https://www.youtube.com/watch?v=CoIXXUUOPxs
720p HD to see the splits bug : )

**Comment by Gigabyte918** [comment]
Yes you are right! Split need to be improved!

**Comment by AGarRiBiA** [comment]
new bug : http://prnt.sc/embuc3
server randomly closed ?
![7a0bbf144bf644058be5cd835395e5d8](https://cloud.githubusercontent.com/assets/25711259/24112877/f75ec394-0dab-11e7-910d-fbdcbdd4e30e.png)

**Comment by AlexHGaming** [comment]
We need to save the performance aswell you know...

**Comment by Luka967** [comment]
`movilePhysics` config is turned on in 1.6 and not in 1.5.

**Comment by Megabyte918** [comment]
^^

**Comment by AGarRiBiA** [comment]
thanks
