### ISSUE TITLE
server randomly closed ?

### ISSUE THREAD

**Issue by AGarRiBiA** [Megabyte918/MultiOgar-Edited#687]
hello , i found a new bug in MultiOgar-Edited v1.6.0
Server is randomly closed : http://prnt.sc/embuc3
![7a0bbf144bf644058be5cd835395e5d8](https://cloud.githubusercontent.com/assets/25711259/24112972/47c5468c-0dac-11e7-993e-5d8386c9c479.png)

this is a public server [ EXP+ (1) ] in http://k-d.io
so people is playing normaly ...

**Comment by AlexHGaming** [comment]
reinstall the server.

**Comment by AGarRiBiA** [comment]
@AlexHGaming why reinstall :\ ?

**Comment by AlexHGaming** [comment]
Because everything works for me up to date with the server.

**Comment by Megabyte918** [comment]
I could not reproduce this. (using an unedited version)

**Comment by Megabyte918** [comment]
@AGarRiBiA Try using an updated version and make sure not to edit anything regarding the collision/move engine and you should be fine. Tell me if you still experience these crashes

**Comment by AGarRiBiA** [comment]
ok i will try that and give you a response ...

**Comment by AGarRiBiA** [comment]
@Megabyte918 same problem :!

**Comment by MastaCoder** [comment]
Try using node -v, what version does it say you're on?

**Comment by AGarRiBiA** [comment]
@MastaCoder v6.10.0

**Comment by Megabyte918** [comment]
@AGarRiBiA What's the status on this bug? Has it happened again since?

**Comment by MastaCoder** [comment]
^^ Try running on a different PC running fresh install of Node.js 7.9.0.

**Comment by AlexHGaming** [comment]
@Megabyte918 @MastaCoder No response.
