### ISSUE TITLE
Nick Filter

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#688]
Hey, Im trying to add a Nick filter so people cant have for example "Shit" in there name. Is there a way to add this filter into the client?

**Comment by AlexHGaming** [comment]
Ever heard of "badwords.txt"?
ugh issues these days

**Comment by Logan7432** [comment]
@AlexHGaming I wanted to add it into a client, but nvm

**Comment by MastaCoder** [comment]
1. That's a client issue, why post it here.
2. That's a terrible idea.

**Comment by Logan7432** [comment]
@MastaCoder To see if anyone knew

**Comment by Logan7432** [comment]
@MastaCoder And if thats a terrible idea then why is it in multiogar server? I need it so people cant put bad words in there nickname

**Comment by MastaCoder** [comment]
No I meant doing it client sided.
