### ISSUE TITLE
Badwords

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#689]
Is there a way to code the Badnames code from this into the old cigar server so I can blur bad nicknames and words in chatbox?

**Comment by MastaCoder** [comment]
nice mo-ed issue

**Comment by Logan7432** [comment]
@MastaCoder English please

**Comment by Logan7432** [comment]
@MastaCoder By any chance do you have the files for the old cigar server laying around? I kinda just corrupted mine.

**Comment by MastaCoder** [comment]
check commits of cigar, go back to when the server was there. download

**Comment by Logan7432** [comment]
@MastaCoder Can you Please implement the bad word filter thats on this onto the old cigar please?

**Comment by Megabyte918** [comment]
@Logan7432 Please don't make issues unless they have something to do with this project
