### ISSUE TITLE
Brand New Gamemode - Last Man Standing!

### ISSUE THREAD

**Issue by Tyler3D** [Megabyte918/MultiOgar-Edited#69]
Created by Me and @Megabyte918 
4 New Configs.
The Default for The gamemode is: 60 mins until LMS starts. And 60 mins until the you can join again.

**Comment by Tyler3D** [comment]
@Megabyte918 Need the announcement tag XD

**Comment by NameYT** [comment]
What is the command bruhh!

**Comment by Jhair2015** [comment]
In gameserver.ini put 4 on gameserver

`serverGamemode = 4`

**Comment by Tyler3D** [comment]
@Jhair2015 
`ServerGamemode = 5`

**Comment by Jhair2015** [comment]
@Tyler3D  Oh lol xD is 5

**Comment by AlexandriteErikParacelsus** [comment]
@Jhair2015 gamemode 4 is experimental LMS

**Comment by NameYT** [comment]
@Megabyte918 @Tyler3D Doesnt work!! I killed a bot but they keep spawning :3

**Comment by AlexandriteErikParacelsus** [comment]
@NameYT you need to wait m8 until LMS started

**Comment by Tyler3D** [comment]
@NameYT Yea, I just posplited myself with a bot. 5 Seconds later I realize I can't spawn. *facepalm*

**Comment by AlexandriteErikParacelsus** [comment]
@Tyler3D Nice

**Comment by PrinceDark9243** [comment]
Can some one explain the gamerserver.ini Config about LMS!

**Comment by AlexandriteErikParacelsus** [comment]
# [LAST MAN STANDING]
# When it starts/ends is decided randomly just like vanilla, based on the values below
# lastManStandingShortest: Shortest amount of time possible before LMS happens in minutes
# lastManStandingLongest: Longest amount of time possible before LMS happens in minutes
# lastManStandingKickShortest: Shortest amount of minutes till kicking time
# lastManStandingKickLongest: Longest amount of minutes till kicking time

**Comment by MastaCoder** [comment]
@AlexandriteErikParacelsus Too small, I can't read, can you make it bigger?

**Comment by Tyler3D** [comment]
@MastaCoder Lol

**Comment by Megabyte918** [comment]
This is now a command.

**Comment by MastaCoder** [comment]
Aw that sucks, we can't use it in the config anymore? (So it's the default gamemode?)

**Comment by Megabyte918** [comment]
Me and Tyler decided it would be best to have a command, that way you could activate it at any time in any gamemode

**Comment by MastaCoder** [comment]
But that wouldn't really make sense if it's a gamemode, you should add an option to have it auto start in the config 👍

**Comment by Megabyte918** [comment]
So your saying, if the config is enabled, it starts/ends randomly in any gamemode?

**Comment by MastaCoder** [comment]
Nope, something like a gamemode. Let's say a user has LMS running on FFA. However the server turns off and turns back on, it'd go into LMS by itself and start all over again.

Of course I can add this to my own server easy, but I'm just giving the suggestion for others. 👍

**Comment by Megabyte918** [comment]
Alright sounds good
