### ISSUE TITLE
Server Commands

### ISSUE THREAD

**Issue by smky** [Megabyte918/MultiOgar-Edited#691]
How would I initiate a console command at a certain time or interval? For example, how would I run "examplecommand" every time the server starts, or every set number of seconds?

**Comment by Tyler3D** [comment]
@smky At the bottom of GameServer.start do
var CommandList = require('./modules/CommandList');
var split; // What every you want. For example I could do {"mass", 1, 10000} to give mass of 1000 to id 1.
setInterval(function() {CommandList.CommandList.reset(this, split)}, 60 * 60 *1000) // Multiply the num of seconds times 1000. This is one hour

**Comment by smky** [comment]
Thanks! (I'm aware of how time works in javascript)

**Comment by MastaCoder** [comment]
Isn't that already a code sample? Just add it to the code and it should work fine.

**Comment by MineMooreALT** [comment]
Makes no sense to me can you give a example with board ? thanks

**Comment by chewydev** [comment]
Why do you think I asked for an example, didn't make any sense @Tyler3D @MastaCoder @MineMooreALT

**Comment by MastaCoder** [comment]
**At the bottom of GameServer.js do**
var CommandList = require('./modules/CommandList');
var split; // What every you want. For example I could do {"mass", 1, 10000} to give mass of 1000 to id 1.
setInterval(function() {CommandList.CommandList.reset(this, split)}, 60 * 60 *1000) // Multiply the num of seconds times 1000. This is one hour

Could the bolding not be any clearer?

**Comment by chewydev** [comment]
Alright smartass

**Comment by MineMooreALT** [comment]
how would you change it to board tho it makes no fucking sense to me

**Comment by MastaCoder** [comment]
And that's where your efforts of actually trying to learn JavaScript come in. I can't spoon feed you all the code, go and spend time learning to code.

**Comment by chewydev** [comment]
@MastaCoder I'm actually fluent in JavaScript, but i'm not familiar with Node.js or how MultiOgar/MultiOgar-Edited works.

**Comment by MineMooreALT** [comment]
mate the code you gave doesn't even work what do you expect I don't understand how multiogar functions really work. I'm a web developer, not a nodejs developer.

**Comment by chewydev** [comment]
I'm with @MineMooreALT, the code doesn't work...

**Comment by MineMooreALT** [comment]
`var CommandList = require('./modules/CommandList');
var split; // What every you want. For example I could do {"mass", 1, 10000} to give mass of 1000 to id 1.
setInterval(function() {CommandList.CommandList.reset(this, split)}, 60 * 60 *1000) // Multiply the num of seconds times 1000. This is one hour` makes no sense too, what is split supposed to be? is it supposed to be like var split = {"mass",1,10000}; please explain it better this should be a simple taskbut is proving difficult.

**Comment by chewydev** [comment]
Also, @Tyler3D stated that it should be placed at the end of ```Game.prototype.start```, while @MastaCoder sai it should be placed at the end of the ```GameServer.js``` itself.

**Comment by MineMooreALT** [comment]
Please respond with working answer
