### ISSUE TITLE
Mass food issues

### ISSUE THREAD

**Issue by ASDFGerte** [Megabyte918/MultiOgar-Edited#692]
First of all, food collides with ejected mass. While this is neat, it costs a lot of performance and is not how real agario behaves. I already did a premature dirty fix for my own version to prevent food from colliding, however, a proper version (two quad trees? Food should only be checked in the quad tree part around each player - this is a performance thing because food nodes are by far the most) and if need be a setting would be nice.

Secondly, having a lot of food (e.g. just set maxfood to something high and create a 10000+ mass mothercell and wait for it to eject all food) causes weird issues: Apparently the client starts processing ticks slower than the server speed if too much food is in vision range (client side issue? Normal agario can handle a LOT of food though!). All commands' effects are appearing absurdly delayed, however, the server appears to be answering just fine (e.g. clearing the field and joining with another client will behave just fine, the original client will still be slowly showing what happened, like a movie).
I am suspecting the client cannot drop ticks, as there is no resynch feature. The network buffers are then huge, therefore it then just displays this "video" when it cannot keep up. However, as already noted, normal agario can handle a LOT of mass, therefore i think it stems from the server sending something which causes the client to be slower than on normal agario. I cannot be sure about it though, it might simply be a client side issue.

**Comment by AlexHGaming** [comment]
Normally the update before made ejected mass collide, I think @Megabyte918 forgot the food entity to be replaced off this code.
And a lot of food can cause lag. It doesn't lag if you play agar.io because Miniclip hosts it on a good website.

**Comment by ASDFGerte** [comment]
#1: I see

#2: As described, the client is lagging behind - the server has no real problems and bandwidth cannot be the issue*. The only reason why i suspect this is not purely a client-side issue (could be anyways) is because this behavior doesn't seem as bad on real agario (yet still existant, very large amounts of food will lag the client on real agario - hard to test, just from experience with servers on last man standing where you grow by feeding mothercells and then waiting).

*if it ran on localhost, for obvious reasons. In this case because the server it was tested on has tremendously more upload-bandwidth than my home connection's download could ever handle plus it is quite close and has a stable low ping.

**Comment by AlexHGaming** [comment]
Majority of us have watched the Wun Wun 88k experimental LMS video. He did find it extremely lagging like over 2000 foods, over 2x mass.
My client does lag a tiny bit when skins are on when in 16 pieces worth around 2000-3000 mass (32k-48k all together) 
But what I find funny is using his skin script, I go into 16 pieces with same mass - no lag.
Bandwidth isn't really a matter. Turning wifi off while in ur SOLO server (127.0.0.1) won't close you, as it doesn't need wifi, wifi bit is for connecting to it.

**Comment by Megabyte918** [comment]
@ASDFGerte 
> First of all, food collides with ejected mass. While this is neat, it costs a lot of performance and is not how real agario behaves.

I could not reproduce this behavior on the latest version.

> Food should only be checked in the quad tree part around each player

This already happens, collisions between players & food are only checked if their boundaries intersect.

As for the food & client lagging issue, it is normal behavior for the vanilla client.

**Comment by ASDFGerte** [comment]
@Megabyte918 
Did additional tests, appears to be happening with food ejected from mothercells only - [Demonstration](http://i.imgur.com/oEBEEQ6.gif). This might also explain the second issue, guess is food from mothercells has constant updates being sent. Second might also be related to #648, as i was also using the same extension for tests.

**Comment by Megabyte918** [comment]
@ASDFGerte Should be fixed after recent updates

**Comment by ASDFGerte** [comment]
Yes, mothercell food colliding with ejected mass seems to be fixed, thanks. Can't tell if that also improves lags client with mass food, but that's still possibly a client issue and there are other open issues for related bandwidth problems, so this should be done.
