### ISSUE TITLE
How to make food spawn faster? And How to

### ISSUE THREAD

**Issue by SambyAgarYT** [Megabyte918/MultiOgar-Edited#693]
How to make the food spawn faster? How to make player spawn near on the dead point? like dual?

**Comment by SambyAgarYT** [comment]
@Megabyte918 @AlexandriteErikParacelsus @FantasyIsBae @Tyler3D
Help?

**Comment by alktbihd** [comment]
ah thats hard

**Comment by smky** [comment]
I wish I knew, most of these questions this repo gets are good gamemode ideas.

**Comment by MastaCoder** [comment]
It's in the gameserver.ini..

**Comment by Jhair2015** [comment]
ejectSpawnPercent = 100000000000000000

**Comment by Jhair2015** [comment]
:trollface:

**Comment by Luka967** [comment]
:trollface:

**Comment by AlexHGaming** [comment]
:trollface:

**Comment by SambyAgarYT** [comment]
@Jhair2015 Please help?

**Comment by MastaCoder** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini

**Comment by SambyAgarYT** [comment]
@MastaCoder Which Line?

**Comment by MastaCoder** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L103

**Comment by SambyAgarYT** [comment]
@MastaCoder TY :)
