### ISSUE TITLE
Gamemodes

### ISSUE THREAD

**Issue by smky** [Megabyte918/MultiOgar-Edited#694]
Does anyone know where I could find up to date gamemodes for multiogar?

**Comment by ZfsrGhS953** [comment]
There are lots of them [here](https://github.com/ZfsrGhS953/Petridish-Ogar). **However**, you'll need to port them to MultiOgar-Edited, and if you do, your server's performance will decrease.

**Comment by smky** [comment]
What do you mean by "port" @ZfsrGhS953?

**Comment by ZfsrGhS953** [comment]
@smky Change the code to make it compatible with MultiOgar-Edited.

**Comment by smky** [comment]
@ZfsrGhS953 hell nah

**Comment by MastaCoder** [comment]
nice.
