### ISSUE TITLE
Random spawn position 

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#695]
Hello , i think that be good make the random spawn position according the last death position

In summary, if you die in C4, you will look for a safe position but the closest to C4, if there is a safe position in E5 and another in C5, the respawn will be in C5

**Comment by Luka967** [comment]
> SambyAgarYT you not know about JS AND YOU SAID "I FIXED" AHHAHHA

People will immediately assume you know JS, and if you do, do it yourself.

**Comment by AlexHGaming** [comment]
lmao

**Comment by AlexHGaming** [comment]
var savage = Luka967
Savage at comments these days *
var CAP = get.savage copy.and.paste 
savage CAP *
Sorry for errors, im shit at coding lol. But hey! I'm learning slowly and not triggering over other comments
*gyeyoqu triggered*

**Comment by gyeyoqu** [comment]
var human = 7.000.000.000 * luka967.idiocy;

for ( var luka967 = idiocy; luka967 > Human.idiocy; luka967++)

L O L IS INFINITEEEE

**Comment by MastaCoder** [comment]
or you know you could have just used while (true) but ok.

**Comment by Luka967** [comment]
k

**Comment by Tyler3D** [comment]
There is syntax errors and logic errors

**Comment by Megabyte918** [comment]
The random spawning system you are describing isn't how vanilla servers behave.
