### ISSUE TITLE
Cooldown and Spect Speed

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#696]
You can make a configurable Cooldown for MinionFeed and Spectator Speed

**Comment by Luka967** [comment]
> SambyAgarYT you not know about JS AND YOU SAID "I FIXED" AHHAHHA

People will immediately assume you know JS, and if you do, do it yourself.

**Comment by Jhair2015** [comment]
Hahaha read me my mind @Luka967

**Comment by Tyler3D** [comment]
if (typeof @Luka967 === 'savage')
Write something on GitHub
Else
Don't write something on GitHub

**Comment by Luka967** [comment]
```js
user = @Tyler3D;
if (user.personality.indexOf("funny") !== -1)
    @Luka967.write(@Megabyte918, "MultiOgar-Edited", #696, "@Tyler3D ur funny");
else return;
```
Output:

>@Tyler3D ur funny

**Comment by gyeyoqu** [comment]
currently im working in C++ , Pawn and GML , im newbie on JS

**Comment by gyeyoqu** [comment]
@Luka967

**Comment by Luka967** [comment]
There's this thing called the Internet. In it is a website called Google. You can go to it by typing http://www.google.com into the address bar of your browser. Unless you're living under a rock you should know that Google is a search engine and can search stuff. Use this to search "javascript tutorials".

I know HTML, CSS, JS, C#, VB and a little bit of PHP, C++, Python and Lua.

**Comment by ItzLevvie** [comment]
@gyeyoqu http://lmgtfy.com/?iie=1&q=javascript+tutorials

**Comment by Luka967** [comment]
@ItzLevvie Thank you, im a lazy ass xD

**Comment by Megabyte918** [comment]
@gyeyoqu There already is a configurable cooldown for minion-feeding, its called `ejectCooldown`
And what do you mean by "Spectator speed?"

**Comment by MastaCoder** [comment]
If you mean by slowing down camera movement in spectate, never happening.

**Comment by Agarian** [comment]
@gyeyoqu For your first question, you can edit the config `ejectCooldown`.
For your second question, I USED to know how, until a recent update almost completely changed the spectate code in `PlayerTracker.js`.
