### ISSUE TITLE
How to make splits or divisions like Dual Agar plsss???

### ISSUE THREAD

**Issue by TheDark99** [Megabyte918/MultiOgar-Edited#697]
title :D

**Comment by MastaCoder** [comment]
So you take the square calculation of mk2 and make it equal the power of 1ee3 and update the main nodes files to get into the main system root. Then you just need to update x to become y and bam, easy splits!

**Comment by Tyler3D** [comment]
@MastaCoder Don't forget to divide by zero and cause integer overflow

**Comment by MastaCoder** [comment]
Alright, hacking into the mainframe right now!!111! :trollface:

**Comment by Jhair2015** [comment]
:trollface:

**Comment by Megabyte918** [comment]
Reduce the split velocity in gameserver.ini.
