### ISSUE TITLE
Space1.io

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#698]
We Should make a server for Space1.io, Its actually a very fun game

**Comment by Luka967** [comment]
*Few* problems:

1. It's made by Miniclip.
2. It's made with WebGL.
3. The protocol is unknown.
4. It's made by Miniclip.
5. It doesn't use WebSockets.
6. The protocol is unknown.
7. It's made by Miniclip.
8. The JS wasn't deobfuscated by anyone for now.
9. Bounding boxes for bullets aren't aligned.
10. It's made by Miniclip.
11. Nobody here knows non-AABB or isosceles triangle collision.
12. [It's not trivial to do it](https://www.geometrictools.com/Documentation/DynamicCollisionDetection.pdf).
13. It's made by Miniclip.

**Comment by Jhair2015** [comment]
14. It's made by Miniclip.

**Comment by F0RIS** [comment]
Alis_io already made similar game mode

**Comment by Tyler3D** [comment]
It's possible to recreate in agar.io. I'm too lazy to learn Websockets in c# or C++.

**Comment by Logan7432** [comment]
Lol, but couldn't you just take agario and make it shot lines instead of splitting like spaceio

**Comment by AlexHGaming** [comment]
1. I don't understand how this is project-related.
2. Miniclip made the game. Not Matheus (agar.io)
3. We don't have a clue what protocol the server's running at.
4. Is it wrote with JS? No I dont think so.
5. NOT project related!

**Comment by Logan7432** [comment]
@AlexHGaming It was a suggestion that the team that made this should make a space io. We realized that it's impossible to make a server for this at the moment.
