### ISSUE TITLE
new update? connecting

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#701]

**Comment by Tyler3D** [comment]
@Megabyte918 Wtf protocol 13

**Comment by Tyler3D** [comment]
Leaderboard Broke again fukkkkkkkkkkkkkkkkk

**Comment by Jhair2015** [comment]
shittt fuck you miniclip.

**Comment by Tyler3D** [comment]
Miniclip is trolling xD. Protocol 7 to 9 to 11 to 13 wtf

**Comment by Jhair2015** [comment]
Wtf

**Comment by Logan7432** [comment]
Just make a client instead of Agar.io. http://forum.ragezone.com/f927/release-agario-server-files-webclient-1078500/

**Comment by SAVAGE2001** [comment]
i hate miniclip

**Comment by AlexHGaming** [comment]
Noooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by AlexHGaming** [comment]
I FUCKIN HATE MINICLIP
