### ISSUE TITLE
New Agar.io update changes

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#703]
-  Experimental spawnercells are a bit bigger (25% or something)
- On yourself, you have a weird yellow outline on the outside of your cell, with the skin being inside
- Moving system dramatically changed when you are small.
Please comment below what other things have changed, excluding the main menu and this 'friend online' bit.

**Comment by imnotNxhz1** [comment]
Primero :) xD

**Comment by SambyAgarYT** [comment]
TEXT ARE FUCKING BIG LOL @AlexHGaming

**Comment by Luka967** [comment]
Jesus that sounds retarded

**Comment by MineMooreALT** [comment]
Lmfao wtf r they trna make it like mobile

**Comment by cowpits** [comment]
the agar client is now officially crap and holy lag. i have a fast system and i barely get 60fps on my gtx 980 card wtf. lol

**Comment by ItzLevvie** [comment]
This is probably the worst Agar.io update I've ever seen

**Comment by Tyler3D** [comment]
Really. I noticed a performance boost. I can play with 5000 minions on agar.io now but before lagged with 1000

**Comment by Luka967** [comment]
Text drawing now has very interesting traits - it's not anti-aliased and it doesn't use the old scaling technique, both of which are the same with my Cigar fork. Seems like they've ported it over lmao
Nice job Miniclip, nice job.

**Comment by Luka967** [comment]
I also have 20 FPS now, it was solid 60 before with drops in Party mode.

**Comment by Luka967** [comment]
![image](https://cloud.githubusercontent.com/assets/15956695/24296587/f03ff046-109f-11e7-8dbc-af908c024ede.png)
Frames take 33ms for no apparent reason. They're obviously forcing 30 FPS.

**Comment by Luka967** [comment]
> Text drawing now has very interesting traits - it's not anti-aliased and it doesn't use the old scaling technique, both of which are the same with my Cigar fork. Seems like they've ported it over lmao

Forget that. They're not even caching the text, they're drawing them raw. That explains why there's no anti-aliasing.

**Comment by Megabyte918** [comment]
@AlexHGaming 
> Experimental spawnercells are a bit bigger (25% or something)

This has not changed, they are the same size as they have always been

> On yourself, you have a weird yellow outline on the outside of your cell, with the skin being inside

Pretty sure something like this is client sided.

> Moving system dramatically changed when you are small.

Nah, it's still the same :)

Oh and I also have experienced worse FPS after this update, even with everything turned off (skins, names, etc)

**Comment by AlexHGaming** [comment]
> This has not changed, they are the same size as they have always been

I swear they have, I see them bigger.

> Prettty sure something like this is client sided

Yes I am aware of that, I'm just noting what's new, not about the changes we're about to make....right?

> Nah, it's still the same :)

For some reason, the turning sensitivity increased. Moving then pointing the cursor somewhere else, it reacts very quick and goes that way as soon as the cursor reaches it. Old version didn't do this.... I think.

Now moneyclip is gonna keep this update and the game will die quicker.

**Comment by AlexHGaming** [comment]
The yellow outline has now been removed.

**Comment by Tyler3D** [comment]
wtf

**Comment by Luka967** [comment]
Nope, mother cells still have 222 mass.

**Comment by cowpits** [comment]
omg look at the font size lol

**Comment by AlexHGaming** [comment]
oh kk @Luka967

**Comment by AlexHGaming** [comment]
@Luka967 Doesn't the mothercell now shoot out food entities very quick? Because I had deposited mass into the mothercell on a wall and it shot out food fast. Or am I just imagining things?

**Comment by Luka967** [comment]
@AlexHGaming They do, 2.5x faster.

**Comment by Megabyte918** [comment]
The food itself shoots out at a faster speed? Or the rate of the food being shot out is faster?

**Comment by mrzack506** [comment]
I dont like that Lock of 60 FPS

**Comment by Luka967** [comment]
@Megabyte918 Both, food velocity to a lesser degree though.

**Comment by smky** [comment]
Guys, the movement hasn't changed at all, the only thing that changed is the **camera** movement.
@AlexHGaming

**Comment by AlexHGaming** [comment]
Why's it off-topic? 😂

**Comment by MastaCoder** [comment]
i couldn't find any other tags, ehh it's not really related to MultiOgar, rather than the crap moneyclip did.
