### ISSUE TITLE
A fix for agar.io client update, not an issue

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#704]
Not sure if this was posted but to get the agar.io client to work on private servers after 3/23/2017
change the 11 to 13 in PacketHandler.js line 38
  if (this.handshakeProtocol < 1 || this.handshakeProtocol > 11) {

You'll be able to play but leaderboard is shot. I have no idea how to fix that yet.

**Comment by Tyler3D** [comment]
That was already done lol

**Comment by cowpits** [comment]
oh nice, lol i'm always late to the party. leaderboard too?

**Comment by gyeyoqu** [comment]
wow @cowpits , best update 4 ever , thanks for your knowledge

**Comment by NiesamoWhite** [comment]
Where is the leaderboard?

**Comment by AgarXTRA** [comment]
Yea. Where is the leaderboard?

Raga.pw fixed it ...

**Comment by NiesamoWhite** [comment]
@AgarXTRA Nop men

**Comment by AgarXTRA** [comment]
Where is the leaderboard?

**Comment by MineMooreALT** [comment]
I wan't the leaderboard too.

**Comment by cowpits** [comment]
we all do but who cares about the agar.io client if you have a private server just get the cigar client from Luka967 or any other client like alis.io which most people like.

**Comment by AlexHGaming** [comment]
No, Cigar client is so outdated.
And the leaderboard needs to be fixed by putting more code in to make it work, it won't just work the way you want it to work without putting code.
You do need some patience.

**Comment by cowpits** [comment]
i'm not sure what you mean that it needs a lot of work. i'm using this https://github.com/Luka967/Cigar
and seems to work fine. here's what it looks like for me http://gkclan.tk 
i don't need additional work lol.

**Comment by AlexHGaming** [comment]
@cowpits Lol I have a video up on how to fix this, so you don't need to make a video on it :D

**Comment by cowpits** [comment]
oh no i'm not making one for it lol.

**Comment by AlexHGaming** [comment]
@MastaCoder If you're gonna add a bug label atleast change the title to fixing the leaderboard

**Comment by AlexHGaming** [comment]
Otherwise putting a bug label for fixing something makes no sense

**Comment by MastaCoder** [comment]
A fix for agar.io client update, not an issue - Client has an update - MultiOgar needs to be updated - It's a bug. I don't see why we need to get into so many specifics if we already know it needs to be fixed..

**Comment by AlexHGaming** [comment]
eh true

**Comment by NuclearC** [comment]
Leaderboard now has packet opcodes: 0x33(ffa/exp) 0x34(party) 0x32(teams)
0x32 is the same for teams(uint32,float,float,float)

0x33 is like this:
(uint8) packet opcode
(null_str8) names
....

0x34 is like ffa, but:
(uint8) op
(uint16) if player spawned, its 1 otherwise 0 (idk lol)
(null_str8) names
...
(uint16) player position in leaderboard

**Comment by Agarian** [comment]
The show mass feature does not actually show, unless you have a name now. And the enlarged names are HORRIBLE LOOKING!

**Comment by NuclearC** [comment]
I know right, Moneycrap is going to destroy our game lol

**Comment by MastaCoder** [comment]
According to their Twitter, the 30FPS thing was done on purpose since "It was CPU intense". 🤦‍♀️

**Comment by cowpits** [comment]
lol  "It was CPU intense" 
well now it's "jitter intense"

**Comment by Tyler3D** [comment]
@NuclearC How do you decode the packets? Tampermonkey script or something else?

**Comment by Tyler3D** [comment]
Agar.io thinks I have 2 Billion Friends xD

**Comment by Tyler3D** [comment]
I think there is a flag missing for when you are in the leaderboard

**Comment by NuclearC** [comment]
@Tyler3D i made my agar.io bots and client, i know how to decode packets and with some C++ debugging i can easily detect packet errors and try to decode them.

**Comment by F0RIS** [comment]
@NuclearC 
c++ debugging? can u describe what u use for it?

**Comment by NuclearC** [comment]
@F0RIS Visual Studio 2017 :D

**Comment by NuclearC** [comment]
@F0RIS actually Visual Studio is 65 gb to install lol, better with wireshark if you dont know the whole agar.io protocol

**Comment by Luka967** [comment]
I use 2010, it's 4gb xD

**Comment by MastaCoder** [comment]
2010 was bae.

**Comment by FantasyIsBae** [comment]
@MastaCoder Like me? lol

**Comment by MastaCoder** [comment]
lmao xD

**Comment by NuclearC** [comment]
ugh no 2017 is the best ;P

**Comment by Luka967** [comment]
xd

**Comment by Luka967** [comment]
I installed 2015 on my laptop once. Load time was 2 minutes xdddddd

**Comment by NuclearC** [comment]
@Luka967 try the 2017, they fixed that shitty load times xD now it takes me 5-15 seconds to startup VS2017

**Comment by MastaCoder** [comment]
https://gyazo.com/d4fb1548c944c071a043d077e77562b0

@NuclearC gotchu
