### ISSUE TITLE
 The server stops when you press P

### ISSUE THREAD

**Issue by AgarXTRA** [Megabyte918/MultiOgar-Edited#708]
Lol. as soon as I press '' P ''  to collect pellets the server close and get error.

![skarmklipp](https://cloud.githubusercontent.com/assets/24947744/24320698/90ce7ff6-113a-11e7-9053-376fba4ef3b6.PNG)

(I use the latest version)

**Comment by MineMooreALT** [comment]
Must be a error with the collect pellet feature

**Comment by Megabyte918** [comment]
Should be fixed now.
