### ISSUE TITLE
Splits are like in mobile. pls fix this 

### ISSUE THREAD

**Issue by PsychoAgarioYT** [Megabyte918/MultiOgar-Edited#711]
I can't even splitrun. splits are like in mobile agario.
fix physics pls. also mobile physics are set to 0 but it still is like that :/

**Comment by MastaCoder** [comment]
Didn't moneyclip do something to the client making cells look a lot smaller making the physics looks weird?

**Comment by Megabyte918** [comment]
This is a comparison of the splits in 1.5.0:
https://streamable.com/mos96

This is a comparison of the splits now:
https://streamable.com/nuf1h

**Comment by MastaCoder** [comment]
Exactly! I see nothing different between the two versions, it's just text is so big that it makes everything just look weird. When I was playing, I kinda felt as if some of the cells were bigger than they were supposed to be. I don't know if that's just me though lmao

**Comment by AlexHGaming** [comment]
When camera angle zooms out, the text font stays the same as it was before the zooming out

**Comment by MastaCoder** [comment]
As @Megabyte918 said, the splits are pretty much the same.
