### ISSUE TITLE
Minion ...

### ISSUE THREAD

**Issue by vincent95330** [Megabyte918/MultiOgar-Edited#712]
How did you do to patch the bots with tampermonkey extension ?

**Comment by ZfsrGhS953** [comment]
@vincent95330 You don't need any "tampermonkey extension" at all, just type "minion (player ID) (amount) (name)" in the console. If the minions don't come to you, you entered the wrong player ID. If the minions don't spawn at all, you either made a typo in the command or connected to the wrong server.

**Comment by vincent95330** [comment]
@ZfsrGhS953 The problem is not here, it's just that people come in my server and put minions all alone, so the server lag ..

**Comment by ZfsrGhS953** [comment]
@vincent95330 Decrease serverMaxConnections.

**Comment by vincent95330** [comment]
@ZfsrGhS953 Yeah but I do not want to restrict them, I just want to forbid them so that they do not, for example with this version we can't add minions with proxy bots while in the other multiogar project we can. I would just like to know what the designer of this multiogar has adorned for fixed this

**Comment by MastaCoder** [comment]
Well we are doing what we can to stop minions with minion threshold. There are no other ways at the moment to patch minions that wouldn't hit performance.

If we did have a patch, it'd already be in the software.
