### ISSUE TITLE
how enter to the server from alis.io?

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#714]

**Comment by Jhair2015** [comment]
delete your cookies

**Comment by imnotNxhz1** [comment]
pero pongo  la direccion y me pone  en el los servidores de alis :´v    (creo que hablas español)

**Comment by Jhair2015** [comment]
Pués Si xD >:v haber intenta F12, luego da click en un servidor y cambia el servidor por el tuyo

**Comment by imnotNxhz1** [comment]
no funciono :´v    http://i.imgur.com/BML4FfJ.png

**Comment by Jhair2015** [comment]
http://shairplus.tk/ mejor usa ese :v tiene split animation PD: es mio

**Comment by imnotNxhz1** [comment]
no tendras un cliente parecido a  alis que me partrocines? :´v    muy bueno tu juego papuh 7u7

**Comment by Jhair2015** [comment]
si xD :v pasame tu skype

**Comment by imnotNxhz1** [comment]
se me olvido la contraseña :v xD  pero creo que me  gusto mas el estilo de tu juego :v

**Comment by Jhair2015** [comment]
ste men :v al menos tienes facebook? :v ste es mio https://www.facebook.com/JimmyMC.Movi

**Comment by Megabyte918** [comment]
Please search for your issue to see if it's duplicated before making it, this has been asked many times.
