### ISSUE TITLE
LMS Gamemode

### ISSUE THREAD

**Issue by chewydev** [Megabyte918/MultiOgar-Edited#715]
I know LMS is already implemented, but can someone gimme an example of a up-to-date LMS gamemode for this MultiOgar repo? Preferably I would like to have the server shutdown after 5 seconds when only 1 player is left.

**Comment by AlexandriteErikParacelsus** [comment]
kok

**Comment by MastaCoder** [comment]
> If it existed, it would have already been added or is on another repo.

**Comment by SambyAgarYT** [comment]
@MastaCoder Mind helping me? About Popsplits?

**Comment by MastaCoder** [comment]
If this is about making popsplits better, nope.

**Comment by SambyAgarYT** [comment]
@MastaCoder Question 1 : Macro = Posplit?!

**Comment by SambyAgarYT** [comment]
They dont work for me tho even without macro i dont know lol. i did not edit any.. i tried like 10x trying to popsplit

**Comment by SambyAgarYT** [comment]
@MastaCoder I think there is a code for slowly posplit thing?!

**Comment by MastaCoder** [comment]
That'd be best on client side, just get a macro that auto does the action for you. Try tampermonkey scripts.

Well slow popsplits, just add a settimeout for the script.

**Comment by SambyAgarYT** [comment]
@MastaCoder Thanks for answering but i think i have to change the Virus.js from somewherE?

**Comment by MastaCoder** [comment]
To change a popsplit macro? I don't think you even need to touch the server for that.

**Comment by Jhair2015** [comment]
@MastaCoder to popspñit since server
