### ISSUE TITLE
Not to be that guy, but...

### ISSUE THREAD

**Issue by AgarXTRA** [Megabyte918/MultiOgar-Edited#716]
You behind this project call yourself for programmers and developers etc, but you can not even fix such simple things as the leaderboard after the new Agario update? A bit funny (:-D) but tragically... Not to mention the ''ERTP'', when the minion feed you it stop the player and it starts lagging. And the game's physics in general are not the best and could be improved. A joke when compared to the original Agar.io. But but...

Please fix the leaderboard!

**Comment by AlexHGaming** [comment]
If it is such a simple thing to do, why can't you do it yourself?
Why do we have to do the work for you? Learn javascript and do it yourself if it is so called 'easy'
And I don't really understand how this is an issue...

**Comment by Luka967** [comment]
You behind this issue call yourself "not that guy" but you're behaving like one.

We're not connected with Moneyshit or Zeach in any way and we still don't know the new protocol's changes.
Intercepting raw bytes and figuring out what they do isn't easy at all. Try it yourself. Even though forairan and other people have already done this in the past it's not trivial to sit and look at numbers for a few hours all the time.

We're also doing this in our free time, as a hobby, and as you might have seen already nobody has time.

If the performance of this project isnt satisfying your demand then you should make an agar server emulator from scratch.

Please stop whining about our inactivity and try actually doing something productive.

@MastaCoder please close

**Comment by AlexHGaming** [comment]
This is why we need more collaborators, #MakeLukaCollaborator
Honestly issues are just getting lame these days

**Comment by AlexHGaming** [comment]
#700

**Comment by AlexHGaming** [comment]
#700

**Comment by Tyler3D** [comment]
@AgarXTRA What's wrong with the physics too. Get your 1,000,000,000 frame camera out and show a video instead of complaining.

**Comment by Luka967** [comment]
@Tyler3D kek'd

**Comment by AlexHGaming** [comment]
In fact, I have an idea
If it's so easy to do, do a pull request on it instead of whining to us.

**Comment by Tyler3D** [comment]
The O.P apparently has a lot of money -> https://github.com/Megabyte918/MultiOgar-Edited/issues/621
He should contribute to MIT making a 1,000,000,000 camera lol -> https://www.wired.com/2011/12/is-this-really-one-trillion-frames-per-second/

**Comment by Luka967** [comment]
triple kek

**Comment by AlexHGaming** [comment]
quad kek

**Comment by AlexHGaming** [comment]
why dis not closed?
@Megabyte918 @MastaCoder

**Comment by MastaCoder** [comment]
Sorry I was at school.

My response: Do it yourself or don't say anything at all.
