### ISSUE TITLE
Pellet mode not working

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#718]
So I've set my "collectPellets" to 1 and have tried hitting P with bots and nothing had happend.
Is there anything wrong? Or am I doing it wrong?

**Comment by freaky767** [comment]
oops just noticed spelt "Pellet" in the title wrong :P

**Comment by Jhair2015** [comment]
Download the last version.

**Comment by freaky767** [comment]
I've already changed the code from the commit into the old 1.6.0 multiogar edited

**Comment by AlexHGaming** [comment]
Did you install the Tampermonkey script?

**Comment by freaky767** [comment]
yes

**Comment by Megabyte918** [comment]
Could not reproduce. Make sure you are using the latest version along with the `collectPellets` config set to 1, and `disableERTP` set to 0

**Comment by freaky767** [comment]
collectPellets is set on 1 and disableERTP is on 0 and I wasn't on the vanilla client, but on a different client which had the E R T and P script already in it. I did use the client on a different MultiOgar-Edited and the pellet mode worked just fine

**Comment by freaky767** [comment]
I just tried it on the original vanilla client and it isn't working

**Comment by AlexHGaming** [comment]
I don't experience any issues.
Are you sure you didn't change anything about minions in the files? Are you
sure that the ERTP matches agar? Maybe reinstall a draft server, with
everything unedited, then only change the collectPellets and ERTP controls
in the gameserverini

**Comment by freaky767** [comment]
Ok
will try

**Comment by freaky767** [comment]
I do not edit the gameserver.ini file, I just edit the gameserver.js file and then delete the gameserver.ini

**Comment by freaky767** [comment]
Also please @Megabyte918 fix the decay

**Comment by AlexHGaming** [comment]
You can mess with the decay in the gameserver.ini
The more higher the value, the more mass decay reducts.

**Comment by freaky767** [comment]
Ok it does work in the latest version, I still don't know why it doesn't work on the old 1.6.0 which I edited the code with the commit.

**Comment by freaky767** [comment]
When Megabyte did the commit about the minionplayer, I copied the code and then put in my 1.6.0 of multiogar-edited
