### ISSUE TITLE
Just a question...

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#719]
So i'm just wondering why keep updating this version of MultiOgar when Tyler3D made a better version of MultiOgar https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited with plugins and cool gamemodes. Theres so many things you can add to his to make it better and more fun! The only problem is since hes the only one working on it its a little buggy and doesn't get updated often. If all the people on here worked on his version it would be so much better then this. Its literately the same besides being on an older version but with plugins!

**Comment by AlexHGaming** [comment]
I don't understand how this is even an issue...

**Comment by Logan7432** [comment]
@AlexHGaming If you would read it, you would realize that this isn't a issue and that its a question by the title, And since theirs not section on github to ask questions where am I suppose to put this? Exactly Right where it is.

**Comment by AlexHGaming** [comment]
Well don't say it in an issue then

**Comment by Logan7432** [comment]
@AlexHGaming Where do I put it exactly? Maybe Create a section just for questions so people dont have to keep opening issues.

**Comment by AlexHGaming** [comment]
Or just don't say it at all. We're a project to maintain performance, not make bugs. We are trying to make it like real agar. Having fun is what you have to make yourself.
Plugins and cool gamemodes is what we might want, but we are trying to handle performance. What we currently have is fine enough, balanced performance and game balance. It looks like real agar near enough...
Although @Megabyte918 might want to add gamemodes, **we're making it look like real agar**, if you want gamemodes, great! Use Tyler's fork!

var UselessIssue = "#719'
if UselessIssue reaches '#700' 
this.closeIssue

**Comment by AlexHGaming** [comment]
I made one fucked up code there ;D

**Comment by Logan7432** [comment]
@AlexHGaming I understand but the people that having the features like adding plugins is just something awesome/extra you could add to improve your server which is what Tyler3D did. Having it just like the real Agar is fun and all but you want to be able to switch things up and customize your server to your liking so your users have more fun.

**Comment by Logan7432** [comment]
@AlexHGaming And the problem with Tylers fork is nobody helps him improve it and he just 
dosnt have the time to fix everything

**Comment by AlexHGaming** [comment]
Eh you got a point

**Comment by Megabyte918** [comment]
I do not want this project to be like what Ogar-Unlimited used to be. If you want a more "OgarUnlimited" esc experience, then use Tyler's fork.

**Comment by Logan7432** [comment]
@Megabyte918 Im just trying to say he kinda needs help

**Comment by Jhair2015** [comment]
You want us to fix some bugs from that fork, 

I did it, it's pretty easy, just try to understand the code and see what's wrong and if you can not, you can compare this MegaByte fork and solve problems like PopSplit, Mass, fix ERTP (make it work with Q - ERTP), and I also fix the autestart, and leaderboard + position (so that it does not show the position, but only the mass).

**Comment by Logan7432** [comment]
@jhaie2015 I new to coding. I'm not capable of fixing broken code yet. I just need someone's help to fix the plugins for Tyler3ds fork

**Comment by Tyler3D** [comment]
Lol I accidentally replaced my version with this verison. I'm noob at github. So I'm trying to fix everything that broke. But, I don't have much free time. I have a test tomorrow :/
