### ISSUE TITLE
How to ...

### ISSUE THREAD

**Issue by SambyAgarYT** [Megabyte918/MultiOgar-Edited#721]
How to make anti team?? , like all of us is lossing 500 mass? in 5 seconds how to do that?
@Megabyte918

**Comment by MastaCoder** [comment]
Increase decay?

**Comment by proxiemind** [comment]
Hey @SambyAgarYT 

I haven't try this yet, but maybe will help you: [Tyler3D/Multi-Ogar-Edited-Unlimited/src/gamemodes/AntiTeamVanillaFFA.js](https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited/blob/master/src/gamemodes/AntiTeamVanillaFFA.js)

**Comment by freaky767** [comment]
proxiemind? watcha doing? xD jk

**Comment by proxiemind** [comment]
@freaky767 Was in a mood to help ¯\_(ツ)_/¯

**Comment by MastaCoder** [comment]
Do note that it will cause lag. About anti-team, it's probably not going to be added anytime soon to what I think.

**Comment by SambyAgarYT** [comment]
@MastaCoder i mean lossing mass like lossing 500 mass in 5 seconds?

**Comment by MastaCoder** [comment]
So decay.

**Comment by SambyAgarYT** [comment]
Oh okay Thanks MastaCoder

**Comment by MastaCoder** [comment]
If you want decay to increase after x mass, there used to be options for it in other projects. It's easy to add.
