### ISSUE TITLE
Death causes Play button to be disabled

### ISSUE THREAD

**Issue by XtremePlayzCODE** [Megabyte918/MultiOgar-Edited#724]
When you die using the Agar.io client or any other client, you go to the regular death screen but the Play button is always disabled, so you have to refresh.

**Comment by Jhair2015** [comment]
this is client sided

**Comment by XtremePlayzCODE** [comment]
Oh shoot, yes it is, but one time I got a socket error, will try to reproduce

**Comment by XtremePlayzCODE** [comment]
OgarUL is the only client I found that actually works... I'll see if I can make an extension to make it not disabled see if it fixes it 😛

**Comment by XtremePlayzCODE** [comment]
Ok it is an Agar.io-client thing only... seems like maybe protocol/packet issue?

**Comment by Tyler3D** [comment]
@XtremePlayzCODE Probably, Miniclip released a new protocol recently

**Comment by XtremePlayzCODE** [comment]
🤔

**Comment by AlexHGaming** [comment]
@MastaCoder @Megabyte918 cl0se now orr i wil hak this repo

**Comment by AlexHGaming** [comment]
And agar.io now runs under protocol 13.

**Comment by MastaCoder** [comment]
Gotchu fam

**Comment by Agarian** [comment]
k

**Comment by MastaCoder** [comment]
k

**Comment by XtremePlayzCODE** [comment]
k

**Comment by Jhair2015** [comment]
k

**Comment by XtremePlayzCODE** [comment]
haha rekt chain

**Comment by Luka967** [comment]
KYS

**Comment by XtremePlayzCODE** [comment]
Nah I'd rather not

**Comment by Agarian** [comment]
k

**Comment by XtremePlayzCODE** [comment]
k




































k
