### ISSUE TITLE
I don't like this anymore... QUITTING LIFE

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#726]
This repo is shit, everything in it is shit, my life is shit... thanks for making it shit.

HAPPY APRIL FOOLS EVERYBODY!
Honestly, go prank everywhere, and have a good day.

**Comment by FantasyIsBae** [comment]
😆

**Comment by AlexHGaming** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by Luka967** [comment]
https://youtube.com/watch?v=4jeSUveeohw&t=3s

**Comment by MastaCoder** [comment]
GET STMPED KID

**Comment by Tyler3D** [comment]
I have 1.5K emails from github xD

**Comment by MastaCoder** [comment]
:trollface:

**Comment by AlexHGaming** [comment]
nuuuuuuu

**Comment by MastaCoder** [comment]
get april foold skidzzzzzzz

**Comment by AlexHGaming** [comment]
merry christmasss

**Comment by chewydev** [comment]
i delete too many emails XD

**Comment by Agarian** [comment]
@AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming @AlexHGaming :trollface:

**Comment by AlexHGaming** [comment]
@Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Agarian @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 @Megabyte918 :trollface:

**Comment by AlexHGaming** [comment]
o no now it is parst 1 of april

**Comment by Jhair2015** [comment]
@AlexHGaming Hey Alex go to discord pls :D

**Comment by Agarian** [comment]
@Jhair2015 @AlexHGaming Yall' should let me in your discord ;)

**Comment by Agarian** [comment]
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k
k

**Comment by Luka967** [comment]
not k

**Comment by Terabyte918** [comment]
![](http://i1193.photobucket.com/albums/aa355/ohhburn/GIF/tumblr_ldurr2hslo1qe3otj.gif)

**Comment by Jhair2015** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
