### ISSUE TITLE
Collision

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#727]
Is there a way to make the collision for cells go into each other a bit more?

**Comment by XtremePlayzCODE** [comment]
Hang on... https://github.com/CollisionDevelopment/

**Comment by freaky767** [comment]
what?

**Comment by FantasyIsBae** [comment]
@XtremePlayzCODE lol

**Comment by FantasyIsBae** [comment]
>Is there anyway to make the collision for cells go into each other a bit more?

Please explain.

**Comment by freaky767** [comment]
kinda hard to explain, the collision for cells, i want it to be like dual-agar's.

**Comment by XtremePlayzCODE** [comment]
legit i made a "company" called Collision and when i saw this i thought it was aimed towards it so just a heads up this issue is related to my company :D

**Comment by freaky767** [comment]
oh okay. this is related to collision in the private server

**Comment by XtremePlayzCODE** [comment]
i know x) but still pretty funny

**Comment by MastaCoder** [comment]
lmao Dual Agar collisions are nasty, I can take almost half of my cell into the other cell and nothing.

**Comment by freaky767** [comment]
i just want it :p

**Comment by freaky767** [comment]
thanks
