### ISSUE TITLE
Killing the server.

### ISSUE THREAD

**Issue by chewydev** [Megabyte918/MultiOgar-Edited#728]
How would I kill the server after 5 seconds of 1 player being alive.

**Comment by AlexHGaming** [comment]
You mean auto-restart?

**Comment by MastaCoder** [comment]
Duplicate. Auto restart isn't going to happen.

**Comment by chewydev** [comment]
Welp fml

**Comment by Agarian** [comment]
k

**Comment by Logan7432** [comment]
@chewydev Use Tyler3d's Version for auto restart plugin

**Comment by chewydev** [comment]
Thanks @Logan7432
