### ISSUE TITLE
How to link the client to the server?

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#729]
As for example,

I put mass or all the commands on my client (not made from cigar)

http://shairplus.tk/

Could you give me the code so I can do that?

**Comment by MastaCoder** [comment]
Client sided.

**Comment by AlexHGaming** [comment]
@MastaCoder add the client sided label

**Comment by MastaCoder** [comment]
NO

**Comment by AlexHGaming** [comment]
lmfao

**Comment by Jhair2015** [comment]
LOL

**Comment by Agarian** [comment]
Most agar clients have this: If you press F12 on your keyboard, type `connect("ws://serverIP:port")`, then press enter.

**Comment by Jhair2015** [comment]
@Agarian I did not mean that xD

**Comment by Agarian** [comment]
Alright then lol

**Comment by Jhair2015** [comment]
u.u
