### ISSUE TITLE
Stop this!!

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#73]
https://www.youtube.com/watch?v=uJNKZK7g_X8 - his can upload for all this server and all will make the tutorial, many issies, please, stop this, PLEASE!!!!!

**Comment by t11tanYT** [comment]
AND MANY SPAM

**Comment by ZfsrGhS953** [comment]
You are the one who is spamming. If @Megabyte918 doesn't like this, he can dislike the video and post a link to this repo in the comments.

**Comment by Fantasy-Agario** [comment]
Do not create issues like this @t11tanYT !

Closing
