### ISSUE TITLE
ERTP not working properly

### ISSUE THREAD

**Issue by AgarXTRA** [Megabyte918/MultiOgar-Edited#730]
After the new Agario update the ERTP script not working as it should. When the minion feed you with R it stop the player. Very annoying...

**Comment by NuclearC** [comment]
I have idea how to fix this. 'core.proxyMobileData(buf)' sends packet to server with opcode 102 and its contents are [102, buf]. So we can actually use it to make that ERTP thingy without hooking the whole WebSocket, just core.proxyMobileData :)

**Comment by Jhair2015** [comment]
@AgarXTRA @NuclearC This has affected the performance of the game, for example, we can compare that in the classy videos the animations were very good, that because the zoom was reduced to 50% or less in the browser, because it happens that vanilla did that by default, I used the extension before the upgrade and zoomed for less than 50% and had hellish lag, now agrarian is in the shit :).

**Comment by freaky767** [comment]
moneyshit trying to close down private servers ain't it

**Comment by MastaCoder** [comment]
Well the ERTP script is mostly a custom script..

**Comment by freaky767** [comment]
its been two days close the issue/1/1/11/1!11!

**Comment by Agarian** [comment]
How exactly would we fix this?

**Comment by NuclearC** [comment]
core.proxyMobileData :P

**Comment by Agarian** [comment]
That doesn't tell ME anything. I'm not exactly an expert on protocols and packets.

**Comment by Agarian** [comment]
Ok, well after agar.io had a seemingly minor "update", this issue no longer happens.

**Comment by MastaCoder** [comment]
gotchu

**Comment by Agarian** [comment]
@MastaCoder This actually does still occur, however now, it takes a major lag condition for it to occur (not internet lag).

**Comment by MastaCoder** [comment]
And we back up

**Comment by AlexHGaming** [comment]
@MastaCoder And we back down..

**Comment by AlexHGaming** [comment]
@AgarXTRA Try getting a different macro script (W macros, R macros will have to be changed around)
.
