### ISSUE TITLE
Virus Explosion

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#731]
how i can make that if a player eat virus his 75% mass will get splited into peices and 25% stays in center

**Comment by Gigabyte918** [comment]
this make popsplit more easier like gota.io

**Comment by SambyAgarYT** [comment]
Duplicate please close this :( Search issues before you open another 1 @MastaCoder @Megabyte918 Close :D

**Comment by freaky767** [comment]
which duplicate?

**Comment by Gigabyte918** [comment]
yes tell me which dublicate

**Comment by Jhair2015** [comment]
Just see the wiki on MultiOgar.

**Comment by AlexHGaming** [comment]
I weesh I cud close this.
