### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#735]
![image](https://cloud.githubusercontent.com/assets/25285427/24684528/0e70413e-197d-11e7-9dad-51d6f4e4fb1c.png)

**Comment by Tyler3D** [comment]
Log?
1. There is a memory leak
2. You need to buy more ram
One of those

**Comment by Tyler3D** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template

**Comment by FantasyIsBae** [comment]
Ye u need more RAM , your PC can't handle the epicness.

**Comment by ZfsrGhS953** [comment]
@gyeyoqu Run it with this command:
 ```node --max-old-space-size=512 index.js```

**Comment by FantasyIsBae** [comment]
😕

**Comment by MastaCoder** [comment]
No response.
