### ISSUE TITLE
Stats server 

### ISSUE THREAD

**Issue by vincent95330** [Megabyte918/MultiOgar-Edited#737]
How can i make stats server in my index ? 

<script type="text/javascript">
$(document).ready(function(){$("#gamemode option").each(function(){var b=parseInt($(this).val().split(":")[1])+3,d=$(this).val().split(":")[0],c=$(this);$.get("http://"+d+":"+b,function(a,b){a=JSON.parse(a);c.text(c.text()+" ["+alivePlayers+"/"+totalPlayers+"]")})})});
</script>

I want this : "servername" [players/max_players]

**Comment by FantasyIsBae** [comment]
> How can i make stats in my index?

What's below is a button that will lead a user to your stats server (if clicked)
Paste it in your *index.html* file
You can also do an onclick function if you like.
```
<button href="htttp://yourstatsIP:port" target="_blank"></button>
```
