### ISSUE TITLE
Virus style 

### ISSUE THREAD

**Issue by vincent95330** [Megabyte918/MultiOgar-Edited#738]
How can i custom virus color ?

**Comment by Jhair2015** [comment]
[Click Here, is rgb](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js#L8)

**Comment by vincent95330** [comment]
@Jhair2015  ok thx you :)

**Comment by vincent95330** [comment]
And can i change opacity ?

**Comment by Jhair2015** [comment]
I suppose so, because it is rgb
[Click Here to get rgb code](http://www.hexcolortool.com/)

**Comment by vincent95330** [comment]
@Jhair2015 
Don't work but thx you ) 

this.setColor({ r: 57, g: 53, b: 63, a: 0.50 });

**Comment by MastaCoder** [comment]
Client sided.

**Comment by Agarian** [comment]
OPACITY is client sided.

**Comment by Jhair2015** [comment]
@Agarian If I remember xD, in my client if I have the opaciodad of virus
