### ISSUE TITLE
AntiBot/Minion not found

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#74]
i test the serverScrambleLevel in 1, 2 , 3, and not found

AgarioPowerups worked on 3 level's :/

FIX THIS PLEASE

**Comment by Megabyte918** [comment]
@Jhair2015 I will work on this.

**Comment by NameYT** [comment]
@Megabyte918 Are you adding Pellet Mode? xD just asking not forcing

**Comment by Fantasy-Agario** [comment]
Hmm , agario powerups just duplicates the playercell . so we need an option that only allows one IP per player

**Comment by Megabyte918** [comment]
serverIpLimit = 2
serverMinionIgnoreTime = 5
serverMinionThreshold = 5
serverMinionInterval = 500
serverScrambleLevel = 3
playerBotGrow = 0
