### ISSUE TITLE
Problem with this code

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#740]
This code for bots with name of owners from TYLER3D , whats is the error?

I replaced all in PLAYERCOMMAND.JS

```

Find --> this.gameServer.bots.addMinion(player);
Change it to this.gameServer.bots.addMinion(player, (player._name + " Bot"));
Also Find --> this.gameServer.bots.addMinion(client);
And change it to this.gameServer.bots.addMinion(client, (client._name + " Bot"));



```

**Comment by Jhair2015** [comment]
@Megabyte918 Any help with this? And what to do with 'defaultName' [minions option in gameserver.ini]

**Comment by MastaCoder** [comment]
Not a related bug or feature request. Keep debugging until you figure it out.
