### ISSUE TITLE
Is this a client issue... or

### ISSUE THREAD

**Issue by Mr-BrockLee** [Megabyte918/MultiOgar-Edited#742]
**Ok So Skins in my server only works when I use em as nick. It doesn't work when i use <name> or {name} or [name]. what can i do.**

**Comment by ZfsrGhS953** [comment]
Use <name>.

**Comment by Mr-BrockLee** [comment]
That doesnt work, it requires me to use it as my nick

**Comment by AlexHGaming** [comment]
We can't help you with this, since skins are sent through the agar client, not the server itsself.

**Comment by Mr-BrockLee** [comment]
Alex, pm me on skype
