### ISSUE TITLE
Making it work with dual?

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#744]
No issue just wondering if we could make it work on dual-agar.online , 
I play all time dual, and i was wondering if we could do an copy of that? Maybe if someone had the exact settings in their Gameserver.js and gameserver.ini
That could be an idea.. But if you have a copy that looks like duals, send me copy/paste id love to have it

**Comment by AlexHGaming** [comment]
sorry raphy, but this is client sided.
Dual doesn't support private server connections in anyway.

**Comment by Jhair2015** [comment]
@AlexHGaming I think so, but protocol that nobody knows about it lol @raphyjb

**Comment by MastaCoder** [comment]
Nope
