### ISSUE TITLE
Custom text on a leaderboard

### ISSUE THREAD

**Issue by Agarian** [Megabyte918/MultiOgar-Edited#746]
I'd believe this may be easy, but just curious, how would one do this?

**Comment by MastaCoder** [comment]
Isn't there a board command or am I missing something.

**Comment by Wair1o17** [comment]
client sided? @MastaCoder

**Comment by Agarian** [comment]
The board command, last I checked, broke after the Protocol 11 update.

**Comment by Agarian** [comment]
That, or it screwed up the player highlight after the board was reset.

**Comment by Agarian** [comment]
Besides, I meant custom text on a leaderboard, while keeping the players on it. Similar to OgarUL's status plugin.

**Comment by AlexHGaming** [comment]
client sided

**Comment by MastaCoder** [comment]
This isn't client sided lmao. The board command is run on the server.. We need to figure out if the board can even be changed or not.

**Comment by proxiemind** [comment]
Hi, [maybe this](https://github.com/proxiemind/MultiOgar-Edited/commit/da0fcd4d55669381e7d83cd60bc174a8a1845d44) would do (tested and working)?

**Comment by Agarian** [comment]
It works, I added it to my recent PR and gave you credits (obviously).
I will close this just for now

**Comment by MastaCoder** [comment]
@proxiemind awesome code, just merged another PR with it to this repo. 👍

**Comment by Agarian** [comment]
@proxiemind You still have Ogar-Unlimited O_O (it's the closest I've seen to the latest version since it's deletion)

**Comment by proxiemind** [comment]
@Agarian Yeah, it was because of those threats about deleting repo if some charity goal and so on are not met :baby:
