### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#749]
Is there a way to remove the welcome message that appears? https://ibb.co/fOjf85 I know that this is probably for copyright reasons but its actually really annoying. May I please remove it, If so where is it located?

**Comment by Wair1o17** [comment]
Control + F on your Gameserver.js and changue it!

**Comment by Logan7432** [comment]
@Wair1o17 Which line though, I cant find it, I changed line that said Multi-Ogar-edited and it still comes up!

**Comment by AlexHGaming** [comment]
Ever heard of the gameserver.ini?

**Comment by AlexHGaming** [comment]
scroll down, from the start, slowly, until you find serverWelcomeMessage, change the Multiogar-edited bit to what u want.

**Comment by Luka967** [comment]
Remove [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L77) line.

**Comment by Logan7432** [comment]
@Luka967 Thanks!!!!
