### ISSUE TITLE
how to block "q"

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#75]
how to block the funcion of change color at press q and change the block of split and eject mass of myself at press 'q'

**Comment by Megabyte918** [comment]
@RelTakeover see my last comment on #59

**Comment by RelTakeover** [comment]
i want block the FUNCTION of ''q'" not only the change of the color

**Comment by Megabyte918** [comment]
@RelTakeover Replace you PacketHandler.js with this one: http://pastebin.com/rRgL2wxv
