### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#751]
I'm not sure why but when about 10-20 people join my server it gets mad laggy. When a player trys to join it is very very delayed and then they teleport around when they spawn in. It's not a problem after a minute or two of being in but it hard for large amounts of people. It can't be my internet cause the website loading times are still fast and it's 200down and 15up so I'm not sure

**Comment by Tyler3D** [comment]
@Logan7432 15 Mbps Upload is slow. Increase your upload speed. Also you should specify your hardware. I think about 5 Mbps upload per person would be good. So for 100 people you should have 500 Mbps.
Might be overkill I don't know if it is.

**Comment by Logan7432** [comment]
@Tyler3D The PC its running on has Intel I5 4590 and GTX 960 with 8 GIGs of ram. That might be overkill... for 5 Mbs per person, Is there a way to change the bandwidth per person?

**Comment by Wair1o17** [comment]
@Logan7432 That problem not is because MultiOgar Edited Unlimited, on mi VPS i and left of players is playing total fine. No lag

**Comment by MastaCoder** [comment]
15Mbps up is slow. Your internet will do most of the splitting up itself based on how the router or ISP set it and such. Graphics card doesn't matter since it's not a GPU useful app at all, if you are having movement lag it is your internet.

**Comment by Logan7432** [comment]
@Tyler3D It's kinda annoying how service providers (Comcast) give you fast download but slow as hell upload.

**Comment by MastaCoder** [comment]
lmao, I'd run it on a VPS :#

**Comment by Logan7432** [comment]
@NastaCoder I have to pay for that though...

**Comment by Logan7432** [comment]
@MastaCoder Just a question, Did the cigar server use upload speeds as much as this server did? For some reason i use to be able to fit more people on the cigar server then multi-ogar, the website would actually get before the server did.

**Comment by MastaCoder** [comment]
no, cigar and multiogar cannot be compared since Cigar is way too outdated.

**Comment by Logan7432** [comment]
@MastaCoder Ok, but with cigar I use to reach higher players without the server lagging.

**Comment by MastaCoder** [comment]
then again the physics were nasty and it was outdated with major security bugs.

**Comment by Logan7432** [comment]
@MastaCoder Would it be possible for you to be able to implement it so the server uses even less bandwidth then it does? Or is this the lowest possible?

**Comment by Logan7432** [comment]
@MastaCoder Do you know of any free vps? And if you do can you let me know?

**Comment by MastaCoder** [comment]
1. Nope.
2. Most good things are not free.

**Comment by Logan7432** [comment]
@MastaCoder So bandwidth cant go lower? Just clarifying.

**Comment by MastaCoder** [comment]
Nope.
