### ISSUE TITLE
Console freeze when displaying weird characters

### ISSUE THREAD

**Issue by duwayy** [Megabyte918/MultiOgar-Edited#753]
Hi all,
The console (not web console, normal console) freeze when it display weird characters, eg doing a playerlist command will block when encountering such characters -> Řยßïηh⊕🔫 , players after the weird name will not show up
Spamming space and enter keys make it unfreeze, but it will not display the end of player list

![image](https://cloud.githubusercontent.com/assets/19626728/24933677/187107cc-1f4a-11e7-8baf-086645443071.png)

**Comment by MastaCoder** [comment]
You're using a SSH client that doesn't support special characters. Latest version of Putty (I think) and MobaXtreme support them.

**Comment by MastaCoder** [comment]
Oops ^

You're using a SSH client that doesn't support special characters. Latest version of Putty (I think) and MobaXtreme support it.
