### ISSUE TITLE
Server tracker

### ISSUE THREAD

**Issue by deniskrop** [Megabyte918/MultiOgar-Edited#754]
Hi I have spare servers and domain names I can host a server tracker since http://ogar-tracker.tk is down, how would I go about setting one up?

**Comment by Luka967** [comment]
Unrelated to project, however I think that all three large trackers (c0nsume, ogar-tracker and ogar-mivabe.nl) use PHP+GET+SQL. ogar-tracker used the request body as server's data, the other two requested tokens.

**Comment by AlexHGaming** [comment]
@deniskrop now close the issue

**Comment by deniskrop** [comment]
@AlexHGaming  @Luka967  the only active one seems to be ogar-mivabe.nl

**Comment by Luka967** [comment]
True, but they existed.
