### ISSUE TITLE
Questions and ideas about the lag

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#755]
Hi, i have an agar with many players and big food and i've been thinking some ways to reduce the lag.

> 1) - My size food is set in 70 and for each player who is playing, the fooodMaxAmount increase in 20 pellets, and the foodMaxAmount value is same than foodMinAmount without players.
> 
> so , my configurations are:
> 
> foodMinAmount: 500
> foodMaxAmount: 500
> serverMaxConnections: 50
> so , the server not would generate pellets needless and with 50 players the server will generate 1500 pellets with spawnInterval of 40(400ms)
>i think that this is would be something like replacing the foodSpawnAmount.

> 2) - If the server have more than 35 players the foodSpawnAmount will change to 20 instead of 30, and if my first idea is correct  the foodMaxAmount will be increased by 15 pellets instead of 20.

`

> 3) - Increase the value of food size and decrease the value of pellets in the map

> 4) - Replace the creation of ejected mass entity as food Entity

Questions:

> > 1) - My ideas are correcty for reduce the lag? if isnt correct , why not?
> > 2) - How much would it improve performance if i would use jxcore ?
> > 3) - How can i change the amount of ram and internet used by a server?
> 

i wish that not would close this issue, and although MO-E havent lag , it could be better.

If you do not know , please to refrain from comment inconsistencies.

`

**Comment by Megabyte918** [comment]
Test your theories and find out which one works best for your server.

**Comment by FantasyIsBae** [comment]
>Questions:

1. My ideas are correcty for reduce the lag? if isnt correct , why not?
2. How much would it improve performance if i would use jxcore ?
3. How can i change the amount of ram and internet used by a server?

-----------------------------------------------------------------------------

1. foodSpawnAmount will decrease the amount of nodes that are created so yes that would help a bit.
    Increasing food size will not improve overall improvement if anything it will decrease the speed.
2. If you are able to port MultiOgar-Edited into jxcore then yes as JxCore is multi-threaded.
3. You can't change the amount of RAM or internet the server uses lol 

And also MultiOgar-Edited is optimised really well so if anything it is your machine which is not working properly .
