### ISSUE TITLE
Solid virus

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#756]
> 
> 1- Where it is defined that the virus can be transgress when my cell is smaller
> 
> 
> 2- It is possible to create a solid rectangle on the map?

**Comment by Megabyte918** [comment]
1 - What do you mean by "transgress"
2 - Client sided

**Comment by MastaCoder** [comment]
@Megabyte918 "infringe or go beyond the bounds" xD idk google helped meh

Client sided. Stop posting client sided issues.

**Comment by gyeyoqu** [comment]
2 ) not a client issue , i mean a entity.

**Comment by MastaCoder** [comment]
How are you going to render that "rectangle"?

**Comment by Agarian** [comment]
That really is client sided
