### ISSUE TITLE
what is?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#760]
what is the code where is fixed the lag when split fast

**Comment by FantasyIsBae** [comment]
>what is the code where is fixed the lag when split fast

The code is : [Here](https://pastebin.com/yup5npyx)

**Comment by AlexHGaming** [comment]
wow, it works! Yes thank fuck it works @FantasyIsBae

**Comment by FantasyIsBae** [comment]
Also you do not need to make issues over things that are invalid just mention it in an already existing issue @gyeyoqu 

@AlexHGaming i know right I'm getting 10,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,
000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000, + FPS boost (one Googolplexian)

**Comment by AlexHGaming** [comment]
same!

**Comment by AlexHGaming** [comment]
#648?

**Comment by FantasyIsBae** [comment]
Also just to add MultiOgar-Edited can run on my shitty PC Tower (2.93 Ghz CPU, Integrated Intel HD graphics)

**Comment by Luka967** [comment]
JS timer inaccuracy leads to requests for splitting and/or W to be ignored.
All game requests should be processed immediately (and of course ignore them if too consistent).

Fixing this requires refactoring the `PacketHandler` and `PlayerTracker`
Major changes would be [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L240-L260) function and references to it, and also variables prefixed with `press` being removed. Not even that is enough though.

**Comment by MastaCoder** [comment]
Lag can also be latency. You can't have a server down in Turkey with 600ms latency expecting splits to become "faster". No issues on the latest commit.
