### ISSUE TITLE
Multisplitting in agar.io

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#761]
in agar.io even with retina graphics, i not have lag when i split fast , nevertheless with MO-E , when i split fast i have lag , why? I also use protocol 6 and with low graphics

**Comment by Luka967** [comment]
Duplicate of #760

**Comment by FantasyIsBae** [comment]
I answered your question already @gyeyoqu  stop duplicating issues for no reason.

**Comment by FantasyIsBae** [comment]
Close this.

**Comment by MastaCoder** [comment]
Stop posting issues, just stop.
