### ISSUE TITLE
UserScript to send commands to server

### ISSUE THREAD

**Issue by XtremePlayzCODE** [Megabyte918/MultiOgar-Edited#763]
Could there possibly be a UserScript to send commands to the server using Socket.io?

**Comment by gyeyoqu** [comment]
it would amazing.

**Comment by MastaCoder** [comment]
Not at the moment, sounds a lot like OgarUL tbh.

**Comment by XtremePlayzCODE** [comment]
oshoot

**Comment by XtremePlayzCODE** [comment]
this can be done
1. Achieve player list from server using Socket.IO
2. Check if player stats are equal
3. Send command back to server
4. Execute command
