### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#765]
n original multiplayer, the virus explosion changed it with this:
`   var splitMass = Math.min(consumer.mass / (numSplits + 1), 24); // Maximum size of new splits`

the '24' is the virus explosion cells , in big and small cells , how to do that with the new virus.js ? pls help me.

**Comment by MastaCoder** [comment]
If the variable doesn't exist, it was probably changed. This is not the same as Ogar or MultiOgar.
