### ISSUE TITLE
Not an issue... Please answer.

### ISSUE THREAD

**Issue by suprix** [Megabyte918/MultiOgar-Edited#767]
What kind of server gota.io use?
I know its not MultiOgar so I want to know what is it.

**Comment by Agarian** [comment]
They use their own custom server code, not available to the public.

**Comment by suprix** [comment]
Damn :| But check http://dogio.win/ .
Its basiclly copy of gota.io and his servers work...
I have Gota.io Full client but I can't connect to the server. I am getting this:
![Uploading image.png…]()

**Comment by MastaCoder** [comment]
They made their own too.
