### ISSUE TITLE
como entrar a un server que no tiene configurado el userRoles?

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#768]

**Comment by Wair1o17** [comment]
Se te olvido el traductor men :v

**Comment by AlexHGaming** [comment]
uhh refer to the issue template `Must be plain english` ugh

**Comment by imnotNxhz1** [comment]
@Wair1o17  queria saber quien hablaba el hermoso español :´v

**Comment by theoxt** [comment]
No entiendo la pregunta xD

**Comment by Wair1o17** [comment]
@imnotNxhz1 Ste men :v, @theoxt Se refiere a tener acceso a la consola del servidor mediante UserRoles.json, sin que el mismo, esté configurado

**Comment by Agarian** [comment]
k

**Comment by AlexHGaming** [comment]
k
