### ISSUE TITLE
Auto Split

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#77]
How i can stop auto split and consume my mass please dont Close it! @Megabyte918 's Code that he gave me isnt working!

**Comment by Megabyte918** [comment]
replace your autoSplit function in GameServer.js with this one: 
<pre>
GameServer.prototype.autoSplit = function (client, cell1) {
    // rec mode
    if (client.rec == false) {
        var maxSize = this.config.playerMaxSize;
    } else {
        maxSize = this.config.playerMaxSize * 3;
    }
    
    // check size limit
    var checkSize = !client.mergeOverride || client.cells.length == 1;
    if (checkSize && cell1._size > maxSize && cell1.getAge(this.tickCounter) >= 15) {
        // cannot split => just limit
        cell1.setSize(maxSize);
    }
};
</pre>

**Comment by PrinceDark9243** [comment]
Thanks @Megabyte918
