### ISSUE TITLE
Virus/Split

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#771]
Very very good(x16) Division from viruses in the usual MultiOgar!!!

Developers, please transfer the division from viruses to your server, if you transfer, then all of you will make a full quality server similar to vanilla agar.i and fun (I play in agar.io from the very beginning and perfectly understand its physics division) I understand That it is difficult for you to transfer files that do not belong to your server, but please try. If you do this, you can breathe (well, well, throw the server) and is proud to have made a good server.

Developers you should try to take a long rest....
If you do not understand, Sorry google translator xD

**Comment by AlexHGaming** [comment]
We can't transfer, we have to make the code ourselves as we cannot 'transfer'

**Comment by DeadLord1337** [comment]
You can not make the code like the one in Milti Ogar? Just an honest word they divide from viruses is better, and much like vanilla

**Comment by AlexHGaming** [comment]
This is because we rewritten the entire code so yeah

**Comment by DeadLord1337** [comment]
Ehhh...

**Comment by Wair1o17** [comment]
@DeadLord1337 Just re-edit Virus.js
