### ISSUE TITLE
Unexplained lag.

### ISSUE THREAD

**Issue by chewydev** [Megabyte918/MultiOgar-Edited#773]
Basically, my server after about 5 minutes of running is lagging like crazy with about 20 people actively playing. Im hosting on a Centos 7 8 GB Ram VPS with 4x Cores. What the hell is going on with my server? Also, the server is updated to the latest commit.
If you want to see what im talking about, go to <http://popsplit.us/>.

**Comment by proxiemind** [comment]
Hi @chewydev 

a little of invention would be nice, especially that recently @MastaCoder merged template below, which means guys are tired a little and seems you have purposely deleted template completely...

**Now**:
- [ ] You have provided logs […]
Please install such monitoring or any other tool and provide logs, when idle and under load: https://nicolargo.github.io/glances/ (most preferably see how this thingy stores data in logs and sent not only screenshot but main log itself)

I'm hosting only MultiOgar without client. For me there is much bigger issue with transfer than resource drain, I have 4 instances of MO-E running on my VPS, 1 core (2,4GHz), 1GB RAM and for now Ubuntu as OS, and most of the time CPU usage below 30% for node processes, so it has to be some shit related with your VPS and/or Centos packages, or specific node you have... or even something not related... there is a lot of space.

Please install monitoring tool to see for sure what is draining resources, provide node version (and other required packages). Check your network settings (if you setup internal rules), your DB, bla bla bla.

I would suggest to run new installation on your VPS, with all staff downloaded from here + check if you haven't "hardcode" node or related packages versions.

**Please in future give something useful from start, to not waste time for ping-pong guessing...**

------------

**BEFORE POSTING NEW ISSUE READ THIS**: You will find below few points, that you must follow or provide required info to. If you are not going to provide what we need in format we require your issue will be closed instantly without explanation. Spam is treated with fire.


Helpful checklist:

- [ ] You have checked [prev issues](https://github.com/Megabyte918/MultiOgar-Edited/issues?q=is%3Aissue+is%3Aclosed) first and you didn't found answer for your problem (if there is something similar put reference links)
- [ ] You are using and you have tested the latest version of MultiOgar.
- [ ] Issue is in English.
- [ ] Issue is not off-topic, and is related to the project.
- [ ] You have provided below good description of the error, making sure it is something we can reproduce.
- [ ] You have provided logs if there is crashing happening.

[Tutorial of how to format text on github](https://guides.github.com/features/mastering-markdown/), to make your issue not only readable but clean and neat

**Comment by AlexHGaming** [comment]
I have a lot of my own custom code implemented into my server, i still dont lag. Try running a draft server unedited, does the same error occur?

**Comment by MastaCoder** [comment]
Your provider probably has a bandwidth cap, after full use at one rate it will cap you down the amount you can upload. Most hosts do this to avoid abuse, if your host does this 90% sure they don't accept gameservers hosted with them.

Also less cores, stronger cores > more cores, weaker ones.

**Comment by chewydev** [comment]
Ill look for better hosts, im currently hosting with https://www.vultr.com.

**Comment by Logan7432** [comment]
@chewydev If you find a super cheap host that doesn't bottleneck let me know please.

**Comment by Logan7432** [comment]
@chewydev If someone like me were to use https://www.vultr.com/ for hosting which playing option would I buy for hosting this server.

**Comment by chewydev** [comment]
@Logan7432 Actually FadeHost (A minecraft server hosting company) has awesome CPUS, I just started host my 6 game-servers on a 5GB VPS for $20/mo and the average update time is around 3 or 4 ms (incredibly fast). I'd recommend getting a VPS with them: https://www.fadehost.com/billing/cart.php?gid=9
