### ISSUE TITLE
Reload Command Error

### ISSUE THREAD

**Issue by HyperAgar** [Megabyte918/MultiOgar-Edited#775]
This is what I get when i enter "reload" in the console:
![screenshot 27](https://cloud.githubusercontent.com/assets/27769111/25179167/b3306bea-24d6-11e7-80b7-6411d8327f0b.png)
Any solutions?

**Comment by Megabyte918** [comment]
Fixed.

**Comment by AlexHGaming** [comment]
@Megabyte918 We finally find a good issue. Yes I have an issue with this, when i do it, it shows an error.

**Comment by AlexHGaming** [comment]
ffs lol
