### ISSUE TITLE
VPS

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#780]
**BEFORE POSTING NEW ISSUE READ THIS**: You will find below few points, that you must follow or provide required info to. If you are not going to provide what we need in format we require your issue will be closed instantly without explanation. Spam is treated with fire.

Helpful checklist:

- [x] You have checked [prev issues](https://github.com/Megabyte918/MultiOgar-Edited/issues?q=is%3Aissue+is%3Aclosed) first and you didn't found answer for your problem (if there is something similar put reference links)
- [x] You are using and you have tested the latest version of MultiOgar.
- [x] Issue is in English.
- [ ] Issue is not off-topic, and is related to the project.
- [ ] You have provided below good description of the error, making sure it is something we can reproduce.
- [ ] You have provided logs if there is crashing happening.

[Tutorial of how to format text on github](https://guides.github.com/features/mastering-markdown/), to make your issue not only readable but clean and neat

-----------
Most of you might not find this an issue, but there should be directions somewhere on the repo so people like me know how to set up a vps and the best and cheapest option for hosting. Thanks!

**Comment by MastaCoder** [comment]
k

**Comment by Logan7432** [comment]
@MastaCoder Can you do this? Also know any cheap vps sites?

**Comment by Logan7432** [comment]
@MastaCoder If I purchase a vps on https://vpscheap.net/pricing.aspx for 3.99 would that be good enough for a server? Also, which version would I use to run server on. (ubuntu)
