### ISSUE TITLE
Join & Leave Messages.

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#781]
**BEFORE POSTING NEW ISSUE READ THIS**: You will find below few points, that you must follow or provide required info to. If you are not going to provide what we need in format we require your issue will be closed instantly without explanation. Spam is treated with fire.

Helpful checklist:

- [ ] You have checked [prev issues](https://github.com/Megabyte918/MultiOgar-Edited/issues?q=is%3Aissue+is%3Aclosed) first and you didn't found answer for your problem (if there is something similar put reference links)
- [ ] You are using and you have tested the latest version of MultiOgar.
- [ ] Issue is in English.
- [ ] Issue is not off-topic, and is related to the project.
- [ ] You have provided below good description of the error, making sure it is something we can reproduce.
- [ ] You have provided logs if there is crashing happening.

[Tutorial of how to format text on github](https://guides.github.com/features/mastering-markdown/), to make your issue not only readable but clean and neat

------------
It think it would be very good feature to add join leave messages that appear in the chat when someone join/leaves the server. You can make it so you can turn on or off in the config. I also think we could do death messages that you could turn on or off in config. It would be awesome to have

**Comment by AlexHGaming** [comment]
ok you really need to remove that chunk of text.

**Comment by Logan7432** [comment]
@alexhgaming I'm pretty sure it's possible to make the server say something in chat when you join the game

**Comment by AlexHGaming** [comment]
But the client is the one that supports chat features and the vanilla client doesnt support one anyways

**Comment by Logan7432** [comment]
@alexhgaming I guess but I think it would be possible on server side cause when someone joins the server revives that and then sends the messages to everyone that someone joined the game

**Comment by MastaCoder** [comment]
> You can make it so you can turn on or off in the config.

OgarUL.

> turn on or off in config

OgarUL.

**Comment by AlexHGaming** [comment]
^^

**Comment by Logan7432** [comment]
@MastaCoder @AlexHGaming What about something like server broadcast, for example I type "broadcast (message)" And then it sends a message to everyones chat.

**Comment by Logan7432** [comment]
@MastaCoder I could possibly use OgarUL but it doesn't have a swear filter like on here

**Comment by AlexHGaming** [comment]
https://code.org/learn

**Comment by Logan7432** [comment]
@AlexHGaming Do you think im gay?

**Comment by AlexHGaming** [comment]
huh?

**Comment by AlexHGaming** [comment]
idubbzz fan

**Comment by MastaCoder** [comment]
https://www.codecademy.com/

**Comment by Megabyte918** [comment]
@Logan7432 
For death messages, add this underneath `node.onRemove(this);` at the bottom of the `removeNode` function of GameServer.js:
```js
if (node.owner && !node.owner.cells.length) {
    for (var i in this.clients) {
        var client = this.clients[i].playerTracker;
        var message = node.owner._name + " has died."
        this.sendChatMessage(null, client, message);
    }
}
```
For disconnect messages, add this underneath `if (!this.socket.isConnected) {` in the `checkConnection` function of PlayerTracker.js:
```js
for (var i in this.gameServer.clients) {
    var client = this.gameServer.clients[i].playerTracker;
    var message = this._name + " has disconnected."
    this.gameServer.sendChatMessage(null, client, message);
}
```
Although it sounds like a good idea, I will not implement it as a config as it is an OgarUnlimited feature.
And only affects specific clients that support chats, otherwise it is pretty much useless.

**Comment by Logan7432** [comment]
@Megabyte918 AWESOME!!!!!!

**Comment by Megabyte918** [comment]
@Logan7432 You should learn javascript lol, you could make this sort of stuff on your own trust me it's worth it.

**Comment by Logan7432** [comment]
@Megabyte918 The death messages are Great, but would it be possible to show like who ate you instead of just has died?

**Comment by Logan7432** [comment]
@Megabyte918 Indeed. I've been working pretty hard lately to learn JS and HTML but i'm not able to implement the stuff I learned into something like this yet.

**Comment by Megabyte918** [comment]
@Logan7432 Yes showing who ate you is possible:
At the bottom of the `resolveCollision` function in GameServer.js, replace:
```js
// This:

this.removeNode(cell);

// With this:

this.removeNode(cell, check);
```
Then replace your `removeNode` function in GameServer.js with this:
```js
GameServer.prototype.removeNode = function(node, killer) {
    // Remove from quad-tree
    node.isRemoved = true;
    this.quadTree.remove(node.quadItem);
    node.quadItem = null;
    
    // Remove from node lists
    var i = this.nodes.indexOf(node);
    if (i > -1) this.nodes.splice(i, 1);
    i = this.movingNodes.indexOf(node);
    if (i > -1) this.movingNodes.splice(i, 1);
    
    // Special on-remove actions
    node.onRemove(this);

    if (node.owner && !node.owner.cells.length) {
        if (killer.owner != node.owner) {
            for (var i in this.clients) {
                var client = this.clients[i].playerTracker;
                var message = node.owner._name + " was killed by " + killer.owner._name;
                this.sendChatMessage(null, client, message);
            }
        }
    }
}
```

**Comment by Logan7432** [comment]
@Megabyte918 Wonderful 👍  Btw do you think VPScheap.net for 4.99 could hold 10-30 people with 10bots cause I might purchase it.

**Comment by Logan7432** [comment]
@Megabyte918 @MastaCoder https://ibb.co/nybKMQ I just got a error randomly.

**Comment by Megabyte918** [comment]
Replace this:
```js
if (killer.owner != node.owner)
```
With this:
```js
if (killer && killer.owner != node.owner)
```
It should account for when a player's cells are removed by a non-existant owner (e.g: being killed by the kill command or disconnecting)

**Comment by Wair1o17** [comment]
@Megabyte918 I know there is a code to make the minions are born with the name of the player that uses them, but it does not work, and what should be set in * defaultname * in gameserver.ini?

**Comment by Megabyte918** [comment]
@Wair1o17 In this line under the minion command in CommandList.js:
```js
gameServer.bots.addMinion(client, name);
```
Replace `name` with `client._name`

**Comment by Wair1o17** [comment]
and gameserver.ini?

**Comment by Megabyte918** [comment]
@Wair1o17 You cannot connect the player's name to minion names through gameserver.ini

**Comment by Wair1o17** [comment]
@Megabyte918 Anyway thanks for your help

**Comment by Logan7432** [comment]
@Megabyte918 Is there a possible code to force players to pick a name or is that client sided?

**Comment by Megabyte918** [comment]
@Logan7432 The only way players are allowed to choose minions names for themselves is if they have access to the minion playercommand to give themselves minions. Otherwise I'm guessing it would be client sided depending on how you implement such a feature.

**Comment by Logan7432** [comment]
@Megabyte918 Hey, Just wondering do you know any good VPS for about $5 or less and supports this server? I really need one bad cause hosting from home just cant do it anymore as my server is growing. I cant even get on my own server cause lag is so bad!

**Comment by Megabyte918** [comment]
Nope. That's something you're gonna have to figure out on your own, lol

**Comment by Logan7432** [comment]
@Megabyte918 Ok, I looked at so many and can't decide because some look like a scam.
