### ISSUE TITLE
Error..

### ISSUE THREAD

**Issue by SambyAgarYT** [Megabyte918/MultiOgar-Edited#782]
There is an error in playerlist :3 when u do playerlist in the console t makes the console log blank?
@Megabyte918 any fix?
plz close this issue if its fixed

**Comment by Megabyte918** [comment]
I could not reproduce this error. Try using the latest version of CommandList.js, and if that does not solve it could you provide a screenshot of the console?

**Comment by SambyAgarYT** [comment]
nvm i fixed it :D
