### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by AgarXTRA** [Megabyte918/MultiOgar-Edited#785]
Not an issue. Did not find anywhere else to post this. You should fix a section for general questions...

I need help in creating proxy bots for a MO-E server as well as a shop system similar to Raga.pw

If you master javascript and/or PHP well then I have the money. Email josefshaat@gmail.com

**Comment by AlexHGaming** [comment]
🤦‍♂️

**Comment by Megabyte918** [comment]
Dupe of #621

**Comment by AlexHGaming** [comment]
lel
