### ISSUE TITLE
Cheap VPS

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#786]
Anyone know a good cheap vps for around $5 that runs this server good? Thanks!

**Comment by Wair1o17** [comment]
OVH?

**Comment by Logan7432** [comment]
@wair1o17 I was thinking to get that, is it good? I heard there support isn't that good

**Comment by Logan7432** [comment]
@wair1o17 I was thinking to get that, is it good? I heard there support isn't that good

**Comment by Logan7432** [comment]
That glitched.

**Comment by systemroot** [comment]
nouptime.com?

**Comment by Megabyte918** [comment]
Duplicate of #780, please do not make issues unless they are related to this project @Logan7432 .

**Comment by Logan7432** [comment]
@megabyte918 Sorry I just need to know bad

**Comment by AlexHGaming** [comment]
@Logan7432 Well ask somewhere else then. Surely a VPS list could help you, this won't. It's an agar.io project, not a VPS project.

**Comment by Logan7432** [comment]
@alexhgaming the vps for the project so....

**Comment by Luka967** [comment]
There's no *the* VPS for the project.

**Comment by Logan7432** [comment]
@megabyte918 Sorry for asking, would the $4 plan be able to handle about 30 players and 10 bots On the multipart server?

**Comment by Tyler3D** [comment]
@Logan7432 4 dollars won't get you much. Especially because you are using bots. Good specs for a server  would be 8+ GB of ram, i5 or i7,  and 50+ download and upload.
