### ISSUE TITLE
Pellet mode lag

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#787]
Ok, if you have 100+ minions with lots of pellets, and then you turn on pellet mode, it lags so badly.
Bug or is it just me?

**Comment by Wair1o17** [comment]
That's normal, the minions along with a lot of pellets ma hell hell.

**Comment by Agarian** [comment]
^^

**Comment by Megabyte918** [comment]
Yes this is normal. Pellet mode requires visible node calculations for each minions to find food so adding lots of minions with pellet mode will most likely cause performance issues.

**Comment by freaky767** [comment]
ahh okay
