### ISSUE TITLE
linux error

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#788]
https://ibb.co/nLPqVk I get this error when I try and start up my server on Linux.

**Comment by Logan7432** [comment]
https://ibb.co/bOMeqk

**Comment by AlexHGaming** [comment]
ugh reinstall the server

**Comment by AlexHGaming** [comment]
u obviously did add something to the code. Just use a clean unedited server

**Comment by AlexHGaming** [comment]
Or use a node.js version that supports mo-edited

**Comment by MastaCoder** [comment]
The error isn't showing up from the code, verify your install of Node.js. Try running a test script, also check your modules.

**Comment by Logan7432** [comment]
@MastaCoder I followed all instructions to install node and get everything setup. Ill try again though, Also What Linux should i be using?

**Comment by Luka967** [comment]
install gentoo

**Comment by Logan7432** [comment]
@Luka967 Whats that and how?

**Comment by Logan7432** [comment]
Fixed it.

**Comment by Tyler3D** [comment]
@Logan7432 

> Fixed it.

Cool can you close then
