### ISSUE TITLE
how configure server like Ultrasplit?

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#792]

**Comment by vincent95330** [comment]
Try with this : https://github.com/Megabyte918/MultiOgar-Edited/compare/master...vincent95330:patch-1

**Comment by AlexHGaming** [comment]
ultrasplit? define ultrasplit please.

**Comment by Megabyte918** [comment]
> how configure server like Ultrasplit?

Mess with the configuration file until you have the correct physics for "ultrasplit" (whatever that might be).
That's why its there and there are different configs for physics so you could make the server however you like.
