### ISSUE TITLE
Ram

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#794]
I'm honestly not sure why and can not find a solution in previous issues, But for some reason my server is using a lot of ram. There were only about 20 or less on my server today and it became very slow cause almost all two gigs of ram on my server were being used. Any ideas?

**Comment by AlexHGaming** [comment]
> All 2 gigs of ram

k u need better pc

**Comment by MastaCoder** [comment]
2GB is a lot. What did you have enabled?

**Comment by Logan7432** [comment]
@AlexHgaming it's a vps

**Comment by Logan7432** [comment]
@MastaCoder All my files are in my forked MultiOgar on my profile

**Comment by MastaCoder** [comment]
https://i.gyazo.com/bef3a95e40b90f6f879b8487ea7ab1ca.png

Well that explains the memory leak.

**Comment by Logan7432** [comment]
@MastaCoder How do I fix?

**Comment by Logan7432** [comment]
@MastaCoder How do the commits effect the memory?

**Comment by Logan7432** [comment]
https://ibb.co/cQpHRQ

**Comment by MastaCoder** [comment]
I don't know, but you should use an unedited version of MultiOgar so we can provide support.

**Comment by Logan7432** [comment]
@MastaCoder It's exactly the same but I added Kill feed (death messages) in chat.

**Comment by Logan7432** [comment]
@MastaCoder Could be possibly be kill feed? Also please reopen so other people can help solve this memory leak. https://github.com/Megabyte918/MultiOgar-Edited/issues/781

**Comment by MastaCoder** [comment]
The vanilla version of MultiOgar-Edited does not have a memory leak, I can't help with a version of MultiOgar that's been changed. Use vanilla since it doesn't have a memory leak.

**Comment by Logan7432** [comment]
@MastaCoder can you please reopen so someone else can try and help with the issue? And I think vanilla agar is boring. Thanks for helping though.

**Comment by Logan7432** [comment]
@Megabyte918

**Comment by Megabyte918** [comment]
@Logan7432 I could not reproduce the memory leak in your version. I suggest getting a better VPS
