### ISSUE TITLE
Problem to save the mass

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#795]
How to save in an array the value of the mass reached in each game?

Please, im stuck

**Comment by MastaCoder** [comment]
save where..?

**Comment by gyeyoqu** [comment]
@MastaCoder in a array, to be able to show the maximum score for each player

**Comment by Megabyte918** [comment]
@gyeyoqu Add `this.bestScore = 0;` into the PlayerTracker constructor, then in the `updateTick` function, add this:
```js
if (this._score > this.bestScore) {
    this.bestScore = this._score;
}
```
Make sure you place it someplace AFTER the player's viewbox has been updated, it should keep track of the player's best score and it will not change unless they reach a higher one or disconnect.

Here's a command you can use to test it:
```js
test: function(gameServer, split) {
    var id = parseInt(split[1]);
    if (isNaN(id)) {
        Logger.warn("Please specify a valid player ID!");
        return;
    }
    for (var i in gameServer.clients) {
        if (gameServer.clients[i].playerTracker.pID == id) {
            Logger.warn(gameServer.clients[i].playerTracker.bestScore);
        }
    }
},  
```
Then you can add their best score to an array like this
```js
....
var scores = [];
....
scores.push(this.bestScore);

```

**Comment by Megabyte918** [comment]
@gyeyoqu Add `this.bestScore = 0;` into the PlayerTracker constructor, then in the `updateTick` function, add this:
```js
if (this._score > this.bestScore) {
    this.bestScore = this._score;
}
```
Make sure you place it someplace AFTER the player's viewbox has been updated, it should keep track of the player's best score and it will not change unless they reach a higher one or disconnect.

Here's a command you can use to test it:
```js
test: function(gameServer, split) {
    var id = parseInt(split[1]);
    if (isNaN(id)) {
        Logger.warn("Please specify a valid player ID!");
        return;
    }
    for (var i in gameServer.clients) {
        if (gameServer.clients[i].playerTracker.pID == id) {
            Logger.warn(gameServer.clients[i].playerTracker.bestScore);
        }
    }
},  
```
Then you can add their best score to an array like this
```js
array.push(this.bestScore);
```

**Comment by gyeyoqu** [comment]
why push ? and not array.slice(0, 0, this.bestScore); ?

**Comment by Luka967** [comment]
What you're doing is the same as `array.unshift(this.bestScore`.

**Comment by gyeyoqu** [comment]
you are right, but im need a for to save the mass in all index and do while cicle

**Comment by Megabyte918** [comment]
`push` adds an element to an array.

**Comment by gyeyoqu** [comment]
@Megabyte918 but i would need a do while for add the mass in each element

**Comment by Megabyte918** [comment]
@gyeyoqu What do you mean by "Add the mass in each element"?

**Comment by gyeyoqu** [comment]
@Megabyte918 i think that is best save all values of mass, and save in one array , each value of mass in each index of the array , and after use Math.max.apply , to get the best mass , i right?

**Comment by Megabyte918** [comment]
`this.bestScore` already get's the player's highest score(mass) and it stays that way unless they disconnect.
`array.push(this.bestScore)` adds the player's best score to the array.

**Comment by Luka967** [comment]
Yes, using `Math.max.apply(array)` will return the largest number. Just use `array.push(this.bestScore)`.
However note that this will cause a memory leak if you don't remove a few elements from the array, as continously dying does and will make the array massive in size.
