### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by Wair1o17** [Megabyte918/MultiOgar-Edited#796]
How to add an image above the cell (this is not client sided), for example add a crown and appease with the same pellet system ...

Please help!

**Comment by FantasyIsBae** [comment]
This is client sided

**Comment by FantasyIsBae** [comment]
You can't draw images through the server 
Stop making issues unless you know what you are talking about.
if you don't believe me then respond when you can use canvas or canvas.ctx through a server 😄

**Comment by FantasyIsBae** [comment]
@MastaCoder @Megabyte918 Close this.

**Comment by Wair1o17** [comment]
@FantasyIsBae I'm sure this is not client sided ... but good I close this.

**Comment by FantasyIsBae** [comment]
This is client sided 
The image would have to be drawn on the client , using canvas .
Its simple and trust me im right

**Comment by gyeyoqu** [comment]
@Wair1o17 you can with implementattion of node-canvas

**Comment by Logan7432** [comment]
This would be cool.

**Comment by FantasyIsBae** [comment]
@gyeyoqu This is canvas for the node console not the web read the README its not hard :/

**Comment by FantasyIsBae** [comment]
node-canvas just sends the image to localhost using http and displays it @gyeyoqu read the README :/

**Comment by gyeyoqu** [comment]
https://github.com/Automattic/node-canvas @FantasyIsBae

**Comment by FantasyIsBae** [comment]
Exact same thing i was on about ...

**Comment by FantasyIsBae** [comment]
http://www.screenr.com/CTk

**Comment by Luka967** [comment]
look at that vintage github

**Comment by FantasyIsBae** [comment]
It looks so old lol @Luka967
