### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by MartincoderMlg** [Megabyte918/MultiOgar-Edited#798]
How to make bigger cells have more chance of split than smaller ones

**Comment by AlexHGaming** [comment]
What do you mean?

**Comment by MartincoderMlg** [comment]
Like when u are big always smaller cells split more than bigger ones

**Comment by FantasyIsBae** [comment]
This is not possible as when the split packet is sent the server loops through a client's (Player's) cells so in other words it is random.

**Comment by MartincoderMlg** [comment]
So it's client sided or there's no way ?

**Comment by FantasyIsBae** [comment]
There's no way and it is NOT client sided.

**Comment by Megabyte918** [comment]
@FantasyIsBae I think he means when you press space he wants the biggest cells to always split first even if smaller cells are still present and "splitable"
@MartincoderMlg Add one of these two functions to the beginning of the `splitCells` function in GameServer.js:
```js
// Bigger cells always split first
client.cells.sort(function (a, b) {
    return b._size - a._size;
});

// Smaller cells always split first
client.cells.sort(function (a, b) {
    return a._size - b._size;
});
```

**Comment by MartincoderMlg** [comment]
@Megabyte918  omg Thx D:

**Comment by FantasyIsBae** [comment]
@Megabyte918 I didn't understand him at the start he didn't explain the issue well enough 😄
