### ISSUE TITLE
Can you add Pellet Mode On The Minions?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#8]
Plz xD

**Comment by Megabyte918** [comment]
What do you mean?

**Comment by NameYT** [comment]
@Megabyte918 I want Collect Pellet Mode So Bots will collect pellets then they will come to me with mass :)

**Comment by NameYT** [comment]
The Hotkey is P

**Comment by Megabyte918** [comment]
just increase minionStartSize if you want more mass, and you can't use keys such as P on the agario client because it only supports Q, W, and the spacebar

**Comment by NameYT** [comment]
Make a Extension?

**Comment by NameYT** [comment]
Like SingaClan u-bot.ml etc they have collect pellet mode also Can you give me a download with MultiOgar That always have perfect popsplit? I cant change the settings

**Comment by NameYT** [comment]
Also i cant Host This Project on Codeanywhere there is an error :(

**Comment by ZfsrGhS953** [comment]
I think he means when you press P, minions turn into normal bots and vice versa. It'll use more CPU, but other than that, looks like it's possible.

**Comment by NameYT** [comment]
@ZfsrGhS953 I mean when you pressed P The Bots will collect pellets and when you press it again and Press q and space the bot get massed

**Comment by ZfsrGhS953** [comment]
Then you need to add bot AI, but only include food cells into minion's visible nodes.

**Comment by Megabyte918** [comment]
Sorry, but I am not making a separate botting extension just for minions to collect pellets on the way to you, nor am I adding it into the current minions. I do not wan't this project to become OgarUnlimited when there's too many features and too many stuff added onto it where it lags like crap when you run minions. I'd like to keep the features minimal, while also not having any useless ones. And as for popsplits, what do you mean by "the perfect popsplit?" Popsplit rates the same as vanilla? 100% working popsplits? Please be more specific. Also I got the same error, I'll commit the fix.

**Comment by Megabyte918** [comment]
If many people request that I add the minions collecting pellets feature, I may add it. But right now it just seems like its useless and the extra code would increase lag.

**Comment by NameYT** [comment]
The bot will only lag if i make them more massed like 99 = 100 mass?

**Comment by XtremePlayzCODE** [comment]
I request that you add the minion pellet feature

**Comment by NameYT** [comment]
:)

**Comment by Megabyte918** [comment]
Alright, since people are requesting it I guess I could start working on it, but I'm very busy right now, still have alot of features and bugs to fix so it might not be for a while until its implemented

**Comment by Tyler3D** [comment]
@Megabyte918 Is it possible to put the P hotkey on the agario macros and have it send a packet to the server?

**Comment by Tyler3D** [comment]
IDK much node.js.
Im more of a C++ kind of person

**Comment by XtremePlayzCODE** [comment]
Yes it is using Socket.io

P.S. I know I'm not megabyte but whatevs

**Comment by ZfsrGhS953** [comment]
@XtremePlayzCODE It uses WebSocket... Not socket.io like you think.

**Comment by Megabyte918** [comment]
I think it would just be easier to have it send a packet for P to the server so you can use the key however you like @Tyler3D

**Comment by XtremePlayzCODE** [comment]
You could implement socket.io tho

**Comment by Megabyte918** [comment]
Welp I tried, failed, tried again, failed, I do not know how to work with AI whatsoever. I'm sorry to say this but I might not be able to add pellet mode.

**Comment by ZfsrGhS953** [comment]
I'm don't develop Petridish Ogar anymore, so maybe I'll try to make a pellet mode because I have more free time now.

**Comment by ZfsrGhS953** [comment]
I'm now preparing my pull request for collect pellets feature. Quick facts about it:
Q is used to control collect pellets mode
It can be disabled in config
Target is recalculated every 10 ticks (400ms)
It only reduces performance by 15%
It's possible to fill the entire map with cells without leaving any spot open with 5000 minions, if you change food spawn settings to max in config.

**Comment by Megabyte918** [comment]
@ZfsrGhS953 Dayum your good! Also, why have you stopped developing Petridish Ogar? I thought it was a good project :3
