### ISSUE TITLE
Full Leaderboard for protocol v13

### ISSUE THREAD

**Issue by NuclearC** [Megabyte918/MultiOgar-Edited#800]
It took me time to research (lol) but here is it:

(uint8) opcode 0x33 or 0x34 (for party)
(uint16) friend count (only sent if op == 0x34)
then you need to loop though all packet and extract name records:
(uint8) flags
(uint16) read if flags & 1: place in leaderboard
(null_str8) read if flags & 2: player name
(null_str8) read if flags & 4: player account id (like 'facebook:139123192' but multiogar doesnt need this shit)
if (flags & 8) then its me
if (flags & 16) then its friend
and continue looping...

EDIT: yay 800th issue!

**Comment by AlexHGaming** [comment]
Make a PR

**Comment by ZfsrGhS953** [comment]
I think that the party system should be made by listening to a range of ports and flagging players on the same port as friends.

**Comment by FantasyIsBae** [comment]
@ZfsrGhS953 Not a bad idea :)

**Comment by Tyler3D** [comment]
@NuclearC Could you look into the flag for the arrow that points to your friend?

**Comment by SambyAgarYT** [comment]
@NuclearC Can you find a solution havig the yellow circle?

**Comment by NuclearC** [comment]
probs agar will send party token to private server as query parameter (or not?) we need to try that

**Comment by NuclearC** [comment]
@Tyler3D for arrow you need to send packets 160 and 161, which i didnt research yet

**Comment by SambyAgarYT** [comment]
@NuclearC Can you add the Yellow Border Thing?

**Comment by Luka967** [comment]
That's client-sided
*(or is it?)*

**Comment by SambyAgarYT** [comment]
where is the fuqin discord chat? im gonna make a new 1 :)

**Comment by SambyAgarYT** [comment]
https://discord.gg/g8yKmqM
https://discord.gg/g8yKmqM
https://discord.gg/g8yKmqM
https://discord.gg/g8yKmqM
https://discord.gg/g8yKmqM

Multi Ogar Edited ---- Discord Chat @Megabyte918 @AlexHGaming

**Comment by ZfsrGhS953** [comment]
@Luka967 He's talking about cell borders, not the map border.

**Comment by SambyAgarYT** [comment]
@ZfsrGhS953 Join the discord please we need the members whos always in this project

**Comment by NuclearC** [comment]
yellow circle is from packet 160/161

**Comment by MastaCoder** [comment]
@SambyAgarYT The old Discord is there, you got kicked because you constantly tagged everyone and was advertising every other minute.

**Comment by SambyAgarYT** [comment]
@MastaCoder srry can i go back again :) But the new discord is much better so they have to ask permission to make an issue

**Comment by MastaCoder** [comment]
You got kicked, you can still join from the same link lol

**Comment by SambyAgarYT** [comment]
@MastaCoder cant find it send it here :D

**Comment by NuclearC** [comment]
anyone minding on making a PR or should I do it myself with my shitty js code? lol

**Comment by MastaCoder** [comment]
Usually @Tyler3D does em lmao, Luka's been pretty busy recently, and no way would I ever trust my own JS code. ¯\_(ツ)_/¯

**Comment by Luka967** [comment]
I'll do it then lol

**Comment by Luka967** [comment]
erm...
![image](https://cloud.githubusercontent.com/assets/15956695/25624701/867750ee-2f5a-11e7-9640-0d64d155af0a.png)
... Agarian already did all of this

**Comment by Luka967** [comment]
... a month ago.

**Comment by SambyAgarYT** [comment]
Is it cilent sided ? the text are bigger but when in normal agario its small wtf lmfao moneyclip fuckedup

**Comment by Agarian** [comment]
Excuse me, but what did I do? I'm lost lol

**Comment by Agarian** [comment]
@SambyAgarYT The name text is bigger in both private and vanilla servers.

**Comment by AlexHGaming** [comment]
@MastaCoder Issue fixed
now close it daddy

**Comment by Tyler3D** [comment]
@AlexHGaming  No, only part of it is fixed

**Comment by MastaCoder** [comment]
ergh...

**Comment by NuclearC** [comment]
lol

**Comment by Megabyte918** [comment]
Do we still need this open? What's left to do?

**Comment by NuclearC** [comment]
Friend system :D its still possible to do

**Comment by FantasyIsBae** [comment]
wow megaboot is bck , many memez , much awesome

**Comment by Exobyte918** [comment]
@NuclearC add it ;) also the yellow circle thingggyhyyyy

**Comment by AlexHGaming** [comment]
@Exobyte918 This would not be useful. The yellow outline represents being in party mode, yet this project is doing ffa, experimental etc.

**Comment by Exobyte918** [comment]
@AlexHGaming add Party Gamemode?

**Comment by MastaCoder** [comment]
I'm pretty sure the yellow around cells is from the friends system which we is trying to be added.

**Comment by Exobyte918** [comment]
@MastaCoder U know this?
![image](https://cloud.githubusercontent.com/assets/28534731/26431512/f31f0154-4127-11e7-8b3f-eb003a71ea0e.png)
Its from minemoore :3
When u use pellet mode its different from this version also not laggy

**Comment by ZfsrGhS953** [comment]
@Exobyte918 It's an old version which only recalculated the targets every 10 ticks. @Megabyte918 made it calculate it every tick, because according to him that "increases minion performance"

**Comment by Exobyte918** [comment]
@ZfsrGhS953 help me pls add me in discord :) 
ExobyteZ#7288

**Comment by AlexHGaming** [comment]
@FantasyIsBae @Megabyte918 close, dis old version ;-;

**Comment by NuclearC** [comment]
what why close this?

**Comment by AlexHGaming** [comment]
This is an old version.

**Comment by Agarian** [comment]
Do we really need this open still?

**Comment by NuclearC** [comment]
xd
