### ISSUE TITLE
Virus split 

### ISSUE THREAD

**Issue by vincent95330** [Megabyte918/MultiOgar-Edited#803]
i want make perfect explose with virus .. 

i want This : 
![capture](https://cloud.githubusercontent.com/assets/19193995/25556034/43bc5978-2cf5-11e7-8f31-b3bae1a642bb.PNG)

Not this : 
![capture1](https://cloud.githubusercontent.com/assets/19193995/25556035/524f7a6a-2cf5-11e7-94bd-d334db1f1cc7.PNG)

Thx you :)

**Comment by ZfsrGhS953** [comment]
@vincent95330 You want perfect explosions? Here you go:
```playerMaxCells = 13379001```

**Comment by Megabyte918** [comment]
@vincent95330 Increase the size threshold until the size you are exploding at in the second picture is considered a small explosion. Either that or increase playerMaxCells until each cell is distibuted in a way similar to your first picture.

**Comment by Wair1o17** [comment]
@Megabyte918 @ZfsrGhS953 It refers to virus bursts as in MultiOgar 1.2.69, something like virus bursts as well ...

**Comment by Megabyte918** [comment]
If you would like virus explosions like in MultiOgar 1.02.69, add back the original functions for explosions
