### ISSUE TITLE
Pseudo colorful 

### ISSUE THREAD

**Issue by vincent95330** [Megabyte918/MultiOgar-Edited#805]
I would like to make sure to choose the color of the nickname during the game depending on the colors of the cell, for example when spawning with a color of blue cells, our pseudo then appears in yellow to make it resurface ... This with all the random color of the cell ... 
And also display it in the leaderboard .. 

Thx :D

**Comment by AlexHGaming** [comment]
Client sided.

**Comment by vincent95330** [comment]
why ?

**Comment by MastaCoder** [comment]
Changing the color of the name is client sided.

**Comment by Wair1o17** [comment]
yes, client sided
