### ISSUE TITLE
is fixed?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#806]
I have a question with all these updates, is the popsplit fixed? and Pushsplits?

**Comment by AlexHGaming** [comment]
Me, @Megabyte918 and other people are working onto this. You can refer to fixing popsplits, by clicking here(it made long distances better) (#776). Pushsplits are the same (#776) but you will have to configure the popsplit explosions for yourself.

**Comment by AlexHGaming** [comment]
You can refer to the [FAQ](https://github.com/Megabyte918/MultiOgar-Edited/wiki/Frequently-Asked-Questions) to see what you can change there.

**Comment by AlexHGaming** [comment]
#776 was even your own issue. So if it works fine for you, great well done!

**Comment by SambyAgarYT** [comment]
#807 Can you close dis issue plz :D
