### ISSUE TITLE
Bug on new update.

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#808]
I found a weird bug with the splitting. When I split my screen got weird and then as I merging back together I somehow ate myself. This is very hard to explain. I think it's a rare glitch though.

**Comment by Megabyte918** [comment]
> When I split my screen got weird

Can you explain what you meant by "got weird?" I could not reproduce this.
> then as I merging back together I somehow ate myself

That's whats supposed to happen when you merge, lol

**Comment by SambyAgarYT** [comment]
@Logan7432 Can you provide a screenshot or video that might help @Megabyte918

**Comment by Logan7432** [comment]
@SAmbyAgarYT soon as I get the time I'll try and get a video. It was a weird glitch and idk how it happened so I gotta figure out what I did to trigger it to happen.

**Comment by SambyAgarYT** [comment]
@Logan7432 OH okay :D

**Comment by AlexHGaming** [comment]
@Logan7432 Well?

**Comment by Logan7432** [comment]
@alexHgaming I'm not able to reproduce the bug. But It's out there but I'm not sure how it's caused.

**Comment by Logan7432** [comment]
Let me know to reopen this if it happens to someone else

**Comment by Logan7432** [comment]
@Megabyte918 What I mean by ate myself is when my parts merged into the main big blob it killed me and I had to start small again. What I meant by got weird is like my blob was off centered, I really don't know how to explain it.

**Comment by gyeyoqu** [comment]
@Logan7432 sure, you do not even know about nodeJS, and you're changing things

**Comment by Luka967** [comment]
@gyeyoqu And you think you're the god here. You're not.

**Comment by Logan7432** [comment]
@gyeyoqu What am I changing? Only thing I changed is gameserver.ini and a few things in Gameserver.js Not sure why your commenting on something that I solved.
