### ISSUE TITLE
Entity Bounce

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#81]
How i can make entities does not bounce from border @Megabyte918 's MultiOgar Code Removed i need for MultiOgar-Edited!

**Comment by Megabyte918** [comment]
@PrinceDark9243 remove lines 132 through 137 in Cell.js.
If it's a simple question like this it's not worth making an issue about, just comment and ask on another issue no need to make multiple.

**Comment by PrinceDark9243** [comment]
Its isnt wroking
Can u send me the cell.js file with that code!
