### ISSUE TITLE
Small Leaderboard fix

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#810]
I think we should make the leaderboard like real agar. It's a small thing like showing your place if you're not top 10. https://ibb.co/ktxmO5

**Comment by SambyAgarYT** [comment]
This is already in the project bro :3 Try use the updated version
@Megabyte918 @MastaCoder Close?

**Comment by AlexHGaming** [comment]
@SambyAgarYT This is not implemented.

**Comment by SambyAgarYT** [comment]
@AlexHGaming Invite me back to the discord why do i see mine?

**Comment by Logan7432** [comment]
@SAmbyAgarYT Yeah, this isn't in the server.

**Comment by SambyAgarYT** [comment]
@Logan7432 ikr

**Comment by MastaCoder** [comment]
> This is already in the project bro :3

> @SAmbyAgarYT Yeah, this isn't in the server.

> @Logan7432 ikr

I'm lost.

**Comment by Logan7432** [comment]
@MastaCoder What im trying to say is you know how on real agar.io how it shows what position your in below top ten? Look at picture above. I think that we should make it so the number your in shows on leadboard.

**Comment by Tyler3D** [comment]
@Logan7432 Port this to Multi-Ogar-Edited https://github.com/Tyler3D/Multi-Ogar-Edited-Unlimited-Plugins/blob/master/Leaderboard%20Mass%20%2B%20Leaderboard%20Position.js

**Comment by fayizan** [comment]
@Tyler3D how do I use your plugins :| ?

**Comment by ExobyteZ918** [comment]
@Logan7432 
![image](https://cloud.githubusercontent.com/assets/28534731/25830786/fd38b146-3491-11e7-9348-d7f95837e572.png)

**Comment by koda** [comment]
How do you get yellow rings like real agar?

**Comment by MastaCoder** [comment]
Duplicate
