### ISSUE TITLE
Auto-restart with max mass ....

### ISSUE THREAD

**Issue by vincent95330** [Megabyte918/MultiOgar-Edited#811]
I know it existed before but I can not reproduce it with this new update .. help me pls :/

**Comment by AlexHGaming** [comment]
https://www.codecademy.com/learn/javascript

**Comment by AlexHGaming** [comment]
:trollface:

**Comment by Wair1o17** [comment]
like my game? :trollface:

**Comment by MastaCoder** [comment]
Auto-restart is not a vanilla feature.

**Comment by gyeyoqu** [comment]
@Wair1o17 
Quiet, that you did not even create that code. n00b

**Comment by Megabyte918** [comment]
@vincent95330 This feature was implemented as a config a while ago, if you search deep into the commits you should be able to find the code and re-add it. I believe the config was named `playerMaxScore` or something like that.
