### ISSUE TITLE
Server crash bug

### ISSUE THREAD

**Issue by AdaptCharm** [Megabyte918/MultiOgar-Edited#812]
I just added the recent commits to my MultiOgar-Edited servers and for some reason the Experimental server crashed. 

I suspect the issue lies within the Experimental gamemode, because switching the serverGamemode (gameserver.ini) from Experimental to Teams (or any other gamemodes), seems to resolve the issue. All the other gamemodes works, except Experimental (not sure why).

Crash message:
[FATAL] TypeError: Cannot read property 'clone' of undefined
    at GameServer.mainLoop.movingNodes.forEach.GameServer.willCollide (/root/Experimental/src/GameServer.js:900:26)
    at Mode.Experimental.spawnMotherCell (/root/Experimental/src/gamemodes/Experimental.js:35:21)
    at Mode.Experimental.onTick (/root/Experimental/src/gamemodes/Experimental.js:65:14)
    at GameServer.mainLoop.movingNodes.forEach.nodesPlayer.forEach [as mainLoop] (/root/Experimental/src/GameServer.js:647:23)
    at Timer.listOnTimeout (timers.js:92:15)

Screenshot: https://i.gyazo.com/dc39266b76711d4b284b94d9543146fb.png

**Comment by AlexHGaming** [comment]
What you need to do is replace `var mother = new Entity.MotherCell(gameServer, null, gameServer.randomPos(), null);` with `var mother = new Entity.MotherCell(gameServer, null, gameServer.randomPos(), 149);` and then replace `if (!gameServer.willCollide(149, mother))` with `if (!gameServer.willCollide(mother))`

**Comment by AdaptCharm** [comment]
@AlexHGaming That seemed to resolve the crash issue on the Experimental server.

Can you make a pull request for this?

**Comment by AlexHGaming** [comment]
Sure

On 5 May 2017 15:13, "Jamie Isaksen" <notifications@github.com> wrote:

@AlexHGaming <https://github.com/AlexHGaming> That seemed to resolve the
crash issue on the Experimental server.

Can you make a pull request for this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Megabyte918/MultiOgar-Edited/issues/812#issuecomment-299475586>,
or mute the thread

**Comment by AlexHGaming** [comment]
done

**Comment by AdaptCharm** [comment]
Much appreciated.
