### ISSUE TITLE
Experimental Mothercell

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#813]
is there a way the mothercells can spew out pellets after the foodamount?

**Comment by MastaCoder** [comment]
Remove this if: https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/MotherCell.js#L38

There is another one below at the end of the for, but I'm not so sure if you remove that as well :(

**Comment by freaky767** [comment]
thank you!

**Comment by freaky767** [comment]
ok, i tried removing the line and it gives the error:
http://prntscr.com/f4j9fw

**Comment by gyeyoqu** [comment]
@freaky767 remove line 38 to line 40

**Comment by MastaCoder** [comment]
^^

**Comment by freaky767** [comment]
already fixed!
