### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#819]
Is there a way you can make the bots ( not the minions ) split and follow the nearest player?
I want to make it like abs0rb's FFA Bots

**Comment by AlexHGaming** [comment]
`make the bots split and follow the nearest player`
wtf do you mean

**Comment by freaky767** [comment]
ahh... The bots which you add with addbot?

**Comment by freaky767** [comment]
those bots, i want to make them just follow the nearest real player, and split max.

**Comment by freaky767** [comment]
you can try it out on abs0rb.me (FFA Bots)

**Comment by AlexHGaming** [comment]
I don't really see the point of it tbh. I see what u mean, but it can be boring

**Comment by MastaCoder** [comment]
Change the current bots config to instead of moving away from players to go straight into them.

**Comment by freaky767** [comment]
ok, how do i do that?

**Comment by MastaCoder** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/BotPlayer.js#L40

I couldn't program JavaScript at that time I worked on this and I still managed to make it, it's common sense.

**Comment by freaky767** [comment]
okay

**Comment by freaky767** [comment]
do i remove the line?

**Comment by freaky767** [comment]
also i dont have common sense, i dont know how to code.

**Comment by freaky767** [comment]
well, sorry, im not that type of dude who knows straight on everything.

**Comment by Megabyte918** [comment]
@freaky767 Try using what minions use to search for pellets, but instead make it so they search for players.
