### ISSUE TITLE
Bots severely glitch

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#820]
I use a fresh new server. There is one major bug with the AI. Sometimes, when you do like `addbot 10`, all the bots spawn in the exact same place. When I eat, it gives me the normal mass amount, but how to make them spawn not on top of eachother?

**Comment by MastaCoder** [comment]
Anybody confirm?

**Comment by AlexHGaming** [comment]
@MastaCoder http://makeagif.com/gif/glitch-Yhn0Ba

**Comment by Exobyte918** [comment]
This happens to my friend too ;)

**Comment by Gigabyte918** [comment]
it dosent happen on my server

**Comment by ExobyteZOfficial** [comment]
Happens to me ._.

**Comment by MastaCoder** [comment]
Old issue, can't be reproduced.

**Comment by AlexHGaming** [comment]
;-;
