### ISSUE TITLE
About some functions

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#821]
1) I wonder where are the functions that enter half the points of the first cell splitted into the new cell

2) The new cell splitted will be in index 0 of the array cells and where is the function?

3) where is the function that does not allow me to eat the bigger ones that I

**Comment by AlexHGaming** [comment]
`eat the bigger ones that I...` ?

**Comment by gyeyoqu** [comment]
If you do not respond, do not even contribute, refrain from responding stupidities..

**Comment by Luka967** [comment]
1. [Here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L886)
2. [Here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/PlayerCell.js#L30)
3. [Here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L761)
