### ISSUE TITLE
Is there an API to interact with this?

### ISSUE THREAD

**Issue by nerdtron123** [Megabyte918/MultiOgar-Edited#823]
Is there any sort of API i can use to create like nodejs bots with this?

**Comment by MastaCoder** [comment]
No API.

**Comment by Luka967** [comment]
Correction: yes. The only API you have is the stats HTTP server. Set that server's port [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L50) and use HTTP requests to get stats. It'll send a JSON formatted object containing some variables regarding the server.
You can find the return data logic [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L1080-L1108).
