### ISSUE TITLE
Bug?!

### ISSUE THREAD

**Issue by Exobyte918** [Megabyte918/MultiOgar-Edited#827]
So, i'm trying to play without names
Bug : 
![image](https://cloud.githubusercontent.com/assets/28534731/25805959/36cd83c2-3434-11e7-8454-037cf4b62c35.png)
2nd Bug : 
![image](https://cloud.githubusercontent.com/assets/28534731/25805980/5040c22e-3434-11e7-94d3-ac4c5cb950e5.png)
The black dot is the (cell) Me
@Megabyte918 is there anyfix?
I cant spawn without a name ;(

**Comment by AlexHGaming** [comment]
@ExobyteZ918 Did you use an unedited version of this "bug"?
Because otherwise if you did something to one of the files that could've made the bug. Try using an unedited version.

**Comment by MastaCoder** [comment]
Provide steps to reproduce.

**Comment by ExobyteZ918** [comment]
@AlexHGaming I'm using the latest version

**Comment by ExobyteZ918** [comment]
![image](https://cloud.githubusercontent.com/assets/28534731/25830580/700cd668-3490-11e7-9d21-02603ea7738d.png)
Same in Minions too ;( @AlexHGaming @MastaCoder @Megabyte918

**Comment by AlexHGaming** [comment]
1. Try using an UNEDITED VERSION, as in you not making ANY changes to ANY file (serverport excluded)
2. Does this occur on another client?

**Comment by Exobyte918** [comment]
@AlexHGaming Unedited same in other cilent

**Comment by AlexHGaming** [comment]
@Exobyte918 I will look into it.

**Comment by AlexHGaming** [comment]
@Exobyte918 I downloaded a fresh new server. It seems to work completely fine with 200 minions on.
Please verify you have no skin scripts enabled.
