### ISSUE TITLE
Game modes

### ISSUE THREAD

**Issue by F0RIS** [Megabyte918/MultiOgar-Edited#830]
Doest anyone have working Zombies/HungerGames or other unusual game modes for current MultiOgar version?

**Comment by freaky767** [comment]
Proxiemind has a Hunger Games server running on MultiOgar-Edited

**Comment by F0RIS** [comment]
@freaky767 thanks, but Proxiemind didn't finish work on it(

**Comment by Megabyte918** [comment]
@F0RIS I don't think so, I've been meaning to make some/port some over from Ogar but never really got into it.

**Comment by Gatoz** [comment]
porfavor agreguen los demas modos de juego , esta triste con solo 4 modo de juego

**Comment by OfficialKake** [comment]
@F0RIS I have a Hunger Games server working on 1.6.1
