### ISSUE TITLE
How to make GunSplit

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#832]
Issue is not off-topic, and is related to the project. <- SORRY :с 
How to make GunSplit as in gaver.io?

**Comment by AlexHGaming** [comment]
uhhhhhhhh what?
Please define 'gunsplit' and give photos.

**Comment by Exobyte918** [comment]
@AlexHGaming He mean a gamemode in gaver.io
When you split u get big its like pushsplit i think lmfao watch
the viedo on utube 
`https://www.youtube.com/watch?v=o6WWT5uqi0I`

**Comment by MastaCoder** [comment]
OpenAgar is the project for that!

**Comment by gyeyoqu** [comment]
@DeadLord1337 i will make for all

**Comment by DeadLord1337** [comment]
:с shit :(

**Comment by imnotNxhz1** [comment]
I got the configuration but I do not know how to get double the mass to split

gameserver.js
this.splitPlayerCell(client, cell, d.angle(), cell._mass*.5);  change to .92

gameserver.ini
playermaxcells: The ones you want, normal is 2 xD
playerRecombineTime = 0
splitvelocity: 980

you´re welcome :+1:

**Comment by gyeyoqu** [comment]
@imnotNxhz1  Incorrect , horrible answer

**Comment by Luka967** [comment]
@gyeyoqu Not horrible, not horrible at all. Players just won't get bonus mass.

**Comment by gyeyoqu** [comment]
@Luka967  I have already done it in 1 minute, but your client has performance problems with game modes that need zooming and a lot of mass

**Comment by imnotNxhz1** [comment]
@gyeyoqu You still need GunSplit?

**Comment by Megabyte918** [comment]
@DeadLord1337 There are configs regarding physics for a reason.
