### ISSUE TITLE
Skin URL

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#834]
Can you make the skin the URL link, as in OgarUnlimited to the skins file and there you can upload your skin:
nameskin ; http://i.imgur.com/*******.png (or any link on the image) 
When you log into the game to write: "nameskin" nick
All customers well and not all
" = <>

**Comment by AlexHGaming** [comment]
Client 
sided
We 
Can't
Do 
that

**Comment by Luka967** [comment]
Out of the scope of this project. Although this server parses skin names in <> tags, the client is the one who is supposed to get the skin image and draw it, not the server.

**Comment by AlexHGaming** [comment]
^^

**Comment by gyeyoqu** [comment]
@Luka967 u cant help me with ur client? 

There is a lot of LAG when the zoom is increased compared to your normal configuration, when it is in 1 cell of more than 100k

u can fix that? or where work that functions?

**Comment by gyeyoqu** [comment]
[Violation] 'requestAnimationFrame' handler took 340ms

**Comment by gyeyoqu** [comment]
@Luka967 i think is recommended to use persistent FPS rather than shifting.

**Comment by AlexHGaming** [comment]
@gyeyoqu Please DM him about this instead of saying it on an issue that is not related.

**Comment by Exobyte918** [comment]
`var = [skinurl ,id ,idbot], [x23/x54/x32]`
`This is cilent sided`

**Comment by MastaCoder** [comment]
Have the skins instead of making the flag the skin name into a URL? This isn't supported by this project.
