### ISSUE TITLE
Bug: Minions gets counted as players in the server stats

### ISSUE THREAD

**Issue by AdaptCharm** [Megabyte918/MultiOgar-Edited#835]
Long version: Whenever real players connects to the server to play with minions, the stats server counts the minions as real players, which apparently is a bug. Bots, however, are not included in the count - as expected.

Short version: The stats server counts minions as real players.

**Comment by AlexHGaming** [comment]
MultiOgar-Edited 1.6.1 is extremely buggy atm, @Megabyte918 has no internet atm (I think) and upon waiting a response to fix all the bugs.

**Comment by gyeyoqu** [comment]
i will fix

**Comment by AdaptCharm** [comment]
@gyeyoqu Have you fixed this?

**Comment by Megabyte918** [comment]
Fixed.
