### ISSUE TITLE
Spawning glitch

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#836]
SOMETIMES AND RARELY, when I die, 15 pieces are dead, but 1 is alive and still "kills me". When I spawn in, the view is extremely bugged and I would have to split many times to "be alive again". Did this ever happen to anyone else?

**Comment by Exobyte918** [comment]
Same lol u have discord can i join?

**Comment by AlexHGaming** [comment]
AlexHGaming#0849

**Comment by gyeyoqu** [comment]
@AlexHGaming  i can fix if u tell me where is the function

**Comment by gyeyoqu** [comment]
@AlexHGaming im not have that bug with last version

**Comment by Exobyte918** [comment]
`var = fixcode;)
`

**Comment by AdaptCharm** [comment]
@gyeyoqu Add me on Discord, Atmosphere™#3482

**Comment by AlexHGaming** [comment]
@gyeyoqu I am not completely sure where the function for spawning people into a server is in. Also, this happened on my client, also same to the vanilla. So it is server sided. I do not know where the function is, and I'm using the latest version (1.6.1) and not edited any of the spawning systems.

**Comment by MastaCoder** [comment]
Can anybody reproduce. Works fine for me.

**Comment by HyperAgar** [comment]
@MastaCoder please go to my issue so that i can help with this one. You closed it :/

**Comment by Megabyte918** [comment]
I also cannot reproduce this. Anyone else experiencing the same issue?

**Comment by Gigabyte918** [comment]
no this dosent happens to mea

**Comment by Exobyte918** [comment]
dis happens to me ;-;

**Comment by AdaptCharm** [comment]
Never happened to me

**Comment by MastaCoder** [comment]
Can't reproduce. Until this becomes major, it can't be an issue.
