### ISSUE TITLE
MAJOR ISSUE!!! Can't even PLAY!

### ISSUE THREAD

**Issue by HyperAgar** [Megabyte918/MultiOgar-Edited#837]
Major Problem:
![screenshot 12](https://cloud.githubusercontent.com/assets/27769111/26025766/ad2219bc-37bc-11e7-9fe9-7bce8da34fc7.png)
This is what happens when someone connects to the server. Version 1.6.1. How to fix?
Log files
[ServerLog.txt](https://github.com/Megabyte918/MultiOgar-Edited/files/998641/ServerLog.txt)

**Comment by AlexHGaming** [comment]
Does this happen on an unedited version of MultiOgar-Edited?

**Comment by HyperAgar** [comment]
Yes it does, i did not do anything to it. the configs are exactly as downloaded

**Comment by gyeyoqu** [comment]
@HyperAgar is problem of your independences installed

**Comment by FantasyIsBae** [comment]
@HyperAgar try updating node to the latest version.
Then redownload the project.
Install the dependencies.
Aaaaaaaaaaaaaaaaaand...........It should now work! 😃

**Comment by AlexHGaming** [comment]
@HyperAgar What version of node are you currently on?
(To see it, go to CMD and type `node -v`).

**Comment by MastaCoder** [comment]
Make sure you're using the latest version of this project.

**Comment by HyperAgar** [comment]
@MastaCoder I am

**Comment by MastaCoder** [comment]
Alright keeping this closed.

**Comment by HyperAgar** [comment]
@MastaCoder What ws verison should it be? mine is 1.1.0

**Comment by Megabyte918** [comment]
@HyperAgar 
> Next time dont close this like a bitch before its actually solved :/

Please be respectful to other people on this project, thank you.
