### ISSUE TITLE
Mass in the function

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#838]
Which variable serves to make an if / else, with the function resolverRigidCollision, according to the mass of the player ?

m.cell._mass <-- not work for me

**Comment by Megabyte918** [comment]
Can you clarify on what you are trying to do exactly?

**Comment by gyeyoqu** [comment]
im trying to do if/else in resolveRigidCollision depending the mass ... i mean to

if(m.cell_mass > 5000) {

 var r1 = push * m.cell.radius / rt * 0.9;
    var r2 = push * m.check.radius / rt * 0.9;

}
else {
 var r1 = push * m.cell.radius / rt * 0.5;
    var r2 = push * m.check.radius / rt * 0.5;

}

**Comment by Luka967** [comment]
you forgot a dot in your if statement...

**Comment by gyeyoqu** [comment]
@Luka967 ?

**Comment by AlexHGaming** [comment]
I am pretty sure this is not the latest version (idk)
And idk whats ur trying to do with the rigid, but it sounds pretty useless to me (idk x2)

**Comment by gyeyoqu** [comment]
@AlexHGaming  ??

**Comment by AlexHGaming** [comment]
What
are
you
trying
to
do 
with
the
rigid
collision

**Comment by gyeyoqu** [comment]
an if/else depending the mass of player

**Comment by Megabyte918** [comment]
`m.cell._mass` or `m.cell._mass && m.check._mass` should work fine.

**Comment by gyeyoqu** [comment]
m.cell._mass not work for me

**Comment by gyeyoqu** [comment]
so , i cant do &&

**Comment by gyeyoqu** [comment]
help me megabyte918

**Comment by Megabyte918** [comment]
@gyeyoqu If this works then there is an error with the code you were trying to use before. 
```js
if (m.cell._mass > 5000) {
    Logger.warn(true);
} else {
    Logger.warn(false);
}
```
