### ISSUE TITLE
Can my minion be my friend like in party mode?

### ISSUE THREAD

**Issue by ImmortalLegend** [Megabyte918/MultiOgar-Edited#839]
It's easier to find my minion if we die

**Comment by Wair1o17** [comment]
when no have friends :v

**Comment by AlexHGaming** [comment]
Vanilla client sided.

**Comment by ImmortalLegend** [comment]
but how to do that?
I think Megabyte981 should add it

**Comment by Wair1o17** [comment]
@ImmortalLegend That is no posible.

**Comment by MastaCoder** [comment]
Nope.
