### ISSUE TITLE
add indicator to admin in the chat

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#84]
Indicator as: 

[ADMIN]USER : HELLO

and message to all when a admin connect

[ADMIN]Arnold  has connected..

**Comment by AlexandriteErikParacelsus** [comment]
@RelTakeover why

**Comment by Megabyte918** [comment]
@RelTakeover there is no need for this with the server, but if you have a custom client with a chat you can make that happen
