### ISSUE TITLE
Is there a way to get old version of multi ogar edited?

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#840]
Is there a way to get old version of multi ogar edited? if you know comment down Thanks!

**Comment by Gigabyte918** [comment]
i need the version 1.4.0 does anyone have?

**Comment by ZfsrGhS953** [comment]
@Gigabyte918 [Download it here](http://www.mediafire.com/file/dt8461dj6e28zag/Minions+that+collect+mass+server+-+By+MineMoore+and+Megabyte.zip)

**Comment by Gigabyte918** [comment]
Thanks Thank you very much love you all now i can able to play on my mobile thank you!

**Comment by Gigabyte918** [comment]
You can Close this issue i am too lazy to click button :v

**Comment by Gigabyte918** [comment]
the server is working but when i edit the gamerserver.ini the server isnt working could you give real not edited version on MultiOgar 1.4.1

**Comment by ZfsrGhS953** [comment]
@Gigabyte918 You probably changed the server port by mistake, reinstall it and try again.

**Comment by Gigabyte918** [comment]
could you change this code to make player loss mass but doesnt split

**Comment by Gigabyte918** [comment]
GameServer.prototype.autoSplit = function (client, cell1) {
    // rec mode
    if (!client.rec) {
        var maxSize = this.config.playerMaxSize;
    } else {
        maxSize = this.config.playerMaxSize * 3;
    }
    
    // check size limit
    var checkSize = !client.mergeOverride || client.cells.length == 1;
    if (checkSize && cell1._size > maxSize && cell1.getAge(this.tickCounter) >= 15) {
        if (client.cells.length >= this.config.playerMaxCells) {
            // cannot split => just limit
            cell1.setSize(maxSize);
        } else {
            // split
            var maxSplit = this.config.playerMaxCells - client.cells.length,
            maxMass = maxSize * maxSize,
            count = (cell1._sizeSquared / maxMass) >> 0,
            count = Math.min(count, maxSplit),
            splitSize = cell1._size / Math.sqrt(count + 1),
            splitMass = splitSize * splitSize / 100,
            angle = Math.random() * 2 * Math.PI,
            step = 2 * Math.PI / count;
            for (var k = 0; k < count; k++) {
                this.splitPlayerCell(client, cell1, angle, splitMass);
                angle += step;
            }
        }
    }
};

**Comment by Gigabyte918** [comment]
atleast give answer to my Question!

**Comment by MastaCoder** [comment]
At least use the latest version of the project.

**Comment by Gigabyte918** [comment]
You cant able to understand why i want this!

**Comment by Gigabyte918** [comment]
after getting the code i can able release the mobile private server

**Comment by MastaCoder** [comment]
Your install was bad for one of the modules, I can't really help with that.

**Comment by Gigabyte918** [comment]
Thanks I got it to working soon i will release the mobile blob server!
