### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#841]
how know the mass of the top 1 , in gameServer.js

**Comment by AlexHGaming** [comment]
Where do you want to know the mass of number 1, console or leaderboard?

**Comment by MastaCoder** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L444

**Comment by gyeyoqu** [comment]
@MastaCoder  thanks
