### ISSUE TITLE
Why lags?

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#842]
Why lag when more than 100 cell? everything becomes very slow. And version previously there was not any lag even with 1000 cell is not what was not. 

Fix it please

**Comment by AlexHGaming** [comment]
What are you using to host?

**Comment by DeadLord1337** [comment]
No i use standart port 443
And open port 8080 for playing my friends

**Comment by Wair1o17** [comment]
@DeadLord1337 Codeanywhere?

**Comment by MastaCoder** [comment]
Performance seems fine for me.

**Comment by AlexHGaming** [comment]
@DeadLord1337 I mean what are you using to host the server that makes it public. Is it an IDE platform? (codeanywhere, c9 etc)

**Comment by AlexHGaming** [comment]
What is your CPU and Graphics Gard(s)?

**Comment by DeadLord1337** [comment]
so sense I had no lag on previous versions(updates)and when I downloaded the latest version I noticed the lag, the lag started when there were more than 100 parts. this is a server something, and does not depend on the configuration of my computer (everything was fine before) I can record video on the old version 05.05.17 and new

**Comment by DeadLord1337** [comment]
1 time when I play, this is the latest version
2 times, this version 05.05.17
https://streamable.com/w17lz

**Comment by Wair1o17** [comment]
@DeadLord1337 lag is from client

**Comment by DeadLord1337** [comment]
Agar client too lags

**Comment by Luka967** [comment]
You're having 40 FPS on the start screen on astr.io. Your command prompt window leaves a trail behind when moving. Of course it's going to lag, your PC's components are weak even for opening a browser.

**Comment by DeadLord1337** [comment]
record = -20-30 fps...

**Comment by DeadLord1337** [comment]
Have you watched the video until the end ?

**Comment by DeadLord1337** [comment]
in short, you don't fucking want to help or you stupidly don't understand...
and I the problem is described in detail

**Comment by Luka967** [comment]
I have.
>Of course it's going to lag, your PC's components are weal even for opening a browser.

**Comment by Megabyte918** [comment]
@DeadLord1337 Could not reproduce the lag you are talking about, both with 100 cells and 1000 (latest version). I recommend getting a better PC.
Also, please be respectful to others on this repository. People won't help you if you are mean to them.
