### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by ogarcpl** [Megabyte918/MultiOgar-Edited#843]
How to allow Longer messages like if the message length is more than 20 it won't send it

**Comment by gyeyoqu** [comment]
you want allow longer messages, but not send if the message length is more than 20 letters? wtf

**Comment by ogarcpl** [comment]
"you want allow longer messages" Yes how ?

**Comment by gyeyoqu** [comment]
is client side, what is your client?

**Comment by AlexHGaming** [comment]
@gyeyoqu It is both server and client sided. Client is whatever max length it supports. Server is what limit you want to set it to.

**Comment by ogarcpl** [comment]
@AlexHGaming  How to change the server one ?
I wasn't able to find where it's

**Comment by gyeyoqu** [comment]
@AlexHGaming nope is client side

**Comment by ZfsrGhS953** [comment]
@gyeyoqu It has nothing to do with the client.

**Comment by ogarcpl** [comment]
Someone know where it's ?

**Comment by MastaCoder** [comment]
Chat messages?

**Comment by ogarcpl** [comment]
Yes

**Comment by ogarcpl** [comment]
@Megabyte918

**Comment by ogarcpl** [comment]
Guess what @gyeyoqu  was right it was client sided my client  Anyways thanks all

**Comment by gyeyoqu** [comment]
I know what I'm talking about :)

**Comment by ZfsrGhS953** [comment]
@gyeyoqu Because both of you have the same message-cutting client that you stole from a Turkish agar.io clone.
