### ISSUE TITLE
Linux error (And IDE)

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#844]
When doing the following:
`cd MultiOgar-Edited`
`cd src`
`sudo node index`
It shows this error:
![image](https://cloud.githubusercontent.com/assets/23644244/26068590/dd577bec-3995-11e7-8d2a-b2ce7504308f.png)

**Comment by plazo21** [comment]
could you help me pls console plus

**Comment by AlexHGaming** [comment]
This shows the same error to console plus.

**Comment by Luka967** [comment]
Replace
```js
(x, y) => x + y;
```
with
```js
function(x, y) { return x + y; }
```

**Comment by AlexHGaming** [comment]
@Luka967 we gotta fix this lol

**Comment by MastaCoder** [comment]
It's because you're using an old version of Node.js. (I think)
