### ISSUE TITLE
Really trying to understand how to make my own server.

### ISSUE THREAD

**Issue by LemonDoo** [Megabyte918/MultiOgar-Edited#849]
https://github.com/Megabyte918/MultiOgar-Edited/tree/master/run

I'm using this README to understand how to create a local server on just localhost as they said.
It says specifically that the URL will be "127.0.0.1:1234", which is exactly what I want.

however, I am a complete noob at this kind of stuff - can anyone give me any pointers  on how to create this server? I don't quite understand the README as it specifies I have to use a daemon (which is Unix? I have Windows 10).

Do I literally just run "win-Start.bat" after dependencies are installed and go onto "127.0.0.1:1234" and it should work?

**Comment by AlexHGaming** [comment]
@LemonDoo You have to install node.
The server port in Gameserver.ini is what port it runs off
then do `clientName/?ip=127.0.0.1:PORT`
replace client name with the client you want to play it on, for example astr.io running on port 8080
`astr.io/?ip=127.0.0.1:8080`

To install server, like i said befrore you have to install node, you have to download/clone it, extract if needed, install dependencies, do changes in gameserver.ini, launch the start.sh, then go to the URL of whatever it is set to.

**Comment by MastaCoder** [comment]
Go to agar.io and connect to 127.0.0.1:1234. If you're looking for a client try Cigar from the CigarProject and install it on something running under Apache and PHP.
