### ISSUE TITLE
client side? or not?

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#851]
is there a way you can make it, so that the decay updates like every 20ms?

**Comment by AlexHGaming** [comment]
Not client sided. Configure the decay in the gameserver.ini

**Comment by MastaCoder** [comment]
You can't change the ticks since it's part of another tick, forgot what it was. If you want you can move it or add another tick for decay in gameserver.js.

**Comment by freaky767** [comment]
damn, okay, thanks
