### ISSUE TITLE
Switch control with minion 

### ISSUE THREAD

**Issue by vincent95330** [Megabyte918/MultiOgar-Edited#852]
I would like to know how to change the way to control his minion .. stay pressed Q to control his bots and dropped the button to control himself ... thank you

**Comment by AlexHGaming** [comment]
🤦‍♂️

**Comment by SAVAGE2001** [comment]
lmao

**Comment by AlexHGaming** [comment]
http://www.wikihow.com/Increase-Your-General-Knowledge

**Comment by FantasyIsBae** [comment]
http://lmgtfy.com/?q=How+to+press+the+letter+Q+on+a+keyboard%3F

**Comment by MastaCoder** [comment]
You cannot change the keybind since that would require changes with the client as well which vanilla does not support.

**Comment by Megabyte918** [comment]
@vincent95330 Check gameserver.ini. There are configs for changing the control mode from using Q to using the E, R, T, and P keys.
