### ISSUE TITLE
how can i use

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#853]
i know this is an duplicate but i could not find anything how do i connect with alis.io/=ip=
or back.alis.io/?ip=

is this client sideds sorry idk i think it is tho sorry

**Comment by freaky767** [comment]
i think alis changed their protocol.
if you click F12 and use the connect function, it says "protocol error, server is incompatible with this client"

**Comment by FantasyIsBae** [comment]
@freaky767 Is right. 
Close pls mookan

**Comment by AlexHGaming** [comment]
1. This is client sided.
2. [nbk.io](http://nbk.io) may be the closest result to having an alis experience.
Close pls mookan x2

**Comment by plazo123** [comment]
so if i change my protocol to the one like alis will it work ?

**Comment by plazo123** [comment]
@AlexHGaming just add a 3. ass well
