### ISSUE TITLE
Running MultiOgar Edited

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#854]
Is there a way to run Multi Ogar on Android device with roots if anyone know can someone explain otherwise Thank You!

**Comment by FantasyIsBae** [comment]
Try this :http://lmgtfy.com/?s=k&q=How+to+kill+myself%3F
JK 😆 

Try installing jxcore on your android device.

**Comment by AlexHGaming** [comment]
well done @FantasyIsBae

**Comment by Luka967** [comment]
do you even realize how slow that thing would be

**Comment by AlexHGaming** [comment]
Slower than @gyeyoqu trying to solve his own problems.

**Comment by FantasyIsBae** [comment]
@AlexHGaming Definitely

**Comment by MastaCoder** [comment]
https://medium.freecodecamp.com/building-a-node-js-application-on-android-part-1-termux-vim-and-node-js-dfa90c28958f
