### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by Seitas** [Megabyte918/MultiOgar-Edited#855]
When I try to run server I'm getting this:

![ImageError](http://mineworld.com.pl/galeria/error.png)

> **/var/www/html/ogar/src/modules/CommandList.js:820
>         Logger.print("Average score: " + (scores.reduce((x, y) => x + y) / sco
>                                                                 ^
> SyntaxError: Unexpected token >
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/var/www/html/ogar/src/index.js:3:16)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)**
>

**Comment by AlexHGaming** [comment]
Duplicate,
please check other closed issues to solve your answer.

**Comment by MastaCoder** [comment]
Update your Node.js version to the latest.
