### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Exobyte918** [Megabyte918/MultiOgar-Edited#856]
![image](https://cloud.githubusercontent.com/assets/28534731/26228303/35239e50-3c6b-11e7-8e07-5d97cadfdd55.png)
so i started lms then when i split this happens ;-;
@MastaCoder @Megabyte918 @AlexHGaming
fex plz

**Comment by plazo123** [comment]
update node.js use recommended  for most users  and dowload multiogara again

**Comment by plazo123** [comment]
it works for me

**Comment by plazo123** [comment]
@Exobyte918

**Comment by Megabyte918** [comment]
@Exobyte918 Could not reproduce. Please make sure you are using the latest version.
