### ISSUE TITLE
LAG?!

### ISSUE THREAD

**Issue by Exobyte918** [Megabyte918/MultiOgar-Edited#857]
Lagging if you feed w/ without macro
lagg
not PC
not internet
Totally the game ;-;

**Comment by freaky767** [comment]
clientside

**Comment by freaky767** [comment]
close issue

**Comment by AlexHGaming** [comment]
I do not get lag when I am feeding. @freaky767 it maybe client sided, idk, but please make sure your PC is beneficial for the project, (as in, a constant 30FPS+).

**Comment by Exobyte918** [comment]
im using old version since the latest is not working for meh ;3

**Comment by Exobyte918** [comment]
@AlexHGaming Help me with the popsplits please ;) New Version when i add the code it just make the player move faster ;-;

**Comment by MastaCoder** [comment]
Latency of the server, feeding fine here. Make sure to check eject cooldown.
