### ISSUE TITLE
Where in the code is the player actually spawned in?

### ISSUE THREAD

**Issue by LemonDoo** [Megabyte918/MultiOgar-Edited#858]
Weird question, but I'm trying to understand the source code and therefore trying to understand what method calls on spawnPlayer(player,pos) from Gameserver.js.

It seems to be called on by a listener from the Websocket, but i have CTRL+F'd all the javascript files for spawnPlayer(player,pos), but nothing has been showing up. It's really bugging me!

**Comment by Agarian** [comment]
There are two main functions in GameServer for spawning entities. One under the name `GameServer.prototype.spawnPlayer`, and another one near it under the name `GameServer.prototype.spawnCells`. Though, you want the player spawning function, so look for `spawnPlayer`.

**Comment by LemonDoo** [comment]
I meant where is the spawnPlayer method USED, not where it is defined?in what js file is spawnPlayer actually used?

**Comment by Tyler3D** [comment]
@LemonDoo 
Where spawnPlayer is Used
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gamemodes/Mode.js#L27
This calls that
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L170
Which is called from...
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PacketHandler.js#L306
