### ISSUE TITLE
About call some functions

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#859]
When you instantiate the playertracker object in gameServer.js, when you send "this" (which refers to sending the gameserver), what is it sending? All the information from gameserver.js? And with 'ws' refers to the parameter of the onclientsocketopen function, which is the player ip?

`new PlayerTracker(this, ws);`

**Comment by ZfsrGhS953** [comment]
@gyeyoqu ```this``` only sends the pointer.
