### ISSUE TITLE
console plus

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#861]
ik this is dulicate but i cant find anything to my awnser 

how cane i use console plus on my server

**Comment by AlexHGaming** [comment]
you cd into it.
If it brings an error, update your version of node.js.

**Comment by plazo123** [comment]
into with one html or js

**Comment by plazo123** [comment]
@AlexHGaming

**Comment by AlexHGaming** [comment]
Are you using a solo server or public server?

**Comment by plazo123** [comment]
solo and codeanywhere 

@AlexHGaming @AlexHGaming 
@AlexHGaming @AlexHGaming

**Comment by plazo123** [comment]
and whats your website

**Comment by Wair1o17** [comment]
@plazo123 Codeanywhere don't work with console-plus.

**Comment by MineMooreALT** [comment]
@Wair1o17 Do you have discord?

**Comment by plazo123** [comment]
@Wair1o17
do you know any auto restart like alis.io please tell me

**Comment by MineMooreALT** [comment]
@plazo123 This has been talked about and is honestly quite simple. Do you have discord i can help you @plazo123  ?

**Comment by plazo123** [comment]
yes plazo#1640 @

**Comment by plazo123** [comment]
@MineMooreALT

**Comment by MineMooreALT** [comment]
@Wair1o17 Please send your discord i need to pm u

**Comment by AlexHGaming** [comment]
@plazo123 Auto-restarts have been mentioned a bunch of times on this repository.
@Wair1o17 Is correct. Codeanywhere is an IDE so yeah it wouldn't work I think..

**Comment by AlexHGaming** [comment]
@plazo123 http://agarahg.tk

**Comment by MineMooreALT** [comment]
@AlexHGaming http://minemoore.uk.to/agarplus/

**Comment by plazo123** [comment]
@AlexHGaming on solo ?

**Comment by plazo123** [comment]
@MineMooreALT

**Comment by Wair1o17** [comment]
@MineMooreALT Shair-Wair.io#7657

**Comment by plazo123** [comment]
AlexHGaming  how do i use on local host after i cd into it

**Comment by Megabyte918** [comment]
@plazo123 View the README in /run for instruction.

**Comment by plazo123** [comment]
@Megabyte918 i did after i cant use login or thats where im stuck :)

**Comment by AlexHGaming** [comment]
@plazo123 To login in with admin, or whatever, in the chat, do the following:
Go to userroles in the `enum` section of the files.
Get rid of the ip's so it's like `""`
Then set a password which is below the `ip` line. 
Restart server
then go `/login PASSWORD` obviously replace PASSWORD with ur password.
