### ISSUE TITLE
how do i make 

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#862]
not sure if issue sorry
how do i make an ultra split so when i split i merge before 0 what is merge time

**Comment by AlexHGaming** [comment]
This is a [duplicate](https://github.com/Megabyte918/MultiOgar-Edited/issues/792)
Please check other issues to see if your answer has been answered.

**Comment by plazo123** [comment]
@AlexHGaming  sorry i checked it but i could not find my awnser anyway thanks

**Comment by plazo123** [comment]
@AlexHGaming have you got discord and do you want to use my 24/7 server on your site

**Comment by AlexHGaming** [comment]
@plazo123 AlexHGamingYT#0849

**Comment by plazo123** [comment]
elite samria ? 
@AlexHGaming

**Comment by Megabyte918** [comment]
@plazo123 There are configs regarding physics for a reason, I suggest using them to get what you want.
