### ISSUE TITLE
is it Possible?

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#863]
is there a way to eat my w after some seconds but other cell can eat it instantly?

**Comment by AlexHGaming** [comment]
??

**Comment by Luka967** [comment]
If you eject a cell into the border, you'd immediately eat it. That won't happen in vanilla.
He wants the vanilla mode.

**Comment by Gigabyte918** [comment]
yes i want that

**Comment by Megabyte918** [comment]
Duplicate of #103 and #317.
And yes there is, but it would reduce performance with ejected mass.
