### ISSUE TITLE
sorry how can i make a 

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#864]
kill me 
@AlexHGaming

**Comment by AlexHGaming** [comment]
> and how can i add a code so the leader board will evvery 5 mins it says smthing auto matic
This is client sided.

> how can i make it so when i split my mass gets bigger
I don't find the point of it tbh, I'll just leave this here:
https://www.codecademy.com/learn/learn-javascript

**Comment by Megabyte918** [comment]
@plazo123 
> and how can i add a code so the leader board will evvery 5 mins it says smthing auto matic

Do the board command every 5 minutes, lol

> how can i make it so when i split my mass gets bigger

You can try editing [this line](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L782) or [this line.](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L785)

**Comment by plazo123** [comment]
@Megabyte918 you can do the board command evvery 5 min i dont mind :)
