### ISSUE TITLE
where is the code ?

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#865]
where is the code wich makes conntact wwith clients ik this is client sided but please

**Comment by AlexHGaming** [comment]
CTRL+F is your friend.

**Comment by plazo123** [comment]
?

**Comment by cowpits** [comment]
@plazo123 hit me on discord, i think what you're looking for is packetHandler.js just a guess.
hey @AlexHGaming

**Comment by AlexHGaming** [comment]
yo @cowpits 
and @plazo123 Connections are run through the packethandler, with network in the gameserver.js.
