### ISSUE TITLE
automatic restart?

### ISSUE THREAD

**Issue by kekko9994** [Megabyte918/MultiOgar-Edited#866]
Can I add the automatic restart in gameserver.ini?
Please

**Comment by suprix** [comment]
Duplicate #684

**Comment by freaky767** [comment]
^ close issue

**Comment by AlexHGaming** [comment]
Do you not understand how many issues asked this?

**Comment by AlexHGaming** [comment]
Duplicate of:
#141 #146 #266 #447 #458 #811 #596 #527 #728 #76 #684 #243

**Comment by AlexHGaming** [comment]
@Megabyte918
