### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#872]
1. is there a way the minions can have their id on their name?
2. how can the minions have like a delay for splitting, and following?

**Comment by Exobyte918** [comment]
2 is not gonna be added cuz alot people asking it its uessless slfuq

**Comment by freaky767** [comment]
ok

**Comment by gyeyoqu** [comment]
1 ) no , because they havent ID..
2 ) yes, use setTimeout

**Comment by AlexHGaming** [comment]
@freaky767 1) This will be client sided as the client identifies. ( i think)
2) Like @gyeyoqu said, use a setTimeout on the minions to whatever amount of seconds that maybe.

**Comment by Tyler3D** [comment]
@freaky767  For number 1 change https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/packet/UpdateNodes.js#L93
to
writer.writeBytes(node.owner.pID + " " + cellName);
Do the same for https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/packet/UpdateNodes.js#L173
and https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/packet/UpdateNodes.js#L261
and https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/packet/UpdateNodes.js#L353

**Comment by Exobyte918** [comment]
@gyeyoqu halp me with delay minionz pls

**Comment by freaky767** [comment]
damn, thanks!

**Comment by freaky767** [comment]
it gives a error
[FATAL] TypeError: data.copy is not a function
