### ISSUE TITLE
Error/Bug

### ISSUE THREAD

**Issue by Exobyte918** [Megabyte918/MultiOgar-Edited#873]
While doing playerlist in the latest version this happens

**Comment by Exobyte918** [comment]
wtf cant send screenshot here ;-;

**Comment by AlexHGaming** [comment]
I'm gonna see if this happens to me.

**Comment by AlexHGaming** [comment]
Could not reproduce. Make sure you did not edit anything related to the playerlist string
@Megabyte918 close please dad
