### ISSUE TITLE
It will not load for me.

### ISSUE THREAD

**Issue by VSabertail** [Megabyte918/MultiOgar-Edited#874]
I just tried to try download agar.io private servers and ogar servers and this one worked for me so then i started it and went to http://agar.io/?ip=127.0.0.1:443 and it wont load its been loading for a while now. Is this an issue with the server or my pc? If there is a patch for this let me know or let me know whats wrong with my pc if its a problem with that

**Comment by VSabertail** [comment]
Console works fine but agar.io doesnt't.

**Comment by plazo123** [comment]
you want fix ? i have it

**Comment by VSabertail** [comment]
nevermind i had to go to old ogar server

**Comment by VSabertail** [comment]
close it

**Comment by Exobyte918** [comment]
u must logout

**Comment by VSabertail** [comment]
oh thanks

**Comment by VSabertail** [comment]
and in game server .ini when i change recombind time it doesnt work

**Comment by AlexHGaming** [comment]
@VSabertail Close this issue then, and about that recombine time, if you want instant merge, set it to 0 in `playerRecombineTime`
The value is the amount of secs it takes to recombine. It depends on your mass size, the bigger, the longer.

**Comment by VSabertail** [comment]
no i want it to recombind faster not instant merge and i dont know how to close

**Comment by VSabertail** [comment]
nevermind
