### ISSUE TITLE
Gameserver.ini recombine issue (wont work even when i change it) .

### ISSUE THREAD

**Issue by VSabertail** [Megabyte918/MultiOgar-Edited#875]
Iv'e been messing around with Gameserver.ini and found out the one of the best ones don't work the recombine time iv'e changed it many times and it still doesn't work. Anyone know whats going on?

**Comment by VSabertail** [comment]
I got the skins to work atleast but i want this to work

**Comment by AlexHGaming** [comment]
Define 'doesn't work' please.

**Comment by AlexHGaming** [comment]
If you are trying to make the cells recombine at the value they are set to, this would ruin game balance, so we made it so it's like vanilla, it works fine for me.

**Comment by VSabertail** [comment]
Does not work

**Comment by VSabertail** [comment]
well
why cant it be like ogarul
that was better
this one is not good so many bugs

**Comment by VSabertail** [comment]
is there any better ones out there

**Comment by AlexHGaming** [comment]
@VSabertail If you are saying that ogarul is better, maybe download it [here](https://github.com/Codeidiot737/Ogar-unlimited) (I just searched for this lol)
And if you are saying this is bad, and has too many bugs, why are you saying this?

> is there any better ones out there

Ever heard of "forked repos" ? Use an older version?

**Comment by VSabertail** [comment]
sORRY

**Comment by VSabertail** [comment]
I want it so you can change the recombine

**Comment by VSabertail** [comment]
And how do you change the skin when your using agar.io

**Comment by AlexHGaming** [comment]
@VSabertail You can change the combine in the gameserver.ini, it works alright
And skins are client sided

**Comment by VSabertail** [comment]
ok

**Comment by VSabertail** [comment]
and gameserver does not have a .ini at the end

**Comment by AlexHGaming** [comment]
There are 2 gameservers, gameserver.ini and gameserver.js.

**Comment by ZfsrGhS953** [comment]
@VSabertail Then why did you write it with ".ini" in the issue title?

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 is right. Why did you put .ini in the title

**Comment by VSabertail** [comment]
cause you guys will be confused

**Comment by VSabertail** [comment]
but thats the file type
i just wanted to know which one is which

**Comment by VSabertail** [comment]
and there is another problem
![image](https://cloud.githubusercontent.com/assets/17517280/26511137/a23bc54e-422e-11e7-8390-56dcf1387d69.png)

**Comment by VSabertail** [comment]
wont work

**Comment by VSabertail** [comment]
and neither does cell.sh

**Comment by FantasyIsBae** [comment]
@VSabertail Different protocols.

**Comment by AlexHGaming** [comment]
@VSabertail Cell.sh? is that even a thing?
and log out of facebook/google and try again.
gameserver.ini is the config
the js one is the one that contains all the functions for .ini.

**Comment by VSabertail** [comment]
ok
