### ISSUE TITLE
Issue with ERTP controls

### ISSUE THREAD

**Issue by Tomazz95** [Megabyte918/MultiOgar-Edited#876]
Hello creator,
I have small issue. When i paste the code in tampermonkey few errors pop up and the E, R, T and P keys aren't working. Please reply how ti fix it because multi ogar is the best private server ever and i want to control my bots with E, R keys.

**Comment by SAV-404** [comment]
it's not an issues  -_-....this is what do you have to do : MultiOgar-Edited ----> Src ----> gameserver.ini then  replace "disableERTP = 1" By "disableERTP =  0" and replace "collectPellets = 0"  By  "collectPellets = 1"... ;-;
