### ISSUE TITLE
Skins will NOT work for me

### ISSUE THREAD

**Issue by VSabertail** [Megabyte918/MultiOgar-Edited#877]
i do <shark> <cookie> <kraken> <bear> <banana> they all wont work

**Comment by Exobyte918** [comment]
? what do you mean?

**Comment by VSabertail** [comment]
The skins will work for the bots but they wont work for me when i use them

**Comment by SAV-404** [comment]
go here if you wanna play wit skins : https://github.com/SAV-404/Agario-skins

**Comment by MastaCoder** [comment]
It's not worked on the Agar,io client for a while now. (I believe)
