### ISSUE TITLE
Gunsplit Gamemode

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#878]
te amo :v ♥  porque tu a mi no? :c xD

es lo mas parecido que pude hacer ya me canse de mover ese dope :v
http://www83.zippyshare.com/v/xkvqPNxY/file.html

**Comment by Exobyte918** [comment]
DUPLICATE?

**Comment by fayizan** [comment]
wat is gunsplit ? :|

**Comment by Exobyte918** [comment]
@fayizan check gaver.io ;-;

**Comment by fayizan** [comment]
ohh thanks @Exobyte918 

I want self feed config someone help me ;-;

**Comment by plazo123** [comment]
@fayizan i have it

**Comment by MastaCoder** [comment]
English please.
