### ISSUE TITLE
Minions Does Not Show in LeaderBoard [Protocol v13] ! 

### ISSUE THREAD

**Issue by kaliduude** [Megabyte918/MultiOgar-Edited#879]
Hello MegaByte918 I'm Kali , and i have got an issue with MultiOgar-Edited version 1.6.1 that no one talked about yet, the Issue basically is with the leaderboard on protocol v13 , when i join a game and give myself some minions , i cannot see the minions on the leaderboard , i'm only able to see bot players & players 
Can you please fix this issue as soon as possible?  and Thanks

...

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/586
> no one has talked about yet.

**Comment by Exobyte918** [comment]
@AlexHGaming it froze my cell dafuq lmfao
