### ISSUE TITLE
BETTER IMPROVED TO BOTS

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#88]
That the bots can be seen on a map

**Comment by Jhair2015** [comment]
@RelTakeover  I do not think this is a very useful feature, well he who decides to do that would be @Megabyte918

**Comment by Megabyte918** [comment]
@RelTakeover What do you mean? If your using a minimap that works for players, you should be able to see minions on the map too.

**Comment by Jhair2015** [comment]
For that is the HSLO, OGARio, etc; That happened to you @Megabyte918  XD, you could become a client perzonalidado! : D

**Comment by RelTakeover** [comment]
i want that i can only see minions position and myself position , no others players

**Comment by Megabyte918** [comment]
@RelTakeover This is a client-sided issue and therefore cannot be resolved with edits to the server. Try talking to the owner(s) of the client you are using.
