### ISSUE TITLE
Help? pls [Question] [Need Answer]

### ISSUE THREAD

**Issue by Exobyte918** [Megabyte918/MultiOgar-Edited#880]
I know this is duplicate but no one answer :(
i close this if i got the right answer :3

1. How can make the server gives `10 minions` to the `AI Bots` when i do `addbot 25`
Means the `The 25 AI Bots will have 10 bots`
2. How to make umm delay bots splitting feeding , etc?

**Comment by Exobyte918** [comment]
@MastaCoder @Megabyte918 @AlexHGaming

**Comment by XtremePlayzCODE** [comment]
1. Apparently it won't add minions to AI bots. You can change it to add minions to AI bots by not checking if the player is an AI. Then, configure `serverBots` to `10`. Or, if you don't want players to have minions, you can check if the player is a real player, and then not add bots.

**Comment by Exobyte918** [comment]
@XtremePlayzCODE Its possible lol , AI  bots to have minions :3
