### ISSUE TITLE
Make Bots better and what happened to ogarul?

### ISSUE THREAD

**Issue by VSabertail** [Megabyte918/MultiOgar-Edited#883]
Why does everyone say this is the best now what happened to ogar unlimited why doesnt it work anymore idk what happened but im freaking out the bots are stupid they try to team with you but you can basically kill any bot they never kill you they are stupid asf

**Comment by Exobyte918** [comment]
OgarUL IS DEAD

**Comment by MastaCoder** [comment]
... Don't make these useless issues.

**Comment by plazo123** [comment]
@MastaCoder he is a master lsiten to mata coder he aint a masta for nothing XD @VSabertail
