### ISSUE TITLE
Pushsplit on multi-ogar edited ?

### ISSUE THREAD

**Issue by EarthAgar** [Megabyte918/MultiOgar-Edited#884]
please dont close i have found many comments on other issues about this and i am very curious as well how do we make  pushsplit like on gota.io on multi-ogar edited ? if you dont know what it is its basicly this here : https://youtu.be/PB0s5wrXSRs its where you are on somone and next to virus and split once and it some how overlap them and boom pushsplit how tho ? :(

**Comment by EarthAgar** [comment]
Plz help support this issue by submiting your oppinion as well thanks i want this answered

**Comment by freaky767** [comment]
technically i would call this a duplicate, but i actually dont know how to make pushsplit work

**Comment by AlexHGaming** [comment]
Duplicate of #465 (which is my issue)
there are more duplicates, but please search for other issues for your answer.

**Comment by EarthAgar** [comment]
sorry i have been searching for a while
