### ISSUE TITLE
Doesn't enter a game

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#885]
Not join game... (last version MOgar-edited)
![44](https://cloud.githubusercontent.com/assets/24901742/26557944/b8d3bf38-44ad-11e7-8045-ac8786a74cfd.PNG)

**Comment by AlexHGaming** [comment]
client sided.
make sure ports are linked and server is open
make sure you are not signed into facebook/google

**Comment by DeadLord1337** [comment]
thx (facepalm) i know...

**Comment by koda** [comment]
How do i get the yellow rings like the one in agar.io party
