### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#889]
If you set the max amount of cells to Infinity in the gameserver.js and .ini, when you hit a virus, it crashes.
In normal MultiOgar this doesn't happen.
Any fix?

**Comment by MastaCoder** [comment]
> If you set the max amount of cells to Infinity

Well there's your problem.

**Comment by AlexHGaming** [comment]
@MastaCoder 

> In normal MultiOgar this doesn't happen.

xD

**Comment by freaky767** [comment]
that is a problem though...

**Comment by Megabyte918** [comment]
@freaky767 When you hit a virus it splits you into into the amount of cells defined from the `playerMaxCells` config. If you set the value of the config to Infinity the server will crash because your cell cannot split into "Infinity" pieces.
