### ISSUE TITLE
Server doesn't start please help!

### ISSUE THREAD

**Issue by RobertValentin** [Megabyte918/MultiOgar-Edited#890]
![2017-05-31_194452](https://cloud.githubusercontent.com/assets/29102940/26643781/294c195c-463b-11e7-97b1-af7ac8a4f362.png)
I tried everything.... This is showing everytime. Hope you can answer and tell me what I can do.. Have a nice day. :)
And about the port my skype isn't running (if i change the port it says to make sure i'm running ogar in root privileges)

**Comment by plazo123** [comment]
you have somthing runing with the port 443 and 80 change it o anther and try to retsrat tour pc and try that usaly works for me

**Comment by RobertValentin** [comment]
What is the websocket error about?

**Comment by RobertValentin** [comment]
Solved thanks deleting now!!
