### ISSUE TITLE
please give me a hand! ( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#891]
https://i.imgur.com/eHHYwuN.png  :( 
 
I'm so stupid for these things :´v

**Comment by AlexHGaming** [comment]
why the lenny face 🤦

**Comment by FantasyIsBae** [comment]
>OgarUl is deprecated.
>Wrong repo.
>But
>U got the lenny face ❤️ 
>Love u who ever made this shit issue 😃

**Comment by Wair1o17** [comment]
@imnotNxhz1 This is older version :p http://uskip.me/bnAJAA◄

**Comment by imnotNxhz1** [comment]
@Wair1o17  me tomaste el pelo :( xD

**Comment by Wair1o17** [comment]
mmm no lo se, tal vez seas calvo :v

**Comment by imnotNxhz1** [comment]
me estas llamando wismichu? >:v

**Comment by MastaCoder** [comment]
.

**Comment by imnotNxhz1** [comment]
@MastaCoder  :100:
