### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by Exobyte918** [Megabyte918/MultiOgar-Edited#892]
I know this is duplicate but no one answer :(
i close this if i got the right answer :3

1. How can make the server gives `10 minions` to the `AI Bots` when i do `addbot 25`
Means the `The 25 AI Bots will have 10 bots`
2. How to make umm delay bots splitting feeding , etc?

@AlexHGaming
Also when i try to update the leaderboard so the minions can be seen in the leaderboard
my cell freeze ;-;

**Comment by AlexHGaming** [comment]
@Exobyte918 

> Also when i try to update the leaderboard so the minions can be seen in the leaderboard
my cell freeze ;-;

This maybe to adding old code not compatible / linked to the server.

**Comment by Exobyte918** [comment]
@AlexHGaming Answer my 1. 2. Question pls ;-;

**Comment by Agarian** [comment]
@Exobyte918 There is a config in ``gameserver.ini`` called `serverMinions`. This affects how many minions are given to a player by default. Though, this does not affect when bots are added, I believe.

**Comment by ExobyteZOfficial** [comment]
@Agarian by a code it iwll be added ;)

**Comment by ExobyteZOfficial** [comment]
@Megabyte918
