### ISSUE TITLE
Issue With Playing?

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#893]
I am having an issue with playing Multi Ogar on Agar.io Client when i hit play this screen will appear idk how to fix this can someone help?
![ads](https://cloud.githubusercontent.com/assets/17459204/26671593/7a7711b2-46cf-11e7-8f92-b431d655291f.png)

**Comment by AlexHGaming** [comment]
1. Make sure you are signed out of facebook / google.
2. That's it.

**Comment by Exobyte918** [comment]
@Gigabyte918 port is 28 lol

**Comment by Gigabyte918** [comment]
Yes i set the prot to 28
