### ISSUE TITLE
anyone can help me ?

### ISSUE THREAD

**Issue by matrixreal** [Megabyte918/MultiOgar-Edited#895]
Hi,
can anyone share with me a clean client compatible with multiogaredited ?
i cant find any on the net
thank you

**Comment by Gigabyte918** [comment]
Use Astr.io

**Comment by matrixreal** [comment]
@Gigabyte918 
thank for reply it look very great and polished
are you the owner ? where can i get it ?

**Comment by AlexHGaming** [comment]
Client sided, out of scope with project.
