### ISSUE TITLE
Cannot connect to (local) server on Chrome, Win10

### ISSUE THREAD

**Issue by DeemoHarlos** [Megabyte918/MultiOgar-Edited#898]
http://agar.io/?ip=127.0.0.1:443

I'm opening a local server on my computer. When I try to play it (with above url) on Chrome, it kept showing "Connecting". And there's no error message in console.
![image](https://cloud.githubusercontent.com/assets/20572126/26746879/f21d912c-4824-11e7-96f3-3e38da8edc7b.png) ![image](https://cloud.githubusercontent.com/assets/20572126/26746895/0be9f686-4825-11e7-9bd8-29716c7eeb0e.png)

So I had to play it on Edge, which worked just fine.
![image](https://cloud.githubusercontent.com/assets/20572126/26746929/37d06de8-4825-11e7-8d94-ecc340fc59c4.png) ![image](https://cloud.githubusercontent.com/assets/20572126/26746987/733753ec-4825-11e7-84d5-eca432fdf84c.png)

Anyone  have any clues?

**Comment by AlexHGaming** [comment]
On chrome, it works completely fine. I had to use localhost today because of the shit internet i have at my dads. Verify that nothing is blocking the socket connections, or try using incognito mode.

**Comment by ItzLevvie** [comment]
Make sure you're not logged into Google+ or Facebook

**Comment by MastaCoder** [comment]
Duplicate.
