### ISSUE TITLE
How to connect multiogar to agarplus webclient like gaver.io?

### ISSUE THREAD

**Issue by W4rky** [Megabyte918/MultiOgar-Edited#899]
**I NEED CONNECT MULTIOGAR TO AGARPLUS WEBCLIENT, I HAVE FIXED AGARPLUS**
------------

**Comment by fayizan** [comment]
`http://nbk.io/nbk2/?ip=`

**Comment by W4rky** [comment]
No, I need to connect the multiogar with agarplus to send the multiogar messages , commands ... in the agarplus client

**Comment by ogarcpl** [comment]
^ yes how pls some (:

**Comment by FantasyIsBae** [comment]
wtf are you on about @W4rky 
Also this is client sided.
Mookan close dis @MastaCoder

**Comment by W4rky** [comment]
i have agarplus web client fixed same gaver.io, war.io, athex.io ... but dont have desings

**Comment by AlexHGaming** [comment]
Client sided.
@MastaCoder @Megabyte918 close.

**Comment by Wair1o17** [comment]
lol

**Comment by ExobyteZOfficial** [comment]
![image](https://cloud.githubusercontent.com/assets/29154384/26758027/6d8771d6-4904-11e7-8cc6-b2ddc923b960.png)
do u mean like this? ez
