### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#90]
the gamemode lms bug on client vanilla agar.io bug leaderboard...

after of a time the leaderboard dissapears

**Comment by Tyler3D** [comment]
That's strange. Cause LMS doesn't change the leaderboard. So, that means this could happen on the other gamemodes.
@RelTakeover Have you noticed the same bug on any other gamemodes?

**Comment by RelTakeover** [comment]
no , only on lms

**Comment by Megabyte918** [comment]
@RelTakeover I could not reproduce this bug. Can you describe the steps you took to make it happen?
