### ISSUE TITLE
is there a way ?

### ISSUE THREAD

**Issue by ogarcpl** [Megabyte918/MultiOgar-Edited#901]
is there a way to send chat commands through ogar  client by szymy which don't support server side chat

**Comment by AlexHGaming** [comment]
Client sided.
@MastaCoder @Megabyte918 close.

**Comment by Wair1o17** [comment]
I think if it is possible to add ogario.ovh, but I would have to review it lol

**Comment by ExobyteZOfficial** [comment]
u need master to the server because ogar need master ;3
