### ISSUE TITLE
How do you deal with concurrency?

### ISSUE THREAD

**Issue by LemonDoo** [Megabyte918/MultiOgar-Edited#902]
I'm trying to implement my own game server that is similar to this ogar client, but I seem to be running into concurrency issues as some clients cannot print onto the canvas while others can.
I implemented a ticking system that ticks every few milliseconds, which updates all the clients in a for loop from a singlet Server service.

Any tips on how to improve this? I'm reading on the source code from this project and it seems to do the same thing?

**Comment by Wair1o17** [comment]
i think client sided

**Comment by AlexHGaming** [comment]
client sided.

**Comment by Megabyte918** [comment]
This is an issue with your client.
