### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by ExobyteZOfficial** [Megabyte918/MultiOgar-Edited#903]
**I suggest to add here to become like agario**
1. Friend System Thing
2. Yellow Circle (by port who've joined)
3. Delay Minions (For more Realisitic)

**Comment by AlexHGaming** [comment]
1. Client sided
2. Client sided
3. Duplicate

**Comment by ExobyteZOfficial** [comment]
@AlexHGaming 
1. Can Be Added
2. CAn Be ADded
3. SetTimeout

**Comment by AlexHGaming** [comment]
They can't be added. The client is the one that recognises the yellow circle. The client draws out the yellow outline on cells.

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/703
refer to megabyte's comment about yellow circles being client sided.

**Comment by Wair1o17** [comment]
True, that is not possible, because miniclip sends some packages to make it work

**Comment by gyeyoqu** [comment]
@ExobyteZOfficial stop making issues, learn js simply
