### ISSUE TITLE
Agario private servers not working just saying connecting

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#904]
![xzlol](https://cloud.githubusercontent.com/assets/23435125/26762812/50046ea2-4940-11e7-8e27-7e08f021e235.JPG)

any fixes?

**Comment by koda** [comment]
Anyone has a fix for yellow rings?

**Comment by AlexHGaming** [comment]
Yellow rings is a duplicate of an issue on this repo
and make sure you are logged out of facebook/google before accessing the server, in which this is a duplicate aswell.

**Comment by koda** [comment]
So is there a way to fix it? the yellow rings

**Comment by DeadLord1337** [comment]
My issue ))[#885](https://github.com/Megabyte918/MultiOgar-Edited/issues/885)
