### ISSUE TITLE
Yellow rings on multiogar

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#905]
Is it possible to get yellow rings on multiogar like the ones from agario party? thanks :)

**Comment by AlexHGaming** [comment]
it
is
fucking
client
sided
and 
its
a
duplicate
so
stop
asking
**PLEASE**

**Comment by koda** [comment]
duplicate from where?

**Comment by koda** [comment]
Also how did gaver.io party mode do it?

**Comment by AlexHGaming** [comment]
I said `client sided`

> how did gaver.io party mode do it?

What, so gaver.io isn't a client?

**Comment by ZfsrGhS953** [comment]
@AlexHGaming It's not client sided. The client can't detect friends on its own, it reads a cell flag from the server and draws a ring if the flag is set.

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/703
refer to megabyte's comment about it being client sided.

**Comment by Wair1o17** [comment]
That not is like agar.io on gaver.io

**Comment by Megabyte918** [comment]
This may not be client sided, but it is still a duplicate.

**Comment by ExobyteZOfficial** [comment]
This can be added tho ;) = Yellow Packets are 160/161

**Comment by koda** [comment]
hey could you help me with it?

**Comment by koda** [comment]
What is your skype?
