### ISSUE TITLE
Yellow Packets

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#906]
Hi Could anyone help me with yellow packets 160/161 please thanks
my skype is: kodayt1 
if you want to contact me

**Comment by Wair1o17** [comment]
wtf

**Comment by koda** [comment]
?

**Comment by AlexHGaming** [comment]
Talking about yellow cell renders, duplicate.
@MastaCoder @Megabyte918 close pls

**Comment by koda** [comment]
What?? I just need help with something

**Comment by AlexHGaming** [comment]
Well ask it on the issue that was the first to ask it.

**Comment by ExobyteZOfficial** [comment]
@koda u have to stop bro .-.

**Comment by koda** [comment]
@ExobyteZOfficial could you help me with it? Please

**Comment by ExobyteZOfficial** [comment]
@koda lol i have the files ;3

**Comment by ExobyteZOfficial** [comment]
Added :)

**Comment by koda** [comment]
@ExobyteZOfficial Could you send me the files ? Pleaseee

**Comment by koda** [comment]
@ExobyteZOfficial What is your skype? i wil add you

**Comment by ExobyteZOfficial** [comment]
@koda stop ._. i saw ur messages its bad soz

**Comment by ExobyteZOfficial** [comment]
CLOSE DIS ISSUE PLESSSSSSSSSSSSSSSS @Megabyte918 @MastaCoder

**Comment by koda** [comment]
@ExobyteZOfficial Bro shut up omg

**Comment by AlexHGaming** [comment]
CLOSE DIS ISSUE PLESSSSSSSSSSSSSSSS @Megabyte918
<https://github.com/megabyte918> @MastaCoder <https://github.com/mastacoder>

**Comment by MastaCoder** [comment]
Why the packets aren't a-

Right. To get this to work we'd need to get Facebook to work, which I don't think would work. Marking as client.
