### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#907]
i checked up o n this and i found no aswser to my question where is the code wich connects the client to the server i just need the code that conects the client now is this client sided im not sure so please dont 

......................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by Wair1o17** [comment]
that is client sided, that put on client no on Server

**Comment by AlexHGaming** [comment]
Duplicate and client sided.
Please stop asking these type of issues..
