### ISSUE TITLE
Make an Skin Changer or Skin Picker That allows to get skin :)

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#91]
MC.showLevelUp(100,1,100) for kraken
This is only for veteran!! :)
hope it helps
Need a help tag :)

**Comment by Jhair2015** [comment]
@NameYT lol That's what I told @Megabyte918 MegaByte first xd
lol

**Comment by NameYT** [comment]
@Jhair2015 So i can help players :3

**Comment by NameYT** [comment]
@Jhair2015 u ahve skype? add me Samby

**Comment by Megabyte918** [comment]
@NameYT I don't know how to get that working for premium skins, but there is a special bit of code you can paste into the web console to get custom skins. 
`core.registerSkin('yourname', null, 'linkofskin', 1, null)`

So for example if I wanted the Jade Dragon skin and the input box has my name "mega" in it, I would do this:
<pre>
core.registerSkin('mega', null, 'http://agario-skins.org/images/skins/custom/jade-dragon.png?v0.10.8', 1, null)
</pre>

Anyone who spawns with the name "mega" will have the Jade Dragon skin. And you can find most skins by just doing a simple search on google images.

Also, this issue has nothing to do with the server, so I will close this.

**Comment by NameYT** [comment]
@Megabyte918 That's what i meant but i want to have the same stroke :_3

**Comment by NameYT** [comment]
@Megabyte918 When i enter it i cant see my name how

**Comment by Megabyte918** [comment]
What do you mean the same stroke?

**Comment by NameYT** [comment]
![image](https://cloud.githubusercontent.com/assets/20871314/20549961/d603be1c-b16b-11e6-890e-a7c3f46d7cd4.png)
Look at the image! and the skin

**Comment by NameYT** [comment]
Is that supposed to be like the dragon skin like that?

**Comment by NameYT** [comment]
Also we cant see the nametags

**Comment by Megabyte918** [comment]
@NameYT I cannot do anything about that, It is a client-sided issue

**Comment by NameYT** [comment]
@Megabyte918 So we need to do it with color? command

**Comment by Megabyte918** [comment]
You can if you'd like to

**Comment by NameYT** [comment]
@Megabyte918 How? The Same Color as the Dragon Skin on original agar

**Comment by Megabyte918** [comment]
I don't know what the stroke color is, that you will have to find out for yourself

**Comment by NameYT** [comment]
example wait image :3

**Comment by NameYT** [comment]
THE BORDER OF THE SKIN :)

**Comment by NameYT** [comment]
also u need to update the randomskin there are a new of them :3

**Comment by NameYT** [comment]
![image](https://cloud.githubusercontent.com/assets/20871314/20550027/950364a2-b16c-11e6-9147-ecc5a5e6b96c.png)
Look at the mammoth skin :3 Thats what i meant @Megabyte918 The Border of every skin :3

**Comment by Megabyte918** [comment]
@NameYT Yes I know what you are talking about, but I cannot help you with that since it is a client-related issue.

**Comment by NameYT** [comment]
@Megabyte918 Hmm okay but there is an extension that does this thing but i cant find it

**Comment by NameYT** [comment]
@Megabyte918 What is the new update btw? is this like vanilla?

**Comment by NameYT** [comment]
@Megabyte918 
![image](https://cloud.githubusercontent.com/assets/20871314/20550183/20a543c6-b16e-11e6-8935-6a298fecba36.png)Same color as the skin same border that's what im talking bout

**Comment by Jhair2015** [comment]
@NameYT  My skype lol Ĵ✖҉✖҉✖҉ℜ 鿆 -  

profile photo: "J" BIG xd

**Comment by AlexandriteErikParacelsus** [comment]
@Jhair2015 I added you

**Comment by Jhair2015** [comment]
@AlexandriteErikParacelsus  Ok!
