### ISSUE TITLE
lol i did it yellow packets

### ISSUE THREAD

**Issue by ExobyteZOfficial** [Megabyte918/MultiOgar-Edited#910]
![image](https://user-images.githubusercontent.com/29154384/26861288-66b12ef6-4b75-11e7-8a8b-9d2e81f41c1b.png)
well ye fuk my layf

**Comment by koda** [comment]
Omg help me with it please man :(

**Comment by Niall7459** [comment]
@ExobyteZOfficial What are yellow packets?

**Comment by koda** [comment]
@Niall7459 Yellow rings around your cell and I need the files so badly

**Comment by koda** [comment]
@ExobyteZOfficial Could you send me your files please man?
