### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ExobyteZOfficial** [Megabyte918/MultiOgar-Edited#911]
How can i make minions collect pellets in 10 ticks\/

**Comment by ZfsrGhS953** [comment]
@ExobyteZOfficial 
```javascript
if (this.gameServer.tickCounter % 10 == 0) {
    // Add your code here
}
```

**Comment by ExobyteZOfficial** [comment]
@ZfsrGhS953 Thanks <3

**Comment by ExobyteZOfficial** [comment]
@ZfsrGhS953 Also how can i make the minions appear in my leaderboard with the new code ;3

**Comment by ExobyteZOfficial** [comment]
@ZfsrGhS953 Also where should i put the code ?

**Comment by plazo123** [comment]
@ExobyteZOfficial in game server.js

**Comment by AlexHGaming** [comment]
> @ZfsrGhS953 Thanks <3

close then pls

**Comment by ExobyteZOfficial** [comment]
@plazo123 What line :3

**Comment by ExobyteZOfficial** [comment]
@ZfsrGhS953 where is the line xD ._.
