### ISSUE TITLE
Change the gamemode

### ISSUE THREAD

**Issue by Flavorounet** [Megabyte918/MultiOgar-Edited#913]
**BEFORE POSTING NEW ISSUE READ THIS**: You will find below few points, that you must follow or provide required info to. If you are not going to provide what we need in format we require your issue will be closed instantly without explanation. Spam is treated with fire.

Helpful checklist:

- [x] You have checked [prev issues](https://github.com/Megabyte918/MultiOgar-Edited/issues?q=is%3Aissue+is%3Aclosed) first and you didn't found answer for your problem (if there is something similar put reference links)
- [x] You are using and you have tested the latest version of MultiOgar.
- [x] Issue is in English.
- [x] Issue is not off-topic, and is related to the project.
- [x] You have provided logs if there is crashing happening.
- [x] You have provided below good description of the error, making sure it is something we can reproduce.

[Tutorial of how to format text on github](https://guides.github.com/features/mastering-markdown/), to make your issue not only readable but clean and neat

------------

Hi,

I've a question which you probably already answer, but how can i change the gamemode ? I've tried to use the command "gamemode x", but nothing because the command doesn't exists in the commands list. And i've already try to edit gameserver.ini file, but nothing.. Can you help me to change the gamemode please ? Than, how can i run others servers in the same window ? For example, one server connected at 443 port in FFA mode, and another server connected at 444 port in Teams mode ? Thank's !

Flavien

**Comment by koda** [comment]
I need help with yellow rings around my cell do you know how to fix that?

**Comment by AlexHGaming** [comment]
@koda, please stop asking other people if they know the code, just simply learn yourself, instead of being annoying and constantly bragging everyone else.
@Flavorounet, changing the gamemode is an OgarUL feature.

> how can i run others servers in the same window ?

This would be client sided. If you are talking about multiple option values to connect to the server, client sided. Just make a new tab with putting the ip with port that which server you would want to go to.

**Comment by FantasyIsBae** [comment]
>I need help with yellow rings around my cell do you know how to fix that?

Listen to Alex

**Comment by ZfsrGhS953** [comment]
@AlexHGaming It's not, it exists [in Ogar as well](https://github.com/OgarProject/Ogar/blob/master/src/modules/CommandList.js#L332)

**Comment by AlexHGaming** [comment]
listen to @FantasyIsBae

**Comment by Flavorounet** [comment]
@AlexHGaming Oh, thank's ! And do you have any tutorial to make it possible for the gamemode ? For the multiple server, i think about a "screen", i don't know if nodejs know that command, but i will try ! And to make a new tab, do you have some documentation too ? Thank's !

**Comment by Luka967** [comment]
`screen` is a Linux package, not a node.js module.

**Comment by MastaCoder** [comment]
KODA. STOP ASKING ABOUT THE YELLOW RING,

**Comment by koda** [comment]
@MastaCoder sorry im just really desperate ;(

**Comment by ExobyteZOfficial** [comment]
Do change serverGamemode = 0 1 2 3 4 5 idk lol

**Comment by plazo123** [comment]
its easy go to gameserver.ini and scroll i lttle down or search game modesyou will find @Flavorounet 
you will find game mode 1 2 3 4 5 they are from ffa exatra
