### ISSUE TITLE
How to show PlayerID?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#914]
In the chat, how to draw the ID the side of the name

**Comment by AlexHGaming** [comment]
> In the chat, how to draw the ID the side of the name

What the hell do you mean

**Comment by ExobyteZOfficial** [comment]
He mean PlayerID when he do playerlist @AlexHGaming

**Comment by AlexHGaming** [comment]
So you're saying for example:
If I put in chat /id
it would show to you basically what the playerlist in the console does.

**Comment by suprix** [comment]
@gyeyoqu download lastest version and in chat type **/id**

**Comment by gyeyoqu** [comment]
I think they can not read "NEXT" of the name

**Comment by DeadLord1337** [comment]
pl - playerlist

**Comment by plazo123** [comment]
wow wthat he meens is in the chat when he says hi next yto the name ayou can see the id next to name with out /id or id otr pl or player list ...

**Comment by AlexHGaming** [comment]
Then this would be a duplicate.

**Comment by AlexHGaming** [comment]
@gyeyoqu 

> I think they can not read "NEXT" of the name

*cough* 

> In the chat

k den

**Comment by gyeyoqu** [comment]
@AlexHGaming nope, find PLAYERID in questions , not duplicate

**Comment by FantasyIsBae** [comment]
@gyeyoqu Do you mean the Id next to the player when he/she sends a message?

**Comment by Wair1o17** [comment]
@FantasyIsBae That in the nick of the player of the cell appears ia ID

**Comment by gyeyoqu** [comment]
yes @FantasyIsBae

**Comment by AlexHGaming** [comment]
@gyeyoqu Find the function of chat messages, find where username + chatmessage or whatever, then before the username, include pID.

**Comment by AlexHGaming** [comment]
and haha @gyeyoqu I saw you commenting on an issue
`learn js simply`
🤦‍♂️

**Comment by gyeyoqu** [comment]
@AlexHGaming yes i learn js every day, actually im working with ES6

**Comment by pabloalber84** [comment]
You think about add in chat [ID][Name]: Text?

**Comment by ProYTBeatz** [comment]
@pabloalber84 Yes, I think thats what he is talking about, and sorta for me too. I am looking everywhere for that for my game VarZar.cf!

**Comment by MastaCoder** [comment]
Hey there!

This is the issues section of MultiOgar-Edited. Only issues and feature-requests are to be put here. We do not support questions about programming a custom function in. The code is pretty documented with comments, and is provided as-is. If you require support for this project please contact someone with experience that is willing to help.

Enjoy!
