### ISSUE TITLE
teleport

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#915]
how chahnge the specific x.y cordinates to mouse cordinates

**Comment by AlexHGaming** [comment]
What type of coordinates are you trying to change?

**Comment by ogarcpl** [comment]
tp: function(args) {
        var id =this.playerTracker.pID;
        if (isNaN(id)) {
            this.writeLine("Please specify a valid player ID!");
            return;
        }

        // Make sure the input values are numbers
        var pos = {
            x: this.playerTracker.mouse.x,
            y: this.playerTracker.mouse.y
        };

        // Spawn
        for (var i in this.gameServer.clients) {
            if (this.gameServer.clients[i].playerTracker.pID == id) {
                var client = this.gameServer.clients[i].playerTracker;
                for (var j in client.cells) {
                    client.cells[j].position.x = pos.x;
                    client.cells[j].position.y = pos.y;
                    this.gameServer.updateNodeQuad(client.cells[j]);
                }
              this.writeLine("You have been Teleported to ur cursor place ");
                break;
            }
        }
    },
 put it in playercommand.js and Use /tp in chat to make it work

**Comment by imnotNxhz1** [comment]
@ogarcpl  you´re the best  thank you so much :1st_place_medal:
