### ISSUE TITLE
Multiogar rings

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#916]
How do i get those rings from Gaver.io Party FFA or is it client sided??

**Comment by AlexHGaming** [comment]
No offense, but this is really pissing me off on the amount of times you have asked this. This has been duplicated so many times by you, yet you still ignore the 'duplicate' labels and still keep spamming us with how to get these yellow rings. If you were to get hold of exobyte's discord, ask him there and stop turning this repo into a yellow ring syndrome. I'm not trying to be mean to you or anything, but it is really pestering.

**Comment by AlexHGaming** [comment]
![image](https://user-images.githubusercontent.com/23644244/26981956-b3b0613a-4d2e-11e7-96e0-d14b0afd333d.png)
2 issues here. One here was a duplicate, one was client sided. The client sided one is a duplicate too. So you have 2 duplicates of your own issues. Making a 3rd won't solve this. Just get hold of someone you know who could make these yellow rings and hallelujah, you're done.

**Comment by koda** [comment]
Could you give me his discord

**Comment by koda** [comment]
@AlexHGaming

**Comment by Wair1o17** [comment]
@koda Just is client sided -___-, that don't work to the server MultiOgar .-.

**Comment by AlexHGaming** [comment]
**EXPECT FANTASYISBAE COMMENT**

**Comment by FantasyIsBae** [comment]
@koda 
>How do i get those rings from Gaver.io Party FFA or is it client sided??


Please stop making issues about this , It is getting repetitive .
As you may see by the responses to your previous issues no one is willing to help with these rings.
The closest you may get to making rings is setting ```isAgitated``` to ```true``` in cell.js , this will effect the overall speed of the server.
Also what Alex was referring to is you finding someone who will be wiling to make these "rings" for you , not that he knows anyone that would waste their time to do such a simple thing.


Overall please stop making useless issues that have been answered or issues that are just pointless.
Either learn and do it yourself or get someone else to do it for you , but don't make multiple issues documenting the same thing over and over again.

**Comment by AlexHGaming** [comment]
@FantasyIsBae, Someone finally said it all out lmao

**Comment by ZfsrGhS953** [comment]
@FantasyIsBae We'll see the behavior of your automatic system when he accidentally types "rings" with a turkish ı.

**Comment by ZfsrGhS953** [comment]
And apparently you still think that it's client-sided. It can't be like that because the client has no idea about how the players on the screen joined the party.

**Comment by FantasyIsBae** [comment]
Yes , but the client has to display it.
Not really automatic system, rather me checking every now and again 😄 😃 @ZfsrGhS953

**Comment by MastaCoder** [comment]
The Agar.io client already supports drawing of the yellow ring. I don't understand what any of you are saying. This isn't client sided..

**Comment by ExobyteZOfficial** [comment]
ANYOEN GIVE ME A FOKIN KNIFE I WILL KILL DAT GUY ._.

**Comment by ExobyteZOfficial** [comment]
@koda kys
