### ISSUE TITLE
Eh it was better before...

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#918]
Was previously Push split  like in gota.io. If memory serves me it was on version 1.3.7-1.4.4. May try to get it back? If necessary I can give the file with these versions

**Comment by ExobyteZOfficial** [comment]
NO ITS WAS NOT BEFORE ._.

**Comment by AlexHGaming** [comment]
#465 refer to my issue here.

**Comment by AlexHGaming** [comment]
Or change the `unshift` in playercell.js to `push`

**Comment by FantasyIsBae** [comment]
Duplicate of #465 
If anything do what Alex said above.

**Comment by AlexHGaming** [comment]
Read @FantasyIsBae's comment

**Comment by DeadLord1337** [comment]
Or change the unshift in playercell.js to push - it does nothing does not work in gota io, I did push it a thousand times, not what is not changed...

**Comment by DeadLord1337** [comment]
@AlexHGaming

**Comment by AlexHGaming** [comment]
@DeadLord1337 Well it is still a duplicate of my gravitational splits issue, which relates to pushes and easier pops if needed.
