### ISSUE TITLE
How to run the server 25mb +?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#92]
how?

**Comment by NameYT** [comment]
This also reduce lag ?

**Comment by Megabyte918** [comment]
@NameYT Depends on what you plan on using the extra memory for.
<pre>node --max-old-space-size=val index.js</pre>
So if I wanted to increase the memory my server ran on to 6gb i would do:
<pre>node --max-old-space-size=6144 index.js (memory is in mb)</pre>
or you could do:
<pre>node --stack-size=val (memory is in kb)</pre>
