### ISSUE TITLE
How..

### ISSUE THREAD

**Issue by ExobyteZOfficial** [Megabyte918/MultiOgar-Edited#920]
How can i make my minion collect pellets per 10 ticks?
also where should i add da code ._.

**Comment by ZfsrGhS953** [comment]
From the issue template:
```
 You have checked prev issues first and you didn't found answer for your problem (if there is something similar put reference links)
```
In case you didn't notice, I posted an answer on your [previous issue](https://github.com/Megabyte918/MultiOgar-Edited/issues/911).

**Comment by ZfsrGhS953** [comment]
@ExobyteZOfficial

**Comment by ExobyteZOfficial** [comment]
@ZfsrGhS953 I Already know the code ._.
Where can i put it ?
I close dis imddeaitasdsaitl;lyyyy

**Comment by AlexHGaming** [comment]
duplicate.

**Comment by ExobyteZOfficial** [comment]
@AlexHGaming i know im just asking him ._.

**Comment by plazo123** [comment]
@ExobyteZOfficial put it in the end of gameserver.js

**Comment by ExobyteZOfficial** [comment]
@plazo123 tanks :P

**Comment by ExobyteZOfficial** [comment]
@plazo123 it gives error ..
