### ISSUE TITLE
Best score by?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#921]
Saving the mass in playerTracker with:
```

this.bestScore = 0;  // In constructor
this.bestAll = []; // In constructor
```

```
if (this._score > this.bestScore) {  // in UpdateTick function
    this.bestScore = this._score;
}
this.bestAll.push(this.bestScore);

```

_**but, how to know who do the best score of bestAll ?**_

_for use to_ 

> "The best score of the game is 80k by megabyte918"

**Comment by AlexHGaming** [comment]
This would be client sided.

**Comment by MastaCoder** [comment]
This is not client sided.

What do you mean best score? Highest score a cell got in the game and save it?

**Comment by gyeyoqu** [comment]
@Megabyte918  https://github.com/Megabyte918/MultiOgar-Edited/issues/795

**Comment by MastaCoder** [comment]
Duplicate.

**Comment by gyeyoqu** [comment]
It is not even a duplicate

**Comment by MastaCoder** [comment]
You're asking a followup question to the last issue, just post it on there.
