### ISSUE TITLE
New Info about World Update Packet + 160/161

### ISSUE THREAD

**Issue by NuclearC** [Megabyte918/MultiOgar-Edited#922]
For yellow outline around our cell we can try to send gamemode opcode 8 to client.

New Informations about World Update Packet:
(new flags_2)

#### Update Cell Record
Data Type | Value | Description
--- | --- | ---
uint32 | ... | Cell ID
int32 | ... | Cell X
int32 | ... | Cell Y
uint16 | ... | Cell Radius
uint8 | ... | Cell Flags
uint8 | ... | Cell Flags 2 (read if flags & 0x80)
uint8 | 0 | Cell Color (RED) (read if flags & 0x02)
uint8 | 0 | Cell Color (GREEN) (read if flags & 0x02)
uint8 | 0 | Cell Color (BLUE) (read if flags & 0x02)
null_utf8 | ... | Cell Skin (read if flags & 0x04)
null_utf8 | ... | Cell Name  (read if flags & 0x08)
null_utf8 | ... | Cell's Player Account  (read if flags_2 & 0x04)
##### Flags (for flags_2)
Mask | Description
--- | ---
0x01 | Food
0x02 | Is Friend (for yellow outline)
0x04 | Has Account Name

### Packet 160 (set arrow direction)
Data Type | Value | Description
--- | --- | ---
uint8 | 160 | Opcode
int16 | ... | Friend X
int16 | ... | Friend Y
null_str8 | ... | Friend Name (sent only once)

### Packet 161 (remove arrow)
Data Type | Value | Description
--- | --- | ---
uint8 | 161 | Opcode

**Comment by AlexHGaming** [comment]
PR this?

**Comment by NuclearC** [comment]
I didnt implement that xd

**Comment by NuclearC** [comment]
im just making issue so some pro Node coder can make it

**Comment by AlexHGaming** [comment]
ok.

**Comment by NuclearC** [comment]
Btw all these changes are for friend system. Its not very necessary

**Comment by AlexHGaming** [comment]
true.
@koda

**Comment by NuclearC** [comment]
For friend system we can easily get party ID from websocket's request query params (like party_id=ADF9H9) you can make party even when playing in private servers tho

**Comment by ExobyteZOfficial** [comment]
i fixed dis dm me in discord NuclearC :P

**Comment by ElPigianerJone** [comment]
but I and the others who don't know about nodejs don't know how to send gamemode opcode 8 to client 
Help us :+1:

**Comment by freaky767** [comment]
will this be an ability to play with skins??

**Comment by Tyler3D** [comment]
How should the party system work. I'm thinking of a extension for a similar party system to vanilla. But, that might be difficult to use. For now imma use all protocol 13 users

**Comment by NuclearC** [comment]
party system is ez to make on multiogar XD

**Comment by freaky767** [comment]
pzlzplzlplpzpl someone make that

**Comment by MastaCoder** [comment]
Well, we can't use Facebook lmao, should find a way. 🤔

**Comment by NuclearC** [comment]
why you need facebook???

**Comment by ExobyteZOfficial** [comment]
@NuclearC They cant login in the game without face b00k

**Comment by MastaCoder** [comment]
How else would we get the friends list? The party thing could work, but I think a lot of people here just wanted it for the friends list. Could be wrong.

**Comment by NuclearC** [comment]
im talking about friends in agar, i mean when players connect to same party in server

**Comment by chewydev** [comment]
Ok so, you could implement something like Gota.io's party system. I wrote a client sided party system for my game.

**Comment by Agarian** [comment]
Party system, eh? I'm thinking a command that links 2 or more players as a friend group? This can be noted in party mode obviously.

**Comment by Agarian** [comment]
A party system would be quite interesting, I mean, you can create party links while connected to a private server, after all.

**Comment by chewythepig** [comment]
You can use request URIs with websockets for this

**Comment by chewythepig** [comment]
instead of updating the protocol. Ex: ws://websocket.url/?party=PartyCode. I know agar.io does this in their recent updates
