### ISSUE TITLE
My Multiogar keeps crashing 

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#923]
![image](https://user-images.githubusercontent.com/23435125/27036431-b1b0b7c2-4f7c-11e7-81d1-d75f358bfebe.png)
Hi my multiogar keeps crashing when i open it any fixes?

**Comment by koda** [comment]
Nvm i fixed it

**Comment by AlexHGaming** [comment]
But this is multiogar-**EDITED**, not original.
