### ISSUE TITLE
Issues with console-plus

### ISSUE THREAD

**Issue by chewythepig** [Megabyte918/MultiOgar-Edited#925]
Before you read, i'm aware that this is somewhat of a duplicate,  but I haven't seen any issues pointing out this problem.

Currently, I started trying to use `console-plus.js`, as I've been using a new daemon which I can not run commands in. If I do try to run console-plus in node (`cd serverdir/; node console-plus.js`), it will echo `consoleServer is listening on port 1234` and quit instantaneously.

Terminal output: http://i.imgur.com/019ZxCS.png

I'm not sure if i'm doing something wrong, or it's simply a bug, since the web console hasn't been updated in forever. Can someone help me out?

**Comment by AlexHGaming** [comment]
try using `sudo node`
idk im shit at code

**Comment by pabloalber84** [comment]
`pidof node console-plus.js`
And kill the actual process :B

**Comment by chewydev** [comment]
@pabloalber84 And this is Linux, correct?

**Comment by pabloalber84** [comment]
Yes @chewydev

**Comment by chewydev** [comment]
Nothing here worked, but thank you guys for helping.

**Comment by plazo123** [comment]
@chewydev im having troub;e going to 127.0.0.1:1234 wehn i go its page wont sedn deta and its ruuningon port 1234

**Comment by plazo123** [comment]
@chewydev can you help me with after it  starts on port 1234 icantgo to 127.0.0.1:1234

**Comment by plazo123** [comment]
@chewydev same it quits so i done the page realy fast and i cameto login but then it closes

**Comment by plazo123** [comment]
@chewydev i figured it outr dont run winb  start.bat obnly node console plys it starts serverit self!!

**Comment by plazo123** [comment]
@chewydev orks for me now !!

**Comment by chewydev** [comment]
I'm not using windows for this, I haven't use start.bat

**Comment by plazo123** [comment]
@chewydev starst.sh ?

**Comment by MastaCoder** [comment]
That's weird, can you try on another server. Works fine on my end.

**Comment by chewydev** [comment]
@MastaCoder Tried on every server on every one of my machines. They're all on Centos 7 x64 with the latest stable release of NodeJS and NPM.

**Comment by pabloalber84** [comment]
You sure than open firewall ports correctly? all dependencies? correct node library installation?

**Comment by chewydev** [comment]
@pabloalber84 All of that is correct, yes.

**Comment by pabloalber84** [comment]
One thing @chewydev , you press "CTRL + C"?
You modify the console-plus.js?

**Comment by duwayy** [comment]
I got the same problem on Ubuntu, but when I opened an issue, the only thing I got was a "Use Windows" tip

**Comment by pabloalber84** [comment]
Which version of nodejs do you use?

**Comment by plazo123** [comment]
@duwayy make sure not to open star linux .sh just sudo and start the console plus

**Comment by chewydev** [comment]
I haven't modified `console-plus.js`, no.

**Comment by FantasyIsBae** [comment]
What version of node do u use on your servers? @chewydev

**Comment by chewythepig** [comment]
@FantasyIsBae Sorry for the late reply, I use **v6.11.1**.

**Comment by Fan7asy** [comment]
@chewythepig Updating it to the latest version should fix it.

**Comment by chewythepig** [comment]
Thanks dad
