### ISSUE TITLE
[OFF-TOPIC] The responses to some variables of alis.io (MultiOgar protocol 5)

### ISSUE THREAD

**Issue by pabloalber84** [Megabyte918/MultiOgar-Edited#926]
https://github.com/pabloalber84/Alis.io-Old-Client-Server-MultiOgar/
Some information :B 
I dont know how to put OFF-TOPIC or the place to put this information, but alis.io transformed to shit and without updates, enough that there is another copy of alis.io, NOT like the shit of gaver.io or nbk.io.
I used this version of MultiOgar-Edited :baby_chick:

**Comment by ExobyteZOfficial** [comment]
um wut da fok is dis ._.

**Comment by plazo123** [comment]
@pabloalber84 i cant see anything in old clitn ???

**Comment by chewydev** [comment]
It would be useful if the link didn't return a 404 error.

**Comment by imnotNxhz1** [comment]
can give me the link?

**Comment by pabloalber84** [comment]
@imnotNxhz1 NO.

**Comment by Wair1o17** [comment]
Lol that is in my download folder xd

**Comment by pabloalber84** [comment]
No problem, I dont have some important things, nothing special, are the old, I have the new, and the new variables.

**Comment by Wair1o17** [comment]
I'm not interested in that at all.

**Comment by pabloalber84** [comment]
True, I don't too, im only maked to test :B
