### ISSUE TITLE
Macros W dont work

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#928]
not working W macro in your script, which is located in the Scripts folder AgarMacros.js

**Comment by freaky767** [comment]
i have noticed that in the new update, but never said anything about it

**Comment by ExobyteZOfficial** [comment]
every script doesnt work ._.

**Comment by plazo123** [comment]
none in aagario i tryed many :(

**Comment by chewydev** [comment]
Its working fine, im using the latest version of the script and Multiogar-Edited.
http://popsplit.us

**Comment by DeadLord1337** [comment]
@chewydev hm thx nice agar client :/
