### ISSUE TITLE
Cell

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#929]
Cell.prototype.onEat = function (prey) {
    if (!this.gameServer.config.playerBotGrow) {
        if (this._size >= `250` && prey._size <= `41` && prey.cellType == 0)
            prey.radius = 0; // Can't grow from players under 17 mass
    }
    this.setSize(Math.sqrt(this.radius + prey.radius));
};
Cell.js

250 and 41 - What do these numbers, what they do?

**Comment by AlexHGaming** [comment]
@DeadLord1337 This is what triggers the 'can't grow mass from 17 mass or below cells' function

**Comment by DeadLord1337** [comment]
@AlexHGaming what? so why do numbers 250 and 41 so you can put for example 100 and 10 or 1 and 100
