### ISSUE TITLE
Bring Back TP COMMAND

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#93]
Pls

**Comment by Tyler3D** [comment]
@NameYT Have you actually used the TP Command
cause I've never seen anybody use it. So, Mega removed it

**Comment by NameYT** [comment]
@Tyler3D I always use it :) Tyler Do you know how to get a 100000% CHANCE POPSPLIT?

**Comment by NameYT** [comment]
@Tyler3D Also tyler i also cant wait for pellet mode :3

**Comment by Tyler3D** [comment]
@NameYT 
1. Nope
2. Not making it.

**Comment by Megabyte918** [comment]
@NameYT You can add the removed code from the TP command back yourself, I removed it because it seemed useless and nobody used it.
