### ISSUE TITLE
Make the bots smarter :)

### ISSUE THREAD

**Issue by ElPigianerJone** [Megabyte918/MultiOgar-Edited#930]
I think the server will become more interesting if the bots are smarter, the bots can double split well,.....

**Comment by ProYTBeatz** [comment]
Sounds like a good idea , but that would take a while to complete .

**Comment by AlexHGaming** [comment]
This is duplicated many times.
Making the bots smarter is like trying to work out what the meaning of life is.

**Comment by freaky767** [comment]
^^^^^ Mookan close pls

**Comment by chewydev** [comment]
@AlexHGaming Don't forget it's a resource heavy addition!

**Comment by pabloalber84** [comment]
The bot's can't be better than one human...
If you want to do it, modify you the BotPlayer.js
