### ISSUE TITLE
how change this line? 7u7 

### ISSUE THREAD

**Issue by imnotNxhz1** [Megabyte918/MultiOgar-Edited#931]
this xD http://i.imgur.com/96YySgy.png  http://i.imgur.com/96YySgy.png  http://i.imgur.com/96YySgy.png

**Comment by Wair1o17** [comment]
that is client sided

**Comment by imnotNxhz1** [comment]
solo quiero agregarle el id :´v  a lado de la massa

**Comment by mafiakb** [comment]
yo te ayudo discord https://discord.gg/0tIkwmjWJW9SQBkw

**Comment by Wair1o17** [comment]
Yo creí que te referías a hacer con "k" la masa lol

**Comment by chewydev** [comment]
I think you screwed up sending ID packets over, you might want to fix that.

**Comment by chewydev** [comment]
This is also client sided, you can use regex or edit the code itself to remove this.

**Comment by AlexHGaming** [comment]
@imnotNxhz1 This is client sided, out of scope of project.
But if you host a Cigar client you can change it in main_out.js
So making an issue here is off topic I'm afraid.
