### ISSUE TITLE
Leaderboard Scores

### ISSUE THREAD

**Issue by chewydev** [Megabyte918/MultiOgar-Edited#933]
Are compressed messages on the server formatted as JSON (I would hope so)? If so, how would I be able to send the score along with the JSON string that includes the name to where I could access the decompressed data client side with leaderboard[position].score?
P.S. I know how to do this client side, I just need to know if its possible.

**Comment by MastaCoder** [comment]
Hey there!

This is the issues section of MultiOgar-Edited. Only issues and feature-requests are to be put here. We do not support questions about programming a custom function in. The code is pretty documented with comments, and is provided as-is. If you require support for this project please contact someone with experience that is willing to help.

Enjoy!

**Comment by chewydev** [comment]
I appreciate the reply, sorry @MastaCoder. I had seen people asking questions on how do things so i'd thought I ask myself.
