### ISSUE TITLE
help me Console-plus

### ISSUE THREAD

**Issue by caleconman** [Megabyte918/MultiOgar-Edited#934]
Help me : 
http://i.imgur.com/d287ia1.png

**Comment by chewydev** [comment]
Try waiting more than .1 seconds to get the image url, so its not a blob lmao. At least check that...

**Comment by SAV-404** [comment]
hah LOL

**Comment by suprix** [comment]
1. Make webhost or run it on localhost.
2. In consoleplus.js put IP of VPS or 127.0.0.1 if you're running server on localhost
3. Check console plus.html and do same if you need.
It should work :)

**Comment by plazo123** [comment]
@caleconman wow

duplicae 

but il tell you open cmd
right cd and copy file loctaion of mltiogar run past after cd then enter then do node console-plus.js  
then go to 127.0.0.1@:1234
 
make sure you dont start the start.bat file !

and join your server through 
http://plazo.esy.es/test2/
and put pary token this
ws://e127.0.0.1:443
and play

**Comment by MastaCoder** [comment]
It needs to be on Apache, Nginx or any webserver host. You can simply run it off your disk.
