### ISSUE TITLE
Popsplits

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#935]
What are the codes to make popsplits easier on multiogar editied?
What lines do I have to change

**Comment by AlexHGaming** [comment]
Umm...
1. Check the wiki
2. Duplicated like SO MANY TIMES
3. There is no code to make "easier pops"

**Comment by imnotNxhz1** [comment]
this   https://pastebin.com/raw/GxkN6Btz

**Comment by AlexHGaming** [comment]
@imnotNxhz1 That is my virus code, but idc that you posted it lol

**Comment by imnotNxhz1** [comment]
@AlexHGaming   i only  share  because work for me xD

**Comment by gyeyoqu** [comment]
that code is worse

**Comment by koda** [comment]
@imnotNxhz1 What lines have you changed?
