### ISSUE TITLE
Save the last winner on the top

### ISSUE THREAD

**Issue by Wair1o17** [Megabyte918/MultiOgar-Edited#936]
How save the top 1?

**Comment by suprix** [comment]
Not sure, but I think its client sided.
@Megabyte918 what do you think?

**Comment by Wair1o17** [comment]
not client sided

**Comment by gyeyoqu** [comment]
@Wair1o17 you can do with client side, the first index when you draw the positions in the leaderboard

**Comment by MastaCoder** [comment]
This is not client sided to save number 1, but I don't know what you mean by save, put it in a variable?

**Comment by MastaCoder** [comment]
Hey there!

This is the issues section of MultiOgar-Edited. Only issues and feature-requests are to be put here. We do not support questions about programming a custom function in. The code is pretty documented with comments, and is provided as-is. If you require support for this project please contact someone with experience that is willing to help.

Enjoy!

**Comment by gyeyoqu** [comment]
@Wair1o17  you can with client sided, when you are iterating the positions, you only get the first
