### ISSUE TITLE
Cellcraft Powerups & Cell Design

### ISSUE THREAD

**Issue by suprix** [Megabyte918/MultiOgar-Edited#937]
allright, I just want to ask 2 things...
1st Is it possible to make "powerups" in javascript like in cellcraft.io and how?
2nd How can I change design of my cell? 
Example instead circle, to make triangle?

**Comment by Wair1o17** [comment]
draw a triangle is client sided

**Comment by suprix** [comment]
@Wair1o17 dm me on discord.

**Comment by SAV-404** [comment]
you can actually use some extensions look like powerups..i've got some but they are not working correctly..the cell does not following my mouse ..skins are not working ..the extension works just on privete server..i did not fix theme cz i'm making my own..if you need it just tell me

**Comment by AlexHGaming** [comment]
Client sided. 2 issues open already client sided 😠 
@Megabyte918 close.

**Comment by MastaCoder** [comment]
Hey there!

This is the issues section of MultiOgar-Edited. Only issues and feature-requests are to be put here. We do not support questions about programming a custom function in. The code is pretty documented with comments, and is provided as-is. If you require support for this project please contact someone with experience that is willing to help.

Enjoy!
