### ISSUE TITLE
How to do, NOT to apply forbidden words in minions?

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#938]
I think that

`if (!this.socket.playerTracker.isMi && this.gameServer.checkBadWord(name))`

but im wrong

**Comment by AlexHGaming** [comment]
`forbidden words in minions`
ummmmmmmm what

**Comment by MastaCoder** [comment]
Hey there!

This is the issues section of MultiOgar-Edited. Only issues and feature-requests are to be put here. We do not support questions about programming a custom function in. The code is pretty documented with comments, and is provided as-is. If you require support for this project please contact someone with experience that is willing to help.

Enjoy!

**Comment by plazo123** [comment]
@MastaCoder like you 💯 🥇
