### ISSUE TITLE
Can you change the background ?

### ISSUE THREAD

**Issue by EarthAgar** [Megabyte918/MultiOgar-Edited#939]
Hey i was was wondering if you could change the normal grid to this: http://agario.dk/img/mini-map.png
thro multiogar edited ? the main reason i want to know is because i have a agario website: http://ultimateagar.tk/ and i want to make it easier to find teamates and stuff lol. also if its not but somone knows html could you help me out with this that would be amazing thank you i hope this dosnt get emediatly closed lol andd i have not found a single issue like this so ya thanks !!!!!!!!!! 

Email Me to get to me faster : isaiahgrandon@gmail.com

**Comment by gyeyoqu** [comment]
Sorry, but is client side..

**Comment by EarthAgar** [comment]
so u mean i have to do it thro th desplay of my website ? and if thats what u mean do u know how plz?

**Comment by AlexHGaming** [comment]
Client sided.

**Comment by hossem123** [comment]
Just replace body tag with this: 
<body background="http://agario.dk/img/mini-map.png">

**Comment by AlexHGaming** [comment]
with what?

**Comment by hossemThecoder** [comment]
@AlexHGaming with this
```html
<body background="bgimage.jpg">
```

**Comment by AlexHGaming** [comment]
How is it going to be rendered?

**Comment by hossemThecoder** [comment]
No this background for the canvas like overlay

**Comment by AlexHGaming** [comment]
It's a javascript file.

**Comment by AlexHGaming** [comment]
The client is what makes the html, the server is what sends the packets to connect to it.
This is client sided, you do this by changing the background on the client, end of.

**Comment by Luka967** [comment]
@hossemThecoder The game canvas will either draw over or under the image. You need to draw the image *in* the canvas, and as Alex pointed out it's done by Javascript.

**Comment by hossemThecoder** [comment]
```js
drawBackground(ctx) {
    var mainCanvas = document.getElementById("canvas");
    var ctx = mainCanvas.getContext("2d") 
	var background = new Image;
	background.src = "http://agar.tn/img/aga.png";
	var size = ~~(canvas.width / 2);
	ctx.drawImage(background, 0, 0, size, size);
} drawBackground(ctx);
```
may something like this, this will render image on canvas .

**Comment by hossemThecoder** [comment]
```js
drawBackground(ctx) {
    var mainCanvas = document.getElementById("canvas");
    var ctx = mainCanvas.getContext("2d") 
	var background = new Image;
	background.src = "http://agar.tn/img/aga.png";
	var size = ~~(canvas.width / 2);
	ctx.drawImage(background, 0, 0, size, size);
} drawBackground(ctx);
```
may something like this, this will render image on canvas . @AlexHGaming @Luka967

**Comment by hossemThecoder** [comment]
```js
drawBackground(ctx) {
    var mainCanvas = document.getElementById("canvas");
    var ctx = mainCanvas.getContext("2d") 
	var background = new Image;
	background.src = "http://website.com/background.png";
	var size = ~~(canvas.width / 2);
	ctx.drawImage(background, 0, 0, size, size);
} drawBackground(ctx);
```
may something like this, this will render image on canvas .

**Comment by hossemThecoder** [comment]
```js
drawBackground(ctx) {
    var mainCanvas = document.getElementById("canvas");
    var ctx = mainCanvas.getContext("2d") 
	var background = new Image;
	background.src = "http://www/background.png";
	var size = ~~(canvas.width / 2);
	ctx.drawImage(background, 0, 0, size, size);
} drawBackground(ctx);
```
something like this , this will draw a background on canvas . @AlexHGaming  @Luka967
