### ISSUE TITLE
invalid i think so 

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#940]
this is of topic and if @Megabyte918  askes me to close i will

i added setTimeout(function(){process.exit(1);}, 361001000)
to gameservfer.js it wokrs fine :)

but how can i make the server in chat say restarting and on board i will close if @Megabyte918 

askes if this is oftopic :)

**Comment by AlexHGaming** [comment]
`Hey there!

This is the issues section of MultiOgar-Edited. Only issues and feature-requests are to be put here. We do not support questions about programming a custom function in. The code is pretty documented with comments, and is provided as-is. If you require support for this project please contact someone with experience that is willing to help.

Enjoy!`
@MastaCoder 2017

**Comment by pabloalber84** [comment]
And if I'm not mistaken, this is duplicate issue.
To the owner of topic:
You need to do it yourself, only need make a simple timer, but, no one who does this kind of topics know about timer's of what?

**Comment by AlexHGaming** [comment]
And I just actually looked at the comment. You don't understand how fucking triggered i get when i see `auto-restart` all the fuckin time.
https://help.github.com/articles/searching-issues/ refer to this, im unsubscribing from the issue as its all i say. I wish I could give you all the dupes, but there are WAY too many.

**Comment by plazo123** [comment]
@AlexHGaming 
not auto restar i have added my self withouot asking you xd

im asking after some time how can i triger the board to say somthing and im sorry

**Comment by plazo123** [comment]
triger auro matic

**Comment by FantasyIsBae** [comment]
@plazo123 Listen to @AlexHGaming

**Comment by plazo123** [comment]
@FantasyIsBae @AlexHGaming im sorry for that anyway  :)
