### ISSUE TITLE
Gaver.io ultrasplit

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#941]
What are the settings for gaver.io ultrasplit please thank you

**Comment by plazo123** [comment]
hmm

okay change the player spliy velocity to 400 thank you

**Comment by plazo123** [comment]
duplivcate please search your issue before making it please @koda

**Comment by plazo123** [comment]
Close pls mookan @FantasyIsBae

**Comment by plazo123** [comment]
@koda i may give yu an try tho here http://plazo.esy.es/test2

**Comment by Wair1o17** [comment]
get Ogar https://github.com/OgarProject/Ogar and test it ^^ close now

**Comment by AlexHGaming** [comment]
@MastaCoder @Megabyte918 @FantasyIsBae close.

**Comment by DeadLord1337** [comment]
duplicate

**Comment by Mr-BrockLee** [comment]
Yoo, how

**Comment by Mr-BrockLee** [comment]
Yo how did you got agarplus client @koda 
Where can i find it

**Comment by plazo123** [comment]
@Mr-BrockLee its not his its mine and i am not willing to give you

**Comment by imnotNxhz1** [comment]
@Mr-BrockLee  the client --- https://files.fm/u/pxwptssy

**Comment by MastaCoder** [comment]
Please don't share files of other websites. It's against their copyright laws.
