### ISSUE TITLE
i have bnot found an issue like this

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#942]
how can i put so the minion are the megabyte bot  you use so like player name bot

and the server minions give name

**Comment by MastaCoder** [comment]
Hey there!

This is the issues section of MultiOgar-Edited. Only issues and feature-requests are to be put here. We do not support questions about programming a custom function in. The code is pretty documented with comments, and is provided as-is. If you require support for this project please contact someone with experience that is willing to help.

Enjoy!

**Comment by plazo123** [comment]
@MastaCoder 
okay
you have this in a txt fie 
Hey there!

This is the issues section of MultiOgar-Edited. Only issues and feature-requests are to be put here. We do not support questions about programming a custom function in. The code is pretty documented with comments, and is provided as-is. If you require support for this project please contact someone with experience that is willing to help.

Enjoy!
