### ISSUE TITLE
Simple's thing's to fix [Gamemodes]

### ISSUE THREAD

**Issue by pabloalber84** [Megabyte918/MultiOgar-Edited#943]
In gamemode "Rainbow" has been adapted to multiogar, right, but, since the original version of multiogar from Barbosik, he add one require entity without reason:
`var Food = require('../entity/Food');`
Line 2 from Rainbow.js

Same in gamemode "Experimental", but with logger module:
`var Logger = require('../modules/Logger');`
Line 3 from Experimental.js

This not been used, why not simple remove?

**Comment by AlexHGaming** [comment]
Why not actually make a real issue? Or maybe a PR?

**Comment by pabloalber84** [comment]
@AlexHGaming is a simple thing's, dont needed make a PR to detect.

**Comment by Wair1o17** [comment]
and for Hunger Games on MultiOgar Barbosik's fork?

**Comment by pabloalber84** [comment]
@Wair1o17 I do not understand what you want to say...

**Comment by Wair1o17** [comment]
It is possible to solve "Hunger Games" of original MultiOgar


[Click Here](https://github.com/Barbosik/MultiOgar/blob/master/src/gamemodes/HungerGames.js)

**Comment by pabloalber84** [comment]
@Wair1o17 the problem from the original Multiogar Hunger Games gamemode, is the positions and leaderboard, the leaderboard is so easy to fix, the positions not, you need do it, or made a function to make a circle around from one point of center, and controllate the radius to put all food an player's spawns.

**Comment by pabloalber84** [comment]
I want to close this, I made a Pull Request already.

**Comment by Wair1o17** [comment]
Thanks @pabloalber84
