### ISSUE TITLE
Command "ban" to Playercommand.js

### ISSUE THREAD

**Issue by Wair1o17** [Megabyte918/MultiOgar-Edited#944]
title

I've tried copying and pasting from commandlist.js, but no luck yet.

**Comment by pabloalber84** [comment]
I made for you:
[https://pastebin.com/raw/4CUQdYR3](url)
Im already tested.

**Comment by Wair1o17** [comment]
Thanks

**Comment by Wair1o17** [comment]
Don't work

**Comment by pabloalber84** [comment]
Send the error.

**Comment by Wair1o17** [comment]
http://i.imgur.com/ZiRFYqD.png

**Comment by pabloalber84** [comment]
Where you put the functions? Remember, I say in the pastebin script, where are going to put the functions (Final of script)

**Comment by Wair1o17** [comment]
Yes, I followed them in order.

**Comment by pabloalber84** [comment]
Show where you put the two script's.

**Comment by MastaCoder** [comment]
Hey there!

This is the issues section of MultiOgar-Edited. Only issues and feature-requests are to be put here. We do not support questions about programming a custom function in. The code is pretty documented with comments, and is provided as-is. If you require support for this project please contact someone with experience that is willing to help.

Enjoy!

**Comment by AlexHGaming** [comment]
@MastaCoder lmfao stop

**Comment by Wair1o17** [comment]
@MastaCoder lol, i stop ok.

**Comment by ArixProject** [comment]
@Shair17 lol you put to PlayerCommands :DD
