### ISSUE TITLE
How can I use MultiOgar-Edited 1.6.1 in Blob.io?

### ISSUE THREAD

**Issue by Developer123452000** [Megabyte918/MultiOgar-Edited#948]
Help Me Please

**Comment by mafiakb** [comment]
u have vps or dedicated? 
only need node js and install npm

**Comment by Developer123452000** [comment]
I have a vps but when I try to get into my server I get a error "Minions"

**Comment by mafiakb** [comment]
any capture?

**Comment by AlexHGaming** [comment]
Client sided.
@MastaCoder @Megabyte918 @FantasyIsBae close.

**Comment by Gigabyte918** [comment]
not Client Sided i have edited Multi-Ogar which runs on Blob.io Mobile

**Comment by AlexHGaming** [comment]
@Gigabyte918 What do you think client sided means?
`blob.io`
yeah totally not a client

**Comment by Gigabyte918** [comment]
Blob.io is App for Mobile which run Multi Ogar server the old barbosik's one

**Comment by Gigabyte918** [comment]
@Developer123452000 do you have FB i can contact to you so i can give you blob.io server!

**Comment by Valdex** [comment]
@Gigabyte918 can give me server for blob
