### ISSUE TITLE
playerRecombineTime = 1

### ISSUE THREAD

**Issue by mafiakb** [Megabyte918/MultiOgar-Edited#95]
playerRecombineTime = 1? no working

**Comment by NameYT** [comment]
its playerRecombineTime = 0 :) Close this issue pls

**Comment by mafiakb** [comment]
need recombine time 1, don't 0

**Comment by Megabyte918** [comment]
@mafiakb Quote from Barbosik:

> For instant merge, just set playerRecombineTime to 0
Otherwise, playerRecombineTime defines minimum limit for recombine time.
Actual time depends on the cell mass.
>
> It works exactly the same as on vanilla servers.
>
> Don't confuse it with Ogar's recombineTime.
In MultiOgar, actual recombineTime depends on a cell mass and cell age.

**Comment by NameYT** [comment]
@Megabyte918 r u adding pellet mode

**Comment by Megabyte918** [comment]
@NameYT I don't know.
