### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#950]
Is there any client which runs multiogar edited besides Agar.io Client because Astr.io Client isnt working i want a smooth client because agar.io is more laggyer

**Comment by AlexHGaming** [comment]
client
sided
please
actually
make
an 
issue
that
is
something
to 
do
with
the
project
k
thanks

**Comment by AlexHGaming** [comment]
http://nbk.io/

**Comment by FantasyIsBae** [comment]
@Gigabyte918 Use gaver.io.
Go to console and use this command: 
```JS
setCurrentServer("ws://yourip:port");
```

**Comment by Wair1o17** [comment]
or wair.io

**Comment by chewydev** [comment]
@Gigabyte918 Just use https://github.com/CigarProject/Cigar.

**Comment by gyeyoqu** [comment]
@Gigabyte918  use http://ogar.pw

in the chat /connect ip 

is soo smooth that game

**Comment by Gigabyte918** [comment]
So Many Client which one hehe!~RIP~
