### ISSUE TITLE
How the hell do I do this?

### ISSUE THREAD

**Issue by FaZeCumshot** [Megabyte918/MultiOgar-Edited#951]
I know absolutely nothing about code. I have run the win-install_Dep, and no node module thing popped up. Can someone give me like a complete walk through on how to do this? I have absolutely no knowledge of coding. I would really appreciate it.

**Comment by chewydev** [comment]
You don't really need to know how to code if yu're not making any internal modifications to the server.
Reply if you are using Windows or Linux.

**Comment by AlexHGaming** [comment]
Well then.
1. You do not need to code just to open a server
2a. If you are windows, install deps and run the server
2b. If you are Linux, please check the main menu of this repo for further instructions,
3. Verify your node.js installation.
4. Nice name
