### ISSUE TITLE
From da potato

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#952]
Whats the site?
to play da game fam... :) 
I tho you guys were ganna make ur own website but im not sure..

**Comment by pabloalber84** [comment]
You need to do own client or search any client and modify.
This are client side.

**Comment by raphyjb** [comment]
Well yes ogarul.io was one site that we could play on pretty much all :)

**Comment by pabloalber84** [comment]
@raphyjb but ogarul.io:
1.- Are closed.
2.- They sell licenses to put online one server.
3.- Are closed.
4.- Have different protocol.

**Comment by raphyjb** [comment]
Can u list me some sites that works with ogar?

**Comment by gyeyoqu** [comment]
@raphyjb  For people shit like you, this project is dead, read the whore rules to ask a question son of a bitch

**Comment by raphyjb** [comment]
Fuck you dude only reason this project got open was cuz of legitsoulja and david so kys.
Reason why Ogarul.io was popular was cuz of me
So fuck you @gyeyoqu

**Comment by AlexHGaming** [comment]
@FantasyIsBae locked and limited conversation to collaborators

**Comment by gyeyoqu** [comment]
@raphyjb Shut up son of a bitch, you do not even know how to create code, asshole

**Comment by pabloalber84** [comment]
@raphyjb MultiOgar-Edited not are from Ogarul.io project (Death project, this too), dont fight.

@gyeyoqu Stop saying bullshit to new scripters/users, we were all new once.

**Comment by AlexHGaming** [comment]
@pabloalber84 puts it better than I would do.
