### ISSUE TITLE
connecting and i have logged out

### ISSUE THREAD

**Issue by nickhazswag** [Megabyte918/MultiOgar-Edited#953]
**BEFORE POSTING NEW ISSUE READ THIS**: You will find below few points, that you must follow or provide required info to. If you are not going to provide what we need in format we require your issue will be closed instantly without explanation. Spam is treated with fire.

Helpful checklist:

- [x] You have checked [prev issues](https://github.com/Megabyte918/MultiOgar-Edited/issues?q=is%3Aissue+is%3Aclosed) first and you didn't found answer for your problem (if there is something similar put reference links)
- [x] You are using and you have tested the latest version of MultiOgar.
- [x] Issue is in English.
- [x] Issue is not off-topic, and is related to the project.
- [ ] You have provided below good description of the error, making sure it is something we can reproduce.
- [ ] You have provided logs if there is crashing happening.

[Tutorial of how to format text on github](https://guides.github.com/features/mastering-markdown/), to make your issue not only readable but clean and neat

------------

*HERE GOES YOUR ISSUE DESCRIPTION*
I have been trying but it keeps on connecting and never finishes, please help i have client opened and cmd and i have tried incontogo and nothing happens, please help???? i have used the link and still nothing. please help me?

**Comment by pabloalber84** [comment]
You are sure than you connect to correct IP?

**Comment by AlexHGaming** [comment]
Let's run through some tests:
`1.` Are you connecting to the correct port? If so:
`1a.` Try connecting through another client.
`2.` Make sure the IP is linked to whatever your hoster is, in which this case, you're CMD so it is either localhost or 127. 
`3.` If non work of the above, try downloading a new clean copy.
