### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by ExobyteZOfficial** [Megabyte918/MultiOgar-Edited#955]
-=-=-=-=-=-=-=-
1. How can i see the minions in the leaderboard (new version 1.6.1)
2. How can i make minion's collect pellets in 10 ticks
3. is it possible to make the minions counted as friends?
-=-=-=-=-=-=-=-

**Comment by Wair1o17** [comment]
@ExobyteZOfficial 
1- Duplicate.
2- Duplicate.
3- No, Client sided.

**Comment by pabloalber84** [comment]
1.- #586 (Duplicated).
2.- Collect pellets system dont are currently working, made yourself.
3.- No, because don't have fisic account, can be detect in gameserver to friends, but in the game not, is client sided if you request.

**Comment by ExobyteZOfficial** [comment]
@Wair1o17 @pabloalber84 3. Can be added lol i fixed yellow rings but i f0rg0t the code to add the minions to it :3

**Comment by ExobyteZOfficial** [comment]
@pabloalber84 1. dont work just freeze the cell

**Comment by AlexHGaming** [comment]
@Wair1o17, you stole my idea of commenting that xD
And for the sake of god, stop asking the same thing over and over again.

**Comment by pabloalber84** [comment]
@ExobyteZOfficial you don't have idea to put in the correct line from PlayerTracker and from your gamemode config leaderboard.
