### ISSUE TITLE
LAN game not connecting anymore.

### ISSUE THREAD

**Issue by LennyMcLennington** [Megabyte918/MultiOgar-Edited#956]
I was just playing with 2 computers on a LAN game then it suddenly disconnected and won't connect anymore.
I used a port checker and it said my port was open and it detected a service running.
It shows that he is connected in console but it will show "connecting" for him
![Screen](http://i.imgur.com/AI1Ivcm.png)

**Comment by pabloalber84** [comment]
If you connect LAN game: Use your own local ip (No localhost), send Screenshot about the game in your other PC.

**Comment by LennyMcLennington** [comment]
I used my local IP to connect from the other computer which was 192.168.1.5.

**Comment by pabloalber84** [comment]
You open your firewall ports LAN? Try disable firewall..

**Comment by LennyMcLennington** [comment]
I have my ports open dude and other game servers with the same port works fine.

**Comment by LennyMcLennington** [comment]
I will try disabling the firewall.

**Comment by pabloalber84** [comment]
@LennyMcLennington Im no't speak so much english :B I try to help you, I get criticized in my english -.-.

**Comment by chewydev** [comment]
If you connect over LAN, it shouldn't matter if you ports are open, since your LAN IP isn't your external IP. I suggest finding a port that isn't being used by another application, which is probably the issue.

**Comment by FantasyIsBae** [comment]
Unanswered, closing.
Refer to @chewydev if anything.
