### ISSUE TITLE
the name of the bots as a player

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#957]
Hi, Megabyte. As in the file BotLoader.js in the value name to change the name of the player + a BOT? Was trying to do, but not without success. Asking for your help. Explain to the bots take the name of the player.

**Comment by pabloalber84** [comment]
[https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/BotLoader.js#L72]
Change to `s.packetHandler.setNickname(owner._name);`

**Comment by Geson777** [comment]
Don't Work, bots spawn without name!!!

@pabloalber84 @pabloalber84

**Comment by AlexHGaming** [comment]
This has been duplicated many times.

**Comment by gyeyoqu** [comment]
@pabloalber84  wrong.

@Geson777 

delete the lines 68-71 in src/ai/botLoader.js

and in https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L338

change: 

`this.bots.addMinion(ws.playerTracker);`

to:

`this.bots.addMinion(ws.playerTracker, ws.playerTracker._name);`

**Comment by pabloalber84** [comment]
@gyeyoqu is the same thing, but in other place -.-

**Comment by gyeyoqu** [comment]
@pabloalber84 nope, because the https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/BotLoader.js#L68

will evaluate name as undefined, and will set defaultName.

**Comment by pabloalber84** [comment]
@gyeyoqu no, if you put the name before the condition, this load the owner name.

**Comment by gyeyoqu** [comment]
@pabloalber84  You never told him that

**Comment by pabloalber84** [comment]
@gyeyoqu 
> https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/BotLoader.js#L72
Change to s.packetHandler.setNickname(owner._name);

Im use reference and I specify where to change it

**Comment by fayizan** [comment]
Tried changing the code but it remains unnamed cell

**Comment by gyeyoqu** [comment]
@fayizan follow my steps

**Comment by fayizan** [comment]
I did follow but still unnamed cells

![screenshot_184](https://user-images.githubusercontent.com/19163419/27819161-869f1b28-60b6-11e7-85ff-5e7a807fd8d3.png)

**Comment by fayizan** [comment]
@gyeyoqu

**Comment by gyeyoqu** [comment]
@fayizan Show me what you edited

**Comment by fayizan** [comment]
I did this step 
`
delete the lines 68-71 in src/ai/botLoader.js

and in https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L338

change:

this.bots.addMinion(ws.playerTracker);

to:

this.bots.addMinion(ws.playerTracker, ws.playerTracker._name);`

**Comment by fayizan** [comment]
@gyeyoqu ?
