### ISSUE TITLE
Private server or real server ?...

### ISSUE THREAD

**Issue by duwayy** [Megabyte918/MultiOgar-Edited#959]
Hello all,
First of all, I know this is not directly related to Multiogar, BUT
Recently, I noticed raga.pw reopened, with a new chrome extention (https://chrome.google.com/webstore/detail/raga-minions/cajlfianhckdhhdcfiopmnobmgbecdbe), giving 10 free bots. Their extension add a new "game mode", called "raga", which allow to use their bots. No bots in FFa, party etc but only in "raga" mode.

The point I'm very curious to know is what is that raga mode ! I first thought of a kind of private agario server, like Multiogar, but the thing is that Facebook connect works with it.. skins also works the same way that the original client !
I noticed food on the map differs than current agario foods, which makes me think it's not the original agario...

Can someone help me figuring what is that ?

**Comment by TopoR1** [comment]
Raga redid the server MultiOgar for themselves. They made terms, which is checked, authorised user or not. Well, servers are connected to their database.

**Comment by duwayy** [comment]
How is it possible for them to use original agar.io Facebook connect and skins in their private server ?

**Comment by pabloalber84** [comment]
@duwayy get's your login information, and get skin, etc, and disable the autodisable when the user join to private server, and all.
Raga Mode is a fucking fraud of "minions".

**Comment by duwayy** [comment]
So you mean it's possible to implement facebook mass and visible skins in Multiogar?

**Comment by ZfsrGhS953** [comment]
@duwayy You can look at its code [here](https://pastebin.com/raw/9VtniCCv). (it's not obfuscated)

**Comment by freaky767** [comment]
@ZfsrGhS953 how do you make the code work in normal private servers?

**Comment by pabloalber84** [comment]
The code says than he get the activa_skin from the localstorage, this is a vulnerability, because ppl can change the value and easy get own skin.

**Comment by FantasyIsBae** [comment]
Client sided sorry @duwayy

**Comment by fayizan** [comment]
![screenshot_169](https://user-images.githubusercontent.com/19163419/27863386-8aa08b48-61a7-11e7-9c3d-8b408fa7f473.png)

@duwayy @TopoR1
