### ISSUE TITLE
Last Man Standing Bug!!

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#96]
When i put or change the console to **# 

> `serverGamemode = 5`

**

no leaderboard no score fix

**Comment by systemroot** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L29
this is wrong or you.
btw as i have test. LMS work with 4.

**Comment by RelTakeover** [comment]
same error

**Comment by Tyler3D** [comment]
@systemroot That seems to be the case. But, I'm wondering. HOW DA HELL did the Server work cause there's no gamemode 5

**Comment by Megabyte918** [comment]
The leaderboard works fine for me.

**Comment by Tyler3D** [comment]
@Megabyte918 Same

**Comment by AlexandriteErikParacelsus** [comment]
lmao same here
