### ISSUE TITLE
ServerMinions problem

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#960]
Hello

How to make serverMinions started to work after I start playing, but not when I go to a server?

**Comment by pabloalber84** [comment]
Add in gamemode, to, when player connect, add minions from him.

**Comment by gyeyoqu** [comment]
You should THINK, what you ask, how would the server know, who owns the minion?

@MastaCoder close this :-1:

**Comment by ZfsrGhS953** [comment]
@gyeyoqu All right... If the server doesn't know who owns the minions, how does the server know where to move them to?

**Comment by AlexHGaming** [comment]
I am laughing so hard what @gyeyoqu just said
