### ISSUE TITLE
Slowdown the game speed

### ISSUE THREAD

**Issue by ElPigianerJone** [Megabyte918/MultiOgar-Edited#962]
I want to slow down the game for the best splitrunning with the minions
Is it impossible?

**Comment by gyeyoqu** [comment]
@ElPigianerJone  you can do 3 different things:

1) in gameServer.ini change 'splitVelocity' to a minor value
2) in gameServer.js find: 

`var r1 = push * m.cell.radius / rt;`

and multiply for a floating-point number, while smaller will be slower.

3) in GameServer.js find '`var timeStep = 40; // vanilla: 40`' , and change to a minor value

**Comment by ZfsrGhS953** [comment]
@gyeyoqu 
1. That will decrease the split distance (and speed), cells will still move at normal speed. And after the split cooldown, cells will get pushed at normal speed.
2. That will make cells softer which will make the splitting slower, but the cell movement will occur at normal speed.
3. That will make the entire game **faster**, not slower

**Comment by gyeyoqu** [comment]
@ZfsrGhS953 

3) was a major value , im wrong xd

**Comment by ZfsrGhS953** [comment]
@gyeyoqu How does having some parts of the game being slow and others being fast help? It only causes confusion.

**Comment by gyeyoqu** [comment]
@ZfsrGhS953  and what is your idea for make better splitrun?

**Comment by ElPigianerJone** [comment]
But I want to keep the split distance, do "1" make split distance become so little

**Comment by AlexHGaming** [comment]
@gyeyoqu You mean the lower the value, the _faster_ it is.
The more higher, the more slower.

**Comment by Gigabyte918** [comment]
increase the number of timeloop to make game slower
