### ISSUE TITLE
ServerMinions 

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#963]
Hello!

How to make serverMinions run after a certain time, for example, 10 seconds?

**Comment by pabloalber84** [comment]
Make a timer when the player connect, like:
`setTimeout(function() {
  // Your code minions join.
}, 10*1000);`
in code https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L335, but if you need do it only for a gamemode, you need made in onPlayerInit protoype of the gamemode, and change the serverMinions value to 0.

**Comment by TopoR1** [comment]
@pabloalber84 Error, don't work :(
![image](https://user-images.githubusercontent.com/19995663/27808220-18715628-604f-11e7-9910-030f44f509d3.png)
![image](https://user-images.githubusercontent.com/19995663/27808233-28ab8824-604f-11e7-8de8-ff54fa204de1.png)

**Comment by pabloalber84** [comment]
@TopoR1 You have the config serverMinions in your gameserver.ini? set to 0, like:
`serverMinions = 0`

**Comment by TopoR1** [comment]
@pabloalber84 Yes, there is. Even if you change the value to 0, the error still does not disappear

**Comment by pabloalber84** [comment]
Is so strange......

**Comment by plazo123** [comment]
@TopoR1 please do not make issues on other multiogar versions you are using Tyler3D
multiogars :)
