### ISSUE TITLE
Make pellets look smaller but have the same mass

### ISSUE THREAD

**Issue by MineMooreALT** [Megabyte918/MultiOgar-Edited#964]
I want the pellets to be smaller but then when you eat them you gain ~8 mass instead of 2-4 but still have the same size. Hopefully not to complicated!

**Comment by pabloalber84** [comment]
Change entity code.

**Comment by AlexHGaming** [comment]
@pabloalber84 He is asking the exact code to change it, not asking where it is located.
Unless @MineMooreALT could do it himself.

**Comment by MineMooreALT** [comment]
Yes i'm not 100% sure where the size of the pellet is located

**Comment by fayizan** [comment]
@MineMooreALT  I guess You can change the size of food pellets in https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L798

**Comment by MineMooreALT** [comment]
and if i change it will they still get the same mass for eg i set it to pellets = 100mass then i go and change the size in gameserver to 10 they will still get 100 mass?

**Comment by plazo123** [comment]
@MineMooreALT change the pellet grow from 1 to 0

**Comment by gyeyoqu** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/642

**Comment by MineMooreALT** [comment]
I didn't close it for a reason. My issue had still not been resolved, the code in that other issue is old.

**Comment by Megabyte918** [comment]
@MineMooreALT UpdateNodes.js (appearance):
```js
// Search for this line:

writer.writeUInt16(node._size >>> 0);

// Replace each of them with this:

writer.writeUInt16(node.cellType == 1 ? newSize : node._size >>> 0);
```
Replace `newSize` with the size you want. For example to make them look 2x smaller you would replace it with `node._size / 2`

Cell.js (size gained):
```js
// Search for this line:

this.setSize(Math.sqrt(this._sizeSquared + prey._sizeSquared));

// Replace it with this:

this.setSize(Math.sqrt(this._sizeSquared + (prey.cellType == 1 ? newSize : prey._sizeSquared)));
```
Replace `newSize` with the size you want. For example to double the size you gain you would replace it with `prey._sizeSquared * 2`
