### ISSUE TITLE
Change LB

### ISSUE THREAD

**Issue by MineMooreALT** [Megabyte918/MultiOgar-Edited#965]
How do I change the leaderboard via gameserver.js? thank you

**Comment by pabloalber84** [comment]
Check the command `board` from console, you can call with CommandList.js .
`var leaderboardtext = "bla bla blah";
var Commands = require('./modules/CommandList');
var execute = Commands.list['board'](gameServer, leaderboardtext);`

**Comment by MineMooreALT** [comment]
I will test it out thanks

**Comment by MineMooreALT** [comment]
gameServer Undefined

**Comment by MineMooreALT** [comment]
![image](https://user-images.githubusercontent.com/19501596/27815314-c585e11a-60b5-11e7-969a-bd47018ae43f.png)

**Comment by pabloalber84** [comment]
replace gameServer for the gameServer reference variables -.-

**Comment by MineMooreALT** [comment]
Can you explain more I don't really understand how this game server variable works

**Comment by plazo123** [comment]
@pabloalber84 where do you put ths code ?

**Comment by plazo123** [comment]
@pabloalber84 thnx it work but if i put some ilke blah blah or anyb thing its on board like this
r
s
t
a
r
t

**Comment by plazo123** [comment]
i want like restartnot..

**Comment by MineMooreALT** [comment]
Plazo where did you put the code ?

**Comment by pabloalber84** [comment]
@MineMooreALT you need learn about javascript and nodejs, if you get error in gameServer call, is because you don't put the gameServer module variable correctly.
@plazo123 One per piece of array/object of leaderboard.

**Comment by MineMooreALT** [comment]
Do i put the code in commandlist.js ?

**Comment by plazo123** [comment]
@MineMooreALT see discord 👍

**Comment by plazo123** [comment]
@pabloalber84 how canido so its  not one per peace      object leader board

**Comment by MineMooreALT** [comment]
![image](https://user-images.githubusercontent.com/19501596/27901922-6c34a24c-6266-11e7-950b-d3ffdd40947e.png)
![image](https://user-images.githubusercontent.com/19501596/27901954-876a99cc-6266-11e7-9bcf-2325d5c04173.png)

**Comment by MineMooreALT** [comment]
solution use a array
eg `var leaderboardtext = ["useless", "restart"];`
