### ISSUE TITLE
6 the Protocol does not work random skins <r> nickname

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#966]
Hello

Faced with the problem. If you simply write <r> without a nickname, the skins are working, but if you write <r> with a nickname, the skins do not work and only displays their name in the game, and in the top of my screen name. How to fix the problem?
![image](https://user-images.githubusercontent.com/19995663/27833858-2ff2282a-60dd-11e7-8fe0-cede2722f409.png)
![image](https://user-images.githubusercontent.com/19995663/27833872-3c510604-60dd-11e7-958d-84f3f3a864d0.png)
![image](https://user-images.githubusercontent.com/19995663/27833882-4639e000-60dd-11e7-8c54-9368ca699e03.png)
![image](https://user-images.githubusercontent.com/19995663/27833890-57689376-60dd-11e7-8053-dfe441359b42.png)

**Comment by ZfsrGhS953** [comment]
@Megabyte918 @MastaCoder Client-sided.

**Comment by fayizan** [comment]
@TopoR1 The client you are using is broken which needs to be updated

**Comment by AlexHGaming** [comment]
Client sided, please actually report something to do with the project
@Megabyte918 @MastaCoder @FantasyIsBae close.

**Comment by TopoR1** [comment]
@fayizan and how to fix it?

**Comment by gyeyoqu** [comment]
@TopoR1 probs your regular expression that find the skin string
