### ISSUE TITLE
The AI don't know when to split

### ISSUE THREAD

**Issue by logicalatomical** [Megabyte918/MultiOgar-Edited#967]
Take this shit down and I will embarass your ass so hard man I swear, fix the fucking AI before I make my own edited version and make a video on how lazy retards are to make these bots randomly split around and fail to splitrun as an excuse as how they do not know how to split. I have an older version that has better fucking AI and I will use that version to show how fucking retarded you are. All I know is that Pablo dickhead is going to shut this down with whatever little english he knows and try to make an excuse as to why they cannot update the AI. For the third time. Fix the AI or this whole thing will go on video and I will have people make their own versions leaving this shit to rot. Fucking delicate scum you are.

**Comment by logicalatomical** [comment]
I have 735 active subs on youtube so I will have a big enough voice to do this if you ever fucking underestimate me!

**Comment by plazo123** [comment]
@logicalatomical please dont make isseus like this we do not suport costom code and bs so please go some where else and if im wrong ask easy and ai are a should be gone anyway use minions

**Comment by logicalatomical** [comment]
fuck off bro, the ai add something to play against otherwise your server would be useless. I am about to make offline private servers into a thing now. And my fans would like some damn ai or bots to play against. Be my guest and remove the ai all you want. Then you can go ahead and watch me upload my own version with an ai. Lets see whos versions people will be getting then.... hmm?

**Comment by logicalatomical** [comment]
like honesty what the fuck am I going to be playing for if there is no bots? you guys are actually insane ffs.

**Comment by gyeyoqu** [comment]
@logicalatomical 

Create your own code, and if you want them not to be lazy, then pay them, they've done enough for free, asshole

**Comment by AlexHGaming** [comment]
@logicalatomical Well:
Having 735 subs on YouTube doesn't even fucking matter, not if you were on a million.
that `rant video` will probably only get 30 views.
We can't really properly program the bots to achknowledge when to split.
So how about you shut the fuck up and actually understand that 1 - 2 people took time into making this project **FOR FREE**. If you were to actually make your own version, then if u know how to program bots, why won't you make a PR on this project to help the bots _your way_.

> Take this shit down

It's a free project, it is not paid u twat.  What would be the point of us having it if we have so many users not using it. in which this case, we are getting people enjoying the server alongside with making videos with it, including myself.

> make a video on how lazy retards are to make these bots randomly split around and fail to splitrun as an excuse 

How can bots just splitrun? How can they link a connection between others? 

> Fix the AI or this whole thing will go on video

THIS THING WILL GO ON VIDEO. OH SHIT. WE ARE GOING TO GET EXPOSED BY LIKE LITTLE VIEWERS

`fix the ai`

How about if you do it.

> And my fans

Alright then. Like they would give a flying shit in the first place.

> like honesty what the fuck am I going to be playing for if there is no bots? 

Well, here at MultiOgar-Edited, it isn't only **JUST** bots that matter the most. There are minions, console control alongside with playing with people that use your hosted server.
@FantasyIsBae @MastaCoder @Megabyte918 close this, this is so bullshit.
And those questions are rhetorical btw.

**Comment by FantasyIsBae** [comment]
@logicalatomical 

I have deleted one of your comments , as you are proving yourself to be quite ignorant and childish. 
Your first comment has been edited as i thought of it to be INVALID. 
Stop making pointless issues showing off off how many subs you have , i couldn't give less of a shit about it.

**I have no words no point even responding @AlexHGaming ❤️ said everything already , i haven't seen not much fame get to someone so quick**

**Comment by plazo123** [comment]
@FantasyIsBae GG 👍

**Comment by MineMooreALT** [comment]
What a fucking fag so selfish and thinks 735 subs is enough to brag about, Toxic
