### ISSUE TITLE
better AI

### ISSUE THREAD

**Issue by logicalatomical** [Megabyte918/MultiOgar-Edited#969]
MAKE BETTER AI YOU LAZY FUCK

**Comment by logicalatomical** [comment]
I will keep fucking doing this until it happens I don't give two shits

**Comment by Luka967** [comment]
Toxic kids like you killed the fun of games that we had earlier. We're not going to help you. Deal with it.

**Comment by FantasyIsBae** [comment]
Toxic kids like you killed the fun of games that we had earlier. We're not going to help you. Deal with it. [x2]

**Comment by AlexHGaming** [comment]
You mentioned earlier that you were going to make your own version. go on then.
