### ISSUE TITLE
add pm2 to the server

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#97]

**Comment by systemroot** [comment]
pm2 doesn't do what you think. i have test it!
that is for nothing.
if you want to clear ram etc then (talking for linux)
set up a cron job which run every 5min or 10 or whenever you what. with 

```
sudo sync; sudo echo 3 > /proc/sys/vm/drop_caches
```
if you want to restart server for some mins /h or whatever

```
npm install -g nodemon
```

then you can chose time for restart ex restart every 5min

```
nodemon --delay 300 index.js
```

that what pm2 do is ex if you have 4CPU pm2 will start your server 4 times.. which doesn't do anything about lag just will make lag more than is..

about windows. well just ask google. then you will found what you want example one which clear your pc, and ram/cpu is **pcfaster.com** or `advanced systemcare` (which i use!) :rocket:
