### ISSUE TITLE
auto restart

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#970]
auto restart  i need it :dango: haha just kiding
 #596 #527 #447 #458 #266 #141 #146 and #243

this may be clientsided but the multiogar code some one hereshould know about it realy i am not sure if issue or not
http://plazo.esy.es/test2/agarplus.js
i added  this to case 81 

and i got server sided chat connected but i could not play then   
here iwillshow  http://plazo.esy.es/test2/
try join a server and right click
client sided not sure
i have autorestart all ready

**Comment by plazo123** [comment]
and how cn i use set time out to after some time server will send a client message to that time over or somthing

**Comment by pabloalber84** [comment]
In english understandable?

**Comment by AlexHGaming** [comment]
Make sure client and server ports and URLs are linked together.
Try getting a new server and try put URL and port to the client
If that doesn't work, it is a problem with your client.
If you are trying to make auto restart, but the server isn't working like it would have before, I recommend you verify your code.

> and how cn i use set time out to after some time server will send a client message 

Use setTimeout on the chat launch messages function and add the code at the bottom of serverWelcome2, or at the end of such function. Please feel free to respond to this if you need help / experiening problems or my solutions didn't help.

**Comment by plazo123** [comment]
i have auto restart fine with board restart aswell im askin how to i ment to say do /command code what is it for agarplus to connnect
like /commdn not workin in my client plazo.esy.es/test2
im rly close as you can see

**Comment by plazo123** [comment]
@pabloalber84 ok simple see my client whats my error in console

**Comment by fayizan** [comment]
its agarplus script how you get it ?

**Comment by pabloalber84** [comment]
@plazo123 you say about connect errors?

**Comment by plazo123** [comment]
@pabloalber84 so iremoved it for know but uhm do you have skype or discord because im dont wanna send my files here :dagger: 
but forget about what isaid for now
but in my mywebsite warlist.tk how do you know code to coonect to server sided chat ?
like right now i cant do /command in my client becasue or even server  msg how will i connecttob     server sided chat   i dontind sending you the website files
@pabloalber84 expert :d:

**Comment by pabloalber84** [comment]
@plazo123 https://discord.gg/D5qKfu when I script, I passed here

**Comment by plazo123** [comment]
@AlexHGaming i am better i tryed before you no luckso i nmade issue xd
when u saw auto restart what did u think XD

**Comment by AlexHGaming** [comment]
I was about to give you the largest essay in the world @plazo123

**Comment by AlexHGaming** [comment]
Wait, this is **_CLICKBAIT_**

**Comment by pabloalber84** [comment]
@AlexHGaming what is the problem, in youtube most people use clickbait xdddd

**Comment by AlexHGaming** [comment]
@pabloalber84 Well we don't want it here.

**Comment by fayizan** [comment]
@pabloalber84  Comeon Discord  ?

**Comment by plazo123** [comment]
@AlexHGaming i had to make a laugh to make @AlexHGaming @MastaCoder @Megabyte918 happy of auto restarts :+1:

**Comment by plazo123** [comment]
my issue is how can i connect warlist.tk to server sided chat so i am able to do /commands and welcome msg
