### ISSUE TITLE
Issues :(

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#971]
## MultiOgar-Edited RIP? :(
And I want to say that the best version 1.5.0, I have it, even a pleasure to play on this version, the physics are 100% similar to the vanilla agar. IO (there's even one push split I made https://youtu.be/CNFOG6UuWhU?t=152) , I have made it better, made a new leaderboard Protocol 13, added "unshift" (well, when double split most large cells flies forward)

**Comment by AlexHGaming** [comment]
And this is an issue because?
And give the link to the standard 1.5.0 to the comments of this issue if you like :) .

**Comment by pabloalber84** [comment]
Unless issue if you only say your "work" and not the issue problem.

**Comment by DeadLord1337** [comment]
@AlexHGaming http://www.mediafire.com/file/d68ylim8evo9tw6/MultiOgar-Edited+1.5.0.zip 
give me moder moderator :В

**Comment by DeadLord1337** [comment]
@AlexHGaming http://www.mediafire.com/file/5895p4rvp44vvtv/MultiOgar-Edited-1.5.0.zip Treat I can give any version!!! (Give me moderator :В)
