### ISSUE TITLE
Extension-like clients

### ISSUE THREAD

**Issue by 2wiseguy** [Megabyte918/MultiOgar-Edited#974]
(This might not be entirely related to the project, but I don't know where else to ask.)
Since astr.io and xgario.ml have been shut down, are there any other clients that are styled like agarplus and other extensions?

**Comment by AlexHGaming** [comment]
Please don't ask this here.
@FantasyIsBae close this

**Comment by ExobyteZOfficial** [comment]
gey xd use nbk.io
