### ISSUE TITLE
pellet size

### ISSUE THREAD

**Issue by plazo123** [Megabyte918/MultiOgar-Edited#975]
ok edited again :D:  so multiogar works fine but in multiogar edited some pellets are bigger then others i need them to be same size

**Comment by AlexHGaming** [comment]
Please can you speak proper grammar so I can understand what is happening.
Trying to not offend :P

**Comment by pabloalber84** [comment]
W-h-a-t?

**Comment by Wair1o17** [comment]
client sided

**Comment by plazo123** [comment]
@AlexHGaming @pabloalber84 ok edited again :D: so multiogar works fine but in multiogar edited some pellets are bigger then others i need them to be same size

**Comment by pabloalber84** [comment]
@plazo123 all no, all food are from the same size, so, if you see different one than others, is client side bug/error/edit

**Comment by Agarian** [comment]
Pretty sure this is because of the food growth feature. In the config file (gameserver.ini), look for `foodMassGrow`, and set it to 0. That will fix the issue.

**Comment by plazo123** [comment]
@Agarian thanks i nevver thought that it would be that :( so i take my self as a noob :( http://warlist.tk/
