### ISSUE TITLE
Cell Color Changes by Using a Specific Name?

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#976]
Can i able to make that when i enter a like spy my color will turn white or any other color i want?

**Comment by FantasyIsBae** [comment]
Umm yes it is possible , i would do it on the client instead of the server.

**Comment by AlexHGaming** [comment]
This is client sided.
@FantasyIsBae Why did you not close this lmao

**Comment by AlexHGaming** [comment]
@Gigabyte918 Aere you using cigar client?

**Comment by FantasyIsBae** [comment]
@AlexHGaming It can be done on the server too

**Comment by AlexHGaming** [comment]
@FantasyIsBae It can not be done on the server. Name drawings and colours happen through the client, while the server recognises it.

**Comment by AlexHGaming** [comment]
Unless you can make protocol changes.

**Comment by FantasyIsBae** [comment]
@AlexHGaming The color can be detected in the name and recognized by the server.
For example if my name is **red** the server reads that and sets the color to that player.
Or if this is easier to understand
```JS
// Only an example of usage 
if (playerName == "red") {
    setColor{(
    r: 255,
    g: 0,
    b: 0
});
};
```

**Comment by AlexHGaming** [comment]
What is `setColor` going to be defined as though?

**Comment by AlexHGaming** [comment]
He is talking about coloured **NAMES** not **CELLS**

**Comment by AlexHGaming** [comment]
I will explain
In playertracker.js

```js
if(name == "spy") {
// Add source of code
}

**Comment by Wair1o17** [comment]
ummh that's cliend sided @FantasyIsBae Close this @AlexHGaming is right

**Comment by AlexHGaming** [comment]
In which that `add source of code` will need to be modified to your standard
We don't have coloured name track in the files.
And @Wair1o17 is right.

**Comment by Luka967** [comment]
@AlexHGaming Can be done on both sides although server-side is more favorable as it applies to all clients instead of just yours.
@Gigabyte918 Yes

**Comment by MastaCoder** [comment]
"Color by Name?"

I think he means color of cell. Color of the cell by name would be a better way to say it. He really never mentions name, so we don't know for sure. @Gigabyte918 Can you confirm?

**Comment by AlexHGaming** [comment]
I can't even read
I thought he said colour of name xD
But changing cell colour isn't recommended if you're using a skin :/

**Comment by AlexHGaming** [comment]
Unless you have cell outline

**Comment by Luka967** [comment]
Agar does it for a lot of skins xd

**Comment by MastaCoder** [comment]
:D I would recommend doing this on server. Then no matter what client connects to it, they'll see the same colour. (Chrome is telling me colour is spelt incorrectly. Why)

**Comment by Luka967** [comment]
Colour is British, color is American spelling
fkn empires

**Comment by AlexHGaming** [comment]
If you have a skin onto a cell, I'd don't understand why you would want to change your cell colour if it's covering the entire cell apart from the outline. If @Gigabyte918 wants to change the outline, then what impact would it make? Why would it really matter?

**Comment by AlexHGaming** [comment]
I am thinking @Gigabyte918 is wanting to change colour of names as it is the spy skin after all :D

**Comment by AlexHGaming** [comment]
That's what I thought anyways.

**Comment by Gigabyte918** [comment]
no beacause like agar mobile you color will change with skin but i am using cigar so color will change by name like i am using spy name this will give me spy skin with 12 random color so i want a color for spy to be changed by server not by client

**Comment by Gigabyte918** [comment]
#BAD #ENGLISH

**Comment by Gigabyte918** [comment]
can someone tells me how i can do that *TITLE*

**Comment by AlexHGaming** [comment]
I am literally confused with what you are saying.
I just read the title of this:  `color of name`
In which you are requesting to change the colour of name?

**Comment by Gigabyte918** [comment]
no name color i mean cell color change when you type a specific nick

**Comment by plazo123** [comment]
@AlexHGaming this can be done from the client or server for egample in cigar i can set the self  color from red to anycolor now its posable both ways but the client way is easer but if you want to add cient but leaderboard colour then server sided is better ::)

**Comment by Gigabyte918** [comment]
No Leaderboard color no name color only cell color change by using a specific nick

**Comment by plazo123** [comment]
@Gigabyte918 o.O ok from server side

**Comment by plazo123** [comment]
you ned toadd somthing like this if player_name gigabyte set color rec moudules/commandlist.js "color" rec  id somthing like this

**Comment by AlexHGaming** [comment]
Why would you need to change your cell colour if you have a skin covering it?

**Comment by AlexHGaming** [comment]
@plazo123 
Go to playertracker.js
Make a variable that requires the files that involves the cell colour changes (i cba to find it out)
Then do the following:
```js
if (name == "input name") {
this.**input cell colour code**; 
}

**Comment by AlexHGaming** [comment]
IK i am a shit "exampleist"
well im your english teacher now, and i can teach you how to use great grammar and spelling.

**Comment by Gigabyte918** [comment]
i cant understand what you are taking about can someone tell me how i can do that TITLE

**Comment by AlexHGaming** [comment]
You mean the title of this issue? `Color by Name`?

**Comment by AlexHGaming** [comment]
Please define `colour` in terms of either cell or name colour.

**Comment by plazo123** [comment]
@AlexHGaming he says cell color by name and i think il have code wait

**Comment by fayizan** [comment]
@AlexHGaming @plazo123 @Gigabyte918  he wants the specific color on cell by nick/skin name like in the agar.io

`{"cellColor":"0x7c000100","gameplayId":74,"image":"Evil.png","productId":"skin_evil","skinType":"premium"},{"cellColor":"0x00000000","gameplayId":75,"image":"Pirate.png","productId":"skin_pirate","skinType":"premium"},{"cellColor":"0x7c000100","gameplayId":76,"image":"evil_eye.png","productId":"skin_evileye","skinType":"premium"},{"cellColor":"0x7c000100","gameplayId":77,"image":"Halloween.png","productId":"skin_halloween","skinType":"premium"},{"cellColor":"0x7c000100","gameplayId":78,"image":"Monster.png","productId":"skin_monster","skinType":"premium"},{"cellColor":"0x83838300","gameplayId":79,"image":"Scarecrow.png","productId":"skin_scarecrow","skinType":"premium"},{"cellColor":"0x83838300","gameplayId":80,"image":"Spy.png","productId":"skin_spy","skinType":"premium"}`

**Comment by Gigabyte918** [comment]
@fayizan You are right

**Comment by gyeyoqu** [comment]
```
if (skin == 'some skin') node.color({

r: value,
g: value,
b: value

});
```

**Comment by Gigabyte918** [comment]
where do i add this code?

**Comment by AlexHGaming** [comment]
Playertracker.js.

**Comment by gyeyoqu** [comment]
in gameServer.js

**Comment by plazo123** [comment]
guys ik wat he wants

 var Commands = require('../modules/CommandList'); var execute = Commands.list['color'](gameServer,);
and code get player id of name

**Comment by AlexHGaming** [comment]
Alright alex, shut the fuck up, stop thinking giga wants a change of name colour.

**Comment by AlexHGaming** [comment]
You will need to require playertracker.js
```js
if (skin == "spy") {
this.cellcolor = setColor{(
    r:  0,
    g: 0, // put 255 on the color in the RGB section you'd like.
    b: 255
});

**Comment by gyeyoqu** [comment]
@AlexHGaming  nope you not know

**Comment by Gigabyte918** [comment]
Can someone Explain how to do this

**Comment by AlexHGaming** [comment]
You don't know how to speak fluent english bruh

**Comment by gyeyoqu** [comment]
@AlexHGaming i know 👍

**Comment by Gigabyte918** [comment]
where do i add this code
if (skin == "spy") {
this.cellcolor = setColor{(
    r:  0,
    g: 0, // put 255 on the color in the RGB section you'd like.
    b: 255
});

**Comment by Gigabyte918** [comment]
plz tell me how i can make player cell color change by using a specific nick

**Comment by fayizan** [comment]
Thanks gyeyoqu  working nice

**Comment by Gigabyte918** [comment]
@fayizan HOW?

**Comment by AlexHGaming** [comment]
@Gigabyte918 You add it in Playertracker.js in the joingame function.

**Comment by chewydev** [comment]
I have written a messenger server to where I can send messages back and forth between clients without interacting with MultiOgar, but that's for my own private use.

**Comment by Gigabyte918** [comment]
ok ill try

**Comment by Gigabyte918** [comment]
i got error can you make a tutorial on it plz

**Comment by chewydev** [comment]
@Gigabyte918 I could show you to do this, im working on a certain thing as well to keep my cells from drawing if i use a certain name, to make myself invisible.

**Comment by Megabyte918** [comment]
@Gigabyte918 Add this at the end of the `spawnPlayer()` function in GameServer.js:
```js
if (player._name == 'example') {
    cell.color = {
	r: val,
        g: val,
        b: val		
    };
}
```
Replace `val` with your desired RGB rating.

**Comment by Gigabyte918** [comment]
i tried but dosent work

**Comment by Megabyte918** [comment]
It works perfectly fine for me. Make sure you are placing it directly underneath the `player.mouse = new Vec2(pos.x, pos.y);` line and replace "example" with the name you want and you should be good to go.

**Comment by suprix** [comment]
@Megabyte918 is it possible to make instead of cell.color, to add like a password for locked name.
So if it's

 `if (player._name == 'example') {
     **code for setting password**
    };
}`

**Comment by AlexHGaming** [comment]
@suprix yet again, client sided.

**Comment by suprix** [comment]
@AlexHGaming I don't think so, it's possible to connect it with chat so to continue to the server, you have to type correct password.

**Comment by AlexHGaming** [comment]
@suprix How are you going to bring a message for entering a password?

**Comment by Agarian** [comment]
Most likely by the chat

**Comment by AlexHGaming** [comment]
Mhm, true.

**Comment by chewythepig** [comment]
You could also use `window.prompt` and send a request to an API that checks if the password is correct or not, preventing the password from being revealed to anyone that shouldn't know it.

**Comment by Agarian** [comment]
He's got a point there, I mean Ogar Unlimited used to do that (then again it's Ogar Unlimited so...).
