### ISSUE TITLE
E,R,T,P control

### ISSUE THREAD

**Issue by SAV-404** [Megabyte918/MultiOgar-Edited#977]
i actually made and extension to play in the privete server..and there is an issue when i use the ERTP control script.
-when i'm using the script in my extension : 
![2017-07-11_175314](https://user-images.githubusercontent.com/26459304/28079872-dcb97066-6661-11e7-8017-f6c98034859d.png)
-and when i'm not : 
![2017-07-11_175427](https://user-images.githubusercontent.com/26459304/28079909-0184906a-6662-11e7-9788-ca510e9ac534.png)

**Comment by pabloalber84** [comment]
Because ERTP control send direct the key with WebSocket directly.

**Comment by SAV-404** [comment]
@pabloalber84 and how to fix that???

**Comment by ArixProject** [comment]
privete server??? whaat????

**Comment by SAV-404** [comment]
@ArixProject  yes...extension of agarioV786 for privete server..cz the original agario is so laggy and ugly(i don't like it)...would you like to help me plz??

**Comment by SAV-404** [comment]
for f**k sake ..no one helps???

**Comment by SAV-404** [comment]
@FantasyIsBae

**Comment by Wair1o17** [comment]
Use older client
