### ISSUE TITLE
Client [Question]

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#978]
How come on the server through nbk.io (I know how to access the nbk.io/?ip127.0.0.1:443) what is the Protocol at nbk previously came and played, but right now the fuck
![55](https://user-images.githubusercontent.com/24901742/28173766-16762050-67f8-11e7-99a6-9419653c187d.PNG)

**Comment by DeadLord1337** [comment]
:с

**Comment by AlexHGaming** [comment]
And this has to do with the project because????
@MastaCoder @FantasyIsBae

**Comment by DeadLord1337** [comment]
ok I close my bad boy >:с AlexHGaming

**Comment by Wair1o17** [comment]
try wair.io

**Comment by DeadLord1337** [comment]
@Wair1o17 nope

**Comment by Agarian** [comment]
k
