### ISSUE TITLE
How?!

### ISSUE THREAD

**Issue by ExobyteZOfficial** [Megabyte918/MultiOgar-Edited#979]
I close this immideatlylylylylylylylylyly

1. Minion Collect Pellets 10 ticks or 5 seconds they stop and they collect pellets again
2. Show minions in da leaderboard (Latest Version) Need HELP

@AlexHGaming i close dis if i get answer lol

**Comment by AlexHGaming** [comment]
STOP FUCKING MAKING THE SAME ISSUES OVER AND OVER AGAIN. IT IS REALLY ANNOYING! (spam)
@FantasyIsBae @MastaCoder

**Comment by ExobyteZOfficial** [comment]
@AlexHGaming FUCKING ANSWER MY MOTHER FUCKING QUESTION U RETARD!!
THE OLD CODES YOU FUCKING SENT DOESN'T FUCKING WORK IN THE LATEST VERSION U FUCKING CUNT BITCH ASSHOLE FUCK

**Comment by AlexHGaming** [comment]
Calls me a retard when he can't solve his own question.
Honestly, why do you keep duplicating issues when on the first issue asking for this, you can ask there?

> OLD CODES YOU FUCKING SENT DOESN'T FUCKING WORK

`1.` Learn how to use grammar correctly.
`2.` I never sent you any piece of code about this.

> U FUCKING CUNT BITCH ASSHOLE FUCK

`1.` Grow up.
`2.` Does that even make any sense?
`3.` Are you trying to take that as a compliment?

Stop spamming duplicate issues on the repository.
